Repository dotnet/macios, pull requests merged in 2018-05, with the labels that each got.

#3058 [runtime] add support for mono runtime interpreter
  builds/Makefile
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  runtime/mono-runtime.h.t4
  tests/xharness/Jenkins.cs
  tests/xharness/ProjectFileExtensions.cs
  tools/common/Application.cs
  tools/mtouch/Application.cs
  tools/mtouch/Assembly.cs
  tools/mtouch/Target.cs
  tools/mtouch/mtouch.cs
Labels: enable-device-build, run-all-tests, skip-device-tests, skip-ios-device-tests

#4051 [mtouch] Take into account the contents of response files when determining whether the cache is valid or not. Fixes #4033. (#4032)
  tests/common/BundlerTest.cs
  tools/common/cache.cs
Labels: requires-approval-before-merge

#4050 [builds] Add a --disable-packaged-llvm configure option to enable building LLVM from source.
  builds/Makefile
  configure
Labels: enable-device-build

#4071 [d15-7] Fix default values for touchbar APIs in NSTextViewDelegate. (#3843)
  src/appkit.cs
Labels: macOS, requires-qa-before-merge

#4109 [msbuild] Unbreak netstd2 project msbuild support
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.TargetFrameworkFix.targets
Labels: macOS, run-mmp-tests, run-mtouch-tests

#4138 [jenkins] Improve api/generator diff reporting to say if there were changes, and if they were breaking or not.
  jenkins/compare.sh
Labels: do-not-merge, skip-all-tests

#3772 [Linker] Remove bundled mscorlib.xml descriptor from mmp and mtouch
  tools/linker/Descriptors/mscorlib.xml
  tools/mmp/Makefile
  tools/mmp/linker/Descriptors/mscorlib.xml
  tools/mmp/mmp.csproj
  tools/mtouch/Makefile
  tools/mtouch/mtouch.csproj
Labels: run-mmp-tests, run-mtouch-tests
