Repository dotnet/macios, pull requests merged in 2019-08, with the labels that each got.

#6697 [d16-3] [tests] wrench is long gone
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/CryptoTest.cs
Labels: not-notes-worthy

#6696 [xcode11] [tests] wrench is long gone
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/CryptoTest.cs
Labels: not-notes-worthy

#6698 [d16-2] [tests] wrench is long gone
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/CryptoTest.cs
Labels: not-notes-worthy, test-only-issue

#6712 [API Diff] Ignore the autogenerated projects until they are moved to their own dir.
  .gitignore
Labels: not-notes-worthy

#6713 [d16-3] [API Diff] Ignore the autogenerated projects until they are moved to their own dir.
  .gitignore
Labels: not-notes-worthy

#6714 [d16-2] [API Diff] Ignore the autogenerated projects until they are moved to their own dir.
  .gitignore
Labels: not-notes-worthy, test-only-issue

#6645 [xcode11] [VideoToolbox] bindings for beta 1-5
  src/VideoToolbox/VTCompressionProperties.cs
  src/videotoolbox.cs
  tests/xtro-sharpie/iOS-VideoToolbox.todo
  tests/xtro-sharpie/macOS-VideoToolbox.todo
  tests/xtro-sharpie/tvOS-VideoToolbox.todo
Labels: community, note-highlight

#6718 [AuthenticationServices] Update bindings to Xcode 11 Beta 5
  src/authenticationservices.cs
  tests/xtro-sharpie/iOS-AuthenticationServices.todo
  tests/xtro-sharpie/macOS-AuthenticationServices.todo
  tests/xtro-sharpie/tvOS-AuthenticationServices.todo
  tests/xtro-sharpie/watchOS-AuthenticationServices.todo
Labels: note-highlight

#6719 [PassKit] Update bindings to Xcode 11 Beta 5
  src/passkit.cs
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/watchOS-PassKit.todo
Labels: note-highlight

#6717 [UIKit] Update bindings to Xcode 11 Beta 5
  src/UIKit/UIEnums.cs
  src/uikit.cs
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-UIKit.todo
Labels: note-highlight

#6661 [mtouch/mmp] Don't write runtime-options.plist if it hasn't changed.
  src/ObjCRuntime/RuntimeOptions.cs
Labels: not-notes-worthy

#6689 Fix NLLanguageRecognizer crash
  src/NaturalLanguage/NLLanguageRecognizer.cs
  tests/monotouch-test/NaturalLanguage/NLLanguageRecognizerTest.cs
Labels: community, note-highlight

#6731 [coretext] Update for Xcode 11 beta 5
  src/CoreText/CTEnums.cs
  src/CoreText/CTFont.cs
  src/CoreText/CTFontManager.cs
  src/CoreText/CTGlyphInfo.cs
  src/coretext.cs
  tests/monotouch-test/CoreText/FontTest.cs
  tests/monotouch-test/CoreText/GlyphInfoTest.cs
  tests/xtro-sharpie/iOS-CoreText.todo
  tests/xtro-sharpie/macOS-CoreText.todo
  tests/xtro-sharpie/tvOS-CoreText.todo
  tests/xtro-sharpie/watchOS-CoreText.todo
Labels: enhancement

#6732 [xcode11] Fix NLLanguageRecognizer crash
  src/NaturalLanguage/NLLanguageRecognizer.cs
  tests/monotouch-test/NaturalLanguage/NLLanguageRecognizerTest.cs
Labels: bug, community

#6733 [mediaaccessibility] Update for Xcode 11 beta 5
  src/MediaAccessibility/MediaAccessibility.cs
  tests/monotouch-test/MediaAccessibility/CaptionAppearanceTest.cs
  tests/xtro-sharpie/iOS-MediaAccessibility.todo
  tests/xtro-sharpie/macOS-MediaAccessibility.todo
  tests/xtro-sharpie/tvOS-MediaAccessibility.todo
Labels: enhancement

#6736 [MediaToolbox] Remove non-unified (classic) version of MTAudioProcessingTap
  src/MediaToolbox/MTAudioProcessingTap-Unified.cs
  src/MediaToolbox/MTAudioProcessingTap.cs
  src/frameworks.sources
Labels: not-notes-worthy

#6710 [xcode11] [HomeKit] Bindings for HomeKit beta1 - beta5 - all platforms
  src/HomeKit/HMEnums.cs
  src/homekit.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/xtro-sharpie/iOS-HomeKit.todo
  tests/xtro-sharpie/tvOS-HomeKit.todo
  tests/xtro-sharpie/watchOS-HomeKit.todo
Labels: community, note-highlight

#6743 [pdfkit] Update for Xcode 11 beta 1
  src/pdfkit.cs
  tests/xtro-sharpie/iOS-PdfKit.todo
Labels: enhancement

#6744 [xcode11] Disable bcl tests
  tests/Makefile
Labels: not-notes-worthy

#6745 [photos][macos] Fix breaking changes for XM
  src/Photos/PHCompat.cs
  src/photos.cs
Labels: not-notes-worthy

#6746 [externalaccessory] Update for Xcode 11 beta 5
  src/externalaccessory.cs
  tests/xtro-sharpie/iOS-ExternalAccessory.todo
  tests/xtro-sharpie/macOS-ExternalAccessory.todo
  tests/xtro-sharpie/tvOS-ExternalAccessory.todo
Labels: enhancement

#6741 [naturallanguage] Update for Xcode 11 beta 1
  src/NaturalLanguage/Enums.cs
  src/NaturalLanguage/NLEmbedding.cs
  src/NaturalLanguage/NLStrongDictionary.cs
  src/NaturalLanguage/NLVectorDictionary.cs
  src/frameworks.sources
  src/naturallanguage.cs
  tests/monotouch-test/NaturalLanguage/EmbeddingTest.cs
  tests/monotouch-test/NaturalLanguage/GazetteerTest.cs
  tests/xtro-sharpie/iOS-NaturalLanguage.todo
  tests/xtro-sharpie/macOS-NaturalLanguage.todo
  tests/xtro-sharpie/tvOS-NaturalLanguage.todo
  tests/xtro-sharpie/watchOS-NaturalLanguage.todo
Labels: enhancement

#6752 [quartzcomposer] Update for Xcode 11 beta 1
  src/quartzcomposer.cs
  tests/xtro-sharpie/macOS-QuartzComposer.todo
Labels: enhancement, macOS

#6742 [d16-3] [linker] Always preserve INativeObject (interface) on types. Fixes #6711
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tools/linker/CoreMarkStep.cs
Labels: bug

#6754 [foundation] Update for Xcode 11 beta 5
  src/Security/SecureTransport.cs
  src/foundation.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/iOS-Foundation.todo
  tests/xtro-sharpie/iOS-Security.todo
  tests/xtro-sharpie/macOS-Foundation.todo
  tests/xtro-sharpie/macOS-Security.todo
  tests/xtro-sharpie/tvOS-Foundation.todo
  tests/xtro-sharpie/tvOS-Security.todo
  tests/xtro-sharpie/watchOS-Foundation.todo
  tests/xtro-sharpie/watchOS-Security.todo
Labels: enhancement

#6757 [jenkins] Don't trust brew to not fail when things are working fine.
  jenkins/prepare-packaged-macos-tests.sh
Labels: not-notes-worthy, run-internal-tests, skip-public-jenkins

#6763 [generator] Add support for [Native] enums inside [StrongDictionaries]
  src/generator.cs
  tests/generator/BGenTests.cs
  tests/generator/strong-dict-native-enum.cs
Labels: not-notes-worthy

#6722 Add correct casing for Microsoft.FSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.FSharp.targets
Labels: community, note-highlight

#6660 [tests][msbuild] Tweak the NativeReferencesNoEmbedding test to work with a locally built mtouch.
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/NativeReferencesNoEmbedding.cs
Labels: not-notes-worthy

#6759 [fileprovider[ui]] Update for Xcode 11 beta 1 to 5
  src/Constants.mac.cs.in
  src/fileprovider.cs
  src/fileproviderui.cs
  src/foundation.cs
  src/frameworks.sources
  src/uikit.cs
  tests/introspection/ApiProtocolTest.cs
  tests/xtro-sharpie/iOS-FileProvider.todo
  tests/xtro-sharpie/macOS-FileProvider.todo
  tests/xtro-sharpie/macOS-FileProviderUI.todo
  tools/common/Frameworks.cs
Labels: enhancement

#6760 [storekit] Update Xcode 11 beta 1 to 5
  src/storekit.cs
  tests/xtro-sharpie/iOS-StoreKit.ignore
  tests/xtro-sharpie/iOS-StoreKit.todo
  tests/xtro-sharpie/macOS-StoreKit.ignore
  tests/xtro-sharpie/macOS-StoreKit.todo
  tests/xtro-sharpie/tvOS-StoreKit.todo
Labels: enhancement

#6751 [xcode11] [EventKit] bindings for all platforms
  src/EventKit/EKEnums.cs
  src/eventkit.cs
  tests/xtro-sharpie/iOS-EventKit.todo
  tests/xtro-sharpie/macOS-EventKit.todo
  tests/xtro-sharpie/watchOS-EventKit.todo
Labels: community, note-highlight

#6767 [safariservices] Update for Xcode 11 beta 1 to 5
  src/ObjCRuntime/PlatformAvailability2.cs
  src/SafariServices/SSEnums.cs
  src/safariservices.cs
  tests/xtro-sharpie/macOS-SafariServices.todo
Labels: enhancement

#6503 [xcode11] Remove the WatchKit framework from iOS while keeping API stability. Fixes #6492.
  docs/website/mmp-errors.md
  docs/website/mtouch-errors.md
  src/Foundation/NSError.cs
  src/WatchKit/WKDefs.cs
  src/WatchKit/WKInterfaceController.cs
  src/WatchKit/WKInterfaceDevice.cs
  src/WatchKit/iOS/WKAccessibility.cs
  src/WatchKit/iOS/WKAccessibilityImageRegion.cs
  src/WatchKit/iOS/WKErrorCode.cs
  src/WatchKit/iOS/WKImageAnimatable.cs
  src/WatchKit/iOS/WKInterfaceButton.cs
  src/WatchKit/iOS/WKInterfaceController.cs
  src/WatchKit/iOS/WKInterfaceDate.cs
  src/WatchKit/iOS/WKInterfaceDevice.cs
  src/WatchKit/iOS/WKInterfaceGroup.cs
  src/WatchKit/iOS/WKInterfaceImage.cs
  src/WatchKit/iOS/WKInterfaceLabel.cs
  src/WatchKit/iOS/WKInterfaceMap.cs
  src/WatchKit/iOS/WKInterfaceMapPinColor.cs
  src/WatchKit/iOS/WKInterfaceObject.cs
  src/WatchKit/iOS/WKInterfaceSeparator.cs
  src/WatchKit/iOS/WKInterfaceSlider.cs
  src/WatchKit/iOS/WKInterfaceSwitch.cs
  src/WatchKit/iOS/WKInterfaceTable.cs
  src/WatchKit/iOS/WKInterfaceTimer.cs
  src/WatchKit/iOS/WKMenuItemIcon.cs
  src/WatchKit/iOS/WKTextInputMode.cs
  src/WatchKit/iOS/WKUserNotificationInterfaceController.cs
  src/WatchKit/iOS/WKUserNotificationInterfaceType.cs
  src/foundation.cs
  src/frameworks.sources
  src/watchkit.cs
  tests/common/ExecutionHelper.cs
  tests/generator/sof20696157.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/ApiFieldTest.cs
  tests/introspection/ApiFrameworkTest.cs
  tests/xtro-sharpie/EnumCheck.cs
  tests/xtro-sharpie/iOS-WatchKit.ignore
  tests/xtro-sharpie/iOS-WatchKit.todo
  tests/xtro-sharpie/iOS-WebKit.ignore
  tests/xtro-sharpie/macOS-Foundation.ignore
  tests/xtro-sharpie/watchOS-GameKit.ignore
  tools/common/Frameworks.cs
  tools/common/StaticRegistrar.cs
  tools/common/Target.cs
  tools/mtouch/Makefile
Labels: note-highlight

#6768 [eventkit] Obsolete `EKReminder` default constructor
  src/EventKit/EventKit.cs
  src/eventkit.cs
  tests/introspection/iOS/iOSApiCtorInitTest.cs
Labels: note-deprecation

#6769 The watchOS 3.2 simulator is now functional again, so let's use it.
  Make.config
Labels: not-notes-worthy

#6771 [contactsui] Update for Xcode 11 beta 1 to 5
  src/uikit.cs
Labels: enhancement

#6772 [macos][imagekit] Update for Xcode 11 beta 1
  src/ImageKit/Enums.cs
Labels: enhancement

#6773 [gamekit] Update for Xcode 11 beta 1 to 5
  src/GameKit/GameKit.cs
  src/gamekit.cs
  tests/xtro-sharpie/iOS-GameKit.todo
  tests/xtro-sharpie/macOS-GameKit.todo
  tests/xtro-sharpie/tvOS-GameKit.ignore
  tests/xtro-sharpie/tvOS-GameKit.todo
  tests/xtro-sharpie/watchOS-GameKit.todo
Labels: enhancement

#6774 [executionpolicy] Update for Xcode 11 beta 1
  src/Constants.mac.cs.in
  src/executionpolicy.cs
  src/frameworks.sources
  tests/xtro-sharpie/macOS-ExecutionPolicy.todo
  tools/common/Frameworks.cs
Labels: enhancement

#6776 [tests][xtro] Fix reported failure for SFSafariServicesVersion on macOS
  tests/xtro-sharpie/macOS-SafariServices.ignore
Labels: not-notes-worthy

#6779 [corewlan][macos] Update for Xcode 11 beta 1
  src/CoreWlan/Enums.cs
  src/frameworks.sources
  tests/xtro-sharpie/macOS-CoreWLAN.ignore
Labels: enhancement, macOS

#6780 [iad] Update for Xcode beta 1 to 5
  src/iad.cs
  tests/xtro-sharpie/iOS-iAd.todo
Labels: enhancement

#6784 [CoreML] Update bindings to Xcode 11 Beta 1 - 5
  src/coreml.cs
  tests/xtro-sharpie/iOS-CoreML.todo
  tests/xtro-sharpie/macOS-CoreML.todo
  tests/xtro-sharpie/tvOS-CoreML.todo
  tests/xtro-sharpie/watchOS-CoreML.ignore
  tests/xtro-sharpie/watchOS-CoreML.todo
Labels: note-highlight

#6789 [quicklookthumbnailing] Update for Xcode11 beta 1 to 5
  src/Constants.iOS.cs.in
  src/Constants.mac.cs.in
  src/frameworks.sources
  src/quicklook.cs
  src/quicklookthumbnailing.cs
  tests/xtro-sharpie/iOS-QuickLookThumbnailing.todo
  tests/xtro-sharpie/macOS-QuickLookThumbnailing.todo
  tools/common/Frameworks.cs
Labels: enhancement

#6803 [replaykit] Update for Xcode 11 beta 6
  src/ReplayKit/RPEnums.cs
Labels: enhancement

#6804 [authenticationservices] Update for Xcode 11 beta 6
  src/authenticationservices.cs
Labels: enhancement

#6805 [linker] Fix NRE when System.Linq.Queryable is used. Fix #6346
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tools/linker/MobileMarkStep.cs
Labels: bug

#6810 [docs] Make our documentation gender neutral
  docs/website/binding_objc_libs.md
  docs/website/binding_types_reference_guide.md
Labels: note-highlight

#6807 [UIKit] Update bindings to Xcode 11 Beta 6
  src/uikit.cs
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.todo
Labels: note-highlight

#6806 [tests] Adjust expected result of looking for 'mono_native_initialize'. Fixes xamarin/maccore#1809.
  tests/mono-native/Introspection.cs
Labels: not-notes-worthy

#6819 [authenticationservices] Remove [Abstract] from ASAuthorizationPasswordRequest. Fix #6816
  src/authenticationservices.cs
Labels: bug

#6821 [tests] Fix MTouch's LinkerWarnings test for Xcode 11 beta 6
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#6823 [monotouch-test] Fix PinAnnotationViewTest's InitWithFrame
  tests/monotouch-test/MapKit/PinAnnotationViewTest.cs
Labels: not-notes-worthy

#6822 [CoreVideo] Update framework for Xcode 11 beta 6.
  src/CoreVideo/CoreVideo.cs
  src/corevideo.cs
  tests/xtro-sharpie/iOS-CoreVideo.todo
  tests/xtro-sharpie/macOS-CoreVideo.todo
  tests/xtro-sharpie/tvOS-CoreVideo.todo
Labels: note-highlight

#6829 [generator] Handle subclasses of NSObject as ref/out parameters in third-party libraries. Fixes #6828.
  src/generator.cs
  tests/generator/BGenTests.cs
  tests/generator/generator-tests.csproj
  tests/generator/tests/vsts-970507.cs
Labels: bug

#6847 [generator] Handle subclasses of NSObject as ref/out parameters in third-party libraries. Fixes #6828. (#6829)
  src/generator.cs
  tests/generator/BGenTests.cs
  tests/generator/generator-tests.csproj
  tests/generator/tests/vsts-970507.cs
Labels: bug

#6848 Add a dummy x86_64 slice to all our native libraries that don't have one.
  builds/.gitignore
  builds/Makefile
  runtime/.gitignore
  runtime/Makefile
  tests/common/ProductTests.cs
  tools/common/MachO.cs
  tools/mtouch/Application.cs
Labels: not-notes-worthy

#6850 [registrar] Fix verification of generic parameters to accept unrelated generic types. Fixes #6687.
  src/ObjCRuntime/DynamicRegistrar.cs
  tests/monotouch-test/ObjCRuntime/Messaging.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: bug

#6874 [network][watchos] Enable Network.framework for watchOS (new in 6.0)
  src/Constants.watch.cs.in
  src/Network/NWAdvertiseDescriptor.cs
  src/Network/NWConnection.cs
  src/Network/NWContentContext.cs
  src/Network/NWEndpoint.cs
  src/Network/NWError.cs
  src/Network/NWInterface.cs
  src/Network/NWListener.cs
  src/Network/NWParameters.cs
  src/Network/NWPath.cs
  src/Network/NWPathMonitor.cs
  src/Network/NWProtocolDefinition.cs
  src/Network/NWProtocolMetadata.cs
  src/Network/NWProtocolOptions.cs
  src/Network/NWProtocolStack.cs
  src/frameworks.sources
  src/network.cs
  tests/xtro-sharpie/watchOS-Network.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#6867 [security] Partial updates for Xcode 11 (up to beta 7)
  src/Security/Enums.cs
  src/Security/Items.cs
  src/Security/SecAccessControl.cs
  src/Security/SecIdentity2.cs
  src/Security/SecProtocolMetadata.cs
  src/Security/SecProtocolOptions.cs
  src/Security/SecTrust.cs
  src/Security/SecureTransport.cs
  src/Security/SslConnection.cs
  src/Security/SslContext.cs
  src/security.cs
  tests/monotouch-test/Security/IdentityTest.cs
  tests/monotouch-test/Security/ProtocolOptionsTest.cs
  tests/monotouch-test/Security/SecProtocolMetadataTest.cs
  tests/monotouch-test/Security/SecStatusCodeTest.cs
  tests/monotouch-test/Security/TrustTest.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/common-Security.ignore
  tests/xtro-sharpie/iOS-Security.todo
  tests/xtro-sharpie/macOS-Security.ignore
  tests/xtro-sharpie/macOS-Security.todo
  tests/xtro-sharpie/tvOS-Security.todo
  tests/xtro-sharpie/watchOS-Security.todo
Labels: enhancement

#6858 [CoreMedia] Add support up to Xcode beta 7.
  src/CoreMedia/CMSync.cs
  tests/xtro-sharpie/iOS-CoreMedia.todo
  tests/xtro-sharpie/macOS-CoreMedia.todo
  tests/xtro-sharpie/tvOS-CoreMedia.todo
  tests/xtro-sharpie/watchOS-CoreMedia.todo
Labels: note-highlight

#6871 Instruction to find the build logs
  ISSUE_TEMPLATE.md
Labels: skip-public-jenkins

#6864 Build native code with -std=c++14.
  Make.config
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/Extensions/PhotoEditing.cs
  runtime/Makefile
  tests/monotouch-test/Photos/LivePhotoEditingContextTest.cs
  tools/common/Driver.cs
  tools/common/StaticRegistrar.cs
  tools/mmp/Makefile
  tools/mmp/driver.cs
  tools/mtouch/BuildTasks.mtouch.cs
  tools/mtouch/Makefile
Labels: note-highlight

#6881 [generator] Fix CS1522 warning building generated bindings
  src/generator-enums.cs
Labels: not-notes-worthy

#6678 [Xcode11] [carplay] Updates for beta 5
  src/carplay.cs
  tests/xtro-sharpie/iOS-CarPlay.todo
Labels: enhancement

#6844 [VisionKit] Add Xcode 11 Beta 1 - 6 bindings
  src/Constants.iOS.cs.in
  src/ObjCRuntime/Class.cs
  src/frameworks.sources
  src/visionkit.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/iOS/iOSApiCtorInitTest.cs
  tests/xtro-sharpie/iOS-VisionKit.todo
  tools/common/Frameworks.cs
  tools/mtouch/Makefile
Labels: note-highlight

#6882 [watchkit] Update for Xcode 11 up to beta 7
  src/watchkit.cs
  tests/xtro-sharpie/watchOS-WatchKit.todo
Labels: enhancement

#6890 [tests] Change URL for UrlSessionTest.CreateDataTaskAsync
  tests/monotouch-test/Foundation/UrlSessionTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#6887 [foundation] Add support for NSValue/CGAffineTransform and StoreValueAtAddress overload
  runtime/monotouch-support.h
  runtime/xamarin-support.m
  src/Foundation/NSValue.cs
  src/foundation.cs
  tests/monotouch-test/CoreGraphics/AffineTransformTest.cs
  tests/xtro-sharpie/common-Foundation.ignore
Labels: not-notes-worthy
