Repository dotnet/macios, pull requests merged in 2019-02, with the labels that each got.

#5538 [tests] Use latest version of NUnit for test projects to get support for parallelized tests.
  tests/generator/generator-tests.csproj
  tests/generator/packages.config
  tests/mmptest/mmptest.csproj
  tests/mmptest/packages.config
  tests/msbuild-mac/msbuild-mac.csproj
  tests/msbuild-mac/packages.config
  tests/mtouch/mtouch.csproj
  tests/mtouch/packages.config
  tests/xharness/Jenkins.cs
Labels: skip-public-jenkins

#5572 [tests|mtouch] armv7 to arm64 in a couple of device build tests
  tests/mtouch/MTouch.cs
Labels: skip-public-jenkins

#5577 [tests|mmp] Bump mmp's WarningTests to use Xcode 9.4
  tests/common/Configuration.cs
  tests/mmptest/src/WarningTests.cs
Labels: skip-public-jenkins

#5575 [msbuild] Fixes NativeExecutable MTouch output prop for VS
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: requires-approval-before-merge

#5578 Bump maccore to get ruby fix.
  mk/xamarin.mk
Labels: build-package, run-internal-tests, skip-public-jenkins

#5570 [Maccore] Bump maccore to pick up some ci fixes.
  mk/xamarin.mk
Labels: build-package, run-internal-tests

#5584 Bump maccore to get ruby fix.
  mk/xamarin.mk
Labels: build-package, run-internal-tests, skip-public-jenkins

#5585 [d15-9] Bump maccore to get mlaunch fix.
  mk/xamarin.mk
Labels: build-package, requires-approval-before-merge, run-internal-tests, skip-public-jenkins

#5586 [d16-0] Bump maccore to get mlaunch fix.
  mk/xamarin.mk
Labels: build-package, requires-approval-before-merge, run-internal-tests, skip-public-jenkins

#5681 [Tests] Fix failing mtouch tests after bcl test were removed.
  tests/mtouch/MTouch.cs
Labels: run-mtouch-tests

#5676 [XHarness] Remove not longer needed .csproj on the bcl tests.
  tests/bcl-test/Mono.CSharp/Info.plist
  tests/bcl-test/Mono.CSharp/Mono.CSharp.csproj.template
  tests/bcl-test/Mono.Data.Tds/Info-mac.plist
  tests/bcl-test/Mono.Data.Tds/Info.plist
  tests/bcl-test/Mono.Data.Tds/Makefile
  tests/bcl-test/Mono.Data.Tds/Mono.Data.Tds-mac.csproj.template
  tests/bcl-test/Mono.Data.Tds/Mono.Data.Tds.csproj.template
  tests/bcl-test/Mono.Security/Info-mac.plist
  tests/bcl-test/Mono.Security/Info.plist
  tests/bcl-test/Mono.Security/Makefile
  tests/bcl-test/Mono.Security/Mono.Security-mac.csproj.template
  tests/bcl-test/Mono.Security/Mono.Security.csproj.template
  tests/bcl-test/System.ComponentModel.DataAnnotations/Info-mac.plist
  tests/bcl-test/System.ComponentModel.DataAnnotations/Info.plist
  tests/bcl-test/System.ComponentModel.DataAnnotations/Makefile
  tests/bcl-test/System.ComponentModel.DataAnnotations/System.ComponentModel.DataAnnotations-mac.csproj.template
  tests/bcl-test/System.ComponentModel.DataAnnotations/System.ComponentModel.DataAnnotations.csproj.template
  tests/bcl-test/System.Core/Info.plist
  tests/bcl-test/System.Core/System.Core.csproj.template
  tests/bcl-test/System.Json/Info-mac.plist
  tests/bcl-test/System.Json/Info.plist
  tests/bcl-test/System.Json/Makefile
  tests/bcl-test/System.Json/System.Json-mac.csproj.template
  tests/bcl-test/System.Json/System.Json.csproj.template
  tests/bcl-test/System.Net.Http/Info-mac.plist
  tests/bcl-test/System.Net.Http/System.Net.Http-mac.csproj.template
  tests/bcl-test/System.Numerics/Info-mac.plist
  tests/bcl-test/System.Numerics/Info.plist
  tests/bcl-test/System.Numerics/Makefile
  tests/bcl-test/System.Numerics/System.Numerics-mac.csproj.template
  tests/bcl-test/System.Numerics/System.Numerics.csproj.template
  tests/bcl-test/System.Runtime.Serialization/Info.plist
  tests/bcl-test/System.Runtime.Serialization/System.Runtime.Serialization.csproj.template
  tests/bcl-test/System.Security/Info.plist
  tests/bcl-test/System.Security/System.Security.csproj.template
  tests/bcl-test/System.ServiceModel.Web/Info.plist
  tests/bcl-test/System.ServiceModel.Web/System.ServiceModel.Web.csproj.template
  tests/bcl-test/System.Transactions/Info.plist
  tests/bcl-test/System.Transactions/System.Transactions.csproj.template
  tests/bcl-test/System.Xml.Linq/Info-mac.plist
  tests/bcl-test/System.Xml.Linq/Info.plist
  tests/bcl-test/System.Xml.Linq/Makefile
  tests/bcl-test/System.Xml.Linq/System.Xml.Linq-mac.csproj.template
  tests/bcl-test/System.Xml.Linq/System.Xml.Linq.csproj.template
  tests/bcl-test/System/Info.plist
  tests/bcl-test/System/System.csproj.template
Labels: run-bcl-tests

#5666 [Tests] Fix the make rule that generate the test projects. Fixes #5638
  tests/bcl-test/BCLTests/Makefile
  tests/bcl-test/BCLTests/common-SystemCoreXunit.ignore
  tests/bcl-test/BCLTests/common-SystemWebServicesTests.ignore
  tests/bcl-test/BCLTests/iOS-MicrosoftCSharpXunit.ignore
  tests/bcl-test/BCLTests/tvOS-MicrosoftCSharpXunit.ignore
  tests/bcl-test/BCLTests/watchOS-MicrosoftCSharpXunit.ignore
  tools/bcl-test-importer/BCLTestImporter/ApplicationOptions.cs
  tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
  tools/bcl-test-importer/BCLTestImporter/Program.cs
Labels: run-bcl-tests

#5574 [XHarness] Ensure we do a nuget restore on bcl imported tests. Fixes #5383
  tests/bcl-test/BCLTests/BCLTests-mac.csproj.in
  tests/bcl-test/BCLTests/BCLTests-tv.csproj.in
  tests/bcl-test/BCLTests/BCLTests-watchos-extension.csproj.in
  tests/bcl-test/BCLTests/BCLTests.csproj
  tests/bcl-test/BCLTests/BCLTests.csproj.in
  tests/bcl-test/BCLTests/RegisterType.cs.in
  tests/bcl-test/BCLTests/packages.config
  tests/bcl-test/BCLTests/templates/macOS/MacTestMain.cs
  tests/xharness/BCLTestImporter/BCLTestImportTargetFactory.cs
  tests/xharness/Jenkins.cs
  tests/xharness/TestProject.cs
  tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
Labels: run-bcl-tests
