Repository dotnet/macios, pull requests merged in 2019-12, with the labels that each got.

#7516 [monotouch-test] Make NetworkReachabilityTest.CtorIPAddressPair a bit more permissive. Fixes xamarin/maccore#2047.
  tests/monotouch-test/SystemConfiguration/NetworkReachabilityTest.cs
Labels: not-notes-worthy

#7520 [d16-5] [monotouch-test] Make NetworkReachabilityTest.CtorIPAddressPair a bit more permissive. Fixes xamarin/maccore#2047.
  tests/monotouch-test/SystemConfiguration/NetworkReachabilityTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7505 [d16-5] [xharness] Add a timeout to the periodic command.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy

#7504 [xcode11.3] [xharness] Add a timeout to the periodic command.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7506 [xcode11.3] [xharness] Make sure to always stop log and system capture.
  tests/xharness/AppRunner.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7521 [xcode11.3] [monotouch-test] Make NetworkReachabilityTest.CtorIPAddressPair a bit more permissive. Fixes xamarin/maccore#2047.
  tests/monotouch-test/SystemConfiguration/NetworkReachabilityTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7508 [xibuild] Clean up temporary files when done.
  tools/xibuild/Main.cs
Labels: not-notes-worthy

#7503 [d16-5] [xharness] Make sure to always stop log and system capture.
  tests/xharness/AppRunner.cs
Labels: not-notes-worthy

#7543 Bump version number for d16.4 service release 1
  Make.versions
Labels: not-notes-worthy, skip-all-tests

#7192 Bump to mono:2019-10
  Make.config
  builds/Makefile
  mk/mono.mk
  runtime/monotouch-main.m
  src/CFNetwork/CFHTTPMessage.cs
  src/Foundation/NSUrlSessionHandler.cs
  src/System.Net.Http/CFContentStream.cs
  src/System.Net.Http/CFNetworkHandler.cs
  tests/bcl-test/common-monotouch_corlib_xunit-test.dll.ignore
  tests/bcl-test/macOSModern-xammac_net_4_5_System_xunit-test.dll.ignore
  tests/linker/ios/link sdk/HttpClientHandlerTest.cs
  tests/mmptest/src/MMPTest.cs
  tests/mmptest/src/WarningTests.cs
  tests/monotouch-test/Network/NWEstablishmentReportTest.cs
  tests/monotouch-test/Network/NWParametersTest.cs
  tests/monotouch-test/Network/NWProtocolIPOptionsTest.cs
  tests/monotouch-test/Network/NWProtocolStackTest.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
  tests/mtouch/MTouch.cs
  tests/mtouch/SdkTest.cs
  tools/linker/MobileSweepStep.cs
  tools/mmp/mmp.csproj
  tools/mtouch/mtouch.csproj
Labels: run-all-tests, run-internal-tests, skip-api-comparison, skip-device-tests

#7542 [monotouch-test] Improve MessageHandlerTest.TestNSUrlSessionHandlerCookies.
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
Labels: not-notes-worthy

#7544 [mtouch] Fix caching issues. Fix #7514
  tools/common/FileCopier.cs
  tools/common/cache.cs
Labels: bug

#7545 Use relative paths in scripts.
  docs/website/generator-errors.md
  src/Makefile.generator
  src/bgen
  src/btouch-native
  src/btouch.in
  src/btv
  src/bwatch
  tools/mtouch/Makefile
  tools/mtouch/mtouch
  tools/mtouch/mtouch.in
Labels: not-notes-worthy

#7548 [mtouch][mmp] Include satellite assemblies from nuget dependencies. Fix #7113
  tests/mmptest/src/PackageReferenceTests.cs
  tools/common/Assembly.cs
Labels: enhancement

#7573 [xcode11.3] Bump version number now that Xcode 11.3 is out
  Make.versions
Labels: not-notes-worthy, skip-all-tests

#7567 [introspection] Update according to changes that seem to have occurred in macOS 10.15.2.
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
Labels: run-internal-tests, skip-public-jenkins

#7546 [monotouch-test] Simplify NetworkReachabilityTest.CtorIPAddressPair test.
  tests/monotouch-test/SystemConfiguration/NetworkReachabilityTest.cs
Labels: not-notes-worthy, trigger-device-tests

#7583 [xharness] Don't try to parse log files that don't exist.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy

#7578 [d16-5] [introspection] Update according to changes that seem to have occurred in macOS 10.15.2.
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
Labels: not-notes-worthy

#7592 [xcode11.3] [introspection] Update according to changes that seem to have occurred in macOS 10.15.2.
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7599 [msbuild] Remove unused files.
  msbuild/Xamarin.MacDev.Tasks/Tasks/ACTool.cs
  msbuild/Xamarin.iOS.Tasks/Tasks/ValidateAppExtensionBundleIdentifiers.cs
  msbuild/Xamarin.iOS.Tasks/Tasks/ValidateWatchAppBundleIdentifiers.cs
Labels: not-notes-worthy

#7594 [msbuild] Update to latest ILRepack.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
  msbuild/Xamarin.Mac.Tasks/packages.config
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
  msbuild/Xamarin.iOS.Tasks/packages.config
Labels: not-notes-worthy

#7597 [msbuild] Update tests to NUnit 3.12.
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/CompileSceneKitAssetsTest.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/ReleaseBuild.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TargetTests/TargetTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/IBToolTaskTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/MTouchTaskTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
  msbuild/tests/Xamarin.iOS.Tasks.Tests/packages.config
  tests/Makefile
  tests/xharness/Jenkins.cs
  tools/nunit3-console-3.10.0
Labels: not-notes-worthy

#7613 [xcode11.3] [monotouch-test] Simplify NetworkReachabilityTest.CtorIPAddressPair test.
  tests/monotouch-test/SystemConfiguration/NetworkReachabilityTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7614 [xcode11.3] [xharness] Don't try to parse log files that don't exist.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7612 [Tests] Split groups so that they work on iOS 32b.
  .gitignore
  tests/xharness/UnifiedTarget.cs
  tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7610 [msbuild] Remove unused file.
  msbuild/tests/Bug60536/Assets.xcassets/AppIcon.appiconset/Contents.json~
Labels: not-notes-worthy

#7617 [xcode11.3] [Tests] Split groups so that they work on iOS 32b.
  .gitignore
  tests/xharness/UnifiedTarget.cs
  tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
Labels: not-notes-worthy, pr-change-not-shipping, requires-approval-before-merge

#7622 [msbuild] Use mono's coding style.
  msbuild/Xamarin.MacDev.Tasks.sln
Labels: not-notes-worthy

#7611 [msbuild] Use System.Text.Json instead of System.Json, since only the former is available in .netcore.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
  msbuild/tests/Bug60536/Assets.xcassets/AppIcon.appiconset/Contents.json
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/Bug60536.cs
Labels: not-notes-worthy

#7623 [msbuild] Don't use gdk-sharp, use native functions instead.
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CollectITunesArtworkTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Resources/iTunesArtwork-invalid-size.jpg
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Resources/iTunesArtwork-invalid-size.png
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Resources/iTunesArtwork.jpg
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Resources/iTunesArtwork.png
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Resources/iTunesArtwork@2x.jpg
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Resources/iTunesArtwork@2x.png
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/CollectITunesArtworkTaskTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
Labels: not-notes-worthy

#7602 [sample-tester] Collect app size and build duration statistics.
  tests/sampletester/BaselineTest/AppDelegate.cs
  tests/sampletester/BaselineTest/BaselineTest.csproj
  tests/sampletester/BaselineTest/BaselineTest.sln
  tests/sampletester/BaselineTest/Info.plist
  tests/sampletester/BaselineTest/LaunchScreen.storyboard
  tests/sampletester/Configuration.cs
  tests/sampletester/ProcessHelper.cs
  tests/sampletester/SampleTester.cs
  tests/sampletester/Samples.cs
  tests/sampletester/sampletester.sln
  tools/devops/build-samples.sh
  tools/devops/build-samples.yml
  tools/devops/fetch-maccore.sh
  tools/devops/prepare-performance-data.sh
  tools/devops/push-performance-data.sh
  tools/devops/system-info.sh
  tools/mmp/driver.cs
Labels: build-package, not-notes-worthy, run-sample-tests, skip-all-tests, skip-public-jenkins

#7621 [msbuild] Use package references.
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  msbuild/Xamarin.MacDev.Tasks/packages.config
Labels: not-notes-worthy

#7633 [mtouch] Fix case where `copyfile` could fail silently
  tools/common/FileCopier.cs
Labels: bug

#7628 mtouch/mmp assembly resolution spam (Take II)
  tools/common/Tuning.cs
  tools/mmp/Tuning.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Tuning.cs
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#7647 [msbuild] Avoid lines starting with a whitespace inside generated response files. Fix #7645
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/CommandLineArgumentBuilder.cs
Labels: not-notes-worthy
