Repository dotnet/macios, pull requests merged in 2019-09, with the labels that each got.

#6869 Jenkinsfile notarization
  jenkins/Jenkinsfile
  mac-entitlements.plist
Labels: build-package

#6899 Bump maccore to get fix for #6362.
  mk/xamarin.mk
Labels: bug

#6896 [CoreData] Add support up to Xcode11 beta 7.
  src/CoreData/Enums.cs
  src/coredata.cs
  src/frameworks.sources
  tests/xtro-sharpie/iOS-CoreData.ignore
  tests/xtro-sharpie/iOS-CoreData.todo
  tests/xtro-sharpie/macOS-CoreData.todo
  tests/xtro-sharpie/tvOS-CoreData.ignore
  tests/xtro-sharpie/tvOS-CoreData.todo
  tests/xtro-sharpie/watchOS-CoreData.ignore
  tests/xtro-sharpie/watchOS-CoreData.todo
Labels: note-highlight

#6904 [registrar] Ignore method encodings when processing copyback arguments in the dynamic registrar. Fixes #6883.
  runtime/trampolines-invoke.m
  tests/bindings-test/ApiDefinition.cs
  tests/monotouch-test/ObjCRuntime/Messaging.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/test-libraries/libtest.h
  tests/test-libraries/libtest.m
Labels: bug

#6897 [imageio] Update for Xcode11 beta 7
  src/imageio.cs
  tests/xtro-sharpie/iOS-ImageIO.todo
  tests/xtro-sharpie/macOS-ImageIO.todo
  tests/xtro-sharpie/tvOS-ImageIO.todo
  tests/xtro-sharpie/watchOS-ImageIO.todo
Labels: enhancement

#6902 [d16-3] Bump mono for the latest mono fixes related to culture.
  mk/mono.mk
Labels: do-not-merge, requires-approval-before-merge

#6911 [AVFoundation] Add constructor for AVCaptureSynchronizedDepthData to fix breaking change.
  src/AVFoundation/AVCaptureSynchronizedDepthData.cs
  src/frameworks.sources
Labels: not-notes-worthy

#6914 [d16-3] [Tests] Ignore memory hungry tests in old devices.
  tests/bcl-test/iOS-monotouch_corlib_xunit-test.dll.ignore
Labels: pr-change-not-shipping

#6905 [monotouch-test] Apple has fixed a crash in the ImageCaptioningTest, so update the test accordingly.
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
Labels: not-notes-worthy

#6912 Bump mono to be in sync with android and pick a needed fix for them.
  mk/mono.mk
Labels: requires-approval-before-merge

#6907 [Make.config] Update API diff hash to current stable XI/XM (d16-2)
  Make.config
Labels: pr-change-not-shipping

#6852 [AVFoundation] Add support up to Xcode 11 beta 7.
  src/AVFoundation/AVContentKeyResponse.cs
  src/AVFoundation/AVTypes.cs
  src/AVFoundation/AVUrlAssetOptions.cs
  src/AVFoundation/Enums.cs
  src/avfoundation.cs
  src/foundation.cs
  src/frameworks.sources
  tests/xtro-sharpie/common-AVFoundation.ignore
  tests/xtro-sharpie/iOS-AVFoundation.ignore
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/macOS-AVFoundation.ignore
  tests/xtro-sharpie/macOS-AVFoundation.todo
  tests/xtro-sharpie/tvOS-AVFoundation.ignore
  tests/xtro-sharpie/tvOS-AVFoundation.todo
  tests/xtro-sharpie/watchOS-AVFoundation.ignore
  tests/xtro-sharpie/watchOS-AVFoundation.todo
Labels: note-highlight

#6927 [d16-3] Implement notarization.
  builds/.gitignore
  builds/Makefile
  jenkins/Jenkinsfile
  mac-entitlements.plist
  runtime/.gitignore
  runtime/Makefile
  tests/common/ProductTests.cs
  tools/common/MachO.cs
  tools/mtouch/Application.cs
Labels: note-highlight

#6926 Rename bundle identifier for the frameworks we ship. Fixes #6920.
  builds/Mono.framework-tvos.Info.plist
  builds/Mono.framework-watchos.Info.plist
  runtime/Xamarin.framework-tvos.Info.plist
  runtime/Xamarin.framework-watchos.Info.plist
Labels: bug, iOS

#6933 [tests][monotouch-tests] Fix UITabBar.TintColor on tvOS
  tests/monotouch-test/UIKit/TabBarTest.cs
Labels: not-notes-worthy

#6929 [tests] Fix several issues that show up in the mtouch and introspection tests on macOS 10.15.
  src/Photos/PHCompat.cs
  src/Security/Items.cs
  src/avfoundation.cs
  src/gamekit.cs
  tests/common/ProductTests.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/mtouch/MTouch.cs
  tools/mtouch/BuildTasks.mtouch.cs
Labels: enable-device-build, not-notes-worthy, run-mtouch-tests

#6928 Implement notarization.
  builds/.gitignore
  builds/Makefile
  jenkins/Jenkinsfile
  mac-entitlements.plist
  runtime/.gitignore
  runtime/Makefile
  tests/common/ProductTests.cs
  tools/common/MachO.cs
  tools/mtouch/Application.cs
Labels: not-notes-worthy

#6723 Bump to mono:2019-08
  Make.config
  mk/mono.mk
  tests/bcl-test/iOS-monotouch_corlib_xunit-test.dll.ignore
  tools/common/ClassicStaticRegistrar.cs
  tools/common/StaticRegistrar.cs
  tools/mmp/driver.cs
Labels: run-all-tests, run-internal-tests, skip-api-comparison

#6941 [introspection] Add a few more typo whitelist entries.
  tests/introspection/ApiTypoTest.cs
Labels: not-notes-worthy

#6939 [soundanalysis][watchos] Update to include last, missing API on watchOS now that AVFoundation is merged
  src/soundanalysis.cs
  tests/xtro-sharpie/watchOS-SoundAnalysis.todo
Labels: not-notes-worthy

#6930 [ModelIO] Implement new API introduced with Xcode 11 b1-7.
  runtime/bindings-generator.cs
  runtime/bindings.h
  src/ModelIO/MDLAnimatedQuaternion.cs
  src/frameworks.sources
  src/modelio.cs
  tests/monotouch-test/Asserts.cs
  tests/monotouch-test/ModelIO/MDLAnimatedValueTypesTests.cs
  tests/xtro-sharpie/common-ModelIO.ignore
  tests/xtro-sharpie/iOS-ModelIO.todo
  tests/xtro-sharpie/macOS-ModelIO.todo
  tests/xtro-sharpie/tvOS-ModelIO.todo
Labels: note-highlight

#6659 [registrar] Report a warning when the registrar export an abstract INativeObject type to Objective-C.
  docs/website/mmp-errors.md
  docs/website/mtouch-errors.md
  src/ObjCRuntime/DynamicRegistrar.cs
  src/ObjCRuntime/ErrorHelper.cs
  src/ObjCRuntime/Registrar.cs
  tests/mtouch/RegistrarTest.cs
  tools/common/ClassicStaticRegistrar.cs
  tools/common/StaticRegistrar.cs
Labels: enhancement

#6956 [metalkit] Update for Xcode 11 up to beta 7
  src/metalkit.cs
  tests/xtro-sharpie/iOS-MetalKit.todo
  tests/xtro-sharpie/macOS-MetalKit.todo
  tests/xtro-sharpie/tvOS-MetalKit.todo
Labels: enhancement

#6957 [tests][intro] Add test for simlauncher [weak] frameworks. Fixes #6951
  tests/introspection/ApiFrameworkTest.cs
  tests/introspection/iOS/introspection-ios.csproj
  tools/mtouch/.gitignore
  tools/mtouch/Makefile
Labels: not-notes-worthy

#6958 [tests][mtouch] Don't sleep a second for timestamp rollover unless we're on a non-APFS file system.
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#6974 [fileprovider][macos] Update (remove some) API for Xcode 11 GM
  src/fileprovider.cs
  tests/xtro-sharpie/macOS-FileProvider.ignore
  tests/xtro-sharpie/macOS-FileProvider.todo
Labels: not-notes-worthy

#6976 [coretext] Update for Xcode 11 GM
  src/CoreText/CTEnums.cs
Labels: enhancement

#6977 [medialibrary] Update for Xcode 11 GM
  src/medialibrary.cs
  tests/xtro-sharpie/macOS-MediaLibrary.todo
Labels: enhancement

#6975 [coreaudio] Update for Xcode 11 GM
  src/AudioToolbox/AudioType.cs
Labels: not-notes-worthy

#6979 [homekit] Update for Xcode 11 GM
  src/homekit.cs
  tests/xtro-sharpie/iOS-HomeKit.ignore
Labels: not-notes-worthy

#6978 [storekit] Update for Xcode 11 GM
  src/storekit.cs
  tests/xtro-sharpie/macOS-StoreKit.todo
Labels: enhancement

#6961 [generator] Handle inheriting the same member from multiple protocols. Fixes #6366.
  docs/website/generator-errors.md
  src/corenfc.cs
  src/generator.cs
  tests/generator/BGenTests.cs
  tests/generator/ErrorTests.cs
  tests/generator/generator-tests.csproj
  tests/generator/tests/diamond-protocol-errors.cs
  tests/generator/tests/diamond-protocol.cs
  tests/xtro-sharpie/iOS-CoreNFC.ignore
Labels: not-notes-worthy

#6999 Fix broken introspection tests on macOS 10.15. Fixes #6998.
  src/MapKit/MKEnums.cs
  src/avfoundation.cs
  src/mapkit.cs
  tests/introspection/ApiTypoTest.cs
  tests/xtro-sharpie/macOS-AVFoundation.ignore
Labels: run-internal-tests

#7010 Don't build mono from source when we're running device tests.
  Make.config
Labels: build-package, not-notes-worthy, skip-public-jenkins

#7009 Merge xcode11 into d16-3 (updated).
  Make.config
  docs/website/generator-errors.md
  runtime/bindings-generator.cs
  src/AudioToolbox/AudioType.cs
  src/Constants.iOS.cs.in
  src/Constants.mac.cs.in
  src/CoreBluetooth/CBManager.cs
  src/MapKit/MKEnums.cs
  src/MapKit/MKMapCameraZoomRange.cs
  src/MapKit/MKPointOfInterestFilter.cs
  src/NewsstandKit/Enums.cs
  src/avfoundation.cs
  src/corebluetooth.cs
  src/corehaptics.cs
  src/corenfc.cs
  src/frameworks.sources
  src/generator.cs
  src/homekit.cs
  src/mapkit.cs
  src/medialibrary.cs
  src/metrickit.cs
  src/modelio.cs
  src/newsstandkit.cs
  src/storekit.cs
  tests/common/TestRuntime.cs
  tests/generator/BGenTests.cs
  tests/generator/ErrorTests.cs
  tests/generator/generator-tests.csproj
  tests/generator/tests/diamond-protocol-errors.cs
  tests/generator/tests/diamond-protocol.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/ApiTypoTest.cs
  tests/monotouch-test/ModelIO/MDLAnimatedValueTypesTests.cs
  tests/xtro-sharpie/common-CoreBluetooth.ignore
  tests/xtro-sharpie/common-ModelIO.ignore
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/iOS-CoreHaptics.ignore
  tests/xtro-sharpie/iOS-CoreNFC.ignore
  tests/xtro-sharpie/iOS-HomeKit.ignore
  tests/xtro-sharpie/iOS-MapKit.todo
  tests/xtro-sharpie/iOS-MetricKit.ignore
  tests/xtro-sharpie/iOS-MetricKit.todo
  tests/xtro-sharpie/iOS-NewsstandKit.todo
  tests/xtro-sharpie/macOS-AVFoundation.ignore
  tests/xtro-sharpie/macOS-AVFoundation.todo
  tests/xtro-sharpie/macOS-CoreBluetooth.todo
  tests/xtro-sharpie/macOS-MapKit.todo
  tests/xtro-sharpie/macOS-MediaLibrary.todo
  tests/xtro-sharpie/macOS-StoreKit.todo
  tests/xtro-sharpie/tvOS-AVFoundation.todo
  tests/xtro-sharpie/tvOS-CoreBluetooth.todo
  tests/xtro-sharpie/tvOS-MapKit.todo
  tests/xtro-sharpie/watchOS-AVFoundation.todo
  tools/common/Frameworks.cs
  tools/mtouch/Makefile
Labels: not-notes-worthy, run-internal-tests, skip-device-tests

#7013 [runtime] Silence, please.
  runtime/Makefile
Labels: not-notes-worthy

#7014 [runtime] Build and ship Xamarin[-debug].framework.dSYM. Fixes #7004.
  runtime/Makefile
Labels: bug

#7033 [d16-3] [xharness] Fix incorrect merge.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy, pr-change-not-shipping, requires-approval-before-merge

#7034 [xcode11.1] [xharness] Fix incorrect merge.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy

#7019 Add SECURITY.MD to repo (as suggested by OSPO)
  SECURITY.MD
Labels: not-notes-worthy, skip-all-tests

#7039 [builds] Stop shipping the 32-bit AOT compiler for Xamarin.Mac.
  builds/Makefile
Labels: not-notes-worthy

#7041 [xcode11.1] [builds] Stop shipping the 32-bit AOT compiler for Xamarin.Mac.
  builds/Makefile
Labels: not-notes-worthy

#7029 [d16-3] Bump maccore for device scheduling fix
  mk/xamarin.mk
Labels: not-notes-worthy, pr-change-not-shipping, requires-approval-before-merge

#7066 [mmp] Don't ignore failures to execute pkg-config.
  Make.config
  docs/website/mmp-errors.md
  docs/website/mtouch-errors.md
  tools/mmp/driver.cs
Labels: not-notes-worthy

#7073 [d16-3] Use Xcode 11 final
  Make.config
Labels: pr-change-not-shipping, requires-approval-before-merge

#7044 Drop the Xcode 9.4 dependency.
  Make.config
  builds/Makefile
  mk/mono.mk
  runtime/Makefile
  system-dependencies.sh
  tests/common/Configuration.cs
  tests/common/ProductTests.cs
  tests/mmptest/mmptest.csproj
  tests/mmptest/src/CodeStrippingTests.cs
  tests/test-libraries/libtest-fat.macos.dylib
  tools/common/MachO.cs
Labels: not-notes-worthy

#7042 [d16-3] [builds] Stop shipping the 32-bit AOT compiler for Xamarin.Mac.
  builds/Makefile
Labels: not-notes-worthy, requires-approval-before-merge

#7085 [generator] Do not generate PlatformNotSupportedException in chaining .ctor
  src/generator.cs
  tests/monotouch-test/UIKit/KeyCommandTest.cs
Labels: bug, regression

#7093 [Metal] Add some fixed that were skipped due to a fast finger clicking.
  src/Metal/Defs.cs
  src/Metal/MTLCompat.cs
Labels: not-notes-worthy

#7097 [mtouch] Tweak watchOS architecture test to build for bitcode when building with llvm. Fixes xamarin/maccore#1994.
  docs/website/mmp-errors.md
  docs/website/mtouch-errors.md
  tests/mtouch/MTouch.cs
  tools/mtouch/mtouch.cs
Labels: enable-device-build, run-mtouch-tests

#7096 Use the mono archive again.
  Make.config
  tools/install-source/Program.cs
Labels: skip-api-comparison

#7118 [generator] Reduce code duplication in trampolines by introducing a new base type
  src/ObjCRuntime/TrampolineBlockBase.cs
  src/frameworks.sources
  src/generator.cs
Labels: enhancement

#6676 Fix the NSFileTypeForHFSTypeCode enum
  src/AppKit/Enums.cs
  src/AppKit/NSWorkspace.cs
  src/appkit.cs
  tests/apitest/src/AppKit/NSWorkspace.cs
  tests/xtro-sharpie/macOS-Foundation.ignore
Labels: community, note-highlight
