Repository dotnet/macios, pull requests merged in 2019-06, with the labels that each got.

#6188 [d16-2] [msbuild] Lock variables accessed in a Parallel.ForEach callback. Fixes #6008.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
Labels: requires-approval-before-merge

#6193 [xharness] Improve marking and reporting of known failures in tests.
  tests/xharness/Jenkins.cs
Labels: skip-api-comparison

#6187 [tests] Automatically download mono packages before running device builds.
  tests/Makefile
Labels: build-package, run-sample-tests, skip-all-tests, skip-public-jenkins

#6169 [d16-2] [xharness] Don't report tests whose device were not found if there were no such tests.
  tests/xharness/Jenkins.cs
Labels: pr-change-not-shipping

#6208 [XHarness] Point to the correct directory that has the linker config.
  tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
Labels: run-bcl-tests, run-internal-tests, skip-public-jenkins

#6220 [XHanress] Move ignore file to the correct dir.
  tests/bcl-test/tvOS-monotouch_corlib_xunit-test.dll.ignore
Labels: run-bcl-tests

#6219 [d16-2] [monotouch-test] Ignore MessageHandlerTest.RejectSslCertificatesServicePointManager on macOS 10.10.
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: pr-change-not-shipping

#6266 [d16-1] [Tests] Try different urls before failing the test.
  tests/monotouch-test/Foundation/NSDataTest.cs
Labels: pr-change-not-shipping, requires-approval-before-merge

#6265 [d16-2] [Tests] Try different urls before failing the test.
  tests/monotouch-test/Foundation/NSDataTest.cs
Labels: pr-change-not-shipping

#6160 [Xharness] Do use the traits provided by the mono sdk.
  tests/bcl-test/iOS-monotouch_corlib_xunit-test.dll.ignore
  tests/bcl-test/macOSFull-xammac_net_4_5_System.Net.Http_test.dll.ignore
  tests/bcl-test/macOSFull-xammac_net_4_5_System.Xml_test.dll.ignore
  tests/bcl-test/macOSFull-xammac_net_4_5_corlib_test.dll.ignore
  tests/bcl-test/templates/common/IgnoreFileParser.cs
  tests/bcl-test/templates/common/TestRunner.xUnit/XUnitTestRunner.cs
  tests/bcl-test/templates/iOSApp/ViewController.cs
  tests/bcl-test/templates/macOS/MacTestMain.cs
  tests/bcl-test/templates/tvOSApp/ViewController.cs
  tests/bcl-test/templates/watchOS/Extension/InterfaceController.cs
  tests/bcl-test/tvOS-monotouch_corlib_xunit-test.dll.ignore
  tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
Labels: run-bcl-tests

#6275 [system-dependencies] Add support for installing the expected CoreSimulator.framework version.
  system-dependencies.sh
Labels: run-internal-tests

#6305 [system-dependencies] Handle Xcodes with symlinks into system locations.
  system-dependencies.sh
Labels: run-internal-tests, skip-public-jenkins

#6335 [tvos] Fix introspection tests when running on tvOS 10.2. Fixes #6324
  src/cloudkit.cs
  src/coreimage.cs
Labels: run-old-simulator-tests

#6361 [d16-2] Bump VSMac to 8.1.0.2742 to fix msbuild issues (#6279)
  Make.config
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/generator/Makefile
  tests/mmptest/Makefile
  tests/mtouch/Makefile
  tests/xharness/MakefileGenerator.cs
  tests/xtro-sharpie/Makefile
  tools/mmp/tests/Makefile
  tools/xibuild/Main.cs
Labels: requires-approval-before-merge

#6164 [d16-2] [Metal] Sprinkle [return: Release] on all 'new*' selectors. Fixes #5941.
  src/Metal/MTLDevice.cs
  src/generator.cs
  src/metal.cs
  tests/generator/BGenTests.cs
  tests/generator/generator-tests.csproj
  tests/generator/tests/return-release.cs
  tests/monotouch-test/.gitignore
  tests/monotouch-test/Metal/MTLDeviceTests.cs
  tests/monotouch-test/Resources/fragmentShader.metal
  tests/monotouch-test/Resources/metal-sample.metal
  tests/monotouch-test/monotouch-test.csproj
  tests/xammac_tests/xammac_tests.csproj
  tests/xharness/ProjectFileExtensions.cs
  tests/xtro-sharpie/iOS-Metal.ignore
  tests/xtro-sharpie/macOS-Metal.ignore
  tests/xtro-sharpie/tvOS-Metal.ignore
Labels: requires-approval-before-merge

#6373 [XHarness] Re-enable tests from System-xunit-tests.dll
  tests/bcl-test/common-monotouch_System_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System_xunit-test.dll.ignore
Labels: run-bcl-tests

#6288 [d16-2] [system-dependencies] Add support for installing the expected CoreSimulator.framework version.
  system-dependencies.sh
Labels: pr-change-not-shipping

#6372 [Xharness][32b] Ignore a number of tests that fail on old devices.
  tests/bcl-test/common-monotouch_Microsoft.CSharp_xunit-test.dll.ignore
  tests/bcl-test/common-monotouch_System.Core_xunit-test.dll.ignore
  tests/bcl-test/common-monotouch_System.Numerics_xunit-test.dll.ignore
  tests/bcl-test/templates/common/TestRunner.xUnit/XUnitTestRunner.cs
Labels: run-bcl-tests

#6386 [d16-2] [tests] Handle Xcodes without proper versions by ignoring them. Fixes xamarin/maccore#1768.
  tests/common/Configuration.cs
Labels: pr-change-not-shipping

#6368 [d16-2] [CoreGraphics] Fix lifetime of delegates passed to CGPatternCreate.
  src/CoreGraphics/CGPattern.cs
Labels: requires-approval-before-merge

#6380 [xcode11][builds] Build the BCL test assemblies. Fixes #6261.
  builds/Makefile
Labels: run-bcl-tests

#6398 [XHarness] Re-enable ignored test in Mac OS from xammac_net_4_5_System_xunit-test.dll
  tests/bcl-test/macOS-xammac_net_4_5_System_xunit-test.dll.ignore
Labels: run-bcl-tests

#6403 [XHarness] Reneable tests in Mac OS X Full and ignore them in modern.
  tests/bcl-test/macOS-xammac_net_4_5_System.Core_xunit-test.dll.ignore
  tests/bcl-test/macOSModern-xammac_net_4_5_System.Core_xunit-test.dll.ignore
Labels: run-bcl-tests

#6395 [XHarness] Re-enable ignored corlib tests.
  tests/bcl-test/common-monotouch_corlib_xunit-test.dll.ignore
  tests/bcl-test/iOS-monotouch_corlib_xunit-test.dll.ignore
Labels: run-bcl-tests

#6420 Fix some availability attributes wrt macOS 10.14.6
  src/coreanimation.cs
  src/coregraphics.cs
Labels: not-notes-worthy

#6408 [authenticationservices] Update for Xcode 11 beta 1 and 2
  src/Constants.mac.cs.in
  src/Constants.tvos.cs.in
  src/Constants.watch.cs.in
  src/ObjCRuntime/PlatformAvailability2.cs
  src/authenticationservices.cs
  src/frameworks.sources
  tests/introspection/iOS/Entitlements.plist
  tests/xtro-sharpie/iOS-AuthenticationServices.todo
  tests/xtro-sharpie/macOS-AuthenticationServices.todo
  tests/xtro-sharpie/tvOS-AuthenticationServices.todo
  tests/xtro-sharpie/watchOS-AuthenticationServices.ignore
  tests/xtro-sharpie/watchOS-AuthenticationServices.todo
  tools/common/Frameworks.cs
Labels: enhancement, note-highlight

#6416 [uikit] Add some `advice` to UISearchController's constructors
  src/uikit.cs
Labels: community, enhancement, iOS

#6433 [javascriptcore] Update for Xcode 11 beta 1
  src/JavaScriptCore/Enums.cs
Labels: enhancement

#6419 [coremotion] Update for Xcode 11 beta 1
  src/Constants.mac.cs.in
  src/CoreMotion/CMCompat.cs
  src/CoreMotion/CMDeviceMotion.cs
  src/CoreMotion/CMMagnetometer.cs
  src/CoreMotion/CMSensorDataList.cs
  src/CoreMotion/Defs.cs
  src/CoreMotion/Extras.cs
  src/coremotion.cs
  src/frameworks.sources
  tests/xtro-sharpie/macOS-CoreMotion.ignore
  tests/xtro-sharpie/macOS-CoreMotion.todo
  tools/common/Frameworks.cs
Labels: enhancement

#6429 [d16-3] [GameController] GCGamepad is deprecated in the headers, so mark it as such. Fixes xamarin/maccore#1742.
  src/gamecontroller.cs
Labels: not-notes-worthy

#6427 [d16-3] Bump VSMac to 8.1.0.2742 to fix msbuild issues (#6279)
  Make.config
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/generator/Makefile
  tests/mmptest/Makefile
  tests/mtouch/Makefile
  tests/xharness/MakefileGenerator.cs
  tests/xtro-sharpie/Makefile
  tools/mmp/tests/Makefile
Labels: not-notes-worthy

#6432 [pushkit] Update for Xcode 11 beta 1
  src/Constants.mac.cs.in
  src/Constants.watch.cs.in
  src/frameworks.sources
  src/pushkit.cs
  tests/xtro-sharpie/macOS-PushKit.todo
  tests/xtro-sharpie/watchOS-PushKit.todo
  tools/common/Frameworks.cs
Labels: enhancement

#6415 [PencilKit] Add Xcode 11 Beta 1 & Beta 2 bindings
  src/Constants.iOS.cs.in
  src/Constants.mac.cs.in
  src/frameworks.sources
  src/pencilkit.cs
  tests/xtro-sharpie/iOS-PencilKit.ignore
  tests/xtro-sharpie/iOS-PencilKit.todo
  tests/xtro-sharpie/macOS-PencilKit.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#6430 [tests] Ignore all compiler warnings in apitest, introspection, monotouch-test and xammac tests.
  tests/apitest/apitest.csproj
  tests/introspection/Mac/introspection-mac.csproj
  tests/introspection/iOS/introspection-ios.csproj
  tests/mmptest/mmptest.csproj
  tests/monotouch-test/monotouch-test.csproj
  tests/xammac_tests/xammac_tests.csproj
Labels: not-notes-worthy

#6447 [passkit] Update for Xcode 11 beta 1
  src/PassKit/PKEnums.cs
  src/passkit.cs
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/watchOS-PassKit.todo
Labels: enhancement

#6450 [videosubscriberaccount] Update for Xcode 11 beta 1
  src/videosubscriberaccount.cs
  tests/xtro-sharpie/iOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/tvOS-VideoSubscriberAccount.todo
Labels: enhancement

#6446 [xcode11] Merge d16-2.
  src/CoreGraphics/CGPattern.cs
  tests/common/Configuration.cs
Labels: not-notes-worthy

#6445 [mmptest] Modify the Unified_HelloWorld_ShouldHaveNoWarnings test to not fail if the branch name contains 'warning'. Fixes xamarin/maccore#1404.
  tests/common/ExecutionHelper.cs
  tests/mmptest/src/MMPTest.cs
Labels: not-notes-worthy

#6431 [xcode11] Fix several test and API issues that made apitest, introspection and xammac tests fail on macOS 10.15.
  src/appkit.cs
  src/coreml.cs
  src/foundation.cs
  src/metalperformanceshaders.cs
  src/photos.cs
  src/safariservices.cs
  src/vision.cs
  src/xkit.cs
  tests/apitest/Info.plist
  tests/apitest/apitest.csproj
  tests/apitest/src/AppKit/NSTextInputClient.cs
  tests/apitest/src/DelegateAndDataSourceTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/Mac/Info.plist
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/introspection/Mac/introspection-mac.csproj
  tests/monotouch-test/AVFoundation/AVDepthDataTests.cs
  tests/monotouch-test/EventKit/CalendarTest.cs
  tests/monotouch-test/Metal/MTLDeviceTests.cs
  tests/monotouch-test/Security/TrustTest.cs
  tests/tests-mac.sln
  tests/xtro-sharpie/iOS-CoreML.todo
  tests/xtro-sharpie/iOS-Foundation.todo
  tests/xtro-sharpie/iOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/iOS-Vision.todo
  tests/xtro-sharpie/macOS-AppKit.todo
  tests/xtro-sharpie/macOS-CoreML.todo
  tests/xtro-sharpie/macOS-Foundation.todo
  tests/xtro-sharpie/macOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/macOS-Photos.todo
  tests/xtro-sharpie/macOS-SafariServices.todo
  tests/xtro-sharpie/macOS-Vision.todo
  tests/xtro-sharpie/tvOS-CoreML.todo
  tests/xtro-sharpie/tvOS-Foundation.todo
  tests/xtro-sharpie/tvOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/tvOS-Vision.todo
  tests/xtro-sharpie/watchOS-CoreML.todo
  tests/xtro-sharpie/watchOS-Foundation.todo
Labels: not-notes-worthy, run-internal-tests

#6457 [mediaaccessibility] Update for Xcode 11 beta 1
  src/MediaAccessibility/MAImageCaptioning.cs
  src/frameworks.sources
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
  tests/xtro-sharpie/iOS-MediaAccessibility.todo
  tests/xtro-sharpie/macOS-MediaAccessibility.todo
  tests/xtro-sharpie/tvOS-MediaAccessibility.todo
Labels: note-highlight
