Repository dotnet/macios, pull requests merged in 2019-07, with the labels that each got.

#6467 [xharness] Propagate the BUILD_REVISION variable to test apps to specify if we're in CI or not. Fixes xamarin/maccore#649.
  tests/xharness/AppRunner.cs
  tests/xharness/Harness.cs
Labels: not-notes-worthy

#6463 [xammac-test/MapKit/PinAnnotationView] Changed assertion of PinTintColor property to work on other language than English
  tests/monotouch-test/MapKit/PinAnnotationViewTest.cs
Labels: community

#6440 [Speech] Add Xcode 11 Beta 1 & Beta 2 bindings
  src/Constants.mac.cs.in
  src/frameworks.sources
  src/speech.cs
  tests/xtro-sharpie/iOS-Speech.todo
  tests/xtro-sharpie/macOS-Speech.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#6438 [BackgroundTasks] Add new Framework for Xcode 11 beta 1.
  src/BackgroundTasks/Enums.cs
  src/Constants.iOS.cs.in
  src/Constants.tvos.cs.in
  src/backgroundtasks.cs
  src/frameworks.sources
  tests/introspection/ApiSelectorTest.cs
  tests/monotouch-test/AppDelegate.cs
  tests/monotouch-test/BackgroundTasks/BGTaskSchedulerTest.cs
  tests/monotouch-test/Info.plist
  tests/monotouch-test/monotouch-test.csproj
  tests/xtro-sharpie/iOS-BackgroundTasks.todo
  tests/xtro-sharpie/tvOS-BackgroundTasks.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#6472 [CloudKit] Update CloudKit for Xcode 11 beta 2.
  src/CloudKit/Enums.cs
  src/cloudkit.cs
  tests/xtro-sharpie/watchOS-CloudKit.ignore
  tests/xtro-sharpie/watchOS-CloudKit.todo
Labels: note-highlight

#6434 [AudioToolBox] [AudioUnit] Add support for Xcode 11 beta 1 & beta 2.
  src/AudioToolbox/AudioFile.cs
  src/AudioToolbox/AudioType.cs
  src/AudioToolbox/Enums.cs
  src/AudioToolbox/MusicTrack.cs
  src/AudioUnit/AudioComponentDescription.cs
  src/audiounit.cs
  src/frameworks.sources
  tests/monotouch-test/AudioToolbox/MusicTrackTest.cs
  tests/xtro-sharpie/common-AudioToolbox.ignore
  tests/xtro-sharpie/iOS-AudioToolbox.ignore
  tests/xtro-sharpie/iOS-AudioToolbox.todo
  tests/xtro-sharpie/macOS-AudioToolbox.ignore
  tests/xtro-sharpie/macOS-AudioToolbox.todo
  tests/xtro-sharpie/tvOS-AudioToolbox.ignore
  tests/xtro-sharpie/tvOS-AudioToolbox.todo
Labels: note-highlight

#6473 [tests] Provision dotnet for the sample tests. Fixes xamarin/maccore#1811.
  tests/sampletester/Configuration.cs
  tools/devops/build-samples.csx
Labels: not-notes-worthy, run-internal-tests, run-sample-tests

#6481 [videosubscriberaccount] Update for Xcode 11 beta 3
  src/videosubscriberaccount.cs
  tests/xtro-sharpie/iOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/macOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/tvOS-VideoSubscriberAccount.todo
Labels: enhancement

#6482 [authenticationservices] Update for Xcode 11 beta 3
  src/authenticationservices.cs
Labels: enhancement

#6483 [replaykit] Update for Xcode 11 beta 3
  src/ReplayKit/RPEnums.cs
Labels: enhancement

#6484 [incomingcallnotifications] Removed from Xcode 11 beta 3
  src/incomingcallnotifications.cs
Labels: note-highlight

#6485 [AppKit] Implement [NSView sortSubviewsUsingFunction:context:]
  runtime/trampolines.m
  src/AppKit/NSView.cs
  src/appkit.cs
  src/frameworks.sources
  tests/apitest/src/AppKit/NSView.cs
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: enhancement

#6460 [arkit] Update for Xcode 11 beta 2 and beta 3
  runtime/bindings-generator.cs
  src/ARKit/ARSkeleton2D.cs
  src/ARKit/ARSkeleton3D.cs
  src/arkit.cs
  src/frameworks.sources
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/monotouch-test/ARKit/ARSkeleton2DTest.cs
  tests/monotouch-test/ARKit/ARSkeleton3DTest.cs
  tests/xtro-sharpie/iOS-ARKit.ignore
  tests/xtro-sharpie/iOS-ARKit.todo
Labels: enhancement

#6477 [httpclient] Change NSUrlSessionHandler and CFNetworkHandler to throw HttpRequestException. Fix #6439
  src/Foundation/NSUrlSessionHandler.cs
  src/System.Net.Http/CFNetworkHandler.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: bug, iOS, macOS, note-highlight

#6487 [d16-3][tests] Provision dotnet for the sample tests. Fixes xamarin/maccore#1811. (#6473)
  tests/sampletester/Configuration.cs
  tools/devops/build-samples.csx
Labels: not-notes-worthy, run-internal-tests, run-sample-tests, skip-public-jenkins

#6496 [wkwebkit] Update for Xcode 11 beta 3
  src/Foundation/NSAttributedString.iOS.cs
  src/foundation.cs
  src/wkwebkit.cs
  tests/monotouch-test/WebKit/NSAttributedStringCatagoryTest.cs
  tests/monotouch-test/access-denied.html
  tests/monotouch-test/access-granted.html
  tests/monotouch-test/monotouch-test.csproj
  tests/xtro-sharpie/iOS-WebKit.todo
  tests/xtro-sharpie/macOS-WebKit.todo
Labels: enhancement

#6497 [mmptest] Remove the link-gdiplus-1/2 tests, they can't be ported to Unified. Partial fix for #4975.
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-gdiplus-1/Info.plist
  tests/mmptest/regression/link-gdiplus-1/LinkGdiPlus1.cs
  tests/mmptest/regression/link-gdiplus-1/link-gdiplus-1.csproj
  tests/mmptest/regression/link-gdiplus-2/Info.plist
  tests/mmptest/regression/link-gdiplus-2/LinkGdiPlus2.cs
  tests/mmptest/regression/link-gdiplus-2/link-gdiplus-2.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6501 [mmptest] Port link-aes-1 to an NUnit LinkAll+LinkSdk test. Partial fix for #4975.
  tests/linker/mac/LinkAnyTest.cs
  tests/linker/mac/link all/link all-mac.csproj
  tests/linker/mac/link sdk/link sdk-mac.csproj
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-aes-1/Info.plist
  tests/mmptest/regression/link-aes-1/LinkAes1.cs
  tests/mmptest/regression/link-aes-1/link-aes-1.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6499 [javascriptcore] Update for Xcode 11 beta 3
  src/javascriptcore.cs
  tests/monotouch-test/JavascriptCore/ValueTest.cs
  tests/xtro-sharpie/common-JavaScriptCore.ignore
  tests/xtro-sharpie/iOS-JavaScriptCore.todo
  tests/xtro-sharpie/macOS-JavaScriptCore.todo
  tests/xtro-sharpie/tvOS-JavaScriptCore.todo
Labels: enhancement

#6500 [mmptest] Remove the link-system.web-icalls test. Partial fix for #4975.
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-system.web-icalls/Info.plist
  tests/mmptest/regression/link-system.web-icalls/LinkSysWebIcalls.cs
  tests/mmptest/regression/link-system.web-icalls/link-system.web-icalls.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6506 [monotouch-test] Disable the MidiThruConnectionTests tests, they're randomly failing.
  tests/monotouch-test/CoreMidi/MidiThruConnectionTests.cs
Labels: not-notes-worthy

#6453 [appkit] add signatures to NSGridView.Create and deprecate the actual one
  src/Foundation/NSArray.cs
  src/appkit.cs
  tests/xammac_tests/AppKit/NSGridViewTest.cs
  tests/xammac_tests/xammac_tests.csproj
Labels: bug, community

#6505 [CoreMidi] Fix creating a native MidiThruConnectionParamsStruct.
  src/CoreMidi/MidiThruConnectionParams.cs
  tests/monotouch-test/CoreMidi/MidiThruConnectionTests.cs
Labels: bug, iOS

#6515 [tests] The watchOS 3.2 simulator is unusable, so use the 4.0 simulator instead. Fixes xamarin/maccore#1835.
  Make.config
  tests/introspection/ApiSelectorTest.cs
Labels: not-notes-worthy

#6516 [apitest] Remove comment about fixed crasher.
  tests/apitest/src/AppKit/NSTextInputClient.cs
Labels: not-notes-worthy

#6510 [identitylookupui] Update for Xcode 11 beta 1
  src/identitylookupui.cs
Labels: enhancement

#6421 [d16-2] [xharness] Don't try to find simulators for ignored tests.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy, pr-change-not-shipping, requires-approval-before-merge

#6423 [d16-2] [tests] Only call MTLDevice.CreateSharedTexture macOS 10.14+. Fixes xamarin/maccore#1663.
  tests/monotouch-test/Metal/MTLDeviceTests.cs
Labels: not-notes-worthy, pr-change-not-shipping, requires-approval-before-merge

#6428 [d16-2] [GameController] GCGamepad is deprecated in the headers, so mark it as such. Fixes xamarin/maccore#1742.
  src/gamecontroller.cs
Labels: not-notes-worthy, requires-approval-before-merge

#6520 [Introspection] Add missing acronyms.
  tests/introspection/ApiTypoTest.cs
Labels: not-notes-worthy

#6509 [mmptest] Port link-posix-1 to Unified, and remove the link-posix-2 test. Partial fix for #4975.
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-posix-1/LinkPosix1.cs
  tests/mmptest/regression/link-posix-1/link-posix-1.csproj
  tests/mmptest/regression/link-posix-2/Info.plist
  tests/mmptest/regression/link-posix-2/LinkPosix2.cs
  tests/mmptest/regression/link-posix-2/link-posix-2.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6514 [registar] Search the entire interface hierarchy for protocols. Fixes #6493.
  src/ObjCRuntime/Registrar.cs
  tests/monotouch-test/Foundation/UrlProtocolTest.cs
  tools/common/StaticRegistrar.cs
Labels: bug

#6437 [LinkPresentation] Add Xcode 11 Beta 1 & Beta 2 bindings
  src/Constants.iOS.cs.in
  src/Constants.mac.cs.in
  src/frameworks.sources
  src/linkpresentation.cs
  tests/xtro-sharpie/iOS-LinkPresentation.todo
  tests/xtro-sharpie/macOS-LinkPresentation.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#6512 [carplay] Update for Xcode11 beta 3
  src/carplay.cs
  tests/xtro-sharpie/iOS-CarPlay.ignore
  tests/xtro-sharpie/iOS-CarPlay.todo
Labels: enhancement

#6517 [ARKit] Uncomment bindings that only work on device.
  src/arkit.cs
  tests/introspection/ApiSelectorTest.cs
  tests/xtro-sharpie/iOS-ARKit.ignore
Labels: not-notes-worthy

#6535 [mmptest] Reuse the existing iOS version of the link-data-contract-1 test. Partial fix for #4975.
  tests/linker/ios/link all/DataContractTest.cs
  tests/linker/mac/link all/link all-mac.csproj
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-data-contract-1/Info.plist
  tests/mmptest/regression/link-data-contract-1/LinkDataContract1.cs
  tests/mmptest/regression/link-data-contract-1/link-data-contract-1.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6533 [mmptest] Port link-keep-resources-2 to Unified. Partial fix for #4975.
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-keep-resources-2/LinkKeepResources2.cs
  tests/mmptest/regression/link-keep-resources-2/link-keep-resources-2.csproj
Labels: not-notes-worthy

#6529 [package] Remove creation of files/symlinks under /Developer
  Makefile
Labels: build-package, note-highlight

#6498 [sampletester] Provision Xcode when it's not already available. Fixes #6326.
  .gitignore
  tools/devops/build-samples.csx
  tools/devops/build-samples.yml
  tools/devops/provision-xcode.csx
Labels: build-package, not-notes-worthy, run-sample-tests, skip-all-tests, skip-public-jenkins

#6536 [mmptest] Port link-blocks-1 to an NUnit LinkAll+LinkSdk test. Partial fix for #4975.
  tests/linker/CommonLinkAnyTest.cs
  tests/linker/ios/link all/link all.csproj
  tests/linker/ios/link sdk/link sdk.csproj
  tests/linker/mac/link all/link all-mac.csproj
  tests/linker/mac/link sdk/link sdk-mac.csproj
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-blocks-1/Info.plist
  tests/mmptest/regression/link-blocks-1/LinkBlocks1.cs
  tests/mmptest/regression/link-blocks-1/link-blocks-1.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6539 [mmptest] Port link-callfilepath-45 to an NUnit LinkAll+LinkSdk test. Partial fix for #4975.
  tests/linker/CommonLinkAnyTest.cs
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-callfilepath-45/Info.plist
  tests/mmptest/regression/link-callfilepath-45/LinkCallFilePath.cs
  tests/mmptest/regression/link-callfilepath-45/link-callfilepath-45.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6545 [mtouch] Work around regression in dyld. Fixes #6422.
  tools/common/CompilerFlags.cs
Labels: not-notes-worthy

#6543 [mmptest] Port link-frameworks-1 to Unified and improve it. Partial fix for #4975.
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-frameworks-1/LinkFrameworks1.cs
  tests/mmptest/regression/link-frameworks-1/link-frameworks-1.csproj
Labels: not-notes-worthy

#6541 [mmptest] Port link-preserve-assembly to Unified. Partial fix for #4975.
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-preserve-assembly/LinkPreserveAssembly.cs
  tests/mmptest/regression/link-preserve-assembly/link-preserve-assembly.csproj
Labels: not-notes-worthy

#6538 [foundation] Partial update for Xcode 11 beta 1 to 3
  src/Foundation/Enum.cs
  src/foundation.cs
  tests/introspection/ApiProtocolTest.cs
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/iOS-Foundation.todo
  tests/xtro-sharpie/macOS-Foundation.ignore
  tests/xtro-sharpie/macOS-Foundation.todo
  tests/xtro-sharpie/tvOS-Foundation.todo
  tests/xtro-sharpie/watchOS-Foundation.todo
Labels: enhancement

#6449 [tests] Fix (no failure) introspection tests on device (iOS13)
  tests/introspection/ApiProtocolTest.cs
Labels: not-notes-worthy, run-internal-tests

#6547 [mmptest] Port link-remove-attributes-1 to Unified. Partial fix for #4975.
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-remove-attributes-1/LinkRemoveAttributes.cs
  tests/mmptest/regression/link-remove-attributes-1/link-remove-attributes-1.csproj
Labels: not-notes-worthy

#6546 [mmptest] Port link-uithread-1/2 to an NUnit LinkAll test. Partial fix for #4975.
  tests/linker/mac/link all/LinkAllTest.cs
  tests/linker/mac/link all/link all-mac.csproj
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-uithread-1/Info.plist
  tests/mmptest/regression/link-uithread-1/LinkUiThread.cs
  tests/mmptest/regression/link-uithread-1/link-uithread-1.csproj
  tests/mmptest/regression/link-uithread-2/Info.plist
  tests/mmptest/regression/link-uithread-2/link-uithread-2.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6488 [xcode11][tests] Provision dotnet for the sample tests. Fixes xamarin/maccore#1811. (#6473)
  tests/sampletester/Configuration.cs
  tools/devops/build-samples.csx
Labels: not-notes-worthy, run-internal-tests, run-sample-tests, skip-public-jenkins

#6555 [mmptest] Port the link-xml-serialization test to an NUnit LinkAll test. Partial fix for #4975.
  tests/linker/mac/link all/LinkAllTest.cs
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-xml-serialization/Info.plist
  tests/mmptest/regression/link-xml-serialization/LinkXmlSerialization.cs
  tests/mmptest/regression/link-xml-serialization/Main.cs
  tests/mmptest/regression/link-xml-serialization/link-xml-serialization.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6554 [mmptest] Port link-httpclient-async to an NUnit LinkAll+LinkSdk test. Partial fix for #4975.
  tests/linker/mac/LinkAnyTest.cs
  tests/linker/mac/link all/link all-mac.csproj
  tests/linker/mac/link sdk/link sdk-mac.csproj
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-httpclient-async/Info.plist
  tests/mmptest/regression/link-httpclient-async/LinkHttpClientAsync.cs
  tests/mmptest/regression/link-httpclient-async/link-httpclient-async.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6513 [CoreMedia] Add support for CoreMedia on Xcode 11 beta 3.
  src/AudioToolbox/AudioFormat.cs
  src/Constants.watch.cs.in
  src/CoreMedia/CMAttachmentBearer.cs
  src/CoreMedia/CMBlockBuffer.cs
  src/CoreMedia/CMBufferQueue.cs
  src/CoreMedia/CMCustomBlockAllocator.cs
  src/CoreMedia/CMFormatDescription.cs
  src/CoreMedia/CMMemoryPool.cs
  src/CoreMedia/CMSampleBuffer.cs
  src/CoreMedia/CMSync.cs
  src/CoreMedia/CMTextMarkupAttributes.cs
  src/CoreMedia/CMTime.cs
  src/CoreMedia/CoreMedia.cs
  src/CoreMedia/Enums.cs
  src/CoreMedia/ICMAttachmentBearer.cs
  src/Makefile
  src/coremedia.cs
  src/frameworks.sources
  tests/monotouch-test/CoreMedia/BlockBufferTest.cs
  tests/monotouch-test/CoreMedia/CMClockOrTimebaseTest.cs
  tests/monotouch-test/CoreMedia/CMClockTest.cs
  tests/monotouch-test/CoreMedia/CMFormatDescriptionTest.cs
  tests/monotouch-test/CoreMedia/CMMemoryPoolTest.cs
  tests/monotouch-test/CoreMedia/CMTimeRangeTests.cs
  tests/monotouch-test/CoreMedia/CMTimeTests.cs
  tests/monotouch-test/CoreMedia/CMTimebaseTest.cs
  tests/monotouch-test/CoreMedia/EnumTest.cs
  tests/monotouch-test/CoreMedia/SampleBufferTest.cs
  tests/xtro-sharpie/common-CoreMedia.ignore
  tests/xtro-sharpie/iOS-CoreMedia.todo
  tests/xtro-sharpie/macOS-CoreMedia.todo
  tests/xtro-sharpie/tvOS-CoreMedia.todo
  tests/xtro-sharpie/watchOS-CoreMedia.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#6557 [mmptest] Port the link-webclient-* tests to NUnit LinkAll+LinkSdk tests. Partial fix for #4975.
  tests/linker/mac/LinkAnyTest.cs
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-webclient-1/Info.plist
  tests/mmptest/regression/link-webclient-1/LinkWebClient1.cs
  tests/mmptest/regression/link-webclient-1/link-webclient-1.csproj
  tests/mmptest/regression/link-webclient-2/Info.plist
  tests/mmptest/regression/link-webclient-2/LinkWebClient2.cs
  tests/mmptest/regression/link-webclient-2/link-webclient-2.csproj
  tests/mmptest/regression/link-webclient-3/Info.plist
  tests/mmptest/regression/link-webclient-3/LinkWebClientAsync.cs
  tests/mmptest/regression/link-webclient-3/link-webclient-3.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6556 [mmptest] Port link-safe-1 to Unified. Partial fix for #4975.
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/link-safe-1/LinkSafeAssembly.cs
  tests/mmptest/regression/link-safe-1/link-safe-1.csproj
Labels: not-notes-worthy

#6559 [xcode11] Fix monotouch-test to not crash on device.
  tests/monotouch-test/Info.plist
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
  tests/monotouch-test/Metal/MTLDeviceTests.cs
Labels: not-notes-worthy

#6531 [tests] Don't use unsupported characters in matrix names for yml scripts. Fixes xamarin/maccore#1831.
  tools/devops/build-samples-report-to-github.sh
  tools/devops/build-samples.yml
Labels: not-notes-worthy, run-internal-tests, run-sample-tests, skip-all-tests, skip-public-jenkins

#6544 [tests] Improve handling of permission dialogs. Fixes xamarin/maccore#1856.
  jenkins/Jenkinsfile
  tests/common/TestRuntime.cs
  tests/monotouch-test/Contacts/ContactFetchRequestTest.cs
  tests/monotouch-test/Contacts/ContactVCardSerializationTest.cs
  tests/xharness/AppRunner.cs
  tests/xharness/Harness.cs
  tests/xharness/Jenkins.cs
  tests/xharness/MakefileGenerator.cs
Labels: not-notes-worthy, run-internal-tests, skip-public-jenkins

#6569 [mmptest] Various cleanups.
  tests/mmptest/regression/Makefile
  tests/mmptest/regression/common/MainMenu.xib
  tests/mmptest/regression/common/Test.cs
  tests/mmptest/regression/custom-bundle-name/Info.plist
  tests/mmptest/regression/custom-bundle-name/custom-bundle-name.csproj
  tests/mmptest/regression/embedded-mono-profile/Info.plist
  tests/mmptest/regression/embedded-mono-profile/embedded-mono-profile.csproj
  tests/mmptest/regression/embedded-mono/Info.plist
  tests/mmptest/regression/embedded-mono/embedded-mono.csproj
  tests/mmptest/regression/link-frameworks-1/Info.plist
  tests/mmptest/regression/link-frameworks-1/link-frameworks-1.csproj
  tests/mmptest/regression/link-keep-resources-1/Info.plist
  tests/mmptest/regression/link-keep-resources-1/link-keep-resources-1.csproj
  tests/mmptest/regression/link-keep-resources-2/Info.plist
  tests/mmptest/regression/link-keep-resources-2/link-keep-resources-2.csproj
  tests/mmptest/regression/link-posix-1/Info.plist
  tests/mmptest/regression/link-posix-1/link-posix-1.csproj
  tests/mmptest/regression/link-preserve-assembly/Info.plist
  tests/mmptest/regression/link-preserve-assembly/link-preserve-assembly.csproj
  tests/mmptest/regression/link-remove-attributes-1/Info.plist
  tests/mmptest/regression/link-remove-attributes-1/link-remove-attributes-1.csproj
  tests/mmptest/regression/link-safe-1/Info.plist
  tests/mmptest/regression/link-safe-1/link-safe-1.csproj
  tests/mmptest/regression/system-mono-profile/Info.plist
  tests/mmptest/regression/system-mono-profile/system-mono-profile.csproj
  tests/mmptest/regression/system-mono/Info.plist
  tests/mmptest/regression/system-mono/system-mono.csproj
  tests/mmptest/regression/tests.sln
Labels: not-notes-worthy

#6574 [localauthentication] Update for Xcode 11 beta 1-3
  src/LocalAuthentication/LAEnums.cs
  src/localauthentication.cs
Labels: enhancement

#6575 [xammac_tests] Fix a few issues after the latest beta. Fixes xamarin/maccore#1886.
  tests/monotouch-test/EventKit/CalendarTest.cs
  tests/xammac_tests/xammac_tests.csproj
Labels: not-notes-worthy

#6553 [UIKit] Partial update to Xcode 11 Beta 1, 2 and 3 - Part 2 of ?
  src/UIKit/NSLayoutManager.cs
  src/UIKit/UIAccessibility.cs
  src/UIKit/UIEnums.cs
  src/UIKit/UIFont.cs
  src/UIKit/UITypes.cs
  src/foundation.cs
  src/uikit.cs
  src/usernotifications.cs
  src/xkit.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/monotouch-test/UIKit/FloatRangeTest.cs
  tests/xtro-sharpie/iOS-FileProvider.todo
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/macOS-AppKit.ignore
  tests/xtro-sharpie/macOS-AppKit.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-UIKit.ignore
  tests/xtro-sharpie/watchOS-UIKit.todo
Labels: note-highlight

#6458 [msbuild] $(ProduceReferenceAssembly) support
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/XamarinForms.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TestHelpers/Logger.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TestHelpers/TestBase.cs
Labels: note-highlight, run-mac-binding-project-tests, run-mmp-tests, run-sample-tests

#6562 [coretext] Update for Xcode 11 beta 1-3
  src/CoreText/CTEnums.cs
  src/CoreText/CTFontManager.cs
  src/CoreText/CTRun.cs
  src/CoreText/CTStringAttributes.cs
  src/coretext.cs
  tests/monotouch-test/CoreText/FontManagerTest.cs
  tests/monotouch-test/CoreText/RunTest.cs
  tests/monotouch-test/CoreText/StringAttributes.cs
  tests/xtro-sharpie/common-CoreText.ignore
  tests/xtro-sharpie/iOS-CoreText.ignore
  tests/xtro-sharpie/iOS-CoreText.todo
  tests/xtro-sharpie/macOS-CoreText.todo
  tests/xtro-sharpie/tvOS-CoreText.todo
  tests/xtro-sharpie/watchOS-CoreText.todo
Labels: enhancement

#6584 [sampletester] Bump xamarin-forms-book-samples to the tip of master, where a few fixes have been merged.
  tests/sampletester/Samples.cs
Labels: run-internal-tests, run-sample-tests, skip-public-jenkins

#6196 Bump to mono:2019-06
  Make.config
  builds/Makefile
  mk/mono.mk
  mk/versions.mk
  mk/xamarin.mk
  runtime/Makefile
  runtime/monotouch-support.h
  src/Makefile
  src/Makefile.generator
  tests/Makefile
  tests/bcl-test/common-monotouch_System.Net.Http.UnitTests_xunit-test.dll.ignore
  tests/bcl-test/common-monotouch_System.Numerics_xunit-test.dll.ignore
  tests/bcl-test/common-monotouch_System_xunit-test.dll.ignore
  tests/bcl-test/common-monotouch_corlib_xunit-test.dll.ignore
  tests/bcl-test/iOS-monotouch_System.Data_xunit-test.dll.ignore
  tests/bcl-test/macOS-xammac_net_4_5_System.Data_xunit-test.dll.ignore
  tests/bcl-test/macOS-xammac_net_4_5_System.Net.Http.UnitTests_xunit-test.dll.ignore
  tests/bcl-test/macOS-xammac_net_4_5_System_xunit-test.dll.ignore
  tests/bcl-test/macOS-xammac_net_4_5_corlib_xunit-test.dll.ignore
  tests/bcl-test/macOSModern-xammac_net_4_5_System.Core_xunit-test.dll.ignore
  tests/bcl-test/macOSModern-xammac_net_4_5_System_xunit-test.dll.ignore
  tests/bcl-test/tvOS-monotouch_System.Data_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Data_xunit-test.dll.ignore
  tests/common/ProductTests.cs
  tests/mtouch/Makefile
  tests/mtouch/MiscTests.cs
  tests/mtouch/SdkTest.cs
  tests/package-mac-tests.sh
  tools/mmp/Makefile
  tools/mtouch/Makefile
  tools/mtouch/mtouch.cs
Labels: note-highlight, run-all-tests, run-internal-tests, skip-api-comparison, skip-public-jenkins

#6579 [NotificationCenter] Bindings for iOS Xcode 11 beta 1
  src/UIKit/UIVibrancyEffect.cs
  src/notificationcenter.cs
  tests/xtro-sharpie/iOS-NotificationCenter.ignore
  tests/xtro-sharpie/iOS-NotificationCenter.todo
Labels: community, note-highlight

#6594 [xharness] Run the mtouch tests when anything in runtime/ changes.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy

#6593 [runtime] Fix xamarin_timezone_get_local_name signature.
  runtime/monotouch-support.h
  runtime/xamarin-support.m
Labels: not-notes-worthy, run-mtouch-tests

#6610 [replaykit] Update for Xcode 11 beta 4
  src/ReplayKit/RPEnums.cs
Labels: enhancement

#6608 [ARKit] Update to Xcode 11 Beta 4
  src/arkit.cs
Labels: note-highlight

#6611 [coreanimation] Update for Xcode 11 b4
  src/coreanimation.cs
Labels: enhancement

#6612 [PencilKit] Update to Xcode 11 Beta 4
  src/pencilkit.cs
Labels: note-highlight

#6613 [generator] Allow the generation of smart enums `*Extensions` code even if no fields are present
  src/generator-enums.cs
Labels: not-notes-worthy

#6609 [corenfc] Update for Xcode 11 beta 4
  src/corenfc.cs
  tests/xtro-sharpie/iOS-CoreNFC.ignore
  tests/xtro-sharpie/iOS-CoreNFC.todo
Labels: enhancement

#6617 [authenticationservices] Update for Xcode 11 beta 4
  src/authenticationservices.cs
  tests/xtro-sharpie/macOS-AuthenticationServices.todo
Labels: enhancement

#6621 [Tests] Fix introspection tests in catalina
  src/foundation.cs
  tests/introspection/ApiTypoTest.cs
Labels: not-notes-worthy

#6619 [AuthenticationServices] Fix ASAuthorization and ASAuthorizationRequest
  src/AuthenticationServices/ASAuthorization.cs
  src/AuthenticationServices/ASAuthorizationRequest.cs
  src/authenticationservices.cs
  src/frameworks.sources
Labels: note-highlight

#6618 [UIKit] Update bindings to Xcode 11 beta 4
  src/uikit.cs
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-UIKit.todo
Labels: note-highlight

#6583 [tests] Package Xamarin.Mac tests using 7z instead of zip.
  jenkins/Jenkinsfile
  jenkins/prepare-packaged-macos-tests.sh
  tests/package-mac-tests.sh
Labels: not-notes-worthy, run-internal-tests, skip-public-jenkins

#6521 [Photos] Add Xcode 11 Beta 1-4 bindings
  src/Photos/Enums.cs
  src/Photos/PHChangeRequest.cs
  src/frameworks.sources
  src/photos.cs
  tests/xtro-sharpie/common-Photos.ignore
  tests/xtro-sharpie/iOS-Photos.todo
  tests/xtro-sharpie/macOS-Photos.todo
  tests/xtro-sharpie/tvOS-Photos.todo
Labels: note-highlight

#6602 [xcode11] [ItunesLibrary] macOS b1 bindings
  src/frameworks.sources
  src/iTunesLibrary/ITCompat.cs
  src/ituneslibrary.cs
  tests/xtro-sharpie/macOS-iTunesLibrary.todo
Labels: community, note-highlight

#6628 [mmp] Fix QTKit submission issue when linker is disabled
  tools/common/Target.cs
Labels: run-mmp-tests

#6563 [contacts] xcode11 beta1 - beta4 updated bindings
  src/Contacts/CNEnums.cs
  src/contacts.cs
  tests/xtro-sharpie/iOS-Contacts.todo
  tests/xtro-sharpie/macOS-Contacts.todo
  tests/xtro-sharpie/watchOS-Contacts.todo
Labels: note-highlight

#6636 [AppKit] Add missing NSScreen method.
  src/appkit.cs
  tests/xtro-sharpie/macOS-AppKit.todo
Labels: enhancement

#6641 [src] Remove the named macOS version attributes.
  docs/website/binding_types_reference_guide.md
  src/ObjCRuntime/PlatformAvailability.cs
  src/storekit.cs
  tests/linker/ios/link all/LinkAllTest.cs
Labels: not-notes-worthy

#6640 [tests] Use built-in feature checks to check for API non-crashyness.
  src/Metal/MTLEnums.cs
  tests/monotouch-test/Metal/MTLDeviceTests.cs
Labels: not-notes-worthy

#6639 [monotouch-test] Ignore the FontManagerTest.RegisterFontDescriptors_NoCallback test, it may crash.
  tests/monotouch-test/CoreText/FontManagerTest.cs
Labels: not-notes-worthy

#6642 [mmp] Remove support for 32-bit apps. Partial fix for #6300.
  src/ObjCRuntime/DynamicRegistrar.cs
  src/ObjCRuntime/Registrar.cs
  tools/common/Application.cs
  tools/common/ClassicStaticRegistrar.cs
  tools/common/Driver.cs
  tools/common/Frameworks.cs
  tools/common/Optimizations.cs
  tools/common/PInvokeWrapperGenerator.cs
  tools/common/StaticRegistrar.cs
  tools/common/Symbols.cs
  tools/common/Target.cs
  tools/linker/CoreTypeMapStep.cs
  tools/linker/MonoTouch.Tuner/Extensions.cs
  tools/mmp/Application.cs
  tools/mmp/aot.cs
  tools/mmp/driver.cs
  tools/mmp/linker/MonoMac.Tuner/MacBaseProfile.cs
  tools/mmp/linker/MonoMac.Tuner/MacMobileProfile.cs
  tools/mmp/linker/MonoMac.Tuner/MonoMacMarkStep.cs
  tools/mmp/linker/MonoMac.Tuner/MonoMacProfile.cs
  tools/mmp/linker/MonoMac.Tuner/XamarinMacProfile.cs
  tools/mmp/mmp.csproj
  tools/mmp/resolver.cs
  tools/mmp/tests/aot.cs
Labels: not-notes-worthy

#6643 [generator] Remove support for Classic bindings. Partial fix for #6300.
  src/Makefile.generator
  src/ObjCRuntime/Stret.cs
  src/bmac
  src/btouch.cs
  src/generator-attribute-manager.cs
  src/generator-typemanager.cs
  src/generator.cs
Labels: not-notes-worthy

#6646 [registrar] Fix a generics type issue with dynamic registrar
  src/ObjCRuntime/DynamicRegistrar.cs
  src/uikit.cs
  tests/monotouch-test/UIKit/NSDiffableDataSourceSnapshotTest.cs
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
Labels: not-notes-worthy

#6650 [xammac tests] Silence debug spew.
  tests/monotouch-test/CoreGraphics/PDFDocumentTest.cs
Labels: not-notes-worthy

#6625 [xcode11] [IntentsUI] bindings for iOS beta1
  src/intentsui.cs
  tests/xtro-sharpie/iOS-IntentsUI.todo
Labels: community, note-highlight

#6662 [d16-3] bump mono-2019-06
  mk/mono.mk
Labels: not-notes-worthy

#6201 [CFNetwork] Expose methods that were ignored until the dependencies were present.
  src/CoreFoundation/CFProxySupport.cs
  tests/monotouch-test/CoreFoundation/ProxyTest.cs
  tests/monotouch-test/example.pac
  tests/monotouch-test/monotouch-test.csproj
  tests/xtro-sharpie/common-CFNetwork.ignore
Labels: build-package, note-highlight

#6663 [CFNetwork] Non-implementation of new API in Xcode 11 beta 1-4.
  tests/xtro-sharpie/common-CFNetwork.ignore
  tests/xtro-sharpie/iOS-CFNetwork.todo
  tests/xtro-sharpie/macOS-CFNetwork.todo
  tests/xtro-sharpie/tvOS-CFNetwork.todo
Labels: enhancement
