Repository dotnet/macios, pull requests merged in 2019-11, with the labels that each got.

#7347 Bump to Xcode 11.2 final
  Make.config
  tests/xtro-sharpie/iOS-ImageCaptureCore.todo
Labels: needs-babysitting-:baby_bottle:

#7356 [d16-4] Bump mono 2019-08@e1ef7743
  mk/mono.mk
Labels: needs-babysitting-:baby_bottle:

#7351 [runtime] Merge two identical code paths
  runtime/trampolines.m
Labels: not-notes-worthy

#7352 [runtime] Free `env-argv` in `xamarin-main`
  runtime/launcher.m
Labels: not-notes-worthy

#7313 [mmp] [mtouch] Expand error message for MM4162 and MT4162. Fixes #4286
  docs/website/mmp-errors.md
  docs/website/mtouch-errors.md
Labels: community

#7353 [Runtime] Enable the -Wshorten-64-to-32 flag and fix all warnings.
  Make.config
  runtime/bindings.m
  runtime/delegates.t4
  runtime/monotouch-debug.h
  runtime/monotouch-debug.m
  runtime/monotouch-main.m
  runtime/monotouch-support.h
  runtime/runtime.m
  runtime/trampolines-arm64.m
  runtime/trampolines-internal.h
  runtime/trampolines-invoke.m
  runtime/trampolines-x86_64.m
  runtime/trampolines.m
  runtime/xamarin-support.m
  runtime/xamarin/runtime.h
  runtime/xamarin/trampolines.h
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy

#7367 [xcode11.3] Bump mono to get mono archives.
  mk/mono.mk
Labels: not-notes-worthy, skip-api-comparison

#7365 Bump mono to get mono archives.
  mk/mono.mk
Labels: not-notes-worthy, skip-api-comparison

#7369 [Tests] Fix introspection failing due to a typo.
  tests/introspection/ApiTypoTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7346 Bring HttpClient from CoreFX.
  builds/Makefile
  mk/mono.mk
  src/Foundation/NSUrlSessionHandler.cs
  src/System.Net.Http/CFContentStream.cs
  src/System.Net.Http/CFNetworkHandler.cs
  tests/linker/ios/link sdk/HttpClientHandlerTest.cs
  tests/mmptest/src/MMPTest.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
  tests/mtouch/MTouch.cs
Labels: build-package, run-all-tests, run-internal-tests, skip-api-comparison, skip-device-tests

#7370 [d16-4] [Tests] Fix introspection failing due to a typo.
  tests/introspection/ApiTypoTest.cs
Labels: pr-change-not-shipping

#7378 [Install] Do not crash when the directory is not found.
  tools/install-source/Program.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7372 [d16-4] Update APIDIFF_REFERENCES to current stable
  Make.config
Labels: pr-change-not-shipping

#7380 [d16-4] [Install] Do not crash when the directory is not found.
  tools/install-source/Program.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7381 [xcode11.2] [Install] Do not crash when the directory is not found.
  tools/install-source/Program.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7282 [tests] Add make target to manually launch a device test run for the current commit.
  jenkins/Jenkinsfile
  tests/Makefile
  tests/launch-manual-device-tests.sh
Labels: not-notes-worthy, skip-public-jenkins

#7385 [Install] Ensure that sources from mono are included when building from source.
  tools/install-source/PathManglerFactory.cs
Labels: build-package, not-notes-worthy, pr-change-not-shipping

#7388 [xcode11.2] [Install] Ensure that sources from mono are included when building from source.
  tools/install-source/PathManglerFactory.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7390 [d16-4] [Install] Ensure that sources from mono are included when building from source.
  tools/install-source/PathManglerFactory.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7389 [xcode11.3] [Install] Ensure that sources from mono are included when building from source.
  tools/install-source/PathManglerFactory.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7391 [CoreFoundation] Ensure that we are thread safe.
  src/CoreFoundation/CFBundle.cs
Labels: not-notes-worthy

#7394 [Packaging] Ensure that when we build from source, the srcs go to the correct place.
  tools/install-source/InstallSourcesTests/MonoPathManglerTest.cs
  tools/install-source/MonoPathMangler.cs
  tools/install-source/PathManglerFactory.cs
Labels: build-package, not-notes-worthy

#7343 [CoreFoundation] [tests] Add new DispatchQueue overloaded method
  src/CoreFoundation/Dispatch.cs
  tests/bindings-test/ApiDefinition.cs
  tests/bindings-test/RuntimeTest.cs
  tests/monotouch-test/CoreFoundation/DispatchTests.cs
  tests/test-libraries/libtest.h
  tests/test-libraries/libtest.m
Labels: community

#7408 [d16-5] [Packaging] Ensure that when we build from source, the srcs go to the correct place.
  tools/install-source/InstallSourcesTests/MonoPathManglerTest.cs
  tools/install-source/MonoPathMangler.cs
  tools/install-source/PathManglerFactory.cs
Labels: not-notes-worthy

#7407 [xcode11.3] [Packaging] Ensure that when we build from source, the srcs go to the correct place.
  tools/install-source/InstallSourcesTests/MonoPathManglerTest.cs
  tools/install-source/MonoPathMangler.cs
  tools/install-source/PathManglerFactory.cs
Labels: not-notes-worthy

#7406 [xcode11.2] [Packaging] Ensure that when we build from source, the srcs go to the correct place.
  tools/install-source/InstallSourcesTests/MonoPathManglerTest.cs
  tools/install-source/MonoPathMangler.cs
  tools/install-source/PathManglerFactory.cs
Labels: not-notes-worthy

#7411 [runtime] Zeroize dummy member of structure in binding-generator
  runtime/bindings-generator.cs
Labels: not-notes-worthy

#7415 [xcode11.3] [Tests] If we have server errors. Mark test as inconclusive.
  tests/linker/mac/LinkAnyTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7417 [d16-4] [Tests] If we have server errors. Mark test as inconclusive.
  tests/linker/mac/LinkAnyTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7416 [d16-5] [Tests] If we have server errors. Mark test as inconclusive.
  tests/linker/mac/LinkAnyTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7419 [Tests] GetGlobalQueue_QualityOfService is only supported on Mac OS X 10.10 and later
  tests/monotouch-test/CoreFoundation/DispatchTests.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7414 [xcode11.2] [Tests] If we have server errors. Mark test as inconclusive.
  tests/linker/mac/LinkAnyTest.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7403 [CoreFoundation] Add Clone method for CFArray.
  src/CoreFoundation/CFArray.cs
  tests/xtro-sharpie/common-CoreFoundation.ignore
Labels: not-notes-worthy

#7420 [runtime] Filter isblank input to 8 bits values
  runtime/launcher.m
Labels: not-notes-worthy

#7424 [Jenkins] Make it possible to trigger device tests from PRs built on internal Jenkins.
  jenkins/Jenkinsfile
Labels: build-package, not-notes-worthy, skip-all-tests, skip-public-jenkins, trigger-device-tests

#7425 [CoreFoundation] CFBundle.GetAll better thread safe.
  src/CoreFoundation/CFBundle.cs
Labels: not-notes-worthy

#7421 [runtime] Catch and log exceptions in ObjC++ destructor
  runtime/runtime.m
Labels: not-notes-worthy

#7418 [Tests] Centralized the endpoints for the different network tests.
  tests/monotouch-test/AVFoundation/AVAssetDownloadUrlSessionTests.cs
  tests/monotouch-test/CoreFoundation/NetworkTest.cs
  tests/monotouch-test/CoreFoundation/ProxyTest.cs
  tests/monotouch-test/Foundation/NSDataTest.cs
  tests/monotouch-test/Foundation/UrlConnectionTest.cs
  tests/monotouch-test/Foundation/UrlProtocolTest.cs
  tests/monotouch-test/Foundation/UrlSessionTaskTest.cs
  tests/monotouch-test/Foundation/UrlSessionTest.cs
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
  tests/monotouch-test/Network/NWConnectionTest.cs
  tests/monotouch-test/Network/NWEstablishmentReportTest.cs
  tests/monotouch-test/Network/NWParametersTest.cs
  tests/monotouch-test/Network/NWPathTest.cs
  tests/monotouch-test/Network/NWProtocolIPOptionsTest.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
  tests/monotouch-test/example.pac
Labels: not-notes-worthy, pr-change-not-shipping

#7444 Bump mono to get archive built with Xcode 11.3 b1.
  mk/mono.mk
Labels: skip-api-comparison

#7454 Keep track of SDK versions and OS versions separately. Fixes xamarin/maccore#2066.
  tests/xharness/Simulators.cs
  tools/common/Make.common
  tools/common/SdkVersions.cs.in
Labels: not-notes-worthy

#7453 [d16-5] [generator] If forcing a managed type, we must do so even if there's another managed instance of an incompatible type. Fixes #7441.
  src/ObjCRuntime/Runtime.cs
  src/generator.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: bug

#7479 [Tests] Update tests.sln to include all the BCL tests.
  tests/tests.sln
Labels: not-notes-worthy, pr-change-not-shipping, skip-all-tests

#7480 [d16-5] [Tests] Update tests.sln to include all the BCL tests.
  tests/tests.sln
Labels: not-notes-worthy, pr-change-not-shipping, skip-all-tests

#7482 [xcode11.3] [Tests] Update tests.sln to include all the BCL tests.
  tests/tests.sln
Labels: not-notes-worthy, pr-change-not-shipping, skip-all-tests

#7491 [runtime] Comment two special cases that triggers static analysis tools
  runtime/monotouch-main.m
  tools/mtouch/simlauncher.mm
Labels: not-notes-worthy, skip-all-tests

#7460 [xcode11.3] [generator] If forcing a managed type, we must do so even if there's another managed instance of an incompatible type. Fixes #7441.
  src/ObjCRuntime/Runtime.cs
  src/generator.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: bug, requires-approval-before-merge

#7499 [xharness] Make sure to always stop log and system capture.
  tests/xharness/AppRunner.cs
Labels: not-notes-worthy
