Repository dotnet/macios, pull requests merged in 2020-01, with the labels that each got.

#7660 [generator] Remove unrequired `Class.GetHandle` calls on 32bits bindings
  src/generator.cs
Labels: enhancement

#7650 [mtouch] Fix cache.cs wrt response files. Fix #7514
  tools/common/cache.cs
Labels: bug, run-all-tests, skip-device-tests

#7649 [msbuild] Add verbosity options on separate lines for mtouch parsing
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/VerbosityUtils.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/VerbosityTest.cs
Labels: not-notes-worthy

#7662 [xharness] Only run 'dont link' on release configuration
  tests/xharness/Jenkins.cs
  tests/xharness/TestProject.cs
Labels: not-notes-worthy, pr-change-not-shipping, test-only-issue

#7680 [xcode11.3] [XHarness] If there are issues generating the BCL tests for mac don't crash.
  mk/mono.mk
  tools/bcl-test-importer/BCLTestImporter/BCLTestProjectGenerator.cs
Labels: disable-packaged-mono

#7668 [msbuild] Stub out GenerateManifests to prevent Windows ClickOnce target collisions
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.NativeReference.Stubs.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
Labels: msbuild

#7698 [msbuild] Convert project files to sdk-style project files.
  msbuild/.gitignore
  msbuild/Makefile
  msbuild/Xamarin.Mac.Tasks.Core/Xamarin.Mac.Tasks.Core.csproj
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
  msbuild/Xamarin.MacDev.Tasks.Core/Properties/AssemblyInfo.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
  msbuild/Xamarin.MacDev.Tasks/Properties/AssemblyInfo.cs
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TargetTests/TargetTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/CollectITunesArtworkTaskTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/MTouchTaskTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TestHelpers/TestBase.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
  tests/.gitignore
  tests/Makefile
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy

#7703 [xharness] Fix two compiler warnings.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy

#7713 [xcode11.3][devops] Bump maccore to update provisioning script
  mk/xamarin.mk
Labels: not-notes-worthy, pr-change-not-shipping, skip-all-tests

#7714 [d16-5][devops] Bump maccore to update provisioning script
  mk/xamarin.mk
Labels: not-notes-worthy, pr-change-not-shipping, skip-all-tests

#7721 Bump to the latest xcode11.3 API diff
  Make.config
Labels: pr-change-not-shipping

#7725 Bump to the latest xcode11.3 API diff
  Make.config
Labels: pr-change-not-shipping

#7726 [jenkins] Fix a couple of issues.
  jenkins/Jenkinsfile
Labels: not-notes-worthy

#7735 [registrar] Fixes NSString trampoline code generation in static registrar
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tools/common/StaticRegistrar.cs
Labels: regression

#7739 Produce the API diff based on 13.8 (not 13.6)
  Make.config
Labels: pr-change-not-shipping

#7736 [d16-5] [Mtouch] Make sure that the given SDK version and the iOS version do match.
  Make.config
  builds/Makefile
  tools/common/Application.cs
  tools/common/Make.common
  tools/common/SdkVersions.cs.in
Labels: do-not-merge

#7755 [Xharness] Add workaround when we could not share the internet in bots.
  tests/xharness/AppRunner.cs
Labels: build-package, trigger-device-tests

#7763 [tests][sampletester] Only provide '/verbosity:diag' one time
  tests/sampletester/ProcessHelper.cs
Labels: not-notes-worthy

#7758 [SampleTester] Add 4 new samples
  tests/sampletester/ProcessHelper.cs
  tests/sampletester/SampleTester.cs
  tests/sampletester/Samples.cs
Labels: build-package, not-notes-worthy, run-sample-tests, skip-all-tests, skip-public-jenkins

#7766 [tests][sampletester] Allow project(s) removal
  tests/sampletester/SampleTester.cs
  tests/sampletester/Samples.cs
Labels: build-package, not-notes-worthy, run-sample-tests, skip-all-tests, skip-public-jenkins

#7537 Bump to mono:2019-12
  Make.config
  mk/mono.mk
Labels: run-all-tests, run-internal-tests, skip-api-comparison, skip-device-tests, trigger-device-tests

#7774 Add AVCaptureVideoStabilizationMode.CinematicExtended
  src/AVFoundation/Enums.cs
Labels: community

#7776 Bump maccore (updated submission runner)
  mk/xamarin.mk
Labels: not-notes-worthy

#7710 [Localization] mtouch/mmp C#
  msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
  src/Makefile
  src/ObjCRuntime/Registrar.cs
  src/ObjCRuntime/RuntimeOptions.cs
  tests/introspection/ApiFrameworkTest.cs
  tests/introspection/ApiTypoTest.cs
  tests/mmptest/mmptest.csproj
  tests/mtouch/MTouch.cs
  tests/mtouch/RegistrarTest.cs
  tests/mtouch/mtouch.csproj
  tools/common/Application.cs
  tools/common/Assembly.cs
  tools/common/BuildTasks.cs
  tools/common/CompilerFlags.cs
  tools/common/CoreResolver.cs
  tools/common/Driver.cs
  tools/common/FileCopier.cs
  tools/common/Frameworks.cs
  tools/common/MachO.cs
  tools/common/Optimizations.cs
  tools/common/StaticRegistrar.cs
  tools/common/Symbols.cs
  tools/common/Target.cs
  tools/common/Tuning.cs
  tools/linker/CoreOptimizeGeneratedCode.cs
  tools/linker/CoreTypeMapStep.cs
  tools/linker/MobileExtensions.cs
  tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversionsSubStep.cs
  tools/linker/MonoTouch.Tuner/RemoveBitcodeIncompatibleCodeStep.cs
  tools/mmp/Assembly.cs
  tools/mmp/Tuning.cs
  tools/mmp/aot.cs
  tools/mmp/driver.cs
  tools/mmp/mmp.csproj
  tools/mmp/packages.config
  tools/mtouch/Application.cs
  tools/mtouch/Assembly.cs
  tools/mtouch/BitcodeConverter.cs
  tools/mtouch/BuildTasks.mtouch.cs
  tools/mtouch/Target.cs
  tools/mtouch/Tuning.cs
  tools/mtouch/errors.Designer.cs
  tools/mtouch/errors.resx
  tools/mtouch/mtouch.cs
  tools/mtouch/mtouch.csproj
  tools/mtouch/packages.config
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: do-not-merge
