Repository dotnet/macios, pull requests merged in 2020-11, with the labels that each got.

#10016 [appkit] Fix introspection tests for NSAccessibility on macOS 10.9
  src/AppKit/NSAccessibility.cs
  src/appkit.cs
  tests/introspection/ApiAvailabilityTest.cs
Labels: not-notes-worthy, run-internal-tests, test-only-issue

#10024 [d16-8][Make] Update the path of xcode12 to the stable one.
  Make.config
Labels: not-notes-worthy

#10025 [Xcode12.1][Makefile] Point to the correct path of xcode12 stable.
  Make.config
Labels: not-notes-worthy

#10029 [jenkins] Add missing eol to pr comments.
  jenkins/build.sh
Labels: not-notes-worthy, run-sample-tests, skip-all-tests

#10023 [Makefile] Update the path of xcode to be stable.
  Make.config
Labels: not-notes-worthy

#10028 [Xcode12.1][Actions] Backport labels action to stable branch.
  .github/workflows/label-checker.yml
Labels: not-notes-worthy

#10031 [tests] Update .NET unit tests to parse the binlog.
  tests/common/BinLog.cs
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/BuildEngine.cs
Labels: not-notes-worthy, run-dotnet-tests

#10032 [VSTS] Continue even if we could not clean the HD, we might have space.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy

#10036 add tools/devops/python-dependencies.txt
  tools/devops/python-dependencies.txt
Labels: not-notes-worthy

#10034 [VSTS] Remove the UI prompt ASAP.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy

#9995 [dotnet] Add atlas textures to the our items included by default.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
  tests/common/DotNet.cs
Labels: not-notes-worthy, run-dotnet-tests

#10018 Generate default compilation includes for pdf image assets.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
Labels: community, run-dotnet-tests

#10020 [tests] Bump sampletester hashes to pick up fixes
  tests/sampletester/Samples.cs
Labels: build-package, not-notes-worthy, run-sample-tests, skip-all-tests

#10040 [tests] Re-enable a test that requires msbuild (as opposed to xbuild).
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/CodesignAppBundle.cs
Labels: enable-device-build, not-notes-worthy, run-msbuild-tests

#10039 [msbuild] Share the app extensions targets between iOS and Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: enable-device-build, not-notes-worthy, run-dotnet-tests, run-msbuild-tests

#10038 [msbuild] Add CoreML models to our items included by default.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/DotNet.cs
Labels: not-notes-worthy, run-dotnet-tests

#10022 [msbuild] Adding W0111 Translations
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationIgnore/common-Translations.ignore
Labels: msbuild, not-notes-worthy

#9866 [generator] Remove generated availability attribute duplicates (and some incorrect ones)
  src/generator-attribute-manager.cs
  src/generator.cs
Labels: enhancement

#10041 [tests] Re-enable the ReleaseBuild.RebuildTest, since we're using msbuild exclusively now.
  tests/common/TestProjects/MyReleaseBuild/MyReleaseBuildLlvm.csproj
  tests/common/TestProjects/MyReleaseBuild/MyReleaseBuildLlvm.dotnet.csproj
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/ReleaseBuild.cs
Labels: enable-device-build, not-notes-worthy, run-msbuild-tests

#10044 [dotnet] Add app extension targets to our list of stuff to do during the build.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/DotNet.cs
  tests/common/TestProjects/MyActionExtension/MyActionExtension.dotnet.csproj
  tests/common/TestProjects/MyDocumentPickerExtension/MyDocumentPickerExtension.dotnet.csproj
  tests/common/TestProjects/MyExtensionWithPackageReference/MyExtensionWithPackageReference.dotnet.csproj
  tests/common/TestProjects/MyKeyboardExtension/MyKeyboardExtension.dotnet.csproj
  tests/common/TestProjects/MyPhotoEditingExtension/MyPhotoEditingExtension.dotnet.csproj
  tests/common/TestProjects/MyShareExtension/MyShareExtension.dotnet.csproj
  tests/common/TestProjects/MyTVServicesExtension/MyTVServicesExtension.dotnet.csproj
  tests/common/TestProjects/MyTodayExtension/MyTodayExtension.dotnet.csproj
  tests/common/TestProjects/MyWatchApp2/MyWatchApp2.dotnet.csproj
  tests/common/TestProjects/MyWatchKit2Extension/MyWatchKit2Extension.dotnet.csproj
  tests/common/TestProjects/MyWatchKit2IntentsExtension/MyWatchKit2IntentsExtension.dotnet.csproj
  tests/common/TestProjects/MyiOSFrameworkBinding/MyiOSFrameworkBinding.dotnet.csproj
Labels: enable-device-build, not-notes-worthy, run-dotnet-tests, run-msbuild-tests

#10050 [msbuild] Share targets related to Collada assets between iOS and Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-msbuild-tests

#10049 [msbuild] Add Metal files to our items included by default.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/DotNet.cs
Labels: not-notes-worthy, run-dotnet-tests, run-msbuild-tests

#10045 [Makefile] Respect the configuration of dotnet after the make clean.
  Makefile
Labels: not-notes-worthy

#10043 [d16-7] [tests] Bump sampletester hashes to pick up fixes
  tests/sampletester/Samples.cs
Labels: pr-change-not-shipping

#10042 [d16-8] [tests] Bump sampletester hashes to pick up fixes
  tests/sampletester/Samples.cs
Labels: pr-change-not-shipping

#10057 [tests] Disable XM samples that use QTKit, ibtool won't compile their nib anymore
  tests/sampletester/Samples.cs
Labels: pr-change-not-shipping

#10058 [VSTS] Make the pipeline build and notarize the pkgs
  .gitignore
  tools/devops/Makefile
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/productsign.sh
  tools/devops/build-provisioning.csx.in
  tools/devops/provision-brew-packages.csx
  tools/devops/provision-xcode.csx
  tools/devops/python-dependencies.txt
Labels: not-notes-worthy

#10053 [msbuild] Add SceneKit assets to our items included by default.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
Labels: not-notes-worthy, run-dotnet-tests, run-msbuild-tests

#10055 [dotnet] Fix MSBuild syntax.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
Labels: not-notes-worthy, run-dotnet-tests

#10060 Bump Xcode 12.2 to RC
  Make.config
Labels: not-notes-worthy

#10069 [mono] Bump mono to match android
  mk/mono.mk
Labels: notes-mention

#10077 [VSTS] Upload pacakges to azure and set statuses.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/scripts/GitHub.Tests.ps1
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/scripts/MLaunch.Tests.ps1
  tools/devops/automation/scripts/MLaunch.psm1
  tools/devops/automation/scripts/Makefile
  tools/devops/automation/scripts/System.Tests.ps1
  tools/devops/automation/scripts/System.psm1
  tools/devops/automation/scripts/VSTS.Tests.ps1
  tools/devops/automation/scripts/VSTS.psm1
  tools/devops/automation/templates/build-packages.yml
  tools/devops/automation/templates/device-tests.yml
  tools/devops/automation/templates/upload-azure.yml
  tools/devops/provision-brew-packages.csx
Labels: not-notes-worthy

#10078 [VSTS] Add missing 'package' in the url prefix.
  tools/devops/automation/templates/upload-azure.yml
Labels: not-notes-worthy

#10064 [dotnet-linker] Improve error reporting
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
  tools/dotnet-linker/Steps/ConfigurationAwareSubStep.cs
Labels: not-notes-worthy, run-dotnet-tests

#10062 [mmp] Fix link path for Stripper.cs
  tools/mmp/mmp.csproj
Labels: not-notes-worthy

#10061 [dotnet] Add _CreateDebugSettings, _CreateDebugConfiguration and _CreatePkgInfo to the targets we run on app creation.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/DotNet.cs
Labels: not-notes-worthy, run-dotnet-tests

#10065 [tools] Add all our product constants to SdkVersions.cs and use them in dotnet-linker.
  tools/common/Application.cs
  tools/common/Driver.cs
  tools/common/Make.common
  tools/common/SdkVersions.cs.in
  tools/common/cache.cs
  tools/dotnet-linker/Constants.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy, run-dotnet-tests

#10082 [mmp] Fix the build.
  tools/mmp/driver.cs
Labels: not-notes-worthy

#10085 Re-enable provisioning steps
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build-packages.yml
Labels: not-notes-worthy

#10081 [dotnet-linker] Remove AssemblyResolver.cs from the project, it's not needed.
  tools/dotnet-linker/dotnet-linker.csproj
Labels: not-notes-worthy

#10083 [dotnet] We're not doing anything with regards to the http handler, so we won't have a runtime-options.plist.
  tests/common/DotNet.cs
Labels: not-notes-worthy, run-dotnet-tests

#10080 [msbuild] Remove unnecessary properties in Xamarin.Mac.Common.targets.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
Labels: not-notes-worthy

#10073 [tests] Update framework tests not to embed/zip the native binaries
  tests/bindings-framework-test/XTest.framework.linkwith.cs
  tests/bindings-framework-test/bindings-framework-test.csproj
  tests/common/TestProjects/MyiOSFrameworkBinding/MyiOSFrameworkBinding.csproj
  tests/common/TestProjects/MyiOSFrameworkBinding/MyiOSFrameworkBinding.dotnet.csproj
  tests/mtouch/MTouch.cs
  tests/mtouch/mtouch.csproj
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Labels: not-notes-worthy, pr-change-not-shipping

#10090 Update CODEOWNERS. :wave:
  CODEOWNERS
Labels: not-notes-worthy

#10092 [VSMac] Bump max version to current stable.
  Make.config
Labels: not-notes-worthy

#10099 [fileprovider] Fix breaking change
  src/FileProvider/Compat.cs
Labels: not-notes-worthy

#10100 [ApiTests] Add missing dot.
  src/FileProvider/Compat.cs
Labels: not-notes-worthy

#10101 [Maccore] Bump maccore to fix governance issues.
  mk/xamarin.mk
Labels: not-notes-worthy

#10104 [Xcode12.2][Make] Point to the correct xcode12.2 final app and path.
  Make.config
Labels: not-notes-worthy

#10105 [Maccore] Bump maccore to remove old not needed code.
  mk/xamarin.mk
Labels: not-notes-worthy

#10102 [jenkins] Clean more Xcodes.
  jenkins/clean-jenkins-bots.sh
Labels: not-notes-worthy

#10103 [xharness] Bring back special processing of GuiUnit for Xamarin.Mac test projects.
  tests/xharness/Targets/MacTarget.cs
Labels: not-notes-worthy, pr-change-not-shipping

#10110 [msbuild] Stop allowing a watch family for iOS apps.
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ValidateAppBundleTaskBase.cs
Labels: not-notes-worthy

#10111 [msbuild] Use localized error strings instead of constants for a few errors.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileEntitlementsTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
Labels: not-notes-worthy

#10114 [Maccore] Bump maccore to fix governance issues.
  mk/xamarin.mk
Labels: not-notes-worthy

#10116 [VSTS] Start running tests on the pipeline
  mk/xamarin.mk
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/agent-pool-selector.yml
  tools/devops/automation/templates/build-packages.yml
  tools/devops/automation/templates/device-tests-stage.yml
  tools/devops/automation/templates/device-tests.yml
  tools/devops/automation/templates/download-artifacts.yml
  tools/devops/automation/templates/governance-checks.yml
  tools/devops/automation/templates/mac-tests.yml
  tools/devops/automation/templates/publish-html.yml
  tools/devops/automation/templates/upload-azure.yml
  tools/devops/automation/templates/upload-vsdrops.yml
  tools/devops/automation/templates/upload-vsts-tests.yml
Labels: not-notes-worthy

#10117 [msbuild] Fix missing localization in error
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/PrepareNativeReferencesTaskBase.cs
Labels: not-notes-worthy

#10120 [VSTS] Multiline bash needs a pipe.
  tools/devops/automation/templates/build-packages.yml
Labels: not-notes-worthy

#10122 [mlaunch] Adjust build logic to ship mlaunch with the .NET nugets when we're building mlaunch as well.
  tools/mlaunch/Makefile
Labels: not-notes-worthy, run-dotnet-tests

#10125 [VSTS] Fix borken pwsh.
  tools/devops/automation/templates/build-packages.yml
Labels: not-notes-worthy

#10059 [main][watchOS] Add x86_64 simulator support
  Make.config
  dotnet/package/Microsoft.watchOS.Runtime.watchos-x64/package.csproj
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  mk/rules.mk
  runtime/Makefile
  src/Makefile
  src/ObjCRuntime/Registrar.cs
  tests/mtouch/MTouch.cs
  tests/test-libraries/Makefile
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Targets/WatchOSTarget.cs
  tests/xharness/TestImporter/Templates/Managed/Resources/Managed.watchOS.App.csproj.in
  tests/xharness/TestImporter/Templates/Managed/Resources/Managed.watchOS.Extension.csproj.in
  tools/common/Application.cs
  tools/mtouch/Makefile
  tools/mtouch/mtouch.cs
Labels: note-highlight

#10118 [VSTS] Add support to get the info of a PR.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/scripts/GitHub.Tests.ps1
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/configure-build.yml
  tools/devops/automation/templates/device-tests.yml
  tools/devops/automation/templates/publish-html.yml
Labels: not-notes-worthy

#10128 [VSTS] Fix dev tests conditions.
  tools/devops/automation/templates/device-tests-stage.yml
Labels: not-notes-worthy

#10131 [VSTS] Parse labels and add them as output vars fro the rest of the stages.
  tools/devops/automation/templates/configure-build.yml
Labels: build-package, not-notes-worthy

#10123 [tools] Disable Objective-C exception handling for macOS .NET apps due to a missing feature in the runtime.
  tools/common/Target.cs
Labels: not-notes-worthy, run-dotnet-tests

#10127 [dotnet] Don't link the main executable with any dylibs on macOS.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#10130 [runtime] Simplify code for custom mono bundle name a bit by using a default value for the 'xamarin_custom_bundle_name' variable.
  runtime/launcher.m
  runtime/runtime.m
Labels: not-notes-worthy

#10126 [dotnet] Add an issue for a missing Mono.framework, which isn't on us for now.
  tests/common/DotNet.cs
Labels: not-notes-worthy

#10135 [xcode12.3] Initial bump to Xcode 12.3 Beta 1
  Make.config
  Make.versions
  Versions-ios.plist.in
  Versions-mac.plist.in
  tests/xtro-sharpie/iOS-ARKit.todo
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/iOS-AdServices.todo
  tests/xtro-sharpie/iOS-Contacts.todo
  tests/xtro-sharpie/iOS-CoreImage.todo
  tests/xtro-sharpie/iOS-CoreMotion.todo
  tests/xtro-sharpie/iOS-GameController.todo
  tests/xtro-sharpie/iOS-HealthKit.todo
  tests/xtro-sharpie/iOS-ImageIO.todo
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/macOS-AVFoundation.todo
  tests/xtro-sharpie/macOS-AdServices.todo
  tests/xtro-sharpie/macOS-Contacts.todo
  tests/xtro-sharpie/macOS-ContextualActionsClient.ignore
  tests/xtro-sharpie/macOS-CoreImage.todo
  tests/xtro-sharpie/macOS-CoreMotion.todo
  tests/xtro-sharpie/macOS-GameController.todo
  tests/xtro-sharpie/macOS-ImageIO.todo
  tests/xtro-sharpie/macOS-NetworkExtension.todo
  tests/xtro-sharpie/tvOS-AVFoundation.todo
  tests/xtro-sharpie/tvOS-CoreImage.todo
  tests/xtro-sharpie/tvOS-GameController.todo
  tests/xtro-sharpie/tvOS-ImageIO.todo
  tests/xtro-sharpie/tvOS-TVServices.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-AVFoundation.todo
  tests/xtro-sharpie/watchOS-Contacts.todo
  tests/xtro-sharpie/watchOS-CoreMotion.todo
  tests/xtro-sharpie/watchOS-HealthKit.todo
  tests/xtro-sharpie/watchOS-ImageIO.todo
Labels: note-highlight

#10136 [src] Don't generate a reference assembly for both the 32-bit and 64-bit variant of Xamarin.WatchOS.dll.
  src/Makefile
Labels: not-notes-worthy

#10124 [tools] Set xamarin_executable_name in main for macOS .NET apps.
  tools/common/Target.cs
Labels: not-notes-worthy, run-dotnet-tests

#10138 [VSTS] Perform configuration pkgs in the pipeline
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build-packages.yml
  tools/devops/automation/templates/configure-build.yml
  tools/devops/automation/templates/device-tests-stage.yml
  tools/devops/automation/templates/mac-tests.yml
  tools/devops/provision-brew-packages.csx
Labels: not-notes-worthy, trigger-device-tests

#10142 [tests][monotouch] Fix recent CGColorSpace tests not to fail on macOS 10.15.x
  tests/monotouch-test/CoreGraphics/ColorSpaceTest.cs
Labels: not-notes-worthy, test-only-issue

#10088 [arkit] Add nullability for manual bindings
  src/ARKit/ARCompat.cs
  src/ARKit/ARFaceGeometry.cs
  src/ARKit/ARPlaneGeometry.cs
  src/ARKit/ARPointCloud.cs
  src/ARKit/ARSkeleton.cs
  src/ARKit/ARSkeleton2D.cs
  src/ARKit/ARSkeleton3D.cs
  src/Makefile
Labels: enhancement

#10151 [VSTS] Move the build pkgs to a template, since we will need to add extra jobs for the html publishing.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build-packages-stage.yml
Labels: not-notes-worthy

#10140 Ensure the pip virtualenv command is on the PATH
  tools/devops/automation/templates/build-packages.yml
Labels: not-notes-worthy

#10153 [VSTS] Add a reasonable timeout to the profiles provisioning.
  tools/devops/automation/templates/device-tests.yml
Labels: not-notes-worthy

#10152 [VSTS] Make it clear what device test is running.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/device-tests-stage.yml
Labels: not-notes-worthy

#10154 [VSTS] Fix code that add the summary to the vsts UI.
  tools/devops/automation/templates/device-tests.yml
Labels: not-notes-worthy

#10147 [msbuild] Default to verbose logs for mmp/mtouch if creating a binary log.
  msbuild/Xamarin.MacDev.Tasks.Core/VerbosityUtils.cs
Labels: enhancement, notes-mention

#10155 [corevideo] Update for Xcode 12.2 RC
  src/CoreVideo/CVPixelFormatType.cs
  tests/monotouch-test/CoreVideo/CoreVideoEnumsTest.cs
Labels: enhancement

#10157 [tests] Remove empty xtro files
  tests/xtro-sharpie/iOS-CarPlay.todo
  tests/xtro-sharpie/iOS-CoreGraphics.todo
  tests/xtro-sharpie/iOS-HealthKit.todo
  tests/xtro-sharpie/iOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/macOS-CoreFoundation.todo
  tests/xtro-sharpie/macOS-CoreGraphics.todo
  tests/xtro-sharpie/macOS-CoreML.ignore
  tests/xtro-sharpie/macOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/tvOS-CoreGraphics.todo
  tests/xtro-sharpie/tvOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/tvOS-Vision.todo
  tests/xtro-sharpie/watchOS-CoreGraphics.todo
  tests/xtro-sharpie/watchOS-HealthKit.todo
Labels: not-notes-worthy

#10150 [avkit] Add nullability for manual bindings
  src/AVKit/AVPlayerViewController.cs
  src/AVKit/Enums.cs
Labels: enhancement

#10144 [mac] Add user-framework support for Xamarin.Mac
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CollectFrameworksBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CollectFrameworks.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/bindings-framework-test/ApiDefinition.cs
  tests/bindings-framework-test/StructsAndEnums.cs
  tests/bindings-framework-test/bindings-framework-test-mac.csproj
  tests/framework-test/iOS/AppDelegate.cs
  tests/framework-test/iOS/Entitlements.plist
  tests/framework-test/iOS/FrameworkTests.cs
  tests/framework-test/iOS/Info.plist
  tests/framework-test/iOS/Main.cs
  tests/framework-test/iOS/Resources/Default-568h@2x.png
  tests/framework-test/iOS/framework-test-ios.csproj
  tests/framework-test/macOS/Info.plist
  tests/framework-test/macOS/framework-test-mac.csproj
  tests/tests-mac.sln
  tests/xharness/Harness.cs
Labels: note-highlight

#10159 [uikit] Update for Xcode 12.2 RC
  src/uikit.cs
Labels: enhancement

#10158 [ARKit] Update bindings to Xcode 12.3 Beta 1
  src/arkit.cs
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/xtro-sharpie/iOS-ARKit.todo
Labels: note-highlight

#10160 [assetslibrary] Add nullability for manual bindings
  src/AssetsLibrary/ALAsset.cs
  src/AssetsLibrary/ALAssetsGroup.cs
  src/AssetsLibrary/Enums.cs
Labels: enhancement

#10169 [src/mtouch] Put implementation assemblies in a per-platform directory
  src/Makefile
  tests/cecil-tests/Helper.cs
  tests/xtro-sharpie/Makefile
  tests/xtro-sharpie/xtro-sharpie.csproj
  tools/mtouch/Makefile
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#10173 [src] Reintroduce namespaces as constants to simplify code.
  src/generator-filters.cs
  src/generator.cs
Labels: not-notes-worthy

#10176 [src] Improve the generate-frameworks.csharp script.
  src/Makefile.generator
  src/generate-frameworks.csharp
Labels: not-notes-worthy

#10174 [msbuild] Remove unnecessary validation of the SdkPlatform.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
Labels: not-notes-worthy

#10172 [tests] Re-enable MediaAccessibility/ImageCaptioningTest.cs` `SetCaption` test
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
Labels: pr-change-not-shipping, test-only-issue

#10161 [accounts] Add nullability for manual bindings
  src/Accounts/AccountStoreOptions.cs
  src/Accounts/Enums.cs
  src/ObjCRuntime/ThrowHelper.cs
Labels: enhancement

#10180 [MetricKit] Don't use deprecated API to check system version.
  src/MetricKit/MXMetaData.cs
  src/MetricKit/MXMetric.cs
  src/MetricKit/MXMetricPayload.cs
Labels: not-notes-worthy

#10046 [msbuild] Add support for `.xcframework`
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Properties/AssemblyInfo.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveFrameworksBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
  msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferences.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/bindings-framework-test/StructsAndEnums.cs
  tests/bindings-xcframework-test/bindings-xcframework-test-mac.csproj
  tests/bindings-xcframework-test/bindings-xcframework-test.csproj
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/Resources/xcf-prexcode12.plist
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/Resources/xcf-xcode12.2.plist
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationIgnore/common-Translations.ignore
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ResolveNativeReferencesTaskTest.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/NativeReferencesNoEmbedding.cs
  tests/test-libraries/Makefile
  tests/tests.sln
  tests/xcframework-test/iOS/AppDelegate.cs
  tests/xcframework-test/iOS/Entitlements.plist
  tests/xcframework-test/iOS/Info.plist
  tests/xcframework-test/iOS/Main.cs
  tests/xcframework-test/iOS/Resources/Default-568h@2x.png
  tests/xcframework-test/iOS/XCFrameworkTests.cs
  tests/xcframework-test/iOS/xcframework-test-ios.csproj
  tests/xcframework-test/macOS/Info.plist
  tests/xcframework-test/macOS/xcframework-test-mac.csproj
  tests/xharness/Harness.cs
  tools/common/Assembly.cs
Labels: enhancement

#10177 [metal] Update Xcode 12.2 final
  src/Metal/MTLEnums.cs
Labels: enhancement

#10181 [uikit] Update for Xcode 12.3 beta 1
  src/UIKit/UIEnums.cs
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
Labels: enhancement

#10162 [AVFoundation] Update bindings to Xcode 12.3 Beta 1
  src/avfoundation.cs
  tests/introspection/ApiAvailabilityTest.cs
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/macOS-AVFoundation.todo
  tests/xtro-sharpie/tvOS-AVFoundation.todo
  tests/xtro-sharpie/watchOS-AVFoundation.ignore
  tests/xtro-sharpie/watchOS-AVFoundation.todo
Labels: note-highlight

#10184 [tvservices] Update for Xcode 12.3 beta 1
  src/tvservices.cs
  tests/xtro-sharpie/tvOS-TVServices.todo
Labels: enhancement

#10143 [VSTS] Use the rest API to workaround the fact that we build from forks.
  tools/devops/automation/scripts/VSTS.psm1
  tools/devops/automation/templates/configure-build.yml
Labels: not-notes-worthy
