Repository dotnet/macios, pull requests merged in 2020-02, with the labels that each got.

#7778 [msbuild] Remove unused csproj variable.
  msbuild/tests/AppWithExtraArgumentThatOverrides/AppWithExtraArgumentThatOverrides.csproj
  msbuild/tests/Bug60536/Bug60536.csproj
  msbuild/tests/MyCoreMLApp/MyCoreMLApp.csproj
  msbuild/tests/MyIBToolLinkTest/MyIBToolLinkTest.csproj
  msbuild/tests/MyLinkedAssets/MyLinkedAssets.csproj
  msbuild/tests/MyReleaseBuild/MyReleaseBuild.csproj
  msbuild/tests/MyReleaseBuild/MyReleaseBuildLlvm.csproj
  msbuild/tests/MySceneKitApp/MySceneKitApp.csproj
Labels: not-notes-worthy

#7777 [msbuild] Remove outdated AppStore and Ad-Hoc configurations from test projects.
  msbuild/tests/MyActionExtension/MyActionExtension.csproj
  msbuild/tests/MyDocumentPickerExtension/MyDocumentPickerExtension.csproj
  msbuild/tests/MyKeyboardExtension/MyKeyboardExtension.csproj
  msbuild/tests/MyMasterDetailApp/MyMasterDetailApp.csproj
  msbuild/tests/MyMetalGame/MyMetalGame.csproj
  msbuild/tests/MyOpenGLApp/MyOpenGLApp.csproj
  msbuild/tests/MyPhotoEditingExtension/MyPhotoEditingExtension.csproj
  msbuild/tests/MyShareExtension/MyShareExtension.csproj
  msbuild/tests/MySingleView/MySingleView.csproj
  msbuild/tests/MySingleView/MySingleView.sln
  msbuild/tests/MySpriteKitGame/MySpriteKitGame.csproj
  msbuild/tests/MyTabbedApplication/MyTabbedApplication.csproj
  msbuild/tests/MyTodayExtension/MyTodayExtension.csproj
  msbuild/tests/MyWatchApp/MyWatchApp.csproj
  msbuild/tests/MyWatchApp/MyWatchApp.sln
  msbuild/tests/MyWatchKitApp/MyWatchKitApp.csproj
  msbuild/tests/MyWatchKitExtension/MyWatchKitExtension.csproj
  msbuild/tests/MyWebViewApp/MyWebViewApp.csproj
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/Extensions/WatchKit.cs
Labels: not-notes-worthy

#7781 [mtouch] Auto-change settings where they're honored for extensions. Fixes #7780.
  tests/mtouch/MTouch.cs
  tools/mtouch/Application.cs
  tools/mtouch/mtouch.cs
Labels: bug

#7784 [Localization] Fix mtouch/mmp errors being referenced in mlaunch
  mk/xamarin.mk
  tools/common/MachO.cs
Labels: build-package

#7786 [mtouch] Auto-change settings where they're honored for extensions. Fixes #7780.
  tests/mtouch/MTouch.cs
  tools/mtouch/Application.cs
  tools/mtouch/mtouch.cs
Labels: bug

#7785 [d16-5][tests][sampletester] Backport fixes from master
  tests/sampletester/BaselineTest/AppDelegate.cs
  tests/sampletester/BaselineTest/BaselineTest.csproj
  tests/sampletester/BaselineTest/BaselineTest.sln
  tests/sampletester/BaselineTest/Info.plist
  tests/sampletester/BaselineTest/LaunchScreen.storyboard
  tests/sampletester/Configuration.cs
  tests/sampletester/ProcessHelper.cs
  tests/sampletester/SampleTester.cs
  tests/sampletester/Samples.cs
  tests/sampletester/sampletester.sln
  tools/devops/build-samples.sh
  tools/devops/build-samples.yml
  tools/devops/fetch-maccore.sh
  tools/devops/prepare-performance-data.sh
  tools/devops/push-performance-data.sh
  tools/devops/system-info.sh
  tools/mmp/driver.cs
Labels: note-highlight

#7768 [Xharness] Fix all xml parsing issues and ensure that the xml can be consumed by VSTS.
  tests/bcl-test/BCLTests-mac.csproj.in
  tests/bcl-test/BCLTests-tv.csproj.in
  tests/bcl-test/BCLTests-watchos-extension.csproj.in
  tests/bcl-test/BCLTests.csproj.in
  tests/bcl-test/templates/common/TestRunner.NUnit/NUnitTestRunner.cs
  tests/bcl-test/templates/common/TestRunner.NUnit/XmlOutputWriter.cs
  tests/bcl-test/templates/common/TestRunner.xUnit/XUnitTestRunner.cs
  tests/xharness/AppRunner.cs
  tests/xharness/SimpleTcpListener.cs
Labels: build-package, run-internal-tests, trigger-device-tests

#7790 [msbuild] Make code a bit more future-proof.
  msbuild/ILMerge.targets
Labels: not-notes-worthy

#7801 [msbuild] Remove unused files.
  msbuild/tests/MySingleView/CustomViewController.cs
  msbuild/tests/MySingleView/CustomViewController.designer.cs
  msbuild/tests/MySingleView/Entitlements.plist.tmp
Labels: not-notes-worthy

#7804 [msbuild] Fix several issues in the MyWatchApp2 test project.
  msbuild/tests/MyWatchApp2/MyWatchApp2.csproj
  msbuild/tests/MyWatchApp2/Resources/Images.xcassets/AppIcons.appiconset/Contents.json
  msbuild/tests/MyWatchApp2/Resources/Images.xcassets/AppIcons.appiconset/Icon-44x44@2x.png
  msbuild/tests/MyWatchApp2/Resources/Images.xcassets/AppIcons.appiconset/Icon1024x1024.png
Labels: not-notes-worthy

#7798 [mtouch] Fix tests broken by localization
  tools/common/Application.cs
  tools/mtouch/Application.cs
  tools/mtouch/errors.Designer.cs
  tools/mtouch/errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: build-package, enable-device-build, trigger-device-tests

#7810 [d16-5] Cherry-picked all xharness fixes done for Xml parsing.
  tests/bcl-test/BCLTests-mac.csproj.in
  tests/bcl-test/BCLTests-tv.csproj.in
  tests/bcl-test/BCLTests-watchos-extension.csproj.in
  tests/bcl-test/BCLTests.csproj.in
  tests/bcl-test/templates/common/TestRunner.NUnit/NUnitTestRunner.cs
  tests/bcl-test/templates/common/TestRunner.NUnit/XmlOutputWriter.cs
  tests/bcl-test/templates/common/TestRunner.xUnit/XUnitTestRunner.cs
  tests/xharness/AppRunner.cs
  tests/xharness/BCLTestImporter/BCLTestImportTargetFactory.cs
  tests/xharness/Harness.cs
  tests/xharness/Jenkins.cs
  tests/xharness/MakefileGenerator.cs
  tests/xharness/SimpleTcpListener.cs
  tests/xharness/XmlResultParser.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy, pr-change-not-shipping

#7822 Update sampletester docs and fix typos
  runtime/runtime.m
  tests/sampletester/README.md
Labels: not-notes-worthy

#7821 [objcruntime] Fix CS0105 warning in Registrar.cs
  src/ObjCRuntime/Registrar.cs
Labels: not-notes-worthy

#7828 [d16-5] [Harness] Just try to generate the report when is NUnit.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy, pr-change-not-shipping, requires-approval-before-merge

#7829 [d16-6] [Harness] Just try to generate the report when is NUnit.
  tests/xharness/Jenkins.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7833 [builds] Make sure downloaded files have a newer timestamp than any other file from previous builds.
  builds/Makefile
Labels: not-notes-worthy

#7832 [msbuild] Make sure DeviceSpecificOutputPath is a relative path.
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#7835 [XHarness] Do write the TestReport when we have xUnit results.
  tests/xharness/AppRunner.cs
  tests/xharness/Extensions.cs
  tests/xharness/Jenkins.cs
  tests/xharness/XmlResultParser.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7837 [XHarness] Use static variables for common test names.
  tests/xharness/AppRunner.cs
  tests/xharness/Jenkins.cs
  tests/xharness/Log.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7848 [d16-6][DDFun|VSTS] Add a URL to a more interesting view. (#7845)
  jenkins/vsts-device-tests-set-status.sh
Labels: not-notes-worthy, pr-change-not-shipping

#7849 [xcode11.4] [XHarness] Do write the TestReport when we have xUnit results.
  tests/xharness/AppRunner.cs
  tests/xharness/Extensions.cs
  tests/xharness/Jenkins.cs
  tests/xharness/XmlResultParser.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7850 [d16-6] [XHarness] Do write the TestReport when we have xUnit results.
  tests/xharness/AppRunner.cs
  tests/xharness/Extensions.cs
  tests/xharness/Jenkins.cs
  tests/xharness/XmlResultParser.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7852 [d16-6][XHarness] Use static variables for common test names. (#7837)
  tests/xharness/AppRunner.cs
  tests/xharness/Jenkins.cs
  tests/xharness/Log.cs
Labels: not-notes-worthy, pr-change-not-shipping

#7856 [d16-6] [XHarness] Add logs to VSTS test runs.
  tests/xharness/AppRunner.cs
  tests/xharness/Jenkins.cs
  tests/xharness/XmlResultParser.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy, pr-change-not-shipping

#7866 [Xcode11.4][XHarness] Add logs to VSTS test runs. (#7844)
  tests/xharness/AppRunner.cs
  tests/xharness/Jenkins.cs
  tests/xharness/XmlResultParser.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy

#7857 [AppKit] Update bindings to Xcode 11.4 Beta 1
  src/appkit.cs
  tests/xtro-sharpie/macOS-AppKit.todo
Labels: note-highlight

#7858 [AuthenticationServices] Update bindings to Xcode 11.4 Beta 1
  src/authenticationservices.cs
  tests/xtro-sharpie/iOS-AuthenticationServices.todo
  tests/xtro-sharpie/macOS-AuthenticationServices.todo
  tests/xtro-sharpie/watchOS-AuthenticationServices.todo
Labels: note-highlight

#7861 [CarPlay] Update bindings to Xcode 11.4 Beta 1
  src/carplay.cs
  tests/xtro-sharpie/iOS-CarPlay.todo
Labels: note-highlight

#7862 [ClassKit] Update bindings to Xcode 11.4 Beta 1
  src/classkit.cs
  tests/xtro-sharpie/iOS-ClassKit.todo
Labels: note-highlight

#7859 [AVFoundation] Update bindings to Xcode 11.4 Beta 1
  src/avfoundation.cs
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/tvOS-AVFoundation.todo
Labels: note-highlight

#7863 [Contacts] Update bindings to Xcode 11.4 Beta 1
  src/contacts.cs
Labels: note-highlight

#7864 [CoreBluetooth] Update bindings to Xcode 11.4 Beta 1
  src/CoreBluetooth/Enums.cs
Labels: note-highlight

#7868 [CoreText] Update bindings to Xcode 11.4 Beta 1
  src/CoreText/CTEnums.cs
Labels: note-highlight

#7865 [CoreGraphics] Update bindings to Xcode 11.4 Beta 1
  src/CoreGraphics/CGColorSpace.cs
  src/coregraphics.cs
  tests/xtro-sharpie/iOS-CoreGraphics.todo
  tests/xtro-sharpie/macOS-CoreGraphics.todo
  tests/xtro-sharpie/tvOS-CoreGraphics.todo
  tests/xtro-sharpie/watchOS-CoreGraphics.todo
Labels: note-highlight

#7869 [GameKit] Update bindings to Xcode 11.4 Beta 1
  src/gamekit.cs
  tests/xtro-sharpie/iOS-GameKit.todo
  tests/xtro-sharpie/macOS-GameKit.todo
  tests/xtro-sharpie/tvOS-GameKit.todo
  tests/xtro-sharpie/watchOS-GameKit.todo
Labels: note-highlight

#7867 [CoreLocation] Update to Xcode 11.4 Beta 1
  src/corelocation.cs
  tests/xtro-sharpie/iOS-CoreLocation.todo
  tests/xtro-sharpie/macOS-CoreLocation.todo
  tests/xtro-sharpie/tvOS-CoreLocation.todo
  tests/xtro-sharpie/watchOS-CoreLocation.todo
Labels: note-highlight

#7860 [CallKit] Update bindings to Xcode 11.4 Beta 1
  src/callkit.cs
  tests/xtro-sharpie/iOS-CallKit.todo
Labels: note-highlight

#7884 [LocalAuthentication] Update bindings to Xcode 11.4 Beta 1
  src/LocalAuthentication/LAEnums.cs
Labels: note-highlight

#7886 [SafariServices] Update bindings to Xcode 11.4 Beta 1
  src/SafariServices/SSEnums.cs
  src/safariservices.cs
Labels: note-highlight

#7885 [PassKit] Update bindings to Xcode 11.4 Beta 1
  src/passkit.cs
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/watchOS-PassKit.todo
Labels: note-highlight

#7887 [UIKit] Update bindings to Xcode 11.4 Beta 1
  src/UIKit/UIEnums.cs
  src/uikit.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.todo
Labels: note-highlight

#7855 [Harness] Attach build logs to NUnit V3 xml results.
  tests/xharness/AppRunner.cs
  tests/xharness/Jenkins.cs
  tests/xharness/XmlResultParser.cs
Labels: not-notes-worthy

#7891 Make the x86-64 slice we inject into binaries optional.
  Make.config
  builds/Makefile
  runtime/Makefile
Labels: not-notes-worthy

#7841 [msbuild] Deduplicate the code for generating the app bundle name/path between our various platforms.
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.Common.targets
Labels: not-notes-worthy

#7894 [sharpie] Update sharpie to latest notarized version
  Make.config
Labels: not-notes-worthy

#7889 [XHarness] Add ids to the xunit to nunit transformed tests.
  tests/bcl-test/templates/common/TestRunner.xUnit/NUnit3Xml.xslt
  tests/bcl-test/templates/common/TestRunner.xUnit/XUnitTestRunner.cs
Labels: build-package, run-internal-tests

#7900 [d16-5] Replace removed dsymutil `-t` switch with `-num-threads`
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
  tools/mtouch/mtouch.cs
Labels: note-highlight

#7901 [d16-6] Replace removed dsymutil `-t` switch with `-num-threads`
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
  tools/mtouch/mtouch.cs
Labels: note-highlight

#7906 [Harness] If app does not launch or crash, create a test failure.
  tests/xharness/AppRunner.cs
  tests/xharness/XmlResultParser.cs
Labels: not-notes-worthy

#7899 [xcode11.3] Replace removed dsymutil `-t` switch with `-num-threads`
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
  tools/mtouch/mtouch.cs
Labels: note-highlight

#7912 [Harness] Use fullname for test-case in the xunit xslt.
  tests/bcl-test/templates/common/TestRunner.xUnit/NUnit3Xml.xslt
Labels: build-package, enable-device-build, not-notes-worthy

#7915 [XHarness] Close left open html tags.
  tests/xharness/XmlResultParser.cs
Labels: not-notes-worthy

#7914 [Harness] Add a prefix to the final xml to be imported.
  tests/xharness/AppRunner.cs
  tests/xharness/Jenkins.cs
  tests/xharness/XmlResultParser.cs
Labels: not-notes-worthy

#7916 [VSTS] Ensure that certain tasks do not run when not needed.
  tools/devops/device-tests-common.yml
Labels: not-notes-worthy

#7917 [VSTS] Propagate debug to the make rules
  tools/devops/run-tests.sh
Labels: not-notes-worthy

#7922 [VSTS] Update pipeline yml to use the correct results pattern.
  tools/devops/device-tests-common.yml
Labels: not-notes-worthy, pr-change-not-shipping

#7930 [Tests] Fix AudioQueueTest.Properties test.
  tests/monotouch-test/AudioToolbox/AudioQueueTest.cs
Labels: not-notes-worthy

#7926 [VSTS] Clean always, no matter what.
  tools/devops/device-tests-common.yml
Labels: not-notes-worthy

#7927 [VSTS] Correct order of params for make.
  tools/devops/run-tests.sh
Labels: not-notes-worthy

#7928 [Harness] Create an xml crash file when we do not have a result file.
  tests/xharness/AppRunner.cs
Labels: not-notes-worthy

#7929 [Harness] Create xml unit test failure when an application timesout.
  tests/xharness/AppRunner.cs
Labels: not-notes-worthy

#7905 [tests][msbuild] Update testing build engine to implement IBuildEngine4
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TestHelpers/TestEngine.cs
Labels: not-notes-worthy

#7933 Make the x86-64 slice we inject into binaries optional.
  Make.config
  builds/Makefile
  runtime/Makefile
Labels: not-notes-worthy

#7908 [mtouch/mmp] Share verbosity code.
  tools/common/Driver.cs
  tools/mmp/driver.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#7910 [mtouch/mmp] Share Main.
  tools/common/Driver.cs
  tools/mmp/driver.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#7911 [mtouch/mmp] Share code to locate the framework directory.
  tools/common/Driver.cs
  tools/mmp/aot.cs
  tools/mmp/driver.cs
  tools/mtouch/Target.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#7936 [Harness] If there is no BuildTask, do not add logs.
  tests/xharness/AppRunner.cs
Labels: run-mtouch-tests

#7944 [xcode11.4] Add support for Xcode 11.4 Beta 2
  Make.config
  tests/introspection/ApiProtocolTest.cs
  tests/xtro-sharpie/iOS-IntentsUI.todo
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-WatchKit.todo
Labels: note-highlight

#7925 [mtouch][mmp] Add a `--warn-on-type-ref=X` option
  docs/website/mmp-errors.md
  docs/website/mtouch-errors.md
  tests/common/BundlerTest.cs
  tools/common/Application.cs
  tools/linker/ScanTypeReferenceStep.cs
  tools/mmp/Tuning.cs
  tools/mmp/driver.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Target.cs
  tools/mtouch/Tuning.cs
  tools/mtouch/mtouch.cs
  tools/mtouch/mtouch.csproj
Labels: note-highlight

#7942 [mono] Bump mono to match android
  mk/mono.mk
Labels: requires-approval-before-merge

#7949 [mtouch][mmp] Add a `--warn-on-type-ref=X` option
  docs/website/mmp-errors.md
  docs/website/mtouch-errors.md
  tests/common/BundlerTest.cs
  tools/common/Application.cs
  tools/linker/ScanTypeReferenceStep.cs
  tools/mmp/Tuning.cs
  tools/mmp/driver.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Target.cs
  tools/mtouch/Tuning.cs
  tools/mtouch/errors.Designer.cs
  tools/mtouch/errors.resx
  tools/mtouch/mtouch.cs
  tools/mtouch/mtouch.csproj
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: note-highlight

#7950 [Harness] Do not add the variation two times to failure messages.
  tests/xharness/AppRunner.cs
Labels: not-notes-worthy

#7951 [Harness] Add start-time to work around a bug in the publishing tool.
  tests/xharness/XmlResultParser.cs
Labels: not-notes-worthy

#7953 [mono] bump mono to match android
  mk/mono.mk
Labels: note-highlight

#7965 [WatchKit] Update bindings to Xcode 11.4 Beta 2
  src/watchkit.cs
  tests/xtro-sharpie/watchOS-WatchKit.todo
Labels: note-highlight

#7966 Rename bmac-mobile-mono to mono-sgen.
  builds/Makefile
  tools/mmp/aot.cs
  tools/mmp/tests/aot.cs
Labels: not-notes-worthy

#7909 [mmp] Use relative path in mmp script.
  tools/mmp/Makefile
  tools/mmp/mmp
  tools/mmp/mmp.in
Labels: not-notes-worthy

#7968 [mmp] Remove dead code.
  tools/mmp/driver.cs
Labels: not-notes-worthy

#7967 [mtouch/mmp] Share boolean parsing logic.
  tools/common/Driver.cs
  tools/mmp/driver.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#7964 [VideoSubscriberAccount] Update bindings to Xcode 11.4 Beta 2
  src/videosubscriberaccount.cs
Labels: note-highlight

#7970 [CoreImage] Add missing properties found by intro tests
  src/coreimage.cs
Labels: not-notes-worthy

#7963 [UIKit] Update bindings to Xcode 11.4 Beta 2
  src/uikit.cs
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.todo
Labels: note-highlight

#7977 [d16-6][corefoundation] Fix TypeInitializationException in OSLog (#7962)
  src/CoreFoundation/OSLog.cs
  tests/monotouch-test/CoreFoundation/OSLogTest.cs
Labels: bug

#7969 [mmp] Don't ignore failures to execute pkg-config and simplify/improve logic.
  docs/website/mmp-errors.md
  docs/website/mtouch-errors.md
  tools/mmp/driver.cs
  tools/mtouch/errors.Designer.cs
  tools/mtouch/errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#7976 [tests] Add `.cctor` execution to introspection
  tests/introspection/ApiTypeTest.cs
  tests/introspection/Mac/introspection-mac.csproj
  tests/introspection/iOS/introspection-ios.csproj
Labels: not-notes-worthy, pr-change-not-shipping

#7980 [Bump][Maccore] Bump maccore to be able to use tcp tunnels.
  mk/xamarin.mk
Labels: not-notes-worthy

#7984 [bgen] Put output in subdirectories based on namespaces again.
  src/generator.cs
Labels: not-notes-worthy

#7996 [VSTS] update labels used in the pipeline.
  tools/devops/device-tests-common.yml
  tools/devops/device-tests.yml
Labels: not-notes-worthy

#8004 [linker] Remove a few redundant lines of code
  tools/common/DerivedLinkContext.cs
Labels: not-notes-worthy

#8006 [src] Remove unused make variables.
  src/Makefile
Labels: not-notes-worthy

#8007 [src] Remove code to compile System.Drawing.dll for Xamarin.iOS.
  src/Makefile
  src/system-drawing.sources
Labels: not-notes-worthy

#8008 [src] Remove redundant/overwritten/deprecated command line argument to generator.
  src/Makefile
Labels: not-notes-worthy

#8014 [Security] Don't call .Count() on an IEnumerable when we have an array we can call .Length on.
  src/Security/SslContext.cs
Labels: not-notes-worthy

#8013 [CFNetworkHandler] Stop using internal API and instead copy-paste a modified version of it.
  src/System.Net.Http/CFNetworkHandler.cs
Labels: not-notes-worthy

#8011 [src] Simplify/remove defines.
  src/Makefile
  src/README.md
  src/appkit.cs
  tests/introspection/Mac/MacApiFieldTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
Labels: not-notes-worthy

#8016 [src] Stop using assembly identity while computing stret-ness.
  src/ObjCRuntime/Stret.cs
Labels: not-notes-worthy

#8015 [Harness] When on device, check if we got a tcp exception on a crash.
  tests/xharness/AppRunner.cs
Labels: not-notes-worthy
