Repository dotnet/macios, pull requests merged in 2020-08, with the labels that each got.

#9260 [mtouch/mmp] Add a few instructions to the list of instructions that we don't know how to calculate a constant value for.
  tools/linker/CoreOptimizeGeneratedCode.cs
Labels: not-notes-worthy

#9257 [xharness] Implement Log.GetReader for all loggers.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Logging/AggregatedLog.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Logging/CallbackLog.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Logging/ConsoleLog.cs
Labels: notes-not-worthy

#9258 [xharness] Fix main log parsing by not requiring it to come from a file.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
Labels: notes-not-worthy

#9259 [xharness] Improve parsing of NUnitV2 xml reports to fix an issue with failures in parameterized tests.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests.csproj
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/TestCaseFailures.xml
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/XmlResultParserTests.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/XmlResultParser.cs
Labels: notes-not-worthy

#9262 [mtouch] Don't try to copy invalid symbol files.
  tests/common/ExecutionHelper.cs
  tests/mtouch/MTouch.cs
  tools/common/Assembly.cs
  tools/common/CoreResolver.cs
  tools/mtouch/Assembly.mtouch.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#9261 [AppKit/UIKit] Merge the definitions of NS[Mutable]ParagraphStyle.
  src/AppKit/Compat.cs
  src/appkit.cs
  src/frameworks.sources
  src/uikit.cs
  src/xkit.cs
  tests/xtro-sharpie/SelectorCheck.cs
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/watchOS-UIKit.ignore
Labels: not-notes-worthy

#9269 [README] Update community chat link
  README.md
Labels: not-notes-worthy, skip-all-tests, skip-public-jenkins

#9272 [xcode12] Initial bump to Xcode 12 Beta 4
  Make.config
  src/mlcompute.cs
  src/sensorkit.cs
  src/uikit.cs
  tests/monotouch-test/Security/TrustTest.cs
  tests/xtro-sharpie/Makefile
  tests/xtro-sharpie/iOS-CoreMIDI.todo
  tests/xtro-sharpie/iOS-CoreMotion.todo
  tests/xtro-sharpie/iOS-ExposureNotification.ignore
  tests/xtro-sharpie/iOS-MLCompute.todo
  tests/xtro-sharpie/iOS-Metal.todo
  tests/xtro-sharpie/iOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/iOS-NetworkExtension.todo
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/iOS-PhotosUI.todo
  tests/xtro-sharpie/iOS-SensorKit.todo
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/iOS-WidgetKit.todo
  tests/xtro-sharpie/macOS-AppKit.todo
  tests/xtro-sharpie/macOS-AuthenticationServices.todo
  tests/xtro-sharpie/macOS-CoreMIDI.todo
  tests/xtro-sharpie/macOS-MLCompute.todo
  tests/xtro-sharpie/macOS-Metal.todo
  tests/xtro-sharpie/macOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/macOS-Network.todo
  tests/xtro-sharpie/macOS-NetworkExtension.todo
  tests/xtro-sharpie/macOS-PassKit.todo
  tests/xtro-sharpie/macOS-StoreKit.todo
  tests/xtro-sharpie/macOS-VideoToolbox.todo
  tests/xtro-sharpie/macOS-Virtualization.todo
  tests/xtro-sharpie/macOS-Vision.todo
  tests/xtro-sharpie/macOS-WidgetKit.todo
  tests/xtro-sharpie/tvOS-MLCompute.todo
  tests/xtro-sharpie/tvOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-CoreMotion.todo
  tests/xtro-sharpie/watchOS-NetworkExtension.todo
  tests/xtro-sharpie/watchOS-PassKit.todo
  tests/xtro-sharpie/watchOS-UIKit.todo
  tests/xtro-sharpie/watchOS-WatchKit.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#9277 [dotnet-linker] Rework the project file a bit.
  tools/dotnet-linker/dotnet-linker.csproj
Labels: not-notes-worthy

#9278 [mtouch/mmp] Share a few P/Invokes.
  tools/common/Driver.cs
  tools/mmp/driver.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#9279 [mtouch/mmp] Share the min Xcode version.
  tools/common/Driver.cs
  tools/mmp/driver.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#9287 [AppKit] Update bindings to Xcode 12 Beta 4
  src/AppKit/Enums.cs
  src/appkit.cs
  tests/xtro-sharpie/macOS-AppKit.todo
Labels: note-highlight

#9290 [monotouch-test] Improve a few asserts to make them show better output when they fail.
  tests/monotouch-test/Security/KeyChainTest.cs
Labels: not-notes-worthy

#9288 [msbuild] Make sure to restore the binding project before trying to build it.
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/BindingProject.cs
Labels: not-notes-worthy, run-msbuild-tests

#9280 [mtouch/mmp] Move the Driver.PRODUCT constant to an Application.ProductName instance field.
  tools/common/Application.cs
  tools/common/Driver.cs
  tools/common/SdkVersions.cs.in
  tools/mmp/Application.mmp.cs
  tools/mmp/aot.cs
  tools/mmp/driver.cs
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/BuildTasks.mtouch.cs
  tools/mtouch/Target.mtouch.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#9292 [dotnet] Use the right variable to determine whether we're in debug mode or not.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#9293 [CFNetwork] Update bindings to Xcode 11 Beta 4
  src/CoreFoundation/CFNetwork.cs
Labels: note-highlight

#9294 [dotnet] Always process symbol files.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#9296 [dotnet] Fix referencing an MSBuild variable.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#9297 [CoreFoundation] Update bindings to Xcode 11 Beta 4
  src/Foundation/Enum.cs
  tests/xtro-sharpie/common-CoreFoundation.ignore
  tests/xtro-sharpie/iOS-CoreFoundation.todo
  tests/xtro-sharpie/macOS-CoreFoundation.todo
  tests/xtro-sharpie/tvOS-CoreFoundation.todo
  tests/xtro-sharpie/watchOS-CoreFoundation.todo
Labels: note-highlight

#9299 [CoreGraphics] Update bindings to Xcode 12 Beta 3 & 4
  src/CoreGraphics/CGEvent.cs
  src/coregraphics.cs
  tests/xtro-sharpie/macOS-CoreGraphics.ignore
  tests/xtro-sharpie/macOS-CoreGraphics.todo
Labels: note-highlight

#9301 Remove wrongly added dir.
  tests/xharness/.idea/.idea.xharness/.idea/.gitignore
  tests/xharness/.idea/.idea.xharness/.idea/indexLayout.xml
  tests/xharness/.idea/.idea.xharness/.idea/misc.xml
  tests/xharness/.idea/.idea.xharness/.idea/vcs.xml
  tests/xharness/.idea/.idea.xharness/riderModule.iml
Labels: not-notes-worthy, skip-all-tests

#9303 [Harness] Fix some typos.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/BuildProject.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/IResourceManager.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/MSBuild.cs
Labels: not-notes-worthy, skip-all-tests

#9302 [AuthenticationServices] Update bindings to Xcode 12 Beta 4
  src/authenticationservices.cs
  tests/xtro-sharpie/macOS-AuthenticationServices.todo
Labels: note-highlight

#9291 [monotouch-test] Adjust tests based on Environment.OSVersion
  tests/monotouch-test/MetalPerformanceShaders/ImageScaleTest.cs
  tests/monotouch-test/MetalPerformanceShaders/KernelTest.cs
  tests/monotouch-test/MetalPerformanceShaders/MPSImageHistogramEqualizationTest.cs
  tests/monotouch-test/MetalPerformanceShaders/MPSImageHistogramSpecificationTest.cs
  tests/monotouch-test/MetalPerformanceShaders/MPSImageHistogramTest.cs
  tests/monotouch-test/ModelIO/MDLLight.cs
Labels: not-notes-worthy, run-internal-tests, skip-external-tests, skip-public-jenkins

#9298 [xharness] Make it possible to include .NET tests by setting a label.
  tests/xharness/Jenkins/TestSelector.cs
Labels: not-notes-worthy, run-internal-tests

#9300 [introspection] Some P/Invokes have moved to a QCall library in .NET 5 preview 8+.
  tests/introspection/ApiPInvokeTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#9306 [mtouch/mmp] Move Target.Is32Build and Target.Is64Build to shared code.
  tools/common/Target.cs
  tools/mtouch/Target.mtouch.cs
Labels: not-notes-worthy

#9308 [mtouch] Sort the errors in Errors.resx.
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
  tools/mtouch/Makefile
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#9310 [mtouch/mmp] Share Assembly.CopyAssembly.
  tools/common/Assembly.cs
  tools/mmp/Assembly.mmp.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Assembly.mtouch.cs
Labels: not-notes-worthy

#9295 [msbuild] Pass the full path to the output file to the native linker.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
Labels: not-notes-worthy

#9304 [msbuild] Compute variables for where the platform assembly is, and the platform assembly name.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.TargetFrameworkFix.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.msbuild.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
Labels: not-notes-worthy

#9305 [msbuild] Create a few '_*DependsOn' variables that specifies depend targets.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#9307 [CoreMedia] Update bindings to Xcode 12 Beta 4
  src/CoreMedia/CoreMedia.cs
Labels: note-highlight

#9309 [CoreML] Update bindings to Xcode 12 Beta 4
  src/coreml.cs
Labels: note-highlight

#9316 [CoreMotion] Update bindings to Xcode 12 Beta 4
  src/coremotion.cs
  tests/xtro-sharpie/iOS-CoreMotion.todo
  tests/xtro-sharpie/watchOS-CoreMotion.todo
Labels: note-highlight

#9317 [CoreNFC] Update bindings to Xcode 12 Beta 4
  src/corenfc.cs
Labels: note-highlight

#9311 [xcode12] [On-demand resources] Make sure to Uri escape paths
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateAssetPackManifestTaskBase.cs
Labels: note-highlight

#9281 [CoreLocation] Update framework to Xcode 12 beta 3.
  src/corelocation.cs
Labels: note-highlight

#9325 [CoreAudio] Update framework to Xcode 12 beta 4.
  src/AudioUnit/AudioUnit.cs
Labels: note-highlight

#9327 [WatchKit] Update framework to xcode 12 beta 4.
  src/watchkit.cs
  tests/xtro-sharpie/watchOS-WatchKit.todo
Labels: note-highlight

#9326 [CoreMidi] Update framework for Xcode 12 beta 4.
  src/coremidi.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/iOS-CoreMIDI.todo
  tests/xtro-sharpie/macOS-CoreMIDI.todo
Labels: note-highlight

#9328 [Foundation] Update bindings to Xcode 12 Beta 4
  src/Foundation/Enum.cs
  src/foundation.cs
  tests/xtro-sharpie/iOS-Foundation.todo
  tests/xtro-sharpie/macOS-Foundation.todo
  tests/xtro-sharpie/tvOS-Foundation.todo
  tests/xtro-sharpie/watchOS-Foundation.todo
Labels: note-highlight

#9329 [Intents] Update bindings to Xcode 12 Beta 4
  src/intents.cs
Labels: note-highlight

#9331 [UIKit] Update bindings to Xcode 12 Beta 4
  src/UIKit/UIEnums.cs
  src/uikit.cs
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-UIKit.todo
Labels: note-highlight

#9332 [CoreGraphics] Update 10,16 -> 11,0 missed on #9299 manual files
  src/CoreGraphics/CGColor.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGContextPDF.cs
Labels: not-notes-worthy

#9333 [Xcode12] Fix some availability attributes missed in the Beta 3/4 updates
  src/CoreLocation/CLEnums.cs
  src/cfnetwork.cs
  src/classkit.cs
  src/coremotion.cs
Labels: not-notes-worthy

#9334 [Security] Update bindings to Xcode 12 Beta 4
  src/Security/Enums.cs
Labels: note-highlight

#9319 [mtouch/mmp] Remove the Error91LinkerSuggestion and implement it using two different error codes.
  tools/common/Application.cs
  tools/mmp/Application.mmp.cs
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#9320 [mtouch/mmp] Move Driver's LOCAL_BUILD_DIR and FRAMEWORK_LOCATION_VARIABLE constants to Application instance fields.
  tools/common/Application.cs
  tools/common/Driver.cs
  tools/mmp/driver.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#9322 [xharness] Look at the exact NUnit version an NUnit project is referencing to figure out how to run it in a makefile.
  tests/xharness/Jenkins/TestTasks/NUnitExecuteTask.cs
  tests/xharness/MakefileGenerator.cs
  tools/nunit3-console-3.9.0
Labels: not-notes-worthy

#9324 [tests] Port the EmbeddedResources test project to .NET and add a test to build it.
  tests/EmbeddedResources/dotnet/.gitignore
  tests/EmbeddedResources/dotnet/iOS/EmbeddedResources.csproj
  tests/EmbeddedResources/dotnet/macOS/EmbeddedResources.csproj
  tests/EmbeddedResources/dotnet/shared.targets
  tests/EmbeddedResources/dotnet/tvOS/EmbeddedResources.csproj
  tests/EmbeddedResources/dotnet/watchOS/EmbeddedResources.csproj
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#9323 [msbuild] Share the _CompileEntitlements target.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/CompileEntitlementsTaskCore.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/CompileEntitlements.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileEntitlementsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileEntitlementsTaskCore.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/CompileEntitlements.cs
  tests/cecil-tests/TaskAssemblyTests.cs
Labels: not-notes-worthy, run-internal-tests

#9314 [MapKit] Update the framework to Xcode 12 beta 4.
  src/mapkit.cs
  tests/xtro-sharpie/iOS-MapKit.todo
  tests/xtro-sharpie/macOS-MapKit.todo
  tests/xtro-sharpie/tvOS-MapKit.todo
Labels: note-highlight

#9339 [dotnet] Port the fsharplibrary project to .NET
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/fsharplibrary/dotnet/.gitignore
  tests/fsharplibrary/dotnet/iOS/fsharplibrary.fsproj
  tests/fsharplibrary/dotnet/macOS/fsharplibrary.fsproj
  tests/fsharplibrary/dotnet/shared.targets
  tests/fsharplibrary/dotnet/tvOS/fsharplibrary.fsproj
  tests/fsharplibrary/dotnet/watchOS/fsharplibrary.fsproj
Labels: not-notes-worthy

#9321 [mtouch/mmp] Move Application.RequiresXcodeHeaders to shared code.
  tools/common/Application.cs
  tools/mmp/Application.mmp.cs
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy

#9343 [README] Add d16-7 versions
  README.md
Labels: not-notes-worthy, skip-all-tests, skip-public-jenkins

#9342 [mtouch] Fix the MT0091 test (now called MT0180) after recent code changes. Fixes xamarin/maccore@2280.
  tests/mtouch/MTouch.cs
  tools/common/Application.cs
Labels: not-notes-worthy

#9338 [mtouch/mmp] Add CoreFoundation and GSS to our list of known frameworks.
  tools/common/Frameworks.cs
Labels: not-notes-worthy

#9340 [dotnet] Add support for building binding projects.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  src/Makefile.generator
  src/bgen/bgen.dotnet
  src/btouch.cs
  tests/bindings-test/dotnet/.gitignore
  tests/bindings-test/dotnet/iOS/bindings-test.csproj
  tests/bindings-test/dotnet/macOS/bindings-test.csproj
  tests/bindings-test/dotnet/shared.targets
  tests/bindings-test/dotnet/tvOS/bindings-test.csproj
  tests/bindings-test/dotnet/watchOS/bindings-test.csproj
  tests/bindings-test2/dotnet/.gitignore
  tests/bindings-test2/dotnet/iOS/bindings-test2.csproj
  tests/bindings-test2/dotnet/macOS/bindings-test2.csproj
  tests/bindings-test2/dotnet/shared.targets
  tests/bindings-test2/dotnet/tvOS/bindings-test2.csproj
  tests/bindings-test2/dotnet/watchOS/bindings-test2.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#9349 [tests] Add --dlsym:+nunit.framework.dll to all Xamarin.iOS test suites.
  tests/framework-test/framework-test.csproj
  tests/fsharp/fsharp.fsproj
  tests/interdependent-binding-projects/interdependent-binding-projects.csproj
  tests/introspection/iOS/introspection-ios.csproj
  tests/linker/ios/dont link/dont link.csproj
  tests/linker/ios/link all/link all.csproj
  tests/linker/ios/link sdk/link sdk.csproj
  tests/mono-native/iOS/mono-native.csproj.template
  tests/nunit.framework.targets
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy, run-internal-tests

#9348 [tests] Fix running several test suites from the command line. Fixes xamarin/maccore@2279.
  tests/generator/Makefile
  tests/mmptest/Makefile
  tests/mtouch/Makefile
  tests/sampletester/Makefile
Labels: not-notes-worthy, run-internal-tests, run-sample-tests

#9347 [xharness] Add support for adding PropertyGroups for unknown platform/configuration values in a csproj. Fixes xamarin/maccore@2277.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Labels: not-notes-worthy, run-internal-tests

#9350 [ARKit] Bug fix: Add SupportsFrameSemantics to all subclasses of ARConfiguration
  src/arkit.cs
Labels: iOS

#9361 [xcode12] Update API diff to latest stable release
  Make.config
Labels: not-notes-worthy, skip-all-tests

#9357 [iOSurface] Remove warning from the generator.
  src/iosurface.cs
Labels: not-notes-worthy

#9360 [d16-8] Update API diff to latest stable release
  Make.config
Labels: not-notes-worthy, skip-all-tests

#9358 [GameController] Remove warnings from the generator.
  src/gamecontroller.cs
Labels: enhancement

#9359 [main] Update API diff to latest stable release
  Make.config
Labels: not-notes-worthy, skip-all-tests, skip-public-jenkins

#9364 [mtouch/mmp] Move a few Application.Is* properties to shared code.
  tools/common/Application.cs
  tools/mmp/Application.mmp.cs
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy

#9365 [mtouch] Move Driver.IsFrameworkAvailableInSimulator to shared Application code.
  tools/common/Application.cs
  tools/common/Assembly.cs
  tools/common/StaticRegistrar.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#9363 [mtouch/mmp] Move Application.BuildTarget, Application.IsDeviceBuild and Application.IsSimulatorBuild to shared code.
  tools/common/Application.cs
  tools/mmp/Application.mmp.cs
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy

#9354 [AVFoundation] Update framework for Xcode 12 beta 4.
  src/AVFoundation/Enums.cs
  src/avfoundation.cs
  tests/xtro-sharpie/common-AVFoundation.ignore
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/macOS-AVFoundation.ignore
  tests/xtro-sharpie/macOS-AVFoundation.todo
  tests/xtro-sharpie/tvOS-AVFoundation.todo
  tests/xtro-sharpie/watchOS-AVFoundation.todo
Labels: note-highlight

#9369 [xharness] Add support for getting the default AssemblyName for projects.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/PlistExtensions.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Labels: not-notes-worthy

#9374 [mtouch] Don't validate the --target-framework argument if we're just calling mlaunch.
  tools/common/Driver.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#9395 [tests][intro] Fix tvOS crash on older (non 4k) devices
  tests/introspection/iOS/iOSApiCtorInitTest.cs
Labels: not-notes-worthy

#9396 [DevOps] Just clean the xamarin-macios dir to ensure we do not delete maccore creds.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#9397 [d16-8] [DevOps] Just clean the xamarin-macios dir to ensure we do not delete maccore creds.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy

#9385 [AppTrackingTransparency] Add support for Xcode 12 beta 4
  src/Constants.iOS.cs.in
  src/Constants.mac.cs.in
  src/Constants.tvos.cs.in
  src/apptrackingtransparency.cs
  src/frameworks.sources
  tests/xtro-sharpie/common-AppTrackingTransparency.ignore
  tests/xtro-sharpie/iOS-AppTrackingTransparency.todo
  tests/xtro-sharpie/macOS-AppTrackingTransparency.todo
  tests/xtro-sharpie/tvOS-AppTrackingTransparency.todo
  tools/common/Frameworks.cs
  tools/mtouch/Makefile
Labels: community, note-highlight

#9399 [monotouch-test] Fix typo in Foundation/UrlTest
  tests/monotouch-test/Foundation/UrlTest.cs
Labels: not-notes-worthy

#9403 [dotnet] Turn the linker off by default for simulator builds.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#9371 Partial fix for AVAudioEngine.Connect(input, sink, format) crash when format == null
  src/AVFoundation/AVAudioFormat.cs
  tests/monotouch-test/AVFoundation/AVAudioFormatTest.cs
Labels: iOS, macOS

#9412 [scenekit] Update for Xcode 12 beta 5
  tests/xtro-sharpie/common-SceneKit.ignore
  tests/xtro-sharpie/iOS-SceneKit.todo
  tests/xtro-sharpie/macOS-SceneKit.todo
  tests/xtro-sharpie/tvOS-SceneKit.todo
Labels: note-highlight

#9411 [coreml] Update for Xcode 12 beta 5
  src/coreml.cs
  tests/xtro-sharpie/iOS-CoreML.todo
  tests/xtro-sharpie/macOS-CoreML.todo
  tests/xtro-sharpie/tvOS-CoreML.todo
  tests/xtro-sharpie/watchOS-CoreML.todo
Labels: note-highlight

#9413 [foundation] Update for Xcode 12 beta 5
  src/Foundation/Enum.cs
  src/foundation.cs
  tests/xtro-sharpie/iOS-Foundation.todo
  tests/xtro-sharpie/macOS-Foundation.todo
  tests/xtro-sharpie/tvOS-Foundation.todo
  tests/xtro-sharpie/watchOS-Foundation.todo
Labels: note-highlight

#9416 [notificationcenter] Update for Xcode 12 beta 5
  src/NotificationCenter/NCEnums.cs
  src/notificationcenter.cs
Labels: note-highlight

#9415 [Bug][AudioUnit] Add [Obsolete] to write access for read-only property
  src/AudioUnit/AudioUnit.cs
Labels: enhancement

#9401 [xharness] Make monotouch-test (all optimization) aware of IncludesiOS32
  tests/xharness/Jenkins/Jenkins.cs
Labels: run-internal-tests

#9419 [UIKit] Update bindings to Xcode 12 Beta 5
  src/uikit.cs
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
Labels: note-highlight

#9431 [GameController] Update bindings to Xcode beta 5
  src/GameController/Enums.cs
  src/gamecontroller.cs
  tests/xtro-sharpie/iOS-GameController.todo
  tests/xtro-sharpie/macOS-GameController.todo
  tests/xtro-sharpie/tvOS-GameController.todo
Labels: note-highlight

#9426 [Intents] Update bindings to Xcode 12 Beta 5
  src/CoreLocation/CoreLocation.cs
  src/intents.cs
  tests/xtro-sharpie/iOS-Intents.todo
  tests/xtro-sharpie/tvOS-Intents.ignore
  tests/xtro-sharpie/watchOS-Intents.todo
Labels: note-highlight

#9430 [ScreenTime] Update bindings to Xcode 12 Beta 5
  src/screentime.cs
  tests/xtro-sharpie/iOS-ScreenTime.todo
  tests/xtro-sharpie/macOS-ScreenTime.todo
Labels: note-highlight

#9427 [CoreLocation] Update framework to Xcode 12 beta 5.
  src/corelocation.cs
  tests/xtro-sharpie/iOS-CoreLocation.todo
  tests/xtro-sharpie/macOS-CoreLocation.ignore
  tests/xtro-sharpie/macOS-CoreLocation.todo
Labels: note-highlight

#9414 [msbuild] Remove the _AssignBundleResourceNames target, it's not used anymore.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.targets
Labels: not-notes-worthy

#9417 [msbuild] Share the AllowedReferenceRelatedFileExtensions property override.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.props
Labels: not-notes-worthy

#9418 [msbuild] Remove unnecessary logic to not re-import props files.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.Common.targets
Labels: not-notes-worthy

#9421 [dotnet] Add support for resolving Mono's runtime pack.
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#9424 [dotnet-linker] Make Driver.Verbosity the single source of truth.
  tools/dotnet-linker/LinkerConfiguration.cs
Labels: not-notes-worthy

#9451 [dotnet] Bump .NET and the linker.
  Make.config
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/fsharplibrary/dotnet/shared.targets
  tools/dotnet-linker/dotnet-linker.csproj
Labels: not-notes-worthy

#9450 [msbuild] Share the _CollectNativeFrameworkResources target between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
Labels: not-notes-worthy

#9452 [tests] Port monotouch-test to .NET.
  tests/monotouch-test/OpenGLES/EAGLContext.cs
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
  tests/monotouch-test/mono/MonoWeakReferenceTest.cs
  tests/monotouch-test/mono/WeakReferenceTest.cs
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/RunDeviceTasksFactory.cs
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestProject.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Labels: not-notes-worthy

#9453 [tests][monotouch-test] Re-enable SystemSoundTest
  tests/monotouch-test/AudioToolbox/SystemSoundTest.cs
Labels: not-notes-worthy

#9433 [Bug] Fix AVAudioFormat failure on older OS
  tests/monotouch-test/AVFoundation/AVAudioFormatTest.cs
Labels: not-notes-worthy, test-only-issue

#9467 [xharness] Process '$(RootTestsDirectory)' before bailing due to any other variables when resolving paths in project files.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Labels: not-notes-worthy

#9460 [dotnet] Implement support for our different link modes.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/common/Application.cs
  tools/common/LinkMode.cs
  tools/mmp/driver.cs
Labels: not-notes-worthy

#9468 [dotnet] Copy the app.config file to the app bundle.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#9469 [dotnet] It's time to start signing apps.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#9470 [dotnet] Normalize the casing of TargetPlatformIdentifier according to the design documents.
  dotnet/targets/Xamarin.Shared.Sdk.TargetFrameworkInference.targets
Labels: not-notes-worthy

#9466 [ObjCRuntime] Work around a difference in .NET where Type.IsInterface doesn't work the same way for byref types.
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy

#9465 [monotouch-test] Ignore an autoreleasepool threadpool test which is a known issue in .NET.
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: not-notes-worthy

#9464 [monotouch-test] Don't run the mono tests for the System.Drawing types in .NET
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
Labels: not-notes-worthy

#9463 [dotnet/monotouch-test] Disable tests that require Crypto for .NET.
  tests/monotouch-test/Foundation/UrlCredentialTest.cs
  tests/monotouch-test/Security/CertificateTest.cs
  tests/monotouch-test/Security/KeyTest.cs
  tests/monotouch-test/Security/RecordTest.cs
  tests/monotouch-test/Security/TrustTest.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy

#9462 [dotnet] Don't include the F# library in monotouch-test yet, it makes the linker crash.
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
Labels: not-notes-worthy

#9438 [dotnet] Implement support for the partial static registrar.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/common/Application.cs
  tools/common/AssemblyBuildTarget.cs
  tools/common/StaticRegistrar.cs
  tools/dotnet-linker/Compat.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
  tools/dotnet-linker/Steps/RegistrarStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/mmp/.gitignore
  tools/mmp/Makefile
  tools/mmp/driver.cs
  tools/mtouch/Assembly.mtouch.cs
  tools/mtouch/Makefile
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#9461 [msbuild] Share the _CompressNativeFrameworkResources/_CompressFrameworks target between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
Labels: not-notes-worthy

#9471 [msbuild] Share the Pack/UnpackLibraryResources targets between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#9472 [dotnet] Implement resource bundling.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/BundledResources/ResourcesTest.cs
  tests/BundledResources/dotnet/iOS/BundledResources.csproj
  tests/BundledResources/dotnet/macOS/BundledResources.csproj
  tests/BundledResources/dotnet/tvOS/BundledResources.csproj
  tests/BundledResources/dotnet/watchOS/BundledResources.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#9485 [tests] Update the MT0113_linker test asserting an error message after the message changed.
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#9488 [tests] Port dont link to .NET
  tests/linker/ios/dont link/dotnet/iOS/dont link.csproj
  tests/xharness/Harness.cs
Labels: not-notes-worthy

#9491 [dotnet-linker] Add Debug to the linker configuration.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/dotnet-linker/LinkerConfiguration.cs
Labels: not-notes-worthy

#9486 [msbuild] Rework how we compute the input when compressing frameworks for binding projects.
  msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
Labels: not-notes-worthy

#9489 [dotnet/msbuild] Add support for compiling and embedding entitlements to .NET apps.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
Labels: not-notes-worthy

#9492 [tools] Extract the code to parse, validate and process exception marshalling arguments into the Application class.
  tools/common/Application.cs
  tools/common/Driver.cs
Labels: not-notes-worthy

#9507 [xcode12] Initial bump for Xcode 12 Beta 6
  Make.config
  tests/xtro-sharpie/Makefile
  tests/xtro-sharpie/iOS-CarPlay.todo
  tests/xtro-sharpie/iOS-GameKit.todo
  tests/xtro-sharpie/tvOS-GameKit.todo
  tests/xtro-sharpie/tvOS-Intents.ignore
  tests/xtro-sharpie/watchOS-GameKit.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#9497 [dotnet] Preserve relative directory when deciding where in the app bundle files should be copied.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#9501 [tests] Fix the don't link test on .NET.
  tests/linker/CommonDontLinkTest.cs
  tests/linker/ios/dont link/CalendarTest.cs
  tests/linker/ios/dont link/DontLinkRegressionTests.cs
  tests/xharness/Harness.cs
Labels: not-notes-worthy, run-dotnet-tests

#9502 [tools] Honor the ENABLE_DOTNET variable. Fixes #9475.
  tools/Makefile
  tools/mmp/Makefile
Labels: not-notes-worthy

#9496 [dotnet] Make sure the 'BuildOnlySettings' target has been called before any other .NET target we depend on.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#9498 [tests] Adjust resources test to cope with the fact that only the invariant culture is currently shipping in .NET 5.
  tests/EmbeddedResources/ResourcesTest.cs
Labels: not-notes-worthy

#9509 [tests] Port link sdk to .NET.
  tests/linker/CommonLinkSdkTest.cs
  tests/linker/ios/link sdk/AotBugs.cs
  tests/linker/ios/link sdk/AsyncTest.cs
  tests/linker/ios/link sdk/Bug1820Test.cs
  tests/linker/ios/link sdk/CryptoTest.cs
  tests/linker/ios/link sdk/DllImportTest.cs
  tests/linker/ios/link sdk/LinkExtraDefsTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/linker/ios/link sdk/PclTest.cs
  tests/linker/ios/link sdk/dotnet/extra-linker-defs.xml
  tests/linker/ios/link sdk/dotnet/iOS/link sdk.csproj
  tests/xharness/Harness.cs
Labels: not-notes-worthy, run-dotnet-tests

#9504 [msbuild] Re-use existing logic to compress frameworks for the ObjCBindingNativeFramework items.
  msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
Labels: not-notes-worthy

#9493 [msbuild] Parse --marshal-managed-exceptions and --marshal-objectivec-exceptions in ParseBundlerArgumentsTask.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
Labels: not-notes-worthy

#9519 Revert "[MTouch] Add a workaround for a failing tests in the Xcode 12 betas. (#9073)"
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#9521 [Intents] Update bindings to Xcode 12 Beta 6
  src/intents.cs
Labels: note-highlight

#9512 [linker] Fix typo in method name: MarkDefautConstructor -> MarkDefaultConstructor
  tools/linker/ApplyPreserveAttribute.cs
Labels: not-notes-worthy

#9513 Bump .NET to 5.0.100-rc.1.20414.5.
  Make.config
Labels: not-notes-worthy

#9515 [tests] Port link all to .NET
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link all/dotnet/iOS/link all.csproj
  tests/xharness/Harness.cs
Labels: not-notes-worthy

#9516 [msbuild] Share the _CollectGeneratedSources target between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
Labels: not-notes-worthy

#9517 [dotnet] Add support for setting the exception marshalling mode in the GenerateMain step.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
Labels: not-notes-worthy

#9518 [xharness] Use the local 'ignore' variable instead of fetching 'test.TestProject.Ignore' for every test when generating test variations.
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#9514 [runtime] Give a better error message if we can't load ObjCRuntime.Runtime.Initialize ()
  runtime/launcher.m
  runtime/runtime.m
Labels: not-notes-worthy

#9527 [tests] Skip the TypeDescriptorCanary test in .NET.
  tests/linker/CommonDontLinkTest.cs
Labels: not-notes-worthy

#9522 [GameKit] Updates Xcode 12 through beta 6
  src/gamekit.cs
  tests/xtro-sharpie/iOS-GameKit.todo
  tests/xtro-sharpie/tvOS-GameKit.todo
  tests/xtro-sharpie/watchOS-GameKit.ignore
  tests/xtro-sharpie/watchOS-GameKit.todo
Labels: iOS, macOS, note-highlight

#9526 [xharness] Enable monotouch-test/.NET by default, but ignore all variations.
  tests/monotouch-test/Foundation/LocaleTest.cs
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy, run-dotnet-tests

#9528 [dotnet-linker] Print out substeps too when printing pipeline steps.
  tools/dotnet-linker/SetupStep.cs
Labels: not-notes-worthy

#9525 [msbuild] Emit binding resources to the EmbeddedResource item group instead of ManifestResourceWithNoCulture. Fixes #3876.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/PrepareNativeReferencesTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
  tests/mmptest/src/BindingProjectTests.cs
Labels: not-notes-worthy, run-msbuild-tests

#9524 [msbuild] Unify the code to define our platform-specific conditional compilation symbols.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.CSharp.targets
Labels: not-notes-worthy

#9529 [dotnet-linker] Add ApplyPreserveAttribute into the pipeline.
  tools/dotnet-linker/ApplyPreserveAttributeBase.cs
  tools/dotnet-linker/Compat.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/CollectAssembliesStep.cs
  tools/dotnet-linker/Steps/DotNetSubStepDispatcher.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/linker/ApplyPreserveAttribute.cs
  tools/linker/MobileApplyPreserveAttribute.cs
  tools/mmp/Tuning.mmp.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Tuning.mtouch.cs
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#9510 [xharness] Enable the .NET tests when a file containing 'dotnet' is modified.
  tests/xharness/Jenkins/TestSelector.cs
Labels: not-notes-worthy

#9530 [tools] Use Extensions.Is instead of Extensions.IsPlatformType.
  tools/common/Assembly.cs
  tools/linker/MonoTouch.Tuner/Extensions.cs
  tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversionsSubStep.cs
Labels: not-notes-worthy
