Repository dotnet/macios, pull requests merged in 2020-07, with the labels that each got.

#8979 [DevOps] Release device bots as soon as possible.
  tools/devops/device-tests/scripts/GitHub.psm1
  tools/devops/device-tests/templates/cambridge-variables.yml
  tools/devops/device-tests/templates/ddfun-variables.yml
  tools/devops/device-tests/templates/device-tests-stage.yml
  tools/devops/device-tests/templates/device-tests.yml
  tools/devops/device-tests/templates/download-artifacts.yml
  tools/devops/device-tests/templates/publish-html.yml
  tools/devops/device-tests/templates/upload-vsdrops.yml
  tools/devops/device-tests/templates/upload-vsts-tests.yml
Labels: not-notes-worthy

#8976 [xharness] Try to not have log directories with spaces in them.
  tests/xharness/Jenkins/TestTasks/AppleTestTask.cs
Labels: not-notes-worthy

#8978 [Foundation] Fix code to not cause a potential null error when compiling using the .NET 5 BCL.
  src/Foundation/DictionaryContainer.cs
Labels: not-notes-worthy

#8985 Bump .NET 5 version to preview 7.20317.11.
  Make.config
Labels: not-notes-worthy

#8984 [dotnet] Use the exact same dotnet version in our global.jsons as in Make.config.
  dotnet/Makefile
  dotnet/global.json
  tests/dotnet/Makefile
  tools/dotnet-linker/Makefile
  tools/dotnet-linker/global.json
Labels: not-notes-worthy

#8983 [msbuild] Share the MSBuild logic for CollectBundleResources and a few related properties.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.targets
Labels: not-notes-worthy

#8987 [msbuild] Unify the logic to copy bundle resources to the app.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeBundleResourceOutputPathsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8988 [msbuild] Share a few binding variables: BaseLibDllPath, BTouchToolPath and BTouchToolExe.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.props
Labels: not-notes-worthy

#8994 [mtouch] Regenerate Errors.designer.cs after some entries were removed from Errors.resx.
  tools/mtouch/Errors.designer.cs
Labels: not-notes-worthy

#9012 [tests] Skip a few networking tests on macOS 10.9. Fixes #xamarin/maccore@2221.
  tests/monotouch-test/Foundation/NSDataTest.cs
  tests/monotouch-test/Foundation/UrlProtocolTest.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy

#9013 [dotnet] Add some project capabilities.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#8995 [msbuild] Unify XamarinMacFrameworkRoot and MonoTouchSdkRoot into _XamarinSdkRoot.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.targets
Labels: not-notes-worthy

#8997 [msbuild] Unify the _GenerateBindings target and a few properties related to binding projects.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.props
Labels: not-notes-worthy

#8998 [msbuild] Unify all the UsingTask statements.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.Common.targets
Labels: not-notes-worthy

#9023 [d16-7] [tests] Skip a few networking tests on macOS 10.9. Fixes #xamarin/maccore@2221.
  tests/monotouch-test/Foundation/NSDataTest.cs
  tests/monotouch-test/Foundation/UrlProtocolTest.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: pr-change-not-shipping

#9018 [d16-7] [Foundation] Do expose server errors.
  src/Foundation/NSUrlSessionHandler.cs
Labels: requires-approval-before-merge

#9016 [d16-7] [Foundation] Avoid LINQ in bindings. Fixes #8773
  src/Foundation/NSUrlSessionHandler.cs
Labels: requires-approval-before-merge

#9028 [DevOps] Clean all workspaces and try to fix our space problems.
  tools/devops/device-tests/templates/device-tests-stage.yml
Labels: not-notes-worthy, skip-all-tests

#9033 [AVFoundation] Ignore a few compiler warnings about missing overrides for comparison support.
  src/AVFoundation/AVAudioChannelLayout.cs
  src/AVFoundation/AVAudioFormat.cs
Labels: not-notes-worthy

#9031 [src] Create a Constants.cs file for Constants that are in all platforms.
  src/Constants.iOS.cs.in
  src/Constants.mac.cs.in
  src/Constants.tvos.cs.in
  src/Constants.watch.cs.in
  src/ObjCRuntime/Constants.cs
  src/frameworks.sources
  tools/mmp/mmp.csproj
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#9034 [xcode12] [tests][xtro] Fix NSUrl-based categories
  src/foundation.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/Runner.cs
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/iOS-NetworkExtension.ignore
Labels: not-notes-worthy

#9040 [DevOps] Move back to self hosted windows pools.
  tools/devops/device-tests/templates/cambridge-variables.yml
  tools/devops/device-tests/templates/ddfun-variables.yml
  tools/devops/device-tests/templates/device-tests-stage.yml
Labels: not-notes-worthy, skip-all-tests

#9042 [tests][monotouch-test] Re-enable some tests with beta 2
  tests/monotouch-test/AudioToolbox/SystemSoundTest.cs
  tests/monotouch-test/CoreText/FontTest.cs
  tests/monotouch-test/MapKit/AnnotationViewTest.cs
  tests/monotouch-test/MapKit/PinAnnotationViewTest.cs
  tests/monotouch-test/Network/NWBrowserTest.cs
Labels: not-notes-worthy

#9043 [DevOps] Fix issues with the xm storage path.
  tools/devops/device-tests/scripts/GitHub.psm1
  tools/devops/device-tests/templates/device-tests-stage.yml
  tools/devops/device-tests/templates/device-tests.yml
  tools/devops/device-tests/templates/publish-html.yml
  tools/devops/device-tests/templates/upload-vsdrops.yml
Labels: not-notes-worthy, skip-all-tests

#9061 [msbuild] Make the ParseExtraMtouchArgs task platform-agnostic, and share it between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/ParseBundlerArguments.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/ParseExtraMtouchArgs.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
Labels: not-notes-worthy

#9067 [monotouch-test] Use a normal thread instead of MulticastDelegate.BeginInvoke in AVAssetImageGeneratorTest.
  tests/monotouch-test/AVFoundation/AVAssetImageGeneratorTest.cs
Labels: not-notes-worthy

#9032 [xharness] Add support for generating a tvOS version of .NET iOS projects.
  tests/xharness/Harness.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/IDevice.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
  tests/xharness/Targets/MacTarget.cs
  tests/xharness/Targets/TVOSTarget.cs
  tests/xharness/Targets/Target.cs
  tests/xharness/Targets/UnifiedTarget.cs
  tests/xharness/Targets/WatchOSTarget.cs
  tests/xharness/Targets/iOSTarget.cs
Labels: not-notes-worthy

#9082 [xharness] Use Cecil to inspect assemblies, instead of Reflection.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Microsoft.DotNet.XHarness.iOS.Shared.csproj
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/ProjectDefinition.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/RegisterTypeGenerator.cs
Labels: not-notes-worthy

#9084 [monotouch-test] Fix debug naming.
  tests/monotouch-test/Foundation/NSStreamTest.cs
Labels: not-notes-worthy

#9091 [tests] Provide an ignore reason for Ignore attributes.
  tests/monotouch-test/AudioUnit/AUParameterNodeTest.cs
  tests/monotouch-test/UIKit/FloatRangeTest.cs
Labels: not-notes-worthy

#9093 [monotouch-test] Use Is.EqualTo instead of Is.EquivalentTo for equal arrays.
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: not-notes-worthy

#9100 [DevOps] In a self-hosted pool we need to specify the os.
  tools/devops/device-tests/templates/device-tests-stage.yml
Labels: not-notes-worthy, skip-all-tests

#9101 [DevOps] If we cannot clear the hd, continue.
  tools/devops/device-tests/scripts/System.psm1
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#9102 [DevOps] Add debugging messages from when we fail the ./configure
  configure
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#9094 [monotouch-test] Comparing uint to int for inequality doesn't work newer versions of NUnit[Lite].
  tests/monotouch-test/Network/NWEstablishmentReportTest.cs
Labels: not-notes-worthy

#9092 [tests] Use Assert.Throws instead of the ExpectedException attribute.
  tests/apitest/src/Foundation/NSScriptCommandArgumentDescriptionTest.cs
  tests/apitest/src/Foundation/NSScriptCommandDescriptionTest.cs
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/AotBugs.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/monotouch-test/Compression/CompressionStreamTest.cs
  tests/monotouch-test/CoreData/ManagedObjectContextTest.cs
  tests/monotouch-test/CoreFoundation/BundleTest.cs
  tests/monotouch-test/CoreFoundation/UrlTest.cs
  tests/monotouch-test/CoreText/FontManagerTest.cs
  tests/monotouch-test/EventKit/CalendarTest.cs
  tests/monotouch-test/Foundation/BlockOperationTest.cs
  tests/monotouch-test/Foundation/BundleTest.cs
  tests/monotouch-test/Foundation/FileCoordinatorTest.cs
  tests/monotouch-test/Foundation/OperationQueueTest.cs
  tests/monotouch-test/Foundation/StringTest.cs
  tests/monotouch-test/GameplayKit/GKEntityTests.cs
  tests/monotouch-test/Intents/INIntentResolutionResultTests.cs
  tests/monotouch-test/MapKit/PolygonTest.cs
  tests/monotouch-test/MapKit/PolylineTest.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
  tests/monotouch-test/Security/SecSharedCredentialTest.cs
  tests/monotouch-test/SystemConfiguration/CaptiveNetworkTest.cs
  tests/monotouch-test/UIKit/PopoverControllerTest.cs
  tests/monotouch-test/UIKit/UIDocumentTest.cs
  tests/monotouch-test/UIKit/ViewTest.cs
Labels: not-notes-worthy

#9096 [monotouch-test] Fix broken UrlRequestTest.Mutability_30744 test.
  tests/monotouch-test/Foundation/UrlRequestTest.cs
Labels: not-notes-worthy

#9098 [xharness] Don't group simulators when running in server mode.
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
Labels: not-notes-worthy

#9048 Add support for arbitrary extensions to be bundled in XI/XM apps
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/tests/NativeExtensionEmbedding/.gitignore
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/AppDelegate.cs
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/Entitlements.plist
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/Info.plist
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/LaunchScreen.storyboard
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/Main.cs
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/Main.storyboard
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/ManagedContainer.csproj
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/ManagedContainer.sln
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/Properties/AssemblyInfo.cs
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/Resources/LaunchScreen.xib
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/SceneDelegate.cs
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/ViewController.cs
  msbuild/tests/NativeExtensionEmbedding/managed/ManagedContainer/ViewController.designer.cs
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer.xcodeproj/project.pbxproj
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer/.gitignore
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer/AppDelegate.swift
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer/Assets.xcassets/AppIcon.appiconset/Contents.json
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer/Assets.xcassets/Contents.json
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer/Base.lproj/LaunchScreen.storyboard
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer/ContentView.swift
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer/Info.plist
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer/Preview Content/Preview Assets.xcassets/Contents.json
  msbuild/tests/NativeExtensionEmbedding/native/NativeContainer/SceneDelegate.swift
  msbuild/tests/NativeExtensionEmbedding/native/NativeTodayExtension/Base.lproj/MainInterface.storyboard
  msbuild/tests/NativeExtensionEmbedding/native/NativeTodayExtension/Info.plist
  msbuild/tests/NativeExtensionEmbedding/native/NativeTodayExtension/TodayViewController.swift
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/EmbeddedExtension.cs
  tests/common/mac/NativeExtension/.gitignore
  tests/common/mac/NativeExtension/NativeContainerApp.xcodeproj/project.pbxproj
  tests/common/mac/NativeExtension/NativeContainerApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  tests/common/mac/NativeExtension/NativeContainerApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  tests/common/mac/NativeExtension/NativeContainerApp/AppDelegate.swift
  tests/common/mac/NativeExtension/NativeContainerApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  tests/common/mac/NativeExtension/NativeContainerApp/Assets.xcassets/Contents.json
  tests/common/mac/NativeExtension/NativeContainerApp/Base.lproj/Main.storyboard
  tests/common/mac/NativeExtension/NativeContainerApp/ContentView.swift
  tests/common/mac/NativeExtension/NativeContainerApp/Info.plist
  tests/common/mac/NativeExtension/NativeContainerApp/NativeContainerApp.entitlements
  tests/common/mac/NativeExtension/NativeContainerApp/Preview Content/Preview Assets.xcassets/Contents.json
  tests/common/mac/NativeExtension/NativeTodayExtension/Base.lproj/TodayViewController.xib
  tests/common/mac/NativeExtension/NativeTodayExtension/Info.plist
  tests/common/mac/NativeExtension/NativeTodayExtension/NativeTodayExtension.entitlements
  tests/common/mac/NativeExtension/NativeTodayExtension/TodayViewController.swift
  tests/common/mac/NativeExtension/NativeTodayExtension/en.lproj/InfoPlist.strings
  tests/mmptest/mmptest.csproj
  tests/mmptest/src/NativeExtensionEmbedding.cs
Labels: note-highlight

#9103 [xharness] Fix finding testable types in test assemblies. Fixes #xamarin/maccore@2267.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/ProjectDefinition.cs
Labels: not-notes-worthy, run-bcl-tests

#9105 [mmp] Use the right pkg-config directory.
  tools/mmp/driver.cs
Labels: not-notes-worthy

#9110 [xharness] Parse NUnit v2 xml reports correctly.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests.csproj
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/NUnitV2SampleFailure.xml
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/XmlResultParserTests.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/IResultParser.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/XmlResultParser.cs
Labels: not-notes-worthy

#9109 [apitest] Refactor tests to not be async.
  tests/apitest/src/AudioUnit/AUGraphTest.cs
  tests/apitest/src/Foundation/NSObject.cs
Labels: not-notes-worthy

#9108 [apitest] Sleep for 0.05s instead of 0.5s.
  tests/apitest/src/Darwin/KernelNotificationTest.cs
Labels: not-notes-worthy

#9104 [xharness] De-asyncify template expansion.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/TestImporter/Templates/Managed/InfoPlistGeneratorTests.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/InfoPlistGenerator.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/RegisterTypeGenerator.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/XamariniOSTemplate.cs
Labels: not-notes-worthy

#9116 [monotouch-test] Second attempt at fixing the broken UrlRequestTest.Mutability_30744 test.
  tests/monotouch-test/Foundation/UrlRequestTest.cs
Labels: not-notes-worthy

#9117 Bump maccore to get provisioning fix for Big Sur.
  mk/xamarin.mk
Labels: not-notes-worthy

#9118 [xharness] Improve code to not throw exceptions in the first place instead of catching and ignoring.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Labels: not-notes-worthy

#9119 [xharness] Try harder to make lldb quit after trying to get a backtrace.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Execution/ProcessManager.cs
Labels: not-notes-worthy

#9120 [xharness] Improve process killing a bit.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Execution/ProcessManager.cs
Labels: not-notes-worthy

#9122 [xharness] Don't try to write cleaned xml into the same file as the dirty xml was.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
Labels: not-notes-worthy

#9123 [xharness] Don't replace existing files, instead add new files, when providing human-readable logs.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
Labels: not-notes-worthy

#9131 [xharness] Fix BCL project generation for watchOS projects.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/XamariniOSTemplate.cs
Labels: not-notes-worthy

#9121 [xharness] Don't generate into the same directory/files for macOS Modern and macOS Full.
  tests/bcl-test/macOSFull-xammac_net_4_5_System.Configuration_test.dll.ignore
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/XamariniOSTemplate.cs
Labels: not-notes-worthy, run-bcl-tests

#9137 [xharness] Disable default inclusion behavior for the introspection .NET tests.
  tests/introspection/iOS/introspection-ios-dotnet.csproj
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestProject.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Labels: not-notes-worthy

#9138 [tests] Remove the mono-native CheckSymbols test.
  tests/mono-native/Introspection.cs
Labels: not-notes-worthy

#9083 [xharness] Generate BCL projects asynchronously.
  tests/xharness/BCLTestImportTargetFactory.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/ITemplatedProject.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/XamariniOSTemplate.cs
  tests/xharness/Xharness.Tests/Tests/BCLTestImportTargetFactoryTest.cs
Labels: not-notes-worthy, run-bcl-tests

#9147 [xharness] Fix compiler warning.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/XmlResultParser.cs
Labels: not-notes-worthy

#9148 [xharness] Fix logic to not create makefile targets to run BCL tests.
  tests/xharness/MakefileGenerator.cs
Labels: not-notes-worthy

#9146 [msbuild] Share the logic to implicitly include netstandard.dll in the build.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.msbuild.targets
  msbuild/Xamarin.Shared/Xamarin.ImplicitFacade.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#9155 [xcode12] Bump API diff to latest released stable
  Make.config
Labels: pr-change-not-shipping

#9154 [d16-8] Bump API diff to latest released stable
  Make.config
Labels: pr-change-not-shipping

#9153 [d16-7] Bump API diff to latest released stable
  Make.config
Labels: pr-change-not-shipping

#9140 [xharness] Allow for null environment variables to mlaunch.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Execution/Mlaunch/Arguments.cs
Labels: not-notes-worthy

#9158 [xharness] Generate makefile targets for non-executable projects.
  tests/xharness/MakefileGenerator.cs
Labels: not-notes-worthy

#9157 [tests] The HttpWebRequest constructors are not publicly available in .NET 5, so use WebRequest.CreateHttp instead.
  tests/monotouch-test/CoreFoundation/NetworkTest.cs
Labels: not-notes-worthy

#9166 [tests] Move the aot.cs inside the mmptest directory, and remove some redundant code/files.
  tests/mmp-aot-tests/.gitignore
  tests/mmp-aot-tests/Makefile
  tests/mmp-aot-tests/packages.config
  tests/mmptest/mmptest.csproj
  tests/mmptest/src/AOTTests.cs
  tests/mmptest/src/aot.cs
  tools/mmp/Makefile
Labels: not-notes-worthy

#9165 [xharness] Backport Touch.Unit fix for command line parsing.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/common/ApplicationOptions.cs
Labels: not-notes-worthy

#9167 [test-libraries] Don't include all the dependencies in the ar archives we create.
  tests/test-libraries/Makefile
Labels: not-notes-worthy

#9169 [dotnet] Add Verbosity to the linker configuration.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tools/dotnet-linker/LinkerConfiguration.cs
Labels: not-notes-worthy

#9172 [DevOps] Clean all before we run the tests.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#9160 [Devops] Use the deployment pool.
  tools/devops/device-tests/templates/cambridge-variables.yml
  tools/devops/device-tests/templates/ddfun-variables.yml
  tools/devops/device-tests/templates/download-artifacts.yml
  tools/devops/device-tests/templates/publish-html.yml
Labels: skip-all-tests

#9173 [dotnet] Only pass a single custom step to the linker.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
  tools/dotnet-linker/SetupStep.cs
Labels: not-notes-worthy

#9171 [jenkins] Don't try to publish NuGet packages if there are no NuGet packages.
  jenkins/Jenkinsfile
Labels: not-notes-worthy

#9170 [jenkins] Make it possible to skip running packaged Xamarin.Mac tests by setting the 'skip-packaged-xamarin-mac-tests' label.
  jenkins/Jenkinsfile
Labels: not-notes-worthy

#9168 [xharness] Fix how .NET projects are ignored.
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#9195 [corenfc] Add NFCNdefTag (protocol) to NFCIso15693Tag (protocol)
  src/corenfc.cs
Labels: bug

#9180 [mmp] Remove inexistent file from csproj.
  tools/mmp/mmp.csproj
Labels: not-notes-worthy

#9202 [msbuild] Fix automatic stripping of release builds by using the correct variable.
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#9201 [tests] Skip 32-bit iOS tests in the simulator, because the 32-bit iOS simulator is broken.
  tests/Makefile
Labels: run-internal-tests

#9149 [xharness] Only have a single project per directory.
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/BindingProject.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TestHelpers/TestBase.cs
  tests/.gitignore
  tests/bindings-test/iOS/bindings-test.csproj
  tests/bindings-test/macOS/bindings-test.csproj
  tests/bindings-test2/bindings-test2.csproj
  tests/common/ExecutionHelper.cs
  tests/interdependent-binding-projects/interdependent-binding-projects.csproj
  tests/linker/ios/link all/link all.csproj
  tests/linker/ios/link sdk/link sdk.csproj
  tests/linker/mac/link all/link all-mac.csproj
  tests/mono-native/iOS/Info.plist
  tests/mono-native/iOS/mono-native.csproj.template
  tests/mono-native/macOS/Entitlements.plist
  tests/mono-native/macOS/Info.plist
  tests/mono-native/macOS/mono-native.csproj.template
  tests/monotouch-test/monotouch-test.csproj
  tests/mtouch/MTouch.cs
  tests/package-mac-tests.sh
  tests/tests-mac.sln
  tests/tests.sln
  tests/xammac_tests/xammac_tests.csproj
  tests/xharness/BCLTestImportTargetFactory.cs
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/RunDeviceTasksFactory.cs
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
  tests/xharness/Jenkins/TestData.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/SystemXunit.csproj
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/TestProject/SystemXunit.csproj
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Utilities/ProjectFileExtensionsTests.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/MacTestProject.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/MonoNativeInfo.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/Managed.iOS.csproj.in
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/Managed.macOS.csproj.in
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/Managed.tvOS.csproj.in
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/Managed.watchOS.Extension.csproj.in
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/XamariniOSTemplate.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestProject.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/XmlDocumentExtensions.cs
  tests/xharness/Targets/MacTarget.cs
  tests/xharness/Targets/TVOSTarget.cs
  tests/xharness/Targets/Target.cs
  tests/xharness/Targets/TodayExtensionTarget.cs
  tests/xharness/Targets/UnifiedTarget.cs
  tests/xharness/Targets/WatchOSTarget.cs
  tests/xharness/Targets/iOSTarget.cs
  tests/xharness/TestProjectExtensions.cs
  tests/xharness/Xharness.Tests/Samples/SystemXunit.csproj
  tests/xharness/Xharness.Tests/Samples/TestProject/SystemXunit.csproj
Labels: build-package, enable-device-build, not-notes-worthy, run-bcl-tests, run-internal-tests

#9182 [DevOps] Clean all before we run the tests. (#9172)
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, pr-change-not-shipping, skip-all-tests

#9161 [DevOps] If test fail but pipeline builds, set the correct status.
  tools/devops/device-tests/scripts/VSTS.Tests.ps1
  tools/devops/device-tests/scripts/VSTS.psm1
  tools/devops/device-tests/templates/publish-html.yml
Labels: not-notes-worthy, skip-all-tests

#9227 [Accessibility] Update bindings to Xcode 12 Beta 3
  src/CoreGraphics/CGColor.cs
  src/accessibility.cs
Labels: note-highlight

#9228 [Accounts] Update bindings to Xcode 12 Beta 3
  src/accounts.cs
Labels: note-highlight

#9229 [AdSupport] Update bindings to Xcode 12 Beta 3
  src/adsupport.cs
Labels: note-highlight

#9230 [ARKit] Update bindings to Xcode 12 Beta 3
  src/arkit.cs
Labels: note-highlight

#9232 [AppKit] Update bindings to Xcode 12 Beta 3
  src/AppKit/Enums.cs
  src/AppKit/NSWorkspace.cs
  src/appkit.cs
  tests/xtro-sharpie/macOS-AppKit.todo
Labels: note-highlight

#9220 [Intents] Update bindings from Xcode 12 Beta 1 to Beta 3
  src/Constants.tvos.cs.in
  src/Intents/INBillTypeResolutionResult.cs
  src/Intents/INCallRecord.cs
  src/Intents/INCallRecordTypeResolutionResult.cs
  src/Intents/INCarAirCirculationModeResolutionResult.cs
  src/Intents/INCarAudioSourceResolutionResult.cs
  src/Intents/INCarDefrosterResolutionResult.cs
  src/Intents/INCarSeatResolutionResult.cs
  src/Intents/INCarSignalOptionsResolutionResult.cs
  src/Intents/INGetCarLockStatusIntentResponse.cs
  src/Intents/INGetCarPowerLevelStatusIntentResponse.cs
  src/Intents/INIntentResolutionResult.cs
  src/Intents/INInteraction.cs
  src/Intents/INMessageAttributeOptionsResolutionResult.cs
  src/Intents/INMessageAttributeResolutionResult.cs
  src/Intents/INPaymentStatusResolutionResult.cs
  src/Intents/INRadioTypeResolutionResult.cs
  src/Intents/INRelativeReferenceResolutionResult.cs
  src/Intents/INRelativeSettingResolutionResult.cs
  src/Intents/INRideOption.cs
  src/Intents/INSearchCallHistoryIntent.cs
  src/Intents/INSetCarLockStatusIntent.cs
  src/Intents/INSpeakableString.cs
  src/Intents/INWorkoutGoalUnitTypeResolutionResult.cs
  src/Intents/INWorkoutLocationTypeResolutionResult.cs
  src/frameworks.sources
  src/intents.cs
  tests/xtro-sharpie/common-Intents.ignore
  tests/xtro-sharpie/iOS-Intents.todo
  tests/xtro-sharpie/macOS-Intents.ignore
  tests/xtro-sharpie/macOS-Intents.todo
  tests/xtro-sharpie/tvOS-Intents.ignore
  tests/xtro-sharpie/tvOS-Intents.todo
  tests/xtro-sharpie/watchOS-Intents.ignore
  tests/xtro-sharpie/watchOS-Intents.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#9224 [UIKit] Update bindings to Xcode 12 Beta 3
  src/UIKit/UIEnums.cs
  src/uikit.cs
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-UIKit.todo
Labels: note-highlight

#9225 [DevOps] Both labs use the same utility pool, lets keep it in one place.
  tools/devops/device-tests/templates/cambridge-variables.yml
  tools/devops/device-tests/templates/common-variables.yml
  tools/devops/device-tests/templates/ddfun-variables.yml
Labels: not-notes-worthy, skip-all-tests

#9240 [tests] Migrate the xtro sharpie project to use package references.
  tests/xtro-sharpie/ObjCInterfaceCheck.cs
  tests/xtro-sharpie/packages.config
  tests/xtro-sharpie/xtro-sharpie.csproj
Labels: not-notes-worthy

#9235 [AppKit] NSScrollView.DocumentView is an NSView.
  src/appkit.cs
Labels: not-notes-worthy

#9236 [tests] mmptest doesn't need to include MacTestMain.cs
  tests/mmptest/mmptest.csproj
Labels: not-notes-worthy

#9237 [xharness] Make restoring nugets the default for all test projects.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/BuildProject.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestProject.cs
Labels: not-notes-worthy

#9238 [tests] Migrate the mtouch test project to use package references.
  tests/mtouch/Makefile
  tests/mtouch/mtouch.csproj
  tests/mtouch/packages.config
Labels: not-notes-worthy

#9239 [tests] Migrate the generator tests to use package references.
  tests/generator/generator-tests.csproj
  tests/generator/packages.config
Labels: not-notes-worthy

#9241 [tests] Migrate Xamarin.Mac template projects to use package references.
  tests/common/mac/ProjectTestHelpers.cs
  tests/common/mac/TestProjects/BasicPCLTest/MyLibrary/MyLibrary.csproj
  tests/common/mac/TestProjects/BasicPCLTest/MyLibrary/packages.config
  tests/common/mac/TestProjects/ImmutableCollection_Test/ImmutableCollection_Test/ImmutableCollection_Test.csproj
  tests/common/mac/TestProjects/ImmutableCollection_Test/ImmutableCollection_Test/packages.config
  tests/common/mac/TestProjects/Protobuf_Test/Protobuf_Test/Protobuf_Test.csproj
  tests/common/mac/TestProjects/Protobuf_Test/Protobuf_Test/packages.config
  tests/common/mac/TestProjects/RoslynTestApp/Full/RoslynTestApp.csproj
  tests/common/mac/TestProjects/RoslynTestApp/Full/packages.config
  tests/common/mac/TestProjects/RoslynTestApp/Modern/RoslynTestApp.csproj
  tests/common/mac/TestProjects/RoslynTestApp/Modern/packages.config
  tests/mmptest/src/Unified45.cs
  tests/msbuild-mac/src/RoslynSmokeTests.cs
Labels: not-notes-worthy

#9242 [xharness] Improve restoring NuGets for Xamarin.Mac projects in the makefile by depending on the csproj files in addition to the packages.conf files.
  tests/xharness/MakefileGenerator.cs
Labels: not-notes-worthy, run-internal-tests, skip-public-jenkins

#9231 [AuthenticationServices] Update bindings to Xcode 12 Beta 3
  src/authenticationservices.cs
Labels: note-highlight

#9233 [AVKit] Update bindings to Xcode 12 Beta 3
  src/avkit.cs
Labels: note-highlight

#9223 [DevOps] The powershell in Windows is older, we do not support the param.
  tools/devops/device-tests/scripts/GitHub.psm1
  tools/devops/device-tests/scripts/VSTS.psm1
Labels: not-notes-worthy, skip-all-tests

#9250 [DevOps] Report the correct bot used.
  tools/devops/device-tests/scripts/GitHub.psm1
  tools/devops/device-tests/templates/device-tests-stage.yml
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#9244 [tests] Migrate the sample tests to use package references.
  tests/sampletester/packages.config
  tests/sampletester/sampletester.csproj
  tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
Labels: not-notes-worthy

#9245 [tests] Switch msbuild-mac to use package references.
  tests/msbuild-mac/msbuild-mac.csproj
  tests/msbuild-mac/packages.config
  tests/xharness/Jenkins/MacTestTasksEnumerable.cs
Labels: not-notes-worthy

#9243 Bump .NET 5 to preview.8.20359.11.
  Make.config
Labels: not-notes-worthy, run-internal-tests

#9246 [tests] Switch mmptest to use package references.
  tests/mmptest/mmptest.csproj
  tests/mmptest/packages.config
Labels: not-notes-worthy

#9247 [msbuild] Default 'BundlerDebug' to 'true' if no other option is set and we're building for a 'Debug' configuration.
  msbuild/Xamarin.Shared/Xamarin.Shared.props
Labels: not-notes-worthy, run-internal-tests, skip-public-jenkins

#9248 [msbuild] Fix arguments to error logging for GetMinimumOSVersionTask.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetMinimumOSVersionTaskBase.cs
Labels: not-notes-worthy

#9251 [xharness] Mark the .NET tests project as a .NET project so that we don't try to call nuget restore on it.
  tests/xharness/Jenkins/Jenkins.cs
Labels: not-notes-worthy, run-dotnet-tests

#9252 [xharness] Resolve relative project references using the referencing project's directory.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/BuildProject.cs
Labels: not-notes-worthy

#9253 [xharness] Don't try to parse a build log that doesn't exist.
  tests/xharness/TestTasks/RunTest.cs
Labels: not-notes-worthy
