Repository dotnet/macios, pull requests merged in 2020-10, with the labels that each got.

#9747 [Vision] Clean xtro files.
  tests/xtro-sharpie/iOS-Vision.todo
  tests/xtro-sharpie/macOS-Vision.todo
Labels: not-notes-worthy

#9735 [msbuild] Share the _*CompileSceneKitAssets targets between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/common/mac/TestProjects/MyCocoaSceneKitApp/AppDelegate.cs
  tests/common/mac/TestProjects/MyCocoaSceneKitApp/Info.plist
  tests/common/mac/TestProjects/MyCocoaSceneKitApp/MyCocoaSceneKitApp.csproj
  tests/common/mac/TestProjects/MyCocoaSceneKitApp/MyCocoaSceneKitApp.sln
  tests/common/mac/TestProjects/MyCocoaSceneKitApp/art.scnassets/scene.scn
  tests/common/mac/TestProjects/MyCocoaSceneKitApp/art.scnassets/texture.png
  tests/msbuild-mac/src/MSBuild-Smoke.cs
Labels: not-notes-worthy, run-dotnet-tests

#9738 Revert "[introspection] Adapt to .NET 5's vision of how ConstructorInfo.ToString () should behave."
  tests/introspection/ApiCtorInitTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#9736 [tests] Fix a couple of typos.
  tests/msbuild-mac/src/RoslynSmokeTests.cs
Labels: not-notes-worthy

#9739 [tests] Set the build environment when cleaning project as well in the mac msbuild tests.
  tests/common/mac/ProjectTestHelpers.cs
Labels: not-notes-worthy

#9740 [Photos] Correct nullability attributes for the Photos framework
  src/photos.cs
  tests/xtro-sharpie/iOS-Photos.ignore
  tests/xtro-sharpie/macOS-Photos.ignore
  tests/xtro-sharpie/tvOS-Photos.ignore
Labels: community, note-highlight

#9743 [tests][xtro] Consider class (static) methods when checking for deprecation. Fix #9026
  tests/xtro-sharpie/DeprecatedCheck.cs
  tests/xtro-sharpie/common-CoreBluetooth.ignore
  tests/xtro-sharpie/common-CoreLocation.ignore
Labels: not-notes-worthy

#9746 [ExternalAccessory] Update framework for xcode 12.2 beta 1.
  src/externalaccessory.cs
Labels: note-highlight

#9719 [CarPlay] Update bindings to Xcode 12.2 Beta 1
  src/CarPlay/CPCompat.cs
  src/carplay.cs
  src/frameworks.sources
  tests/xtro-sharpie/iOS-CarPlay.ignore
Labels: note-highlight

#9761 Bump API diff to the released (stable) xcode12 version of XI
  Make.config
Labels: not-notes-worthy

#9762 [Xcode12] Bring some changes preset in d16-7 that are missing in xcode12.
  src/Foundation/NSUrlSessionHandler.cs
  src/MetalPerformanceShaders/MPSStateBatch.cs
  src/avfoundation.cs
Labels: not-notes-worthy

#9751 [tests][intro] ConstantsCheck should only be executed on latest OS
  tests/introspection/ApiTypoTest.cs
Labels: not-notes-worthy

#9758 Bump to .NET 5.0.100-rc.2.20459.1
  Make.config
  dotnet/generate-target-platforms.csharp
Labels: run-dotnet-tests, run-internal-tests

#9759 [msbuild] Fix warning text for the 0111 warning to use the correct format specifier.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
Labels: not-notes-worthy

#9766 [xcode12.2][tests][intro] Split attributes typos from API typos tests
  src/AVFoundation/Events.cs
  src/AddressBook/ABPerson.cs
  src/AudioToolbox/AudioFileStream.cs
  src/AudioToolbox/AudioSession.cs
  src/Constants.watch.cs.in
  src/CoreAnimation/CACompat.cs
  src/CoreBluetooth/CBCompat.cs
  src/CoreTelephony/CoreTelephony.cs
  src/CoreText/CTParagraphStyle.cs
  src/Foundation/NSError.cs
  src/GameplayKit/GKCompat.cs
  src/Intents/INCarAirCirculationModeResolutionResult.watchOS.cs
  src/Intents/INCarAudioSourceResolutionResult.watchOS.cs
  src/Intents/INCarDefrosterResolutionResult.watchOS.cs
  src/Intents/INCarSeatResolutionResult.watchOS.cs
  src/Intents/INRadioTypeResolutionResult.watchOS.cs
  src/Intents/INRelativeReferenceResolutionResult.watchOS.cs
  src/Intents/INRelativeSettingResolutionResult.watchOS.cs
  src/ObjCRuntime/ObsoleteConstants.cs
  src/SearchKit/SearchKit.cs
  src/Security/Items.cs
  src/UIKit/UIEnums.cs
  src/WatchKit/iOS/WKAccessibility.cs
  src/WatchKit/iOS/WKAccessibilityImageRegion.cs
  src/WatchKit/iOS/WKErrorCode.cs
  src/WatchKit/iOS/WKImageAnimatable.cs
  src/WatchKit/iOS/WKInterfaceButton.cs
  src/WatchKit/iOS/WKInterfaceController.cs
  src/WatchKit/iOS/WKInterfaceDate.cs
  src/WatchKit/iOS/WKInterfaceDevice.cs
  src/WatchKit/iOS/WKInterfaceGroup.cs
  src/WatchKit/iOS/WKInterfaceImage.cs
  src/WatchKit/iOS/WKInterfaceLabel.cs
  src/WatchKit/iOS/WKInterfaceMap.cs
  src/WatchKit/iOS/WKInterfaceMapPinColor.cs
  src/WatchKit/iOS/WKInterfaceObject.cs
  src/WatchKit/iOS/WKInterfaceSeparator.cs
  src/WatchKit/iOS/WKInterfaceSlider.cs
  src/WatchKit/iOS/WKInterfaceSwitch.cs
  src/WatchKit/iOS/WKInterfaceTable.cs
  src/WatchKit/iOS/WKInterfaceTimer.cs
  src/WatchKit/iOS/WKMenuItemIcon.cs
  src/WatchKit/iOS/WKTextInputMode.cs
  src/WatchKit/iOS/WKUserNotificationInterfaceController.cs
  src/WatchKit/iOS/WKUserNotificationInterfaceType.cs
  src/callkit.cs
  src/coretelephony.cs
  src/foundation.cs
  src/frameworks.sources
  src/healthkit.cs
  src/mapkit.cs
  src/uikit.cs
  src/watchkit.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/Mac/MacApiTypoTest.cs
  tests/introspection/iOS/iOSApiTypoTest.cs
Labels: not-notes-worthy

#9771 [xcode12.2][tests][cecil] Check for absence of `[NoX]` (Unavailable) in platform assemblies. Fix #4835
  src/AVFoundation/AVTypes.cs
  src/AudioUnit/AudioComponent.cs
  src/CoreMidi/MidiServices.cs
  src/CoreVideo/CVImageBuffer.cs
  src/GameKit/GKCompat.cs
  src/HomeKit/HMHome.cs
  src/MapKit/MKFeatureDisplayPriority.cs
  src/Metal/Defs.cs
  tests/cecil-tests/Test.cs
Labels: not-notes-worthy

#9765 [tests][xtro] Check for missing/extra [Appearance]. Fix #7136
  src/uikit.cs
  tests/xtro-sharpie/Runner.cs
  tests/xtro-sharpie/UIAppearanceCheck.cs
  tests/xtro-sharpie/common-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/xtro-sharpie.csproj
Labels: enhancement

#9770 [msbuild] Share the _CreatePkgInfo target between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#9769 [msbuild] Refactor the ProjectPaths to use strongly typed properties.
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/BindingProject.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/BindingReferences.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/Bug60536.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/Extensions/ExtensionTestBase.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/ProjectTest.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TestHelpers/TestBase.cs
Labels: not-notes-worthy, run-dotnet-tests, run-msbuild-tests

#9768 [msbuild] Refactor how we figure out which native libraries to sign for Xamarin.Mac
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
Labels: not-notes-worthy

#9773 [xcode12.2][tests][xtro] Check for deprecated p/invokes (C API)
  src/AddressBook/ABMultiValue.cs
  src/AppKit/NSGraphics.cs
  src/AppKit/NSWorkspace.cs
  src/AudioUnit/AUGraph.cs
  src/AudioUnit/AudioComponent.cs
  src/AudioUnit/AudioUnit.cs
  src/CoreFoundation/CFStream.cs
  src/CoreFoundation/Dispatch.cs
  src/CoreGraphics/CGContext.cs
  src/CoreMedia/CMSync.cs
  src/CoreMidi/MidiServices.cs
  src/CoreServices/LaunchServices.cs
  src/CoreText/CTFontManager.cs
  src/ObjCRuntime/PlatformAvailability.cs
  src/Security/Authorization.cs
  src/Security/Certificate.cs
  src/Security/SecProtocolMetadata.cs
  src/Security/SecSharedCredential.cs
  src/Security/Trust.cs
  src/SystemConfiguration/CaptiveNetwork.cs
  src/TVServices/TVEnums.cs
  tests/xtro-sharpie/DeprecatedCheck.cs
Labels: not-notes-worthy

#9780 [xcode12.2] [tests][cecil] Check that error-based enum values don't have availability attributes
  src/AVFoundation/Enums.cs
  src/AudioToolbox/AudioServices.cs
  src/CloudKit/Enums.cs
  src/CoreBluetooth/Enums.cs
  src/Foundation/Enum.cs
  src/HomeKit/HMEnums.cs
  src/MediaPlayer/MediaPlayer.cs
  src/Metal/MTLEnums.cs
  src/PassKit/PKEnums.cs
  src/callkit.cs
  src/coreml.cs
  src/fileprovider.cs
  tests/cecil-tests/EnumTest.cs
Labels: not-notes-worthy

#9691 [tests][xtro] Add enum member/values checks. Fix #7527
  src/AVFoundation/Enums.cs
  src/AudioToolbox/AudioType.cs
  src/AudioUnit/AudioUnit.cs
  src/ClockKit/CLKEnums.cs
  src/Contacts/CNEnums.cs
  src/CoreData/Enums.cs
  src/CoreGraphics/CGEventTypes.cs
  src/CoreGraphics/CGImage.cs
  src/CoreHaptics/Enums.cs
  src/CoreLocation/CLEnums.cs
  src/CoreText/CTFont.cs
  src/CoreText/CTFrame.cs
  src/CoreText/CTParagraphStyle.cs
  src/CoreWlan/Enums.cs
  src/Foundation/Enum.cs
  src/GameKit/GameKit.cs
  src/HealthKit/Enums.cs
  src/MapKit/MKEnums.cs
  src/Metal/MTLEnums.cs
  src/MetalPerformanceShaders/MPSDefs.cs
  src/NetworkExtension/NEEnums.cs
  src/PassKit/PKEnums.cs
  src/ReplayKit/RPEnums.cs
  src/Security/SecureTransport.cs
  src/StoreKit/Enums.cs
  src/UIKit/UIEnums.cs
  src/WebKit/Enums.cs
  src/arkit.cs
  src/corenfc.cs
  src/healthkit.cs
  src/intents.cs
  src/networkextension.cs
  src/usernotifications.cs
  tests/xtro-sharpie/EnumCheck.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/common-CFNetwork.ignore
  tests/xtro-sharpie/common-CoreAnimation.ignore
  tests/xtro-sharpie/common-CoreText.ignore
  tests/xtro-sharpie/common-EventKit.ignore
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/common-MLCompute.ignore
  tests/xtro-sharpie/common-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/common-Security.ignore
  tests/xtro-sharpie/common-UIKit.ignore
  tests/xtro-sharpie/iOS-AVKit.ignore
  tests/xtro-sharpie/iOS-FileProvider.ignore
  tests/xtro-sharpie/macOS-WebKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/watchOS-PassKit.ignore
  tests/xtro-sharpie/watchOS-UIKit.ignore
Labels: breaking-change, note-highlight

#9781 [xcode12.2] [tests][xtro] Consider class (static) methods when checking for deprecation. Fix #9026
  tests/xtro-sharpie/DeprecatedCheck.cs
  tests/xtro-sharpie/common-CoreBluetooth.ignore
  tests/xtro-sharpie/common-CoreLocation.ignore
  tests/xtro-sharpie/macOS-CoreLocation.ignore
Labels: not-notes-worthy

#9784 [Xcode12][ARKit] Fix ARFrameSemantics and ARErrorCode
  src/arkit.cs
Labels: notes-mention, requires-approval-before-merge

#9785 [xcode12.2] [tests][xtro] Check for missing/extra [Appearance]. Fix #7136
  src/uikit.cs
  tests/xtro-sharpie/Runner.cs
  tests/xtro-sharpie/UIAppearanceCheck.cs
  tests/xtro-sharpie/common-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/xtro-sharpie.csproj
Labels: enhancement

#9786 [msbuild] Share the _*Metal tasks between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-dotnet-tests

#9775 [msbuild] Share the CodesignNativeLibraries target between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-msbuild-tests

#9787 [msbuild] Include all the *.targets and *.props files from the Xamarin.Shared directory in the XI and XM tasks projects.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
Labels: build-package, run-internal-tests, skip-public-jenkins

#9774 [tests] Fix sample tests to take into account when a platform has been disabled.
  tests/sampletester/SampleTester.cs
  tools/devops/build-samples.csx
Labels: build-package, not-notes-worthy, run-sample-tests

#9791 [FileProvider] Update bindings up to Xcode 12.2 Beta 2
  src/fileprovider.cs
  tests/xtro-sharpie/macOS-FileProvider.todo
Labels: note-highlight

#9793 [ImageIO] Update bindings up to Xcode 12.2 Beta 2
  src/ImageIO/Enums.cs
  src/imageio.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/iOS-ImageIO.todo
  tests/xtro-sharpie/macOS-ImageIO.todo
  tests/xtro-sharpie/tvOS-ImageIO.todo
  tests/xtro-sharpie/watchOS-ImageIO.todo
Labels: note-highlight

#9796 [xcode12.2][tests][xtro] Add enum member/values checks. Fix #7527 (#9691)
  src/AVFoundation/Enums.cs
  src/AppKit/Enums.cs
  src/AudioToolbox/AudioType.cs
  src/AudioUnit/AudioUnit.cs
  src/ClockKit/CLKEnums.cs
  src/Contacts/CNEnums.cs
  src/CoreData/Enums.cs
  src/CoreGraphics/CGEventTypes.cs
  src/CoreGraphics/CGImage.cs
  src/CoreHaptics/Enums.cs
  src/CoreLocation/CLEnums.cs
  src/CoreText/CTFont.cs
  src/CoreText/CTFrame.cs
  src/CoreText/CTParagraphStyle.cs
  src/CoreWlan/Enums.cs
  src/Foundation/Enum.cs
  src/GameKit/GameKit.cs
  src/HealthKit/Enums.cs
  src/MapKit/MKEnums.cs
  src/Metal/MTLEnums.cs
  src/MetalPerformanceShaders/MPSDefs.cs
  src/NetworkExtension/NEEnums.cs
  src/PassKit/PKEnums.cs
  src/ReplayKit/RPEnums.cs
  src/Security/Authorization.cs
  src/Security/Items.cs
  src/Security/SecureTransport.cs
  src/StoreKit/Enums.cs
  src/UIKit/UIEnums.cs
  src/WebKit/Enums.cs
  src/arkit.cs
  src/corenfc.cs
  src/fileprovider.cs
  src/healthkit.cs
  src/intents.cs
  src/mlcompute.cs
  src/networkextension.cs
  src/usernotifications.cs
  tests/xtro-sharpie/EnumCheck.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/common-CFNetwork.ignore
  tests/xtro-sharpie/common-CoreAnimation.ignore
  tests/xtro-sharpie/common-CoreText.ignore
  tests/xtro-sharpie/common-EventKit.ignore
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/common-MLCompute.ignore
  tests/xtro-sharpie/common-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/common-Security.ignore
  tests/xtro-sharpie/common-UIKit.ignore
  tests/xtro-sharpie/iOS-AVKit.ignore
  tests/xtro-sharpie/iOS-FileProvider.ignore
  tests/xtro-sharpie/macOS-AVFoundation.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
  tests/xtro-sharpie/macOS-CoreWLAN.ignore
  tests/xtro-sharpie/macOS-FileProvider.ignore
  tests/xtro-sharpie/macOS-Security.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/watchOS-PassKit.ignore
Labels: breaking-change

#9794 [VideoSubscriberAccount] Update bindings up to Xcode 12.2 Beta 2
  src/videosubscriberaccount.cs
  tests/introspection/ApiProtocolTest.cs
  tests/xtro-sharpie/common-VideoSubscriberAccount.ignore
  tests/xtro-sharpie/iOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/macOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/tvOS-VideoSubscriberAccount.todo
Labels: note-highlight

#9805 [xcode12.2] [Photos] Correct nullability attributes for the Photos framework
  src/photos.cs
  tests/xtro-sharpie/iOS-Photos.ignore
  tests/xtro-sharpie/macOS-Photos.ignore
  tests/xtro-sharpie/tvOS-Photos.ignore
Labels: community, enhancement

#9795 [UIKit] Update bindings up to Xcode 12.2 Beta 2
  src/uikit.cs
Labels: note-highlight

#9807 [maccore] Bump maccore to get CredScan fixes
  mk/xamarin.mk
Labels: not-notes-worthy, pr-change-not-shipping

#9809 [xcode12] [maccore] Bump maccore to get CredScan fixes
  mk/xamarin.mk
Labels: not-notes-worthy, pr-change-not-shipping, requires-approval-before-merge

#9808 [d16-8][maccore] Bump maccore to get CredScan fixes
  mk/xamarin.mk
Labels: not-notes-worthy, pr-change-not-shipping

#9806 [mlcompute] Update for Xcode 12.2 beta 2
  src/mlcompute.cs
  tests/xtro-sharpie/iOS-MLCompute.todo
  tests/xtro-sharpie/macOS-MLCompute.todo
  tests/xtro-sharpie/tvOS-MLCompute.todo
Labels: enhancement

#9812 [security] Update for Xcode 12.2 beta 2
  src/Security/Enums.cs
  src/security.cs
  tests/xtro-sharpie/macOS-Security.ignore
  tests/xtro-sharpie/macOS-Security.todo
Labels: enhancement

#9810 [xcode12.2] [maccore] Bump maccore to get CredScan fixes
  mk/xamarin.mk
Labels: not-notes-worthy, pr-change-not-shipping

#9799 [dotnet-linker] Update GenerateMainStep to generate code compatible with libxamarin on macOS
  tools/dotnet-linker/Steps/GenerateMainStep.cs
Labels: community, dotnet, macOS, run-dotnet-tests

#9802 [dotnet] Copy native executable to Contents/MacOS directory in the .app bundle…
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: community, dotnet, macOS, run-dotnet-tests

#9804 [dotnet] Use correct relative path for install_name_tool on macOS
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: community, dotnet, macOS, run-dotnet-tests

#9720 [CoreFoundation] Update bindings up to Xcode 12.2 Beta 2
  src/CoreFoundation/CFBundle.cs
  tests/monotouch-test/CoreFoundation/BundleTest.cs
  tests/xtro-sharpie/macOS-CoreFoundation.todo
Labels: note-highlight

#9813 [photos] Update for Xcode 12.2 beta 2
  src/photos.cs
  tests/xtro-sharpie/iOS-Photos.todo
  tests/xtro-sharpie/macOS-Photos.todo
  tests/xtro-sharpie/tvOS-Photos.todo
Labels: enhancement

#9803 [dotnet] Respect xamarin_executable_name on macOS if specified
  runtime/launcher.m
Labels: community, dotnet, macOS, run-dotnet-tests

#9815 [xcode12.2][qtkit] Stub removed API. Fix #7704
  src/ObjCRuntime/ObsoleteConstants.cs
  src/QTKit/Defs.cs
  src/QTKit/Enums.cs
  src/QTKit/QTCaptureConnection.cs
  src/QTKit/QTCaptureDevice.cs
  src/QTKit/QTCompat.cs
  src/QTKit/QTCompressionOptions.cs
  src/QTKit/QTFormatDescription.cs
  src/QTKit/QTMedia.cs
  src/QTKit/QTMovie.cs
  src/frameworks.sources
  src/qtkit.cs
  tests/xtro-sharpie/macOS-QTKit.ignore
Labels: note-highlight

#9822 [HealthKit] Update bindings up to Xcode 12.2 Beta 2
  src/healthkit.cs
  tests/xtro-sharpie/iOS-HealthKit.todo
  tests/xtro-sharpie/watchOS-HealthKit.todo
Labels: note-highlight

#9820 [oslog] New framework in macOS 11
  src/Constants.mac.cs.in
  src/frameworks.sources
  src/oslog.cs
  tests/monotouch-test/CoreFoundation/OSLogTest.cs
  tests/xtro-sharpie/macOS-OSLog.ignore
  tools/common/Frameworks.cs
Labels: enhancement

#9798 [msbuild] Add SceneKit assets to our items included by default.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  msbuild/Xamarin.MacDev.Tasks.Core/BundleResource.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/DotnetTest.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TestHelpers/TestBase.cs
  tests/common/DotNet.cs
Labels: not-notes-worthy, run-dotnet-tests, run-msbuild-tests

#9801 [msbuild] Move PathUtils.cs to tools/common so that other code can use it too.
  msbuild/Xamarin.MacDev.Tasks.Core/BundleResource.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ZipTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/FindWatchOS1AppExtensionBundleTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/FindWatchOS2AppBundleTaskBase.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/UtilityTests.cs
  tools/common/PathUtils.cs
Labels: not-notes-worthy

#9826 [Foundation] Update up to Xcode 12.2 Beta 2
  src/foundation.cs
  tests/xtro-sharpie/macOS-Foundation.todo
Labels: note-highlight

#9828 [CoreGraphics] Update bindings to Xcode 12.2 Beta 2
  src/CoreGraphics/CGColorSpace.cs
  src/coregraphics.cs
  tests/monotouch-test/CoreGraphics/ColorSpaceTest.cs
  tests/xtro-sharpie/iOS-CoreGraphics.todo
  tests/xtro-sharpie/macOS-CoreGraphics.todo
  tests/xtro-sharpie/tvOS-CoreGraphics.todo
  tests/xtro-sharpie/watchOS-CoreGraphics.todo
Labels: note-highlight

#9823 [dotnet] Add support for 'dotnet build -t:run'.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/GetMlaunchArgumentsTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
  msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArguments.cs
  tools/mlaunch/Makefile
Labels: not-notes-worthy, run-dotnet-tests, run-msbuild-tests

#9797 [msbuild] Remove some watchOS 1 code.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/FindWatchOS1AppExtensionBundleTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ValidateAppBundleTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/FindWatchOS1AppExtensionBundle.cs
Labels: not-notes-worthy

#9821 [dotnet] Fix install name for libxamarin[-debug].dylib on macOS
  runtime/Makefile
  runtime/launcher.m
  runtime/runtime.m
  runtime/xamarin/main.h
Labels: community, dotnet, macOS, run-dotnet-tests

#9833 [dotnet] Default to static libxamarin[-debug].a builds on macOS
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: community, dotnet, macOS, run-dotnet-tests

#9843 [introspection] Do not let intro check on QTKit now that is just stubs
  tests/apitest/src/DelegateAndDataSourceTest.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/Mac/MacApiFieldTest.cs
  tests/introspection/Mac/MacApiWeakPropertyTest.cs
Labels: not-notes-worthy

#9844 [tests] Fix macOS 11 intro/apitest
  src/gamekit.cs
  tests/apitest/src/DelegateAndDataSourceTest.cs
  tests/introspection/Mac/MacApiCtorInitTest.cs
Labels: not-notes-worthy

#9837 [msbuild] Don't use exceptions as control flow in CollectITunesArtworkTaskBase.
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CollectITunesArtworkTaskBase.cs
Labels: not-notes-worthy

#9836 [msbuild] Set DEVELOPER_DIR to the Xcode we're using when calling ibtool.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
  tests/msbuild/Xamarin.iOS.Tasks.Tests/TaskTests/IBToolTaskTests.cs
Labels: not-notes-worthy, run-msbuild-tests

#9845 [dotnet] Remove workaround for F# projects
  tests/fsharplibrary/dotnet/shared.targets
Labels: community, dotnet

#9819 [dotnet] Avoid using install_name_tool on macOS and specify correct rpath instead
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
Labels: community, dotnet, macOS, run-dotnet-tests

#9853 [compare-commits] Ignore Publish.*.txt files when comparing generator output. Fixes #9852.
  tools/compare-commits.sh
Labels: not-notes-worthy

#9863 [dotnet] Remove workaround for mono/linker#1435, which has now been fixed.
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
Labels: not-notes-worthy, run-dotnet-tests

#9858 [msbuild] Re-use existing code to launch processes.
  msbuild/Xamarin.MacDev.Tasks.Core/CommandLineArgumentBuilder.cs
  msbuild/Xamarin.MacDev.Tasks.Core/ProcessUtils.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CoreMLCompilerTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
Labels: not-notes-worthy, skip-public-jenkins

#9859 [tests] Set DEVELOPER_DIR when calling xcrun manually.
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
  tests/monotouch-test/monotouch-test.csproj
  tests/xammac_tests/xammac_tests.csproj
Labels: not-notes-worthy

#9878 [coretelephony] Update for Xcode 12.1 GM
  src/coretelephony.cs
  tests/xtro-sharpie/iOS-CoreTelephony.ignore
Labels: note-highlight

#9879 [apidiff] Compare Xcode 12.1 (iOS 14.1) against stable Xcode 12 (XI 14.0)
  Make.config
Labels: not-notes-worthy

#9871 [tests][intro] Detect cases where [Unavailable] is mis-used
  src/WatchKit/iOS/WKAccessibility.cs
  src/WatchKit/iOS/WKAccessibilityImageRegion.cs
  src/WatchKit/iOS/WKErrorCode.cs
  src/WatchKit/iOS/WKInterfaceButton.cs
  src/WatchKit/iOS/WKInterfaceController.cs
  src/WatchKit/iOS/WKInterfaceDate.cs
  src/WatchKit/iOS/WKInterfaceDevice.cs
  src/WatchKit/iOS/WKInterfaceGroup.cs
  src/WatchKit/iOS/WKInterfaceImage.cs
  src/WatchKit/iOS/WKInterfaceLabel.cs
  src/WatchKit/iOS/WKInterfaceMap.cs
  src/WatchKit/iOS/WKInterfaceObject.cs
  src/WatchKit/iOS/WKInterfaceSeparator.cs
  src/WatchKit/iOS/WKInterfaceSlider.cs
  src/WatchKit/iOS/WKInterfaceSwitch.cs
  src/WatchKit/iOS/WKInterfaceTable.cs
  src/WatchKit/iOS/WKInterfaceTimer.cs
  src/WatchKit/iOS/WKMenuItemIcon.cs
  src/WatchKit/iOS/WKTextInputMode.cs
  src/WatchKit/iOS/WKUserNotificationInterfaceController.cs
  src/WatchKit/iOS/WKUserNotificationInterfaceType.cs
  src/watchkit.cs
  tests/introspection/ApiAvailabilityTest.cs
Labels: not-notes-worthy

#9884 [videotoolbox] Update for Xcode 12.1 GM
  src/videotoolbox.cs
  tests/xtro-sharpie/iOS-VideoToolbox.todo
Labels: note-highlight

#9887 [avfoundation] Update for Xcode 12.1 GM
  src/AVFoundation/Enums.cs
  src/avfoundation.cs
  tests/xtro-sharpie/iOS-AVFoundation.todo
Labels: note-highlight

#9886 [coreimage] Update for Xcode 12.1 GM
  src/coreimage.cs
  tests/xtro-sharpie/iOS-CoreImage.todo
Labels: note-highlight

#9880 [coregraphics] Update for Xcode 12.1 GM
  src/CoreGraphics/CGColorSpace.cs
  src/coregraphics.cs
  tests/common/TestRuntime.cs
  tests/monotouch-test/CoreGraphics/ColorSpaceTest.cs
  tests/xtro-sharpie/iOS-CoreGraphics.todo
Labels: note-highlight

#9890 [mpscore] Update for Xcode 12.1 GM
  src/MetalPerformanceShaders/MPSDefs.cs
Labels: note-highlight

#9891 [imageio] Update bindings up to Xcode 12.1 GM
  src/ImageIO/Enums.cs
  src/imageio.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/iOS-ImageIO.todo
Labels: note-highlight

#9885 [system-dependencies] Only use the locally installed .NET version.
  Make.config
  builds/Makefile
  system-dependencies.sh
Labels: not-notes-worthy

#9895 [tests] Simplify temp file management in the msbuild tests.
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/IBToolTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/MTouchTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/PropertyListEditorTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TestHelpers/TestBase.cs
  tests/msbuild/Xamarin.MacDev.Tests/TargetTests/TargetTests.cs
  tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/TestBase.cs
Labels: not-notes-worthy

#9893 Bump to .NET 5.0.100-rtm.20509.5.
  Make.config
Labels: not-notes-worthy, run-dotnet-tests

#9896 [tests] Put linked source code into an external/ folder in the msbuild test projects.
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj
  tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj
Labels: not-notes-worthy

#9900 [corebluetooth] Update for Xcode 12.2 beta 3
  src/CoreBluetooth/Enums.cs
  tests/xtro-sharpie/iOS-CoreBluetooth.todo
  tests/xtro-sharpie/macOS-CoreBluetooth.todo
  tests/xtro-sharpie/tvOS-CoreBluetooth.todo
  tests/xtro-sharpie/watchOS-CoreBluetooth.todo
Labels: note-highlight

#9905 [videotoolbox] Update attributes and add 12.2 specific key
  src/VideoToolbox/VTVideoEncoder.cs
  src/videotoolbox.cs
  tests/xtro-sharpie/iOS-VideoToolbox.todo
  tests/xtro-sharpie/macOS-VideoToolbox.todo
  tests/xtro-sharpie/tvOS-VideoToolbox.todo
Labels: note-highlight

#9898 [xcode12.2][coregraphics] Update availability wrt Xcode 12.1 GM
  src/CoreGraphics/CGColorSpace.cs
  src/coregraphics.cs
  tests/common/TestRuntime.cs
Labels: note-highlight

#9892 [msbuild] Make the default value for IsMacEnabled property dependent upon the OS.
  msbuild/Xamarin.Shared/Xamarin.Shared.props
Labels: build-package, not-notes-worthy

#9894 [builds] Implement support for optionally cache downloads in ~/Library/Caches/xamarin-macios.
  builds/Makefile
Labels: not-notes-worthy

#9906 [xcode12.2][coreimage] Update availability and new API from Xcode 12.1 GM
  src/coreimage.cs
  tests/xtro-sharpie/iOS-CoreImage.todo
  tests/xtro-sharpie/macOS-CoreImage.todo
  tests/xtro-sharpie/tvOS-CoreImage.todo
Labels: note-highlight

#9907 [xcode12.2][imageio] Update availability and new API from Xcode 12.1 GM
  src/ImageIO/Enums.cs
  src/imageio.cs
  tests/xtro-sharpie/iOS-ImageIO.todo
  tests/xtro-sharpie/macOS-ImageIO.todo
  tests/xtro-sharpie/tvOS-ImageIO.todo
  tests/xtro-sharpie/watchOS-ImageIO.todo
Labels: note-highlight

#9914 [uikit] Update for Xcode 12.2 beta 3
  src/uikit.cs
Labels: note-highlight

#9913 [xcode12.2][avfoundation] Update for Xcode 12.1 GM
  src/AVFoundation/Enums.cs
  src/avfoundation.cs
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/macOS-AVFoundation.todo
  tests/xtro-sharpie/tvOS-AVFoundation.todo
Labels: note-highlight

#9917 [avkit] Update for Xcode 12.2 beta 3
  src/avkit.cs
  tests/xtro-sharpie/iOS-AVKit.todo
Labels: note-highlight

#9918 [fileprovider] Update for Xcode 12.2 beta 3
  src/fileprovider.cs
  tests/xtro-sharpie/macOS-FileProvider.todo
Labels: note-highlight

#9919 [coreimage] Update macOS availability for new filter attributes added in 12.1 GM
  src/coreimage.cs
Labels: not-notes-worthy

#9915 [xcode12.1] [tests] Fix sample tests to take into account when a platform has been disabled.
  tests/sampletester/SampleTester.cs
  tools/devops/build-samples.csx
Labels: not-notes-worthy, pr-change-not-shipping

#9916 [xcode12] [tests] Fix sample tests to take into account when a platform has been disabled.
  tests/sampletester/SampleTester.cs
  tools/devops/build-samples.csx
Labels: not-notes-worthy, pr-change-not-shipping

#9926 [xharness] Announce to the world that we're creating UTF8 documents.
  tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
Labels: not-notes-worthy

#9923 [xcode12.2] [monotouch] Fix ARSkeletonTest failure
  tests/monotouch-test/ARKit/ARSkeletonTest.cs
Labels: not-notes-worthy

#9910 [dotnet] Don't run the linker nor install_name_tool when running in offline mode on Windows.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-internal-tests, skip-public-jenkins

#9922 [monotouch] Fix ARSkeletonTest failure
  tests/monotouch-test/ARKit/ARSkeletonTest.cs
Labels: ci-failure, not-notes-worthy, pr-change-not-shipping

#9930 [storekit] Update for Xcode 12.2 beta 3
  src/StoreKit/Enums.cs
  src/storekit.cs
  tests/xtro-sharpie/iOS-StoreKit.todo
  tests/xtro-sharpie/macOS-StoreKit.todo
  tests/xtro-sharpie/tvOS-StoreKit.todo
  tests/xtro-sharpie/watchOS-StoreKit.todo
Labels: note-highlight

#9931 [videotoolbox] Add missing VTVideoEncoderList mappings. Fix 9904
  src/VideoToolbox/VTVideoEncoder.cs
Labels: enhancement

#9927 [xharness] Give the MSBuild tests 30 more minutes to finish. Fixes #xamarin/maccore@2623.
  tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
Labels: not-notes-worthy

#9933 [Main] Bring Xcode12.1 support.
  Make.config
  Make.versions
  Versions-ios.plist.in
  jenkins/Jenkinsfile
  src/AVFoundation/Enums.cs
  src/CoreGraphics/CGColorSpace.cs
  src/ImageIO/Enums.cs
  src/MetalPerformanceShaders/MPSDefs.cs
  src/avfoundation.cs
  src/coregraphics.cs
  src/coreimage.cs
  src/coretelephony.cs
  src/imageio.cs
  src/videotoolbox.cs
  tests/common/TestRuntime.cs
  tests/introspection/ApiCoreImageFiltersTest.cs
  tests/monotouch-test/CoreGraphics/ColorSpaceTest.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/iOS-CoreGraphics.todo
  tests/xtro-sharpie/iOS-CoreTelephony.ignore
  tests/xtro-sharpie/iOS-MetalPerformanceShadersGraph.todo
Labels: note-highlight

#9936 [dotnet] Don't try to update the location of the dynamic libraries when we didn't fix them.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#9846 Fixed issue with code signing when using multiple AdditionalAppExtensions
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: community, notes-mention

#9940 Bump API diff to be produced against xcode12.1
  Make.config
Labels: not-notes-worthy

#9943 [xcode12.2] Fixed issue with code signing when using multiple AdditionalAppExtensions
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: community

#9935 [tests][xcode12.2] Fix xammac tests
  tests/common/TestRuntime.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/iOS/iOSApiCtorInitTest.cs
  tests/monotouch-test/AudioUnit/AudioUnitTest.cs
  tests/monotouch-test/CoreGraphics/ColorTest.cs
  tests/monotouch-test/CoreText/FontManagerTest.cs
  tests/monotouch-test/GameKit/LeaderboardViewControllerTest.cs
  tests/monotouch-test/MLCompute/MLEnumsTest.cs
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
  tests/monotouch-test/Metal/MTLBlitPassDescriptorTest.cs
  tests/monotouch-test/Metal/MTLBlitPassSampleBufferAttachmentDescriptorArrayTest.cs
  tests/monotouch-test/Metal/MTLBlitPassSampleBufferAttachmentDescriptorTest.cs
  tests/monotouch-test/Metal/MTLComputePassDescriptorTest.cs
  tests/monotouch-test/Metal/MTLComputePassSampleBufferAttachmentDescriptorArrayTest.cs
  tests/monotouch-test/Metal/MTLComputePassSampleBufferAttachmentDescriptorTest.cs
  tests/monotouch-test/Metal/MTLIntersectionFunctionTableDescriptorTest.cs
  tests/monotouch-test/Metal/MTLLinkedFunctionsTest.cs
  tests/monotouch-test/Metal/MTLRenderPassSampleBufferAttachmentDescriptorArrayTest.cs
  tests/monotouch-test/Metal/MTLRenderPassSampleBufferAttachmentDescriptorTest.cs
  tests/monotouch-test/Metal/MTLResourceStatePassDescriptorTest.cs
  tests/monotouch-test/Metal/MTLResourceStatePassSampleBufferAttachmentDescriptorArrayTest.cs
  tests/monotouch-test/Metal/MTLResourceStatePassSampleBufferAttachmentDescriptorTest.cs
  tests/monotouch-test/Metal/MTLTileRenderPipelineDescriptorTest.cs
  tests/monotouch-test/Metal/MTLVisibleFunctionTableDescriptorTest.cs
  tests/monotouch-test/ModelIO/MDLAnimatedValueTypesTests.cs
  tests/monotouch-test/NaturalLanguage/NLTaggerTest.cs
  tests/monotouch-test/Network/NWConnectionGroupTest.cs
  tests/monotouch-test/Network/NWMulticastGroupTest.cs
  tests/monotouch-test/Security/TrustTest.cs
  tests/monotouch-test/UniformTypeIdentifiers/TypeTest.cs
  tests/monotouch-test/VideoToolbox/VTUtilitiesTests.cs
  tests/monotouch-test/Vision/VNCircleTests.cs
  tests/monotouch-test/Vision/VNGeometryUtilsTests.cs
  tests/monotouch-test/Vision/VNRequestTests.cs
  tests/monotouch-test/Vision/VNVectorTests.cs
Labels: not-notes-worthy

#9941 [xharness] Make the MSBuildTask capable of building .NET projects.
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
  tests/xharness/Jenkins/TestTasks/BuildProjectTask.cs
  tests/xharness/Jenkins/TestTasks/BuildToolTask.cs
  tests/xharness/Jenkins/TestTasks/DotNetBuildTask.cs
  tests/xharness/Jenkins/TestTasks/DotNetTestTask.cs
  tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
  tests/xharness/Jenkins/TestTasks/MakeTask.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy, run-dotnet-tests

#9947 [xharness] Create device variations for the .NET tests.
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/RunDeviceTasksFactory.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestProject.cs
Labels: not-notes-worthy

#9948 [msbuild] Change XamarinTask to fail the build if a tool fails to execute.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
Labels: not-notes-worthy, run-dotnet-tests

#9946 [msbuild] Always create debug symbols when building native code.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileNativeCodeTaskBase.cs
Labels: not-notes-worthy, run-dotnet-tests

#9945 [msbuild] Add a TargetArchitectures argument to the LinkNativeCode task.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
  msbuild/Xamarin.MacDev.Tasks.Core/TargetArchitecture.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
Labels: not-notes-worthy, run-dotnet-tests

#9944 [dotnet] Only fix the id of mono libraries which are actually dylibs.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#9952 [tests] Make the baseline sample test pass the correct environment variables.
  tests/sampletester/SampleTester.cs
Labels: not-notes-worthy, run-internal-tests, run-sample-tests, skip-public-jenkins

#9955 [tools] Renumber RemoveRejectedTypesStep's error code base to match other ExceptionalSubStep subclasses.
  tools/linker/RemoveRejectedTypesStep.cs
  tools/mtouch/Errors.resx
Labels: not-notes-worthy

#9953 [tools/dotnet] Re-use the existing main generation code in our dotnet code.
  tools/common/Application.cs
  tools/common/Assembly.cs
  tools/common/BitCodeMode.cs
  tools/common/Driver.cs
  tools/common/Target.cs
  tools/dotnet-linker/Compat.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/mmp/Application.mmp.cs
  tools/mmp/driver.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/Assembly.mtouch.cs
  tools/mtouch/BuildTasks.mtouch.cs
  tools/mtouch/mtouch.cs
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy, run-dotnet-tests

#9959 [tools] Localize error messages from the ExceptionSubStep linker step.
  tools/linker/ExceptionalSubStep.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#9954 [dotnet-linker] Catch any exceptions from our custom steps and show them using our error reporting logic.
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/CollectAssembliesStep.cs
  tools/dotnet-linker/Steps/CollectUnmarkedMembers.cs
  tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
  tools/dotnet-linker/Steps/ConfigurationAwareSubStep.cs
  tools/dotnet-linker/Steps/ExtractBindingLibrariesStep.cs
  tools/dotnet-linker/Steps/GatherFrameworksStep.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
  tools/dotnet-linker/Steps/LoadNonSkippedAssembliesStep.cs
  tools/dotnet-linker/Steps/PreserveBlockCodeSubStep.cs
  tools/dotnet-linker/Steps/RegistrarStep.cs
  tools/linker/ExceptionalSubStep.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy, run-dotnet-tests

#9967 [Actions] Fix the if condition. Return error with empty labels.
  .github/workflows/label-checker.yml
Labels: not-notes-worthy

#9969 [d16-8] Add label checks.
  .github/workflows/label-checker.yml
Labels: not-notes-worthy

#9970 [Xcode12.2] Add label checks.
  .github/workflows/label-checker.yml
Labels: not-notes-worthy

#9965 [msbuild] Have `XcodeCompilerToolTask` use `xcrun` to start Apple tools
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
  tests/mmptest/src/MMPTest.cs
Labels: enhancement

#9976 [xharness] Automatically run the msbuild tests if something in the msbuild or tests/msbuild directories changed.
  tests/xharness/Jenkins/TestSelector.cs
Labels: not-notes-worthy

#9973 [Makefile] Point to xcode12.1 xip file.
  Make.config
Labels: not-notes-worthy

#9978 [dotnet] Ship a LICENSE file with the workloads.
  dotnet/.gitignore
  dotnet/Makefile
Labels: not-notes-worthy, run-dotnet-tests

#9972 [msbuild] Have `XcodeCompilerToolTask` use `xcrun` to start Apple tools (#9965)
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
  tests/mmptest/src/MMPTest.cs
Labels: enhancement

#9977 [tests] Set MSBuildEnableWorkloadResolver=true when running the .NET tests.
  tests/common/DotNet.cs
Labels: not-notes-worthy, run-dotnet-tests

#9975 [tests] Clean up Xamarin.MacDev.Tasks.Tests.
  tests/Makefile
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/IBToolTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/PropertyListEditorTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TestHelpers/Logger.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TestHelpers/TestBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TestHelpers/TestEngine.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj
  tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
Labels: not-notes-worthy, run-msbuild-tests

#9979 [dotnet] Package the workloads in a Windows installer (.msi) as well.
  dotnet/.gitignore
  dotnet/Makefile
  dotnet/generate-wix.csharp
  jenkins/Jenkinsfile
  jenkins/build-nugets.sh
Labels: build-package, not-notes-worthy, run-dotnet-tests

#9981 [README] Bump downloads to our new Xamarin.iOS stable
  README.md
Labels: not-notes-worthy, skip-all-tests, skip-public-jenkins, skip-public-tests

#9982 [tests] Fix assert in DetectAppManifest_LibraryProject.
  tests/msbuild/Xamarin.MacDev.Tests/TargetTests/TargetTests.cs
Labels: not-notes-worthy, run-msbuild-tests

#9985 [tests] Use MyiOSFrameworkBinding as a binding test project instead of bindings-test
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/BindingProject.cs
Labels: not-notes-worthy

#9987 [tests] Simplify a WatchKit 1 test (since we don't support WatchKit 1 anymore)
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/Extensions/WatchKit.cs
Labels: not-notes-worthy

#9986 [tests] Bump Xamarin.MacDev.Tests to net472
  tests/Makefile
  tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj
  tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
Labels: not-notes-worthy

#9988 [tests][monotouch-tests] ModelIO tests can't be executed on old Mac
  tests/monotouch-test/ModelIO/MDLAnimatedValueTypesTests.cs
Labels: pr-change-not-shipping

#9993 [appkit] Fix NSAvailability availability information
  src/AppKit/NSAccessibility.cs
  src/appkit.cs
  src/generator.cs
Labels: not-notes-worthy

#9983 [tests] Rewrite ValidateAppBundleTaskTests to not create a task in-process.
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/Extensions/ExtensionTestBase.cs
  tests/msbuild/Xamarin.MacDev.Tests/TargetTests/ValidateAppBundleTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/TestBase.cs
Labels: not-notes-worthy, run-msbuild-tests

#9990 [tools] Always show nested exceptions if they're our own exceptions.
  tools/common/ErrorHelper.tools.cs
Labels: not-notes-worthy

#9991 [dotnet] Improve context-ful linker errors by including the underlying exception message in the output.
  tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy, run-dotnet-tests

#9992 [dotnet-linker] Improve error reporting by consolidating it in the LinkerConfiguration class.
  src/ObjCRuntime/ErrorHelper.cs
  tools/common/ErrorHelper.tools.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
  tools/dotnet-linker/Steps/ConfigurationAwareSubStep.cs
Labels: not-notes-worthy, run-dotnet-tests

#9841 [dotnet] Add asset catalogs to the our items included by default.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
  tests/common/DotNet.cs
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests, skip-all-tests

#9998 [bgen] Improve output when compilation fails for either the binding sources or the generated sources.
  src/btouch.cs
Labels: not-notes-worthy

#10008 [Actions] Add debug for the workflow to find why it does not work with hub
  .github/workflows/label-checker.yml
Labels: not-notes-worthy, skip-all-tests

#9989 [dotnet] Don't try to include any results from the AOT compiler unless we're on a Mac.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#9999 [tests] Remove 10.15 version checks since we only run on 10.15+ now.
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/Extensions/CustomKeyboard.cs
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/TVOS/TVApp.cs
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/TVOS/TVMetalGameTests.cs
Labels: not-notes-worthy

#9997 [bgen] Fix verbosity mode confusion.
  src/btouch.cs
Labels: not-notes-worthy

#10006 [xcode12.2] Bump maccore. Fixes #9961.
  mk/xamarin.mk
Labels: bug, run-internal-tests, skip-public-jenkins

#10011 [compare-commits] Fix corruption in dotnet assemblies after API comparison.
  tools/compare-commits.sh
Labels: not-notes-worthy
