Repository dotnet/macios, pull requests merged in 2020-06, with the labels that each got.

#8710 [msbuild] Share some of the code signing targets between Xamarin.Mac and Xamarin.iOS.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8713 [tests] Remove unused file from the mtouch tests.
  tests/mtouch/RuntimeException.cs
  tests/mtouch/mtouch.csproj
Labels: not-notes-worthy

#8714 [dotnet] Add class library test project for every platform.
  tests/dotnet/MyClassLibrary/MyClass.cs
  tests/dotnet/MyClassLibrary/MyClassLibrary.csproj
  tests/dotnet/MyClassLibrary/iOS/MyClass.cs
  tests/dotnet/MyClassLibrary/iOS/MyClassLibrary.csproj
  tests/dotnet/MyClassLibrary/macOS/MyClass.cs
  tests/dotnet/MyClassLibrary/macOS/MyClassLibrary.csproj
  tests/dotnet/MyClassLibrary/tvOS/MyClass.cs
  tests/dotnet/MyClassLibrary/tvOS/MyClassLibrary.csproj
  tests/dotnet/MyClassLibrary/watchOS/MyClass.cs
  tests/dotnet/MyClassLibrary/watchOS/MyClassLibrary.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#8719 [AddressBookUI] Fix indentation.
  src/AddressBookUI/ABPeoplePickerNavigationController.cs
Labels: not-notes-worthy

#8715 [dotnet] Inject logic into the Build target to put resolved assemblies and dylibs into the .app.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
Labels: not-notes-worthy

#8720 [runtime] Remove Classic code.
  runtime/bindings.h
  runtime/bindings.m
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#8711 [msbuild] Add a Xamarin.Shared.props.
  msbuild/Makefile
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
Labels: not-notes-worthy

#8725 [mtouch] Remove XAMCORE_2_0 define from simlauncher build.
  tools/mtouch/Makefile
Labels: not-notes-worthy

#8723 [mtouch/mmp] Add CFNetwork to our list of frameworks for iOS and macOS.
  tools/common/Frameworks.cs
Labels: not-notes-worthy

#8726 [msbuild] Unify XamMacResourcePrefix and IPhoneResourcePrefix into _ResourcePrefix.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.targets
Labels: not-notes-worthy

#8729 [dotnet] Improve the 'clean' target.
  dotnet/Makefile
Labels: not-notes-worthy

#8728 [tests] Add a global.json targeting dotnet 3.1.100 to the dotnet unit tests.
  tests/dotnet/UnitTests/global.json
Labels: not-notes-worthy

#8733 [dotnet] Add dotnet-linker, a project to contain custom linker steps for our net5.0 build.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/DotNet.cs
  tests/dotnet/UnitTests/ProjectTest.cs
  tools/Makefile
  tools/common/create-makefile-fragment.sh
  tools/dotnet-linker/.gitignore
  tools/dotnet-linker/Makefile
  tools/dotnet-linker/NuGet.config
  tools/dotnet-linker/README.md
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/dotnet-linker/dotnet-linker.sln
  tools/dotnet-linker/global.json
Labels: not-notes-worthy

#8734 [msbuild] Unify MtouchSdkVersion and MacOSXSdkVersion into _SdkVersion.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8746 [generator] Remove [RetainList] from generator-attributes and docs
  docs/website/binding_types_reference_guide.md
  src/generator-attributes.cs
Labels: not-notes-worthy

#8744 [src] Remove files that only contain Classic code.
  src/AVFoundation/AVAudioUnit.cs
  src/AVFoundation/AVCaptureVideoDataOutput.cs
  src/AVFoundation/DescriptionHelpers.cs
  src/AssetsLibrary/ALAssetsLibrary.cs
  src/AudioToolbox/AudioBufferList.cs
  src/AudioUnit/AudioGraphEventArgs.cs
  src/AudioUnit/AudioUnitEventArgs.cs
  src/AudioUnit/_AudioConverter.cs
  src/AudioUnit/_AudioConverterEventArgs.cs
  src/Compat.iOS.cs
  src/CoreData/NSAttributeDescription.cs
  src/CoreFoundation/CFIndex.cs
  src/CoreLocation/CLLocationManagerDelegate.cs
  src/CoreLocation/CoreLocation2.cs
  src/Foundation/NSCompoundPredicate.cs
  src/Foundation/NSExtension.cs
  src/Foundation/NSHttpCookieStorage.cs
  src/Foundation/NSJsonSerialization.cs
  src/Foundation/NSMutableArray.cs
  src/Foundation/NSPortMessage.cs
  src/GameController/Compat.cs
  src/Makefile
  src/MapKit/MKCircle.cs
  src/MapKit/MKMapView.cs
  src/MediaPlayer/MPMediaItemProperty.cs
  src/Obsoletes.cs
  src/UIKit/UIApplicationDelegate.cs
  src/UIKit/UIDocumentInteractionController.cs
  src/UIKit/UINib.cs
  src/UIKit/UIResponder.cs
  src/frameworks.sources
Labels: not-notes-worthy

#8745 [msbuild] Unify the _DetectAppManifest target.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8751 [msbuild] Share _ComputeTargetArchitectures and use the output variables for both Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8743 [msbuild] Unify _RequireCodeSigning and EnableCodeSigning into _RequireCodeSigning.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8753 [dotnet-linker] Fix dependency tracking in the makefile.
  tools/dotnet-linker/Makefile
Labels: not-notes-worthy

#8754 [dotnet] Improve incremental builds in make.
  dotnet/Makefile
  mk/quiet.mk
Labels: not-notes-worthy

#8750 [src] Remove Classic code from the Accelerate, Accounts, AddressBook[UI] and ARKit frameworks.
  src/ARKit/ARFaceGeometry.cs
  src/ARKit/ARPlaneGeometry.cs
  src/ARKit/ARPointCloud.cs
  src/ARKit/ARSkeleton2D.cs
  src/ARKit/ARSkeleton3D.cs
  src/Accelerate/vImageTypes.cs
  src/Accounts/AccountStoreOptions.cs
  src/AddressBook/ABPerson.cs
  src/AddressBook/ABSource.cs
  src/AddressBookUI/ABNewPersonViewController.cs
  src/AddressBookUI/ABPeoplePickerNavigationController.cs
  src/AddressBookUI/ABPersonViewController.cs
  src/AddressBookUI/ABUnknownPersonViewController.cs
  src/accounts.cs
  src/addressbookui.cs
  src/arkit.cs
Labels: not-notes-worthy

#8749 [tools] Fix printing failed command to print the actual arguments instead of the list itself.
  tests/common/mac/ProjectTestHelpers.cs
  tools/common/Driver.cs
Labels: not-notes-worthy

#8766 [sharpie] Use a better CDN download link
  Make.config
Labels: not-notes-worthy

#8771 [CODEOWNERS] Update ownership.
  CODEOWNERS
Labels: skip-all-tests

#8767 [d16-7] [sharpie] Use a better CDN download link
  Make.config
Labels: not-notes-worthy

#8769 [tools] Remove MD5 from tooling
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Helpers.cs
  tools/apidiff/merger.cs
Labels: not-notes-worthy, pr-change-not-shipping

#8762 [src] Remove Classic code from the AudioUnit, AudioToolbox and AssetsLibrary frameworks.
  src/AssetsLibrary/ALAsset.cs
  src/AssetsLibrary/ALAssetsGroup.cs
  src/AudioToolbox/AudioFile.cs
  src/AudioToolbox/AudioQueue.cs
  src/AudioToolbox/AudioSession.cs
  src/AudioToolbox/AudioToolbox.cs
  src/AudioToolbox/AudioType.cs
  src/AudioToolbox/MusicSequence.cs
  src/AudioUnit/AUGraph.cs
  src/AudioUnit/AUParameter.cs
  src/AudioUnit/AUParameterNode.cs
  src/AudioUnit/AudioComponent.cs
  src/AudioUnit/AudioComponentDescription.cs
  src/AudioUnit/AudioUnit.cs
  src/AudioUnit/AudioUnitUtils.cs
  src/AudioUnit/ExtAudioFile.cs
  src/assetslibrary.cs
  src/audiounit.cs
Labels: not-notes-worthy

#8765 [src] Remove Classic code from AVFoundation.
  src/AVFoundation/AVAssetImageGenerator.cs
  src/AVFoundation/AVAssetReaderVideoCompositionOutput.cs
  src/AVFoundation/AVAudioPlayer.cs
  src/AVFoundation/AVAudioRecorder.cs
  src/AVFoundation/AVAudioSession.cs
  src/AVFoundation/AVAudioSessionDataSourceDescription.cs
  src/AVFoundation/AVAudioSettings.cs
  src/AVFoundation/AVCaptureConnection.cs
  src/AVFoundation/AVCaptureDeviceInput.cs
  src/AVFoundation/AVCaptureMetadataOutput.cs
  src/AVFoundation/AVCompat.cs
  src/AVFoundation/AVLayerVideoGravity.cs
  src/AVFoundation/AVMetadataItemFilter.cs
  src/AVFoundation/AVMetadataMachineReadableCodeObject.cs
  src/AVFoundation/AVMetadataObject.cs
  src/AVFoundation/AVPlayer.cs
  src/AVFoundation/AVTypes.cs
  src/AVFoundation/AVVideoSettings.cs
  src/AVFoundation/Enums.cs
  src/avfoundation.cs
Labels: not-notes-worthy

#8752 [dotnet] Detect, compile and publish Info.plist into the app.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#8780 [dotnet-linker] Add support for passing configuration from the MSBuild targets to our linker steps.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
Labels: not-notes-worthy

#8779 [src] Remove Classic code from the CoreData, CoreFoundation, CoreGraphics, CoreImage and CoreLocation frameworks.
  src/CoreData/Enums.cs
  src/CoreData/Obsolete.cs
  src/CoreFoundation/CFAllocator.cs
  src/CoreFoundation/CFBoolean.cs
  src/CoreFoundation/CFDictionary.cs
  src/CoreFoundation/CFReadStream.cs
  src/CoreFoundation/CFRunLoop.cs
  src/CoreFoundation/CFStream.cs
  src/CoreFoundation/CFString.cs
  src/CoreFoundation/CFWriteStream.cs
  src/CoreGraphics/CGBitmapContext.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGContext.cs
  src/CoreGraphics/CGEvent.cs
  src/CoreGraphics/CGFont.cs
  src/CoreGraphics/CGGeometry.cs
  src/CoreGraphics/CGImageProperties.cs
  src/CoreGraphics/CGPDFDocument.cs
  src/CoreGraphics/CGPDFStream.cs
  src/CoreGraphics/CGPath.cs
  src/CoreImage/CIImage.cs
  src/CoreLocation/CLCompat.cs
  src/CoreLocation/CLLocationManager.cs
  src/CoreLocation/CoreLocation.cs
  src/coregraphics.cs
  src/coreimage.cs
  src/corelocation.cs
Labels: not-notes-worthy

#8778 [src] Remove Classic code from the CoreBluetooth, CoreAudioKit, CoreAnimation, ContactsUI, Contacts, CloudKit, ClassKit, CFNetwork, CarPlay, CallKit and BusinessChat frameworks.
  src/BusinessChat/BCChatAction.cs
  src/CFNetwork/Content.cs
  src/CFNetwork/MessageHandler.cs
  src/CFNetwork/WorkerThread.cs
  src/CallKit/CXProvider.cs
  src/CarPlay/CPNavigationAlert.cs
  src/ClassKit/CLSContext.cs
  src/CloudKit/CKRecord.cs
  src/CloudKit/CKUserIdentityLookupInfo.cs
  src/Contacts/CNContact.cs
  src/Contacts/CNContactFetchRequest.cs
  src/Contacts/CNContactStore.cs
  src/Contacts/CNEnums.cs
  src/Contacts/CNInstantMessageAddress.cs
  src/Contacts/CNObsolete.cs
  src/Contacts/CNSocialProfile.cs
  src/CoreAnimation/CADefs.cs
  src/CoreAnimation/CALayer.cs
  src/CoreAnimation/CAMediaTimingFunction.cs
  src/CoreAnimation/CATextLayer.cs
  src/CoreBluetooth/CBUUID.cs
  src/CoreBluetooth/CoreBluetooth.cs
  src/CoreBluetooth/GuidWrapper.cs
  src/CoreBluetooth/PeripheralConnectionOptions.cs
  src/callkit.cs
  src/carplay.cs
  src/classkit.cs
  src/cloudkit.cs
  src/contacts.cs
  src/contactsui.cs
  src/coreanimation.cs
  src/coreaudiokit.cs
  src/corebluetooth.cs
Labels: not-notes-worthy

#8758 [msbuild] Unify CodesignKey and CodeSigningKey into _SpecifiedCodesignKey.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8755 [msbuild] Share the _DetectSdkLocations target.
  msbuild/Xamarin.Mac.Tasks/Tasks/DetectSdkLocations.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8781 [mtouch] Remove empty comment tags from localization resx files.
  src/Resources.resx
  src/bgen/bgen.csproj
  src/generator.csproj
  tools/mmp/mmp.csproj
  tools/mtouch/Errors.resx
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#8785 [msbuild] Share the _DetectSigningIdentity target.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/DetectSigningIdentityTaskCore.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/DetectSigningIdentity.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSigningIdentityTaskCore.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/DetectSigningIdentity.cs
Labels: not-notes-worthy

#8786 [src] Remove Classic code from the CoreMedia, CoreMidi, CoreML, CoreMotion, CoreNFC, CoreTelephony and CoreText frameworks.
  src/CoreML/MLDictionaryFeatureProvider.cs
  src/CoreML/MLMultiArray.cs
  src/CoreML/MLMultiArrayConstraint.cs
  src/CoreMedia/CMAttachmentBearer.cs
  src/CoreMedia/CMFormatDescription.cs
  src/CoreMedia/CMSampleBuffer.cs
  src/CoreMedia/CMSync.cs
  src/CoreMedia/CMTime.cs
  src/CoreMedia/CoreMedia.cs
  src/CoreMidi/MidiServices.cs
  src/CoreMotion/Extras.cs
  src/CoreText/Adapter.cs
  src/CoreText/CTFont.cs
  src/CoreText/CTFontDescriptor.cs
  src/CoreText/CTRunDelegate.cs
  src/coreml.cs
  src/corenfc.cs
  src/coretelephony.cs
  src/coretext.cs
Labels: not-notes-worthy

#8790 [README.md] Fix markdown warnings. Don't force 'en-us' URL.
  README.md
Labels: not-notes-worthy, skip-all-tests

#8798 [tests] Remove the MT1211 mtouch test.
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#8799 [tests] Update the MT0051 tests to use newer test helper API.
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#8800 [devops] Add Policheck tool to our pipeline and update CredScan to latest version
  mk/xamarin.mk
  tools/devops/azure-pipelines.yml
Labels: skip-all-tests

#8802 [d16-7][devops] Add Policheck tool to our pipeline
  mk/xamarin.mk
  tools/devops/azure-pipelines.yml
Labels: skip-all-tests

#8793 [src] Remove Classic code from the FinderSync, FileProvider[UI], ExternalAccessory, EventKit[UI], DeviceCheck, CoreWlan and CoreVideo frameworks.
  src/CoreVideo/CVBuffer.cs
  src/CoreVideo/CVImageBuffer.cs
  src/CoreVideo/CVMetalTextureAttributes.cs
  src/CoreVideo/CVMetalTextureCache.cs
  src/CoreVideo/CVOpenGLESTexture.cs
  src/CoreVideo/CVOpenGLESTextureCache.cs
  src/CoreVideo/CVPixelBuffer.cs
  src/CoreVideo/CVPixelBufferAttributes.cs
  src/CoreVideo/CVPixelBufferIOSurface.cs
  src/CoreVideo/CVPixelBufferPool.cs
  src/CoreVideo/CVTime.cs
  src/CoreVideo/CoreVideo.cs
  src/CoreWlan/Enums.cs
  src/EventKit/EKEnums.cs
  src/EventKit/EventKit.cs
  src/EventKitUI/Defs.cs
  src/EventKitUI/EKUIBundle.cs
  src/corevideo.cs
  src/devicecheck.cs
  src/eventkit.cs
  src/externalaccessory.cs
  src/fileprovider.cs
  src/fileproviderui.cs
  src/findersync.cs
Labels: not-notes-worthy

#8794 [src] Remove Classic code from Foundation.
  src/Foundation/Additions.cs
  src/Foundation/Compat.cs
  src/Foundation/DictionaryContainer.cs
  src/Foundation/Enum.cs
  src/Foundation/ExportAttribute.cs
  src/Foundation/FieldAttribute.cs
  src/Foundation/NSArray.cs
  src/Foundation/NSArray_1.cs
  src/Foundation/NSAutoreleasePool.cs
  src/Foundation/NSBundleResourceRequest.cs
  src/Foundation/NSCoder.cs
  src/Foundation/NSDate.cs
  src/Foundation/NSDecimal.cs
  src/Foundation/NSDictionary_2.cs
  src/Foundation/NSFileManager.cs
  src/Foundation/NSHttpCookie.cs
  src/Foundation/NSIndexPath.cs
  src/Foundation/NSIndexSet.cs
  src/Foundation/NSItemProvider.cs
  src/Foundation/NSMetadataItem.cs
  src/Foundation/NSMutableArray_1.cs
  src/Foundation/NSMutableData.cs
  src/Foundation/NSMutableDictionary_2.cs
  src/Foundation/NSMutableOrderedSet_1.cs
  src/Foundation/NSMutableSet_1.cs
  src/Foundation/NSNotificationCenter.cs
  src/Foundation/NSNumber.mac.cs
  src/Foundation/NSNumber2.cs
  src/Foundation/NSOrderedSet_1.cs
  src/Foundation/NSProgress.cs
  src/Foundation/NSRange.cs
  src/Foundation/NSRunLoop.cs
  src/Foundation/NSSet_1.cs
  src/Foundation/NSString.cs
  src/Foundation/NSString2.cs
  src/Foundation/NSTimer.cs
  src/Foundation/NSUbiquitousKeyValueStore.cs
  src/Foundation/NSUrl.cs
  src/Foundation/NSUrlConnection.cs
  src/Foundation/NSUrlCredential.cs
  src/Foundation/NSUrlProtectionSpace.cs
  src/Foundation/NSUrlProtocol.cs
  src/Foundation/NSUrlProtocolClient.cs
  src/Foundation/NSUrlSession.cs
  src/Foundation/NSUrlSessionHandler.cs
  src/Foundation/NSUserDefaults.cs
  src/Foundation/RegisterAttribute.cs
  src/foundation.cs
Labels: not-notes-worthy

#8797 [msbuild] Unify MtouchArch and XamMacArch into TargetArchitectures.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
Labels: not-notes-worthy

#8813 [msbuild] Remove the support for faking the watchOS 4.3 SDK.
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8808 [src] Remove Classic code from SceneKit.
  src/SceneKit/Defs.cs
  src/SceneKit/SCNCompat.cs
  src/SceneKit/SCNGeometrySource.cs
  src/SceneKit/SCNJavaScript.cs
  src/SceneKit/SCNMatrix4.cs
  src/SceneKit/SCNQuaternion.cs
  src/SceneKit/SCNTechnique.cs
  src/SceneKit/SCNVector3.cs
  src/SceneKit/SCNVector4.cs
  src/scenekit.cs
Labels: not-notes-worthy

#8809 [src] Remove Classic code from UIKit.
  src/UIKit/Compat.cs
  src/UIKit/NSLayoutConstraint.cs
  src/UIKit/NSLayoutManager.cs
  src/UIKit/UIAppearance.cs
  src/UIKit/UIControl.cs
  src/UIKit/UIDevice.cs
  src/UIKit/UIEnums.cs
  src/UIKit/UIFont.cs
  src/UIKit/UIFontDescriptor.cs
  src/UIKit/UIGestureRecognizer.cs
  src/UIKit/UIGuidedAccessRestriction.cs
  src/UIKit/UIImage.cs
  src/UIKit/UIImagePickerController.cs
  src/UIKit/UINavigationBar.cs
  src/UIKit/UIPickerView.cs
  src/UIKit/UIScreen.cs
  src/UIKit/UITableView.cs
  src/UIKit/UITextField.cs
  src/UIKit/UITypes.cs
  src/UIKit/UIView.cs
  src/UIKit/UIWindow.cs
  src/uikit.cs
Labels: not-notes-worthy

#8811 [msbuild] We have a top-level editor config now, so use that.
  msbuild/.editorconfig
Labels: not-notes-worthy, skip-all-tests

#8812 [msbuild] Remove duplicate NativeReferenceKind enum.
  msbuild/Xamarin.MacDev.Tasks.Core/NativeReferenceKind.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
Labels: not-notes-worthy

#8827 [apidiff] Fix range expression.
  tools/apidiff/merger.cs
Labels: not-notes-worthy

#8829 [ObjCRuntime] Revert unintentional Unified API changes.
  src/ObjCRuntime/Selector.mac.cs
Labels: not-notes-worthy

#8824 [d16-7] [ObjCRuntime] Remove Classic code.
  src/ObjCRuntime/AdoptsAttribute.cs
  src/ObjCRuntime/AlphaAttribute.cs
  src/ObjCRuntime/BlockProxyAttribute.cs
  src/ObjCRuntime/Blocks.cs
  src/ObjCRuntime/Class.cs
  src/ObjCRuntime/CompileFlagsAttribute.cs
  src/ObjCRuntime/DelayedRegistrationAttribute.cs
  src/ObjCRuntime/Dlfcn.cs
  src/ObjCRuntime/LinkWithAttribute.cs
  src/ObjCRuntime/Messaging.iOS.cs
  src/ObjCRuntime/Messaging.mac.cs
  src/ObjCRuntime/Messaging.watch.cs
  src/ObjCRuntime/Method.cs
  src/ObjCRuntime/MethodDescription.cs
  src/ObjCRuntime/NSStringMarshal.cs
  src/ObjCRuntime/PlatformAvailability.cs
  src/ObjCRuntime/ReleaseAttribute.cs
  src/ObjCRuntime/RequiredFrameworkAttribute.cs
  src/ObjCRuntime/Selector.cs
  src/ObjCRuntime/Selector.iOS.cs
  src/ObjCRuntime/Selector.mac.cs
  src/ObjCRuntime/ThreadSafeAttribute.cs
  src/ObjCRuntime/Trampolines.cs
  src/ObjCRuntime/TransientAttribute.cs
  src/bgen/bgen.csproj
  src/frameworks.sources
  src/generator.cs
  src/generator.csproj
Labels: not-notes-worthy

#8834 [dotnet] Rebuild nugets and global.json when we switch branches or commit something, or change any of the project files involved in package creation.
  dotnet/Makefile
  tests/dotnet/Makefile
Labels: not-notes-worthy

#8674 [d16-6] [ObjCRuntime] Use _NSConcreteStackBlock instead of _NSStackBlock.
  src/ObjCRuntime/Blocks.cs
Labels: note-highlight, requires-approval-before-merge

#8833 [msbuild] Remove version comparisons that will always be true by now.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileEntitlementsTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
Labels: not-notes-worthy

#8831 [msbuild] Rename a few CodeSign* variables to Codesign* variables to make Xamarin.iOS and Xamarin.Mac code identical.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
Labels: not-notes-worthy

#8842 [mmp] Update generated code for `main.c`
  tools/mmp/driver.cs
Labels: not-notes-worthy

#8847 [tests] Don't add the build output to the assert message our mmp tests, it makes html reports hard to read.
  tests/mmptest/src/CodeStrippingTests.cs
  tests/mmptest/src/MMPTest.cs
Labels: not-notes-worthy

#8846 [msbuild/tests] Set MSBUILD_EXE_PATH when running unit tests from within VS. Fixes #5042.
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/AssemblySetup.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/FrameworkListTest.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/ProjectReference.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/EnsureEmptyTasks.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/IBToolTaskTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
  tests/common/Configuration.cs
Labels: not-notes-worthy

#8845 [xharness] Always use nuget to restore nugets, and always use xibuild to run nuget.
  tests/xharness/Jenkins/TestTasks/BuildProjectTask.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/BuildProject.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/MSBuild.cs
Labels: not-notes-worthy

#8832 [msbuild] Unify MtouchDebug and MmpDebug into _Debug.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8830 [dotnet] Ship libxamarin.dylib and friends.
  Make.config
  dotnet/Makefile
  dotnet/package/common.csproj
  runtime/Makefile
  tools/dotnet-linker/Makefile
Labels: not-notes-worthy

#8853 [runtime] Update launcher to use `strndup`
  runtime/launcher.m
Labels: not-notes-worthy

#8855 [runtime] Have launcher use https-based URL if mono is missing
  runtime/launcher.m
Labels: not-notes-worthy

#8856 [tests] Use Cache.CreateTemporaryDirectory to create temporary directories for the msbuild-mac tests.
  tests/msbuild-mac/msbuild-mac.csproj
  tests/msbuild-mac/src/MSBuild-Smoke.cs
Labels: not-notes-worthy

#8852 [xharness] Don't ignore a failure to restore nugets.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/MSBuild.cs
Labels: not-notes-worthy

#8851 Rename master to main.
  Make.versions
  README.md
  docs/website/binding_objc_libs.md
  docs/website/binding_types_reference_guide.md
  docs/website/generator-errors.md
  docs/website/mtouch-errors.md
  docs/website/optimizations.md
  docs/website/xamarin-analysis-doc-tool/xamarin-analysis-doc.cs
  dotnet/VERSIONS.md
  jenkins/custom-labels.txt
  mk/xamarin.mk
  src/README.md
  tests/README.md
  tests/sampletester/BaseTester.cs
  tests/sampletester/GitHub.cs
  tests/sampletester/README.md
  tests/sampletester/SampleTester.cs
  tests/sampletester/Samples.cs
  tests/xharness/Jenkins/TestSelector.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/common/TestRunner/Core/TcpTextWriter.cs
  tests/xtro-sharpie/iOS-CoreGraphics.ignore
  tools/devops/azure-pipelines.yml
  tools/devops/build-samples.yml
  tools/devops/device-tests.yml
  tools/devops/push-performance-data.sh
Labels: build-package, run-internal-tests, run-sample-tests

#8864 [xharness] Make ConsoleLog thread-safe. Fixes #8569.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Logging/ConsoleLog.cs
Labels: not-notes-worthy

#8854 [msbuild] Share the DeviceSpecificIntermediateOutputPath property.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8865 [runtime] Replace custom string concatenation inside `mono-runtime.m.t4`
  runtime/mono-runtime.m.t4
Labels: not-notes-worthy

#8859 [runtime] Simplify string code inside launcher by using ObjC
  runtime/launcher.m
Labels: not-notes-worthy

#8872 [Devtools] Do not try to install tools via brew if present.
  tools/devops/device-tests-provisioning.csx.in
Labels: not-notes-worthy, skip-all-tests

#8874 [DevOps] Move away from a testing branch and use main.
  tools/devops/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8878 [d16-7][Devops] Move to main rather than using a testing branch.
  tools/devops/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8877 [d16-6][Devops] Move to main rather than using a testing branch.
  tools/devops/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8863 [monotouch-test] Check for Metal compatibility for all platforms before creating indirect command buffers. Fixes #xamarin/maccore@2235.
  tests/monotouch-test/Metal/MTLDeviceTests.cs
Labels: not-notes-worthy, run-internal-tests, trigger-device-tests

#8873 [AppKit] NSTextView allows passing nil to PasteAsPlainText and PasteAsRichText.
  src/appkit.cs
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: not-notes-worthy

#8866 Bump maccore.
  mk/xamarin.mk
Labels: build-package, not-notes-worthy, run-sample-tests, skip-public-jenkins

#8848 Unify code for executing processes.
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
  src/bgen/bgen.csproj
  src/btouch.cs
  src/generator.csproj
  tests/cecil-tests/cecil-tests.csproj
  tests/common/ExecutionHelper.cs
  tests/common/mac/ProjectTestHelpers.cs
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/mmp-aot-tests/aot.cs
  tests/mmptest/mmptest.csproj
  tests/mmptest/src/MMPTest.cs
  tests/mmptest/src/NativeReferencesTests.cs
  tests/mmptest/src/NetStandardTests.cs
  tests/mmptest/src/WarningTests.cs
  tests/msbuild-mac/msbuild-mac.csproj
  tests/msbuild-mac/src/MSBuild-Smoke.cs
  tests/mtouch/mtouch.csproj
  tests/sampletester/sampletester.csproj
  tests/xammac_tests/xammac_tests.csproj
  tools/common/Driver.cs
  tools/common/Driver.execution.cs
  tools/common/Execution.cs
  tools/mmp/aot.cs
  tools/mmp/driver.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Assembly.mtouch.cs
  tools/mtouch/BuildTasks.mtouch.cs
  tools/mtouch/mtouch.cs
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy, run-internal-tests, trigger-device-tests

#8879 [runtime] Remove strlen and memcpy usage from runtime/xamarin-support.m
  runtime/xamarin-support.m
Labels: not-notes-worthy

#8876 [msbuild] Split out min version argument calculation from MetalTask.
  msbuild/Xamarin.MacDev.Tasks.Core/PlatformFramework.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MetalTaskBase.cs
Labels: not-notes-worthy

#8875 [msbuild] Unify the CompileAppManifest target.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/CompileAppManifest.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/CompileAppManifest.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
Labels: not-notes-worthy

#8886 [monotouch-test] Lower indirect command buffer availability.
  tests/monotouch-test/Metal/MTLDeviceTests.cs
Labels: not-notes-worthy

#8894 [Devops] Fix typo in beta device pipeline.
  tools/devops/device-tests/cambridge-ios-beta-device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8895 [Devops] Use correct variables template on ddfun tvos pipeline.
  tools/devops/device-tests/ddfun-tvos-device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8896 [DevOps] Update contexts to be more clear.
  tools/devops/device-tests/cambridge-ios-32b-device-tests.yml
  tools/devops/device-tests/cambridge-ios-beta-device-tests.yml
  tools/devops/device-tests/cambridge-ios-device-tests.yml
  tools/devops/device-tests/cambridge-tvos-beta-device-tests.yml
  tools/devops/device-tests/cambridge-tvos-device-tests.yml
  tools/devops/device-tests/ddfun-ios-device-tests.yml
  tools/devops/device-tests/ddfun-tvos-device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8884 Bump maccore
  mk/xamarin.mk
Labels: not-notes-worthy, run-internal-tests, run-sample-tests

#8893 [runtime] Use `strnlen` instead of `strlen`
  runtime/monotouch-main.m
  runtime/runtime.m
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy

#8891 [runtime] Fix warning in launcher.m
  runtime/launcher.m
Labels: not-notes-worthy

#8890 [runtime] Remove internal memcpy p/invoke
  src/AudioToolbox/AudioConverter.cs
  src/AudioToolbox/AudioQueue.cs
  src/AudioToolbox/MusicTrack.cs
  src/CoreMidi/MidiServices.cs
  src/CoreMidi/MidiThruConnectionParams.cs
  src/ObjCRuntime/Runtime.cs
  tests/cecil-tests/Test.cs
  tests/xtro-sharpie/common-ObjCRuntime.ignore
Labels: not-notes-worthy

#8888 [msbuild] Make sure all the Base/Core tasks are abstract.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/ALToolUploadTaskBase.cs
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/ALToolValidateTaskBase.cs
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/EmbedProvisionProfileTaskBase.cs
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CollectFrameworksBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateInstallerPackageTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ALToolUploadTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ALToolValidateTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CollectAssetPacksTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CollectITunesSourceFilesTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CreateAssetPackTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/WriteAssetPackManifestTaskBase.cs
  tests/cecil-tests/Helper.cs
  tests/cecil-tests/TaskAssemblyTests.cs
Labels: not-notes-worthy

#8897 [Bump] Bump maccore to use the new yaml pipelines.
  mk/xamarin.mk
Labels: not-notes-worthy

#8887 [dotnet] Generate a main function, and use it to compile the main executable.
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileNativeCodeTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileNativeCode.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCode.cs
  tools/dotnet-linker/Compat.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
Labels: not-notes-worthy

#8912 [DevOps] Do not fail the tests is xamarin-storage cannot be reached.
  tools/devops/device-tests/scripts/GitHub.psm1
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8910 [xharness] Set the working directory to the project directory when building projects.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/MSBuild.cs
Labels: not-notes-worthy

#8904 [configure] Add an option to enable/disable install-source.
  Make.config
  configure
  jenkins/build.sh
  tools/Makefile
Labels: not-notes-worthy

#8903 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy, pr-change-not-shipping, run-internal-tests

#8915 [d16-6] [AppKit][Tests] Do not fail when we cannot create a NSPasteboard.
  tests/apitest/src/AppKit/NSPasteboard.cs
Labels: pr-change-not-shipping, requires-approval-before-merge

#8914 [d16-7] [AppKit][Tests] Do not fail when we cannot create a NSPasteboard.
  tests/apitest/src/AppKit/NSPasteboard.cs
Labels: pr-change-not-shipping

#8913 [d16-6] [sharpie] Bump version of sharpie and accommodate xtro to new output
  Make.config
  tests/xtro-sharpie/Makefile
  tests/xtro-sharpie/SimdCheck.cs
  tests/xtro-sharpie/xtro-sharpie.csproj
Labels: pr-change-not-shipping, requires-approval-before-merge

#8908 [dotnet] Make the generated main function work.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileNativeCodeTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
  tests/dotnet/MySingleView/AppDelegate.cs
  tests/dotnet/MySingleView/Info.plist
  tests/dotnet/MySingleView/MainStoryboard.storyboard
  tests/dotnet/MySingleView/MySingleViewViewController.cs
  tests/dotnet/MySingleView/MySingleViewViewController.designer.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
Labels: dotnet, not-notes-worthy

#8938 [CODEOWNERS] Add the rightful owners of the device tests.
  CODEOWNERS
Labels: not-notes-worthy, skip-all-tests

#8916 [DevOps] Allow to use vsdrops AND xamarin storage.
  tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
  tools/devops/device-tests/README.md
  tools/devops/device-tests/cambridge-ios-32b-device-tests.yml
  tools/devops/device-tests/cambridge-ios-beta-device-tests.yml
  tools/devops/device-tests/cambridge-ios-device-tests.yml
  tools/devops/device-tests/cambridge-tvos-beta-device-tests.yml
  tools/devops/device-tests/cambridge-tvos-device-tests.yml
  tools/devops/device-tests/ddfun-ios-device-tests.yml
  tools/devops/device-tests/ddfun-tvos-device-tests.yml
  tools/devops/device-tests/scripts/GitHub.psm1
  tools/devops/device-tests/scripts/System.psm1
  tools/devops/device-tests/templates/cambridge-variables.yml
  tools/devops/device-tests/templates/common-variables.yml
  tools/devops/device-tests/templates/ddfun-variables.yml
  tools/devops/device-tests/templates/device-tests-stage.yml
  tools/devops/device-tests/templates/device-tests.yml
  tools/devops/device-tests/templates/publish-html.yml
Labels: not-notes-worthy

#8946 [DevOps] Using netcat over ssh to check if port is open.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8945 [DevOps] Clean summary message.
  tools/devops/device-tests/scripts/GitHub.Tests.ps1
  tools/devops/device-tests/scripts/GitHub.psm1
Labels: not-notes-worthy, skip-all-tests

#8909 [xharness] Automatically detect and use .NET 5
  tests/Makefile
  tests/xharness/Harness.cs
  tests/xharness/IHarness.cs
  tests/xharness/Jenkins/TestTasks/BuildProjectTask.cs
  tests/xharness/Jenkins/TestTasks/DotNetBuildTask.cs
  tests/xharness/Jenkins/TestTasks/DotNetTestTask.cs
  tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/BuildProject.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Tasks/MSBuild.cs
  tests/xharness/TestTasks/DotNetBuild.cs
Labels: dotnet, not-notes-worthy, run-internal-tests

#8951 [DevOps] Return a success even when Clear-HD has issues.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8952 [DevOps] Fix broken link.
  tools/devops/device-tests/scripts/GitHub.psm1
Labels: not-notes-worthy, skip-all-tests

#8953 [DevOps] Add the agent name to find the provisioning issues faster.
  tools/devops/device-tests/scripts/GitHub.psm1
Labels: not-notes-worthy, skip-all-tests

#8950 [xharness] Don't access the simulator tasks if we failed to created them.
  tests/xharness/Jenkins/Jenkins.cs
Labels: not-notes-worthy

#8956 [mlaunch] Add a commit message with a pointer to the maccore hash that GitHub renders as a link.
  tools/mlaunch/Makefile
Labels: not-notes-worthy

#8959 [DevOps] fix quotes.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy, skip-all-tests

#8963 [DevOp] Allow $XamarinStorage to be empty.
  tools/devops/device-tests/scripts/GitHub.psm1
Labels: not-notes-worthy, skip-all-tests

#8962 [xcode12] Merge d16-7 into xcode12
  src/AVFoundation/AVAudioChannelLayout.cs
  src/AVFoundation/AVAudioFormat.cs
  src/Makefile
  src/generate-errors.csharp
Labels: not-notes-worthy

#8961 [xharness] Disable diagnostics when killing Xcode processes.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Execution/ProcessManager.cs
Labels: not-notes-worthy

#8977 [DevOps] Explicitly allow empty xamarin storage paths.
  tools/devops/device-tests/scripts/GitHub.psm1
Labels: not-notes-worthy, skip-all-tests
