Repository dotnet/macios, pull requests merged in 2020-09, with the labels that each got.

#9558 [d16-8] Bump maccore to get provisioning changes
  mk/xamarin.mk
Labels: not-notes-worthy

#9559 [xcode12] Bump maccore to get provisioning changes
  mk/xamarin.mk
Labels: not-notes-worthy

#9560 [d16-7-xcode11.7] Bump maccore to get provisioning changes
  mk/xamarin.mk
Labels: not-notes-worthy

#9555 [Enhancement] Fix typo in AVFoundation
  src/avfoundation.cs
Labels: not-notes-worthy

#9557 [d16-7] Bump maccore to get provisioning changes
  mk/xamarin.mk
Labels: not-notes-worthy, pr-change-not-shipping, requires-approval-before-merge

#9564 [d16-7] [Enhancement] Fix typo in AVFoundation
  src/avfoundation.cs
Labels: requires-approval-before-merge

#9547 [jenkins] Clean up old simulators and Xcodes before every build.
  jenkins/Jenkinsfile
  jenkins/clean-jenkins-bots.sh
Labels: not-notes-worthy, skip-all-tests

#9567 [tests] Add test case for issue #9566.
  tests/linker/ios/link all/InterfacesTest.cs
Labels: not-notes-worthy

#9570 [tests] Ignore/fix/adjust several link all tests to make them pass in .NET.
  tests/linker/CommonLinkAllTest.cs
  tests/linker/ios/link all/AttributeTest.cs
  tests/linker/ios/link all/CalendarTest.cs
  tests/linker/ios/link all/ClassLayoutTest.cs
  tests/linker/ios/link all/DataContractTest.cs
  tests/linker/ios/link all/InterfacesTest.cs
  tests/linker/ios/link all/PreserveTest.cs
  tests/linker/ios/link all/XmlSerializationTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#9572 [msbuild] Parse the --optimize extra bundler arguments in ParseBundlerArgumentsTask.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
Labels: not-notes-worthy

#9561 [d16-7] Rename master to main.
  README.md
  docs/website/binding_objc_libs.md
  docs/website/binding_types_reference_guide.md
  docs/website/generator-errors.md
  docs/website/mtouch-errors.md
  docs/website/optimizations.md
  docs/website/xamarin-analysis-doc-tool/xamarin-analysis-doc.cs
  src/README.md
  tests/README.md
  tests/sampletester/BaseTester.cs
  tests/sampletester/GitHub.cs
  tests/sampletester/README.md
  tests/sampletester/SampleTester.cs
  tests/sampletester/Samples.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/common/TestRunner/Core/TcpTextWriter.cs
  tests/xtro-sharpie/iOS-CoreGraphics.ignore
  tools/devops/azure-pipelines.yml
  tools/devops/build-samples.yml
  tools/devops/push-performance-data.sh
Labels: not-notes-worthy, pr-change-not-shipping, requires-approval-before-merge, run-internal-tests, run-sample-tests

#9576 [coredata] Fix breaking change for NSCoreDataCoreSpotlightDelegate
  src/CoreData/Obsolete.cs
Labels: not-notes-worthy

#9586 [CarPlay] Remove warnings when building the intermediate dlls.
  src/carplay.cs
Labels: not-notes-worthy

#9587 [ARKit] Remove warning from intermediate compilation.
  src/arkit.cs
Labels: not-notes-worthy

#9588 [UIKit] Remove warning from intermediate compilation.
  src/uikit.cs
Labels: not-notes-worthy

#9575 [tests] Disable some of linkall's SealerTest in .NET/Release until we can implement them.
  tests/linker/ios/link all/SealerTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#9571 [dotnet] Define and implement a 'framework' or 'sdk' assembly as an assembly that comes from the .NET BCL NuGet.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/common/Assembly.cs
  tools/dotnet-linker/Compat.cs
  tools/dotnet-linker/LinkerConfiguration.cs
Labels: not-notes-worthy, run-dotnet-tests

#9593 [ObjCRuntime] Improve a few error/log messages to show the class name instead of the class handle.
  src/ObjCRuntime/Class.cs
Labels: not-notes-worthy

#9595 [tests] Prebuilt the Touch.Client projects when packaging the Xamarin.Mac tests.
  tests/package-mac-tests.sh
Labels: not-notes-worthy

#9594 [dotnet] Make the linker always process debug symbols, and remove debugging support if we're building a release build.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
Labels: not-notes-worthy, run-dotnet-tests

#9545 nunit2 format for supported in MSBuild Tests Workaround
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
Labels: run-msbuild-tests

#9585 [NetworkExtensions] Update framework to Xcode12 beta 6.
  src/NetworkExtension/NEEnums.cs
  src/networkextension.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/iOS-NetworkExtension.todo
  tests/xtro-sharpie/macOS-NetworkExtension.todo
  tests/xtro-sharpie/watchOS-NetworkExtension.ignore
Labels: note-highlight

#9596 [tools] Refactor the Optimizations class to have no conditionally compiled code.
  tests/mmptest/src/MMPTest.cs
  tests/mtouch/MTouch.cs
  tools/common/ApplePlatform.cs
  tools/common/Application.cs
  tools/common/Driver.cs
  tools/common/Optimizations.cs
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy, run-dotnet-tests

#9601 [d16-7-xcode11.7] [tests] Disable currently broken System.Tests.DateTimeTests mono tests
  tests/bcl-test/common-monotouch_corlib_xunit-test.dll.ignore
  tests/bcl-test/macOS-xammac_net_4_5_corlib_xunit-test.dll.ignore
  tests/bcl-test/macOSModern-xammac_net_4_5_corlib_xunit-test.dll.ignore
Labels: not-notes-worthy, pr-change-not-shipping

#9598 [UIKit] Sprinkle NullAllowed on UIImage according to Apple's headers. Fixes #9597.
  src/uikit.cs
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/watchOS-UIKit.ignore
Labels: bug

#9600 [linker] Fix warnings on type references that still exists. Fix #8814
  tools/linker/ScanTypeReferenceStep.cs
Labels: bug

#9605 [tests] Add DYNAMIC_REGISTAR when we're using the dynamic registrar in the .NET version of monotouch-test.
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
Labels: not-notes-worthy, run-dotnet-tests

#9599 [dotnet] Pass the Optimize flags from the extra bundler arguments to the linker configuration.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/xharness/Harness.cs
  tools/dotnet-linker/LinkerConfiguration.cs
Labels: not-notes-worthy, run-dotnet-tests

#9606 [msbuild] Parse the --registrar extra bundler argument in ParseBundlerArgumentsTask.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
Labels: not-notes-worthy, run-dotnet-tests

#9610 [Foundation] Fix NSUrl's implicit Uri operators. Fixes #9607.
  src/Foundation/NSUrl.cs
  tests/monotouch-test/Foundation/UrlTest.cs
Labels: bug

#9608 [dotnet-linker] Add OptimizeGeneratedCodeSubStep into the pipeline.
  tests/xharness/Harness.cs
  tools/common/Application.cs
  tools/dotnet-linker/Compat.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/linker/CoreOptimizeGeneratedCode.cs
Labels: not-notes-worthy, run-dotnet-tests

#9609 [registrar] Make the registrar code non-conditional.
  src/ObjCRuntime/Registrar.cs
  tools/common/Application.cs
  tools/common/StaticRegistrar.cs
  tools/common/Target.cs
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/Target.mtouch.cs
Labels: not-notes-worthy, run-dotnet-tests

#9604 [mediaplayer] Fix MPMusicPlayerController NowPlayingItem on recent iOS versions
  src/ObjCRuntime/DynamicRegistrar.cs
  src/ObjCRuntime/Runtime.cs
  src/mediaplayer.cs
Labels: bug

#9616 [xharness] Add support for adding PropertyGroups if none are applicable when adding a property.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Labels: not-notes-worthy, run-dotnet-tests

#9619 [xcode12][mediaplayer] Fix MPMusicPlayerController NowPlayingItem on recent iOS versions
  src/ObjCRuntime/DynamicRegistrar.cs
  src/ObjCRuntime/Runtime.cs
  src/mediaplayer.cs
Labels: bug

#9615 [dotnet] Add support for the static registrar.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/common/Application.cs
  tools/common/Driver.cs
  tools/dotnet-linker/Compat.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/Steps/RegistrarStep.cs
Labels: not-notes-worthy, run-dotnet-tests

#9603 [AudioToolbox] Update API to xcode 12 beta 6.
  src/AudioToolbox/Enums.cs
  src/AudioUnit/AudioComponent.cs
  tests/monotouch-test/AudioUnit/AudioUnitTest.cs
  tests/xtro-sharpie/common-AudioToolbox.ignore
  tests/xtro-sharpie/iOS-AudioToolbox.todo
  tests/xtro-sharpie/macOS-AudioToolbox.todo
  tests/xtro-sharpie/tvOS-AudioToolbox.todo
Labels: note-highlight

#9569 [Metal] Update framework for xcode 12 beta 6.
  src/Metal/Defs.cs
  src/Metal/MTLBlitPassSampleBufferAttachmentDescriptorArray.cs
  src/Metal/MTLComputePassSampleBufferAttachmentDescriptorArray.cs
  src/Metal/MTLEnums.cs
  src/Metal/MTLIntersectionFunctionTable.cs
  src/Metal/MTLRenderPassSampleBufferAttachmentDescriptorArray.cs
  src/Metal/MTLResourceStatePassSampleBufferAttachmentDescriptorArray.cs
  src/frameworks.sources
  src/metal.cs
  tests/introspection/ApiSelectorTest.cs
  tests/monotouch-test/Metal/MTLBlitPassDescriptorTest.cs
  tests/monotouch-test/Metal/MTLBlitPassSampleBufferAttachmentDescriptorArrayTest.cs
  tests/monotouch-test/Metal/MTLBlitPassSampleBufferAttachmentDescriptorTest.cs
  tests/monotouch-test/Metal/MTLComputePassDescriptorTest.cs
  tests/monotouch-test/Metal/MTLComputePassSampleBufferAttachmentDescriptorArrayTest.cs
  tests/monotouch-test/Metal/MTLComputePassSampleBufferAttachmentDescriptorTest.cs
  tests/monotouch-test/Metal/MTLCounterSampleBufferDescriptorTest.cs
  tests/monotouch-test/Metal/MTLIntersectionFunctionTableDescriptorTest.cs
  tests/monotouch-test/Metal/MTLIntersectionFunctionTableTests.cs
  tests/monotouch-test/Metal/MTLLinkedFunctionsTest.cs
  tests/monotouch-test/Metal/MTLRenderPassSampleBufferAttachmentDescriptorArrayTest.cs
  tests/monotouch-test/Metal/MTLRenderPassSampleBufferAttachmentDescriptorTest.cs
  tests/monotouch-test/Metal/MTLResourceStatePassDescriptorTest.cs
  tests/monotouch-test/Metal/MTLResourceStatePassSampleBufferAttachmentDescriptorArrayTest.cs
  tests/monotouch-test/Metal/MTLResourceStatePassSampleBufferAttachmentDescriptorTest.cs
  tests/monotouch-test/Metal/MTLTileRenderPipelineDescriptorTest.cs
  tests/monotouch-test/Metal/MTLVisibleFunctionTableDescriptorTest.cs
  tests/xtro-sharpie/iOS-Metal.ignore
  tests/xtro-sharpie/iOS-Metal.todo
  tests/xtro-sharpie/macOS-Metal.ignore
  tests/xtro-sharpie/macOS-Metal.todo
  tests/xtro-sharpie/tvOS-Metal.ignore
  tests/xtro-sharpie/tvOS-Metal.todo
Labels: note-highlight

#9565 [Bug] AVAudioSourceNodeRenderHandler delegate is incorrectly bound
  src/AVFoundation/AVCompat.cs
  src/avfoundation.cs
Labels: bug, iOS, macOS, note-highlight

#9627 Improve the layout of the table of old packages in the README.
  README.md
Labels: not-notes-worthy, skip-public-jenkins

#9629 [xharness] The linkall tests are green for .NET/Release now.
  tests/xharness/Harness.cs
Labels: not-notes-worthy, run-dotnet-tests

#9632 [xcode12] Introspection-based fixes for Big Sur
  src/Foundation/Compat.cs
  src/Foundation/NSCompat.cs
  src/classkit.cs
  src/foundation.cs
  src/gamekit.cs
  src/passkit.cs
  src/pencilkit.cs
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/CoreSelectorTest.cs
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/xtro-sharpie/common-GameKit.ignore
  tests/xtro-sharpie/iOS-GameKit.ignore
  tests/xtro-sharpie/tvOS-GameKit.ignore
  tests/xtro-sharpie/watchOS-GameKit.ignore
Labels: not-notes-worthy

#9636 [tests] Rework a few tests to not throw exceptions in a background thread.
  tests/monotouch-test/AudioUnit/AUParameterNodeTest.cs
  tests/monotouch-test/CoreAnimation/LayerTest.cs
Labels: not-notes-worthy

#9621 [Bug] Fix inconsistent use of punctuation in argument descriptions
  tools/common/Driver.cs
Labels: bug, not-notes-worthy

#9638 [xcode12][intro] Fix running introspection on old macOS versions
  src/intents.cs
  tests/monotouch-test/NaturalLanguage/NLTaggerTest.cs
Labels: not-notes-worthy, test-only-issue

#9640 [xcode12][tests] Fix typos
  src/accounts.cs
  src/appkit.cs
  src/gamecontroller.cs
  src/mediaplayer.cs
  tests/introspection/ApiTypoTest.cs
Labels: not-notes-worthy

#9624 [d16-8] [Bug] AVAudioSourceNodeRenderHandler delegate is incorrectly bound
  src/AVFoundation/AVCompat.cs
  src/avfoundation.cs
Labels: note-highlight

#9635 [jenkins] Fix version logic with macOS 11.0.
  jenkins/Jenkinsfile
  jenkins/list-macos-platforms.csharp
Labels: not-notes-worthy, run-internal-tests

#9639 [msbuild] Parse the --xml extra bundler argument in ParseBundlerArgumentsTask.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
Labels: not-notes-worthy

#9644 [xcode12] Initial bump for Xcode 12 GM
  Make.config
  Versions-mac.plist.in
  mk/xamarin.mk
  msbuild/tests/Xamarin.iOS.Tasks.Tests/FrameworkListTest.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/CoreMLCompiler.cs
  src/AVFoundation/Enums.cs
  src/Metal/MTLEnums.cs
  src/gamecontroller.cs
  src/gamekit.cs
  src/healthkit.cs
  src/intents.cs
  src/metal.cs
  src/watchkit.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/iOS/iOSApiCtorInitTest.cs
  tests/xtro-sharpie/Makefile
  tests/xtro-sharpie/common-CoreFoundation.ignore
  tests/xtro-sharpie/common-CoreMIDI.ignore
  tests/xtro-sharpie/common-Metal.ignore
  tests/xtro-sharpie/common-PDFKit.ignore
  tests/xtro-sharpie/iOS-Metal.ignore
  tests/xtro-sharpie/iOS-OSLog.ignore
  tests/xtro-sharpie/macOS-CoreFoundation.ignore
  tests/xtro-sharpie/macOS-CoreMIDI.ignore
  tests/xtro-sharpie/macOS-Metal.ignore
  tests/xtro-sharpie/macOS-PDFKit.ignore
  tests/xtro-sharpie/tvOS-OSLog.ignore
  tests/xtro-sharpie/watchOS-Intents.ignore
  tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
  tools/common/Frameworks.cs
  tools/mlaunch/Makefile
Labels: note-highlight

#9653 [Metal] Add missing GC.KeeAlive.
  src/Metal/MTLIntersectionFunctionTable.cs
Labels: not-notes-worthy

#9641 CGRect, CGPoint, CGSize: add tuple deconstruction methods
  src/NativeTypes/Drawing.tt
Labels: enhancement

#9647 [mtouch] Refactor how we detect and avoid broken frameworks when building for the simulator.
  tests/mtouch/MTouch.cs
  tools/common/CompilerFlags.cs
  tools/common/Frameworks.cs
  tools/common/Target.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#9656 [Tests]Fixed broken tests.sln.
  tests/tests.sln
Labels: not-notes-worthy

#9655 [Cecil] Try to fix tests by stating the version in the console runner.
  tests/cecil-tests/packages.config
Labels: not-notes-worthy, run-cecil-tests

#9661 [monotouch-test] Rework CBCentralManagerTest to handle not having permissions.
  tests/monotouch-test/CoreBluetooth/CentralManagerTest.cs
Labels: not-notes-worthy

#9660 [monotouch-test] Don't assert any specific value for the ReusedConnection value in UrlSessionTaskTransactionMetricsTest. Fixes #xamarin/maccore@2281.
  tests/monotouch-test/Foundation/UrlSessionTaskTransactionMetricsTest.cs
Labels: not-notes-worthy, run-internal-tests, skip-public-jenkins

#9659 [xharness] Skip the 'dont link / AssemblyBuildTarget: SDK framework (release)' variation for tvOS. Fixes #xamarin/maccore@2282.
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy, run-internal-tests, skip-public-jenkins

#9620 [SBApplication][Bug] SBApplication.FromBundleIdentifier<T> should return null when bundle ID is unknown
  src/ScriptingBridge/SBApplication.cs
  src/scriptingbridge.cs
  tests/apitest/apitest.csproj
  tests/apitest/src/ScriptingBridge/SBApplicationTest.cs
  tests/xtro-sharpie/macOS-ScriptingBridge.ignore
Labels: bug, macOS, note-highlight

#9666 Bump to .NET 5.0.100-rc.1.20426.3.
  Make.config
  dotnet/generate-target-platforms.csharp
Labels: not-notes-worthy, run-dotnet-tests

#9662 [msbuild/dotnet] Execute bgen using dotnet from the MSBuild tasks when in .NET mode.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  src/bgen/runtimeconfig.template.json
Labels: not-notes-worthy, run-dotnet-tests

#9658 [jenkins] Don't try to run the packaged Xamarin.Mac tests if none were built.
  jenkins/Jenkinsfile
Labels: not-notes-worthy, run-internal-tests

#9637 [src] Build the .NET version of our product assemblies using a .NET 5 BCL.
  .gitignore
  Make.config
  Makefile
  NuGet.config
  builds/Makefile
  dotnet/Makefile
  src/Makefile
  src/Makefile.generator
  src/bgen/bgen.csproj
  src/bgen/bgen.dotnet
  tests/.gitignore
  tests/bgen/bgen-tests.csproj
  tests/dotnet/Makefile
  tests/xharness/Jenkins/TestTasks/DotNetTestTask.cs
  tools/mmp/Makefile
  tools/mtouch/Makefile
Labels: not-notes-worthy, run-dotnet-tests

#9675 [dotnet-linker] Set the dynamic registration mode at runtime.
  tools/dotnet-linker/Steps/GenerateMainStep.cs
Labels: not-notes-worthy, run-dotnet-tests

#9677 [tools] Simplify code a little bit by making DerivedLinkContext.StaticRegistrar a fetch property instead of a push property
  tools/common/DerivedLinkContext.cs
  tools/mmp/Tuning.mmp.cs
  tools/mtouch/Tuning.mtouch.cs
Labels: not-notes-worthy, run-dotnet-tests

#9676 [dotnet] Tell the linker about any xml descriptors we might have.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
Labels: not-notes-worthy, run-dotnet-tests

#9665 Bump to Xcode 12.2 beta 1.
  Make.config
  Make.versions
  Versions-ios.plist.in
  Versions-mac.plist.in
  src/gamecontroller.cs
  tests/common/TestRuntime.cs
  tests/introspection/iOS/iOSApiFieldTest.cs
  tests/monotouch-test/Security/TrustTest.cs
  tests/xharness/Jenkins/Jenkins.cs
  tests/xtro-sharpie/common-MLCompute.ignore
  tests/xtro-sharpie/iOS-CarPlay.ignore
  tests/xtro-sharpie/iOS-CoreGraphics.todo
  tests/xtro-sharpie/iOS-HealthKit.ignore
  tests/xtro-sharpie/iOS-HealthKit.todo
  tests/xtro-sharpie/iOS-ImageIO.todo
  tests/xtro-sharpie/iOS-MLCompute.todo
  tests/xtro-sharpie/macOS-CoreFoundation.todo
  tests/xtro-sharpie/macOS-CoreGraphics.todo
  tests/xtro-sharpie/macOS-FileProvider.todo
  tests/xtro-sharpie/macOS-Foundation.ignore
  tests/xtro-sharpie/macOS-Foundation.todo
  tests/xtro-sharpie/macOS-ImageIO.todo
  tests/xtro-sharpie/macOS-MLCompute.todo
  tests/xtro-sharpie/macOS-OSLog.ignore
  tests/xtro-sharpie/macOS-Security.todo
  tests/xtro-sharpie/tvOS-CoreGraphics.todo
  tests/xtro-sharpie/tvOS-ImageIO.todo
  tests/xtro-sharpie/tvOS-MLCompute.todo
  tests/xtro-sharpie/watchOS-CoreGraphics.todo
  tests/xtro-sharpie/watchOS-HealthKit.ignore
  tests/xtro-sharpie/watchOS-HealthKit.todo
  tests/xtro-sharpie/watchOS-ImageIO.todo
  tests/xtro-sharpie/watchOS-Intents.ignore
Labels: not-notes-worthy

#9684 [d16-8] Merge xcode12 into d16-8.
  jenkins/Jenkinsfile
Labels: not-notes-worthy

#9688 [dotnet] Mark our platform assemblies as linkable.
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
Labels: not-notes-worthy, run-dotnet-tests

#9689 [msbuild] Don't include Execution.cs in the test project.
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
Labels: not-notes-worthy

#9694 [dotnet] Use xcrun to execute install_name_tool.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#9693 [tests] Make the .NET bgen tests actually reference the .NET BCL.
  tests/Makefile
  tests/cecil-tests/cecil-tests.csproj
  tests/common/Configuration.cs
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/generator/BGenTests.cs
  tests/generator/BGenTool.cs
  tests/generator/ErrorTests.cs
  tests/generator/bug17232.cs
  tests/generator/generator-tests.csproj
  tests/msbuild-mac/msbuild-mac.csproj
  tests/mtouch/mtouch.csproj
  tests/sampletester/sampletester.csproj
  tests/xammac_tests/xammac_tests.csproj
  tools/common/TargetFramework.cs
Labels: not-notes-worthy, run-dotnet-tests

#9699 [d16-8-xm] [jenkins] Don't try to run the packaged Xamarin.Mac tests if none were built.
  jenkins/Jenkinsfile
Labels: not-notes-worthy, pr-change-not-shipping

#9685 [dotnet-linker] Make sure to preserve block-related generated code. Fixes #9562.
  src/bgen/bgen.csproj
  src/generator.cs
  tests/linker/CommonLinkAllTest.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/ConfigurationAwareSubStep.cs
  tools/dotnet-linker/Steps/PreserveBlockCodeSubStep.cs
Labels: not-notes-worthy, run-dotnet-tests

#9702 [xharness] Fix typo in test case creating two identical test cases.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/XmlResultParserTests.cs
Labels: not-notes-worthy

#9703 [xharness] Use XmlReaderSettings to ignore stuff we don't care about when parsing xml.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/XmlResultParser.cs
Labels: not-notes-worthy

#9704 [xharness] Fix rendering human-readable results for parameterized tests. Fixes #9400.
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/NUnitV3SampleParameterizedFailure.xml
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/XmlResultParserTests.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/IResultParser.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/XmlResultParser.cs
Labels: not-notes-worthy

#9705 [tools] Remove unnecessary conditional code
  tools/common/Application.cs
  tools/common/Assembly.cs
  tools/common/Target.cs
Labels: not-notes-worthy, run-dotnet-tests

#9708 [msbuild] Share the _*CompileInterfaceDefinitions targets between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#9710 [README] Add stable d16-7 version with Xcode 12 support
  README.md
Labels: skip-all-tests, skip-public-tests

#9623 [Network] Partial bindings of Network for Xcode 12 beta 6.
  src/Network/NWConnectionGroup.cs
  src/Network/NWMulticastGroup.cs
  src/frameworks.sources
  tests/monotouch-test/Entitlements.plist
  tests/monotouch-test/Network/NWConnectionGroupTest.cs
  tests/monotouch-test/Network/NWMulticastGroupTest.cs
  tests/xtro-sharpie/common-Network.ignore
  tests/xtro-sharpie/iOS-Network.todo
  tests/xtro-sharpie/macOS-Network.todo
  tests/xtro-sharpie/tvOS-Network.todo
  tests/xtro-sharpie/watchOS-Network.todo
Labels: note-highlight

#9709 [msbuild] Use the ParseBundlerArguments task to parse mmp's --custom_bundle_name argument.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
Labels: not-notes-worthy

#9706 [msbuild] Port the test projects to .NET, and add a test case that compares the built .app
  msbuild/tests/AppWithExtraArgumentThatOverrides/AppWithExtraArgumentThatOverrides.dotnet.csproj
  msbuild/tests/Bug60536/Bug60536.dotnet.csproj
  msbuild/tests/My Spaced App/My Spaced App.dotnet.csproj
  msbuild/tests/MyActionExtension/MyActionExtension.dotnet.csproj
  msbuild/tests/MyAppWithPackageReference/MyAppWithPackageReference.dotnet.csproj
  msbuild/tests/MyCoreMLApp/MyCoreMLApp.dotnet.csproj
  msbuild/tests/MyDocumentPickerExtension/MyDocumentPickerExtension.dotnet.csproj
  msbuild/tests/MyExtensionWithPackageReference/MyExtensionWithPackageReference.dotnet.csproj
  msbuild/tests/MyIBToolLinkTest/MyIBToolLinkTest.dotnet.csproj
  msbuild/tests/MyKeyboardExtension/MyKeyboardExtension.dotnet.csproj
  msbuild/tests/MyLinkedAssets/MyLinkedAssets.dotnet.csproj
  msbuild/tests/MyMasterDetailApp/MyMasterDetailApp.dotnet.csproj
  msbuild/tests/MyMetalGame/MyMetalGame.dotnet.csproj
  msbuild/tests/MyOpenGLApp/MyOpenGLApp.dotnet.csproj
  msbuild/tests/MyPhotoEditingExtension/MyPhotoEditingExtension.dotnet.csproj
  msbuild/tests/MyReleaseBuild/MyReleaseBuild.dotnet.csproj
  msbuild/tests/MyReleaseBuild/MyReleaseBuildLlvm.dotnet.csproj
  msbuild/tests/MySceneKitApp/MySceneKitApp.dotnet.csproj
  msbuild/tests/MyShareExtension/MyShareExtension.dotnet.csproj
  msbuild/tests/MySingleView/MyLibrary/MyLibrary.dotnet.csproj
  msbuild/tests/MySingleView/MySingleView.dotnet.csproj
  msbuild/tests/MySingleView/MySingleView.dotnet.sln
  msbuild/tests/MySpriteKitGame/MySpriteKitGame.dotnet.csproj
  msbuild/tests/MyTVApp/MyTVApp.dotnet.csproj
  msbuild/tests/MyTVMetalGame/MyTVMetalGame.dotnet.csproj
  msbuild/tests/MyTVServicesExtension/MyTVServicesExtension.dotnet.csproj
  msbuild/tests/MyTabbedApplication/MyTabbedApplication.dotnet.csproj
  msbuild/tests/MyTodayExtension/MyTodayExtension.dotnet.csproj
  msbuild/tests/MyWatch2Container/MyWatch2Container.dotnet.csproj
  msbuild/tests/MyWatchApp2/MyWatchApp2.dotnet.csproj
  msbuild/tests/MyWatchKit2Extension/MyWatchKit2Extension.dotnet.csproj
  msbuild/tests/MyWatchKit2IntentsExtension/MyWatchKit2IntentsExtension.dotnet.csproj
  msbuild/tests/MyWebViewApp/MyWebViewApp.dotnet.csproj
  msbuild/tests/MyXamarinFormsApp/Directory.Build.dotnet.targets
  msbuild/tests/MyXamarinFormsApp/MyXamarinFormsApp.dotnet.csproj
  msbuild/tests/MyiOSAppWithBinding/MyiOSAppWithBinding.dotnet.csproj
  msbuild/tests/MyiOSFrameworkBinding/MyiOSFrameworkBinding.dotnet.csproj
  msbuild/tests/Xamarin.iOS.Tasks.Tests/DotnetTest.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/ProjectTest.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TestHelpers/TestBase.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/Xamarin.iOS.Tasks.Tests.csproj
  tests/cecil-tests/cecil-tests.csproj
  tests/common/Configuration.cs
  tests/common/DotNet.cs
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/xammac_tests/xammac_tests.csproj
Labels: not-notes-worthy, run-bcl-tests, run-btouch-tests, run-cecil-tests, run-dotnet-tests, run-mac-binding-project-tests, run-mmp-tests, run-msbuild-tests, run-mtouch-tests

#9707 [dotnet-linker] Add a RemoveAttributesStep that will remove some of the attributes we don't need.
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/RemoveAttributesStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
Labels: not-notes-worthy, run-dotnet-tests

#9723 [msbuild] Fix setting the IsXcode8 variable.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs
Labels: not-notes-worthy

#9721 [msbuild] Pass -F <dir> -framework <framework> for user frameworks.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/DotnetTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#9722 [dotnet-linker] Add a CollectUnmarkedMembersStep that will keep linked away types around for the static registrar.
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/CollectUnmarkedMembers.cs
Labels: not-notes-worthy, run-dotnet-tests

#9718 [AVFoundation] Update bindings to Xcode 12.2 Beta 1
  src/AVFoundation/Enums.cs
Labels: note-highlight

#9729 [xharness] Only run xammac variations if macOS tests are included.
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#9728 [xharness] The dotnet version of introspection/iOS 10.3 works fine now.
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy, run-dotnet-tests

#9686 [tests][cecil] Check for absence of `[NoX]` (Unavailable) in platform assemblies. Fix #4835
  src/AVFoundation/AVTypes.cs
  src/AudioUnit/AudioComponent.cs
  src/CoreMidi/MidiServices.cs
  src/CoreVideo/CVImageBuffer.cs
  src/GameKit/GKCompat.cs
  src/HomeKit/HMHome.cs
  src/MapKit/MKFeatureDisplayPriority.cs
  src/Metal/Defs.cs
  tests/cecil-tests/Test.cs
  tests/cecil-tests/cecil-tests.csproj
Labels: not-notes-worthy

#9700 [tests][xtro] Check for deprecated p/invokes (C API)
  src/AddressBook/ABMultiValue.cs
  src/AudioUnit/AUGraph.cs
  src/AudioUnit/AudioComponent.cs
  src/AudioUnit/AudioUnit.cs
  src/CoreFoundation/CFStream.cs
  src/CoreFoundation/Dispatch.cs
  src/CoreGraphics/CGContext.cs
  src/CoreMedia/CMSync.cs
  src/CoreMidi/MidiServices.cs
  src/CoreText/CTFontManager.cs
  src/Security/Certificate.cs
  src/Security/SecProtocolMetadata.cs
  src/Security/SecSharedCredential.cs
  src/Security/Trust.cs
  src/SystemConfiguration/CaptiveNetwork.cs
  src/TVServices/TVEnums.cs
  tests/xtro-sharpie/DeprecatedCheck.cs
Labels: not-notes-worthy

#9732 [xharness] Disable iOS 32-bit simulator tests, they don't work on Xcode 12+. (Re)fixes #xamarin/maccore@2284.
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#9731 [msbuild] Merge the CodesignNativeLibraries task into the Codesign task.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CodesignNativeLibrariesTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/CodesignNativeLibraries.cs
Labels: skip-public-jenkins

#9733 [tests] Remove duplicated code to set the requirement environment variables for building locally.
  tests/common/Configuration.cs
  tests/common/ExecutionHelper.cs
  tests/common/mac/ProjectTestHelpers.cs
Labels: not-notes-worthy

#9734 [tests] Simplify ProjectTestHelpers.FindRootDirectory by re-using existing code.
  tests/common/mac/ProjectTestHelpers.cs
Labels: not-notes-worthy
