Repository dotnet/macios, pull requests merged in 2020-12, with the labels that each got.

#10166 [networkextension] Update to Xcode 12.3 beta 1
  src/networkextension.cs
  tests/xtro-sharpie/iOS-NetworkExtension.todo
  tests/xtro-sharpie/macOS-NetworkExtension.todo
Labels: enhancement

#10185 [dotnet] Avoid double registration of static registrar
  tools/common/Target.cs
Labels: community, dotnet

#10171 [src] Generate a define for each framework for every platform.
  opentk/Makefile.include
  src/CoreImage/CIContext.cs
  src/CoreVideo/CVOpenGLESTexture.cs
  src/CoreVideo/CVOpenGLESTextureCache.cs
  src/Makefile
  src/Makefile.generator
  src/OpenGLES/Makefile-1.0.include
  src/UIKit/UIVibrancyEffect.cs
  src/coreanimation.cs
  src/coreimage.cs
  src/foundation.cs
  src/generate-defines.csharp
Labels: not-notes-worthy

#10175 [bgen] Use ErrorHelper.Verbosity to store the verbosity to avoid storing it in multiple places with different values
  src/btouch.cs
  tools/common/Driver.execution.cs
Labels: not-notes-worthy

#10163 [Contacts] Update bindings to Xcode 12.3 Beta 1
  src/contacts.cs
  tests/xtro-sharpie/iOS-Contacts.todo
  tests/xtro-sharpie/macOS-Contacts.todo
  tests/xtro-sharpie/watchOS-Contacts.todo
Labels: note-highlight

#10164 [CoreImage] Update bindings to Xcode 12.3 Beta 1
  src/coreimage.cs
  tests/xtro-sharpie/iOS-CoreImage.todo
  tests/xtro-sharpie/macOS-CoreImage.todo
  tests/xtro-sharpie/tvOS-CoreImage.todo
Labels: note-highlight

#10186 [VSTS] Add whitesource bolt analysis in the governance tasks.
  tools/devops/automation/templates/governance-checks.yml
Labels: not-notes-worthy

#10187 Tags from labels using dedicated Azure DevOps token
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/scripts/VSTS.Tests.ps1
  tools/devops/automation/scripts/VSTS.psm1
  tools/devops/automation/templates/configure-build.yml
  tools/devops/automation/templates/device-tests.yml
  tools/devops/automation/templates/governance-checks.yml
  tools/devops/automation/templates/publish-html.yml
  tools/devops/automation/templates/upload-azure.yml
Labels: build-package, run-internal-tests, skip-external-tests

#10190 [VSTS] Fix merge that change the template to use for the azure upload.
  tools/devops/automation/templates/build-packages-stage.yml
Labels: not-notes-worthy

#10188 [VSTS] upload static analysis.
  tools/devops/automation/templates/governance-checks.yml
Labels: not-notes-worthy

#10193 [VSTS] If we fail dumping the env, continue.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy

#10192 [VSTS] Build API diff when requested.
  tools/devops/automation/templates/build-packages-stage.yml
  tools/devops/automation/templates/build-packages.yml
  tools/devops/automation/templates/configure-build.yml
Labels: not-notes-worthy

#10189 [msbuild] Unify the _GetCompileToNativeInputs target between iOS and Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-msbuild-tests

#10182 [dotnet] Prevent linking out code referenced by P/Invoke
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/GenerateReferencesStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Labels: community, dotnet

#10195 [scenekit] Add nullability to (generated and manual) bindings
  src/SceneKit/Constructors.cs
  src/SceneKit/Defs.cs
  src/SceneKit/SCNAnimatable.cs
  src/SceneKit/SCNCompat.cs
  src/SceneKit/SCNGeometry.cs
  src/SceneKit/SCNGeometrySource.cs
  src/SceneKit/SCNJavaScript.cs
  src/SceneKit/SCNMatrix4.cs
  src/SceneKit/SCNNode.cs
  src/SceneKit/SCNParticleSystem.cs
  src/SceneKit/SCNPhysicsShape.cs
  src/SceneKit/SCNPhysicsTest.cs
  src/SceneKit/SCNQuaternion.cs
  src/SceneKit/SCNRenderingOptions.cs
  src/SceneKit/SCNScene.cs
  src/SceneKit/SCNSceneLoadingOptions.cs
  src/SceneKit/SCNSceneRenderer.cs
  src/SceneKit/SCNSceneSource.cs
  src/SceneKit/SCNSkinner.cs
  src/SceneKit/SCNTechnique.cs
  src/SceneKit/SCNVector3.cs
  src/SceneKit/SCNVector4.cs
  src/scenekit.cs
  tests/monotouch-test/SceneKit/AvoidOccluderConstraintTest.cs
  tests/monotouch-test/SceneKit/MorpherTest.cs
  tests/xtro-sharpie/common-SceneKit.ignore
  tests/xtro-sharpie/iOS-SceneKit.ignore
  tests/xtro-sharpie/macOS-SceneKit.ignore
  tests/xtro-sharpie/tvOS-SceneKit.ignore
  tests/xtro-sharpie/watchOS-SceneKit.ignore
Labels: enhancement

#10197 [msbuild] Treat 'ResolvedCompileFileDefinitions' as a list of reference assemblies as well. Fixes #9266.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: bug, run-msbuild-tests

#10183 [tests] Remove the MM0143 test, it doesn't look like VSMac is going to fix the bug. Fixes #8939.
  tests/common/mac/ProjectTestHelpers.cs
  tests/mmptest/src/MMPTest.cs
Labels: not-notes-worthy

#10021 [docs] Clarify optional protocol support with class vs interface
  docs/website/binding_types_reference_guide.md
Labels: not-notes-worthy, skip-all-tests

#10205 [d16-8] [VSTS] Ensure that we have a reasonable timeout. Will unblock device tests.
  tools/devops/device-tests/templates/device-tests.yml
Labels: pr-change-not-shipping

#10204 [VSTS] Ensure that we have a reasonable timeout. Will unblock device tests.
  tools/devops/device-tests/templates/device-tests.yml
Labels: not-notes-worthy

#10203 [d16-8] [VSTS] If we fail dumping the env, continue.
  tools/devops/device-tests/templates/device-tests.yml
Labels: pr-change-not-shipping

#10201 [VSTS] Fix device tets to be triggered correctly.
  tools/devops/automation/templates/build-packages.yml
  tools/devops/automation/templates/device-tests-stage.yml
Labels: not-notes-worthy

#10198 [tests] Update test to cope with change in Xamarin.WatchOS.dll's location.
  tests/mtouch/SdkTest.cs
Labels: not-notes-worthy, run-mtouch-tests

#10207 [VSTS] Machines can give problems and the default image does have enough HDD.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build-packages-stage.yml
  tools/devops/automation/templates/device-tests-stage.yml
Labels: not-notes-worthy

#10129 [tests] Merge the msbuild-mac tests into the Xamarin.MacDev.Tests project.
  CODEOWNERS
  tests/bgen/bgen-tests.csproj
  tests/common/BinLog.cs
  tests/common/ExecutionHelper.cs
  tests/common/Tool.cs
  tests/common/mac/ProjectTestHelpers.cs
  tests/generator/generator-tests.csproj
  tests/mmptest/mmptest.csproj
  tests/mmptest/src/AOTTests.cs
  tests/mmptest/src/BindingProjectNoEmbeddingTests.cs
  tests/mmptest/src/BindingProjectTests.cs
  tests/mmptest/src/CodeStrippingTests.cs
  tests/mmptest/src/LinkerTests.cs
  tests/mmptest/src/MMPTest.cs
  tests/mmptest/src/NativeReferencesTests.cs
  tests/mmptest/src/PackageReferenceTests.cs
  tests/mmptest/src/TargetFrameworkMutateTests.cs
  tests/msbuild-mac/CustomBuildActions.targets
  tests/msbuild-mac/msbuild-mac.csproj
  tests/msbuild/Xamarin.MacDev.Tests/MSBuild-Smoke.cs
  tests/msbuild/Xamarin.MacDev.Tests/RoslynSmokeTests.cs
  tests/msbuild/Xamarin.MacDev.Tests/RuntimeTests.cs
  tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/BuildEngine.cs
  tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj
  tests/mtouch/mtouch.csproj
  tests/tests-mac.sln
  tests/xammac_tests/xammac_tests.csproj
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
  tests/xharness/Jenkins/TestSelector.cs
Labels: not-notes-worthy, run-msbuild-tests

#10208 [VSTS] Add branchname in the nugets.
  tools/devops/automation/templates/build-packages.yml
Labels: not-notes-worthy

#10194 [msbuild] Only execute DetectDebugNetworkConfigurationTask for debug builds
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectDebugNetworkConfigurationTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: enhancement

#10209 [src] Fix generation and usage of the <platform>-defines.rsp files for .NET assemblies.
  src/Makefile
Labels: not-notes-worthy

#10223 [coregraphics] Expose CGColor.CreateByMatchingToColorSpace
  src/CoreGraphics/CGColor.cs
  tests/monotouch-test/CoreGraphics/ColorTest.cs
Labels: enhancement

#10224 [imageio] Update for Xcode 12.3 beta 1
  src/imageio.cs
  tests/xtro-sharpie/iOS-ImageIO.todo
  tests/xtro-sharpie/macOS-ImageIO.todo
  tests/xtro-sharpie/tvOS-ImageIO.todo
  tests/xtro-sharpie/watchOS-ImageIO.todo
Labels: enhancement

#10225 [healthkit] Update for Xcode 12.3 beta 1
  src/healthkit.cs
  tests/xtro-sharpie/iOS-HealthKit.todo
  tests/xtro-sharpie/watchOS-HealthKit.todo
Labels: enhancement

#10228 [gamecontroller] Update for Xcode 12.3 beta 1
  src/gamecontroller.cs
  tests/introspection/ApiProtocolTest.cs
  tests/xtro-sharpie/iOS-GameController.todo
  tests/xtro-sharpie/macOS-GameController.todo
  tests/xtro-sharpie/tvOS-GameController.todo
Labels: enhancement

#10229 [adservices] New in Xcode 12.3 beta 1
  src/Constants.iOS.cs.in
  src/Constants.mac.cs.in
  src/adservices.cs
  src/frameworks.sources
  tests/xtro-sharpie/iOS-AdServices.todo
  tests/xtro-sharpie/macOS-AdServices.todo
  tools/common/Frameworks.cs
  tools/mtouch/Makefile
Labels: enhancement

#10196 [Xcode12.3] [watchOS] Add x86_64 simulator support (#10059)
  Make.config
  dotnet/package/Microsoft.watchOS.Runtime.watchos-x64/package.csproj
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  mk/mono.mk
  mk/rules.mk
  runtime/Makefile
  src/Makefile
  src/ObjCRuntime/Registrar.cs
  tests/bcl-test/watchOS-monotouch_Microsoft.CSharp_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_Mono.Runtime.Tests_test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Core_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Numerics_test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Numerics_xunit-test.dll.ignore
  tests/mtouch/MTouch.cs
  tests/test-libraries/Makefile
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/Managed.watchOS.App.csproj.in
  tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/Managed.watchOS.Extension.csproj.in
  tests/xharness/Targets/WatchOSTarget.cs
  tools/common/Application.cs
  tools/mtouch/Makefile
  tools/mtouch/mtouch.cs
Labels: note-highlight

#10234 [coremotion] Update for Xcode 12.3 beta 1
  src/coremotion.cs
  tests/xtro-sharpie/watchOS-CoreMotion.todo
Labels: enhancement

#10235 [tests] Ignore bcl-tests that causes a SIGFPE
  tests/bcl-test/watchOS-monotouch_Microsoft.CSharp_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_Mono.Runtime.Tests_test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Core_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Numerics_test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Numerics_xunit-test.dll.ignore
Labels: not-notes-worthy

#10238 [network] Update for Xcode 12.2 beta 2
  src/Network/NWPath.cs
  src/network.cs
  tests/monotouch-test/Network/NWPathTest.cs
  tests/xtro-sharpie/iOS-Network.todo
  tests/xtro-sharpie/macOS-Network.todo
  tests/xtro-sharpie/tvOS-Network.todo
  tests/xtro-sharpie/watchOS-Network.todo
Labels: enhancement

#10239 [tests] Re-enable ModelIO in Mac's introspection tests (fixed in 11.1 beta 2)
  tests/introspection/Mac/MacApiCtorInitTest.cs
Labels: not-notes-worthy

#10237 [gamekit] Add nullability to (generated and manual) bindings
  src/GameKit/GKCompat.cs
  src/GameKit/GKLocalPlayerListener.cs
  src/GameKit/GKScore.cs
  src/GameKit/GameKit.cs
  src/GameKit/GameKit2.cs
  src/gamekit.cs
  tests/xtro-sharpie/iOS-GameKit.ignore
  tests/xtro-sharpie/macOS-GameKit.ignore
  tests/xtro-sharpie/tvOS-GameKit.ignore
  tests/xtro-sharpie/watchOS-GameKit.ignore
Labels: not-notes-worthy

#10241 [corebluetooth] Add nullability to (generated and manual) bindings
  src/CoreBluetooth/AdvertisementDataOptions.cs
  src/CoreBluetooth/CBCompat.cs
  src/CoreBluetooth/CBManager.cs
  src/CoreBluetooth/CBPeer.cs
  src/CoreBluetooth/CBUUID.cs
  src/CoreBluetooth/CoreBluetooth.cs
  src/CoreBluetooth/Enums.cs
  src/CoreBluetooth/GuidWrapper.cs
  src/CoreBluetooth/PeripheralConnectionOptions.cs
  src/CoreBluetooth/PeripheralScanningOptions.cs
  src/corebluetooth.cs
  tests/xtro-sharpie/common-CoreBluetooth.ignore
  tests/xtro-sharpie/iOS-CoreBluetooth.ignore
  tests/xtro-sharpie/macOS-CoreBluetooth.ignore
  tests/xtro-sharpie/tvOS-CoreBluetooth.ignore
Labels: enhancement

#10220 [msbuild] Archive the user frameworks .dSYM when available
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
Labels: enhancement

#10242 [compare-commits] Fix building the previous commit for Xamarin.MacCatalyst. Fixes #10222.
  tools/compare-commits.sh
Labels: not-notes-worthy

#10243 [VSTS] Add a postfix to the artifacts and download accordingly
  tools/devops/automation/templates/build-packages-stage.yml
  tools/devops/automation/templates/build-packages.yml
  tools/devops/automation/templates/device-tests-stage.yml
  tools/devops/automation/templates/device-tests.yml
  tools/devops/automation/templates/download-artifacts.yml
  tools/devops/automation/templates/upload-vsdrops.yml
  tools/devops/automation/templates/upload-vsts-tests.yml
Labels: not-notes-worthy

#10240 [xcode12.3] Bump to Xcode 12.3 RC
  Make.config
  Make.versions
  src/HealthKit/Enums.cs
  src/UIKit/UIEnums.cs
  src/healthkit.cs
  src/networkextension.cs
  tests/xtro-sharpie/macOS-ContextualActionsClient.ignore
Labels: notes-mention

#10246 [VSTS] Clean template tree to make it more manageable.
  .gitignore
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/common/download-artifacts.yml
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/common/upload-vsdrops.yml
  tools/devops/automation/templates/common/upload-vsts-tests.yml
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/devices/stage.yml
  tools/devops/automation/templates/packages/build.yml
  tools/devops/automation/templates/packages/configure.yml
  tools/devops/automation/templates/packages/stage.yml
  tools/devops/automation/templates/packages/upload-azure.yml
Labels: not-notes-worthy

#10247 [VSTS] Stop build on error.
  tools/devops/automation/templates/packages/build.yml
Labels: not-notes-worthy

#10248 [src] Fix dependencies of the maccatalyst-defines.rsp files for .NET assemblies.
  src/Makefile
Labels: not-notes-worthy

#10245 [VSTS] Use the jenkins scripts over re-implementing everything.
  tools/devops/automation/templates/packages/build.yml
  tools/devops/automation/templates/packages/stage.yml
Labels: not-notes-worthy

#10244 [CallKit] Add to macOS.
  src/Constants.mac.cs.in
  src/frameworks.sources
  tests/xtro-sharpie/macOS-CallKit.ignore
  tools/common/StaticRegistrar.cs
Labels: note-highlight

#10250 [dotnet] Set default runtime feature switches.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#10219 [msbuild] Fix xcframework support when used directly as native references
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveFrameworksBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#10255 [VSTS] Make sure we fwd the device prefix to the download of the publ…
  tools/devops/automation/templates/common/publish-html.yml
Labels: not-notes-worthy

#10256 [xcode12.3][mono] Bump mono to get watchsim64 fix
  mk/mono.mk
  tests/bcl-test/watchOS-monotouch_Microsoft.CSharp_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_Mono.Runtime.Tests_test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Core_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Numerics_test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Numerics_xunit-test.dll.ignore
Labels: notes-mention

#10257 [main][mono] Bump mono to match Android
  mk/mono.mk
  tests/bcl-test/watchOS-monotouch_Microsoft.CSharp_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_Mono.Runtime.Tests_test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Core_xunit-test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Numerics_test.dll.ignore
  tests/bcl-test/watchOS-monotouch_System.Numerics_xunit-test.dll.ignore
Labels: notes-mention

#10263 [Foundation] Fix typo in NSFileCoordinator.CoordinateBatc[h]. Fixes #10260.
  src/foundation.cs
Labels: bug

#10264 [compare-commits] Rework logic to build xamarin-macios again from a separate clone.
  tools/compare-commits.sh
Labels: not-notes-worthy, run-internal-tests, skip-all-tests, skip-external-tests

#10258 [Actions] Add the backport action
  .github/workflows/backport-trigger.yml
Labels: not-notes-worthy

#10259 [Actions] Add a rebase action.
  .github/workflows/rebase-trigger.yml
Labels: not-notes-worthy

#10271 [d16-8][Actions] Backport rebase and backport actions.
  .github/workflows/backport-trigger.yml
  .github/workflows/rebase-trigger.yml
Labels: not-notes-worthy

#10262 [spritekit] Add nullability to (generated and manual) bindings
  src/ObjCRuntime/ThrowHelper.cs
  src/SpriteKit/Enums.cs
  src/SpriteKit/ObsoleteCompat.cs
  src/SpriteKit/SKAction.cs
  src/SpriteKit/SKFieldNode.cs
  src/SpriteKit/SKKeyframeSequence.cs
  src/SpriteKit/SKNode.cs
  src/SpriteKit/SKShapeNode.cs
  src/SpriteKit/SKUniform.cs
  src/SpriteKit/SKVideoNode.cs
  src/SpriteKit/SKWarpGeometryGrid.cs
  src/spritekit.cs
  tests/monotouch-test/SpriteKit/SpriteNodeTest.cs
  tests/xtro-sharpie/common-SpriteKit.ignore
  tests/xtro-sharpie/iOS-SpriteKit.ignore
  tests/xtro-sharpie/macOS-SpriteKit.ignore
  tests/xtro-sharpie/tvOS-SpriteKit.ignore
  tests/xtro-sharpie/watchOS-SpriteKit.ignore
Labels: enhancement

#10274 [VSTS] Allow to skip tests via a parameter to make debugging easier.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/packages/build.yml
  tools/devops/automation/templates/packages/stage.yml
Labels: not-notes-worthy

#10272 [Foundation] Fix nullability for the 'resourceValues' parameter for NSUrl.CreateBookmarkData. Fixes #10261.
  src/foundation.cs
Labels: bug

#10277 [VSTS] Allow to skip device tests when triggering form vsts.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/packages/build.yml
  tools/devops/automation/templates/packages/stage.yml
Labels: not-notes-worthy

#10280 [VSTS] Remove all the device pipelines.
  tools/devops/device-tests/README.md
  tools/devops/device-tests/cambridge-ios-32b-device-tests.yml
  tools/devops/device-tests/cambridge-ios-beta-device-tests.yml
  tools/devops/device-tests/cambridge-ios-device-tests.yml
  tools/devops/device-tests/cambridge-tvos-beta-device-tests.yml
  tools/devops/device-tests/cambridge-tvos-device-tests.yml
  tools/devops/device-tests/ddfun-ios-device-tests.yml
  tools/devops/device-tests/ddfun-tvos-device-tests.yml
  tools/devops/device-tests/scripts/GitHub.Tests.ps1
  tools/devops/device-tests/scripts/GitHub.psm1
  tools/devops/device-tests/scripts/MLaunch.Tests.ps1
  tools/devops/device-tests/scripts/MLaunch.psm1
  tools/devops/device-tests/scripts/Makefile
  tools/devops/device-tests/scripts/System.Tests.ps1
  tools/devops/device-tests/scripts/System.psm1
  tools/devops/device-tests/scripts/VSTS.Tests.ps1
  tools/devops/device-tests/scripts/VSTS.psm1
  tools/devops/device-tests/templates/cambridge-variables.yml
  tools/devops/device-tests/templates/common-variables.yml
  tools/devops/device-tests/templates/ddfun-variables.yml
  tools/devops/device-tests/templates/device-tests-stage.yml
  tools/devops/device-tests/templates/device-tests.yml
  tools/devops/device-tests/templates/download-artifacts.yml
  tools/devops/device-tests/templates/publish-html.yml
  tools/devops/device-tests/templates/upload-vsdrops.yml
  tools/devops/device-tests/templates/upload-vsts-tests.yml
Labels: not-notes-worthy

#10278 [VSTS] Add code to be able to create gists from windows via pwsh.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#10279 [xtro] Fix nullability checks on parameters
  src/avfoundation.cs
  src/avkit.cs
  src/classkit.cs
  src/coreimage.cs
  src/coreml.cs
  src/corewlan.cs
  src/foundation.cs
  src/gamekit.cs
  src/mapkit.cs
  src/messageui.cs
  src/scenekit.cs
  src/uikit.cs
  src/xkit.cs
  tests/xtro-sharpie/NullabilityCheck.cs
  tests/xtro-sharpie/common-UIKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: bug

#10283 [VSTS] Remove all the references of xamarin-storage.
  tools/devops/automation/scripts/GitHub.Tests.ps1
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/devices/stage.yml
Labels: not-notes-worthy

#10282 [VSTS] Use the correct md path.
  tools/devops/automation/templates/common/download-artifacts.yml
Labels: not-notes-worthy

#10218 Replace manually maintained code about frameworks with generated code.
  src/Constants.iOS.cs.in
  src/Constants.mac.cs.in
  src/Constants.maccatalyst.cs.in
  src/Constants.tvos.cs.in
  src/Constants.watch.cs.in
  src/Foundation/NSObject.mac.cs
  src/Makefile
  src/ObjCRuntime/Dlfcn.cs
  src/generate-frameworks-constants/Program.cs
  src/generate-frameworks-constants/generate-frameworks-constants.csproj
  src/generate-frameworks-constants/generate-frameworks-constants.sln
  tools/common/Frameworks.cs
  tools/mmp/linker/MonoMac.Tuner/MonoMacNamespaces.cs
Labels: not-notes-worthy

#10288 [VSTS] Reuse the script from jenkins to clean the bots.
  tools/devops/automation/scripts/bash/clean-bot.sh
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/packages/build.yml
Labels: not-notes-worthy

#10293 [VSTS] Reuse the script used in jenkins to build the nugets.
  jenkins/build-nugets.sh
  jenkins/build-package.sh
  tools/devops/automation/scripts/bash/build-nugets.sh
  tools/devops/automation/scripts/bash/productsign.sh
  tools/devops/automation/templates/packages/build.yml
Labels: not-notes-worthy

#10297 [VSTS] Add a comment once the tests have been executed by the pipeline.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/packages/build.yml
  tools/devops/automation/templates/packages/download-artifacts.yml
  tools/devops/automation/templates/packages/publish-html.yml
  tools/devops/automation/templates/packages/stage.yml
Labels: not-notes-worthy

#10301 Yaml pipeline triggers: Enable CI trigger for all topic branches
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#10307 [tests] Use the FSharp.Core NuGet for Mac Catalyst.
  tests/fsharp/fsharp.fsproj
  tests/fsharplibrary/fsharplibrary.fsproj
Labels: not-notes-worthy

#10311 [bgen] Avoid a NullReferenceException when reporting multiple attributes on a type. Fixes #10310.
  src/generator-attribute-manager.cs
  tests/generator/ErrorTests.cs
  tests/generator/bi1059.cs
Labels: enhancement

#10295 Add support for binding projects in Mac Catalyst. Fixes #10286.
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.MacCatalyst.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/test-libraries/Makefile
  tools/common/Application.cs
  tools/common/CompilerFlags.cs
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy

#10306 [main] Merge xcode12.3 into main
  Make.config
  Make.versions
  Versions-ios.plist.in
  Versions-mac.plist.in
  src/CoreGraphics/CGColor.cs
  src/CoreVideo/CVPixelFormatType.cs
  src/HealthKit/Enums.cs
  src/Metal/MTLEnums.cs
  src/Network/NWPath.cs
  src/UIKit/UIEnums.cs
  src/adservices.cs
  src/arkit.cs
  src/avfoundation.cs
  src/contacts.cs
  src/coreimage.cs
  src/coremotion.cs
  src/frameworks.sources
  src/gamecontroller.cs
  src/healthkit.cs
  src/imageio.cs
  src/network.cs
  src/networkextension.cs
  src/tvservices.cs
  src/uikit.cs
  tests/bindings-test2/bindings-test2.csproj
  tests/introspection/ApiAvailabilityTest.cs
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/monotouch-test/CoreGraphics/ColorTest.cs
  tests/monotouch-test/CoreVideo/CoreVideoEnumsTest.cs
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
  tests/monotouch-test/Network/NWPathTest.cs
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
  tests/xtro-sharpie/iOS-CoreMotion.todo
  tests/xtro-sharpie/iOS-Network.todo
  tests/xtro-sharpie/iOS-NetworkExtension.todo
  tests/xtro-sharpie/macOS-CoreMotion.todo
  tests/xtro-sharpie/macOS-Network.todo
  tests/xtro-sharpie/macOS-NetworkExtension.todo
  tests/xtro-sharpie/tvOS-Network.todo
  tests/xtro-sharpie/watchOS-AVFoundation.ignore
  tests/xtro-sharpie/watchOS-Network.todo
  tools/common/Frameworks.cs
  tools/mtouch/Makefile
Labels: note-highlight

#10313 [main] Update API diff to the xcode12.3 release
  Make.config
Labels: not-notes-worthy

#10318 [mtouch] Allow referencing Xamarin.iOS.dll in a Mac Catalyst app.
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy

#10317 [src] Any type forwarders in iOS' Xamarin.iOS.dll must appear in the Mac Catalyst facade as well.
  src/generate-type-forwarders/Program.cs
Labels: not-notes-worthy

#10319 [tests] Add a Xamarin.Forms test project using Mac Catalyst.
  tests/common/TestProjects/MyCatalystFormsApp/AppDelegate.cs
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon1024.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon120.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon152.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon167.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon180.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon20.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon29.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon40.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon58.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon60.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon76.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon80.png
  tests/common/TestProjects/MyCatalystFormsApp/Assets.xcassets/AppIcon.appiconset/Icon87.png
  tests/common/TestProjects/MyCatalystFormsApp/Entitlements.plist
  tests/common/TestProjects/MyCatalystFormsApp/Info.plist
  tests/common/TestProjects/MyCatalystFormsApp/Main.cs
  tests/common/TestProjects/MyCatalystFormsApp/MyCatalystFormsApp.csproj
  tests/common/TestProjects/MyCatalystFormsApp/MyCatalystFormsAppNS/App.xaml
  tests/common/TestProjects/MyCatalystFormsApp/MyCatalystFormsAppNS/App.xaml.cs
  tests/common/TestProjects/MyCatalystFormsApp/MyCatalystFormsAppNS/AssemblyInfo.cs
  tests/common/TestProjects/MyCatalystFormsApp/MyCatalystFormsAppNS/MainPage.xaml
  tests/common/TestProjects/MyCatalystFormsApp/MyCatalystFormsAppNS/MainPage.xaml.cs
  tests/common/TestProjects/MyCatalystFormsApp/MyCatalystFormsAppNS/MyCatalystFormsAppNS.csproj
  tests/common/TestProjects/MyCatalystFormsApp/Properties/AssemblyInfo.cs
  tests/common/TestProjects/MyCatalystFormsApp/Resources/Default-568h@2x.png
  tests/common/TestProjects/MyCatalystFormsApp/Resources/Default-Portrait.png
  tests/common/TestProjects/MyCatalystFormsApp/Resources/Default-Portrait@2x.png
  tests/common/TestProjects/MyCatalystFormsApp/Resources/Default.png
  tests/common/TestProjects/MyCatalystFormsApp/Resources/Default@2x.png
  tests/common/TestProjects/MyCatalystFormsApp/Resources/LaunchScreen.storyboard
Labels: not-notes-worthy
