Repository dotnet/macios, pull requests merged in 2020-03, with the labels that each got.

#8018 [bgen] Refactor a bit to not use target framework string comparison when we can use an enum.
  src/btouch.cs
Labels: not-notes-worthy

#8017 [bgen] No need to verify that System.Nullable`1 comes from mscorlib.
  src/generator-typemanager.cs
Labels: not-notes-worthy

#8019 [bgen] Don't determine assembly name directly from target framework identifier.
  src/generator.cs
Labels: not-notes-worthy

#8009 [mtouch] Add `force-rejected-types-removal` optimization
  docs/website/optimizations.md
  msbuild/tests/MyReleaseBuild/MyReleaseBuild.csproj
  msbuild/tests/MyReleaseBuild/ViewController.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/ReleaseBuild.cs
  tests/introspection/ApiBaseTest.cs
  tests/introspection/ApiClassPtrTest.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/ApiWeakPropertyTest.cs
  tests/linker/ios/link all/link all.csproj
  tests/monotouch-test/UIKit/WebViewTest.cs
  tests/mtouch/MTouch.cs
  tools/common/Driver.cs
  tools/common/Optimizations.cs
  tools/common/StaticRegistrar.cs
  tools/linker/MonoTouch.Tuner/RemoveCode.cs
  tools/linker/MonoTouch.Tuner/RemoveCodeBase.cs
  tools/linker/RemoveRejectedTypesStep.cs
  tools/mtouch/Tuning.cs
  tools/mtouch/mtouch.csproj
Labels: note-highlight

#8023 [bgen] Don't use assembly identity to identify attributes.
  src/Resources.Designer.cs
  src/Resources.resx
  src/btouch.cs
  src/generator-attribute-manager.cs
  src/generator-typemanager.cs
  src/xlf/Resources.cs.xlf
  src/xlf/Resources.de.xlf
  src/xlf/Resources.es.xlf
  src/xlf/Resources.fr.xlf
  src/xlf/Resources.it.xlf
  src/xlf/Resources.ja.xlf
  src/xlf/Resources.ko.xlf
  src/xlf/Resources.pl.xlf
  src/xlf/Resources.pt-BR.xlf
  src/xlf/Resources.ru.xlf
  src/xlf/Resources.tr.xlf
  src/xlf/Resources.zh-Hans.xlf
  src/xlf/Resources.zh-Hant.xlf
Labels: not-notes-worthy

#8027 [src] Simplify the makefile a bit.
  src/Makefile
Labels: not-notes-worthy

#8025 [Intents] Update bindings from Xcode 10.3 to Xcode 11.4 Beta 2
  src/Intents/INIntentResolutionResult.cs
  src/intents.cs
  tests/introspection/ApiProtocolTest.cs
  tests/xtro-sharpie/common-Intents.ignore
  tests/xtro-sharpie/iOS-Intents.todo
  tests/xtro-sharpie/macOS-Intents.todo
  tests/xtro-sharpie/watchOS-Intents.todo
Labels: note-highlight

#8033 [tests][monotouch-test] Tweak UIWebView tests to work in every case
  tests/monotouch-test/UIKit/WebViewTest.cs
Labels: not-notes-worthy

#8034 [xcode11.4] Initial commit for Xcode 11.4 Beta 3 support
  Make.config
  src/passkit.cs
  tests/common/TestRuntime.cs
  tests/monotouch-test/UIKit/TextFieldTest.cs
  tests/xtro-sharpie/iOS-AutomaticAssessmentConfiguration.todo
  tests/xtro-sharpie/iOS-NetworkExtension.todo
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/iOS-WebKit.todo
  tests/xtro-sharpie/macOS-AutomaticAssessmentConfiguration.todo
  tests/xtro-sharpie/macOS-NetworkExtension.todo
  tests/xtro-sharpie/macOS-WebKit.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/watchOS-PassKit.todo
Labels: note-highlight

#8039 [configure] Fix shellcheck warnings.
  configure
Labels: not-notes-worthy

#8044 [msbuild] Re-use tools/common/TargetFramework.cs.
  msbuild/Xamarin.Mac.Tasks/Tasks/DetectSigningIdentity.cs
  msbuild/Xamarin.MacDev.Tasks.Core/PlatformFramework.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/AlToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MetalTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
  msbuild/Xamarin.iOS.Tasks.Core/IPhoneSdks.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ParseDeviceSpecificBuildInformationTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ValidateAppBundleTaskBase.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/IBToolTaskTests.cs
Labels: not-notes-worthy

#8052 Add dotnet as a configure option and provision it.
  .gitignore
  Make.config
  Makefile
  configure
  jenkins/build.sh
  system-dependencies.sh
Labels: not-notes-worthy

#8050 [linker] No need to support monotouch.dll anymore.
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link all/PreserveTest.cs
  tools/linker/MonoTouch.Tuner/RemoveCode.cs
  tools/mtouch/Target.cs
Labels: not-notes-worthy

#8051 [tools] Remove the MonoTouch,v1.0 target framework.
  src/btouch.cs
  tools/common/TargetFramework.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#8056 [jenkins] Fix provisioning old macOS bots.
  jenkins/prepare-packaged-macos-tests.sh
Labels: not-notes-worthy

#8048 [msbuild] Pass the entire TargetFrameworkMoniker to tasks instead of just TargetFrameworkIdentifier/TargetFrameworkVersion.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
  msbuild/Xamarin.MacDev.Tasks.Core/PlatformFramework.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/AlToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileSceneKitAssetsTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MetalTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ScnToolTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/IPhoneSdks.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileEntitlementsTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ParseDeviceSpecificBuildInformationTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ResolveNativeWatchAppTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ValidateAppBundleTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.Common.targets
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/DetectSdkLocationsTaskTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_iOS.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_tvOS.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_watchOS.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/MTouchTaskTests.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/ValidateAppBundleTaskTests.cs
Labels: not-notes-worthy

#8060 [devops] Fix provisioning device testing bots.
  tools/devops/device-tests-common.yml
Labels: build-package, not-notes-worthy, skip-all-tests, trigger-device-tests

#8055 [Metal] Update bindings to Xcode 11.4 Beta 3
  src/Metal/Defs.cs
  src/metal.cs
  tests/xtro-sharpie/macOS-Metal.ignore
  tests/xtro-sharpie/macOS-Metal.todo
Labels: note-highlight

#8066 [tests] Don't assume test assemblies are at a specific distance from the root directory.
  tests/common/Configuration.cs
Labels: not-notes-worthy

#8065 [xharness] Handle UTF8 text better.
  tests/xharness/Execution/ProcessManager.cs
  tests/xharness/Jenkins/Jenkins.cs
Labels: not-notes-worthy

#8062 [d16-5-xcode11.4] Merge xcode11.4 into d16-5
  Make.config
  docs/website/mmp-errors.md
  docs/website/mtouch-errors.md
  docs/website/optimizations.md
  msbuild/tests/MyReleaseBuild/MyReleaseBuild.csproj
  msbuild/tests/MyReleaseBuild/ViewController.cs
  msbuild/tests/Xamarin.iOS.Tasks.Tests/ProjectsTests/ReleaseBuild.cs
  src/Constants.iOS.cs.in
  src/Constants.mac.cs.in
  src/Metal/Defs.cs
  src/PassKit/PKEnums.cs
  src/VideoToolbox/VTDefs.cs
  src/automaticassessmentconfiguration.cs
  src/frameworks.sources
  src/metal.cs
  src/passkit.cs
  src/wkwebkit.cs
  tests/common/BundlerTest.cs
  tests/common/TestRuntime.cs
  tests/introspection/ApiBaseTest.cs
  tests/introspection/ApiClassPtrTest.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/ApiWeakPropertyTest.cs
  tests/linker/ios/link all/link all.csproj
  tests/monotouch-test/UIKit/TextFieldTest.cs
  tests/monotouch-test/UIKit/WebViewTest.cs
  tests/mtouch/MTouch.cs
  tests/mtouch/RegistrarTest.cs
  tests/xtro-sharpie/common-PassKit.ignore
  tests/xtro-sharpie/iOS-AutomaticAssessmentConfiguration.todo
  tests/xtro-sharpie/iOS-NetworkExtension.todo
  tests/xtro-sharpie/iOS-WebKit.todo
  tests/xtro-sharpie/macOS-AutomaticAssessmentConfiguration.todo
  tests/xtro-sharpie/macOS-Metal.ignore
  tests/xtro-sharpie/macOS-Metal.todo
  tests/xtro-sharpie/macOS-NetworkExtension.todo
  tests/xtro-sharpie/macOS-WebKit.ignore
  tests/xtro-sharpie/macOS-WebKit.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/watchOS-PassKit.ignore
  tools/common/Application.cs
  tools/common/Driver.cs
  tools/common/Frameworks.cs
  tools/common/Optimizations.cs
  tools/common/StaticRegistrar.cs
  tools/linker/MonoTouch.Tuner/RemoveCode.cs
  tools/linker/MonoTouch.Tuner/RemoveCodeBase.cs
  tools/linker/RemoveRejectedTypesStep.cs
  tools/linker/ScanTypeReferenceStep.cs
  tools/mmp/Tuning.cs
  tools/mmp/driver.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Makefile
  tools/mtouch/Target.cs
  tools/mtouch/Tuning.cs
  tools/mtouch/mtouch.cs
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#8076 [mmp] Only iOS has dual bitness now, no need to check for Xamarin.Mac.
  tools/common/Application.cs
Labels: not-notes-worthy

#8075 [FileProvider] Update bindings to Xcode 11.4 Beta 3
  src/fileprovider.cs
  tests/xtro-sharpie/macOS-FileProvider.ignore
  tests/xtro-sharpie/macOS-FileProvider.todo
Labels: not-notes-worthy

#8082 Revert "[Harness] Move utilities out from Harness.cs, refactor AppRunner fields (#8074)"
  tests/xharness/AppInstallMonitorLog.cs
  tests/xharness/AppRunner.cs
  tests/xharness/BCLTestImporter/BCLTestImportTargetFactory.cs
  tests/xharness/BCLTestImporter/BCLTestProjectGenerator.cs
  tests/xharness/Collections/BlockingEnumerableCollection.cs
  tests/xharness/Collections/IAsyncEnumerable.cs
  tests/xharness/Collections/ILoadAsync.cs
  tests/xharness/CrashReportSnapshot.cs
  tests/xharness/Execution/IProcessManager.cs
  tests/xharness/Execution/MLaunchArguments.cs
  tests/xharness/Execution/ProcessManager.cs
  tests/xharness/Hardware/Device.cs
  tests/xharness/Hardware/Devices.cs
  tests/xharness/Hardware/IDevice.cs
  tests/xharness/Hardware/IHardwareDevice.cs
  tests/xharness/Hardware/ISimulatorDevice.cs
  tests/xharness/Hardware/SimDevice.cs
  tests/xharness/Hardware/Simulators.cs
  tests/xharness/Hardware/TCCDatabase.cs
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/TestTasks/AggregatedRunSimulatorTask.cs
  tests/xharness/Jenkins/TestTasks/NUnitExecuteTask.cs
  tests/xharness/Jenkins/TestTasks/RunDeviceTask.cs
  tests/xharness/Jenkins/TestTasks/RunSimulatorTask.cs
  tests/xharness/Jenkins/TestTasks/RunXITask.cs
  tests/xharness/MakefileGenerator.cs
  tests/xharness/MonoNativeInfo.cs
  tests/xharness/Program.cs
  tests/xharness/Simulators.cs
  tests/xharness/SolutionGenerator.cs
  tests/xharness/Targets/MacTarget.cs
  tests/xharness/Targets/TVOSTarget.cs
  tests/xharness/Targets/TodayExtensionTarget.cs
  tests/xharness/Targets/UnifiedTarget.cs
  tests/xharness/Targets/WatchOSTarget.cs
  tests/xharness/TestProject.cs
  tests/xharness/Utilities/DirectoryUtilities.cs
  tests/xharness/Utilities/Helpers.cs
  tests/xharness/Xharness.Tests/Execution/Tests/MlaunchArgumentsTest.cs
  tests/xharness/Xharness.Tests/Hardware/Tests/DeviceTest.cs
  tests/xharness/Xharness.Tests/Hardware/Tests/DevicesTest.cs
  tests/xharness/Xharness.Tests/Hardware/Tests/TCCDatabaseTests.cs
  tests/xharness/Xharness.Tests/Logging/Tests/LogFileTest.cs
  tests/xharness/Xharness.Tests/Samples/devices.xml
  tests/xharness/Xharness.Tests/Xharness.Tests.csproj
  tests/xharness/xharness.csproj
Labels: not-notes-worthy

#8080 [msbuild] Create common base class for MmpTaskBase and MtouchTaskBase.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BundlerToolTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#8084 Limit GitHub comments to 32768 characters.
  jenkins/Jenkinsfile
  jenkins/add-commit-comment.sh
Labels: run-internal-tests

#8089 [d16-5-xcode11.4] Bump versions and Api diff
  Make.config
  Make.versions
Labels: not-notes-worthy

#8070 Build bgen and the product assemblies using/referencing netcore3.1.
  Make.config
  builds/Makefile
  mk/quiet.mk
  src/CFNetwork/Content.cs
  src/CFNetwork/MessageHandler.cs
  src/Compression/TaskToApm.cs
  src/Foundation/NSUrlSessionHandler.cs
  src/Makefile
  src/Makefile.generator
  src/ObjCRuntime/Runtime.cs
  src/Resources.Designer.cs
  src/Resources.resx
  src/Security/Certificate.cs
  src/System.Net.Http/CFContentStream.cs
  src/System.Net.Http/CFNetworkHandler.cs
  src/bgen/bgen
  src/bgen/bgen.csproj
  src/bgen/bgen.sln
  src/btouch.cs
  src/frameworks.sources
  src/xlf/Resources.cs.xlf
  src/xlf/Resources.de.xlf
  src/xlf/Resources.es.xlf
  src/xlf/Resources.fr.xlf
  src/xlf/Resources.it.xlf
  src/xlf/Resources.ja.xlf
  src/xlf/Resources.ko.xlf
  src/xlf/Resources.pl.xlf
  src/xlf/Resources.pt-BR.xlf
  src/xlf/Resources.ru.xlf
  src/xlf/Resources.tr.xlf
  src/xlf/Resources.zh-Hans.xlf
  src/xlf/Resources.zh-Hant.xlf
  tests/Makefile
  tests/bgen/bgen-tests.csproj
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/TestTasks/DotNetBuildTask.cs
  tests/xharness/Jenkins/TestTasks/DotNetTestTask.cs
  tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
  tests/xharness/Jenkins/TestTasks/NUnitExecuteTask.cs
  tests/xharness/Jenkins/TestTasks/RunTestTask.cs
  tests/xharness/Jenkins/TestTasks/RunXtroTask.cs
  tests/xharness/Logging/ILog.cs
  tests/xharness/xharness.csproj
  tools/common/TargetFramework.cs
Labels: not-notes-worthy

#8095 [xharness] Rework how we build test-libraries a bit.
  tests/xharness/Jenkins/Jenkins.cs
Labels: not-notes-worthy

#8094 [xharness] Improve TCC database editing.
  tests/xharness/Hardware/TCCDatabase.cs
Labels: not-notes-worthy

#8097 [foundation] Fix typos in NSExpression
  src/Foundation/NSExpression.cs
Labels: not-notes-worthy

#8099 [runtime] Abort if the call to Runtime.Initialize fails.
  runtime/runtime.m
Labels: not-notes-worthy

#8096 [msbuild] Simplify the BTouch task implementation.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/BTouch.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.Common.props
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
Labels: not-notes-worthy

#8109 Fix path to dont link project in Xamarin.Mac.sln.
  Xamarin.Mac.sln
Labels: not-notes-worthy

#8108 Fix API comparison. Fixes #xamarin/maccore@2176.
  src/Makefile
  src/Makefile.generator
  tools/compare-commits.sh
Labels: not-notes-worthy

#8118 [msbuild] The Mmp/Mtouch tasks are passed the expected TargetFrameworkMoniker, so no need to have any custom logic here.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BundlerToolTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
Labels: not-notes-worthy

#8119 [src] Fix git duplicating code when merging.
  src/Makefile
Labels: not-notes-worthy

#8122 [Harness] Move all test project generation to the template object.
  tests/xharness/BCLTestImporter/BCLTestImportTargetFactory.cs
  tests/xharness/BCLTestImporter/BCLTestProjectGenerator.cs
  tests/xharness/BCLTestImporter/BclTestProject.cs
  tests/xharness/BCLTestImporter/BclTestProjectInfo.cs
  tests/xharness/BCLTestImporter/Templates/IAssemblyLocator.cs
  tests/xharness/BCLTestImporter/Templates/IProjectFilter.cs
  tests/xharness/BCLTestImporter/Templates/ITemplatedProject.cs
  tests/xharness/BCLTestImporter/Templates/Managed/RegisterTypeGenerator.cs
  tests/xharness/BCLTestImporter/Templates/Managed/Resources/RegisterType.cs
  tests/xharness/BCLTestImporter/Templates/Managed/XamariniOSTemplate.cs
  tests/xharness/BCLTestImporter/Xamarin/AssemblyLocator.cs
  tests/xharness/BCLTestImporter/Xamarin/ProjectFilter.cs
  tests/xharness/BCLTestImporter/iOSBclTestProject.cs
  tests/xharness/Utilities/ProjectFileExtensions.cs
  tests/xharness/Xharness.Tests/BCLTestImporter/Tests/BCLTestProjectGeneratorTest.cs
  tests/xharness/Xharness.Tests/BCLTestImporter/Xamarin/Tests/AssemblyLocatorTest.cs
  tests/xharness/Xharness.Tests/BCLTestImporter/Xamarin/Tests/ProjectFilterTest.cs
  tests/xharness/Xharness.Tests/BCLTestImporter/Xamarin/Tests/XamariniOSTemplateTest.cs
  tests/xharness/Xharness.Tests/Xharness.Tests.csproj
  tests/xharness/xharness.csproj
Labels: run-bcl-tests

#8121 [mtouch/mmp] Rework how we find developer tools. Partial fix for #4634 and fixes #8005.
  tests/mmptest/src/MMPTest.cs
  tests/mmptest/src/NativeReferencesTests.cs
  tools/common/Driver.cs
  tools/mmp/Application.cs
  tools/mmp/driver.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Application.cs
  tools/mtouch/Target.cs
  tools/mtouch/errors.Designer.cs
  tools/mtouch/errors.resx
  tools/mtouch/mtouch.cs
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#8126 [NetworkExtension] Update bindings to Xcode 11.4 Beta 3
  src/generator.cs
  src/networkextension.cs
  tests/xtro-sharpie/common-NetworkExtension.ignore
  tests/xtro-sharpie/iOS-NetworkExtension.todo
  tests/xtro-sharpie/macOS-NetworkExtension.todo
Labels: note-highlight

#8132 [mmp] Fix install_name_tool invocation.
  tools/mmp/driver.cs
Labels: not-notes-worthy

#8128 [mtouch/mmp] Rework how we find developer tools. Partial fix for #4634 and fixes #8005. (#8121)
  tests/mmptest/src/MMPTest.cs
  tests/mmptest/src/NativeReferencesTests.cs
  tools/common/Driver.cs
  tools/mmp/Application.cs
  tools/mmp/driver.cs
  tools/mmp/mmp.csproj
  tools/mtouch/Application.cs
  tools/mtouch/Target.cs
  tools/mtouch/mtouch.cs
Labels: bug, build-package, run-sample-tests, skip-device-tests, skip-public-jenkins

#8136 [tests] Adjust MT5107 to work when external verbosity is higher, and make it faster.
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#8135 [jenkins] Add missing parenthesis in text.
  jenkins/Jenkinsfile
Labels: not-notes-worthy

#8131 [Harness] Remove the code that check if the test dlls were downloaded.
  tests/xharness/BCLTestImporter/BCLTestAssemblyDefinition.cs
  tests/xharness/BCLTestImporter/BCLTestProjectDefinition.cs
  tests/xharness/BCLTestImporter/Templates/Managed/XamariniOSTemplate.cs
  tests/xharness/Xharness.Tests/BCLTestImporter/Tests/TestAssemblyDefinitionTest.cs
  tests/xharness/Xharness.Tests/BCLTestImporter/Tests/TestProjectDefinitionTest.cs
Labels: run-bcl-tests

#8137 [mtouch/mmp] Improve target framework code.
  src/btouch.cs
  tests/common/BundlerTest.cs
  tests/common/BundlerTool.cs
  tests/mmptest/src/MMPTest.cs
  tests/mmptest/src/MmpTool.cs
  tests/mtouch/MTouch.cs
  tools/common/Driver.cs
  tools/common/TargetFramework.cs
  tools/mmp/Makefile
  tools/mmp/Tuning.cs
  tools/mmp/driver.cs
  tools/mtouch/Application.cs
  tools/mtouch/errors.Designer.cs
  tools/mtouch/errors.resx
  tools/mtouch/mtouch.cs
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: breaking-change, note-deprecation

#8151 [tests] Remove test that used Xamarin.Mac/Classic.
  tests/Makefile
  tests/no-mmp/.gitignore
  tests/no-mmp/Main.cs
  tests/no-mmp/Makefile
  tests/no-mmp/main.m
Labels: not-notes-worthy

#7795 Bump to mono:2020-02
  Make.config
  mk/mono.mk
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
  tools/linker/MonoTouch.Tuner/MonoTouchMarkStep.cs
  tools/mmp/mmp.csproj
  tools/mtouch/mtouch.csproj
Labels: run-all-tests, run-internal-tests, skip-api-comparison, skip-device-tests, trigger-device-tests

#8150 [mtouch/mmp] Only use stdout from xcrun as the path of the file that was found. Fixes #8147.
  tests/mmptest/src/System.ServiceModel/Net45.cs
  tools/common/Driver.cs
  tools/mmp/driver.cs
Labels: not-notes-worthy, skip-device-tests, skip-public-jenkins

#8163 [tests] Work around xamarin/maccore#2177 by building test-libraries as part of the build.
  tests/Makefile
Labels: not-notes-worthy

#8164 [d16-5-xcode11.4][mtouch/mmp] Only use stdout from xcrun as the path of the file that was found. Fixes #8147. (#8150)
  tests/mmptest/src/System.ServiceModel/Net45.cs
  tools/common/Driver.cs
  tools/mmp/driver.cs
Labels: not-notes-worthy

#8165 [d16-6-xcode11.4][mtouch/mmp] Only use stdout from xcrun as the path of the file that was found. Fixes #8147. (#8150)
  tests/mmptest/src/System.ServiceModel/Net45.cs
  tools/common/Driver.cs
  tools/mmp/driver.cs
Labels: not-notes-worthy

#8168 [tests][monotouch-test] Update UrlProtocolTest
  tests/monotouch-test/Foundation/UrlProtocolTest.cs
Labels: not-notes-worthy, test-only-issue

#8169 [d16-6-xcode11.4] Bump to mono:2020-02
  Make.config
  mk/mono.mk
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
  tools/linker/MonoTouch.Tuner/MonoTouchMarkStep.cs
  tools/mmp/mmp.csproj
  tools/mtouch/mtouch.csproj
Labels: note-highlight

#8166 [mtouch/mmp] Add better diagnostics if xcrun returns invalid data.
  tools/common/Driver.cs
  tools/mtouch/errors.Designer.cs
  tools/mtouch/errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#8173 It seems 'initWithRequest:cachedResponse:client:' is not called on 10.9
  tests/monotouch-test/Foundation/UrlProtocolTest.cs
Labels: build-package, run-internal-tests, skip-api-comparison, skip-bcl-tests, skip-btouch-tests, skip-docs-tests, skip-ios-msbuild-tests, skip-ios-tests, skip-mmp-tests, skip-mtouch-tests, skip-public-jenkins, skip-simulator-tests, skip-tvos-tests, skip-watchos-tests, skip-xtro-tests

#8180 Fix generator diff after .NET modifications.
  jenkins/.gitignore
  tools/compare-commits.sh
Labels: not-notes-worthy

#8179 [d16-6-xcode11.4] It seems 'initWithRequest:cachedResponse:client:' is not called on 10.9
  tests/monotouch-test/Foundation/UrlProtocolTest.cs
Labels: not-notes-worthy, skip-api-comparison, skip-bcl-tests, skip-btouch-tests, skip-device-tests, skip-docs-tests, skip-ios-msbuild-tests, skip-mmp-tests, skip-mtouch-tests, skip-xtro-tests

#8182 Revert "[tests] Adjust expected result of looking for 'mono_native_initialize'. Fixes xamarin/maccore#1809. (#6806)"
  tests/mono-native/Introspection.cs
Labels: not-notes-worthy

#8189 [d16-5-xcode11.4] Initial bump to Xcode 11.4 Final
  Make.config
  tests/xtro-sharpie/iOS-ARKit.todo
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
Labels: note-highlight

#8190 [xcode11.4][arkit] Add final bindings (ARKit 3.5)
  src/arkit.cs
  tests/xtro-sharpie/iOS-ARKit.todo
Labels: note-highlight

#8191 [xcode11.4][intentsui] Add missing [DesignatedInitializer]
  src/intentsui.cs
  tests/xtro-sharpie/iOS-IntentsUI.todo
Labels: not-notes-worthy

#8194 [FileProvider] Update bindings to Xcode 11.4 Beta 3 (#8075)
  src/fileprovider.cs
  tests/xtro-sharpie/macOS-FileProvider.ignore
  tests/xtro-sharpie/macOS-FileProvider.todo
Labels: note-highlight

#8183 [Harness] Refactor, simplify and fix issues in the result parsing.
  tests/xharness/AppBundleInformationParser.cs
  tests/xharness/AppRunner.cs
  tests/xharness/Harness.cs
  tests/xharness/IAppRunner.cs
  tests/xharness/ITestReporter.cs
  tests/xharness/Jenkins/Resource.cs
  tests/xharness/Jenkins/TestTasks/BuildToolTask.cs
  tests/xharness/Jenkins/TestTasks/RunDeviceTask.cs
  tests/xharness/Jenkins/TestTasks/RunSimulatorTask.cs
  tests/xharness/Jenkins/TestTasks/TestTask.cs
  tests/xharness/Listeners/SimpleListener.cs
  tests/xharness/TestReporter.cs
  tests/xharness/Xharness.Tests/Samples/NUnitV3SampleFailure.xml
  tests/xharness/Xharness.Tests/Samples/NUnitV3SampleSuccess.xml
  tests/xharness/Xharness.Tests/Samples/run-log.txt
  tests/xharness/Xharness.Tests/Tests/AppRunnerTests.cs
  tests/xharness/Xharness.Tests/Tests/TestReporterTests.cs
  tests/xharness/Xharness.Tests/Xharness.Tests.csproj
  tests/xharness/xharness.csproj
Labels: run-bcl-tests

#8192 [xcode11.4][UIKit] Update bindings to Xcode 11.4 Final
  src/UIKit/UIEnums.cs
  src/UIKit/UIEventButtonMaskExtensions.cs
  src/frameworks.sources
  src/uikit.cs
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
Labels: note-highlight

#8204 [mmp] Remove MonoMacPreserveCode, it's not needed anymore.
  tools/mmp/Tuning.cs
  tools/mmp/linker/MonoMac.Tuner/MonoMacPreserveCode.cs
  tools/mmp/mmp.csproj
Labels: not-notes-worthy

#8203 [Harness] Remove Harness as a dependency
  tests/xharness/AppRunner.cs
  tests/xharness/Collections/ILoadAsync.cs
  tests/xharness/CrashSnapshotReporter.cs
  tests/xharness/DeviceLogCapturer.cs
  tests/xharness/Execution/IProcessManager.cs
  tests/xharness/Execution/ProcessManager.cs
  tests/xharness/GitHub.cs
  tests/xharness/Hardware/Devices.cs
  tests/xharness/Hardware/ISimulatorDevice.cs
  tests/xharness/Hardware/SimulatorDevice.cs
  tests/xharness/Hardware/Simulators.cs
  tests/xharness/Hardware/TCCDatabase.cs
  tests/xharness/Harness.cs
  tests/xharness/IAppRunner.cs
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/TestTasks/BuildProjectTask.cs
  tests/xharness/Jenkins/TestTasks/BuildToolTask.cs
  tests/xharness/Jenkins/TestTasks/DotNetBuildTask.cs
  tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
  tests/xharness/Jenkins/TestTasks/MakeTask.cs
  tests/xharness/Jenkins/TestTasks/RunDeviceTask.cs
  tests/xharness/Jenkins/TestTasks/RunSimulatorTask.cs
  tests/xharness/Program.cs
  tests/xharness/Xharness.Tests/Execution/Tests/ProcessManagerTests.cs
  tests/xharness/Xharness.Tests/Hardware/Tests/DevicesTest.cs
  tests/xharness/Xharness.Tests/Hardware/Tests/SimulatorDeviceTest.cs
  tests/xharness/Xharness.Tests/Hardware/Tests/SimulatorsTest.cs
  tests/xharness/Xharness.Tests/Hardware/Tests/TCCDatabaseTests.cs
  tests/xharness/Xharness.Tests/Tests/AppRunnerTests.cs
  tests/xharness/Xharness.Tests/Tests/CrashSnapshotReporterTests.cs
Labels: do-not-merge

#8209 [siminstaller] Update parsing xml because Apple changed their schema.
  tools/siminstaller/Program.cs
Labels: not-notes-worthy

#8227 [Harness] Add a new known failure to help the monitoring person.
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/TestTasks/MSBuildTask.cs
  tests/xharness/Jenkins/TestTasks/RunTestTask.cs
Labels: run-bcl-tests, run-internal-tests

#8221 [Harness] Remove the BCLTestProjectInfo class.
  tests/xharness/BCLTestImporter/BCLTestProjectGenerator.cs
  tests/xharness/BCLTestImporter/BclTestProjectInfo.cs
  tests/xharness/BCLTestImporter/Templates/ITemplatedProject.cs
  tests/xharness/BCLTestImporter/Templates/Managed/XamariniOSTemplate.cs
  tests/xharness/Xharness.Tests/BCLTestImporter/Tests/BCLTestProjectGeneratorTest.cs
  tests/xharness/xharness.csproj
Labels: run-internal-tests

#8237 [generator] Remove unreachable code
  src/generator.cs
Labels: not-notes-worthy

#8231 [master] [siminstaller] Update parsing xml because Apple changed their schema.
  tools/siminstaller/Program.cs
Labels: not-notes-worthy

#8243 [Harness] Make sure we do not copy/generate the app sources more than once.
  tests/xharness/BCLTestImporter/Templates/Managed/XamariniOSTemplate.cs
Labels: run-bcl-tests

#8242 Wrap mono_gc_init_finalizer_thread() call with now-needed coop GC state transition
  runtime/monotouch-main.m
Labels: bug

#8247 [mtouch] Fix filename casing for Errors.resx.
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
Labels: not-notes-worthy

#8248 [d16-5-xcode11.4] Wrap mono_gc_init_finalizer_thread() call with now-needed coop GC state transition
  runtime/monotouch-main.m
Labels: build-package
