Repository dotnet/macios, pull requests merged in 2021-08, with the labels that each got.

#12309 [runtime] Implement computing and passing the NATIVE_DLL_SEARCH_DIRECTORIES runtime property. Fixes #10504.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/runtime.m
Labels: not-notes-worthy, run-dotnet-tests

#12311 [dotnet-tools] Fix Profile.Is[Product|Sdk]Assembly. Fixes #12276.
  tools/dotnet-linker/Compat.cs
Labels: not-notes-worthy, run-dotnet-tests

#12317 [monotouch-test] Teach HealthKit tests about new HKQuantityTypeIdentifiers/HKCategoryTypeIdnetifiers.
  tests/monotouch-test/HealthKit/CategoryTypeIdentifierTest.cs
  tests/monotouch-test/HealthKit/QuantityTypeIdentifierTest.cs
Labels: not-notes-worthy

#12300 [FileProvider] Add support for Xcode13 beta 4.
  src/FileProvider/Structs.cs
  src/fileprovider.cs
  src/frameworks.sources
  tests/xtro-sharpie/iOS-FileProvider.todo
  tests/xtro-sharpie/macOS-FileProvider.todo
Labels: note-highlight

#12301 [LocalAuthentication] Add support for Xcode 13 beta 4.
  src/LocalAuthentication/LAEnums.cs
  tests/xtro-sharpie/MacCatalyst-LocalAuthentication.todo
  tests/xtro-sharpie/iOS-LocalAuthentication.todo
  tests/xtro-sharpie/macOS-LocalAuthentication.ignore
Labels: note-highlight

#12258 [Localization] Removing Test with Ignore File
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationIgnore/common-Translations.ignore
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationStringTest.cs
Labels: not-notes-worthy

#12321 [monotouch-test] Resolve symlinks in paths before comparing them.
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: not-notes-worthy

#12328 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#12318 [xharness] Gracefully handle any exceptions that may occur when parsing build logs.
  tests/xharness/Jenkins/TestTasks/RunTest.cs
Labels: not-notes-worthy

#12297 [objcruntime] Avoid intermediate strings for formatting
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy

#12323 [runtime/tools] Implement finding native support libraries when linking statically. Fixes #10950, #11145 and #12100.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/runtime.m
  runtime/xamarin/main.h
  tools/common/Application.cs
  tools/common/Target.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Labels: not-notes-worthy, run-dotnet-tests

#12329 [introspection] Make green on .NET/Mac Catalyst. Fixes #10215.
  tests/introspection/ApiAvailabilityTest.cs
  tests/introspection/ApiPInvokeTest.cs
  tests/xharness/Harness.cs
Labels: not-notes-worthy, run-dotnet-tests

#12092 [HomeKit] Updates for Xcode13 Beta 1-2
  src/HomeKit/HMEnums.cs
  src/frameworks.sources
  src/homekit.cs
  tests/xtro-sharpie/MacCatalyst-HomeKit.ignore
  tests/xtro-sharpie/Makefile
  tests/xtro-sharpie/common-HomeKit.ignore
  tests/xtro-sharpie/iOS-HomeKit.ignore
  tests/xtro-sharpie/iOS-HomeKit.todo
  tests/xtro-sharpie/tvOS-HomeKit.ignore
  tests/xtro-sharpie/tvOS-HomeKit.todo
  tests/xtro-sharpie/watchOS-HomeKit.ignore
  tests/xtro-sharpie/watchOS-HomeKit.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#12283 [CI] Remove beta3 from bots.
  tools/devops/automation/scripts/bash/clean-bot.sh
Labels: do-not-merge, not-notes-worthy

#12299 [PassKit] Update bindings for Xcode 13.0 beta 1, 2
  src/PassKit/PKEnums.cs
  src/passkit.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/xtro-sharpie/MacCatalyst-PassKit.todo
  tests/xtro-sharpie/common-PassKit.ignore
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/macOS-PassKit.todo
  tests/xtro-sharpie/watchOS-PassKit.todo
Labels: note-highlight

#12121 [SceneKit] Update bindings for Xcode13.0 beta 1 & beta 2
  src/SceneKit/Defs.cs
  src/scenekit.cs
  tests/xtro-sharpie/MacCatalyst-SceneKit.ignore
  tests/xtro-sharpie/MacCatalyst-SceneKit.todo
  tests/xtro-sharpie/common-SceneKit.ignore
  tests/xtro-sharpie/iOS-SceneKit.todo
  tests/xtro-sharpie/macOS-SceneKit.todo
  tests/xtro-sharpie/tvOS-SceneKit.todo
  tests/xtro-sharpie/watchOS-SceneKit.todo
Labels: note-highlight

#12330 [tools] Link away Runtime.RegisterEntryAssembly if and only if we've optimized away the dynamic registrar. Fixes #12327.
  src/ObjCRuntime/Runtime.cs
  tools/linker/MonoTouch.Tuner/RemoveCode.cs
Labels: not-notes-worthy, run-dotnet-tests

#12331 Always create binlogs during the build.
  builds/Makefile
  msbuild/Makefile
  src/Makefile
  src/Makefile.generator
  tests/Makefile
  tools/mmp/Makefile
  tools/siminstaller/Makefile
  tools/xibuild/Makefile
Labels: not-notes-worthy

#12340 [objcruntime] Enable nullable on `Selector` class
  src/ObjCRuntime/Selector.cs
  src/appkit.cs
  src/foundation.cs
  src/generator.cs
  src/uikit.cs
  tests/xtro-sharpie/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
Labels: not-notes-worthy

#12339 [xcode13] Fix catalyst intro tests on macOS 12
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
Labels: not-notes-worthy

#12333 [dotnet] Handle an absolute PublishDir. Fixes #12041 and #12224.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12181 [SoundAnalysis] Updates for Xcode13 Beta1
  src/soundanalysis.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/xtro-sharpie/MacCatalyst-SoundAnalysis.todo
  tests/xtro-sharpie/iOS-SoundAnalysis.todo
  tests/xtro-sharpie/macOS-SoundAnalysis.todo
  tests/xtro-sharpie/tvOS-SoundAnalysis.todo
  tests/xtro-sharpie/watchOS-SoundAnalysis.todo
Labels: note-highlight

#12203 [AuthenticationServices] Updates for Xcode13 Beta3
  src/AuthenticationServices/PublicPrivateKeyAuthentication.cs
  src/Security/Certificate.cs
  src/authenticationservices.cs
  src/frameworks.sources
  tests/monotouch-test/AuthenticationServices/PublicPrivateKeyAuthenticationTests.cs
  tests/xtro-sharpie/MacCatalyst-AuthenticationServices.ignore
  tests/xtro-sharpie/MacCatalyst-AuthenticationServices.todo
  tests/xtro-sharpie/common-AuthenticationServices.ignore
  tests/xtro-sharpie/iOS-AuthenticationServices.todo
  tests/xtro-sharpie/macOS-AuthenticationServices.todo
  tests/xtro-sharpie/tvOS-AuthenticationServices.todo
  tests/xtro-sharpie/watchOS-AuthenticationServices.todo
Labels: note-highlight

#12326 [MetricKit] Add support for Xcode 13 beta4.
  src/MetricKit/MXMetricManager.cs
  src/frameworks.sources
  src/metrickit.cs
  tests/xtro-sharpie/MacCatalyst-MetricKit.ignore
  tests/xtro-sharpie/iOS-MetricKit.ignore
  tests/xtro-sharpie/macOS-MetricKit.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#12338 [QuickLookThumbnailing] Update bindings for Xcode 13.0 beta 1
  src/quicklookthumbnailing.cs
  tests/xtro-sharpie/MacCatalyst-QuickLookThumbnailing.todo
  tests/xtro-sharpie/iOS-QuickLookThumbnailing.todo
  tests/xtro-sharpie/macOS-QuickLookThumbnailing.todo
Labels: note-highlight

#12322 [xharness] Automatically inline Imports to a "shared.csproj" when cloning projects. Fixes #12316 and #12277.
  tests/common/shared-dotnet.csproj
  tests/linker/ios/dont link/dotnet/MacCatalyst/dont link.csproj
  tests/linker/ios/dont link/dotnet/iOS/dont link.csproj
  tests/linker/ios/dont link/dotnet/shared.csproj
  tests/linker/ios/dont link/dotnet/tvOS/dont link.csproj
  tests/linker/ios/link all/dotnet/MacCatalyst/link all.csproj
  tests/linker/ios/link all/dotnet/iOS/link all.csproj
  tests/linker/ios/link all/dotnet/shared.csproj
  tests/linker/ios/link all/dotnet/tvOS/link all.csproj
  tests/linker/ios/link sdk/dotnet/MacCatalyst/link sdk.csproj
  tests/linker/ios/link sdk/dotnet/iOS/link sdk.csproj
  tests/linker/ios/link sdk/dotnet/shared.csproj
  tests/linker/ios/link sdk/dotnet/tvOS/link sdk.csproj
  tests/monotouch-test/dotnet/MacCatalyst/monotouch-test.csproj
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
  tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
  tests/monotouch-test/dotnet/shared.csproj
  tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj
  tests/xharness/Harness.cs
  tests/xharness/ProjectFileExtensions.cs
  tests/xharness/TestPlatformExtensions.cs
  tests/xharness/TestProject.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy, run-dotnet-tests

#12098 [PHASE] Add suppport for Xcode13 beta 2.
  runtime/bindings-generator.cs
  src/frameworks.sources
  src/phase.cs
  tests/introspection/iOS/iOSApiClassPtrTest.cs
  tests/introspection/iOS/iOSApiFieldTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/monotouch-test/Phase/PhaseAmbientMixerDefinitionTest.cs
  tests/monotouch-test/Phase/PhaseEnvelopeSegmentTest.cs
  tests/monotouch-test/Phase/PhaseEnvelopeTest.cs
  tests/monotouch-test/Phase/PhaseObjectTest.cs
  tests/xtro-sharpie/MacCatalyst-PHASE.todo
  tests/xtro-sharpie/SimdCheck.cs
  tests/xtro-sharpie/common-PHASE.ignore
  tests/xtro-sharpie/iOS-PHASE.todo
  tests/xtro-sharpie/macOS-PHASE.todo
  tests/xtro-sharpie/tvOS-PHASE.ignore
  tools/common/Frameworks.cs
  tools/common/StaticRegistrar.cs
  tools/common/Target.cs
Labels: note-highlight

#12349 [ModelIO] Add Xcode 13 beta4 support.
  src/ModelIO/MIEnums.cs
  src/mobilecoreservices.cs
  src/modelio.cs
  tests/xtro-sharpie/MacCatalyst-ModelIO.todo
  tests/xtro-sharpie/iOS-ModelIO.todo
  tests/xtro-sharpie/macOS-ModelIO.todo
  tests/xtro-sharpie/tvOS-ModelIO.todo
Labels: note-highlight

#12348 [MLCompute] Add support for Xcode 13 beta 4.
  src/MLCompute/MLHelpers.cs
  src/mlcompute.cs
  tests/xtro-sharpie/MacCatalyst-MLCompute.todo
  tests/xtro-sharpie/common-MLCompute.ignore
  tests/xtro-sharpie/iOS-MLCompute.todo
  tests/xtro-sharpie/macOS-MLCompute.todo
  tests/xtro-sharpie/tvOS-MLCompute.todo
Labels: note-highlight

#12344 [runtime] Add support for logging exceptions that go through exception marshalling using an environment variable. Fixes #12343.
  runtime/runtime.m
  runtime/xamarin/main.h
  runtime/xamarin/runtime.h
Labels: not-notes-worthy

#12346 [msbuild/dotnet] Don't overwrite the 'CreateAppBundleDependsOn' property, only add to it. Fixes #12325.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/common/BinLog.cs
  tests/dotnet/UnitTests/TemplateProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12350 [foundation] Enable nullable for `MonoTouchException`
  src/Foundation/MonoTouchException.cs
Labels: not-notes-worthy

#12352 [NetworkExtension] Add Xcode 13 beta 4 support.
  src/networkextension.cs
  tests/xtro-sharpie/MacCatalyst-NetworkExtension.ignore
  tests/xtro-sharpie/MacCatalyst-NetworkExtension.todo
  tests/xtro-sharpie/iOS-NetworkExtension.todo
Labels: note-highlight

#12355 [release/6.0.xx-preview7] Fix version to be preview 7.X, not preview 7X.
  Make.config
Labels: not-notes-worthy, run-dotnet-tests

#12351 [NearbyInterction] Add support for xcode 13 beta 4.
  src/NearbyInteraction/Enums.cs
  src/NearbyInteraction/NINearbyObject.cs
  src/frameworks.sources
  src/nearbyinteraction.cs
  tests/xtro-sharpie/MacCatalyst-NearbyInteraction.todo
  tests/xtro-sharpie/iOS-NearbyInteraction.todo
  tests/xtro-sharpie/watchOS-NearbyInteraction.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#12361 [corefoundation] Fix minimum version on MacCatalyst
  src/CoreFoundation/OSLog.cs
  tests/introspection/ApiAvailabilityTest.cs
Labels: not-notes-worthy

#12359 [tests] Add .NET version of the fsharp test.
  tests/common/mac/MacMain.fs
  tests/fsharp/FSharpTests.fs
  tests/fsharp/Main.fs
  tests/fsharp/dotnet/MacCatalyst/Info.plist
  tests/fsharp/dotnet/MacCatalyst/Makefile
  tests/fsharp/dotnet/MacCatalyst/fsharp.fsproj
  tests/fsharp/dotnet/Makefile
  tests/fsharp/dotnet/iOS/Info.plist
  tests/fsharp/dotnet/iOS/Makefile
  tests/fsharp/dotnet/iOS/fsharp.fsproj
  tests/fsharp/dotnet/macOS/Info.plist
  tests/fsharp/dotnet/macOS/Makefile
  tests/fsharp/dotnet/macOS/fsharp.fsproj
  tests/fsharp/dotnet/shared.fsproj
  tests/fsharp/dotnet/shared.mk
  tests/fsharp/dotnet/tvOS/Info.plist
  tests/fsharp/dotnet/tvOS/Makefile
  tests/fsharp/dotnet/tvOS/fsharp.fsproj
  tests/xharness/Harness.cs
  tests/xharness/TestProject.cs
Labels: not-notes-worthy, run-dotnet-tests

#12358 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#12356 [tests] Merge the Main function into the AppDelegate class in numerous tests.
  tests/framework-test/iOS/AppDelegate.cs
  tests/framework-test/iOS/Main.cs
  tests/framework-test/iOS/framework-test-ios.csproj
  tests/introspection/dotnet/MacCatalyst/introspection.csproj
  tests/introspection/dotnet/iOS/introspection.csproj
  tests/introspection/dotnet/tvOS/introspection.csproj
  tests/introspection/iOS/AppDelegate.cs
  tests/introspection/iOS/Main.cs
  tests/introspection/iOS/introspection-ios.csproj
  tests/linker/ios/dont link/AppDelegate.cs
  tests/linker/ios/dont link/Main.cs
  tests/linker/ios/dont link/dont link.csproj
  tests/linker/ios/dont link/dotnet/shared.csproj
  tests/linker/ios/link all/AppDelegate.cs
  tests/linker/ios/link all/MEFTests.cs
  tests/linker/ios/link all/Main.cs
  tests/linker/ios/link all/dotnet/shared.csproj
  tests/linker/ios/link all/link all.csproj
  tests/linker/ios/link sdk/AppDelegate.cs
  tests/linker/ios/link sdk/Main.cs
  tests/linker/ios/link sdk/dotnet/shared.csproj
  tests/linker/ios/link sdk/link sdk.csproj
  tests/mono-native/AppDelegate.cs
  tests/mono-native/Main.cs
  tests/mono-native/iOS/mono-native.csproj.template
  tests/monotouch-test/AppDelegate.cs
  tests/monotouch-test/Main.cs
  tests/xcframework-test/iOS/AppDelegate.cs
  tests/xcframework-test/iOS/Main.cs
  tests/xcframework-test/iOS/xcframework-test-ios.csproj
Labels: not-notes-worthy, run-dotnet-tests

#12354 [tests] Add debug spew to track down #xamarin/maccore@2414.
  tests/framework-test/iOS/AppDelegate.cs
  tests/interdependent-binding-projects/Main.cs
  tests/introspection/iOS/AppDelegate.cs
  tests/linker/ios/dont link/AppDelegate.cs
  tests/linker/ios/link all/AppDelegate.cs
  tests/linker/ios/link sdk/AppDelegate.cs
  tests/monotouch-test/AppDelegate.cs
  tests/xcframework-test/iOS/AppDelegate.cs
Labels: not-notes-worthy, run-dotnet-tests

#12363 [release/6.0.1xx-preview7] [net6] Stops replacing custom linker steps on Windows
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy, backported

#12362 [net6] Stops replacing custom linker steps on Windows
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy

#12368 [generator] Use new `CFArray.StringArrayFromHandle` instead of the existing `NSArray` API
  src/AssetsLibrary/ALAsset.cs
  src/AudioUnit/AudioComponent.cs
  src/CoreFoundation/CFArray.cs
  src/CoreServices/LaunchServices.cs
  src/CoreText/Adapter.cs
  src/Foundation/NSArray.cs
  src/Foundation/NSMetadataItem.cs
  src/Foundation/NSSearchPath.cs
  src/ImageIO/CGImageDestination.cs
  src/ImageIO/CGImageSource.cs
  src/MediaAccessibility/MediaAccessibility.cs
  src/MobileCoreServices/UTType.cs
  src/NaturalLanguage/NLStrongDictionary.cs
  src/PrintCore/PrintCore.cs
  src/SceneKit/SCNSceneSource.cs
  src/Security/Certificate.cs
  src/Security/SslContext.cs
  src/SystemConfiguration/CaptiveNetwork.cs
  src/generator.cs
  tests/perftest/TollFreeBridge.cs
Labels: enhancement

#12337 [QuickLook] Update bindings for Xcode 13.0 beta 1,2,3,4
  src/generator.cs
  src/quicklook.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/xtro-sharpie/MacCatalyst-QuickLook.todo
  tests/xtro-sharpie/iOS-QuickLook.todo
Labels: note-highlight

#12364 [NearbyInteraction] Convert spaces to tabs.
  src/NearbyInteraction/Enums.cs
  src/NearbyInteraction/NINearbyObject.cs
  src/nearbyinteraction.cs
Labels: not-notes-worthy

#12376 [tests][intro] Fix Phase tests on macOS 12 and iOS devices
  tests/introspection/ApiBaseTest.cs
Labels: not-notes-worthy

#12334 [dotnet] Remove workaround for private symbols for AOT.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/MySimpleApp/MacCatalyst/Info.plist
  tests/mtouch/MTouch.cs
  tools/common/Application.cs
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy, run-dotnet-tests

#12370 [tests] Fix typo in error message.
  tests/common/mac/MacMain.cs
  tests/common/mac/MacMain.fs
Labels: not-notes-worthy

#12360 [msbuild] Fix the inclusion of the mtouch errors in the Xamarin.MacDev.Tasks.Core assembly.
  msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
Labels: not-notes-worthy

#12383 [monotouch-test] Ignore ReadingListTest.DefaultReadingList.
  tests/monotouch-test/SafariServices/ReadingListTest.cs
Labels: not-notes-worthy

#12379 [cecil] Update all package references to the latest 0.11.4
  msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  tests/bgen/bgen-tests.csproj
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/generator/generator-tests.csproj
  tests/mmptest/mmptest.csproj
  tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj
  tests/xharness/xharness.csproj
  tests/xtro-sharpie/xtro-sharpie.csproj
  tools/install-source/install-source.csproj
Labels: not-notes-worthy

#12377 [objcruntime] Enable nullable on `ErrorHelper` and `RuntimeException`
  src/ObjCRuntime/ErrorHelper.cs
  src/ObjCRuntime/RuntimeException.cs
  tools/mmp/mmp.csproj
Labels: not-notes-worthy

#12365 [Security] Add Xcode 13 beta 4 support.
  src/Security/Authorization.cs
  src/Security/Certificate.cs
  src/Security/Trust.cs
  tests/xtro-sharpie/MacCatalyst-Security.ignore
  tests/xtro-sharpie/MacCatalyst-Security.todo
  tests/xtro-sharpie/iOS-Security.todo
  tests/xtro-sharpie/macOS-Security.todo
  tests/xtro-sharpie/tvOS-Security.todo
  tests/xtro-sharpie/watchOS-Security.todo
Labels: note-highlight

#12332 [msbuild] Delete any Mono crash dump files in the root app bundle before codesigning. Fixes #12320.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetFileSystemEntriesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/GetFileSystemEntries.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests

#12373 [tests] Add a .NET version of framework-test to our test list.
  tests/bindings-framework-test/dotnet/MacCatalyst/Makefile
  tests/bindings-framework-test/dotnet/MacCatalyst/bindings-framework-test.csproj
  tests/bindings-framework-test/dotnet/iOS/Makefile
  tests/bindings-framework-test/dotnet/iOS/bindings-framework-test.csproj
  tests/bindings-framework-test/dotnet/macOS/Makefile
  tests/bindings-framework-test/dotnet/macOS/bindings-framework-test.csproj
  tests/bindings-framework-test/dotnet/shared.csproj
  tests/bindings-framework-test/dotnet/shared.mk
  tests/bindings-framework-test/dotnet/tvOS/Makefile
  tests/bindings-framework-test/dotnet/tvOS/bindings-framework-test.csproj
  tests/common/shared-dotnet.csproj
  tests/framework-test/dotnet/MacCatalyst/Info.plist
  tests/framework-test/dotnet/MacCatalyst/Makefile
  tests/framework-test/dotnet/MacCatalyst/framework-test.csproj
  tests/framework-test/dotnet/Makefile
  tests/framework-test/dotnet/iOS/Info.plist
  tests/framework-test/dotnet/iOS/Makefile
  tests/framework-test/dotnet/iOS/framework-test.csproj
  tests/framework-test/dotnet/macOS/Info.plist
  tests/framework-test/dotnet/macOS/Makefile
  tests/framework-test/dotnet/macOS/framework-test.csproj
  tests/framework-test/dotnet/shared.csproj
  tests/framework-test/dotnet/shared.mk
  tests/framework-test/dotnet/tvOS/Info.plist
  tests/framework-test/dotnet/tvOS/Makefile
  tests/framework-test/dotnet/tvOS/framework-test.csproj
  tests/xharness/Harness.cs
  tests/xharness/TestProject.cs
Labels: not-notes-worthy, run-dotnet-tests

#12390 [xtro] Ignore Obsoleted enums in EnumCheck.
  tests/xtro-sharpie/AttributeHelpers.cs
  tests/xtro-sharpie/EnumCheck.cs
  tests/xtro-sharpie/iOS-CoreTelephony.ignore
  tests/xtro-sharpie/iOS-iAd.ignore
  tests/xtro-sharpie/macOS-Intents.todo
  tests/xtro-sharpie/macOS-QTKit.ignore
  tests/xtro-sharpie/macOS-SafariServices.ignore
Labels: not-notes-worthy

#12394 [OpenGL] Add support for xcode 13 beta4.
  tests/xtro-sharpie/MacCatalyst-OpenGL[ES].ignore
Labels: note-highlight

#12393 [SystemConfiguration] Add support for xcode13 beta4.
  tests/xtro-sharpie/MacCatalyst-SystemConfiguration.ignore
Labels: note-highlight

#12387 [msbuild] Set `UseSecureTimestamp` inside `_CodesignFrameworks` too
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: bug

#12009 [dotnet][linker] Enable the sealer optimization
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/linker/ios/link all/SealerTest.cs
  tools/linker/MonoTouch.Tuner/SealerSubStep.cs
Labels: do-not-merge

#12401 [src] Ensure complete (error) coverage for nullability warnings
  src/CoreVideo/CVTime.cs
  src/Makefile
Labels: not-notes-worthy

#12392 [OSLog] Add support for xcode13 beta4.
  src/frameworks.sources
  src/oslog.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/xtro-sharpie/MacCatalyst-OSLog.todo
  tests/xtro-sharpie/iOS-OSLog.todo
  tests/xtro-sharpie/macOS-OSLog.todo
  tests/xtro-sharpie/tvOS-OSLog.todo
  tests/xtro-sharpie/watchOS-OSLog.todo
  tools/common/Frameworks.cs
  tools/mtouch/Makefile
Labels: note-highlight

#12385 [src] Define __MACOS__ for macOS builds.
  src/Makefile
  src/intents.cs
Labels: not-notes-worthy, run-dotnet-tests

#12395 [monotouch-test] Use unique file names to avoid issues when multiple proceseses of monotouch-test are running simultaneously. Fixes #xamarin/maccore@2461.
  tests/monotouch-test/Foundation/FileManagerTest.cs
  tests/monotouch-test/Foundation/UrlTest.cs
Labels: not-notes-worthy

#12404 [tests][linker] Re-enable the metadata reducer test case for dotnet
  tests/linker/ios/link sdk/ReflectionTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12403 [tests][intro] Fix introspection when running on MacCatalyst 15 (macOS12)
  tests/introspection/ApiCMAttachmentTest.cs
Labels: not-notes-worthy

#12411 [tests][monotouch-test] Re-enable registrar test for conformsToProtocol for dotnet
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12407 [src] Use [NoMacCatalyst] everywhere.
  src/AudioUnit/AudioComponentDescription.cs
  src/SceneKit/Defs.cs
  src/Security/SecProtocolOptions.cs
  src/StoreKit/Enums.cs
  src/avfoundation.cs
  src/callkit.cs
  src/coreaudiokit.cs
  src/corelocation.cs
  src/fileprovider.cs
  src/intentsui.cs
  src/metal.cs
  src/passkit.cs
  src/photos.cs
  src/photosui.cs
  src/pushkit.cs
  src/scenekit.cs
  src/uikit.cs
  src/videosubscriberaccount.cs
  src/xkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#12417 [msbuild] Promote '_PartialAppManifest' to a public item group ('PartialAppManifest'). Fixes #10646.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CoreMLCompilerTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ReadItemsFromFileBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/dotnet/MyPartialAppManifestApp/AppDelegate.cs
  tests/dotnet/MyPartialAppManifestApp/MacCatalyst/Info.plist
  tests/dotnet/MyPartialAppManifestApp/MacCatalyst/Makefile
  tests/dotnet/MyPartialAppManifestApp/MacCatalyst/MyPartialAppManifestApp.csproj
  tests/dotnet/MyPartialAppManifestApp/Makefile
  tests/dotnet/MyPartialAppManifestApp/Partial.plist
  tests/dotnet/MyPartialAppManifestApp/iOS/Info.plist
  tests/dotnet/MyPartialAppManifestApp/iOS/Makefile
  tests/dotnet/MyPartialAppManifestApp/iOS/MyPartialAppManifestApp.csproj
  tests/dotnet/MyPartialAppManifestApp/macOS/Info.plist
  tests/dotnet/MyPartialAppManifestApp/macOS/Makefile
  tests/dotnet/MyPartialAppManifestApp/macOS/MyPartialAppManifestApp.csproj
  tests/dotnet/MyPartialAppManifestApp/shared.csproj
  tests/dotnet/MyPartialAppManifestApp/shared.mk
  tests/dotnet/MyPartialAppManifestApp/tvOS/Info.plist
  tests/dotnet/MyPartialAppManifestApp/tvOS/Makefile
  tests/dotnet/MyPartialAppManifestApp/tvOS/MyPartialAppManifestApp.csproj
  tests/dotnet/UnitTests/PartialAppManifestTest.cs
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests

#12412 [msbuild] Show a message in the ParseBundlerArguments task if we run into an argument we don't understand.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
Labels: not-notes-worthy

#12421 [dotnet] Fix exclusion of mono components.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#12415 [generator] Use new CFArray.ArrayFromHandle instead of the existing NSArray API
  src/CoreFoundation/CFArray.cs
  src/corefoundation.cs
  src/generator.cs
  tests/perftest/TollFreeBridge.cs
  tests/xtro-sharpie/common-CoreFoundation.ignore
Labels: notes-mention

#12420 [tests] Add .NET versions of xcframeworks-test and bindings-xcframework-test.
  tests/bindings-xcframework-test/dotnet/MacCatalyst/Makefile
  tests/bindings-xcframework-test/dotnet/MacCatalyst/bindings-xcframework-test.csproj
  tests/bindings-xcframework-test/dotnet/iOS/Makefile
  tests/bindings-xcframework-test/dotnet/iOS/bindings-xcframework-test.csproj
  tests/bindings-xcframework-test/dotnet/macOS/Makefile
  tests/bindings-xcframework-test/dotnet/macOS/bindings-xcframework-test.csproj
  tests/bindings-xcframework-test/dotnet/shared.csproj
  tests/bindings-xcframework-test/dotnet/shared.mk
  tests/bindings-xcframework-test/dotnet/tvOS/Makefile
  tests/bindings-xcframework-test/dotnet/tvOS/bindings-xcframework-test.csproj
  tests/xcframework-test/dotnet/MacCatalyst/Info.plist
  tests/xcframework-test/dotnet/MacCatalyst/Makefile
  tests/xcframework-test/dotnet/MacCatalyst/xcframework-test.csproj
  tests/xcframework-test/dotnet/Makefile
  tests/xcframework-test/dotnet/iOS/Info.plist
  tests/xcframework-test/dotnet/iOS/Makefile
  tests/xcframework-test/dotnet/iOS/xcframework-test.csproj
  tests/xcframework-test/dotnet/macOS/Info.plist
  tests/xcframework-test/dotnet/macOS/Makefile
  tests/xcframework-test/dotnet/macOS/xcframework-test.csproj
  tests/xcframework-test/dotnet/shared.csproj
  tests/xcframework-test/dotnet/shared.mk
  tests/xcframework-test/dotnet/tvOS/Info.plist
  tests/xcframework-test/dotnet/tvOS/Makefile
  tests/xcframework-test/dotnet/tvOS/xcframework-test.csproj
  tests/xharness/Harness.cs
Labels: not-notes-worthy, run-dotnet-tests

#12419 [Runtime] Ignore assemblies that aren't found at startup for macOS in .NET. Fixes #12341.
  src/AppKit/NSApplication.cs
  src/ObjCRuntime/Runtime.cs
  tests/dotnet/SimpleAppWithOldReferences/AppDelegate.cs
  tests/dotnet/SimpleAppWithOldReferences/MacCatalyst/Info.plist
  tests/dotnet/SimpleAppWithOldReferences/MacCatalyst/Makefile
  tests/dotnet/SimpleAppWithOldReferences/MacCatalyst/SimpleAppWithOldReferences.csproj
  tests/dotnet/SimpleAppWithOldReferences/dotnet45assembly/Library.cs
  tests/dotnet/SimpleAppWithOldReferences/dotnet45assembly/Makefile
  tests/dotnet/SimpleAppWithOldReferences/iOS/Info.plist
  tests/dotnet/SimpleAppWithOldReferences/iOS/Makefile
  tests/dotnet/SimpleAppWithOldReferences/iOS/SimpleAppWithOldReferences.csproj
  tests/dotnet/SimpleAppWithOldReferences/macOS/Info.plist
  tests/dotnet/SimpleAppWithOldReferences/macOS/Makefile
  tests/dotnet/SimpleAppWithOldReferences/macOS/SimpleAppWithOldReferences.csproj
  tests/dotnet/SimpleAppWithOldReferences/shared.csproj
  tests/dotnet/SimpleAppWithOldReferences/shared.mk
  tests/dotnet/SimpleAppWithOldReferences/tvOS/Info.plist
  tests/dotnet/SimpleAppWithOldReferences/tvOS/Makefile
  tests/dotnet/SimpleAppWithOldReferences/tvOS/SimpleAppWithOldReferences.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests

#12423 Bump ObjectiveSharpie.
  Make.config
Labels: not-notes-worthy

#12430 [xharness] Show better error message
  tests/xharness/TestProject.cs
Labels: not-notes-worthy

#12428 Bump mono.
  mk/mono.mk
Labels: not-notes-worthy

#12413 [Xcode13] Bump to beta 5.
  Make.config
  src/carplay.cs
  src/coremotion.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/monotouch-test/UIKit/TextFieldTest.cs
  tests/xtro-sharpie/MacCatalyst-AVFoundation.todo
  tests/xtro-sharpie/MacCatalyst-AudioToolbox.todo
  tests/xtro-sharpie/MacCatalyst-CoreGraphics.todo
  tests/xtro-sharpie/MacCatalyst-DataDetection.todo
  tests/xtro-sharpie/MacCatalyst-FileProvider.todo
  tests/xtro-sharpie/MacCatalyst-GameController.todo
  tests/xtro-sharpie/MacCatalyst-Intents.todo
  tests/xtro-sharpie/MacCatalyst-MailKit.todo
  tests/xtro-sharpie/MacCatalyst-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/MacCatalyst-Network.todo
  tests/xtro-sharpie/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/iOS-AudioToolbox.todo
  tests/xtro-sharpie/iOS-CarPlay.todo
  tests/xtro-sharpie/iOS-CoreGraphics.todo
  tests/xtro-sharpie/iOS-DataDetection.todo
  tests/xtro-sharpie/iOS-GameController.todo
  tests/xtro-sharpie/iOS-HealthKit.todo
  tests/xtro-sharpie/iOS-Intents.todo
  tests/xtro-sharpie/iOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/iOS-Network.todo
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/macOS-AVFoundation.todo
  tests/xtro-sharpie/macOS-AudioToolbox.todo
  tests/xtro-sharpie/macOS-CoreGraphics.todo
  tests/xtro-sharpie/macOS-CoreMotion.ignore
  tests/xtro-sharpie/macOS-CoreMotion.todo
  tests/xtro-sharpie/macOS-DataDetection.todo
  tests/xtro-sharpie/macOS-FileProvider.todo
  tests/xtro-sharpie/macOS-GameController.todo
  tests/xtro-sharpie/macOS-Intents.todo
  tests/xtro-sharpie/macOS-MailKit.todo
  tests/xtro-sharpie/macOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/macOS-Network.todo
  tests/xtro-sharpie/macOS-WebKit.todo
  tests/xtro-sharpie/tvOS-AVFoundation.todo
  tests/xtro-sharpie/tvOS-AudioToolbox.todo
  tests/xtro-sharpie/tvOS-CoreGraphics.todo
  tests/xtro-sharpie/tvOS-DataDetection.todo
  tests/xtro-sharpie/tvOS-GameController.todo
  tests/xtro-sharpie/tvOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/tvOS-Network.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-AVFoundation.todo
  tests/xtro-sharpie/watchOS-CoreGraphics.todo
  tests/xtro-sharpie/watchOS-DataDetection.todo
  tests/xtro-sharpie/watchOS-HealthKit.todo
  tests/xtro-sharpie/watchOS-Intents.todo
  tests/xtro-sharpie/watchOS-Network.todo
  tests/xtro-sharpie/watchOS-UIKit.todo
Labels: not-notes-worthy

#12429 [tests] Add/improve interdependent-binding-projects on .NET
  tests/common/mac/MacMain.cs
  tests/interdependent-binding-projects/Main.cs
  tests/interdependent-binding-projects/dotnet/MacCatalyst/Info.plist
  tests/interdependent-binding-projects/dotnet/MacCatalyst/Makefile
  tests/interdependent-binding-projects/dotnet/MacCatalyst/interdependent-binding-projects.csproj
  tests/interdependent-binding-projects/dotnet/iOS/Makefile
  tests/interdependent-binding-projects/dotnet/iOS/interdependent-binding-projects.csproj
  tests/interdependent-binding-projects/dotnet/macOS/Info.plist
  tests/interdependent-binding-projects/dotnet/macOS/Makefile
  tests/interdependent-binding-projects/dotnet/macOS/interdependent-binding-projects.csproj
  tests/interdependent-binding-projects/dotnet/shared.csproj
  tests/interdependent-binding-projects/dotnet/shared.mk
  tests/interdependent-binding-projects/dotnet/tvOS/Makefile
  tests/interdependent-binding-projects/dotnet/tvOS/interdependent-binding-projects.csproj
  tests/interdependent-binding-projects/dotnet/watchOS/Info.plist
  tests/interdependent-binding-projects/dotnet/watchOS/interdependent-binding-projects.csproj
  tests/xharness/Harness.cs
Labels: not-notes-worthy, run-dotnet-tests

#12425 [msbuild] Share the ACTool task implementation between iOS and macOS.
  msbuild/Xamarin.Mac.Tasks/Tasks/ACTool.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/ACTool.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#12432 [tests] Add .NET version of dont link for macOS.
  tests/linker/ios/dont link/DontLinkRegressionTests.cs
  tests/linker/ios/dont link/TableViewSourceTest.cs
  tests/linker/ios/dont link/dotnet/macOS/Info.plist
  tests/linker/ios/dont link/dotnet/macOS/Makefile
  tests/linker/ios/dont link/dotnet/macOS/dont link.csproj
  tests/linker/ios/dont link/dotnet/shared.csproj
  tests/xharness/Harness.cs
Labels: not-notes-worthy, run-dotnet-tests

#12431 [tests] Rework the bindings-test and fsharplibrary test projects to follow the pattern of the other .NET test projects.
  tests/bindings-test/dotnet/MacCatalyst/bindings-test.csproj
  tests/bindings-test/dotnet/iOS/bindings-test.csproj
  tests/bindings-test/dotnet/macOS/bindings-test.csproj
  tests/bindings-test/dotnet/shared.csproj
  tests/bindings-test/dotnet/tvOS/bindings-test.csproj
  tests/bindings-test/dotnet/watchOS/bindings-test.csproj
  tests/fsharplibrary/dotnet/MacCatalyst/Makefile
  tests/fsharplibrary/dotnet/MacCatalyst/fsharplibrary.fsproj
  tests/fsharplibrary/dotnet/iOS/Makefile
  tests/fsharplibrary/dotnet/iOS/fsharplibrary.fsproj
  tests/fsharplibrary/dotnet/macOS/Makefile
  tests/fsharplibrary/dotnet/macOS/fsharplibrary.fsproj
  tests/fsharplibrary/dotnet/shared.fsproj
  tests/fsharplibrary/dotnet/shared.mk
  tests/fsharplibrary/dotnet/tvOS/Makefile
  tests/fsharplibrary/dotnet/tvOS/fsharplibrary.fsproj
  tests/fsharplibrary/dotnet/watchOS/fsharplibrary.fsproj
Labels: not-notes-worthy, run-dotnet-tests

#12439 [dotnet] Don't use system resource keys if we're debugging. Fixes #12438.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#12424 [msbuild] Unify the iOS and macOS versions of the IBTool task.
  msbuild/Xamarin.Mac.Tasks/Tasks/IBTool.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/IBTool.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/IBToolTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/IBToolTaskTests.cs
Labels: not-notes-worthy

#12437 Fix lstat P/Invoke on arm64
  tools/common/PathUtils.cs
  tools/mmp/mmp.csproj
Labels: community, run-dotnet-tests

#12389 [QuickLookUI] Update bindings for Xcode 13.0 beta 1
  src/quicklookUI.cs
  tests/xtro-sharpie/macOS-QuickLookUI.todo
Labels: note-highlight

#12402 [QuickLook] Update based on quicklookui feedback
  src/quicklook.cs
Labels: note-highlight

#12445 [GameController] Add support for xcode 13 beta5.
  src/gamecontroller.cs
  tests/xtro-sharpie/MacCatalyst-GameController.todo
  tests/xtro-sharpie/iOS-GameController.todo
  tests/xtro-sharpie/macOS-GameController.todo
  tests/xtro-sharpie/tvOS-GameController.todo
Labels: note-highlight

#12448 [CoreMotion] Add Xcode13 beta5 support.
  src/coremotion.cs
  tests/xtro-sharpie/macOS-CoreMotion.todo
Labels: note-highlight

#12451 [HomeKit] Updates for Xcode13 Beta 5
  src/homekit.cs
Labels: note-highlight

#12442 .NET: make main the 'rc.1' release.
  Make.config
Labels: not-notes-worthy, run-dotnet-tests

#12443 [runtime] Skip early from xamarin_pinvoke_override to avoid a later logging statement.
  runtime/runtime.m
Labels: not-notes-worthy

#12441 [msbuild] Move app manifest loading code from ACTool/IBTool to the base XcodeCompiler tool.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/IBToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
Labels: not-notes-worthy, run-dotnet-tests

#12433 [msbuild] Add a property that specifies the final path to the Info.plist in the app bundle
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
Labels: not-notes-worthy, run-dotnet-tests

#12446 [runtime] Set the RUNTIME_IDENTIFER and APP_CONTEXT_BASE_DIRECTORY app context values. Fixes #12444.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/runtime.m
Labels: not-notes-worthy, run-dotnet-tests

#12453 [HealthKit] Add Xcode13 beta5 support.
  src/healthkit.cs
  tests/xtro-sharpie/iOS-HealthKit.todo
  tests/xtro-sharpie/watchOS-HealthKit.todo
Labels: note-highlight

#12456 [PassKit] Add support for xcode13 beta 5.
  src/passkit.cs
  tests/xtro-sharpie/iOS-PassKit.todo
Labels: note-highlight

#12447 [runtime] Set DOTNET_MODIFIABLE_ASSEMBLIES=debug when running an interpreted app with debug symbols. Fixes #12378.
  tools/common/Target.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
Labels: not-notes-worthy, run-dotnet-tests

#12436 [tests] Add .NET version of link all for macOS.
  tests/linker/ios/link all/DataContractTest.cs
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link all/PreserveTest.cs
  tests/linker/ios/link all/SealerTest.cs
  tests/linker/ios/link all/dotnet/Makefile
  tests/linker/ios/link all/dotnet/macOS/Info.plist
  tests/linker/ios/link all/dotnet/macOS/Makefile
  tests/linker/ios/link all/dotnet/macOS/link all.csproj
  tests/linker/ios/link all/dotnet/shared.csproj
  tests/linker/ios/link all/dotnet/shared.mk
  tests/linker/ios/link sdk/OptimizeGeneratedCodeTest.cs
  tests/linker/mac/link all/LinkAllTest.cs
  tests/xharness/Harness.cs
  tools/linker/CoreOptimizeGeneratedCode.cs
Labels: not-notes-worthy, run-dotnet-tests

#12458 [dotnet] Implement a workaround for .NET's lack of extensibility for 'dotnet run'.
  dotnet/Microsoft.iOS.Sdk/targets/Microsoft.iOS.Sdk.targets
  dotnet/Microsoft.tvOS.Sdk/targets/Microsoft.tvOS.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#12189 [ShazamKit] Updates Xcode13 beta1
  src/frameworks.sources
  src/shazamkit.cs
  tests/introspection/iOS/iOSApiClassPtrTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/xtro-sharpie/MacCatalyst-ShazamKit.todo
  tests/xtro-sharpie/iOS-ShazamKit.todo
  tests/xtro-sharpie/macOS-ShazamKit.todo
  tests/xtro-sharpie/tvOS-ShazamKit.todo
  tests/xtro-sharpie/watchOS-ShazamKit.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#12454 [Carplay] Add support for Xcode 13 beta 5 and fix catalyst attrs.
  src/carplay.cs
  tests/xtro-sharpie/iOS-CarPlay.todo
Labels: note-highlight

#12462 [tests] Add .NET version of link sdk for macOS.
  src/ILLink.Substitutions.MacCatalyst.xml
  src/ILLink.Substitutions.macOS.xml
  src/Makefile
  tests/linker/ios/link sdk/AotBugs.cs
  tests/linker/ios/link sdk/Bug2096Test.cs
  tests/linker/ios/link sdk/CryptoTest.cs
  tests/linker/ios/link sdk/DllImportTest.cs
  tests/linker/ios/link sdk/HttpClientHandlerTest.cs
  tests/linker/ios/link sdk/LinkExtraDefsTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/linker/ios/link sdk/dotnet/Makefile
  tests/linker/ios/link sdk/dotnet/macOS/Info.plist
  tests/linker/ios/link sdk/dotnet/macOS/Makefile
  tests/linker/ios/link sdk/dotnet/macOS/link sdk.csproj
  tests/linker/ios/link sdk/dotnet/shared.csproj
  tests/linker/ios/link sdk/dotnet/shared.mk
  tests/xharness/Harness.cs
Labels: not-notes-worthy, run-dotnet-tests

#12464 [Xcode13] Add the todo for ThreadNetwork.
  tests/xtro-sharpie/Makefile
  tests/xtro-sharpie/iOS-ThreadNetwork.todo
Labels: not-notes-worthy

#12461 [msbuild] Refactor the logic to compute the target devices for IBTool/ACTool.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
Labels: not-notes-worthy, run-dotnet-tests

#12470 [xharness] Bump timeout for .NET tests again.
  tests/xharness/Jenkins/Jenkins.cs
Labels: not-notes-worthy, run-dotnet-tests

#12471 [dotnet] Update logic for default global namespaces and fix the templates. Fixes #12457.
  dotnet/Microsoft.MacCatalyst.Sdk/Sdk/AutoImport.props
  dotnet/Microsoft.iOS.Sdk/Sdk/AutoImport.props
  dotnet/Microsoft.macOS.Sdk/Sdk/AutoImport.props
  dotnet/Microsoft.tvOS.Sdk/Sdk/AutoImport.props
  dotnet/Microsoft.watchOS.Sdk/Sdk/AutoImport.props
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/MacCatalystApp1.csproj
  dotnet/Templates/Microsoft.iOS.Templates/ios/iOSApp1.csproj
  dotnet/Templates/Microsoft.iOS.Templates/ioslib/iOSLib1.csproj
  dotnet/Templates/Microsoft.macOS.Templates/macos/macOSApp1.csproj
  dotnet/Templates/Microsoft.tvOS.Templates/tvos/tvOSApp1.csproj
  dotnet/targets/Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.tvOS.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Xamarin.Shared.Sdk.props
  tests/dotnet/UnitTests/TemplateTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12475 [tests] Fix the build for link sdk tests on .NET/macOS.
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12449 [dotnet] use **FromWorkload** for targeting/runtime pack versions
  Make.config
  dotnet/.gitignore
  dotnet/Makefile
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  tests/dotnet/Makefile
Labels: not-notes-worthy

#12474 [msbuild] Add a task to compute the path to the AOT compiler.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompiler.cs
Labels: not-notes-worthy, run-dotnet-tests

#12473 [generator] Simplify native enums logic.
  runtime/bindings-generator.cs
  src/generator.cs
  tests/generator/BGenTests.cs
  tests/generator/tests/nativeenum.cs
Labels: not-notes-worthy, run-dotnet-tests

#12466 [VideoToolbox] Add support for Xcode13 beta5.
  src/VideoToolbox/VTVideoEncoder.cs
  src/videotoolbox.cs
  tests/xtro-sharpie/MacCatalyst-VideoToolbox.todo
  tests/xtro-sharpie/iOS-VideoToolbox.todo
  tests/xtro-sharpie/macOS-VideoToolbox.todo
  tests/xtro-sharpie/tvOS-VideoToolbox.todo
Labels: note-highlight

#12478 Remove obsolete code
  tools/common/Application.cs
Labels: community, run-dotnet-tests

#12479 [Tools] Add editor snippets to help new developers.
  tools/editors/README.md
  tools/editors/VSCode/csharp.json
Labels: not-notes-worthy

#12480 [dotnet] Make CoreCLR the only option for macOS. Fixes #12477.
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/linker/BaseOptimizeGeneratedCodeTest.cs
  tests/linker/ios/link sdk/ReflectionTest.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy, run-dotnet-tests

#12485 [msbuild] Rename the GetMinimumOSVersion task to ReadAppManifest and make it read more properties from the app manifest.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetMinimumOSVersionTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ReadAppManifestTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/ReadAppManifest.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileITunesMetadataTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/IBToolTaskTests.cs
Labels: not-notes-worthy, run-dotnet-tests

#12486 [release/6.0.1xx-rc.1] [msbuild] Add a task to compute the path to the AOT compiler.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/FindAotCompiler.cs
Labels: not-notes-worthy, run-dotnet-tests, backported

#12488 [src] Augment the Native attribute to support custom conversion functions. Fixes #12111.
  src/AppKit/Enums.cs
  src/AppKit/NSEnumsExtensions.cs
  src/ObjCRuntime/NativeAttribute.cs
  src/ObjCRuntime/Runtime.cs
  src/UIKit/UIEnums.cs
  src/UIKit/UIEnumsExtensions.cs
  src/frameworks.sources
  src/generator-enums.cs
  src/generator.cs
  tests/generator/BGenTests.cs
  tests/generator/tests/nativeenum-extensions.cs
  tests/generator/tests/nativeenum.cs
Labels: not-notes-worthy, run-dotnet-tests

#12493 [Makefile] Prevent people from bulding in the wrong dir.
  system-dependencies.sh
Labels: not-notes-worthy

#12491 [AudioToolbox] Update bindings for Xcode 13.0 beta 1,3,4,5
  src/AudioUnit/AUEnums.cs
  src/AudioUnit/AudioUnit.cs
  src/audiounit.cs
  tests/xtro-sharpie/MacCatalyst-AudioToolbox.todo
  tests/xtro-sharpie/common-AudioToolbox.ignore
  tests/xtro-sharpie/iOS-AudioToolbox.todo
  tests/xtro-sharpie/macOS-AudioToolbox.todo
  tests/xtro-sharpie/tvOS-AudioToolbox.todo
Labels: note-highlight

#12483 [msbuild] Both the CompileProductDefinition and the CreateInstaller tasks must take the final app manifest as input.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/dotnet/UnitTests/PostBuildTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12496 We need the xamarin-impl feed.
  NuGet.config
Labels: not-notes-worthy

#12498 [tools] Pass the right arguments to the AOT compiler for Mac Catalyst. Fixes #12484.
  tests/monotouch-test/dotnet/MacCatalyst/Makefile
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tools/common/Application.cs
Labels: not-notes-worthy, run-dotnet-tests

#12507 [mono] bump to the HEAD of 2020-02
  Make.config
  mk/mono.mk
Labels: notes-mention

#12509 [monotouch-test] Ignore several HttpMessageTest test cases in CI in case of network failures.
  tests/monotouch-test/CoreServices/HttpMessageTest.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy

#12510 [xharness] Remove debug lock.
  tests/xharness/TestProject.cs
Labels: not-notes-worthy

#12512 [xharness] Move loading old test results into the background.
  tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
Labels: not-notes-worthy

#12487 [release/6.0.1xx-rc.1] [test][dotnet] Manually enable LLVM for app size comparison
  tests/dotnet/Makefile
Labels: not-notes-worthy, backported

#12511 [tests] Move deletion of existing temporary directory to the background.
  tests/mtouch/Cache.cs
  tests/xharness/.gitignore
  tests/xharness/TestProject.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy

#12497 Bump maccore (Increase needed verbosity when logging loaded frameworks)
  mk/xamarin.mk
Labels: not-notes-worthy

#12502 [CI] Build pipeline: Agent-Cleanser: yaml-template step
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#12514 [release/6.0.1xx-rc.1] [dotnet] Updates the path to illink when building from Windows
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: backported

#12517 [release/6.0.1xx-rc.1] Fixes Hot Restart build issues
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/CompileAppManifest.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: backported

#12518 [objcruntime] Do not pre-compute the `Selector.Name` property
  src/ObjCRuntime/Selector.cs
Labels: not-notes-worthy

#12494 [OpenGL] Add Support for DotNet Attributes
  src/OpenGL/CGLContext.cs
  src/OpenGL/CGLEnums.cs
  src/OpenGL/CGLPixelFormat.cs
Labels: dotnet

#12523 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#12525 [build] Set the default target platform version to the current beta versions.
  Make.versions
Labels: not-notes-worthy, run-dotnet-tests

#12527 [tests] Remove some ignores for issues that have been fixed.
  tests/introspection/ApiPInvokeTest.cs
  tests/linker/ios/link all/DataContractTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12529 [ci] Push .NET 6 packages to dnceng dotnet6 feed
  NuGet.config
  dotnet/package/common.csproj
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: not-notes-worthy

#12534 Enable ENABLE_DOTNET by default in Make.config
  Make.config
Labels: not-notes-worthy

#12575 [ci] Opt in to symbol archiving during VS insertion (#12547)
  msbuild/Makefile
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
  src/Makefile.generator
  src/bgen/bgen.csproj
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: not-notes-worthy

#12565 [release/6.0.1xx-rc.1] Import .NET 6 property page targets path in iOS sdk targets
  dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.targets
Labels: not-notes-worthy, backported

#12564 [AddressBook] Add Support for DotNet Attributes
  src/AddressBook/ABAddressBook.cs
  src/AddressBook/ABGroup.cs
  src/AddressBook/ABMultiValue.cs
  src/AddressBook/ABPerson.cs
  src/AddressBook/ABRecord.cs
  src/AddressBook/ABSource.cs
  src/AddressBookUI/ABAddressFormatting.cs
  src/AddressBookUI/ABNewPersonViewController.cs
  src/AddressBookUI/ABPeoplePickerNavigationController.cs
  src/AddressBookUI/ABPersonViewController.cs
  src/AddressBookUI/ABUnknownPersonViewController.cs
  src/AddressBookUI/DisplayedPropertiesCollection.cs
  src/addressbookui.cs
Labels: dotnet

#12568 [HealthKit] Add Support for DotNet Attributes
  src/HealthKit/EnumsCompat.cs
  src/HealthKit/HKAppleWalkingSteadiness.cs
Labels: dotnet

#12576 [HomeKit] Add Support for DotNet Attributes
  src/HomeKit/HMActionSet.cs
  src/HomeKit/HMCharacteristic.cs
  src/HomeKit/HMEventTrigger.cs
  src/HomeKit/HMHome.cs
Labels: dotnet

#12553 [AudioUnit] Add Support for DotNet Attributes
  src/AudioUnit/AUGraph.cs
  src/AudioUnit/AUParameter.cs
  src/AudioUnit/AudioComponent.cs
  src/AudioUnit/AudioComponentDescription.cs
  src/AudioUnit/AudioUnit.cs
Labels: dotnet

#12567 [ImageIO] Add Support for DotNet Attributes
  src/ImageIO/CGImageAnimation.cs
  src/ImageIO/CGImageDestination.cs
  src/ImageIO/CGImageMetadata.cs
  src/ImageIO/CGImageMetadataTag.cs
  src/ImageIO/CGImageSource.cs
  src/ImageIO/CGImageSource.iOS.cs
  src/ImageIO/CGMutableImageMetadata.cs
Labels: dotnet

#12566 [AudioToolbox] Add Support for DotNet Attributes
  src/AudioToolbox/AudioFile.cs
  src/AudioToolbox/AudioFormat.cs
  src/AudioToolbox/AudioQueue.cs
  src/AudioToolbox/AudioSession.cs
  src/AudioToolbox/AudioToolbox.cs
  src/AudioToolbox/AudioType.cs
  src/AudioToolbox/SystemSound.cs
Labels: dotnet

#12465 [CoreAudio] Updates for Xcode13 Beta 5
  src/AudioUnit/AUEnums.cs
  src/AudioUnit/AudioUnit.cs
  tests/xtro-sharpie/MacCatalyst-CoreAudio.ignore
Labels: note-highlight

#12585 [ci] Authenticode sign Mono.Options.dll
  dotnet/Workloads/SignList.xml
Labels: not-notes-worthy
