Repository dotnet/macios, pull requests merged in 2021-09, with the labels that each got.

#12602 [mailkit] Disable some selector not working on macOS 12 beta 6
  src/mailkit.cs
  tests/xtro-sharpie/macOS-MailKit.ignore
Labels: not-notes-worthy

#12598 [avkit] Fix `VideoCallSupport` category failure on MacCatalyst 15
  src/avkit.cs
  tests/xtro-sharpie/MacCatalyst-AVKit.ignore
Labels: not-notes-worthy

#12535 [LocalAuthenticationEmbeddedUI] Update bindings for Xcode 13.0 beta 2 and 3
  src/frameworks.sources
  src/localauthenticationembeddedui.cs
  tests/xtro-sharpie/MacCatalyst-LocalAuthenticationEmbeddedUI.ignore
  tests/xtro-sharpie/macOS-LocalAuthenticationEmbeddedUI.todo
  tools/common/Frameworks.cs
Labels: note-highlight

#12589 [CoreGraphics] Add support for xcode13 beta 5.
  src/Constants.maccatalyst.cs.in
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGDisplay.cs
  src/CoreGraphics/CGEvent.cs
  src/CoreGraphics/CGEventSource.cs
  src/CoreGraphics/CGEventTypes.cs
  src/CoreGraphics/CGImage.cs
  src/coregraphics.cs
  tests/monotouch-test/CoreGraphics/ColorSpaceTest.cs
  tests/xtro-sharpie/MacCatalyst-CoreGraphics.ignore
  tests/xtro-sharpie/common-CoreGraphics.ignore
  tests/xtro-sharpie/iOS-CoreGraphics.todo
  tests/xtro-sharpie/macOS-CoreGraphics.todo
  tests/xtro-sharpie/tvOS-CoreGraphics.todo
  tests/xtro-sharpie/watchOS-CoreGraphics.todo
Labels: note-highlight

#12578 [SceneKit] Add Support for DotNet Attributes
  src/SceneKit/SCNCompat.cs
  src/SceneKit/SCNJavaScript.cs
  src/SceneKit/SCNPhysicsShape.cs
  src/SceneKit/SCNRenderingOptions.cs
  src/SceneKit/SCNSkinner.cs
Labels: dotnet

#12592 [CoreText] Add Support for DotNet Attributes
  src/CoreText/CTFont.cs
  src/CoreText/CTFontCollection.cs
  src/CoreText/CTFontDescriptor.cs
  src/CoreText/CTFontManager.cs
  src/CoreText/CTFramesetter.cs
  src/CoreText/CTGlyphInfo.cs
  src/CoreText/CTLine.cs
  src/CoreText/CTParagraphStyle.cs
  src/CoreText/CTRun.cs
  src/CoreText/CTStringAttributes.cs
  src/CoreText/CTTypesetter.cs
  src/CoreText/CTTypesetterOptionKeyCompat.cs
Labels: dotnet

#12581 Generate msi files and VS setup authoring for all .NET 6 platforms
  dotnet/Makefile
  dotnet/Workloads/vs-workload.template.props
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: not-notes-worthy

#12606 [release/6.0.1xx-rc.1] Generate msi files and VS setup authoring for all .NET 6 platforms
  dotnet/Makefile
  dotnet/Workloads/vs-workload.template.props
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: not-notes-worthy, backported

#12608 [audiounit] remove duplicate `using System.Runtime.Versioning;` to avoid build warnings
  src/AudioUnit/AudioUnit.cs
Labels: not-notes-worthy

#12609 [chip] Disable some API on macOS
  src/chip.cs
  tests/xtro-sharpie/macOS-CHIP.ignore
Labels: not-notes-worthy

#12593 [FileProvider] Add Support for DotNet Attributes
  src/FileProvider/Compat.cs
  src/FileProvider/Structs.cs
Labels: dotnet

#12603 [Foundation] Add Support for DotNet Attributes
  src/Foundation/NSAttributedString.iOS.cs
  src/Foundation/NSCalendar.cs
  src/Foundation/NSCoder.cs
  src/Foundation/NSExpression.cs
  src/Foundation/NSIndexPath.cs
  src/Foundation/NSItemProvider.cs
  src/Foundation/NSMetadataItem.cs
  src/Foundation/NSUrlSessionConfiguration.cs
  src/Foundation/NSUserDefaults.cs
Labels: dotnet

#12469 [xharness] Unify the list of test projects for .NET between iOS and macOS.
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/TestTasks/RunTestTask.cs
  tests/xharness/TestProject.cs
Labels: not-notes-worthy, run-dotnet-tests

#12570 [msbuild] Make the ParseBundlerArgumentsTaskBase take the verbosity as input as well.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy, run-dotnet-tests

#12642 [xharness] Remove legacy Mac Catalyst support.
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/TestTasks/MacTask.cs
  tests/xharness/Targets/MacCatalystTarget.cs
  tests/xharness/TestProjectExtensions.cs
  tests/xharness/iOSTestProject.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy

#12641 [tests] Remove assert that fails on M1 on Rosetta.
  tests/monotouch-test/CoreFoundation/BundleTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12611 [CoreGraphics] Add Support for DotNet Attributes
  src/CoreGraphics/CGColor.cs
  src/CoreGraphics/CGColorConversionInfo.cs
  src/CoreGraphics/CGColorConverter.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGContext.cs
  src/CoreGraphics/CGContextPDF.cs
  src/CoreGraphics/CGDisplay.cs
  src/CoreGraphics/CGEvent.cs
  src/CoreGraphics/CGImage.cs
  src/CoreGraphics/CGPDFArray.cs
  src/CoreGraphics/CGPDFDocument.cs
  src/CoreGraphics/CGPath.cs
  src/CoreGraphics/CGPdfTagType.cs
  src/CoreGraphics/CGVector.cs
Labels: dotnet

#12617 [AssetsLibrary] Add Support for DotNet Attributes
  src/AssetsLibrary/ALAsset.cs
  src/AssetsLibrary/ALAssetsGroup.cs
Labels: dotnet

#12620 [CoreServices] Add Support for DotNet Attributes
  src/CFNetwork/CFHTTPMessage.cs
  src/CFNetwork/CFHTTPStream.cs
  src/CFNetwork/CFHost.cs
  src/CoreServices/FSEvents.cs
  src/CoreServices/LaunchServices.cs
Labels: dotnet

#12621 [GameplayKit] Add Support for DotNet Attributes
  src/GameplayKit/GKCompat.cs
Labels: dotnet

#12623 [CoreLocation] Add Support for DotNet Attributes
  src/CoreLocation/CoreLocation.cs
Labels: dotnet

#12625 [EventKitUI] Add Support for DotNet Attributes
  src/EventKitUI/EKUIBundle.cs
Labels: dotnet

#12645 [msbuild] Add a public target/property to make customers able to add to the PartialAppManifest item group in their own targets. Fixes #10646.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/common/DotNet.cs
  tests/msbuild/Xamarin.MacDev.Tests/TargetTests/CollectAppManifestsTests.cs
  tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/BuildEngine.cs
Labels: not-notes-worthy, run-dotnet-tests

#12655 [tests] Add test case for making sure we have the right bundle identifier when executing DetectSigningIdentity. Fixes #12051.
  tests/msbuild/Xamarin.MacDev.Tests/TargetTests/DetectSigningIdentityTests.cs
Labels: not-notes-worthy, run-dotnet-tests

#12647 [dotnet] rename $(AppleShortVersion) to $(ApplicationDisplayVersion)
  dotnet/SingleProject.md
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy, run-dotnet-tests

#12651 [foundation] Enable nullability on NSString manual bindings
  src/Foundation/NSString2.cs
Labels: not-notes-worthy

#12619 [CoreSpotlight] Add Support for DotNet Attributes
  src/CoreSpotlight/CSSearchableItemAttributeSet.cs
Labels: dotnet

#12624 [CarPlay] Add Support for DotNet Attributes
  src/CarPlay/CPCompat.cs
Labels: dotnet

#12659 Relax the tvOS special folder checks to make them pass both on dotnet and legacy
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Labels: bug, community, run-dotnet-tests, tests

#12658 Update CryptoTest for .NET 6
  tests/linker/ios/link sdk/CryptoTest.cs
Labels: community, tests

#12660 [dotnet] Enable LLVM by default for release builds. Fixes #12147.
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: not-notes-worthy, run-dotnet-tests

#12626 [xtro] Improve detection of Catalyst missing API by fixing xtro
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/MacCatalyst-AVFoundation.todo
  tests/xtro-sharpie/MacCatalyst-AVKit.todo
  tests/xtro-sharpie/MacCatalyst-Accounts.ignore
  tests/xtro-sharpie/MacCatalyst-AdSupport.ignore
  tests/xtro-sharpie/MacCatalyst-AppKit.ignore
  tests/xtro-sharpie/MacCatalyst-AppKit.todo
  tests/xtro-sharpie/MacCatalyst-AudioToolbox.todo
  tests/xtro-sharpie/MacCatalyst-AuthenticationServices.ignore
  tests/xtro-sharpie/MacCatalyst-CFNetwork.todo
  tests/xtro-sharpie/MacCatalyst-Contacts.ignore
  tests/xtro-sharpie/MacCatalyst-ContactsUI.todo
  tests/xtro-sharpie/MacCatalyst-CoreAnimation.todo
  tests/xtro-sharpie/MacCatalyst-CoreData.ignore
  tests/xtro-sharpie/MacCatalyst-CoreFoundation.ignore
  tests/xtro-sharpie/MacCatalyst-CoreFoundation.todo
  tests/xtro-sharpie/MacCatalyst-CoreGraphics.ignore
  tests/xtro-sharpie/MacCatalyst-CoreImage.todo
  tests/xtro-sharpie/MacCatalyst-CoreMIDI.todo
  tests/xtro-sharpie/MacCatalyst-CoreMotion.ignore
  tests/xtro-sharpie/MacCatalyst-CoreText.todo
  tests/xtro-sharpie/MacCatalyst-CoreVideo.ignore
  tests/xtro-sharpie/MacCatalyst-CoreVideo.todo
  tests/xtro-sharpie/MacCatalyst-CoreWLAN.ignore
  tests/xtro-sharpie/MacCatalyst-CoreWLAN.todo
  tests/xtro-sharpie/MacCatalyst-EventKit.ignore
  tests/xtro-sharpie/MacCatalyst-FileProvider.todo
  tests/xtro-sharpie/MacCatalyst-FileProviderUI.todo
  tests/xtro-sharpie/MacCatalyst-FinderSync.todo
  tests/xtro-sharpie/MacCatalyst-Foundation.ignore
  tests/xtro-sharpie/MacCatalyst-Foundation.todo
  tests/xtro-sharpie/MacCatalyst-GameKit.ignore
  tests/xtro-sharpie/MacCatalyst-HomeKit.ignore
  tests/xtro-sharpie/MacCatalyst-LocalAuthenticationEmbeddedUI.ignore
  tests/xtro-sharpie/MacCatalyst-MailKit.ignore
  tests/xtro-sharpie/MacCatalyst-MediaPlayer.todo
  tests/xtro-sharpie/MacCatalyst-Metal.todo
  tests/xtro-sharpie/MacCatalyst-MetalKit.todo
  tests/xtro-sharpie/MacCatalyst-MetalPerformanceShaders.todo
  tests/xtro-sharpie/MacCatalyst-Network.todo
  tests/xtro-sharpie/MacCatalyst-NetworkExtension.todo
  tests/xtro-sharpie/MacCatalyst-NotificationCenter.todo
  tests/xtro-sharpie/MacCatalyst-Photos.ignore
  tests/xtro-sharpie/MacCatalyst-PhotosUI.ignore
  tests/xtro-sharpie/MacCatalyst-QuickLookThumbnailing.todo
  tests/xtro-sharpie/MacCatalyst-ReplayKit.ignore
  tests/xtro-sharpie/MacCatalyst-SceneKit.ignore
  tests/xtro-sharpie/MacCatalyst-Security.ignore
  tests/xtro-sharpie/MacCatalyst-Security.todo
  tests/xtro-sharpie/MacCatalyst-StoreKit.ignore
  tests/xtro-sharpie/MacCatalyst-SystemConfiguration.ignore
  tests/xtro-sharpie/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/MacCatalyst-UserNotifications.todo
  tests/xtro-sharpie/MacCatalyst-VideoSubscriberAccount.ignore
  tests/xtro-sharpie/MacCatalyst-VideoToolbox.ignore
  tests/xtro-sharpie/MacCatalyst-VideoToolbox.todo
  tests/xtro-sharpie/MacCatalyst-iTunesLibrary.todo
  tests/xtro-sharpie/xtro-sharpie.csproj
Labels: do-not-merge, not-notes-worthy

#12668 [tests] Adjust a few introspection checks to work on iOS 11.4.1
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12667 [link sdk] Ignore XmlSerializationTest.Bug1820_GenericList on device due to a linker bug.
  tests/linker/ios/link sdk/Bug1820Test.cs
Labels: not-notes-worthy, run-dotnet-tests

#12661 [msbuild] Don't require an Info.plist for .NET builds.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/dotnet/MyInterpretedApp/Info.plist
  tests/dotnet/MyInterpretedApp/shared.csproj
  tests/dotnet/MyPartialAppManifestApp/MacCatalyst/Info.plist
  tests/dotnet/MyPartialAppManifestApp/iOS/Info.plist
  tests/dotnet/MyPartialAppManifestApp/macOS/Info.plist
  tests/dotnet/MyPartialAppManifestApp/shared.csproj
  tests/dotnet/MyPartialAppManifestApp/tvOS/Info.plist
  tests/dotnet/MySimpleApp/MacCatalyst/Info.plist
  tests/dotnet/MySimpleApp/iOS/Info.plist
  tests/dotnet/MySimpleApp/macOS/Info.plist
  tests/dotnet/MySimpleApp/shared.csproj
  tests/dotnet/MySimpleApp/tvOS/Info.plist
  tests/dotnet/NativeDynamicLibraryReferencesApp/iOS/Info.plist
  tests/dotnet/NativeDynamicLibraryReferencesApp/macOS/Info.plist
  tests/dotnet/NativeDynamicLibraryReferencesApp/shared.csproj
  tests/dotnet/NativeFileReferencesApp/iOS/Info.plist
  tests/dotnet/NativeFileReferencesApp/macOS/Info.plist
  tests/dotnet/NativeFileReferencesApp/shared.csproj
  tests/dotnet/NativeFrameworkReferencesApp/iOS/Info.plist
  tests/dotnet/NativeFrameworkReferencesApp/macOS/Info.plist
  tests/dotnet/NativeFrameworkReferencesApp/shared.csproj
  tests/dotnet/NativeXCFrameworkReferencesApp/iOS/Info.plist
  tests/dotnet/NativeXCFrameworkReferencesApp/macOS/Info.plist
  tests/dotnet/NativeXCFrameworkReferencesApp/shared.csproj
  tests/dotnet/SimpleAppWithOldReferences/MacCatalyst/Info.plist
  tests/dotnet/SimpleAppWithOldReferences/iOS/Info.plist
  tests/dotnet/SimpleAppWithOldReferences/macOS/Info.plist
  tests/dotnet/SimpleAppWithOldReferences/shared.csproj
  tests/dotnet/SimpleAppWithOldReferences/tvOS/Info.plist
Labels: not-notes-worthy, run-dotnet-tests

#12664 [dotnet-linker] Improve output when we report an error we raised ourselves.
  tools/dotnet-linker/Steps/ConfigurationAwareStep.cs
Labels: not-notes-worthy, run-dotnet-tests

#12656 [msbuild/dotnet] Don't use the built-in publishing logic in .NET to copy frameworks to the app bundle. Fixes #12369.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
  tests/test-libraries/Makefile
  tests/test-libraries/XTest-Info-iphoneos.plist
  tests/test-libraries/XTest-Info-iphonesimulator.plist
  tests/test-libraries/XTest-Info-maccatalyst.plist
  tests/test-libraries/XTest-Info-macos.plist
  tests/test-libraries/XTest-Info-tvos.plist
  tests/test-libraries/XTest-Info-tvsimulator.plist
  tests/test-libraries/XTest-Info-watchos.plist
  tests/test-libraries/XTest-Info-watchsimulator.plist
  tools/dotnet-linker/Steps/ExtractBindingLibrariesStep.cs
Labels: not-notes-worthy, run-dotnet-tests

#12671 Remove IsXcode8
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: community

#12666 [CoreFoundation] The native 'dispatch_queue_create_with_target' function is actually called 'dispatch_queue_create_with_target$V2'.
  src/CoreFoundation/Dispatch.cs
  tests/xtro-sharpie/common-CoreFoundation.ignore
Labels: not-notes-worthy, run-dotnet-tests

#12670 [generator] Small source simplification
  src/generator-attribute-manager.cs
Labels: not-notes-worthy

#12674 [CoreBluetooth] Add Support for DotNet Attributes
  src/CoreBluetooth/AdvertisementDataOptions.cs
  src/CoreBluetooth/CBManager.cs
  src/CoreBluetooth/CBPeer.cs
  src/CoreBluetooth/CBUUID.cs
  src/CoreBluetooth/PeripheralConnectionOptions.cs
Labels: dotnet

#12673 [Photos] Add Support for DotNet Attributes
  src/Photos/PHCompat.cs
Labels: dotnet

#12654 [ARKit] Add Support for DotNet Attributes
  src/ARKit/ARSkeleton.cs
Labels: dotnet

#12615 [CI] Only execute iOS 32b on weekends.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#12680 [CI] Fix 32b stage.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#12627 [CoreVideo] Add Support for DotNet Attributes
  src/CoreVideo/CVBuffer.cs
  src/CoreVideo/CVImageBuffer.cs
  src/CoreVideo/CVMetalTexture.cs
  src/CoreVideo/CVMetalTextureCache.cs
  src/CoreVideo/CVPixelBuffer.cs
  src/CoreVideo/CVPixelBufferAttributes.cs
  src/CoreVideo/CVPixelBufferIOSurface.cs
  src/CoreVideo/CVPixelBufferPool.cs
  src/CoreVideo/CVPixelBufferPoolSettings.cs
  src/CoreVideo/CVPixelFormatDescription.cs
  src/CoreVideo/CVPixelFormatType.cs
  src/CoreVideo/CVTime.cs
  src/CoreVideo/CoreVideo.cs
Labels: dotnet

#12652 [CoreFoundation] Add Support for DotNet Attributes
  src/CoreFoundation/CFStream.cs
  src/CoreFoundation/CFUrl.cs
  src/CoreFoundation/Dispatch.cs
  src/CoreFoundation/DispatchBlock.cs
Labels: dotnet

#12653 [WebKit] Add Support for DotNet Attributes
  src/WebKit/Enums.cs
Labels: dotnet

#12672 [CloudKit] Add Support for DotNet Attributes
  src/CloudKit/CKCompat.cs
Labels: dotnet

#12676 [tests] Fix building fsharplibrary using the makefile.
  tests/fsharplibrary/dotnet/shared.mk
Labels: not-notes-worthy

#12675 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#12678 [CI] In order to support APIScan we need to add the governance checks AFTER the build.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#12610 [XKit] Update for xcode13 beta 5.
  src/Foundation/Enums.cs
  src/xkit.cs
  tests/introspection/ApiSignatureTest.cs
  tests/xtro-sharpie/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/macOS-AppKit.todo
  tests/xtro-sharpie/tvOS-UIKit.todo
Labels: note-highlight

#12691 [tests] Import nunit.framework.targets in more .NET test projects.
  tests/introspection/dotnet/shared.csproj
  tests/linker/ios/dont link/dotnet/shared.csproj
  tests/linker/ios/link all/dotnet/shared.csproj
  tests/linker/ios/link sdk/dotnet/shared.csproj
Labels: not-notes-worthy, run-dotnet-tests

#12690 [tests] Improve makefiles for .NET's dont link test.
  tests/linker/ios/dont link/dotnet/shared.mk
Labels: not-notes-worthy

#12689 [msbuild] Improve E7082 error message.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs
Labels: not-notes-worthy, run-dotnet-tests

#12604 [Metal] Add Support for DotNet Attributes
  src/Metal/Defs.cs
  src/Metal/MTLCompat.cs
  src/Metal/MTLDevice.cs
  src/Metal/MTLRenderCommandEncoder.cs
  src/MetalPerformanceShaders/MPSCnnConvolutionDescriptor.cs
  src/MetalPerformanceShaders/MPSCnnNeuron.cs
  src/MetalPerformanceShaders/MPSCompat.cs
  src/MetalPerformanceShaders/MPSDefs.cs
  src/MetalPerformanceShaders/MPSImageBatch.cs
  src/MetalPerformanceShaders/MPSKernel.cs
  src/MetalPerformanceShaders/MPSNNGraph.cs
  src/MetalPerformanceShaders/MPSStateBatch.cs
Labels: dotnet

#12646 [msbuild] Implement ITaskCallback in ReadAppManifest to tell the remote task execution that any files on Windows shouldn't be copied back to the mac.
  msbuild/Xamarin.MacDev.Tasks/Tasks/ReadAppManifest.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/WriteAppManifest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12701 [msbuild/dotnet] Make 'LinkSdk' the default linker mode for Mac Catalyst when building for Release, and 'None' the default when building for Debug. Fixes #12264.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#12699 [xharness] Skip some device variations for .NET.
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#12697 [tests] Adjust BaseOptimizeGeneratedCodeTest.SetupBlockPerfTest to cope for a slower .NET on tvOS.
  tests/linker/BaseOptimizeGeneratedCodeTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12696 [tests] Add perf test for calling Marshal.AllocHGlobal/FreeHGlobal.
  tests/perftest/ManagedRuntime.cs
  tests/perftest/dotnet/perftest.csproj
Labels: not-notes-worthy

#12257 [CoreVideo] Add support for Xcode 13 beta3.
  src/CoreVideo/CVBuffer.cs
  src/CoreVideo/CVDisplayLink.cs
  src/CoreVideo/CVMetalTexture.cs
  src/CoreVideo/CVMetalTextureCache.cs
  src/corevideo.cs
  tests/monotouch-test/CoreVideo/CVDisplayLinkTest.cs
  tests/xtro-sharpie/MacCatalyst-CoreVideo.todo
  tests/xtro-sharpie/iOS-CoreVideo.todo
  tests/xtro-sharpie/macOS-CoreVideo.ignore
  tests/xtro-sharpie/macOS-CoreVideo.todo
  tests/xtro-sharpie/tvOS-CoreVideo.todo
  tests/xtro-sharpie/watchOS-CoreVideo.todo
Labels: note-highlight

#12711 [tests] Add debug spew to try to track down random test failure in NSMutableDictionary2Test.AddEntries.
  tests/monotouch-test/Foundation/NSMutableDictionary2Test.cs
Labels: not-notes-worthy, run-dotnet-tests

#12622 [CoreMotion] Add Support for DotNet Attributes
  src/CoreMotion/CMDeviceMotion.cs
  src/CoreMotion/CMMagnetometer.cs
Labels: dotnet

#12700 [CoreWlan] Add Support for DotNet Attributes
  src/CoreWlan/CWInterface.cs
Labels: dotnet

#12704 [GameKit] Add Support for DotNet Attributes
  src/GameKit/GKCompat.cs
Labels: dotnet

#12705 [AuthenticationServices] Add Support for DotNet Attributes
  src/AuthenticationServices/PublicPrivateKeyAuthentication.cs
Labels: dotnet

#12716 [MediaToolbox] Add Support for DotNet Attributes
  src/MediaToolbox/MTProfessionalVideoWorkflow.cs
Labels: dotnet

#12719 [NetworkExtension] Add Support for DotNet Attributes
  src/NetworkExtension/NEVpnManager.cs
Labels: dotnet

#12721 [ObjCRuntime] Add Support for DotNet Attributes
  src/ObjCRuntime/PlatformAvailability.cs
Labels: dotnet

#12685 [CoreMedia] Add Support for DotNet Attributes
  src/CoreMedia/CMAttachmentBearer.cs
  src/CoreMedia/CMBlockBuffer.cs
  src/CoreMedia/CMCustomBlockAllocator.cs
  src/CoreMedia/CMFormatDescription.cs
  src/CoreMedia/CMMemoryPool.cs
  src/CoreMedia/CMSampleBuffer.cs
  src/CoreMedia/CMSync.cs
  src/CoreMedia/CMTextMarkupAttributes.cs
  src/CoreMedia/CMTime.cs
  src/CoreMedia/CoreMedia.cs
  src/CoreMedia/ICMAttachmentBearer.cs
Labels: dotnet

#12684 [AppKit] Add Support for DotNet Attributes
  src/AppKit/NSAccessibility.cs
  src/AppKit/NSBezierPath.cs
  src/AppKit/NSButton.cs
  src/AppKit/NSCollectionLayoutAnchor.cs
  src/AppKit/NSCollectionView.cs
  src/AppKit/NSCollectionViewDelegate.cs
  src/AppKit/NSFont.cs
  src/AppKit/NSGraphics.cs
  src/AppKit/NSLayoutManager.cs
  src/AppKit/NSSegmentedControl.cs
  src/AppKit/NSSlider.cs
  src/AppKit/NSTextContainer.cs
  src/AppKit/NSWorkspace.cs
  src/UIKit/NSLayoutManager.cs
  src/XKit/Types.cs
  src/XKit/XKitCompat.cs
Labels: dotnet

#12681 [generator] Use the newer, faster API alternatives when generating CIFilter subclasses
  src/CoreImage/CIFilter.cs
  src/generator-filters.cs
Labels: not-notes-worthy

#12725 Update CODEOWNERS
  CODEOWNERS
Labels: not-notes-worthy

#12683 [Build] Do not show the deprecated warnings.
  .editorconfig
  src/Makefile
Labels: not-notes-worthy

#12702 [AVFoundation] Add Support for DotNet Attributes
  src/AVFoundation/AVAudioConverterPrimeInfo.cs
  src/AVFoundation/AVAudioRecorder.cs
  src/AVFoundation/AVAudioSettings.cs
  src/AVFoundation/AVBeatRange.cs
  src/AVFoundation/AVCaptureConnection.cs
  src/AVFoundation/AVCaptureVideoPreviewLayer.cs
  src/AVFoundation/AVCompat.cs
  src/AVFoundation/AVContentKeyResponse.cs
  src/AVFoundation/AVPlayerItem.cs
  src/AVFoundation/AVPlayerLayer.cs
  src/AVFoundation/AVPlayerViewController.cs
  src/AVFoundation/AVTypes.cs
  src/AVFoundation/AVUrlAssetOptions.cs
  src/AVFoundation/AVVideoSettings.cs
  src/AVFoundation/AudioRendererWasFlushedAutomaticallyEventArgs.cs
  src/AVFoundation/Events.cs
Labels: dotnet

#12686 [QTKit] Add Support for DotNet Attributes
  src/QTKit/QTCompat.cs
Labels: dotnet

#12706 [UIKit] Update bindings to Xcode 13 Beta 5
  src/UIKit/UIEnums.cs
  src/UIKit/UITypes.cs
  src/uikit.cs
  src/xkit.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/monotouch-test/UIKit/UIPointerAccessory.cs
  tests/xtro-sharpie/MacCatalyst-UIKit.ignore
  tests/xtro-sharpie/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/macOS-AppKit.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-UIKit.todo
Labels: note-highlight

#12714 [runtime] Use the correct underlying types for our own nfloat/n(u)int types.
  runtime/bindings.h
Labels: not-notes-worthy, run-dotnet-tests

#12713 [tests] Fix creation of IntPtr to work on a 32-bit system.
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: not-notes-worthy

#12728 Updated Xamarin.Messaging version
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#12729 Updated Xamarin.Messaging version
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#12715 [src] Fix the library for a few P/Invokes.
  src/AudioUnit/AudioUnit.cs
  src/CoreFoundation/CFStream.cs
  src/CoreGraphics/CGFont.cs
  tests/introspection/ApiPInvokeTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12710 [msbuild] Unify the iOS and macOS versions of the CreateBindingResourcePackage task.
  msbuild/Xamarin.Mac.Tasks/Tasks/CreateBindingResourcePackage.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackage.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#12730 [objcruntime] Directly call the `Runtime.TryGetNSObject(IntPtr,bool)`
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy

#12720 [foundation] Allow the optimization of `NSAutoreleasePool` bindings
  src/Foundation/NSAutoreleasePool.cs
Labels: not-notes-worthy

#12528 [dotnet-linker] Remove workaround for a dotnet/runtime issue wrt the AOT compiler.
  tests/dotnet/UnitTests/TestBaseClass.cs
  tools/common/Application.cs
Labels: not-notes-worthy, run-dotnet-tests

#12601 [CoreImage] Update Xcode 13.0 bindings betas 1 and 3
  src/CoreImage/CIFilter.cs
  src/coreimage.cs
  src/generator-filters.cs
  tests/introspection/ApiCoreImageFiltersTest.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/MacCatalyst-CoreImage.todo
  tests/xtro-sharpie/common-CoreImage.ignore
  tests/xtro-sharpie/iOS-CoreImage.todo
  tests/xtro-sharpie/macOS-CoreImage.todo
  tests/xtro-sharpie/tvOS-CoreImage.todo
Labels: note-highlight

#12739 [MMP] If we disable mac do not try to build for dotnet.
  tools/mmp/Makefile
Labels: not-notes-worthy

#12737 [dotnet-linker] Mark protocol interfaces when using the dynamic registrar. Fixes #12644.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/dotnet-linker/MarkIProtocolHandler.cs
Labels: not-notes-worthy, run-dotnet-tests

#12731 [msbuild] Fix parsing extra bundler arguments where a space separates the name and value of the argument.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
Labels: not-notes-worthy, run-dotnet-tests

#12712 [tests] Add .NET makefiles for bindings-test.
  tests/bindings-test/dotnet/MacCatalyst/Makefile
  tests/bindings-test/dotnet/iOS/Makefile
  tests/bindings-test/dotnet/macOS/Makefile
  tests/bindings-test/dotnet/shared.mk
  tests/bindings-test/dotnet/tvOS/Makefile
Labels: not-notes-worthy

#12695 [introspection] Skip VideoToolbox classes in the ApiCMAttachmentTest on tvOS devices.
  tests/introspection/ApiCMAttachmentTest.cs
Labels: not-notes-worthy

#12740 [corefoundation] Optimize `CFArray`
  src/CoreFoundation/CFArray.cs
  tests/perftest/NativeArrayPerf.cs
  tests/perftest/legacy/perftest-legacy.csproj
Labels: not-notes-worthy

#12738 [tests] Fix (a)synchronous F# code.
  tests/common/mac/MacMain.fs
Labels: not-notes-worthy, run-dotnet-tests

#12384 [tests] Add additional test to try to narrow down #xamarin/maccore@2443.
  tests/monotouch-test/Foundation/TimerTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12747 [dotnet] Add Mac Catalyst to the list of versions we list in 'make check-system'.
  Makefile
Labels: not-notes-worthy

#12748 [tests] Relax a few special folder checks for tvOS even more. Fixes #12640.
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12628 [UIKit] Add Support for DotNet Attributes
  src/Foundation/NSLayoutConstraint.cs
  src/UIKit/NSLayoutManager.cs
  src/UIKit/UIAccessibility.cs
  src/UIKit/UIContentSizeCategory.cs
  src/UIKit/UIControl.cs
  src/UIKit/UIEventButtonMaskExtensions.cs
  src/UIKit/UIFont.cs
  src/UIKit/UIFontDescriptor.cs
  src/UIKit/UIGuidedAccessRestriction.cs
  src/UIKit/UIImagePickerController.cs
  src/UIKit/UIKeyboard.cs
  src/UIKit/UIStringAttributes.cs
  src/UIKit/UIStringDrawing.cs
  src/UIKit/UITypes.cs
  src/UIKit/UIVibrancyEffect.cs
  src/UIKit/UIViewController.cs
Labels: dotnet

#12751 [xharness] Don't generate makefiles anymore.
  tests/Makefile
  tests/xharness/Harness.cs
  tests/xharness/MakefileGenerator.cs
  tests/xharness/Program.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy, run-dotnet-tests

#12743 [One .NET] use preview.9 version number
  Make.config
  Make.versions
Labels: not-notes-worthy

#12742 [Xtro] Allow to run xtro with some platforms ignored.
  tests/xtro-sharpie/Makefile
Labels: not-notes-worthy

#12744 [CoreVideo] Add Support for DotNet Attributes - Part 2
  src/CoreVideo/CVBuffer.cs
  src/CoreVideo/CVDisplayLink.cs
Labels: dotnet

#12722 [TVUIKit] Update bindings to Xcode 13 Beta 5
  src/tvuikit.cs
  src/xkit.cs
  tests/xtro-sharpie/tvOS-TVUIKit.todo
Labels: note-highlight

#12759 [tests] Re-generate test[-system].config after .NET bumps.
  tests/Makefile
Labels: not-notes-worthy

#12752 [msbuild/dotnet] Include font files by default in .NET apps, and implement a way to automatically register them. Fixes #12536.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/dotnet/AppWithResources/AppDelegate.cs
  tests/dotnet/AppWithResources/MacCatalyst/AppWithResources.csproj
  tests/dotnet/AppWithResources/MacCatalyst/Makefile
  tests/dotnet/AppWithResources/MacCatalyst/Resources/A.ttc
  tests/dotnet/AppWithResources/MacCatalyst/Resources/B.otf
  tests/dotnet/AppWithResources/MacCatalyst/Resources/C.ttf
  tests/dotnet/AppWithResources/iOS/AppWithResources.csproj
  tests/dotnet/AppWithResources/iOS/Makefile
  tests/dotnet/AppWithResources/iOS/Resources/A.ttc
  tests/dotnet/AppWithResources/iOS/Resources/B.otf
  tests/dotnet/AppWithResources/iOS/Resources/C.ttf
  tests/dotnet/AppWithResources/macOS/AppWithResources.csproj
  tests/dotnet/AppWithResources/macOS/Makefile
  tests/dotnet/AppWithResources/macOS/Resources/A.ttc
  tests/dotnet/AppWithResources/macOS/Resources/B.otf
  tests/dotnet/AppWithResources/macOS/Resources/C.ttf
  tests/dotnet/AppWithResources/shared.csproj
  tests/dotnet/AppWithResources/shared.mk
  tests/dotnet/AppWithResources/tvOS/AppWithResources.csproj
  tests/dotnet/AppWithResources/tvOS/Makefile
  tests/dotnet/AppWithResources/tvOS/Resources/A.ttc
  tests/dotnet/AppWithResources/tvOS/Resources/B.otf
  tests/dotnet/AppWithResources/tvOS/Resources/C.ttf
  tests/dotnet/Makefile
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests

#12762 [tests] Fix warning about unused variable.
  tests/mtouch/Cache.cs
Labels: not-notes-worthy

#12755 [msbuild] Remove the BundleDependentFiles item group, it's not used.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#12757 [msbuild] Simplify some code and remove usage of the 'GeneratedSources' item group, which looks public, but really isn't.
  msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
Labels: not-notes-worthy, run-dotnet-tests

#12766 [msbuild] Add @mauroa as a code owner.
  CODEOWNERS
Labels: not-notes-worthy

#12764 [dotnet] Remove watchOS code and from our .NET support.
  dotnet/DefaultCompilationIncludes.md
  dotnet/Microsoft.watchOS.Sdk/Sdk/AutoImport.props
  dotnet/Microsoft.watchOS.Sdk/Sdk/Sdk.props
  dotnet/Microsoft.watchOS.Sdk/targets/Microsoft.watchOS.Sdk.props
  dotnet/Microsoft.watchOS.Sdk/targets/Microsoft.watchOS.Sdk.targets
  dotnet/package/Microsoft.watchOS.Ref/package.csproj
  dotnet/package/Microsoft.watchOS.Runtime.watchos-arm/package.csproj
  dotnet/package/Microsoft.watchOS.Runtime.watchos-x64/package.csproj
  dotnet/package/Microsoft.watchOS.Runtime.watchos-x86/package.csproj
  dotnet/package/Microsoft.watchOS.Sdk/package.csproj
  tests/dotnet/MyClassLibrary/watchOS/MyClass.cs
  tests/dotnet/MyClassLibrary/watchOS/MyClassLibrary.csproj
  tests/dotnet/MyWatchApp/MyWatchApp.sln
  tests/dotnet/MyWatchApp/MyWatchApp/Entitlements.plist
  tests/dotnet/MyWatchApp/MyWatchApp/Info.plist
  tests/dotnet/MyWatchApp/MyWatchApp/Interface.storyboard
  tests/dotnet/MyWatchApp/MyWatchApp/MyWatchApp.csproj
  tests/dotnet/MyWatchApp/MyWatchApp/Resources/Images.xcassets/AppIcons.appiconset/Contents.json
  tests/dotnet/MyWatchApp/MyWatchApp/Resources/Images.xcassets/AppIcons.appiconset/Icon-24x24@2x.png
  tests/dotnet/MyWatchApp/MyWatchApp/Resources/Images.xcassets/AppIcons.appiconset/Icon-27.5x27.5@2x.png
  tests/dotnet/MyWatchApp/MyWatchApp/Resources/Images.xcassets/AppIcons.appiconset/Icon-29x29@2x.png
  tests/dotnet/MyWatchApp/MyWatchApp/Resources/Images.xcassets/AppIcons.appiconset/Icon-29x29@3x.png
  tests/dotnet/MyWatchApp/MyWatchApp/Resources/Images.xcassets/AppIcons.appiconset/Icon-40x40@2x.png
  tests/dotnet/MyWatchApp/MyWatchApp/Resources/Images.xcassets/AppIcons.appiconset/Icon-86x86@2x.png
  tests/dotnet/MyWatchApp/MyWatchApp/Resources/Images.xcassets/AppIcons.appiconset/Icon-98x98@2x.png
  tests/dotnet/MyWatchApp/MyWatchApp/Resources/Images.xcassets/AppIcons.appiconset/Icon1024x1024.png
  tests/dotnet/MyWatchApp/MyWatchContainer/AppDelegate.cs
  tests/dotnet/MyWatchApp/MyWatchContainer/Entitlements.plist
  tests/dotnet/MyWatchApp/MyWatchContainer/Info.plist
  tests/dotnet/MyWatchApp/MyWatchContainer/Main.cs
  tests/dotnet/MyWatchApp/MyWatchContainer/Main.storyboard
  tests/dotnet/MyWatchApp/MyWatchContainer/MyWatchContainer.csproj
  tests/dotnet/MyWatchApp/MyWatchContainer/Resources/Images.xcassets/AppIcons.appiconset/Contents.json
  tests/dotnet/MyWatchApp/MyWatchContainer/Resources/LaunchScreen.xib
  tests/dotnet/MyWatchApp/MyWatchContainer/ViewController.cs
  tests/dotnet/MyWatchApp/MyWatchContainer/ViewController.designer.cs
  tests/dotnet/MyWatchApp/MyWatchExtension/Entitlements.plist
  tests/dotnet/MyWatchApp/MyWatchExtension/Info.plist
  tests/dotnet/MyWatchApp/MyWatchExtension/InterfaceController.cs
  tests/dotnet/MyWatchApp/MyWatchExtension/InterfaceController.designer.cs
  tests/dotnet/MyWatchApp/MyWatchExtension/MyWatchExtension.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12756 [msbuild] Call the generator using a response file.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/CommandLineArgumentBuilder.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BundlerToolTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
  tests/mmptest/src/BindingProjectTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/BTouchTaskTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12775 [tests] Fix a thread synchronization issue in the generator tests.
  tests/generator/BGenTool.cs
Labels: not-notes-worthy

#12774 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy, run-dotnet-tests

#12758 [dotnet] Enable default compile items for binding projects. Fixes #12532.
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  tests/dotnet/BindingWithDefaultCompileInclude/ApiDefinition.cs
  tests/dotnet/BindingWithDefaultCompileInclude/MacCatalyst/ApiDefinition.cs
  tests/dotnet/BindingWithDefaultCompileInclude/MacCatalyst/BindingWithDefaultCompileInclude.csproj
  tests/dotnet/BindingWithDefaultCompileInclude/MacCatalyst/Makefile
  tests/dotnet/BindingWithDefaultCompileInclude/MacCatalyst/MyClass.cs
  tests/dotnet/BindingWithDefaultCompileInclude/MacCatalyst/StructsAndEnums.cs
  tests/dotnet/BindingWithDefaultCompileInclude/MyClass.cs
  tests/dotnet/BindingWithDefaultCompileInclude/StructsAndEnums.cs
  tests/dotnet/BindingWithDefaultCompileInclude/iOS/ApiDefinition.cs
  tests/dotnet/BindingWithDefaultCompileInclude/iOS/BindingWithDefaultCompileInclude.csproj
  tests/dotnet/BindingWithDefaultCompileInclude/iOS/Makefile
  tests/dotnet/BindingWithDefaultCompileInclude/iOS/MyClass.cs
  tests/dotnet/BindingWithDefaultCompileInclude/iOS/StructsAndEnums.cs
  tests/dotnet/BindingWithDefaultCompileInclude/macOS/ApiDefinition.cs
  tests/dotnet/BindingWithDefaultCompileInclude/macOS/BindingWithDefaultCompileInclude.csproj
  tests/dotnet/BindingWithDefaultCompileInclude/macOS/Makefile
  tests/dotnet/BindingWithDefaultCompileInclude/macOS/MyClass.cs
  tests/dotnet/BindingWithDefaultCompileInclude/macOS/StructsAndEnums.cs
  tests/dotnet/BindingWithDefaultCompileInclude/shared.csproj
  tests/dotnet/BindingWithDefaultCompileInclude/shared.mk
  tests/dotnet/BindingWithDefaultCompileInclude/tvOS/ApiDefinition.cs
  tests/dotnet/BindingWithDefaultCompileInclude/tvOS/BindingWithDefaultCompileInclude.csproj
  tests/dotnet/BindingWithDefaultCompileInclude/tvOS/Makefile
  tests/dotnet/BindingWithDefaultCompileInclude/tvOS/MyClass.cs
  tests/dotnet/BindingWithDefaultCompileInclude/tvOS/StructsAndEnums.cs
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests

#12703 [net6][msbuild] Set SelfContained for AppExtensions sooner to fix publishing
  dotnet/targets/Xamarin.Shared.Sdk.props
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/ExtensionConsumer/AppDelegate.cs
  tests/dotnet/ExtensionConsumer/iOS/ExtensionConsumer.sln
  tests/dotnet/ExtensionConsumer/iOS/Makefile
  tests/dotnet/ExtensionConsumer/iOS/MySimpleApp.csproj
  tests/dotnet/ExtensionConsumer/macOS/ExtensionConsumer.sln
  tests/dotnet/ExtensionConsumer/macOS/Makefile
  tests/dotnet/ExtensionConsumer/macOS/MySimpleApp.csproj
  tests/dotnet/ExtensionConsumer/shared.csproj
  tests/dotnet/ExtensionConsumer/tvOS/ExtensionConsumer.sln
  tests/dotnet/ExtensionConsumer/tvOS/Makefile
  tests/dotnet/ExtensionConsumer/tvOS/MySimpleApp.csproj
  tests/dotnet/ExtensionProject/iOS/Entitlements.plist
  tests/dotnet/ExtensionProject/iOS/ExtensionProject.csproj
  tests/dotnet/ExtensionProject/iOS/ExtensionProject.sln
  tests/dotnet/ExtensionProject/iOS/Info.plist
  tests/dotnet/ExtensionProject/iOS/MainInterface.storyboard
  tests/dotnet/ExtensionProject/iOS/Makefile
  tests/dotnet/ExtensionProject/iOS/ShareViewController.cs
  tests/dotnet/ExtensionProject/iOS/ShareViewController.designer.cs
  tests/dotnet/ExtensionProject/macOS/Entitlements.plist
  tests/dotnet/ExtensionProject/macOS/ExtensionProject.csproj
  tests/dotnet/ExtensionProject/macOS/ExtensionProject.sln
  tests/dotnet/ExtensionProject/macOS/Info.plist
  tests/dotnet/ExtensionProject/macOS/Makefile
  tests/dotnet/ExtensionProject/macOS/ShareViewController.cs
  tests/dotnet/ExtensionProject/macOS/ShareViewController.designer.cs
  tests/dotnet/ExtensionProject/macOS/ShareViewController.xib
  tests/dotnet/ExtensionProject/shared.csproj
  tests/dotnet/ExtensionProject/tvOS/Entitlements.plist
  tests/dotnet/ExtensionProject/tvOS/ExtensionProject.csproj
  tests/dotnet/ExtensionProject/tvOS/ExtensionProject.sln
  tests/dotnet/ExtensionProject/tvOS/Info.plist
  tests/dotnet/ExtensionProject/tvOS/Makefile
  tests/dotnet/ExtensionProject/tvOS/ServiceProvider.cs
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#12745 [Dotnet] Enable the Test to check for Dotnet Attributes
  tests/introspection/ApiAvailabilityTest.cs
Labels: dotnet

#12760 [Xcode13] Bump to xcode 13 rc.
  Make.config
  Make.versions
  Versions-mac.plist.in
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/MergeAppBundleTaskTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/MSBuild-Smoke.cs
  tests/msbuild/Xamarin.MacDev.Tests/RuntimeTests.cs
  tests/msbuild/Xamarin.MacDev.Tests/TargetTests/CollectAppManifestsTests.cs
  tests/msbuild/Xamarin.MacDev.Tests/TargetTests/DetectSigningIdentityTests.cs
  tests/xtro-sharpie/MacCatalyst-AppKit.ignore
  tests/xtro-sharpie/MacCatalyst-CoreData.ignore
  tests/xtro-sharpie/MacCatalyst-CoreWLAN.ignore
  tests/xtro-sharpie/Makefile
  tests/xtro-sharpie/common-AppKit.ignore
  tests/xtro-sharpie/common-AutomaticAssessmentConfiguration.ignore
  tests/xtro-sharpie/common-CoreData.ignore
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/iOS-CoreAnimation.todo
  tests/xtro-sharpie/iOS-GameController.todo
  tests/xtro-sharpie/iOS-Intents.todo
  tests/xtro-sharpie/iOS-Metal.todo
  tests/xtro-sharpie/macOS-AppKit.ignore
  tests/xtro-sharpie/macOS-CoreData.ignore
  tests/xtro-sharpie/macOS-CoreWLAN.ignore
  tests/xtro-sharpie/tvOS-CoreAnimation.todo
  tests/xtro-sharpie/tvOS-GameController.todo
  tests/xtro-sharpie/watchOS-Intents.todo
  tests/xtro-sharpie/watchOS-PassKit.todo
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#12781 [xcode13][Version] Bump Xamarin.iOS version
  Make.versions
Labels: not-notes-worthy

#12782 [main][Version] Bump product versions after Xcode 13 release
  Make.versions
Labels: not-notes-worthy

#9139 Add a parameterless constructor for MTKView
  src/metalkit.cs
Labels: enhancement, not-notes-worthy

#12784 [dotnet] Bump to preview 10.
  Make.config
Labels: not-notes-worthy, run-dotnet-tests

#12780 [xcode13-ios] [Netcore] Remove warning from extra using.
  src/AVFoundation/AVTypes.cs
Labels: not-notes-worthy, backported

#12677 Some Catalyst API annotations and corrections
  src/avfoundation.cs
  src/callkit.cs
  src/fileprovider.cs
  src/iTunesLibrary/Enums.cs
  src/intentsui.cs
  src/pencilkit.cs
  src/pushkit.cs
  src/quicklookthumbnailing.cs
  tests/xtro-sharpie/MacCatalyst-AVFoundation.ignore
  tests/xtro-sharpie/MacCatalyst-CHIP.ignore
  tests/xtro-sharpie/MacCatalyst-CHIP.todo
  tests/xtro-sharpie/MacCatalyst-CallKit.todo
  tests/xtro-sharpie/MacCatalyst-CoreAudioKit.ignore
  tests/xtro-sharpie/MacCatalyst-FileProvider.ignore
  tests/xtro-sharpie/MacCatalyst-FileProvider.todo
  tests/xtro-sharpie/MacCatalyst-IntentsUI.ignore
  tests/xtro-sharpie/MacCatalyst-IntentsUI.todo
  tests/xtro-sharpie/MacCatalyst-PencilKit.todo
Labels: not-notes-worthy

#12795 [Xcode13] Bump to use the stable version.
  Make.config
Labels: not-notes-worthy

#12771 [Intents] Update bindings for Xcode 13.0 betas 1 through 5
  src/Intents/INPerson.cs
  src/foundation.cs
  src/frameworks.sources
  src/intents.cs
  tests/introspection/ApiSelectorTest.cs
  tests/xtro-sharpie/MacCatalyst-Intents.todo
  tests/xtro-sharpie/iOS-Intents.todo
  tests/xtro-sharpie/macOS-Intents.ignore
  tests/xtro-sharpie/macOS-Intents.todo
  tests/xtro-sharpie/tvOS-Intents.todo
  tests/xtro-sharpie/watchOS-Intents.ignore
  tests/xtro-sharpie/watchOS-Intents.todo
Labels: note-highlight

#12792 [runtime/tools] Change the 'xamarin_runtime_libraries' array to contain only the names of the runtime library in question.
  runtime/runtime.m
  tools/common/Target.cs
Labels: not-notes-worthy, run-dotnet-tests

#12791 [dotnet-linker] Check if both static and dynamic libraries from the Mono runtime matches P/Invoke libraries.
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Labels: not-notes-worthy, run-dotnet-tests

#12801 [mlaunch] Make sure to install mlaunch when the 'install' target is executed.
  tools/mlaunch/Makefile
Labels: not-notes-worthy

#12798 [release/6.0.1xx-preview9] [runtime/tools] Change the 'xamarin_runtime_libraries' array to contain only the names of the runtime library in question.
  runtime/runtime.m
  tools/common/Target.cs
Labels: not-notes-worthy, run-dotnet-tests, backported

#12799 [release/6.0.1xx-preview9] [dotnet-linker] Check if both static and dynamic libraries from the Mono runtime matches P/Invoke libraries.
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Labels: not-notes-worthy, run-dotnet-tests, backported

#12797 [Xcode13] Update all already publish frameworks to Xcode13 GA.
  src/AVFoundation/Enums.cs
  src/CoreAnimation/CAStructs.cs
  src/avfoundation.cs
  src/coreanimation.cs
  src/frameworks.sources
  src/gamecontroller.cs
  src/uikit.cs
  tests/monotouch-test/CoreAnimation/CAFrameRateRangeTest.cs
  tests/xtro-sharpie/common-CoreAnimation.ignore
  tests/xtro-sharpie/iOS-AVFoundation.todo
  tests/xtro-sharpie/iOS-CoreAnimation.todo
  tests/xtro-sharpie/iOS-GameController.todo
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-CoreAnimation.todo
  tests/xtro-sharpie/tvOS-GameController.todo
Labels: note-highlight

#12811 Fix CopyDSYMFromMac target to copy *.DSYM to the right path in Windows
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy

#12813 [xcode13-ios] [tools] Keep passing 'direct-icalls' to the AOT compiler for legacy Xamarin. Fixes #12810.
  tools/common/Application.cs
Labels: not-notes-worthy, backported

#12812 [tools] Keep passing 'direct-icalls' to the AOT compiler for legacy Xamarin. Fixes #12810.
  tools/common/Application.cs
Labels: not-notes-worthy, run-dotnet-tests

#12805 [msbuild] Remove dead property (AotScope).
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.props
Labels: not-notes-worthy

#12806 [msbuild] Fix casing for couple of properties to match their other usages.
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#12793 [msbuild] Fix a compiler warning about an unused variable.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
Labels: not-notes-worthy

#12815 [xcode13-ios] Fix CopyDSYMFromMac target to copy *.DSYM to the right path in Windows
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy, backported

#12817 [tests] Build interdependent-binding-projects for macOS now, there's a corresponding macOS Touch.Client project.
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12816 [release/6.0.1xx-preview9] Fix CopyDSYMFromMac target to copy *.DSYM to the right path in Windows
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy, backported

#12804 [msbuild] Make the CompileAppManifestTaskBase.AppManifest property an ITaskItem.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
Labels: not-notes-worthy

#12823 [actions] Skip the label checker for pull requests from 'dotnet-maestro'.
  .github/workflows/label-checker.yml
Labels: not-notes-worthy

#12789 [xcode13-ios] [src] Ignore warning due to obsolete method.
  src/CFNetwork/CFHTTPMessage.cs
Labels: not-notes-worthy, backported

#12818 [msbuild] Share the *CompileTextureAtlas targets between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#12794 [dotnet] Fix an issue where we wouldn't re-link if some files changed.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/BinLog.cs
  tests/dotnet/UnitTests/IncrementalBuildTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests

#12819 [msbuild] Share the OptimizeImage and OptimizePropertyList tasks and targets between iOS and macOS.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/OptimizeImageTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/OptimizeImage.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/OptimizePropertyList.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-dotnet-tests

#12814 [release/6.0.1xx-preview9] [dotnet] Fix an issue where we wouldn't re-link if some files changed.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/BinLog.cs
  tests/dotnet/UnitTests/IncrementalBuildTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests, backported

#12829 [xcode13-ios] [msbuild] Make the CompileAppManifestTaskBase.AppManifest property an ITaskItem.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileAppManifestTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
Labels: not-notes-worthy, backported
