Repository dotnet/macios, pull requests merged in 2021-02, with the labels that each got.

#10551 [CI][VSTS] Re-enable the nuget feed push for the preview.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10550 [VSTS][CI] Fix issues with the internal pool and VSTS git usage.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10553 [tests] Adjust BundledResources.ResourcesTest to pass on Mac Catalyst.
  tests/BundledResources/ResourcesTest.cs
  tests/xharness/Harness.cs
Labels: not-notes-worthy

#10560 [xcode12.4][VSTS][CI] Fix issues with the internal pool and VSTS git usage.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10559 [d16-9][VSTS][CI] Fix issues with the internal pool and VSTS git usage.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10558 [Xcode12.3][VSTS][CI] Fix issues with the internal pool and VSTS git usage.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10556 [tests] Use the 'Apple Developer' code signing key instead of 'iPhone Developer' for framework-test.
  tests/framework-test/iOS/framework-test-ios.csproj
Labels: not-notes-worthy

#10557 [msbuild] Fix computing the frameworks directory for Mac Catalyst.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#10565 [CI][VSTS] Do not step over success statuses in rebuilds.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#10561 [wkwebkit] Add nullability to (generated and manual) bindings
  src/WKWebKit/Defs.cs
  src/WKWebKit/WKCompat.cs
  src/WKWebKit/WKWindowFeatures.cs
  src/wkwebkit.cs
  tests/xtro-sharpie/MacCatalyst-WebKit.todo
  tests/xtro-sharpie/iOS-WebKit.ignore
  tests/xtro-sharpie/macOS-WebKit.ignore
Labels: enhancement

#10566 [d16-9] [CI][VSTS] Do not step over success statuses in rebuilds.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#10552 Bump to .NET 6.0.100-preview.1.21080.4.
  Make.config
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#10564 [src] Fix generating Constants.SdkVersion for Mac Catalyst.
  src/Constants.maccatalyst.cs.in
Labels: not-notes-worthy

#10563 [CI] Sign .NET packages.
  tools/devops/automation/templates/build/build.yml
Labels: build-package, not-notes-worthy

#10547 [coreanimation] Add nullability to (generated and manual) bindings
  src/CoreAnimation/.gitignore
  src/CoreAnimation/CABasicAnimation.cs
  src/CoreAnimation/CACompat.cs
  src/CoreAnimation/CADefs.cs
  src/CoreAnimation/CAEnums.cs
  src/CoreAnimation/CAKeyFrameAnimation.cs
  src/CoreAnimation/CALayer.cs
  src/CoreAnimation/CALayerDelegate.cs
  src/CoreAnimation/CAMediaTimingFunction.cs
  src/CoreAnimation/CAScrollLayer.cs
  src/CoreAnimation/CATextLayer.cs
  src/CoreAnimation/CATransform3D.cs
  src/coreanimation.cs
  tests/xtro-sharpie/MacCatalyst-CoreAnimation.todo
  tests/xtro-sharpie/iOS-CoreAnimation.ignore
  tests/xtro-sharpie/macOS-CoreAnimation.ignore
  tests/xtro-sharpie/tvOS-CoreAnimation.ignore
Labels: enhancement

#10572 [xharness] framework-test is now green on Mac Catalyst
  tests/xharness/Harness.cs
Labels: not-notes-worthy

#10571 [mtouch] Hardcode 'Xamarin.iOS' as an SDK assembly for the linker.
  tools/linker/MonoTouch.Tuner/MonoTouchProfile.cs
Labels: not-notes-worthy

#10570 [src] Add support for generating classes that throw PlatformNotSupportedExceptions in the Xamarin.iOS.dll implementation assembly for Mac Catalyst. Fixes #10213.
  src/Makefile
  src/generate-type-forwarders/Program.cs
  src/generate-type-forwarders/generate-type-forwarders.csproj
Labels: not-notes-worthy

#10568 [xcode12.3] [CI][VSTS] Do not step over success statuses in rebuilds.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#10567 [xcode12.4] [CI][VSTS] Do not step over success statuses in rebuilds.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#10576 [CI][VSTS] Move to sign msi files.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy, skip-all-tests

#10577 [pdfkit] Add nullability to (generated and manual) bindings
  src/ObjCRuntime/ObsoleteConstants.cs
  src/PdfKit/Enums.cs
  src/PdfKit/PdfAnnotation.cs
  src/PdfKit/PdfCompat.cs
  src/PdfKit/PdfKit.cs
  src/generator.cs
  src/pdfkit.cs
  tests/xtro-sharpie/MacCatalyst-PDFKit.todo
  tests/xtro-sharpie/iOS-PDFKit.ignore
  tests/xtro-sharpie/macOS-PDFKit.ignore
Labels: enhancement

#10578 [msbuild/tests] Fix support for XCFrameworks for Mac Catalyst.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveFrameworksBase.cs
  tests/xcframework-test/iOS/xcframework-test-ios.csproj
  tests/xharness/Harness.cs
Labels: not-notes-worthy

#10581 [.NET 6] make sure Run target depends on Build
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#10579 [tests] Make link sdk and link all work on Mac Catalyst.
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/linker/ios/link sdk/OptimizeGeneratedCodeTest.cs
  tests/linker/ios/link sdk/extra-linker-defs-maccatalyst.xml
  tests/xharness/Harness.cs
Labels: not-notes-worthy

#10584 Bump product versions after the one used for 'xcode12.5'
  Make.versions
Labels: not-notes-worthy

#10582 [introspection] Stop hardcoding minimum OS versions.
  src/MediaToolbox/MTAudioProcessingTap.cs
  src/avfoundation.cs
  src/corebluetooth.cs
  src/foundation.cs
  src/generator.cs
  src/uikit.cs
  tests/introspection/ApiAvailabilityTest.cs
  tests/introspection/Mac/introspection-mac.csproj
  tests/introspection/dotnet/iOS/introspection.csproj
  tests/introspection/dotnet/tvOS/introspection.csproj
  tests/introspection/iOS/introspection-ios.csproj
Labels: not-notes-worthy

#10583 [dotnet] Don't use install-location in pkgs.
  dotnet/.gitignore
  dotnet/Makefile
Labels: not-notes-worthy

#10591 [d16-9] [msbuild] Don't try to find frameworks in a directory that doesn't exist.
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
Labels: backported, not-notes-worthy

#10594 [xcode12.5] Bump minimum version of simulators (as required for BigSur)
  Make.config
  src/coreimage.cs
  src/intents.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
Labels: not-notes-worthy

#10595 [classkit] Update for Xcode 12.5 beta 1
  src/classkit.cs
  tests/xtro-sharpie/iOS-ClassKit.todo
  tests/xtro-sharpie/macOS-ClassKit.todo
Labels: notes-mention

#10585 [CI][VSTS]Add support to run the tests in older versions of macOS
  tools/devops/Makefile
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/mac-tests.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/mac/stage.yml
  tools/devops/mac-tests-provisioning.csx.in
Labels: not-notes-worthy

#10596 Bump to .NET 6.0.100-preview.1.21103.13.
  Make.config
Labels: not-notes-worthy

#10599 [main] Update NuGet feed
  NuGet.config
  mk/xamarin.mk
Labels: not-notes-worthy

#10602 [d16-9] Update NuGet feed
  NuGet.config
  mk/xamarin.mk
Labels: not-notes-worthy

#10603 [d16-9] [monotouch-test] Rework big parts of KeyChainTest. Fixes #xamarin/maccore@2365.
  tests/monotouch-test/Security/KeyChainTest.cs
  tests/monotouch-test/Security/RecordTest.cs
Labels: backported, not-notes-worthy

#10598 Default InvariantGlobalization in Xamarin IOS
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: enhancement

#10609 [xcode12.3] [dotnet-linker] Delete unnecessary NuGet.config.
  tools/dotnet-linker/NuGet.config
Labels: backported, not-notes-worthy

#10608 [xcode12.4] [dotnet-linker] Delete unnecessary NuGet.config.
  tools/dotnet-linker/NuGet.config
Labels: backported, not-notes-worthy

#10607 [d16-9] [dotnet-linker] Delete unnecessary NuGet.config.
  tools/dotnet-linker/NuGet.config
Labels: backported, not-notes-worthy

#10606 [d16-9] Merge xcode12.4 into d16-9
  Make.config
  Make.versions
  Versions-ios.plist.in
  tests/xtro-sharpie/iOS-ExposureNotification.ignore
Labels: note-highlight

#10604 [CI] Nugets should not stop the build.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10601 [xcode12.3] Update NuGet feed
  Makefile
  NuGet.config
  jenkins/build.sh
  mk/xamarin.mk
  tests/Makefile
  tests/xharness/Jenkins/TestSelector.cs
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10611 [xcode12.5] Merge d16-9 (after xcode12.4 was merged inside)
  NuGet.config
  Versions-ios.plist.in
  mk/xamarin.mk
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
  tests/monotouch-test/Security/KeyChainTest.cs
  tests/monotouch-test/Security/RecordTest.cs
  tools/dotnet-linker/NuGet.config
Labels: not-notes-worthy

#10597 Use pointer-sized GCHandles everywhere.
  runtime/Delegates.cs.t4
  runtime/delegates.inc.t4
  runtime/delegates.t4
  runtime/mono-runtime.h.t4
  runtime/monotouch-main.m
  runtime/runtime-internal.h
  runtime/runtime.m
  runtime/shared.h
  runtime/shared.m
  runtime/trampolines-arm64.m
  runtime/trampolines-i386.m
  runtime/trampolines-internal.h
  runtime/trampolines-invoke.m
  runtime/trampolines-varargs.m
  runtime/trampolines-x86_64.m
  runtime/trampolines.m
  runtime/xamarin/runtime.h
  runtime/xamarin/trampolines.h
  src/ObjCRuntime/DynamicRegistrar.cs
  src/ObjCRuntime/Method.cs
  src/ObjCRuntime/Registrar.cs
  src/ObjCRuntime/Runtime.cs
  tools/common/StaticRegistrar.cs
  tools/common/Target.cs
Labels: not-notes-worthy

#10612 [coreimage] Add nullability to (generated and manual) bindings
  src/CoreImage/.gitignore
  src/CoreImage/CIColor.cs
  src/CoreImage/CIContext.cs
  src/CoreImage/CIDetector.cs
  src/CoreImage/CIDetectorOptions.cs
  src/CoreImage/CIFilter.cs
  src/CoreImage/CIImage.cs
  src/CoreImage/CIImageInitializationOptions.cs
  src/CoreImage/CIKernel.cs
  src/CoreImage/CISampler.cs
  src/CoreImage/CIVector.cs
  src/CoreImage/Enums.cs
  src/coreimage.cs
  tests/xtro-sharpie/MacCatalyst-CoreImage.todo
  tests/xtro-sharpie/iOS-CoreImage.ignore
  tests/xtro-sharpie/macOS-CoreImage.ignore
  tests/xtro-sharpie/tvOS-CoreImage.ignore
Labels: enhancement

#10600 [xcode12.4] Update NuGet feed
  Makefile
  NuGet.config
  jenkins/build.sh
  mk/xamarin.mk
  tests/Makefile
  tests/xharness/Jenkins/TestSelector.cs
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10614 [msbuild] Unify the AppBundleExtension property definition
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.props
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#10613 [msbuild] Use localized strings in a few more places.
  msbuild/Xamarin.MacDev.Tasks.Core/PlatformFramework.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/EmbedProvisionProfileTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinToolTask.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/GetMlaunchArgumentsTaskBase.cs
Labels: not-notes-worthy

#10619 [tools] There's no AOT implemented for Mac Catalyst yet.
  tools/common/Application.cs
Labels: not-notes-worthy

#10618 [dotnet] Templateify some build logic.
  Make.config
  Make.versions
  builds/Makefile
  dotnet/.gitignore
  dotnet/HIERARCHY.md
  dotnet/Makefile
  dotnet/package/common.csproj
  dotnet/targets/.gitignore
  dotnet/targets/Microsoft.Sdk.Versions.template.props
  dotnet/targets/Xamarin.Shared.Sdk.Versions.template.props
  dotnet/targets/Xamarin.Shared.Sdk.props
  tools/dotnet-linker/Makefile
Labels: not-notes-worthy

#10615 [tools] Stop hardcoding the product name for error messages.
  tools/common/Application.cs
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/Target.mtouch.cs
  tools/mtouch/mtouch.cs
Labels: not-notes-worthy

#10617 [dotnet] Normalize the casing of the 'TargetPlatformIdentifier' value on Mac Catalyst.
  dotnet/targets/Xamarin.Shared.Sdk.TargetFrameworkInference.props
Labels: not-notes-worthy

#10623 [CI][VSTS] Do not run tests if the build fails.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10626 [main] Fix running introspection on iOS 11.4 simulators
  src/coreimage.cs
  src/intents.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
Labels: not-notes-worthy

#10624 [dotnet] Build & publish MacCatalyst packs.
  Make.config
  dotnet/Makefile
  dotnet/Microsoft.MacCatalyst.Sdk/Sdk/AutoImport.props
  dotnet/Microsoft.MacCatalyst.Sdk/Sdk/Sdk.props
  dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.props
  dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.targets
  dotnet/Microsoft.NET.Workload.MacCatalyst/WorkloadManifest.targets
  dotnet/package/Microsoft.MacCatalyst.Ref/package.csproj
  dotnet/package/Microsoft.MacCatalyst.Runtime.maccatalyst-arm64/package.csproj
  dotnet/package/Microsoft.MacCatalyst.Runtime.maccatalyst-x64/package.csproj
  dotnet/package/Microsoft.MacCatalyst.Sdk/package.csproj
  dotnet/package/common.csproj
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/Makefile
Labels: not-notes-worthy

#10621 [msbuild] Unify the _GenerateBundleName targets between Xamarin.iOS and Xamarin.Mac
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/xharness/AppBundleLocator.cs
Labels: not-notes-worthy

#10629 [CI][VSTS] Use the same script as other jobs to clean the macOS bots.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#10632 [xcode12.4] [CI][VSTS] Do not run tests if the build fails.
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#10631 [xcode12.5] [CI][VSTS] Do not run tests if the build fails.
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#10630 [d16-9] [CI][VSTS] Do not run tests if the build fails.
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#10633 [CI][VSTS] Do not run old macOS on PRs.
  tools/devops/automation/templates/mac/stage.yml
Labels: not-notes-worthy

#10634 [main] Merge xcode12.4 into main
  Make.config
  Make.versions
  Makefile
  Versions-ios.plist.in
  tests/Makefile
  tests/xtro-sharpie/iOS-ExposureNotification.ignore
Labels: not-notes-worthy

#10616 [tools] Move logic to validate/initialize DeploymentTarget to shared code.
  tools/common/Application.cs
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy

#10635 [msbuild] Add MSBuild files to the Mac Catalyst SDK pack
  msbuild/Makefile
Labels: not-notes-worthy

#10636 [msbuild] Use '_PlatformName' == 'MacCatalyst' instead of '_IsMacCatalyst'.
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#10625 [dotnet] Disable watchOS.
  Make.config
  tests/common/Configuration.cs
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
Labels: not-notes-worthy

#10638 [dotnet] Execute ReadItemsFromFile remotely
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#10643 [tools] Fix issue with default verbosity.
  tools/common/Driver.cs
Labels: not-notes-worthy

#10642 [tools] Don't throw an exception in Prefix if no platform is set, because it ends up obscuring whatever error was supposed to be shown
  tools/common/ErrorHelper.tools.cs
Labels: not-notes-worthy

#10648 Bump maccore to get mlaunch fix for launching 32-bit watch simulators.
  mk/xamarin.mk
Labels: not-notes-worthy

#10651 [mapkit] Add nullability to (generated and manual) bindings
  src/MapKit/MKCompat.cs
  src/MapKit/MKDirections.cs
  src/MapKit/MKEnums.cs
  src/MapKit/MKFeatureDisplayPriority.cs
  src/MapKit/MKGeodesicPolyline.cs
  src/MapKit/MKLocalSearch.cs
  src/MapKit/MKMapCameraZoomRange.cs
  src/MapKit/MKMapItem.cs
  src/MapKit/MKMultiPoint.cs
  src/MapKit/MKOverlayView.cs
  src/MapKit/MKPointOfInterestFilter.cs
  src/MapKit/MKPolygon.cs
  src/MapKit/MKPolyline.cs
  src/MapKit/MapKit.cs
  src/mapkit.cs
  tests/xtro-sharpie/MacCatalyst-MapKit.todo
  tests/xtro-sharpie/common-MapKit.ignore
  tests/xtro-sharpie/iOS-MapKit.ignore
  tests/xtro-sharpie/macOS-MapKit.ignore
  tests/xtro-sharpie/tvOS-MapKit.ignore
  tests/xtro-sharpie/watchOS-MapKit.ignore
Labels: enhancement

#10650 [xcode12.5] Bump for beta 2
  Make.config
  Versions-ios.plist.in
  tests/introspection/ApiCMAttachmentTest.cs
  tests/xtro-sharpie/iOS-CarPlay.todo
  tests/xtro-sharpie/iOS-Foundation.todo
  tests/xtro-sharpie/iOS-HealthKit.todo
  tests/xtro-sharpie/iOS-ImageIO.todo
  tests/xtro-sharpie/iOS-MLCompute.todo
  tests/xtro-sharpie/iOS-iAd.todo
  tests/xtro-sharpie/macOS-FileProvider.todo
  tests/xtro-sharpie/macOS-Foundation.todo
  tests/xtro-sharpie/macOS-ImageIO.todo
  tests/xtro-sharpie/macOS-MLCompute.todo
  tests/xtro-sharpie/tvOS-AVFoundation.ignore
  tests/xtro-sharpie/tvOS-AVFoundation.todo
  tests/xtro-sharpie/tvOS-Foundation.todo
  tests/xtro-sharpie/tvOS-HomeKit.todo
  tests/xtro-sharpie/tvOS-ImageIO.todo
  tests/xtro-sharpie/tvOS-MLCompute.todo
  tests/xtro-sharpie/watchOS-Foundation.todo
  tests/xtro-sharpie/watchOS-HealthKit.todo
  tests/xtro-sharpie/watchOS-ImageIO.todo
Labels: notes-mention

#10653 [xcode12.4] [mmp] Use the right pkg-config directory.
  tools/mmp/driver.cs
Labels: backported, not-notes-worthy

#10656 [dotnet] Update after the AOT compiler moved location.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#10655 Bump maccore to get mlaunch fix for launching 32-bit watch simulators.
  mk/xamarin.mk
Labels: not-notes-worthy

#10654 [tools] Disable mono_dllmap_insert on Mac Catalyst and macOS for now.
  tools/common/Target.cs
Labels: not-notes-worthy

#10663 [tools] Sprinkle more Mac Catalyst decisions/support
  tools/common/Application.cs
  tools/common/ErrorHelper.tools.cs
  tools/common/Frameworks.cs
  tools/dotnet-linker/Compat.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/Steps/RegistrarStep.cs
Labels: not-notes-worthy

#10662 [msbuild] Add Mac Catalyst support to the CompileNativeCode and LinkNativeCode tasks.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileNativeCodeTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
Labels: not-notes-worthy

#10660 [dotnet-linker] Use dlsym for System.Net.Security and System.Net.Quic.
  tools/common/Application.cs
Labels: not-notes-worthy

#10667 [dotnet] Force the GC mode to be preemptive.
  tools/dotnet-linker/Steps/GenerateMainStep.cs
Labels: not-notes-worthy

#10661 [dotnet-linker] Compute per-assembly linker flags.
  tools/common/Assembly.cs
  tools/dotnet-linker/Steps/GatherFrameworksStep.cs
Labels: not-notes-worthy

#10669 [tools] Add verbose logging for references to native symbols.
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Labels: not-notes-worthy

#10668 [generator] Reduce the number of duplicate availability attributes in generated code
  src/generator-filters.cs
  src/generator.cs
Labels: not-notes-worthy

#10658 [catalyst] Remove some framework that are not available on catalyst
  src/AVFoundation/AVPlayerViewController.cs
  src/MediaPlayer/MPMoviePlayerController.cs
  src/UIKit/UIEnums.cs
  src/UIKit/UIViewController.cs
  src/foundation.cs
  src/frameworks.sources
  tests/monotouch-test/AVKit/PlayerViewControllerTest.cs
  tests/monotouch-test/EventKit/EKUIBundleTest.cs
  tests/monotouch-test/MediaPlayer/MoviePlayerControllerTest.cs
  tests/monotouch-test/MessageUI/MailComposeViewControllerTest.cs
  tests/monotouch-test/MessageUI/MessageComposeViewControllerTest.cs
  tests/monotouch-test/Photos/FetchResultTest.cs
  tests/monotouch-test/UIKit/ViewControllerTest.cs
  tests/monotouch-test/iAd/BannerViewTest.cs
  tests/monotouch-test/iAd/ViewControllerExtensionsTest.cs
  tests/xtro-sharpie/MacCatalyst-AppClip.todo
  tests/xtro-sharpie/MacCatalyst-AssetsLibrary.todo
  tests/xtro-sharpie/MacCatalyst-CoreTelephony.todo
  tests/xtro-sharpie/MacCatalyst-EventKitUI.todo
  tests/xtro-sharpie/MacCatalyst-HealthKitUI.todo
  tests/xtro-sharpie/MacCatalyst-IdentityLookupUI.todo
  tests/xtro-sharpie/MacCatalyst-MessageUI.todo
  tests/xtro-sharpie/MacCatalyst-WatchConnectivity.todo
  tests/xtro-sharpie/MacCatalyst-iAd.todo
Labels: not-notes-worthy

#10677 [main] Get sample tests running again
  .gitignore
  tools/devops/Makefile
  tools/devops/build-samples.csx
  tools/devops/build-samples.yml
  tools/devops/provision-shared.csx
  tools/devops/provision-xcode.csx
  tools/devops/provision-xcode.csx.in
  tools/devops/utils.csx
Labels: not-notes-worthy

#10671 [builds] Download the runtime packs for our platforms.
  Make.config
  builds/.gitignore
  builds/Makefile
  builds/package-download/.gitignore
  builds/package-download/download-packages.proj
Labels: not-notes-worthy

#10670 [builds] Remove debug code.
  builds/Makefile
Labels: not-notes-worthy

#10680 [monotouch-test] Clean up keychain items after test completions.
  tests/monotouch-test/Security/CertificateTest.cs
  tests/monotouch-test/Security/KeyTest.cs
  tests/monotouch-test/Security/RecordTest.cs
Labels: not-notes-worthy

#10681 [CI][VSTS] Take into account timeouts and other errors.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10682 [CI][VSTS] Bring back the API diff from stable
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
Labels: not-notes-worthy

#10688 [CarPlay] Update bindings for Xcode 12 Beta 2
  src/carplay.cs
  tests/xtro-sharpie/iOS-CarPlay.todo
Labels: note-highlight

#10676 Set UseNativeHttpHandler project default
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#10692 [Makefile] Why copy-paste when you can 'make fix-xcode-select'
  Makefile
Labels: not-notes-worthy

#10693 [CI][VSTS] continueOnError is the correct way.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10678 [catalyst] Remove more framework that are not available on catalyst
  src/frameworks.sources
  src/generate-type-forwarders/Program.cs
  tests/monotouch-test/CarPlay/CPMessageListItemTests.cs
  tests/monotouch-test/HealthKit/AnchoredObjectQueryTest.cs
  tests/monotouch-test/HealthKit/CategoryTypeIdentifierTest.cs
  tests/monotouch-test/HealthKit/CdaDocumentSampleTest.cs
  tests/monotouch-test/HealthKit/ErrorTest.cs
  tests/monotouch-test/HealthKit/ObjectTypeTest.cs
  tests/monotouch-test/HealthKit/QuantityTypeIdentifierTest.cs
  tests/monotouch-test/HomeKit/HMMutableSignificantTimeEventTest.cs
  tests/monotouch-test/HomeKit/HMSignificantTimeEventTest.cs
  tests/monotouch-test/Messages/MSMessageTest.cs
  tests/monotouch-test/UIKit/UISpringLoadedInteractionSupportingTest.cs
  tests/xtro-sharpie/MacCatalyst-CarPlay.todo
  tests/xtro-sharpie/MacCatalyst-CoreNFC.todo
  tests/xtro-sharpie/MacCatalyst-HealthKit.todo
  tests/xtro-sharpie/MacCatalyst-HomeKit.todo
  tests/xtro-sharpie/MacCatalyst-IntentsUI.todo
  tests/xtro-sharpie/MacCatalyst-Messages.todo
  tests/xtro-sharpie/MacCatalyst-VisionKit.todo
  tools/linker/MarkNSObjects.cs
Labels: not-notes-worthy

#10696 [xcode12.4][tests] Get samples build tests running again (#10677)
  .gitignore
  tools/devops/Makefile
  tools/devops/build-samples.csx
  tools/devops/build-samples.yml
  tools/devops/provision-shared.csx
  tools/devops/provision-xcode.csx
  tools/devops/provision-xcode.csx.in
  tools/devops/utils.csx
Labels: backported, not-notes-worthy

#10695 [xcode12.5][tests] Get samples build tests running again (#10677)
  .gitignore
  tools/devops/Makefile
  tools/devops/build-samples.csx
  tools/devops/build-samples.yml
  tools/devops/provision-shared.csx
  tools/devops/provision-xcode.csx
  tools/devops/provision-xcode.csx.in
  tools/devops/utils.csx
Labels: backported, not-notes-worthy

#10694 [d16-9][tests] Get samples build tests running again (#10677)
  .gitignore
  tools/devops/Makefile
  tools/devops/build-samples.csx
  tools/devops/build-samples.yml
  tools/devops/provision-shared.csx
  tools/devops/provision-xcode.csx
  tools/devops/provision-xcode.csx.in
  tools/devops/utils.csx
Labels: backported, not-notes-worthy

#10689 [xcode12.5] [CI][VSTS] Bring back the API diff from stable
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
Labels: backported, not-notes-worthy

#10690 [xcode12.4] [CI][VSTS] Bring back the API diff from stable
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
Labels: backported, not-notes-worthy

#10691 [d16-9] [CI][VSTS] Bring back the API diff from stable
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
Labels: backported, not-notes-worthy

#10687 [xcode12.5] [CI][VSTS] Take into account timeouts and other errors.
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#10686 [d16-9] [CI][VSTS] Take into account timeouts and other errors.
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#10685 [xcode12.4] [CI][VSTS] Take into account timeouts and other errors.
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#10675 [dotnet] Moves tasks to the Windows project
  msbuild/ILMerge.Common.targets
  msbuild/ILMerge.targets
  msbuild/Makefile
  msbuild/Messaging/Xamarin.Messaging.Build.Contracts/GetUniversalTypeIdentifierMessage.cs
  msbuild/Messaging/Xamarin.Messaging.Build.Contracts/GetUniversalTypeIdentifierResult.cs
  msbuild/Messaging/Xamarin.Messaging.Build.Contracts/VerifyXcodeVersionMessage.cs
  msbuild/Messaging/Xamarin.Messaging.Build.Contracts/VerifyXcodeVersionResult.cs
  msbuild/Messaging/Xamarin.Messaging.Build.Contracts/Xamarin.Messaging.Build.Contracts.csproj
  msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
  msbuild/Messaging/Xamarin.Messaging/ILMerge.Messaging.targets
  msbuild/Messaging/Xamarin.Messaging/Xamarin.Messaging.csproj
  msbuild/Xamarin.MacDev.Tasks.sln
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Windows/ILMerge.Windows.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Model/DataItem.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Model/DataSet.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/ResolveUniversalTypeIdentifiers.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/VerifyXcodeVersion.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.Messaging.Apple.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Windows.props
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
Labels: not-notes-worthy

#10705 [d16-9] [CI][VSTS] continueOnError is the correct way.
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#10704 [xcode12.5] [CI][VSTS] continueOnError is the correct way.
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#10702 [xcode12.5] [Makefile] Why copy-paste when you can 'make fix-xcode-select'
  Makefile
Labels: backported, not-notes-worthy

#10706 [catalyst][arkit] Remove ARKit framework that is not available on catalyst
  src/frameworks.sources
  src/generate-type-forwarders/Program.cs
  tests/monotouch-test/ARKit/ARAnchorTest.cs
  tests/monotouch-test/ARKit/ARConfigurationTest.cs
  tests/monotouch-test/ARKit/AREnvironmentProbeAnchorTest.cs
  tests/monotouch-test/ARKit/ARFaceGeometryTest.cs
  tests/monotouch-test/ARKit/ARPlaneGeometryTest.cs
  tests/monotouch-test/ARKit/ARPointCloudTest.cs
  tests/monotouch-test/ARKit/ARReferenceObjectTest.cs
  tests/monotouch-test/ARKit/ARSkeleton2DTest.cs
  tests/monotouch-test/ARKit/ARSkeleton3DTest.cs
  tests/monotouch-test/ARKit/ARSkeletonTest.cs
  tests/xtro-sharpie/MacCatalyst-ARKit.todo
Labels: not-notes-worthy

#10710 [dotnet] Fixes Xamarin.Messaging HintPath
  msbuild/Messaging/Xamarin.Messaging.Build.Contracts/Xamarin.Messaging.Build.Contracts.csproj
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
Labels: not-notes-worthy

#10707 [dotnet] Fixes builds for iOS physical devices from Windows
  msbuild/Directory.Build.props
  msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompile.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileNativeCode.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/EmbedProvisionProfile.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/LinkNativeCode.cs
Labels: not-notes-worthy

#10697 [tests] Add makefile target to run the .NET unit tests.
  tests/dotnet/Makefile
Labels: not-notes-worthy

#10713 [tests] Make sampletester greener
  tests/sampletester/Configuration.cs
  tests/sampletester/Samples.cs
Labels: not-notes-worthy

#10672 [tests] Add a .NET/macOS version of monotouch-test.
  tests/monotouch-test/CoreFoundation/BundleTest.cs
  tests/monotouch-test/NetworkExtension/VpnManagerTest.cs
  tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
  tests/monotouch-test/Security/KeyChainTest.cs
  tests/monotouch-test/dotnet/macOS/Info.plist
  tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
  tests/xharness/AppBundleLocator.cs
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/TestTasks/MacExecuteTask.cs
  tests/xharness/Jenkins/TestTasks/MacTask.cs
  tests/xharness/MacFlavorsExtensions.cs
  tests/xharness/MacTestProject.cs
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Labels: not-notes-worthy

#10708 [CI][VSTS] Fix small formatting issue.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#10714 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#10716 [xcode12.5] [tests] Make sampletester greener
  tests/sampletester/Configuration.cs
  tests/sampletester/Samples.cs
Labels: backported, not-notes-worthy

#10717 [xcode12.4] [tests] Make sampletester greener
  tests/sampletester/Configuration.cs
  tests/sampletester/Samples.cs
Labels: backported, not-notes-worthy

#10715 [d16-9] [tests] Make sampletester greener
  tests/sampletester/Configuration.cs
  tests/sampletester/Samples.cs
Labels: backported, not-notes-worthy

#10721 [CoreMedia] Store delegate in static variable to prevent premature garbage collection.
  src/CoreMedia/CMSampleBuffer.cs
Labels: not-notes-worthy

#10701 [bgen] Remove trailing newlines from warning/error messages.
  src/Resources.resx
  src/xlf/Resources.cs.xlf
  src/xlf/Resources.de.xlf
  src/xlf/Resources.es.xlf
  src/xlf/Resources.fr.xlf
  src/xlf/Resources.it.xlf
  src/xlf/Resources.ja.xlf
  src/xlf/Resources.ko.xlf
  src/xlf/Resources.pl.xlf
  src/xlf/Resources.pt-BR.xlf
  src/xlf/Resources.ru.xlf
  src/xlf/Resources.tr.xlf
  src/xlf/Resources.zh-Hans.xlf
  src/xlf/Resources.zh-Hant.xlf
Labels: not-notes-worthy

#10711 [catalyst][addressbookui] Remove AddressBookUI framework that is not available on Catalyst
  src/frameworks.sources
  src/generate-type-forwarders/Program.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/monotouch-test/AddressBook/AddressBookTest.cs
  tests/monotouch-test/AddressBookUI/AddressFormattingTest.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/xtro-sharpie/MacCatalyst-AddressBookUI.todo
Labels: not-notes-worthy

#10729 [Speech] Update bindings for Xcode 12.5 Beta 1
  src/speech.cs
  tests/xtro-sharpie/iOS-Speech.todo
  tests/xtro-sharpie/macOS-Speech.todo
Labels: note-highlight

#10725 [dotnet-linker] Disable Objective-C exception marshalling by default for macOS and Mac Catalyst.
  tools/common/Application.cs
Labels: not-notes-worthy

#10724 [dotnet] Fix the Run target for Mac Catalyst to run the app directly instead of using mlaunch.
  dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.targets
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#10723 [runtime] Build a .NET-specific libxamarin-dotnet[-debug].[a|dylib].
  Make.config
  dotnet/targets/Xamarin.Shared.Sdk.targets
  mk/rules.mk
  runtime/Makefile
  runtime/monotouch-debug.m
  runtime/monotouch-main.m
  tools/common/Target.cs
Labels: not-notes-worthy

#10731 [catalyst] Remove "unknown" API inside existing frameworks
  src/AudioUnit/AudioComponent.cs
  src/GameKit/GameKit.cs
  src/avfoundation.cs
  src/devicecheck.cs
  src/foundation.cs
  tests/monotouch-test/AVFoundation/CaptureDeviceTest.cs
  tests/xtro-sharpie/MacCatalyst-AVFoundation.todo
  tests/xtro-sharpie/MacCatalyst-AddressBook.ignore
  tests/xtro-sharpie/MacCatalyst-AddressBook.todo
  tests/xtro-sharpie/MacCatalyst-AudioToolbox.todo
  tests/xtro-sharpie/MacCatalyst-DeviceCheck.todo
  tests/xtro-sharpie/MacCatalyst-Foundation.ignore
  tests/xtro-sharpie/MacCatalyst-Foundation.todo
  tests/xtro-sharpie/MacCatalyst-GameKit.todo
  tests/xtro-sharpie/MacCatalyst-MetalPerformanceShaders.todo
  tests/xtro-sharpie/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/common-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/common-UIKit.ignore
  tests/xtro-sharpie/iOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/macOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/tvOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
Labels: not-notes-worthy

#10730 [mtouch] Remove the non-catalyst frameworks from mtouch
  tools/common/Frameworks.cs
Labels: not-notes-worthy
