Repository dotnet/macios, pull requests merged in 2021-01, with the labels that each got.

#10345 [CI][VSTS] Ensure that xharness creates an index with the correct uris.
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/packages/build.yml
Labels: not-notes-worthy

#10347 [CI][VSTS] Add the correct mac pkg file name.
  tools/devops/automation/templates/packages/upload-azure.yml
Labels: not-notes-worthy

#10346 [Xcode12.3][VSTS] Move away from Jenkins to VSTS pipelines for xamarin-macios. (#10302)
  .gitignore
  jenkins/Jenkinsfile
  jenkins/build-nugets.sh
  jenkins/build-package.sh
  tools/devops/Makefile
  tools/devops/automation/VSMacVersion.ps1
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/scripts/GitHub.Tests.ps1
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/scripts/MLaunch.Tests.ps1
  tools/devops/automation/scripts/MLaunch.psm1
  tools/devops/automation/scripts/Makefile
  tools/devops/automation/scripts/System.Tests.ps1
  tools/devops/automation/scripts/System.psm1
  tools/devops/automation/scripts/VSTS.Tests.ps1
  tools/devops/automation/scripts/VSTS.psm1
  tools/devops/automation/scripts/bash/build-nugets.sh
  tools/devops/automation/scripts/bash/clean-bot.sh
  tools/devops/automation/scripts/bash/productsign.sh
  tools/devops/automation/templates/agent-pool-selector.yml
  tools/devops/automation/templates/common/download-artifacts.yml
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/common/upload-vsdrops.yml
  tools/devops/automation/templates/common/upload-vsts-tests.yml
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/devices/stage.yml
  tools/devops/automation/templates/governance-checks.yml
  tools/devops/automation/templates/mac-tests.yml
  tools/devops/automation/templates/packages/build.yml
  tools/devops/automation/templates/packages/configure.yml
  tools/devops/automation/templates/packages/download-artifacts.yml
  tools/devops/automation/templates/packages/publish-html.yml
  tools/devops/automation/templates/packages/stage.yml
  tools/devops/automation/templates/packages/upload-azure.yml
  tools/devops/build-provisioning.csx.in
  tools/devops/device-tests-provisioning.csx.in
  tools/devops/provision-brew-packages.csx
  tools/devops/provision-shared.csx
  tools/devops/provision-xcode.csx
  tools/devops/python-dependencies.txt
Labels: not-notes-worthy

#10348 [CI][VSTS] Add the donet 6 pkg as a dependency.
  tools/devops/Makefile
  tools/devops/build-provisioning.csx.in
Labels: not-notes-worthy

#10350 [CI][VSTS] Add comments to PR not only to commits.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#10281 [macos] Handle symlinks in user frameworks
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
  tools/mmp/driver.cs
Labels: bug, macOS

#10357 [d16-9] [CI][VSTS] Add comments to PR not only to commits.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#10352 [Actions] Ensure the new bot is considered.
  .github/workflows/label-checker.yml
Labels: not-notes-worthy

#10349 [CI][VSTS] Add trigger for xcode branches.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#10363 [d16-9] [CI][VSTS] Add trigger for xcode branches.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#10362 [d16-9] [Actions] Ensure the new bot is considered.
  .github/workflows/label-checker.yml
Labels: not-notes-worthy

#10361 [xcode12.3] [Actions] Ensure the new bot is considered.
  .github/workflows/label-checker.yml
Labels: not-notes-worthy

#10358 [xcode12.3] [CI][VSTS] Add comments to PR not only to commits.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#10326 [xharness] Bump the shared library version
  tests/xharness/Xharness.Tests/Xharness.Tests.csproj
  tests/xharness/Xharness.Tests/packages.config
  tests/xharness/xharness.csproj
Labels: not-notes-worthy

#10364 [xcode12.3] Update Xcode to stable 12.3
  Make.config
Labels: not-notes-worthy

#10368 [Actions] Add the user to all branches. Remove monojenkins.
  .github/workflows/label-checker.yml
Labels: not-notes-worthy

#10323 [versions-check.csharp] Improve this script a bit
  versions-check.csharp
Labels: not-notes-worthy

#10303 [msbuild] Remove the old `--rsrc` argument when using `ditto`
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DittoTaskBase.cs
Labels: not-notes-worthy

#10304 [msbuild] Use the existing user framework dSYM when available
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: bug

#10322 [msbuild] Unify the EmbedProvisionProfile and EmbedMobileProvision tasks between iOS and macOS.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/EmbedProvisionProfileTaskBase.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/EmbedProvisionProfileTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/EmbedProvisionProfile.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/EmbedMobileProvisionTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/EmbedMobileProvision.cs
Labels: not-notes-worthy, run-msbuild-tests

#10321 [Security] Fix the underlying integral type for SslCipherSuite for Mac Catalyst.
  src/Security/SecureTransport.cs
Labels: not-notes-worthy

#10372 [builds] Create the cache directory if needed.
  builds/Makefile
Labels: not-notes-worthy

#10309 [msbuild] Always codesign the framework directory, not what's inside
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
Labels: bug

#10230 [Foundation] Break out of the delegate when we have canceled a task. Fixes #9132
  src/Foundation/NSUrlSessionHandler.cs
Labels: build-package, notes-mention

#10373 [xtro] Make it possible to override the sharpie executable.
  tests/xtro-sharpie/Makefile
Labels: not-notes-worthy

#10290 [src] Use PlatformName.MacCatalyst instead of PlatformName.UIKitForMac.
  src/AudioToolbox/AudioFile.cs
  src/AudioToolbox/AudioType.cs
  src/AudioToolbox/Enums.cs
  src/AudioUnit/AudioComponentDescription.cs
  src/LocalAuthentication/LAEnums.cs
  src/ObjCRuntime/PlatformAvailability2.cs
  src/audiounit.cs
  src/authenticationservices.cs
  src/callkit.cs
  src/coreaudiokit.cs
  src/corelocation.cs
  src/identitylookup.cs
  src/identitylookupui.cs
  src/intentsui.cs
  src/mapkit.cs
  src/mediaplayer.cs
  src/passkit.cs
  src/photos.cs
  src/photosui.cs
  src/pushkit.cs
  src/xkit.cs
Labels: not-notes-worthy

#10384 [CI][VSTS] Rename path to fix API diff
  .gitignore
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-azure.yml
Labels: not-notes-worthy

#10383 [CI][VSTS] Add a better title for the comments.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#10360 [CI][VSTS] Add links to the created pkgs.
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#10366 [CI][VSTS] Add required profiles for mac.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#10376 [msbuild] Simplify resolving xcframeworks
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveFrameworksBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ResolveNativeReferencesTaskTest.cs
  tools/mmp/driver.cs
Labels: enhancement

#10386 [UIKit] Add the same UIBarItem.SetTitleTextAttributes overload to Mac Catalyst as iOS has.
  src/UIKit/UIBarItem.cs
Labels: not-notes-worthy

#10387 [src] Build and ship a very simple implementation-only version of OpenTK-1.0.dll for Mac Catalyst.
  src/Makefile
Labels: not-notes-worthy

#10400 [mtouch] Fix embedding Mono (and Xamarin) as frameworks. Fixes #10382
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/Target.mtouch.cs
Labels: not-notes-worthy

#10402 Bump system mono to the latest available 2020-02 package.
  Make.config
Labels: not-notes-worthy

#10398 [CI][VSTS] Clean .xip files.
  tools/devops/automation/scripts/bash/clean-bot.sh
Labels: not-notes-worthy

#10407 [msbuild] Merge the iOS and Mac versions of the DetectSigningIdentity task.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/DetectSigningIdentityTaskCore.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/DetectSigningIdentity.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSigningIdentityTaskCore.cs
  msbuild/Xamarin.iOS.Tasks/Tasks/DetectSigningIdentity.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationIgnore/common-Translations.ignore
Labels: not-notes-worthy

#10414 [dotnet-linker] Link with GSS when building for iOS/Mac Catalyst.
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/ComputeNativeBuildFlagsStep.cs
  tools/dotnet-linker/Steps/DoneStep.cs
Labels: not-notes-worthy

#10385 Use the reference assemblies from the final .NET 5.0 release.
  Make.config
Labels: not-notes-worthy

#10388 Bump to .NET 6.0.100-alpha.1.21060.3.
  Make.config
  mk/quiet.mk
  src/Makefile.generator
  tests/introspection/ApiPInvokeTest.cs
  tests/linker/CommonLinkAllTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/linker/ios/link sdk/dotnet/extra-linker-defs.xml
  tools/common/create-makefile-fragment.sh
  tools/devops/Makefile
  tools/devops/build-provisioning.csx.in
  tools/dotnet-linker/Makefile
Labels: not-notes-worthy

#10419 [monotouch-test] Fix a few issues when running the .NET version of monotouch-test on device.
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
Labels: not-notes-worthy

#10418 [dotnet] Don't AOT compile resource assemblies.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#10409 [macos] Add correct support for producing/archiving `dSYM`
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/ArchiveTaskBase.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/mmptest/src/aot.cs
  tools/mmp/aot.cs
Labels: macOS, note-highlight

#10411 [CI][VSTS] When webservers are rude, retry
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#10431 [CI][VSTS] If comments are too large, provide a gist.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#10425 [monotouch-test] Add a few Xcode version checks to ColorTest and AvoidOccluderConstraintTest.
  tests/monotouch-test/CoreGraphics/ColorTest.cs
  tests/monotouch-test/SceneKit/AvoidOccluderConstraintTest.cs
Labels: not-notes-worthy

#10424 [monotouch-test] Add version checks for new HKCategoryTypeIdentifier fields.
  tests/common/TestRuntime.cs
  tests/monotouch-test/HealthKit/CategoryTypeIdentifierTest.cs
Labels: not-notes-worthy

#10423 [monotouch-test] Change the url for the TestPACParsingScriptNoProxy test to be the Microsoft uri.
  tests/monotouch-test/CoreFoundation/ProxyTest.cs
Labels: not-notes-worthy

#10422 [dotnet] Add default exclusions for recursive patterns to not pick up files in the bin/obj directories.
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
Labels: not-notes-worthy

#10432 [CI][VSTS] The pkg of the tests fail because there is a path not longer found.
  tests/package-mac-tests.sh
Labels: not-notes-worthy

#10435 [monotouch-test] Adjust CaptiveNetworkTest.TryCopyCurrentNetworkInfo to work on iOS 10.3.3
  tests/monotouch-test/SystemConfiguration/CaptiveNetworkTest.cs
Labels: not-notes-worthy

#10426 [tests] Preserve a required method in System.Private.CoreLib to work around a bug in .NET 6.
  tests/monotouch-test/dotnet/extra-linker-defs.xml
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
Labels: not-notes-worthy

#10408 [msbuild] Fix code signing logic for Mac Catalyst.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
Labels: not-notes-worthy

#10378 [msbuild] Don't try to find frameworks in a directory that doesn't exist.
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
Labels: not-notes-worthy

#10428 [msbuild] Fix semi-conflicting options to set codesign timestamp
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.cs.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.de.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.es.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.fr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.it.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ja.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ko.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pl.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.pt-BR.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.ru.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.tr.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hans.xlf
  msbuild/Xamarin.Localization.MSBuild/xlf/MSBStrings.zh-Hant.xlf
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationIgnore/common-Translations.ignore
Labels: not-notes-worthy

#10438 [xharness] Fix warning about unknown file wrt default inclusion.
  tests/xharness/TestProject.cs
Labels: not-notes-worthy

#9862 [dotnet] Remove workaround for mono/linker#1304, which has now been fixed.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#10451 [tests] Don't use the tcp tunnel in the HttpClientHandler tests. Fixes xamarin/maccore#2154.
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#10450 [dotnet] Bump ILLink to get an updated linker reference assembly.
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversionsSubStep.cs
Labels: not-notes-worthy

#10449 [msbuild] Remove duplicate trailing slash from _XamarinBclPath. Fixes #10446.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.TargetFrameworkFix.targets
Labels: bug

#10458 [tests] Ignore a few known failures in link sdk / link all on device with .NET.
  tests/linker/ios/link all/PreserveTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Labels: not-notes-worthy

#10456 [dotnet-linker] Add the RemoveUserResources sub step.
  tests/dotnet/UnitTests/ProjectTest.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/DotNetSubStepDispatcher.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/linker/RemoveUserResourcesSubStep.cs
Labels: not-notes-worthy

#10443 [tools] Do not check the existing of a file before deleting it
  tools/common/Application.cs
  tools/common/Driver.cs
  tools/mtouch/Target.mtouch.cs
Labels: not-notes-worthy

#10460 [tests] Fix reporting exit code for .NET tests.
  tests/common/DotNet.cs
Labels: not-notes-worthy

#10441 [mtouch][mmp] Exclude extraneous framework files from being copied into apps
  tools/common/Application.cs
  tools/common/Target.cs
  tools/mmp/driver.cs
  tools/mtouch/Application.mtouch.cs
Labels: enhancement

#10459 [msbuild] Fix codesign `StampPath`. Fix #10445
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
Labels: bug, regression

#10442 [CI][VSTS] Remove warning from mac tests upload.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10468 [tests] Adjust link all's project file to set properties to their expected values according to the current configuration.
  tests/linker/ios/link all/dotnet/iOS/link all.csproj
Labels: not-notes-worthy

#10455 [d16-9] [msbuild] Remove duplicate trailing slash from _XamarinBclPath. Fixes #10446.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.TargetFrameworkFix.targets
Labels: bug, macOS, regression

#10427 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#10461 [mlaunch] Improve make logic to only install bin/mlaunch if it changed.
  tools/mlaunch/Makefile
Labels: not-notes-worthy

#10466 [dotnet-linker] Delete unnecessary NuGet.config.
  tools/dotnet-linker/NuGet.config
Labels: not-notes-worthy

#10469 [Xharness] Fix the xharness links to work with vsdrops.
  tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
Labels: not-notes-worthy

#10472 [d16-9] [tests] Don't use the tcp tunnel in the HttpClientHandler tests. Fixes xamarin/maccore#2154.
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy, test-only-issue

#10444 [CI][VSTS] Move to ESRP for notarization.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/provision-brew-packages.csx
Labels: build-package, not-notes-worthy

#10478 [msbuild] Remove unused property from DetectSigningIdentityTask.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#10479 [msbuild] Simplify some code in DetectSigningIdentityTask.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
Labels: not-notes-worthy

#10475 [msbuild] Unify how CFBundleName is calculated.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_iOS.cs
Labels: breaking-change, note-highlight

#10481 [VSTS][CI] Add links with the generated pkgs.
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/publish-html.yml
Labels: not-notes-worthy

#10483 [CI][VSTS] Remove ALL .xip
  tools/devops/automation/scripts/bash/clean-bot.sh
Labels: not-notes-worthy

#10486 [CI][VSTS] Ensure that the required simulators are present in the machine
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10487 [CI][VSTS] Continue on profiles failure.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10495 [CI][VSTS] Add a poor mans debugger.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10493 [monotouch-test] Be more descriptive and clean up stuff added to the keychain.
  tests/monotouch-test/Security/CertificateTest.cs
  tests/monotouch-test/Security/KeyTest.cs
Labels: not-notes-worthy

#10494 [CI][VSTS] Fix needed in ESRP landed in the prod feed so we can use it now.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10501 Bump .NET to 6.0.100-alpha.1.21064.27.
  Make.config
Labels: not-notes-worthy

#10509 [xcode12.4] Initial bump to Xcode 12.4 RC
  Make.config
  Make.versions
  Versions-ios.plist.in
  tests/xtro-sharpie/iOS-ExposureNotification.ignore
Labels: note-highlight

#10515 [CI][VSTS] Set to no output vars back to be in the env.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10522 [d16-9] Fix versioning
  Make.versions
Labels: not-notes-worthy

#10521 [main] Bump versions to a post d16-9 world
  Make.versions
Labels: not-notes-worthy

#10518 [xtro] Fix Catalyst support
  tests/xtro-sharpie/MacCatalyst-CoreBluetooth.todo
  tests/xtro-sharpie/MacCatalyst-GameKit.todo
  tests/xtro-sharpie/MacCatalyst-Network.todo
  tests/xtro-sharpie/MacCatalyst-NetworkExtension.todo
  tests/xtro-sharpie/MacCatalyst-SceneKit.todo
  tests/xtro-sharpie/MacCatalyst-SpriteKit.todo
  tests/xtro-sharpie/xtro-report/Reporter.cs
  tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
Labels: not-notes-worthy

#10517 [msbuild] Share more code between XI and XM Archive tasks
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ArchiveTaskBase.cs
Labels: not-notes-worthy

#10516 [CI][VSTS] Do not use ESRP when no pkgs is present or in a PR.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10530 [Actions] Backports should use forks.
  .github/workflows/backport-trigger.yml
Labels: not-notes-worthy

#10532 [Maccore] Bump to pick CI fixes.
  mk/xamarin.mk
Labels: not-notes-worthy

#10533 [coredata] Add nullability to (generated and manual) bindings
  src/CoreData/Enums.cs
  src/CoreData/NSEntityDescription.cs
  src/CoreData/Obsolete.cs
  src/coredata.cs
  tests/xtro-sharpie/MacCatalyst-CoreData.todo
  tests/xtro-sharpie/common-CoreData.ignore
  tests/xtro-sharpie/iOS-CoreData.ignore
  tests/xtro-sharpie/macOS-CoreData.ignore
  tests/xtro-sharpie/tvOS-CoreData.ignore
  tests/xtro-sharpie/watchOS-CoreData.ignore
Labels: enhancement

#10513 [tests] Ignore the MonoTouchFixtures.ObjCRuntime.RegistrarTest.RegistrarRemoval test, it's failing on .NET. Fixes #xamarin/maccore@2380.
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: not-notes-worthy

#10511 [link sdk] Adjust the LinkSdkRegressionTest.SpecialFolder to handle uncertainty whether a directory exists or not on .NET. Fixes #xamarin/maccore@2379.
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
Labels: not-notes-worthy

#10467 [dotnet] Add support for LinkDescription items.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/linker/ios/link sdk/dotnet/iOS/link sdk.csproj
Labels: not-notes-worthy

#10514 [msbuild] Merge the iOS and Mac version of CompileEntitlementsTaskCore.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/CompileEntitlementsTaskCore.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/CompileEntitlements.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileEntitlementsTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileEntitlementsTaskCore.cs
  msbuild/Xamarin.iOS.Tasks/Tasks/CompileEntitlements.cs
Labels: not-notes-worthy

#10535 [CI][VSTS] Use the creds store in git for https.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#10492 [monotouch-test] Rework big parts of KeyChainTest. Fixes #xamarin/maccore@2365.
  tests/monotouch-test/Security/KeyChainTest.cs
  tests/monotouch-test/Security/RecordTest.cs
Labels: not-notes-worthy

#10480 [msbuild] Add a BundleIdentifier property to the XcodeCompilerToolTask.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XcodeCompilerToolTask.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy

#10544 [xcode12.4] Bump to use Xcode 12.4 Stable
  Make.config
Labels: note-highlight

#10545 [dotnet] Add support for some of the single-project MSBuild properties.
  dotnet/SingleProject.md
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSigningIdentityTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  tests/dotnet/MySingleView/Info.plist
  tests/dotnet/MySingleView/MySingleView.csproj
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
Labels: not-notes-worthy

#10549 [CI] Add *.msi files as well to our list of packages we've published.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy
