Repository dotnet/macios, pull requests merged in 2021-11, with the labels that each got.

#13173 [CoreLocation] Updates for Catalyst
  src/corelocation.cs
  tests/xtro-sharpie/MacCatalyst-CoreLocation.todo
Labels: not-notes-worthy

#13192 [xcode13.1] [AVFoundation] Fix intro issues in monterey.
  tests/introspection/Mac/MacApiSelectorTest.cs
Labels: not-notes-worthy, backported

#13187 [AppKit] Fix intro tests on monterey.
  src/appkit.cs
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: not-notes-worthy

#13183 [xcode13.1] [msbuild] Create the directory for the .stamp file for the _CreateBindingResourcePackage target before trying to create the .stamp file.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: bug, backported

#13184 [release/6.0.1xx-preview10] [msbuild] Create the directory for the .stamp file for the _CreateBindingResourcePackage target before trying to create the .stamp file.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: bug, backported

#13199 [Foundation] Updates for Catalyst
  tests/xtro-sharpie/MacCatalyst-Foundation.ignore
  tests/xtro-sharpie/MacCatalyst-Foundation.todo
Labels: not-notes-worthy

#13196 [dotnet] add %(Platform) to any global @(Using)
  dotnet/targets/Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.tvOS.Sdk.ImplicitNamespaceImports.props
Labels: not-notes-worthy

#12899 [xharness] Bump to the latest version of Microsoft.DotNet.XHarness.iOS.Shared (1.0.0-prerelease.21479.1).
  tests/xharness/AppRunner.cs
  tests/xharness/Jenkins/ErrorKnowledgeBase.cs
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/Reports/HtmlReportWriter.cs
  tests/xharness/Jenkins/Reports/MarkdownReportWriter.cs
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
  tests/xharness/Jenkins/TestData.cs
  tests/xharness/Jenkins/TestTasks/ITestTask.cs
  tests/xharness/Jenkins/TestTasks/MSBuild.cs
  tests/xharness/Jenkins/TestTasks/RunSimulator.cs
  tests/xharness/Jenkins/TestTasks/RunTest.cs
  tests/xharness/Jenkins/TestTasks/TestTask.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tests/xharness/SimulatorLoaderFactory.cs
  tests/xharness/TestTargetExtensions.cs
  tests/xharness/Xharness.Tests/Tests/AppRunnerTests.cs
  tests/xharness/Xharness.Tests/Xharness.Tests.csproj
  tests/xharness/xharness.csproj
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#13194 [CVMetalTexture] Subclass NativeObject + numerous other code updates
  src/CoreVideo/CVMetalTexture.cs
  src/CoreVideo/CVMetalTextureCache.cs
Labels: not-notes-worthy

#13186 [SecAccessControl] Subclass NativeObject + a few other code updates
  src/Security/SecAccessControl.cs
Labels: not-notes-worthy

#13180 [CV[Image|Pixel[Buffer] Subclass NativeObject + numerous other code updates
  src/CoreVideo/CVBuffer.cs
  src/CoreVideo/CVImageBuffer.cs
  src/CoreVideo/CVPixelBuffer.cs
Labels: not-notes-worthy

#13158 [CGImageSource] Subclass NativeObject + numerous other code updates
  src/ImageIO/CGImageSource.cs
  src/ImageIO/CGImageSource.iOS.cs
Labels: not-notes-worthy

#13151 [PrintCore] Subclass NativeObject + numerous other code updates
  src/PrintCore/PrintCore.cs
Labels: not-notes-worthy

#13150 [CGFont] Subclass NativeObject + numerous other code updates
  src/CoreGraphics/CGFont.cs
Labels: not-notes-worthy

#13149 [SecIdentity] Subclass NativeObject + numerous other code updates
  src/Security/Certificate.cs
  src/Security/SecIdentity.cs
  src/Security/Trust.cs
  tests/introspection/ApiCMAttachmentTest.cs
  tests/monotouch-test/Security/IdentityTest.cs
Labels: not-notes-worthy

#13193 [CVDisplayLink] Subclass NativeObject + numerous other code updates
  src/CoreVideo/CVDisplayLink.cs
Labels: not-notes-worthy

#13202 [xcode13.1] [CoreLocation] Updates for Catalyst
  src/corelocation.cs
  tests/xtro-sharpie/MacCatalyst-CoreLocation.todo
Labels: not-notes-worthy, backported

#13206 [xcode13.1] [AppKit] Fix intro tests on monterey.
  src/appkit.cs
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: not-notes-worthy, backported

#13203 [xcode13.1] [CoreML] Updates for Catalyst
  tests/xtro-sharpie/MacCatalyst-CoreML.ignore
Labels: not-notes-worthy, backported

#13200 [QuickLook] Add missing selectors for Xcode 13.1
  src/quicklook.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/xtro-sharpie/MacCatalyst-QuickLook.ignore
  tests/xtro-sharpie/iOS-QuickLook.todo
Labels: note-highlight

#13198 [PdfKit] Add missing enum.
  src/PdfKit/Enums.cs
  tests/xtro-sharpie/MacCatalyst-PDFKit.todo
  tests/xtro-sharpie/iOS-PDFKit.todo
  tests/xtro-sharpie/macOS-PDFKit.todo
Labels: note-highlight

#13190 [MTAudioProcessingTap] Subclass NativeObject + numerous other code updates
  src/MediaToolbox/MTAudioProcessingTap.cs
Labels: not-notes-worthy

#13189 [CVPixelBufferPool] Subclass NativeObject + numerous other code updates
  src/CoreVideo/CVPixelBufferPool.cs
Labels: not-notes-worthy

#13188 [NEVpnManager/NEHotspotEapSettings] Enable nullability.
  src/NetworkExtension/NEHotspotEapSettings.cs
  src/NetworkExtension/NEVpnManager.cs
Labels: not-notes-worthy

#13172 [CFUrl] Subclass NativeObject + numerous other code updates
  src/CFNetwork/CFHTTPStream.cs
  src/CoreFoundation/CFUrl.cs
Labels: not-notes-worthy

#13207 [xcode13.1] [Foundation] Updates for Catalyst
  tests/xtro-sharpie/MacCatalyst-Foundation.ignore
  tests/xtro-sharpie/MacCatalyst-Foundation.todo
Labels: not-notes-worthy, backported

#13209 [xcode13.1] [PdfKit] Add missing enum.
  src/PdfKit/Enums.cs
  tests/xtro-sharpie/MacCatalyst-PDFKit.todo
  tests/xtro-sharpie/iOS-PDFKit.todo
  tests/xtro-sharpie/macOS-PDFKit.todo
Labels: note-highlight, backported

#13165 [CFRunLoop] Subclass NativeObject + numerous other code updates
  src/CoreFoundation/CFProxySupport.cs
  src/CoreFoundation/CFRunLoop.cs
  src/CoreFoundation/CFSocket.cs
  src/Foundation/NSUrlSessionHandler.cs
Labels: not-notes-worthy

#13191 [Certificate] Subclass NativeObject + numerous other code updates
  src/Security/Certificate.cs
Labels: not-notes-worthy

#13211 [CVMetalTextureCache] Subclass NativeObject + numerous other code updates
  src/CoreVideo/CVMetalTextureCache.cs
Labels: not-notes-worthy

#13210 Fix Nullability
  src/CoreGraphics/CGPath.cs
Labels: not-notes-worthy

#13208 [xcode13.1] [QuickLook] Add missing selectors for Xcode 13.1
  src/quicklook.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/xtro-sharpie/MacCatalyst-QuickLook.ignore
  tests/xtro-sharpie/iOS-QuickLook.todo
Labels: note-highlight, backported

#13230 [CTTypeSetter] Subclass NativeObject + numerous other code updates
  src/CoreText/CTTypesetter.cs
Labels: not-notes-worthy

#13229 [CTTextTab] Subclass NativeObject + numerous other code updates
  src/CoreText/CTTextTab.cs
Labels: not-notes-worthy

#13225 [CTRun] Subclass NativeObject + numerous other code updates
  src/CoreText/CTRun.cs
Labels: not-notes-worthy

#13219 [CTFrame] Subclass NativeObject + numerous other code updates
  src/CoreText/CTFrame.cs
Labels: not-notes-worthy

#13218 [CGPDFScanner] Subclass NativeObject + numerous other code updates
  src/CoreGraphics/CGPDFScanner.cs
Labels: not-notes-worthy

#13217 [CGPDFPage] Subclass NativeObject + numerous other code updates
  src/CoreGraphics/CGPDFDocument.cs
  src/CoreGraphics/CGPDFPage-2.cs
  src/CoreGraphics/CGPDFPage.cs
Labels: not-notes-worthy

#13215 [CGPDFOperatorTable] Subclass NativeObject + numerous other code updates
  src/CoreGraphics/CGPDFOperatorTable.cs
Labels: not-notes-worthy

#13223 [CTLine] Subclass NativeObject + numerous other code updates
  src/CoreText/CTLine.cs
Labels: not-notes-worthy

#13212 [CG[Mutable]ImageMetadata] Subclass NativeObject + numerous other code updates
  src/ImageIO/CGImageMetadata.cs
  src/ImageIO/CGMutableImageMetadata.cs
Labels: not-notes-worthy

#13213 [CGContextPDF] Enable nullability + a few other code updates
  src/CoreGraphics/CGContextPDF.cs
Labels: not-notes-worthy

#13216 [CGPDFString] Enable nullability + a few other code updates
  src/CoreGraphics/CGPDFString.cs
Labels: not-notes-worthy

#13220 [CTFontDescriptor] Subclass NativeObject + numerous other code updates
  src/CoreText/CTFontDescriptor.cs
Labels: not-notes-worthy

#13221 [CTFontCollection] Subclass NativeObject + numerous other code updates
  src/CoreText/CTFontCollection.cs
Labels: not-notes-worthy

#13222 [CTGlyphInfo] Subclass NativeObject + numerous other code updates
  src/CoreText/CTGlyphInfo.cs
Labels: not-notes-worthy

#13226 [CTParagraphStyle] Subclass NativeObject + numerous other code updates
  src/CoreText/CTParagraphStyle.cs
Labels: not-notes-worthy

#13224 [QTKit] Remove the QTKit framework from .NET.
  src/Foundation/NSObject.mac.cs
  src/QTKit/QTCompat.cs
  src/generator.cs
  tools/common/Frameworks.cs
  tools/common/StaticRegistrar.cs
  tools/common/Target.cs
  tools/linker/ObjCExtensions.cs
Labels: not-notes-worthy, run-dotnet-tests

#13214 [CGPDFDocument] Subclass NativeObject + numerous other code updates
  src/CoreGraphics/CGPDFDocument.cs
  src/CoreGraphics/CGPDFPage-2.cs
Labels: not-notes-worthy

#13233 [Tests] Remove not needed usings in the Foundation tests.
  tests/monotouch-test/Foundation/BlockOperationTest.cs
  tests/monotouch-test/Foundation/CachedUrlResponseTest.cs
  tests/monotouch-test/Foundation/CoderTest.cs
  tests/monotouch-test/Foundation/DateFormatterTest.cs
  tests/monotouch-test/Foundation/DateTest.cs
  tests/monotouch-test/Foundation/DecimalNumberTest.cs
  tests/monotouch-test/Foundation/DecimalTest.cs
  tests/monotouch-test/Foundation/EncodingDetectionOptionsTest.cs
  tests/monotouch-test/Foundation/NSCharacterSetTest.cs
  tests/monotouch-test/Foundation/NSDateComponentsTest.cs
  tests/monotouch-test/Foundation/NSLinguisticAnalysisTest.cs
  tests/monotouch-test/Foundation/NSLocaleTest.cs
  tests/monotouch-test/Foundation/NSStreamTest.cs
  tests/monotouch-test/Foundation/NSStringTest.cs
  tests/monotouch-test/Foundation/NSUrlSessionConfiguration.cs
  tests/monotouch-test/Foundation/ProtocolAttributeTest.cs
  tests/monotouch-test/Foundation/RegularExpressionTest.cs
  tests/monotouch-test/Foundation/ThreadTest.cs
  tests/monotouch-test/Foundation/TimerTest.cs
  tests/monotouch-test/Foundation/UbiquitousKeyValueStoreTest.cs
  tests/monotouch-test/Foundation/UrlConnectionTest.cs
  tests/monotouch-test/Foundation/UrlCredentialTest.cs
  tests/monotouch-test/Foundation/UrlSessionTaskTransactionMetricsTest.cs
Labels: not-notes-worthy

#13235 [Tests] Remove not needed usings in the AudioUnit tests.
  tests/monotouch-test/AudioUnit/AudioUnitTest.cs
  tests/monotouch-test/AudioUnit/ExtAudioFileTest.cs
Labels: not-notes-worthy

#13234 [Tests] Remove not needed usings in the AudioToolbox tests.
  tests/monotouch-test/AudioToolbox/AudioBalanceFadeTest.cs
  tests/monotouch-test/AudioToolbox/AudioChannelLayoutTest.cs
  tests/monotouch-test/AudioToolbox/AudioFileGlobalInfoTest.cs
  tests/monotouch-test/AudioToolbox/AudioFileStreamTest.cs
  tests/monotouch-test/AudioToolbox/AudioFileTest.cs
  tests/monotouch-test/AudioToolbox/AudioFormatTest.cs
  tests/monotouch-test/AudioToolbox/AudioQueueTest.cs
  tests/monotouch-test/AudioToolbox/AudioSessionTest.cs
  tests/monotouch-test/AudioToolbox/AudioStreamBasicDescriptionTest.cs
  tests/monotouch-test/AudioToolbox/FourCCTest.cs
  tests/monotouch-test/AudioToolbox/SoundBankTest.cs
  tests/monotouch-test/AudioToolbox/SystemSoundTest.cs
Labels: not-notes-worthy

#13232 [Tests] Remove not needed usings in the Network tests.
  tests/monotouch-test/Network/NWBrowserDescriptorTest.cs
  tests/monotouch-test/Network/NWBrowserTest.cs
  tests/monotouch-test/Network/NWConnectionGroupTest.cs
  tests/monotouch-test/Network/NWConnectionTest.cs
  tests/monotouch-test/Network/NWEstablishmentReportTest.cs
  tests/monotouch-test/Network/NWFramerMessageTest.cs
  tests/monotouch-test/Network/NWIPProtocolMetadataTest.cs
  tests/monotouch-test/Network/NWListenerTest.cs
  tests/monotouch-test/Network/NWMulticastGroupTest.cs
  tests/monotouch-test/Network/NWParametersTest.cs
  tests/monotouch-test/Network/NWPathMonitorTest.cs
  tests/monotouch-test/Network/NWPathTest.cs
  tests/monotouch-test/Network/NWProtocolDefinitionTest.cs
  tests/monotouch-test/Network/NWProtocolIPOptionsTest.cs
  tests/monotouch-test/Network/NWProtocolMetadataTest.cs
  tests/monotouch-test/Network/NWProtocolStackTest.cs
  tests/monotouch-test/Network/NWProtocolTcpOptionsTest.cs
  tests/monotouch-test/Network/NWProtocolTlsOptionsTest.cs
  tests/monotouch-test/Network/NWProtocolUdpOptionsTest.cs
  tests/monotouch-test/Network/NWTxtRecordTest.cs
  tests/monotouch-test/Network/NWWebSocketMetadataTest.cs
  tests/monotouch-test/Network/NWWebSocketOptionsTest.cs
Labels: not-notes-worthy

#13239 [CTFrameSetter] Subclass NativeObject + numerous other code updates
  src/CoreText/CTFrame.cs
  src/CoreText/CTFramesetter.cs
Labels: not-notes-worthy

#13247 [Tests] Remove not needed usings in the AVFoundation tests.
  tests/monotouch-test/AVFoundation/AVAssetDownloadUrlSessionTests.cs
  tests/monotouch-test/AVFoundation/AVAssetImageGeneratorTest.cs
  tests/monotouch-test/AVFoundation/AVAudioConverterPrimeInfoTest.cs
  tests/monotouch-test/AVFoundation/AVAudioFormatTest.cs
  tests/monotouch-test/AVFoundation/AVBeatRangeTest.cs
  tests/monotouch-test/AVFoundation/AVCaptureWhiteBalanceGainsTest.cs
  tests/monotouch-test/AVFoundation/AVDepthDataTests.cs
  tests/monotouch-test/AVFoundation/AVPlayerLooperTest.cs
  tests/monotouch-test/AVFoundation/AudioPlayerTest.cs
  tests/monotouch-test/AVFoundation/AudioRecorderTest.cs
  tests/monotouch-test/AVFoundation/CaptureDeviceTest.cs
  tests/monotouch-test/AVFoundation/CaptureMetadataOutputTest.cs
  tests/monotouch-test/AVFoundation/FourCCTest.cs
  tests/monotouch-test/AVFoundation/MetadataObjectTest.cs
  tests/monotouch-test/AVFoundation/PlayerItemTest.cs
  tests/monotouch-test/AVFoundation/QueuePlayerTest.cs
  tests/monotouch-test/AVFoundation/SpeechSynthesisVoiceTest.cs
  tests/monotouch-test/AVFoundation/UtilitiesTest.cs
  tests/monotouch-test/AVFoundation/VideoCompositionInstructionTest.cs
Labels: not-notes-worthy

#13248 [Tests] Remove not needed usings in the BGTasks tests.
  tests/monotouch-test/BackgroundTasks/BGTaskSchedulerTest.cs
Labels: not-notes-worthy

#13251 [Tests] Remove not needed usings in the CoreAnimation tests.
  tests/monotouch-test/CoreAnimation/EmitterBehaviorTest.cs
  tests/monotouch-test/CoreAnimation/LayerTest.cs
  tests/monotouch-test/CoreAnimation/MediaTimingFunctionTest.cs
  tests/monotouch-test/CoreAnimation/ShapeLayerTest.cs
  tests/monotouch-test/CoreAnimation/TransactionTest.cs
Labels: not-notes-worthy

#13249 [Tests] Remove not needed usings in the Compression tests.
  tests/monotouch-test/Compression/CompressionStreamTest.cs
  tests/monotouch-test/Compression/ThoroughCompressionStreamTest.cs
Labels: not-notes-worthy

#13250 [Tests] Remove not needed usings in the Contacts tests.
  tests/monotouch-test/Contacts/ContactFormatterTest.cs
  tests/monotouch-test/Contacts/ContactStoreTest.cs
  tests/monotouch-test/Contacts/ContactTest.cs
  tests/monotouch-test/Contacts/ContactVCardSerializationTest.cs
  tests/monotouch-test/Contacts/MutableContactTest.cs
Labels: not-notes-worthy

#13254 [Tests] Remove not needed usings in the CoreData and CoreFoundation tests
  tests/api-shared/CoreFoundation/CFNotificationCenterTest.cs
  tests/monotouch-test/CoreData/NSQueryGenerationTokenTest.cs
  tests/monotouch-test/CoreFoundation/ArrayTest.cs
  tests/monotouch-test/CoreFoundation/DispatchBlockTests.cs
  tests/monotouch-test/CoreFoundation/DispatchDataTest.cs
  tests/monotouch-test/CoreFoundation/DispatchGroupTest.cs
  tests/monotouch-test/CoreFoundation/DispatchQueueTest.cs
  tests/monotouch-test/CoreFoundation/DispatchTests.cs
  tests/monotouch-test/CoreFoundation/NotificationCenterTest.cs
  tests/monotouch-test/CoreFoundation/OSLogTest.cs
Labels: not-notes-worthy

#13252 [Tests] Remove not needed usings in the CoreBluetooth and CoreAudioKit tests.
  tests/monotouch-test/CoreAudioKit/AUViewController.cs
  tests/monotouch-test/CoreBluetooth/ErrorTest.cs
  tests/monotouch-test/CoreBluetooth/PeerTest.cs
Labels: not-notes-worthy

#13246 [NaturalLanguage] Remove wrong XAMCORE_4_0 code.
  src/naturallanguage.cs
Labels: not-notes-worthy

#13255 [Tests] Remove not needed usings in the CoreGraphics tests.
  tests/monotouch-test/CoreGraphics/AffineTransformTest.cs
  tests/monotouch-test/CoreGraphics/BitmapContextTest.cs
  tests/monotouch-test/CoreGraphics/CGImageTest.cs
  tests/monotouch-test/CoreGraphics/ColorConversionInfoTest.cs
  tests/monotouch-test/CoreGraphics/ColorTest.cs
  tests/monotouch-test/CoreGraphics/ContextTest.cs
  tests/monotouch-test/CoreGraphics/DataConsumerTest.cs
  tests/monotouch-test/CoreGraphics/FontTest.cs
  tests/monotouch-test/CoreGraphics/FunctionTest.cs
  tests/monotouch-test/CoreGraphics/GeometryTest.cs
  tests/monotouch-test/CoreGraphics/PDFContextTest.cs
  tests/monotouch-test/CoreGraphics/PDFInfoTest.cs
  tests/monotouch-test/CoreGraphics/PathTest.cs
  tests/monotouch-test/CoreGraphics/PatternTest.cs
  tests/monotouch-test/CoreGraphics/RectTest.cs
Labels: not-notes-worthy

#13256 [Tests] Remove not needed usings in the CoreImage & CoreLocation tests.
  tests/monotouch-test/CoreImage/CIKernelTests.cs
  tests/monotouch-test/CoreImage/DetectorTest.cs
  tests/monotouch-test/CoreImage/FilterTest.cs
  tests/monotouch-test/CoreLocation/BeaconRegionTest.cs
  tests/monotouch-test/CoreLocation/LocationManagerTest.cs
Labels: not-notes-worthy

#13227 [CoreAnimation] Add support for Xcode 13.1 rc.
  src/CoreAnimation/CAFrameRateRange.cs
  src/coreanimation.cs
  src/frameworks.sources
  tests/monotouch-test/CoreAnimation/CAFrameRateRangeTest.cs
  tests/xtro-sharpie/MacCatalyst-CoreAnimation.todo
  tests/xtro-sharpie/iOS-CoreAnimation.todo
  tests/xtro-sharpie/macOS-CoreAnimation.todo
  tests/xtro-sharpie/tvOS-CoreAnimation.todo
Labels: note-highlight

#13231 [ObjCRuntime] Add a non-deprecated internal system-version checking API and use it everywhere.
  src/AddressBook/ABAddressBook.cs
  src/CoreBluetooth/CBManager.cs
  src/CoreLocation/CLLocationManager.cs
  src/CoreMedia/CMSync.cs
  src/CoreVideo/CVBuffer.cs
  src/Foundation/NSAttributedString.iOS.cs
  src/GameKit/GKScore.cs
  src/IOSurface/IOSurfacePropertyKey.cs
  src/Intents/INBillTypeResolutionResult.cs
  src/Intents/INCallRecordTypeResolutionResult.cs
  src/Intents/INCarAirCirculationModeResolutionResult.cs
  src/Intents/INCarAudioSourceResolutionResult.cs
  src/Intents/INCarDefrosterResolutionResult.cs
  src/Intents/INCarSeatResolutionResult.cs
  src/Intents/INCarSignalOptionsResolutionResult.cs
  src/Intents/INMessageAttributeOptionsResolutionResult.cs
  src/Intents/INMessageAttributeResolutionResult.cs
  src/Intents/INPaymentStatusResolutionResult.cs
  src/Intents/INRadioTypeResolutionResult.cs
  src/Intents/INRelativeReferenceResolutionResult.cs
  src/Intents/INRelativeSettingResolutionResult.cs
  src/Intents/INSaveProfileInCarIntent.cs
  src/Intents/INSetProfileInCarIntent.cs
  src/Intents/INSpeakableString.cs
  src/Intents/INWorkoutGoalUnitTypeResolutionResult.cs
  src/Intents/INWorkoutLocationTypeResolutionResult.cs
  src/MetricKit/MXMetaData.cs
  src/MetricKit/MXMetric.cs
  src/MetricKit/MXMetricPayload.cs
  src/ObjCRuntime/PlatformAvailability.cs
  src/ObjCRuntime/SystemVersion.cs
  src/Security/Items.cs
  src/SpriteKit/SKUniform.cs
  src/SpriteKit/SKVideoNode.cs
  src/TVMLKit/TVViewElement.cs
  src/UIKit/UIDocumentBrowserViewController.cs
  src/UIKit/UIScreen.cs
  src/WKWebKit/WKCompat.cs
  src/WKWebKit/WKPreferences.cs
  src/frameworks.sources
  tests/introspection/ApiTypoTest.cs
  tests/introspection/Mac/MacApiTypoTest.cs
  tests/monotouch-test/AppKit/NSFont.cs
  tests/monotouch-test/MonoMac/CBUUID.cs
  tests/monotouch-test/ObjCRuntime/DelegateAndDataSourceTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13240 [CGImageMetadataTag] Subclass NativeObject + numerous other code updates
  src/ImageIO/CGImageMetadataTag.cs
  tests/monotouch-test/ImageIO/ImageMetadataTagTest.cs
Labels: not-notes-worthy

#13257 [AudioBuffers] Enable nullability + a few other fixes.
  src/AudioToolbox/AudioBuffers.cs
Labels: not-notes-worthy

#13258 [AudioConverter] Enable nullability + a few other code updates
  src/AudioToolbox/AudioConverter.cs
Labels: not-notes-worthy

#13264 [AudioFile] Enable nullability + a few other code updates
  src/AudioToolbox/AudioFile.cs
Labels: not-notes-worthy

#13271 [Xtro] Fix xtro after a bad commit.
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: not-notes-worthy

#13265 [MusicPlayer] Enable nullability + a few other code updates
  src/AudioToolbox/MusicPlayer.cs
Labels: not-notes-worthy

#13266 [Security/Authorization] Enable nullability + a few other code updates
  src/Security/Authorization.cs
Labels: not-notes-worthy

#13270 [xcode13.1] [CoreAnimation] Add support for Xcode 13.1 rc.
  src/CoreAnimation/CAFrameRateRange.cs
  src/coreanimation.cs
  src/frameworks.sources
  tests/monotouch-test/CoreAnimation/CAFrameRateRangeTest.cs
  tests/xtro-sharpie/MacCatalyst-CoreAnimation.todo
  tests/xtro-sharpie/iOS-CoreAnimation.todo
  tests/xtro-sharpie/macOS-CoreAnimation.todo
  tests/xtro-sharpie/tvOS-CoreAnimation.todo
Labels: note-highlight, backported

#13253 [CGPDFObject] Make CGPDFObject a subclass of CGPDF[Array|Dictionary|Stream] + a few other fixes.
  src/CoreGraphics/CGPDFArray.cs
  src/CoreGraphics/CGPDFDictionary.cs
  src/CoreGraphics/CGPDFObject.cs
  src/CoreGraphics/CGPDFStream.cs
  tests/monotouch-test/CoreGraphics/PDFArrayTest.cs
  tests/monotouch-test/CoreGraphics/PDFObjectTest.cs
Labels: not-notes-worthy

#13259 [CI] Use a vimage for 10.15 since we do not have actual bots.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/mac/stage.yml
Labels: not-notes-worthy

#13267 [AppKit] Fix a few enums for .NET according to current AppKit headers.
  src/AppKit/Enums.cs
Labels: not-notes-worthy, run-dotnet-tests, breaking-changes

#13283 [xcode13.1] [Xtro] Fix xtro after a bad commit.
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: not-notes-worthy, backported

#13282 [Dlfcn] Enable nullability and fix code accordingly.
  src/AddressBook/ABAddressBook.cs
  src/CoreText/CTFontCollection.cs
  src/CoreText/CTFontDescriptor.cs
  src/CoreText/CTFrame.cs
  src/CoreText/CTTextTab.cs
  src/CoreVideo/CVPixelFormatDescription.cs
  src/ObjCRuntime/Dlfcn.cs
  src/generator.cs
Labels: not-notes-worthy

#13269 [iAd] Remove this framework from .NET.
  src/Makefile
  src/Makefile.generator
  src/frameworks.sources
  src/iAd/ADCompat.cs
  src/iAd/iAd.cs
  src/iad.cs
  tools/common/Frameworks.cs
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy, run-dotnet-tests, breaking-changes

#13243 [AppKit/Foundation/UIKit] Use Foundation.NSWritingDirection instead of UIKit.UITextWritingDirection and AppKit.NSWritingDirection for .NET. Fixes #6573.
  src/AppKit/Enums.cs
  src/UIKit/UIEnums.cs
  src/uikit.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: not-notes-worthy, run-dotnet-tests, breaking-changes

#13287 [AppKit] Remove NSEventSubtype from Mac Catalyst.
  src/AppKit/Enums.cs
Labels: not-notes-worthy

#13278 [AudioUnit] Enable nullability + a few other code updates
  src/AudioUnit/AudioUnit.cs
  src/ObjCRuntime/INativeObject.cs
Labels: not-notes-worthy

#13274 [CoreLocation] CLProximity exists in macOS now, so remove the XAMCORE_4_0 condition to remove it.
  src/corelocation.cs
Labels: not-notes-worthy

#13288 [AudioToolbox] AudioConverter.FillComplexBuffer doesn't return a nullable value.
  src/AudioToolbox/AudioConverter.cs
Labels: not-notes-worthy

#13268 [StoreKit] Remove unsupported SKAdNetwork code from .NET.
  src/StoreKit/SKAdNetworkCompat.cs
Labels: not-notes-worthy, run-dotnet-tests, breaking-changes

#13272 [MusicTrack] Enable nullability + a few other code updates
  src/AudioToolbox/MusicTrack.cs
Labels: not-notes-worthy, run-dotnet-tests, breaking-changes

#13273 [MusicSequence] Enable nullability + a few other code updates
  src/AudioToolbox/MusicSequence.cs
Labels: not-notes-worthy

#13275 [SystemSound] Enable nullability + a few other code updates
  src/AudioToolbox/SystemSound.cs
Labels: not-notes-worthy

#13277 [AUGraph] Enable nullability + a few other code updates
  src/AudioToolbox/MusicSequence.cs
  src/AudioUnit/AUGraph.cs
Labels: not-notes-worthy

#13279 [INativeObject] Enable nullability and fix a few issues.
  src/ObjCRuntime/INativeObject.cs
  src/generator.cs
Labels: not-notes-worthy

#13304 [AudioToolbox] Fix nullability issue to fix broken build.
  src/AudioToolbox/MusicTrack.cs
Labels: not-notes-worthy

#13281 [Class] Enable nullability + fix a few code updates.
  src/ObjCRuntime/Class.cs
  src/ObjCRuntime/Runtime.cs
  src/gameplaykit.cs
  src/uikit.cs
Labels: not-notes-worthy

#13292 [api-diff] Bump to latest stable (xcode13.1 branch) + add support for different reference api urls for legacy iOS and Mac.
  Make.config
  README.md
  tools/apidiff/Makefile
Labels: not-notes-worthy

#13295 [.NET/SystemConfiguration] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] for the managed callbacks called from native code.
  src/SystemConfiguration/NetworkReachability.cs
Labels: not-notes-worthy

#13296 [.NET/Security] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] for the managed callbacks called from native code.
  src/Makefile
  src/Security/SslConnection.cs
  src/Security/SslContext.cs
Labels: not-notes-worthy

#13297 [mtouch/mmp] Fix code to report a warning, not only create it.
  tools/common/Application.cs
Labels: not-notes-worthy

#13298 [src] Generate a .NET-specific version of Constants.<platform>.generated.cs.
  src/Makefile
  src/generate-frameworks-constants/Program.cs
  src/generate-frameworks-constants/generate-frameworks-constants.csproj
Labels: not-notes-worthy

#13299 [WatchKit] Remove the WatchKit framework from iOS in .NET.
  src/WatchKit/WKDefs.cs
  src/WatchKit/iOS/WKAccessibility.cs
  src/WatchKit/iOS/WKAccessibilityImageRegion.cs
  src/WatchKit/iOS/WKErrorCode.cs
  src/WatchKit/iOS/WKImageAnimatable.cs
  src/WatchKit/iOS/WKInterfaceButton.cs
  src/WatchKit/iOS/WKInterfaceController.cs
  src/WatchKit/iOS/WKInterfaceDate.cs
  src/WatchKit/iOS/WKInterfaceDevice.cs
  src/WatchKit/iOS/WKInterfaceGroup.cs
  src/WatchKit/iOS/WKInterfaceImage.cs
  src/WatchKit/iOS/WKInterfaceLabel.cs
  src/WatchKit/iOS/WKInterfaceMap.cs
  src/WatchKit/iOS/WKInterfaceMapPinColor.cs
  src/WatchKit/iOS/WKInterfaceObject.cs
  src/WatchKit/iOS/WKInterfaceSeparator.cs
  src/WatchKit/iOS/WKInterfaceSlider.cs
  src/WatchKit/iOS/WKInterfaceSwitch.cs
  src/WatchKit/iOS/WKInterfaceTable.cs
  src/WatchKit/iOS/WKInterfaceTimer.cs
  src/WatchKit/iOS/WKMenuItemIcon.cs
  src/WatchKit/iOS/WKTextInputMode.cs
  src/WatchKit/iOS/WKUserNotificationInterfaceController.cs
  src/WatchKit/iOS/WKUserNotificationInterfaceType.cs
  src/frameworks.sources
  src/watchkit.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/ApiFrameworkTest.cs
  tools/common/Frameworks.cs
  tools/common/StaticRegistrar.cs
  tools/common/Target.cs
Labels: not-notes-worthy, dotnet, breaking-changes

#13286 [CI] Request min version for device tests in the host os.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/devices/stage.yml
Labels: not-notes-worthy

#13305 [generator] Dispose of the universe when done with it.
  src/btouch.cs
Labels: not-notes-worthy

#13293 [CoreBluetooth] Use new availability attributes and remove API that isn't in Apple's headers from .NET.
  src/CoreBluetooth/CBCompat.cs
  src/CoreBluetooth/CBPeer.cs
  src/CoreBluetooth/CoreBluetooth.cs
  src/CoreBluetooth/Enums.cs
  src/CoreBluetooth/GuidWrapper.cs
  src/corebluetooth.cs
  tests/monotouch-test/CoreBluetooth/CentralManagerTest.cs
Labels: not-notes-worthy, dotnet-breaking-changes

#13307 [Security] Remove the SslCipherSuite enum from .NET. Fixes #11498.
  src/Security/SecProtocolMetadata.cs
  src/Security/SecProtocolOptions.cs
  src/Security/SecureTransport.cs
  src/Security/SslContext.cs
  src/foundation.cs
  tests/monotouch-test/Security/SecProtocolMetadataTest.cs
  tests/monotouch-test/Security/SecureTransportTest.cs
Labels: not-notes-worthy, dotnet-breaking-changes

#13306 [CGPath] Fix leak when creating mutable CGPaths. Fixes #11339.
  src/CoreGraphics/CGPath.cs
Labels: bug

#13284 [CI] Use images for older macOS.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#13285 [CI] Do not set the stage to failure on mac tests fails.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#13311 [CI] Download all the artifacts based on a triggered build.
  tools/devops/automation/publish-pr-html-results.yml
  tools/devops/automation/vs-insertion.yml
Labels: not-notes-worthy

#13312 [xcode13.1] [CGBitmapContext] Call the correct base constructor to specify ownership. Fixes #13309.
  src/CoreGraphics/CGBitmapContext.cs
Labels: bug, regression, backported

#13313 [CI] Provide the stage that does the different steps to prepare for an insertion.
  tools/devops/automation/vs-insertion.yml
Labels: not-notes-worthy

#13318 [tests] Fix checking for sub-test failures in packaged macOS tests.
  tests/packaged-macos-tests.mk
Labels: not-notes-worthy

#13317 [tests] Fix macOS 10.15+ version check for Mac Catalyst to actually work.
  tests/packaged-macos-tests.mk
Labels: not-notes-worthy

#13320 [DictionaryContainer] Improve nullability + a few other code improvements.
  src/Foundation/DictionaryContainer.cs
Labels: not-notes-worthy

#13326 [CI] Remove 10.13 tests
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#13324 [SystemSound] Don't implement the INativeObject interface for .NET.
  src/AudioToolbox/SystemSound.cs
  tests/monotouch-test/AudioToolbox/SystemSoundTest.cs
Labels: breaking-change, not-notes-worthy, dotnet

#13316 [src] Introduce DisposableObject and use it.
  src/AudioToolbox/AudioConverter.cs
  src/AudioToolbox/AudioFile.cs
  src/AudioToolbox/MusicPlayer.cs
  src/AudioToolbox/MusicSequence.cs
  src/AudioToolbox/MusicTrack.cs
  src/AudioUnit/AUGraph.cs
  src/AudioUnit/AudioComponent.cs
  src/AudioUnit/AudioUnit.cs
  src/CoreFoundation/NativeObject.cs
  src/Darwin/SystemLog.cs
  src/ObjCRuntime/DisposableObject.cs
  src/Security/Authorization.cs
  src/frameworks.sources
Labels: not-notes-worthy

#13323 [NSMutableData] Enable nullability + a few other code updates
  src/Foundation/NSMutableData.cs
Labels: not-notes-worthy

#13322 [NSZone] Enable nullability + a few other code updates
  src/Foundation/NSZone.cs
Labels: not-notes-worthy

#13321 [CoreNFC] Incorporate XAMCORE_4_0 changes into .NET.
  src/corenfc.cs
Labels: breaking-change, not-notes-worthy, dotnet

#13329 [CoreServices] Fix FSEventStream to properly pass the managed context to the FSEventStreamCreate method. Fixes #13325.
  src/CoreServices/FSEvents.cs
  tests/monotouch-test/CoreServices/FSEventStreamTest.cs
Labels: bug

#13330 [xcode13.1] [CoreServices] Fix FSEventStream to properly pass the managed context to the FSEventStreamCreate method. Fixes #13325.
  src/CoreServices/FSEvents.cs
  tests/monotouch-test/CoreServices/FSEventStreamTest.cs
Labels: bug, backported

#13332 [src] Change all usages of old-style availability attributes to new-style availability attributes.
  src/accounts.cs
  src/addressbookui.cs
  src/appkit.cs
  src/assetslibrary.cs
  src/avfoundation.cs
  src/coredata.cs
  src/corelocation.cs
  src/coremotion.cs
  src/corewlan.cs
  src/eventkit.cs
  src/foundation.cs
  src/gamekit.cs
  src/healthkit.cs
  src/homekit.cs
  src/intents.cs
  src/localauthentication.cs
  src/mapkit.cs
  src/mediaplayer.cs
  src/metal.cs
  src/passkit.cs
  src/photos.cs
  src/replaykit.cs
  src/scenekit.cs
  src/security.cs
  src/storekit.cs
  src/twitter.cs
  src/uikit.cs
  src/webkit.cs
  src/wkwebkit.cs
  src/xkit.cs
Labels: not-notes-worthy

#13334 [CI] Do not try to find the minor version until a bug is fixed.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#13327 [mtouch/mmp/dotnet-bundler] Rework getting the availability attributes so that it works for .NET as well.
  src/ObjCRuntime/DynamicRegistrar.cs
  src/ObjCRuntime/Registrar.cs
  tests/common/BundlerTool.cs
  tests/common/Profile.cs
  tests/common/Tool.cs
  tests/mtouch/MTouchTool.cs
  tests/mtouch/RegistrarTest.cs
  tests/mtouch/mtouchtests.csproj
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#13335 [ARKit/SoundAnalysis] Fix BindAs attribute for .NET
  src/arkit.cs
  src/soundanalysis.cs
Labels: breaking-change, not-notes-worthy, dotnet

#13339 [NSData] Enable nullability + a few other code updates
  src/AddressBook/ABPerson.cs
  src/Foundation/NSData.cs
  src/Security/Trust.cs
Labels: not-notes-worthy

#13338 [compare-commits] Ignore *.binlog files when creating a diff of the generated files.
  tools/compare-commits.sh
Labels: not-notes-worthy

#13336 [src] Use 'csc -refout' to generate reference assemblies instead of mono-cil-strip.
  src/Makefile
Labels: not-notes-worthy

#13314 [GLKit] GLKTextureLoaderGrayscaleAsAlpha was available starting in macOS 10.14
  src/glkit.cs
Labels: not-notes-worthy

#13315 [introspection] Fix macOS 10.15 version checks.
  tests/introspection/Mac/MacApiCtorInitTest.cs
Labels: not-notes-worthy

#13310 [CGBitmapContext] Call the correct base constructor to specify ownership. Fixes #13309.
  src/CoreGraphics/CGBitmapContext.cs
Labels: bug, regression

#13331 [DisposableObject] Fix typo in comment.
  src/ObjCRuntime/DisposableObject.cs
Labels: not-notes-worthy

#13341 [devops] Add a 30/60 minute timeout to the steps to install dependencies + run macOS tests.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#13345 [CI] Remove a OS check not longer needed after the bots have been updated.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#13344 [SystemLog] Enable nullability + a few other fixes.
  src/Darwin/SystemLog.cs
Labels: not-notes-worthy

#13343 [mtouch] Fix logic to determine whether we're using Mono.framework on watchOS.
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy

#13342 [msbuild/dotnet] Build the Xamarin.PreBuilt.iOS app bundle.
  dotnet/Makefile
  dotnet/targets/WorkloadManifest.iOS.template.json
  msbuild/Makefile
  msbuild/Xamarin.HotRestart.PreBuilt/.gitignore
  msbuild/Xamarin.HotRestart.PreBuilt/Makefile
  msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Info.plist
  msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj
Labels: not-notes-worthy

#13349 [EmbeddedResources] Add helper makefiles for .NET testing.
  tests/EmbeddedResources/dotnet/MacCatalyst/Makefile
  tests/EmbeddedResources/dotnet/iOS/Makefile
  tests/EmbeddedResources/dotnet/macOS/Makefile
  tests/EmbeddedResources/dotnet/shared.mk
  tests/EmbeddedResources/dotnet/tvOS/Makefile
Labels: not-notes-worthy

#13348 [introspection] Remove a few version checks which are now constant values.
  tests/common/mac/Mac.cs
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/introspection/Mac/MacApiFieldTest.cs
Labels: not-notes-worthy

#13333 [tools] HomeKit was added to Mac Catalyst in 14.0, so mark it as such.
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tools/common/Frameworks.cs
Labels: not-notes-worthy

#13357 [tests] Create a binlog for the mtouch tests
  tests/mtouch/Makefile
Labels: not-notes-worthy

#13362 [tests] Don't import nunit.frameworks.target more than once.
  tests/fsharp/dotnet/shared.fsproj
  tests/interdependent-binding-projects/dotnet/shared.csproj
  tests/introspection/dotnet/shared.csproj
  tests/linker/ios/dont link/dotnet/shared.csproj
  tests/linker/ios/link all/dotnet/shared.csproj
  tests/linker/ios/link sdk/dotnet/shared.csproj
  tests/monotouch-test/dotnet/shared.csproj
  tests/xcframework-test/dotnet/shared.csproj
Labels: not-notes-worthy, run-dotnet-tests

#13360 [tests] Automatically run/exit tests executed from the command line.
  tests/common/shared-dotnet.mk
Labels: not-notes-worthy

#13351 [tests] Add the compiler response files from src/ to the .NET test builds.
  tests/common/shared-dotnet.csproj
  tests/monotouch-test/Photos/FetchResultTest.cs
  tests/monotouch-test/UIKit/VibrancyEffectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13371 [AVFoundation] Adjust availability attribute for AVCaptureStillImageOutput.HighResolutionStillImageOutputEnabled.
  src/avfoundation.cs
Labels: not-notes-worthy

#13375 [tests] Remove a few unused make variables.
  tests/Makefile
Labels: not-notes-worthy

#13376 [CI] Move the signature to ESRP
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
Labels: not-notes-worthy

#13361 [mtouch] Remove duplicated source file from project file.
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#13367 Updated Messaging and Hot Restart versions
  msbuild/Directory.Build.props
  msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj
Labels: not-notes-worthy

#13381 [CoreAnimation] Make CAGradientLayer.CreateColor private in .NET.
  src/CoreAnimation/CADefs.cs
Labels: not-notes-worthy, run-dotnet-tests

#13372 [CoreWlan] remove some old API from .NET
  src/corewlan.cs
Labels: not-notes-worthy
