Repository dotnet/macios, pull requests merged in 2021-04, with the labels that each got.

#11060 [CI] Run the dotnet tests by default ONLY on main.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#11058 [d16-9] [CI] Fix pool selector
  Make.config
  tools/devops/automation/templates/agent-pool-selector.yml
Labels: backported, not-notes-worthy

#11057 [xcode12.5] [CI] Fix pool selector
  Make.config
  tools/devops/automation/templates/agent-pool-selector.yml
Labels: backported, not-notes-worthy

#11068 [CI] Fwd labels and ensure dotnet tests are run when targeting main.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#11070 [xcode12.5] [CI] Fwd labels and ensure dotnet tests are run when targeting main.
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/stage.yml
Labels: backported, not-notes-worthy

#11071 [d16-9] [CI] Fwd labels and ensure dotnet tests are run when targeting main.
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/stage.yml
Labels: backported, not-notes-worthy

#11073 [CI] Do not build translation branches in the internal pool.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11069 [CI] Add the id of the pr to an old env var to reuse scripts.
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#11075 [build] Fix incorrect warning about CoreSimulator.framework version
  system-dependencies.sh
Labels: not-notes-worthy

#11074 Revert "[dotnet] Force the GC mode to be preemptive. (#10667)"
  tools/dotnet-linker/Steps/GenerateMainStep.cs
Labels: not-notes-worthy

#11054 Revert "[tests] Ignore CommonLinkSdkTest.TypeDescriptor_A7793 in .NET due to a linker bug."
  tests/linker/CommonLinkSdkTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#11064 Revert "[dotnet-linker] Make PreserveSmartEnumConversionsStep active for type as well to work around a linker bug."
  tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversionsSubStep.cs
Labels: not-notes-worthy

#11053 Revert "[tests] Ignore the XmlSerializationTest.Bug1820_GenericList test in .NET due to a linker bug."
  tests/linker/ios/link sdk/Bug1820Test.cs
Labels: not-notes-worthy, run-dotnet-tests

#11076 [d16-9] [CI] Do not build translation branches in the internal pool.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11077 [xcode12.5] [CI] Do not build translation branches in the internal pool.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11079 [xcode12.5] [CI] Add the id of the pr to an old env var to reuse scripts.
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/stage.yml
Labels: backported, not-notes-worthy

#11080 [d16-9] [CI] Add the id of the pr to an old env var to reuse scripts.
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/stage.yml
Labels: backported, not-notes-worthy

#11090 Target new xamarin-macios multi-OS agent pools
  tools/devops/automation/templates/agent-pool-selector.yml
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#11089 [CI] Do not build darc PRs in the CI.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11098 [d16-9] [CI] Do not build darc PRs in the CI.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11092 [CI] Move sign and notarize out.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#11095 Target new xamarin-macios multi-OS agent pools (#11090)
  tools/devops/automation/templates/agent-pool-selector.yml
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy, run-all-tests

#11107 [6.0.1xx-preview3] [main] Update dependencies from dotnet/installer
  eng/Version.Details.xml
  eng/Versions.props
Labels: backported, not-notes-worthy

#11108 [Make.config] Allow '.' on CURRENT_BRANCH_ALPHANUMERIC to match android package names
  Make.config
Labels: not-notes-worthy

#11097 [xcode12.5] [CI] Do not build darc PRs in the CI.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11101 [CI] Black magic to make life better.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11104 [CI] Exclude builds for certain paths.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11111 [6.0.1xx-preview3] [Make.config] Hardcode preview.3 on our versioning
  Make.config
Labels: backported, not-notes-worthy

#11117 [xcode12.5] [CI] Exclude builds for certain paths.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11116 [d16-9] [CI] Exclude builds for certain paths.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11115 Revert "[Make.config] Allow '.' on CURRENT_BRANCH_ALPHANUMERIC to match android package names"
  Make.config
Labels: not-notes-worthy

#11112 [CI] Group all API diff in a template to make things manageable.
  tools/devops/automation/templates/build/api-diff.yml
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#11102 [CI] Do not generate no used stages.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11120 [d16-9][CI] Move sign and notarize out. (#11092)
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
  tools/devops/automation/templates/build/stage.yml
Labels: backported, not-notes-worthy

#11121 [xcode12.5][CI] Move sign and notarize out. (#11092)
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
  tools/devops/automation/templates/build/stage.yml
Labels: backported, not-notes-worthy

#11131 [CI] Simplify if for stage selection.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11133 [CI][GitHub] Use the correct verb to the request.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#11144 [CI] Fix wrong fwd labels.
  tools/devops/automation/templates/build/configure.yml
Labels: not-notes-worthy, run-bcl-tests

#11141 [xcode12.5] [CI][GitHub] Use the correct verb to the request.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#11142 [d16-9] [CI][GitHub] Use the correct verb to the request.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#11149 [tests] Add app bundle size comparison between legacy and dotnet
  tests/dotnet/Makefile
  tests/dotnet/size-comparison/MySingleView/AppDelegate.cs
  tests/dotnet/size-comparison/MySingleView/Info.plist
  tests/dotnet/size-comparison/MySingleView/dotnet/MySingleView.csproj
  tests/dotnet/size-comparison/MySingleView/oldnet/MySingleView.csproj
  tools/app-compare/.gitignore
  tools/app-compare/AppComparer.cs
  tools/app-compare/DirectoryComparer.cs
  tools/app-compare/Program.cs
  tools/app-compare/README.md
  tools/app-compare/app-compare.csproj
Labels: not-notes-worthy

#11124 [xcode12.5] [CI] Group all API diff in a template to make things manageable.
  tools/devops/automation/templates/build/api-diff.yml
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#11123 [d16-9] [CI] Group all API diff in a template to make things manageable.
  tools/devops/automation/templates/build/api-diff.yml
  tools/devops/automation/templates/build/build.yml
Labels: backported, not-notes-worthy

#11153 [dotnet][msbuild] Do not copy `.pdb` files inside `.app` for release builds
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#11159 [CI] Perform a run with no tests on Sundays for the translations team.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11146 [d16-9] [CI] Fix wrong fwd labels.
  tools/devops/automation/templates/build/configure.yml
Labels: backported, not-notes-worthy, run-bcl-tests

#11152 [xcode12.5] [CI] Fix wrong fwd labels.
  tools/devops/automation/templates/build/configure.yml
Labels: backported, not-notes-worthy, run-bcl-tests

#11160 [tests] Revert manual preservation of InternalsVisibleToAttribute.ctor(string)
  tests/linker/ios/link all/Main.cs
Labels: not-notes-worthy

#11167 Revert "[main] Update dependencies from dotnet/installer"
  eng/Version.Details.xml
  eng/Versions.props
Labels: not-notes-worthy

#11139 [Localization] Temporarily Stop OneLocBuild from making PRs
  tools/devops/automation/templates/build/configure.yml
Labels: not-notes-worthy

#11171 [CI] Do not longer need to use a rebase trigger we have it from github.
  .github/workflows/rebase-trigger.yml
Labels: not-notes-worthy

#11173 [dotnet][msbuild] Fix RelativePath inside ResolvedFileToPublish
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#11169 Reenable HotRestart targets for the legacy Sdk
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Windows.After.targets
Labels: not-notes-worthy

#11178 [d16-9] [CI] Do not longer need to use a rebase trigger we have it from github.
  .github/workflows/rebase-trigger.yml
Labels: backported, not-notes-worthy

#11176 [CI] Do not try to upload test results when not ran.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
  tools/devops/automation/templates/common/download-artifacts.yml
Labels: not-notes-worthy

#11165 Bump maccore to fix mlaunch NRE when starting Simulator bundles
  mk/xamarin.mk
Labels: not-notes-worthy

#11177 [xcode12.5] [CI] Do not longer need to use a rebase trigger we have it from github.
  .github/workflows/rebase-trigger.yml
Labels: backported, not-notes-worthy

#11163 [dotnet] Add ICU support for iOS builds
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/runtime.m
  tests/EmbeddedResources/ResourcesTest.cs
  tests/common/DotNet.cs
  tests/monotouch-test/Foundation/LocaleTest.cs
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
Labels: not-notes-worthy

#11182 Bump MSBuild.StructuredLogger to 2.1.404
  tests/bgen/bgen-tests.csproj
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/generator/generator-tests.csproj
  tests/mmptest/mmptest.csproj
  tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj
  tests/mtouch/mtouch.csproj
Labels: not-notes-worthy

#11179 [Build] Allow to disable the build with the xamarin parts.
  configure
Labels: not-notes-worthy

#11181 [CI] Re-enable CI on maestro branches.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11180 [Build] Add a rule to execute the first run of Xcode. Why copy paste a command?
  Makefile
  system-dependencies.sh
Labels: not-notes-worthy

#11170 [CI] Set status as error if one or more tests failed.
  tools/devops/automation/templates/build/publish-html.yml
Labels: not-notes-worthy

#11130 [xcode12.5][CI] Black magic to make life better. (#11101)
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11129 [d16-9][CI] Black magic to make life better. (#11101)
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11186 [d16-9][CI] Do not generate no used stages.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11184 [Xcode12.5][CI] Do not generate no used stages.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11188 [xcode12.5][CI] Set status as error if one or more tests failed. (#11170)
  tools/devops/automation/templates/build/publish-html.yml
Labels: backported, not-notes-worthy

#11185 [d16-9] [CI] Set status as error if one or more tests failed.
  tools/devops/automation/templates/build/publish-html.yml
Labels: backported, not-notes-worthy

#11158 [dotnet] Handle `lib` prefix for P/Invokes for runtime native libraries
  tools/common/Target.cs
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Labels: community

#11193 [tests][introspection] Report error if no version is present in [SupportedOSPlatformAttribute]
  tests/common/PlatformInfo.cs
Labels: not-notes-worthy

#11194 [CI] If the device tests could not be provisioned do communicate it.
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/devices/run-tests.yml
  tools/devops/automation/templates/devices/stage.yml
Labels: not-notes-worthy

#11198 [CI] Provide the name of the bot with provisioning issues.
  tools/devops/automation/templates/devices/run-tests.yml
Labels: not-notes-worthy

#11197 [d16-10-preview2] [runtime] Fix EntryPointNotFoundException: xamarin_release_managed_ref
  Make.versions
  runtime/monovm-bridge.m
  runtime/runtime.m
  runtime/xamarin/runtime.h
  src/Foundation/NSObject2.cs
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#11202 [d16-9][CI] If the device tests could not be provisioned do communicate it.
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/devices/run-tests.yml
  tools/devops/automation/templates/devices/stage.yml
Labels: backported, not-notes-worthy

#11201 [xcode12.5] [CI] If the device tests could not be provisioned do communicate it.
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/devices/run-tests.yml
  tools/devops/automation/templates/devices/stage.yml
Labels: backported, not-notes-worthy

#11200 [Make.versions] Update version after d16-10 Preview 2
  Make.versions
Labels: not-notes-worthy

#11205 [d16-10][msbuild] Fix copy/paste error from #11196
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  runtime/monovm-bridge.m
  runtime/runtime.m
  runtime/xamarin/runtime.h
  src/Foundation/NSObject2.cs
Labels: not-notes-worthy

#11206 [msbuild] Fix copy/paste error from #11196
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#11204 [CI] Add a tag to identify those auto-scheduled builds. fixes #11191
  tools/devops/automation/templates/build/configure.yml
Labels: not-notes-worthy

#11210 [dotnet][msbuild] Stop publishing dylibs in release builds
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#11211 [static-registrar] Re-order some code in ToObjCParameterType
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#11189 [ci] Upload build asset data to darc/maestro
  Make.config
  Makefile
  dotnet/package/common.csproj
  eng/README.md
  eng/Version.Details.xml
  eng/Versions.props
  tools/devops/automation/post-build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#11203 [CI] Provide the info of the commit that generated a message.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#11208 [d16-9] [CI] Add a tag to identify those auto-scheduled builds. fixes #11191
  tools/devops/automation/templates/build/configure.yml
Labels: backported, not-notes-worthy

#11213 [mono] Bump mono to match android
  Make.config
  mk/mono.mk
Labels: notes-mention

#11216 [xcode12.5] [CI] Provide the info of the commit that generated a message.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#11214 [CI] There is no reason to need to run these tests on device bots.
  tools/devops/automation/templates/devices/build.yml
Labels: not-notes-worthy

#11209 [xcode12.5] [CI] Add a tag to identify those auto-scheduled builds. fixes #11191
  tools/devops/automation/templates/build/configure.yml
Labels: backported, not-notes-worthy

#11215 [d16-9] [CI] Provide the info of the commit that generated a message.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#11224 [d16-9] [CI] There is no reason to need to run these tests on device bots.
  tools/devops/automation/templates/devices/build.yml
Labels: backported, not-notes-worthy

#11221 [dotnet] move WorkloadManifest.* files to /data/ folder
  dotnet/package/microsoft.workloads.csproj
Labels: not-notes-worthy

#11199 [CI] Avoid other not needed steps on provisioning issues.
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/common/upload-vsdrops.yml
  tools/devops/automation/templates/common/upload-vsts-tests.yml
  tools/devops/automation/templates/devices/stage.yml
Labels: do-not-merge, not-notes-worthy

#11227 [xcode12.5] [CI] Avoid other not needed steps on provisioning issues.
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/common/upload-vsdrops.yml
  tools/devops/automation/templates/common/upload-vsts-tests.yml
  tools/devops/automation/templates/devices/stage.yml
Labels: backported, do-not-merge, not-notes-worthy

#11225 [xcode12.5] [CI] There is no reason to need to run these tests on device bots.
  tools/devops/automation/templates/devices/build.yml
Labels: backported, not-notes-worthy

#11226 [dotnet][msbuild] Copy dylibs for macOS and Mac Catalyst
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#11230 [dotnet] Add `[Uns|S]upportedOSPlatformAttribute` to manual bindings (part 1)
  src/Compression/Compression.cs
  src/Compression/CompressionStreamStruct.cs
  src/Compression/Enums.cs
  src/CoreData/NSEntityDescription.cs
  src/CoreImage/CIContext.cs
  src/CoreImage/CIDetectorOptions.cs
  src/CoreImage/CIFilter.cs
  src/CoreImage/CIImage.cs
  src/CoreImage/Enums.cs
  src/CoreMedia/CMBufferQueue.cs
  src/CoreMidi/MidiCIDeviceIdentification.cs
  src/CoreMidi/MidiServices.cs
  src/GameKit/GKLocalPlayerListener.cs
  src/Intents/INIntentResolutionResult.cs
  src/Intents/INSetClimateSettingsInCarIntent.cs
  src/Intents/INSetDefrosterSettingsInCarIntent.cs
  src/Intents/INSetProfileInCarIntent.cs
  src/Intents/INSetSeatSettingsInCarIntent.cs
  src/MLCompute/MLHelpers.cs
  src/MapKit/MKFeatureDisplayPriority.cs
  src/MapKit/MKMapItem.cs
  src/MapKit/MapKit.cs
  src/MediaAccessibility/MAImageCaptioning.cs
  src/MediaAccessibility/MediaAccessibility.cs
  src/MediaToolbox/MTFormatNames.cs
  src/Metal/Defs.cs
  src/Metal/MTLDevice.cs
  src/Metal/MTLIntersectionFunctionTable.cs
  src/Metal/MTLRasterizationRateLayerDescriptor.cs
  src/Metal/MTLResourceStateCommandEncoder.cs
  src/MetalKit/MTKTextureLoaderOptions.cs
  src/MobileCoreServices/UTType.cs
  src/ModelIO/MDLNoiseTexture.cs
  src/ModelIO/MDLStructs.cs
  src/NaturalLanguage/NLModel.cs
  src/NetworkExtension/NEHotspotConfiguration.cs
  src/OpenGLES/EAGLConsts.cs
  src/OpenGLES/EAGLContext.cs
  src/PassKit/PKPaymentRequest.cs
  src/PdfKit/PdfAnnotation.cs
  src/SensorKit/SRAbsoluteTime.cs
  src/SensorKit/SRAmbientLightChromaticity.cs
  src/SpriteKit/SKNode.cs
  src/SpriteKit/SKShapeNode.cs
  src/StoreKit/NativeMethods.cs
  src/SystemConfiguration/CaptiveNetwork.cs
  src/SystemConfiguration/NetworkReachability.cs
  src/VideoSubscriberAccount/VSAccountMetadataRequest.cs
  src/Vision/VNUtils.cs
  src/frameworks.sources
Labels: not-notes-worthy

#11229 [linker] Obsolete 'LinkerSafeAttribute' in favor of `AssemblyMetadata`
  src/Foundation/LinkerSafeAttribute.cs
  tools/common/Tuning.cs
  tools/mmp/Tuning.mmp.cs
  tools/mtouch/Tuning.mtouch.cs
Labels: not-notes-worthy

#11228 [dotnet] Use `[AssemblyMetadata ("IsTrimmable", "True")]` in platforms assemblies
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  src/AssemblyInfo.cs.in
Labels: not-notes-worthy

#11231 [ci] Fix artifact upload in post build pipeline
  tools/devops/automation/post-build-pipeline.yml
Labels: not-notes-worthy

#11238 [maccatalyst] Increase iOS compatibility by removing `XAMCORE_3_0`
  src/Makefile
  src/UIKit/UIBarItem.cs
  tests/xharness/Targets/MacCatalystTarget.cs
Labels: not-notes-worthy

#11240 Make the quiet version of 'dotnet build' quieter.
  mk/quiet.mk
  tests/Makefile
Labels: not-notes-worthy

#11241 [mtouch] It seems watchOS simulators can automatically choose the right architecture from fat apps.
  mk/xamarin.mk
  tools/common/Application.cs
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/Target.mtouch.cs
Labels: not-notes-worthy

#11250 [CI][VSTS] Ensure statuses are set in the correct commit and not the merge commit.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#11254 [CoreCLR] Implement mono_assembly_get_object.
  runtime/coreclr-bridge.m
  runtime/exports.t4
  runtime/mono-runtime.h.t4
  runtime/monotouch-main.m
  runtime/runtime.m
Labels: not-notes-worthy

#11248 [xcode12.5] Bump for Xcode 12.5 RC
  Make.config
  src/LocalAuthentication/LAEnums.cs
  src/arkit.cs
  src/avfoundation.cs
  src/metal.cs
  tests/xtro-sharpie/common-Metal.ignore
  tests/xtro-sharpie/macOS-Metal.ignore
Labels: note-highlight

#11249 [CI] Fix import issue in device test templates.
  tools/devops/automation/templates/common/publish-html.yml
Labels: not-notes-worthy

#11252 [msbuild] Accept 'UseInterpreter' as an alternative for 'MtouchInterpreter'. Fixes #11138.
  msbuild/Xamarin.Shared/Xamarin.Shared.props
Labels: community, not-notes-worthy

#11257 [runtime] Move the code to wrap every managed thread with an NSAutoreleasePool to the MonoVM bridge.
  runtime/coreclr-bridge.m
  runtime/exports.t4
  runtime/monovm-bridge.m
  runtime/runtime.m
  runtime/shared.h
  runtime/shared.m
  runtime/xamarin/runtime.h
Labels: not-notes-worthy

#11261 [d16-9] [CI][VSTS] Ensure statuses are set in the correct commit and not the merge commit.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#11263 [main] [xcode12.5] Bump for Xcode 12.5 RC
  Make.config
  src/LocalAuthentication/LAEnums.cs
  src/arkit.cs
  src/avfoundation.cs
  src/metal.cs
  tests/xtro-sharpie/common-Metal.ignore
  tests/xtro-sharpie/macOS-Metal.ignore
Labels: backported, note-highlight

#11253 [xtro] Update MacCatalyst todos.
  tests/xtro-sharpie/MacCatalyst-AVKit.ignore
  tests/xtro-sharpie/MacCatalyst-AudioToolbox.todo
  tests/xtro-sharpie/MacCatalyst-UIKit.ignore
  tests/xtro-sharpie/MacCatalyst-UIKit.todo
Labels: not-notes-worthy, run-xtro-tests

#11265 [d16-9] [CI] Fix import issue in device test templates.
  tools/devops/automation/templates/common/publish-html.yml
Labels: backported, not-notes-worthy

#11266 [xcode12.5] [CI] Fix import issue in device test templates.
  tools/devops/automation/templates/common/publish-html.yml
Labels: backported, not-notes-worthy

#11242 [CI] Reduce the number of statuses when we build nugets.
  tools/devops/automation/templates/build/build-nugets.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-azure.yml
Labels: not-notes-worthy

#11272 [CI] Remove Mac OS devices that will not happen.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11260 [xcode12.5] [CI][VSTS] Ensure statuses are set in the correct commit and not the merge commit.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#11247 [dotnet][tvos] Enable ICU (instead of using Invariant) and additional tests
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/Makefile
  runtime/monovm-bridge.m
  tests/linker/ios/dont link/DontLinkRegressionTests.cs
  tests/linker/ios/dont link/dotnet/tvOS/Info.plist
  tests/linker/ios/dont link/dotnet/tvOS/dont link.csproj
  tests/linker/ios/link all/dotnet/tvOS/Info.plist
  tests/linker/ios/link all/dotnet/tvOS/link all.csproj
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/linker/ios/link sdk/dotnet/extra-linker-defs.xml
  tests/linker/ios/link sdk/dotnet/tvOS/Info.plist
  tests/linker/ios/link sdk/dotnet/tvOS/link sdk.csproj
  tests/monotouch-test/dotnet/tvOS/Info.plist
  tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj
  tests/xharness/Harness.cs
Labels: not-notes-worthy

#11276 [d16-9] [CI] Remove Mac OS devices that will not happen.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11268 [CI] The env var is not provided in the CI builds, just PRs.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#11267 [CI][VSTS] Remove redundant status.
  tools/devops/automation/templates/governance-checks.yml
Labels: not-notes-worthy

#11270 [msbuild] Rename $(_UsingXamarinSdk) to $(UsingAppleNETSdk)
  dotnet/targets/Xamarin.Shared.Sdk.props
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.ObjCBinding.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.MacCatalyst.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.CSharp.targets
Labels: not-notes-worthy

#11245 Updated Xamarin.Messaging version
  msbuild/Directory.Build.props
  msbuild/Messaging/Xamarin.Messaging.Build/BuildAgent.cs
Labels: not-notes-worthy

#11274 [CI] Remove duplicated status.
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/publish-html.yml
Labels: not-notes-worthy

#11278 [xcode12.5][Versions] Bump version to even since we are close to release
  Make.versions
Labels: not-notes-worthy

#11258 [xcode12.5] [mtouch] It seems watchOS simulators can automatically choose the right architecture from fat apps.
  mk/xamarin.mk
  tools/common/Application.cs
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/Target.mtouch.cs
Labels: not-notes-worthy

#11264 [CoreCLR] Implement mono_jit_exec.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11259 [d16-9] [mtouch] It seems watchOS simulators can automatically choose the right architecture from fat apps.
  mk/xamarin.mk
  tools/common/Application.cs
  tools/mtouch/Application.mtouch.cs
  tools/mtouch/Target.mtouch.cs
Labels: not-notes-worthy

#11262 [ObjCRuntime] Print to stderr if using xamarin_log fails. Fixes #11239.
  src/ObjCRuntime/Runtime.CoreCLR.cs
  src/ObjCRuntime/Runtime.cs
  tests/xtro-sharpie/common-CoreFoundation.ignore
Labels: not-notes-worthy

#11277 [msbuild] Fixes archiving and copying files to Windows
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/LocalUnzip.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
Labels: not-notes-worthy

#11285 [xcode12.5] [CI] Remove duplicated status.
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/publish-html.yml
Labels: backported, not-notes-worthy

#11282 [xcode12.5] [CI][VSTS] Remove redundant status.
  tools/devops/automation/templates/governance-checks.yml
Labels: backported, not-notes-worthy

#11281 [d16-9] [CI][VSTS] Remove redundant status.
  tools/devops/automation/templates/governance-checks.yml
Labels: backported, not-notes-worthy

#11275 [xcode12.5] [CI] Remove Mac OS devices that will not happen.
  tools/devops/automation/build-pipeline.yml
Labels: backported, not-notes-worthy

#11283 [xcode12.5] [CI] The env var is not provided in the CI builds, just PRs.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#11284 [d16-9] [CI] The env var is not provided in the CI builds, just PRs.
  tools/devops/automation/scripts/GitHub.psm1
Labels: backported, not-notes-worthy

#11288 [mmp] Use the resolver (and configure it correctly) when using --runregistrar.
  tools/common/Application.cs
  tools/common/CoreResolver.cs
  tools/common/StaticRegistrar.cs
  tools/mmp/driver.cs
  tools/mmp/resolver.cs
Labels: not-notes-worthy

#11287 [tests][link all] Fix nunit silent exception causing some tests not to be enabled
  src/ObjCRuntime/PlatformAvailability.cs
  tests/common/TestRuntime.cs
  tests/linker/ios/link all/LinkAllTest.cs
  tests/xharness/Harness.cs
Labels: not-notes-worthy

#11255 Use the SDK UseMonoRuntime property instead of _XamarinRuntime in MSBuild
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/xharness/Jenkins/TestData.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: community, notes-mention

#11289 [tests] Remove dead Classic test code.
  tests/common/mac/ClassicExample.csproj
  tests/common/mac/Info-Classic.plist
  tests/common/mac/MainClassic.cs
Labels: not-notes-worthy

#11296 [CI] Fix pwsh.
  tools/devops/automation/templates/build/upload-azure.yml
Labels: not-notes-worthy

#11303 [CI] Add triggers for new release branches.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11304 [CI] Add triggers for new release branches. (#11303)
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11295 [dotnet] Enable more trimming switches
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#11300 [catalyst] remove splash screens
  dotnet/Microsoft.MacCatalyst.Templates/maccatalyst/Info.plist
  dotnet/Microsoft.MacCatalyst.Templates/maccatalyst/LaunchScreen.storyboard
  tests/dotnet/MyCatalystApp/Info.plist
  tests/dotnet/MyCatalystApp/Resources/Images.xcassets/LaunchImage.launchimage/Contents.json
  tests/dotnet/MyCatalystApp/Resources/Images.xcassets/LaunchImage.launchimage/Default-568h@2x.png
  tests/dotnet/MyCatalystApp/Resources/Images.xcassets/LaunchImage.launchimage/Default.png
  tests/dotnet/MyCatalystApp/Resources/Images.xcassets/LaunchImage.launchimage/Default@2x.png
Labels: not-notes-worthy

#11293 [release/6.0.1xx-preview4] [msbuild] Accept 'UseInterpreter' as an alternative for 'MtouchInterpreter'. Fixes #11138.
  msbuild/Xamarin.Shared/Xamarin.Shared.props
Labels: backported, not-notes-worthy

#11298 [tests] Add a performance test using BenchmarkDotNet.
  NuGet.config
  tests/bindings-test/ApiDefinition.cs
  tests/perftest/.gitignore
  tests/perftest/AppDelegate.cs
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-128.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-128@2x.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-16.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-16@2x.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-256.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-256@2x.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-32.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-32@2x.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-512.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png
  tests/perftest/Assets.xcassets/AppIcon.appiconset/Contents.json
  tests/perftest/Assets.xcassets/Contents.json
  tests/perftest/Entitlements.plist
  tests/perftest/Info.plist
  tests/perftest/Main.cs
  tests/perftest/Main.storyboard
  tests/perftest/Makefile
  tests/perftest/MessageSend.cs
  tests/perftest/Messaging.cs
  tests/perftest/ObjCBridge.cs
  tests/perftest/ObjectCreation.cs
  tests/perftest/README.md
  tests/perftest/ViewController.cs
  tests/perftest/ViewController.designer.cs
  tests/perftest/dotnet/perftest.csproj
  tests/perftest/legacy/perftest-legacy.csproj
  tests/perftest/perftest.sln
  tests/test-libraries/libtest.h
  tests/test-libraries/libtest.m
Labels: not-notes-worthy

#11273 [release/6.0.1xx-preview4] [main] [xcode12.5] Bump for Xcode 12.5 RC
  Make.config
  src/LocalAuthentication/LAEnums.cs
  src/arkit.cs
  src/avfoundation.cs
  src/metal.cs
  tests/xtro-sharpie/common-Metal.ignore
  tests/xtro-sharpie/macOS-Metal.ignore
Labels: backported, note-highlight

#11302 [msbuild] Removes explicit Mqtt dependency
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
Labels: not-notes-worthy

#11297 [msbuild] Fixes DebugType for VS
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy
