Repository dotnet/macios, pull requests merged in 2021-10, with the labels that each got.

#12889 [Actions] Provide first step for a ping action.
  .github/workflows/ping.yml
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#12890 [Actions] Perform the repo dispatch in our ping action.
  .github/workflows/ping.yml
Labels: not-notes-worthy

#12891 [Action] Fix branch name.
  .github/workflows/ping.yml
Labels: not-notes-worthy

#12892 [Actions] Fix redirect.
  .github/workflows/ping.yml
Labels: not-notes-worthy

#12893 [Action] Replace over bash.
  .github/workflows/ping.yml
Labels: not-notes-worthy

#12894 [Action] Add first step to a pong.
  .github/workflows/pong.yml
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#12895 [Actions] Use market action.
  .github/workflows/ping.yml
Labels: not-notes-worthy

#12896 [Actions] Initial code for pong.
  .github/workflows/pong.yml
Labels: not-notes-worthy

#12897 [Actions] Update local.
  .github/workflows/pong.yml
Labels: not-notes-worthy

#12885 [tests] Add a test to verify that AppDomain.CurrentDomain.BaseDirectory is always something. Fixes #12687.
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12882 [dotnet] Implement support for the MtouchFloat32 MSBuild property. Fixes #12524.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  tools/common/Application.cs
  tools/dotnet-linker/LinkerConfiguration.cs
Labels: not-notes-worthy, run-dotnet-tests

#12881 [tests] Make sure interdependent-binding-projects builds with our workaround for NUnit bugs in .NET.
  tests/interdependent-binding-projects/dotnet/shared.csproj
Labels: not-notes-worthy, run-dotnet-tests

#12880 [xharness] Remove iOS 32-bit simulator support, current Xcodes don't support it.
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
  tests/xharness/TestTargetExtensions.cs
  tests/xharness/Xharness.Tests/Tests/TestTargetExtensionsTests.cs
  tests/xharness/iOSTestProject.cs
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#12879 [tests] Add more special cases for random network errors on CI.
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy

#12868 [msbuild] Augment the CreateBindingResourcePackage to support creating a zipped binding resource package.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateBindingResourcePackageBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveFrameworksBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CreateBindingResourceTaskTests.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TestHelpers/TestEngine.cs
  tools/common/Assembly.cs
  tools/common/PathUtils.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
Labels: not-notes-worthy, run-dotnet-tests

#12867 [msbuild] Ignore CS8002 for the Xamarin.iOS.Tasks and Xamarin.Mac.Tasks projects.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
Labels: not-notes-worthy

#12908 [CI] Manually add certain arcade files.
  eng/common/SetupNugetSources.ps1
  eng/common/SetupNugetSources.sh
  eng/common/pipeline-logging-functions.ps1
  eng/common/pipeline-logging-functions.sh
  eng/common/tools.ps1
  eng/common/tools.sh
Labels: not-notes-worthy

#12904 [Maccore] Bump maccore to bring the feed config.
  mk/xamarin.mk
Labels: not-notes-worthy

#12907 [CI] Conditionally add env group.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#12905 [CI] Add explicit checkout name
  tools/devops/automation/post-build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/upload-azure.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
  tools/devops/automation/templates/common/download-artifacts.yml
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/common/upload-vsdrops.yml
  tools/devops/automation/templates/common/upload-vsts-tests.yml
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/governance-checks.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/publish-html-result.yml
  tools/devops/automation/templates/windows/build.yml
  tools/devops/build-samples.yml
Labels: not-notes-worthy

#12903 [CI] Do not publish private pkgs.
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#12914 [mono] Bump mono/2020-02 to latest HEAD
  mk/mono.mk
Labels: notes-mention

#12910 [CI] Allow to pass extra args to the donet install.
  builds/Makefile
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#12912 [CI] Add a conditional variable template.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/variables.yml
Labels: not-notes-worthy

#12913 [CI] Use a variable present in templates.
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#12900 [dotnet] Add support for 'dotnet pack'. Fixes #12631.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/common/DotNet.cs
  tests/dotnet/MyClassLibrary/MyClassLibrary.csproj
  tests/dotnet/UnitTests/ApplePlatformExtensions.cs
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/dotnet/UnitTests/PackTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#12873 [msbuild] Share the BTouch task implementation between iOS and macOS.
  msbuild/Xamarin.Mac.Tasks/Tasks/BTouch.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/BTouch.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/TaskItemFixer.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/BTouchTaskTest.cs
Labels: not-notes-worthy

#12909 [CI] Allow to choose nuget publishing feeds based in the repo id.
  tools/devops/Makefile
  tools/devops/automation/templates/release/publish-nugets.yml
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: not-notes-worthy

#12911 [CI] Setup nugets config for the private repo.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#12919 [mtouch] Make 'MonoTouch.Dialog-1' and 'MonoTouch.NUnitLite' SDK assemblies, not product assemblies. Fixes #12862.
  tools/linker/MobileProfile.cs
  tools/linker/MonoTouch.Tuner/MonoTouchProfile.cs
Labels: not-notes-worthy, run-dotnet-tests

#12927 [CI] Fix yaml by using else.
  tools/devops/automation/templates/release/publish-nugets.yml
Labels: not-notes-worthy

#12928 [CI] Env is a map, uses : and not =
  tools/devops/automation/templates/release/publish-nugets.yml
Labels: not-notes-worthy

#12929 [CI] Not all bots support the new syntax.
  tools/devops/automation/templates/release/publish-nugets.yml
Labels: not-notes-worthy

#12930 [CI] Cannot use condition.
  tools/devops/automation/templates/release/publish-nugets.yml
Labels: not-notes-worthy

#12931 [CI] Rollback changes.
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: not-notes-worthy

#12920 [.NET/AudioToolbox] Make AudioServicesAddSystemSoundCompletion take an unmanaged function pointer instead of delegate. Very partial fix for #10470.
  src/AudioToolbox/SystemSound.cs
Labels: run-all-tests, skip-device-tests, not-notes-worthy, run-dotnet-tests

#12563 [msbuild] Add ILStrip'ing for net6 applications. Fixes #11445.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  eng/Versions.props
  msbuild/ILMerge.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ILStripBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
  msbuild/Xamarin.iOS.Tasks/Tasks/ILStrip.cs
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
  tests/dotnet/Makefile
  tests/dotnet/README.md
  tests/dotnet/UnitTests/PostBuildTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: do-not-merge, note-highlight, run-dotnet-tests

#12809 [UIKit] Add Catalyst support
  src/appkit.cs
  src/uikit.cs
  tests/xtro-sharpie/MacCatalyst-AppKit.ignore
  tests/xtro-sharpie/MacCatalyst-UIKit.ignore
  tests/xtro-sharpie/MacCatalyst-UIKit.todo
Labels: do-not-merge, not-notes-worthy

#12921 [tests] Modify a few test directories with multiple projects to have the projects in subfolders.
  tests/bindings-framework-test/iOS/bindings-framework-test.csproj
  tests/bindings-framework-test/macOS/bindings-framework-test.csproj
  tests/bindings-xcframework-test/iOS/bindings-xcframework-test.csproj
  tests/bindings-xcframework-test/macOS/bindings-xcframework-test.csproj
  tests/framework-test/iOS/framework-test-ios.csproj
  tests/framework-test/macOS/framework-test-mac.csproj
  tests/mtouch/MTouch.cs
  tests/tests-mac.sln
  tests/tests.sln
  tests/xcframework-test/iOS/xcframework-test-ios.csproj
  tests/xcframework-test/macOS/xcframework-test-mac.csproj
  tests/xharness/Harness.cs
Labels: run-all-tests, skip-device-tests, not-notes-worthy, run-dotnet-tests

#12875 [Metal] Add support for xcode 13 beta5 .
  src/Metal/MTLDevice.cs
  src/Metal/MTLEnums.cs
  src/Metal/MTLRasterizationRateLayerDescriptor.cs
  src/metal.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/monotouch-test/Metal/HeapDescriptorTest.cs
  tests/monotouch-test/Metal/MTLDeviceTests.cs
  tests/monotouch-test/Metal/MTLRasterizationRateLayerDescriptorTest.cs
  tests/monotouch-test/Metal/MTLRasterizationRateMapDescriptorTest.cs
  tests/monotouch-test/Metal/MTLRenderPipelineDescriptorTest.cs
  tests/xtro-sharpie/MacCatalyst-Metal.ignore
  tests/xtro-sharpie/MacCatalyst-Metal.todo
  tests/xtro-sharpie/common-Metal.ignore
  tests/xtro-sharpie/iOS-Metal.ignore
  tests/xtro-sharpie/iOS-Metal.todo
  tests/xtro-sharpie/macOS-Metal.ignore
  tests/xtro-sharpie/macOS-Metal.todo
  tests/xtro-sharpie/tvOS-Metal.ignore
  tests/xtro-sharpie/tvOS-Metal.todo
Labels: note-highlight

#12926 Catalyst changes for CoreAnimation, CoreFoundation, and AVKit
  src/CoreAnimation/CAEnums.cs
  src/CoreFoundation/CFBundle.cs
  src/avkit.cs
  src/coreanimation.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/xtro-sharpie/MacCatalyst-AVKit.todo
  tests/xtro-sharpie/MacCatalyst-CoreAnimation.ignore
  tests/xtro-sharpie/MacCatalyst-CoreAnimation.todo
  tests/xtro-sharpie/MacCatalyst-CoreFoundation.todo
Labels: not-notes-worthy

#12776 [tests] Fix packaging of Xamarin.Mac tests.
  tests/.gitignore
  tests/bindings-framework-test/dotnet/shared.mk
  tests/bindings-test/dotnet/shared.mk
  tests/bindings-xcframework-test/dotnet/shared.mk
  tests/common/shared-dotnet.mk
  tests/framework-test/dotnet/shared.mk
  tests/fsharp/dotnet/shared.mk
  tests/fsharplibrary/dotnet/shared.mk
  tests/interdependent-binding-projects/dotnet/shared.mk
  tests/introspection/dotnet/shared.mk
  tests/linker/ios/dont link/DontLinkRegressionTests.cs
  tests/linker/ios/dont link/dotnet/shared.mk
  tests/linker/ios/link all/dotnet/shared.mk
  tests/linker/ios/link sdk/dotnet/shared.mk
  tests/monotouch-test/dotnet/shared.mk
  tests/package-mac-tests.sh
  tests/packaged-macos-tests.mk
  tests/xammac_tests/xammac_tests.csproj
  tests/xcframework-test/dotnet/shared.mk
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy, run-dotnet-tests

#12918 [msbuild] Share the CodesignVerify task implementation between iOS and macOS.
  msbuild/Xamarin.Mac.Tasks/Tasks/CodesignVerify.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignVerifyTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CodesignVerify.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CodesignVerifyTaskBase.cs
Labels: not-notes-worthy

#13157 [CGImageDestination] Subclass NativeObject + numerous other code updates
  src/ImageIO/CGImageDestination.cs
Labels: not-notes-worthy

#13152 [SearchKit] Subclass NativeObject + numerous other code updates
  src/CoreFoundation/NativeObject.cs
  src/SearchKit/SearchKit.cs
Labels: not-notes-worthy

#13182 [AVFoundation] Fix intro issues in monterey.
  tests/introspection/Mac/MacApiSelectorTest.cs
Labels: not-notes-worthy
