Repository dotnet/macios, pull requests merged in 2021-06, with the labels that each got.

#11752 [tests] Re-enable Mac Catalyst tests related to the GC not working.
  tests/monotouch-test/CoreAnimation/LayerTest.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/mono/WeakReferenceTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#11751 [runtime] Release the block_wrapper_queue and xamarin_wrapper_hash dictionaries upon process exit.
  runtime/monotouch-main.m
  runtime/runtime.m
  runtime/xamarin/runtime.h
Labels: not-notes-worthy, run-dotnet-tests

#11748 [static registrar] Release the return value from xamarin_get_reflection_method_method in generated code.
  runtime/coreclr-bridge.m
  runtime/xamarin/runtime.h
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#11746 [runtime] Don't forget to free the method field in MonoMethodSignatures.
  runtime/coreclr-bridge.m
Labels: not-notes-worthy, run-dotnet-tests

#11754 [generator] Use `is` instead of `==` when doing null checks
  src/NativeTypes/Drawing.tt
  src/NativeTypes/Primitives.tt
  src/generator-enums.cs
  src/generator-filters.cs
  src/generator.cs
  src/mapkit.cs
  src/safariservices.cs
  src/uikit.cs
Labels: not-notes-worthy

#11753 [catalyst][coremotion] Update xtro
  tests/xtro-sharpie/MacCatalyst-CoreMotion.ignore
Labels: not-notes-worthy

#11720 [CI] Do not generate github static pages on CI.
  tools/devops/automation/publish-pr-html-results.yml
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#11732 [tests] Adjust MX8029_b and MX8033 tests to cope with slightly different exception message output for CoreCLR.
  tests/common/TestRuntime.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#11738 [Localization] Update Localization READMEs
  msbuild/Xamarin.Localization.MSBuild/README.md
  src/README.md
  tools/mtouch/README.md
Labels: not-notes-worthy

#11759 [Actions] We do not find data because we are not in the correct path.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11758 [runtime] Show the typename of the MonoObjects we're leaking.
  runtime/coreclr-bridge.m
Labels: not-notes-worthy

#11760 [CI] Use LFS for the static page checkout.
  tools/devops/automation/templates/publish-html-result.yml
Labels: not-notes-worthy

#11756 [runtime] Add missing release for call to mono_reflection_type_get_type.
  runtime/trampolines.m
Labels: not-notes-worthy, run-dotnet-tests

#11768 [Action] Check for dir not file.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11772 [Actions] Need to debug where is the action adding the static page.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11773 [Actions] Yaml extra key.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11774 [Actions] fix checkout.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11775 [Actions] fix steps.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11776 [Actions] name to repository and upper dir.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11777 [Actions] upper path is not allowed yet the docs said nothing.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11769 [CI] Ignore readme files and github actions.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11778 [Actions] default is main.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11757 [runtime] Add support for toggle refs to CoreCLR.
  runtime/coreclr-bridge.m
  src/Foundation/NSObject2.cs
  src/ObjCRuntime/Runtime.CoreCLR.cs
  tests/common/TestRuntime.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/monotouch-test/Foundation/ObjectTest.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
  tests/monotouch-test/UIKit/ControlTest.cs
Labels: not-notes-worthy, run-all-tests, skip-device-tests

#11761 [release/6.0.1xx-preview5] [dotnet] Fix the AOT compiler on iOS and tvOS.
  builds/Makefile
  dotnet/Makefile
  dotnet/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
  dotnet/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets
  dotnet/targets/WorkloadManifest.MacCatalyst.template.json
  dotnet/targets/WorkloadManifest.iOS.template.json
  dotnet/targets/WorkloadManifest.macOS.template.json
  dotnet/targets/WorkloadManifest.tvOS.template.json
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#11765 [monotouch-test] Ignore HKQuantityTypeIdentifier.AppleMoveTime on iOS versions where it didn't exist.
  tests/monotouch-test/HealthKit/QuantityTypeIdentifierTest.cs
Labels: not-notes-worthy

#11749 [coreclr] Support for NSAutoreleasePools has now been implemented for background threads for both MonoVM and CoreCLR. Fixes #11256.
  runtime/coreclr-bridge.m
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#11763 [monotouch-test] Don't run SystemSound tests in the simulator.
  tests/common/TestRuntime.cs
  tests/monotouch-test/AudioToolbox/SystemSoundTest.cs
Labels: not-notes-worthy

#11766 [monotouch-test] Exclude any *.cs file in any obj subdirectory, not only the immediate subdirectory.
  tests/monotouch-test/monotouch-test.csproj
Labels: not-notes-worthy

#11780 [tests][dotnet] Update oldnet sample to use LLVM and add some instructions
  tests/dotnet/README.md
  tests/dotnet/size-comparison/MySingleView/oldnet/MySingleView.csproj
Labels: not-notes-worthy

#11783 [monotouch-test] Try to fix a few runtime warnings about unbalanced calls to begin/end appearance transitions.
  tests/monotouch-test/AppDelegate.cs
Labels: not-notes-worthy, run-dotnet-tests

#11764 [monotouch-test] It doesn't look like the TryCopyCurrentNetworkInfo test works in the iOS 11 simulator either.
  tests/monotouch-test/SystemConfiguration/CaptiveNetworkTest.cs
Labels: not-notes-worthy

#11762 [CI] Do override statuses due to VS Windows using hardcoded strings.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#11737 [Localization] Test to make sure the new resx files are compiled to Resources (Edited)
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/Xamarin.Localization.MSBuild.csproj
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationStringTest.cs
  tests/mtouch/LocalizationTests.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/mmp/mmp.csproj
  tools/mtouch/Errors.designer.cs
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#11770 [monotouch-test] Use TestRuntime.RunAsync instead of AppDelegate.RunAsync so that the system sound tests work on macOS as well.
  src/AudioToolbox/SystemSound.cs
  tests/monotouch-test/AudioToolbox/SystemSoundTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#11779 [coregraphics] Small refactor to ease removal of code by the linker
  src/CoreGraphics/CGAffineTransform.cs
  src/NativeTypes/Drawing.tt
Labels: not-notes-worthy

#11716 [main][mono] Bump mono to HEAD of 2020-02 to match android
  Make.config
  mk/mono.mk
  tests/mmptest/src/TargetFrameworkMutateTests.cs
Labels: notes-mention

#11803 [Actions] Use the correct pat. Do not make the repos to nest.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11804 [Actions] Use the service account pat.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11797 [dotnet] Make sure to set CopyToPublishDirectory=PreserveNewest on files we add to 'ResolvedFileToPublish'. Fixes #11611.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#11798 [tests] Honor V=1 for build verbosity when building size comparison tests.
  tests/dotnet/Makefile
Labels: not-notes-worthy

#11796 [runtime] Disable LOG_MONOVM logging by default.
  runtime/xamarin/monovm-bridge.h
Labels: not-notes-worthy

#11795 [editorconfig] Set the charset to utf-8.
  .editorconfig
Labels: not-notes-worthy

#11805 [Actions] Work with VSEng to fix the clean action.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11806 [Actions] Tryo to use a magic token $
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11787 [release/6.0.1xx-preview5] [dotnet] Rework how we handle workloads.
  builds/Makefile
  dotnet/.gitignore
  dotnet/Makefile
  dotnet/Microsoft.NET.Sdk.watchOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets
Labels: not-notes-worthy, run-dotnet-tests

#11789 Mono changed the location of the AOT compiler, so we have to update our code accordingly.
  dotnet/.gitignore
  dotnet/Makefile
  dotnet/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
  dotnet/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets
  dotnet/Microsoft.NET.Sdk.watchOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets
  dotnet/targets/WorkloadManifest.MacCatalyst.template.json
  dotnet/targets/WorkloadManifest.iOS.template.json
  dotnet/targets/WorkloadManifest.macOS.template.json
  dotnet/targets/WorkloadManifest.tvOS.template.json
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#11811 Remove internal `Xamarin.Utils.*` types from platform assemblies
  src/ObjCRuntime/Registrar.core.cs
  src/ObjCRuntime/Registrar.cs
  src/frameworks.sources
  src/generator.cs
  tools/common/StringUtils.cs
Labels: not-notes-worthy

#11810 [coreanimation] Reduce the size of `CATransform3D`
  src/CoreAnimation/CATransform3D.cs
Labels: not-notes-worthy

#11790 [Localization] Changing the merge to a Pseudo Force Push
  tools/devops/automation/templates/build/configure.yml
Labels: not-notes-worthy

#11736 [Tests] Fix intro tests on older macOS
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
Labels: not-notes-worthy

#11819 [Actions] Remove broken action.
  .github/workflows/github-page-clean-up.yml
Labels: not-notes-worthy

#11821 adding first test to test2
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationStringTest.cs
Labels: not-notes-worthy

#11826 [Test] Want to test this Github Action
  .github/workflows/localization-update.yml
Labels: not-notes-worthy

#11809 Use `CFString` instead of `NSString` to get a (.net) `System.String` from an handle
  src/AppKit/NSAccessibility.cs
  src/AudioToolbox/AudioFile.cs
  src/AudioToolbox/AudioFileGlobalInfo.cs
  src/AudioToolbox/AudioQueue.cs
  src/AudioToolbox/AudioSession.cs
  src/AudioUnit/AudioComponent.cs
  src/AudioUnit/AudioUnit.cs
  src/CoreAnimation/CATextLayer.cs
  src/CoreFoundation/CFBundle.cs
  src/CoreFoundation/CFDictionary.cs
  src/CoreFoundation/CFException.cs
  src/CoreFoundation/CFMessagePort.cs
  src/CoreFoundation/CFNotificationCenter.cs
  src/CoreFoundation/CFString.cs
  src/CoreGraphics/CGColor.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGFont.cs
  src/CoreImage/CIFilter.cs
  src/CoreMedia/CMTime.cs
  src/CoreMidi/MidiServices.cs
  src/CoreText/CTFont.cs
  src/CoreText/CTGlyphInfo.cs
  src/Foundation/DictionaryContainer.cs
  src/Foundation/NSArray.cs
  src/Foundation/NSAttributedString.cs
  src/Foundation/NSKeyedArchiver.cs
  src/Foundation/NSMetadataItem.cs
  src/Foundation/NSString.cs
  src/ImageIO/CGImageSource.cs
  src/MLCompute/MLHelpers.cs
  src/MediaAccessibility/MAImageCaptioning.cs
  src/MediaAccessibility/MediaAccessibility.cs
  src/MediaToolbox/MTFormatNames.cs
  src/MobileCoreServices/UTType.cs
  src/PrintCore/PrintCore.cs
  src/SearchKit/SearchKit.cs
  src/Security/Certificate.cs
  src/Security/SecSharedCredential.cs
  src/VideoToolbox/VTVideoEncoder.cs
  src/generator.cs
  tests/perftest/TollFreeBridge.cs
Labels: notes-mention

#11816 [dotnet] It's x86, not x84.
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#11815 [dotnet] Remove workaround for dotnet/runtime issue with incorrect dylibs.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy, run-dotnet-tests

#11801 [dotnet] Only publish a single libxamarin-dotnet*.dylib file.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#11849 [Localization] Typo in the scheduled build
  tools/devops/automation/templates/build/configure.yml
Labels: not-notes-worthy

#11847 [mediaplayer] Fix MPNowPlayingInfoCenter.DefaultCenter.NowPlaying < iOS 11.1
  src/Foundation/NSDictionary.cs
  src/MediaPlayer/MPNowPlayingInfoCenter.cs
Labels: bug

#11857 [d16-10] [mediaplayer] Fix MPNowPlayingInfoCenter.DefaultCenter.NowPlaying < iOS 11.1
  src/Foundation/NSDictionary.cs
  src/MediaPlayer/MPNowPlayingInfoCenter.cs
Labels: backported, bug

#11854 [CI] Unify the password across templates.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
Labels: not-notes-worthy

#11859 [dotnet] add @(SdkSupportedTargetPlatformIdentifier)
  dotnet/Workloads/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets
Labels: not-notes-worthy

#11850 [tests] Collect and zip up the .NET unit tests for execution on Windows.
  tests/.gitignore
  tests/Makefile
  tests/common/Configuration.cs
  tests/common/DotNet.cs
  tests/dotnet/Makefile
  tests/dotnet/UnitTests/Makefile
  tests/package-dotnet-tests.sh
Labels: not-notes-worthy, run-dotnet-tests

#11856 [release/6.0.1xx-preview5] [dotnet] Make sure to set CopyToPublishDirectory=PreserveNewest on files we add to 'ResolvedFileToPublish'. Fixes #11611. (#11797)
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#11866 [dotnet] Fix the path to the workloads in one more location.
  dotnet/package/microsoft.workloads.csproj
Labels: not-notes-worthy, run-dotnet-tests

#11867 [main] [dotnet] Fix the path to the workloads in one more location.
  dotnet/package/microsoft.workloads.csproj
Labels: backported, not-notes-worthy, run-dotnet-tests

#11864 Bump maccore to get fix for Xcode 13.
  mk/xamarin.mk
Labels: not-notes-worthy

#11869 [dotnet] Add a data/UnixFilePermissions.xml file to the sdk packs. Fixes #11860.
  dotnet/Makefile
  dotnet/Microsoft.MacCatalyst.Sdk/data/UnixFilePermissions.xml
  dotnet/Microsoft.iOS.Sdk/data/UnixFilePermissions.xml
  dotnet/Microsoft.macOS.Sdk/data/UnixFilePermissions.xml
  dotnet/Microsoft.tvOS.Sdk/data/UnixFilePermissions.xml
Labels: not-notes-worthy, run-dotnet-tests

#11872 [uikit] More linker-friendly `UIControl`
  src/UIKit/UIControl.cs
Labels: not-notes-worthy

#11871 [dotnet][linker] Fix incorrect namespace for `[NotImplementedAttribute]`
  src/ILLink.LinkAttributes.xml.in
Labels: not-notes-worthy

#11870 [windows][msbuild] Fix the use of a windows path inside `_PrepareDebugSymbolGeneration`
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetFullPathTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/GetFullPath.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: bug

#11868 [windows][msbuild] Copy entire directory when the native reference is a framework
  msbuild/Xamarin.iOS.Tasks/Tasks/MTouch.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/MTouchTaskTests.cs
Labels: bug

#11865 [CI] Do not add links to static page if we never got results.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#11874 [dotnet] Create binlogs when creating NuGets.
  dotnet/Makefile
Labels: not-notes-worthy, run-dotnet-tests

#11876 [d16-10] [windows][msbuild] Fix the use of a windows path inside `_PrepareDebugSymbolGeneration`
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetFullPathTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/GetFullPath.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: backported, bug

#11875 [d16-10] [windows][msbuild] Copy entire directory when the native reference is a framework
  msbuild/Xamarin.iOS.Tasks/Tasks/MTouch.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/MTouchTaskTests.cs
Labels: backported, bug

#11880 [dotnet] The MSBuildProjectDirectory variable doesn't contain a trailing slash, so make sure we always add one.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#11884 [devops] Upload all the binlogs in xamarin-macios as artifacts after the build.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#11851 [devops] Publish mlaunch as .nupkg during main build
  tools/devops/automation/scripts/bash/build-mlaunch-nuget.sh
  tools/devops/automation/templates/build/build-nugets.yml
  tools/mlaunch/nupkg/Microsoft.DotNet.Mlaunch.csproj
  tools/mlaunch/nupkg/README.md
  tools/mlaunch/nupkg/build/Microsoft.DotNet.Mlaunch.props
  tools/mlaunch/nupkg/build/Microsoft.DotNet.Mlaunch.targets
Labels: not-notes-worthy

#11890 [CI] Ensure that we do not have data downloaded from other builds.
  tools/devops/automation/templates/publish-html-result.yml
Labels: not-notes-worthy

#11848 [Localization] Adding New Github Action (In new branch)
  .github/workflows/localization-update.yml
  .github/workflows/localization_branch_sync.yml
Labels: not-notes-worthy

#11855 [CI] Fix condition to start executing the device tests.
  tools/devops/automation/templates/devices/build.yml
Labels: not-notes-worthy

#11891 [release/6.0.1xx-preview5] [dotnet] Don't allow any other branches to pretend to be release branches.
  Make.config
Labels: not-notes-worthy, run-dotnet-tests

#11892 [msbuild] Fix P/Invoke to stat.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/SmartCopyTaskBase.cs
Labels: not-notes-worthy, run-dotnet-tests

#11893 Try to prevent identical version numbers across branches by matching hardcoded prerelease identifiers with hardcoded branch name.
  Make.config
Labels: not-notes-worthy, run-dotnet-tests

#11897 [dotnet] Try to implement a workaround for xamarin/maccore#2427.
  dotnet/Makefile
  dotnet/package/workaround-for-maccore-issue-2427/restore.csproj
Labels: not-notes-worthy, run-dotnet-tests

#11898 [msbuild] Share several cleaning targets between Xamarin.iOS and Xamarin.Mac.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetDirectoriesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/GetDirectories.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-msbuild-tests

#11896 [CI] Add a new stage that will run windows integration tests.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/windows/build.yml
  tools/devops/automation/templates/windows/stage.yml
Labels: not-notes-worthy

#11895 [d16-10] [CI] Ensure that we do not have data downloaded from other builds.
  tools/devops/automation/templates/publish-html-result.yml
Labels: backported, not-notes-worthy

#11902 [CI] - is not a valid car in a name...
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11900 [Localization] Github Action Fork Check
  .github/workflows/localization_branch_sync.yml
Labels: not-notes-worthy

#11882 [objcruntime] A few cleanup/simplifications for `Selector`
  src/ObjCRuntime/Selector.cs
Labels: not-notes-worthy

#11899 [tests/dotnet] Add test-case for 32-bit iOS device build as well
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#11910 [coremidi] Remove incorrect `.ctor` on `MIDICISession`
  src/CoreMidi/MidiCompat.cs
  src/coremidi.cs
Labels: note-highlight

#11909 [cloudkit] Remove obsoleted properties
  src/CloudKit/CKCompat.cs
  src/cloudkit.cs
Labels: note-highlight

#11907 Remove extra (managed) setters on readonly (native) properties
  src/mlcompute.cs
  src/networkextension.cs
  src/vision.cs
Labels: note-highlight

#11908 [ARKit] Provide updates for Xcode13 beta1.
  src/arkit.cs
  tests/xtro-sharpie/iOS-ARKit.todo
Labels: note-highlight

#11911 [WatchKit] Add support for Xcode13 beta 1.
  src/watchkit.cs
  tests/xtro-sharpie/watchOS-WatchKit.todo
Labels: note-highlight

#11922 [d16-10] [coremidi] Remove incorrect `.ctor` on `MIDICISession`
  src/CoreMidi/MidiCompat.cs
  src/coremidi.cs
Labels: backported, note-highlight

#11927 [introspection] Handle a few Metal classes differently for 'encodeWithCoder:'. Fixes #11885.
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
Labels: not-notes-worthy

#11920 [d16-10] [cloudkit] Remove obsoleted properties
  src/CloudKit/CKCompat.cs
  src/cloudkit.cs
Labels: backported, note-highlight

#11923 [cloudkit] Fix obsolete message
  src/CloudKit/CKCompat.cs
Labels: not-notes-worthy

#11929 [CI] Fix BRANCH_NAME to be the entire branch name.
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#11924 Bump maccore to get mlaunch fix.
  mk/xamarin.mk
Labels: not-notes-worthy

#11739 Fixes for .NET 6 linker
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
  tools/dotnet-linker/Extensions.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/DotNetMarkAssemblyDispatcher.cs
  tools/dotnet-linker/Steps/MarkDispatcher.cs
  tools/dotnet-linker/Steps/PostSweepDispatcher.cs
  tools/dotnet-linker/Steps/PreMarkDispatcher.cs
  tools/dotnet-linker/Steps/PreOutputDispatcher.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/linker/ApplyPreserveAttribute.cs
  tools/linker/CoreTypeMapStep.cs
  tools/linker/MarkNSObjects.cs
  tools/linker/MonoTouch.Tuner/Extensions.cs
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
  tools/linker/ObjCExtensions.cs
Labels: not-notes-worthy

#11930 [d16-10] [cloudkit] Fix obsolete message
  src/CloudKit/CKCompat.cs
Labels: backported, not-notes-worthy

#11906 [iad] Remove most of the framework
  src/AVFoundation/AVPlayerViewController.cs
  src/MediaPlayer/MPMoviePlayerController.cs
  src/ObjCRuntime/ObsoleteConstants.cs
  src/UIKit/UIViewController.cs
  src/frameworks.sources
  src/iAd/ADBannerView.cs
  src/iAd/ADCompat.cs
  src/iAd/iAd.cs
  src/iad.cs
  tests/introspection/iOS/iOSApiFieldTest.cs
  tests/monotouch-test/iAd/BannerViewTest.cs
  tests/monotouch-test/iAd/ViewControllerExtensionsTest.cs
  tests/xtro-sharpie/iOS-iAd.ignore
  tests/xtro-sharpie/iOS-iAd.todo
Labels: note-highlight

#11921 [d16-10] Remove extra (managed) setters on readonly (native) properties
  src/mlcompute.cs
  src/networkextension.cs
  src/vision.cs
  tests/xtro-sharpie/common-Vision.ignore
Labels: backported, note-highlight

#11919 [CI] Fix BRANCH_NAME to be the entire branch name.
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy, run-dotnet-tests

#11933 [d16-10][iad] Remove most of the framework
  src/AVFoundation/AVPlayerViewController.cs
  src/MediaPlayer/MPMoviePlayerController.cs
  src/ObjCRuntime/ObsoleteConstants.cs
  src/UIKit/UIViewController.cs
  src/frameworks.sources
  src/iAd/ADBannerView.cs
  src/iAd/ADCompat.cs
  src/iAd/iAd.cs
  src/iad.cs
  tests/introspection/iOS/iOSApiFieldTest.cs
  tests/monotouch-test/iAd/BannerViewTest.cs
  tests/monotouch-test/iAd/ViewControllerExtensionsTest.cs
  tests/xtro-sharpie/iOS-iAd.ignore
Labels: not-notes-worthy

#11932 [corefoundation] Fix `CFString.ToString` to cache the result
  src/CoreFoundation/CFString.cs
Labels: not-notes-worthy

#11931 [corefoundation] Simplify `CFRange`
  src/CoreFoundation/CFString.cs
Labels: not-notes-worthy

#11928 [CarPlay] Add support for Xcode13 beta1.
  src/carplay.cs
  tests/xtro-sharpie/iOS-CarPlay.ignore
  tests/xtro-sharpie/iOS-CarPlay.todo
Labels: note-highlight

#11940 [linker] Ignore `[AssemblyMetadata]` before net6
  src/Foundation/LinkerSafeAttribute.cs
  tools/common/Tuning.cs
Labels: bug

#11944 [d16-10] [linker] Ignore `[AssemblyMetadata]` before net6
  src/Foundation/LinkerSafeAttribute.cs
  tools/common/Tuning.cs
Labels: backported, bug

#11938 [mmp] Set minimum Xcode to Xcode 12 to get a better error message. Fixes #11937.
  tools/common/Driver.cs
Labels: not-notes-worthy

#11887 [dotnet] Add support for generating a binary version of runtimeconfig.json. Fixes #11745.
  dotnet/Makefile
  dotnet/Workloads/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets
  dotnet/targets/WorkloadManifest.iOS.template.json
  dotnet/targets/WorkloadManifest.tvOS.template.json
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/exports.t4
  runtime/mono-runtime.h.t4
  runtime/monovm-bridge.m
  runtime/runtime.m
  runtime/xamarin/main.h
  runtime/xamarin/runtime.h
  tests/common/DotNet.cs
  tests/dotnet/MySingleView/Makefile
  tools/common/Target.cs
  tools/dotnet-linker/Compat.cs
  tools/dotnet-linker/LinkerConfiguration.cs
Labels: not-notes-worthy, run-dotnet-tests

#11939 [tests] Re-enable tests ignored due to dotnet/runtime #36897
  tests/introspection/ApiCMAttachmentTest.cs
  tests/linker/ios/link sdk/AsyncTest.cs
  tests/linker/ios/link sdk/CryptoTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/monotouch-test/Foundation/UrlCredentialTest.cs
  tests/monotouch-test/Security/CertificateTest.cs
  tests/monotouch-test/Security/KeyTest.cs
  tests/monotouch-test/Security/RecordTest.cs
  tests/monotouch-test/Security/TrustTest.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy, run-dotnet-tests

#11943 [LinkPresentation] Xcode 13 Beta 1 Changes
  src/linkpresentation.cs
  tests/xtro-sharpie/MacCatalyst-LinkPresentation.todo
  tests/xtro-sharpie/iOS-LinkPresentation.todo
  tests/xtro-sharpie/macOS-LinkPresentation.todo
Labels: note-highlight

#11942 [Classkit] Add support for Xcode13 beta1.
  src/classkit.cs
  tests/xtro-sharpie/MacCatalyst-ClassKit.todo
  tests/xtro-sharpie/iOS-ClassKit.todo
  tests/xtro-sharpie/macOS-ClassKit.todo
Labels: note-highlight

#11951 [tests][link sdk] Re-enable test for Ping for dotnet
  tests/linker/ios/link sdk/DllImportTest.cs
Labels: not-notes-worthy

#11946 Use `CFString` instead of `NSString` to get a handle from a (.net) `System.String`
  src/CoreFoundation/CFString.cs
  src/Foundation/NSString.cs
  src/PrintCore/PrintCore.cs
  src/generator.cs
  tests/perftest/TollFreeBridge.cs
Labels: enhancement

#11953 [tests][generator] Remove references to iAd.framework types
  tests/generator/sof20696157.cs
Labels: not-notes-worthy

#11958 [dotnet][tests] Remove workaround for dotnet/runtime #46908
  tests/linker/ios/link sdk/dotnet/extra-linker-defs.xml
Labels: not-notes-worthy, run-dotnet-tests

#11960 [tests][intro] Fix failures when executed on iOS 15 beta1 devices
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
Labels: not-notes-worthy

#11956 [dotnet] Change default http handler to NSUrlSessionHandler
  src/ObjCRuntime/RuntimeOptions.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy, run-dotnet-tests

#11961 [CloudKit] Add support for Xcode13 beta1.
  src/CloudKit/Enums.cs
  src/cloudkit.cs
  tests/xtro-sharpie/MacCatalyst-CloudKit.todo
  tests/xtro-sharpie/common-CloudKit.ignore
  tests/xtro-sharpie/iOS-CloudKit.todo
  tests/xtro-sharpie/macOS-CloudKit.todo
  tests/xtro-sharpie/tvOS-CloudKit.todo
  tests/xtro-sharpie/watchOS-CloudKit.todo
Labels: note-highlight

#11948 [monotouch-tests] Use a LinkDescription item to specify extra linker description files
  tests/monotouch-test/dotnet/MacCatalyst/monotouch-test.csproj
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
  tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj
Labels: not-notes-worthy

#11959 [msbuild] Treat extension-less files as static libraries when linking native code. Fixes #11954.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/LinkNativeCodeTaskBase.cs
Labels: not-notes-worthy, run-dotnet-tests

#11969 [CI] Use the same status as the tests so that we do not have pending statuses.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#11967 [CoreML] Add support for Xcode13 beta 1.
  src/coreml.cs
  tests/xtro-sharpie/iOS-CoreML.todo
  tests/xtro-sharpie/tvOS-CoreML.todo
  tests/xtro-sharpie/watchOS-CoreML.todo
Labels: note-highlight

#11949 [tools] Fix quoting quotes in StringUtils.QuoteForProcess.
  tests/mtouch/StringUtilsTest.cs
  tools/common/StringUtils.cs
Labels: not-notes-worthy, run-all-tests, skip-device-tests

#11971 Remove the option of disabling the windows-specific part of the .NET build.
  Makefile
  configure
  dotnet/Makefile
  msbuild/Makefile
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy, run-dotnet-tests

#11968 [CoreMotion] Add Xcode13 beta1 support.
  src/coremotion.cs
  tests/xtro-sharpie/MacCatalyst-CoreMotion.todo
  tests/xtro-sharpie/iOS-CoreMotion.todo
  tests/xtro-sharpie/macOS-CoreMotion.todo
  tests/xtro-sharpie/watchOS-CoreMotion.todo
Labels: note-highlight

#11963 [CoreHaptics] Add support for Xcode13 beta1.
  src/CoreHaptics/Enums.cs
  src/corehaptics.cs
  tests/xtro-sharpie/MacCatalyst-CoreHaptics.todo
  tests/xtro-sharpie/iOS-CoreHaptics.todo
  tests/xtro-sharpie/macOS-CoreHaptics.ignore
  tests/xtro-sharpie/macOS-CoreHaptics.todo
  tests/xtro-sharpie/tvOS-CoreHaptics.todo
Labels: note-highlight

#11964 [uikit] Simplify and fix (NRE) in `UIApplication`
  src/UIKit/UIApplication.cs
Labels: not-notes-worthy

#11975 Revert "[tests][monotouch-test] Ignore NSTimeZoneTest / All_28300 on dotnet as it hangs"
  tests/monotouch-test/Foundation/NSTimeZoneTest.cs
Labels: not-notes-worthy

#11976 [CI] Sign *.nupkg too. Fixes #11952.
  tools/devops/automation/templates/build/build-nugets.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/publish-nugets.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
Labels: not-notes-worthy

#11980 [corefoundation] Enable nullability on `CFString` and `NativeObject`
  src/CoreFoundation/CFString.cs
  src/CoreFoundation/NativeObject.cs
  src/CoreImage/CIFilter.cs
  src/CoreImage/CIImage.cs
  src/generator.cs
Labels: not-notes-worthy

#11978 [tests][dotnet] Clear packages before building test apps
  tests/dotnet/Makefile
  tests/dotnet/README.md
Labels: not-notes-worthy

#11974 Revert "[tests] Preserve a required method in System.Private.CoreLib to work around a bug in .NET 6. (#10426)"
  tests/monotouch-test/dotnet/MacCatalyst/monotouch-test.csproj
  tests/monotouch-test/dotnet/extra-linker-defs.xml
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
  tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
  tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj
Labels: not-notes-worthy

#11966 [CFNetwork] Add Xcode13 beta 1 support.
  src/CFNetwork/CFHost.cs
  src/CoreFoundation/CFStream.cs
  src/ObjCRuntime/ObsoleteConstants.cs
  src/Security/SecureTransport.cs
  src/Security/SslConnection.cs
  tests/xtro-sharpie/MacCatalyst-CoreFoundation.todo
  tests/xtro-sharpie/MacCatalyst-CoreServices.todo
  tests/xtro-sharpie/iOS-CoreFoundation.todo
  tests/xtro-sharpie/iOS-CoreServices.todo
  tests/xtro-sharpie/macOS-CoreFoundation.todo
  tests/xtro-sharpie/macOS-CoreServices.todo
  tests/xtro-sharpie/tvOS-CoreFoundation.todo
  tests/xtro-sharpie/tvOS-CoreServices.todo
  tests/xtro-sharpie/watchOS-CoreFoundation.todo
Labels: note-highlight

#11965 [CoreLocation] Add xcode13 beta 1 support.
  src/corelocation.cs
  tests/xtro-sharpie/MacCatalyst-CoreLocation.ignore
  tests/xtro-sharpie/MacCatalyst-CoreLocation.todo
  tests/xtro-sharpie/iOS-CoreLocation.todo
  tests/xtro-sharpie/macOS-CoreLocation.todo
  tests/xtro-sharpie/tvOS-CoreLocation.todo
  tests/xtro-sharpie/watchOS-CoreLocation.todo
Labels: note-highlight

#11981 Bump min watchOS simulator to 6.0.
  Make.config
  src/avfoundation.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
Labels: not-notes-worthy

#11979 [CoreLocationUI] Add new framework for Xcode13 beta1.
  src/corelocationui.cs
  src/frameworks.sources
  tests/mtouch/RegistrarTest.cs
  tests/xtro-sharpie/common-CoreLocationUI.ignore
  tests/xtro-sharpie/iOS-CoreLocationUI.todo
  tools/common/Frameworks.cs
  tools/mtouch/Makefile
Labels: note-highlight

#11992 Bump VSMac to use the stable release.
  Make.config
Labels: not-notes-worthy

#11995 [CI] Fix typo
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#11991 [dotnet] Only limit the default inclusion items with a condition on 'EnableDefault<Platform>Items'. Fixes #11990.
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
Labels: not-notes-worthy, run-dotnet-tests

#11945 [PhotosUI] Xcode13 PhotosUI beta1
  src/photosui.cs
  tests/xtro-sharpie/MacCatalyst-PhotosUI.ignore
  tests/xtro-sharpie/MacCatalyst-PhotosUI.todo
  tests/xtro-sharpie/iOS-PhotosUI.todo
  tests/xtro-sharpie/macOS-PhotosUI.todo
  tests/xtro-sharpie/tvOS-PhotosUI.todo
Labels: note-highlight

#11993 [CoreText] Add support for Xcode13 beta1.
  tests/xtro-sharpie/MacCatalyst-CoreText.todo
  tests/xtro-sharpie/common-CoreText.ignore
  tests/xtro-sharpie/iOS-CoreText.todo
  tests/xtro-sharpie/macOS-CoreText.ignore
  tests/xtro-sharpie/tvOS-CoreText.todo
  tests/xtro-sharpie/watchOS-CoreText.todo
Labels: not-notes-worthy
