Repository dotnet/macios, pull requests merged in 2021-05, with the labels that each got.

#11411 [release/6.0.1xx-preview4] [CI] Enable setting provisionator channel as parameter
  tools/devops/automation/build-pipeline.yml
Labels: backported, ci-failure

#11410 [d16-10] [CI] Enable setting provisionator channel as parameter
  tools/devops/automation/build-pipeline.yml
Labels: backported, ci-failure

#11378 [dotnet][msbuild] Strip symbols from native executable
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Labels: not-notes-worthy

#11393 [dotnet][p4] Catalyst does not support ICU (yet)
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#11409 [Generator Diff] Ignore file we are not interested in.
  tools/compare-commits.sh
Labels: not-notes-worthy

#11408 [Tests] Update xamarin domain to make tests not fail.
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
  tests/monotouch-test/example.pac
Labels: not-notes-worthy

#11358 [CI] Allow to enable or disable the dotnet builds.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-azure.yml
Labels: not-notes-worthy

#11419 [release/6.0.1xx-preview4] [Tests] Update xamarin domain to make tests not fail.
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
  tests/monotouch-test/example.pac
Labels: backported, not-notes-worthy

#11414 [d16-10] [Generator Diff] Ignore file we are not interested in.
  tools/compare-commits.sh
Labels: backported, not-notes-worthy

#11415 [release/6.0.1xx-preview4] [Generator Diff] Ignore file we are not interested in.
  tools/compare-commits.sh
Labels: backported, not-notes-worthy

#11413 [xcode12.5] [Generator Diff] Ignore file we are not interested in.
  tools/compare-commits.sh
Labels: backported, not-notes-worthy

#11416 [d16-10] [Tests] Update xamarin domain to make tests not fail.
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
  tests/monotouch-test/example.pac
Labels: backported, not-notes-worthy

#11418 [xcode12.5] [Tests] Update xamarin domain to make tests not fail.
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
  tests/monotouch-test/example.pac
Labels: backported, not-notes-worthy

#11417 [d16-9] [Tests] Update xamarin domain to make tests not fail.
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
  tests/monotouch-test/example.pac
Labels: backported, not-notes-worthy

#11399 [release/6.0.1xx-preview4] [dotnet] Fixes _RunILLink from Windows for Preview 4
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy

#11420 [CI] Just requests translations in the cron job.
  tools/devops/automation/templates/build/configure.yml
Labels: not-notes-worthy

#11422 [tests][dotnet] Bump MSBuild.StructuredLogger to 2.1.472 to fix ArgumentNullException in our tests
  tests/bgen/bgen-tests.csproj
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/generator/generator-tests.csproj
  tests/mmptest/mmptest.csproj
  tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj
  tests/mtouch/mtouch.csproj
Labels: not-notes-worthy

#11381 [runtime] Call into managed code to handle runtime exceptions.
  runtime/delegates.t4
  runtime/exports.t4
  runtime/runtime.m
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy

#11382 [runtime] Return the exception from wrapper methods for exception marshalling.
  runtime/bindings-generator.cs
  runtime/bindings.h
  runtime/bindings.m
  runtime/runtime.m
  runtime/xamarin/runtime.h
  src/ObjCRuntime/Runtime.cs
  src/gameplaykit.cs
  src/generator.cs
  src/spritekit.cs
  tests/generator/BGenTests.cs
  tests/generator/bug31788.cs
  tests/mtouch/MTouch.cs
  tools/mtouch/Makefile
Labels: not-notes-worthy

#11397 [mlaunch] Don't ship for MacCatalyst.
  tools/mlaunch/Makefile
Labels: not-notes-worthy

#11402 [CoreGraphics] Don't exclude ARM64 code path on macOS anymore.
  src/CoreGraphics/CGColorConversionInfo.cs
Labels: not-notes-worthy

#11407 [runtime] Never disable exception marshalling for CoreCLR.
  runtime/exports.t4
  runtime/runtime.m
Labels: not-notes-worthy

#11400 [tests] Make the mtouch test project reference the actual mtouch project.
  Xamarin.iOS.sln
  tests/mtouch/Makefile
  tests/mtouch/SdkTest.cs
  tests/mtouch/mtouchtests.csproj
  tests/mtouch/mtouchtests.sln
  tests/tests.sln
  tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
  tools/common/ErrorHelper.tools.cs
Labels: not-notes-worthy

#11398 [runtime] Implement mono_object_get_class for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/runtime.m
  runtime/trampolines.m
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11423 d16-9 keychain removal
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/devices/build.yml
Labels: ci-failure

#11427 [runtime] Implement mono_object_isinst for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11428 [CI] Do not clutter the nuget feed with PR build nugets.
  tools/devops/automation/templates/build/build-nugets.yml
Labels: not-notes-worthy

#11431 [CI] Create post pipelines that will publish html results.
  tools/devops/automation/publish-ci-html-results.yml
  tools/devops/automation/publish-pr-html-results.yml
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/publish-html-result.yml
Labels: not-notes-worthy

#11435 [CI] Fix broken template after merge.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/devices/build.yml
Labels: not-notes-worthy

#11433 [msbuild/dotnet] Fix build logic when using .NET to not try to use nor require any version of installed Xamarin.iOS/Xamarin.Mac. Fixes #10827.
  builds/Makefile
  dotnet/targets/Xamarin.Shared.Sdk.props
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
Labels: not-notes-worthy

#11438 [release/6.0.1xx-preview4] [msbuild/dotnet] Fix build logic when using .NET to not try to use nor require any version of installed Xamarin.iOS/Xamarin.Mac. Fixes #10827.
  builds/Makefile
  dotnet/targets/Xamarin.Shared.Sdk.props
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
Labels: backported, not-notes-worthy

#11437 [dotnet][linker] Only register assemblies that we're not deleting from the bundle
  tools/dotnet-linker/Steps/RegistrarStep.cs
Labels: not-notes-worthy

#11424 [dotnet][linker] Add a shared ILLink.LinkAttributes.xml file for the platform assemblies
  src/ILLink.LinkAttributes.xml.in
  src/Makefile
Labels: not-notes-worthy

#11440 [runtime] Print more information about the exception for unhandled managed exceptions.
  runtime/coreclr-bridge.m
Labels: not-notes-worthy

#11434 [d16-10] [CI] Do not clutter the nuget feed with PR build nugets.
  tools/devops/automation/templates/build/build-nugets.yml
Labels: backported, not-notes-worthy

#11446 [tests][dotnet] A few helping touch to do size comparison
  tests/dotnet/.gitignore
  tests/dotnet/Makefile
  tools/app-compare/AppComparer.cs
Labels: not-notes-worthy

#11356 Use yaml-templates agent pool selector
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/agent-pool-selector.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#11452 [CI] Remove apitest from the tests executed in older macs.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#11453 [CI] Dump the hardware of the bot to see if we are virtual.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#11439 [runtime] Implement mono_runtime_invoke for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/monovm-bridge.m
  src/ObjCRuntime/Runtime.CoreCLR.cs
  tools/mtouch/Errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#11451 [dotnet] Fix _DetectSdkLocations from Windows
  dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.props
  dotnet/targets/Xamarin.Shared.Sdk.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#11436 [dotnet] rename workload to Microsoft.NET.Sdk._platform_.Manifest-6.0.100
  dotnet/.gitignore
  dotnet/HIERARCHY.md
  dotnet/Makefile
  dotnet/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets
  dotnet/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
  dotnet/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets
  dotnet/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets
  dotnet/Microsoft.NET.Sdk.watchOS/WorkloadManifest.targets
  dotnet/package/Microsoft.NET.Sdk.MacCatalyst/package.csproj
  dotnet/package/Microsoft.NET.Sdk.iOS/package.csproj
  dotnet/package/Microsoft.NET.Sdk.macOS/package.csproj
  dotnet/package/Microsoft.NET.Sdk.tvOS/package.csproj
  dotnet/package/microsoft.workloads.csproj
  dotnet/targets/WorkloadManifest.template.json
  dotnet/targets/WorkloadManifest.windows.template.json
Labels: not-notes-worthy

#11457 [dotnet][linker] Do not remove `[LinkWith]` using xml
  src/ILLink.LinkAttributes.xml.in
Labels: not-notes-worthy

#11465 [runtime] Implement mono_method_signature and related signature methods for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/mono-runtime.h.t4
  runtime/monovm-bridge.m
  runtime/runtime.m
  runtime/trampolines-invoke.m
  runtime/xamarin/coreclr-bridge.h
  runtime/xamarin/runtime.h
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11460 [CI] Store the config in a json to later be shared with other pipelines.
  tools/devops/automation/templates/build/configure.yml
Labels: not-notes-worthy

#11463 [release/6.0.1xx-preview4] [CI] Dump the hardware of the bot to see if we are virtual.
  tools/devops/automation/templates/mac/build.yml
Labels: backported, not-notes-worthy

#11458 [d16-10] [CI] Remove apitest from the tests executed in older macs.
  tools/devops/automation/templates/mac/build.yml
Labels: backported, not-notes-worthy

#11469 [release/6.0.1xx-preview4] [dotnet] Fix _DetectSdkLocations from Windows.
  dotnet/WindowsTargets/Xamarin.Shared.Sdk.Before.targets
  dotnet/targets/Xamarin.Shared.Sdk.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#11471 [CI] Detect if we are running a vm and set the vendor.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#11474 [linker] Split CoreTypeMapStep into two parts
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/linker/CoreTypeMapStep.cs
  tools/linker/RegistrarRemovalTrackingStep.cs
  tools/mtouch/Tuning.mtouch.cs
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#11470 [runtime] Implement mono_class_from_mono_type for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/runtime.m
  runtime/trampolines-invoke.m
  runtime/trampolines.m
  src/ObjCRuntime/Runtime.CoreCLR.cs
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#11472 [Localization] Enabling OneLocBuild for every build
  tools/devops/automation/templates/build/configure.yml
Labels: do-not-merge, not-notes-worthy

#11476 [runtime] Implement mono_class_is_delegate for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11459 [release/6.0.1xx-preview4] [CI] Remove apitest from the tests executed in older macs.
  tools/devops/automation/templates/mac/build.yml
Labels: backported, not-notes-worthy

#11462 [d16-10] [CI] Dump the hardware of the bot to see if we are virtual.
  tools/devops/automation/templates/mac/build.yml
Labels: backported, not-notes-worthy

#11478 [Localization] Using old translations for our MSBuild localization
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationStringTest.cs
  tests/mtouch/LocalizationTests.cs
Labels: not-notes-worthy

#11480 [runtime] Implement mono_thread_detach_if_exiting and mono_free for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/exports.t4
Labels: not-notes-worthy

#11479 Updated Xamarin.Messaging version
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#11482 [runtime] Implement mono_class_is_[valuetype|byref] for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11484 [runtime] Implement mono_type_get_object for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/exports.t4
  runtime/mono-runtime.h.t4
  runtime/runtime.m
  runtime/trampolines-invoke.m
  runtime/trampolines.m
  runtime/xamarin/runtime.h
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#11486 Bump system mono to get fix for #11475.
  Make.config
Labels: not-notes-worthy

#11489 [MetalPerformanceShaders] Stop excluding ARM64-specific code paths from macOS.
  src/MetalPerformanceShaders/MPSStateResourceList.cs
Labels: not-notes-worthy

#11488 [runtime] Implement mono_method_get_object for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/exports.t4
  runtime/runtime.m
  runtime/trampolines-invoke.m
Labels: not-notes-worthy

#11494 [runtime] Implement mono_class_get_type for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/exports.t4
  runtime/runtime.m
  runtime/trampolines.m
Labels: not-notes-worthy

#11493 [runtime] Implement mono_object_unbox for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/exports.t4
  runtime/xamarin/coreclr-bridge.h
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11492 [runtime] Implement mono_string_new and mono_string_to_utf8 for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/mono-runtime.h.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11502 [Translations] Fix error message format with an extra brace.
  tools/mtouch/TranslatedAssemblies/Errors.cs.resx
  tools/mtouch/TranslatedAssemblies/Errors.de.resx
  tools/mtouch/TranslatedAssemblies/Errors.es.resx
  tools/mtouch/TranslatedAssemblies/Errors.fr.resx
  tools/mtouch/TranslatedAssemblies/Errors.hu.resx
  tools/mtouch/TranslatedAssemblies/Errors.it.resx
  tools/mtouch/TranslatedAssemblies/Errors.ja.resx
  tools/mtouch/TranslatedAssemblies/Errors.ko.resx
  tools/mtouch/TranslatedAssemblies/Errors.nl.resx
  tools/mtouch/TranslatedAssemblies/Errors.pl.resx
  tools/mtouch/TranslatedAssemblies/Errors.pt-BR.resx
  tools/mtouch/TranslatedAssemblies/Errors.pt-PT.resx
  tools/mtouch/TranslatedAssemblies/Errors.ru.resx
  tools/mtouch/TranslatedAssemblies/Errors.sv.resx
  tools/mtouch/TranslatedAssemblies/Errors.tr.resx
  tools/mtouch/TranslatedAssemblies/Errors.zh-Hans.resx
  tools/mtouch/TranslatedAssemblies/Errors.zh-Hant.resx
Labels: notes-mention

#11500 [runtime] Implement mono_class_get_element_class for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/trampolines.m
  src/ObjCRuntime/Runtime.CoreCLR.cs
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#11501 Improve support for ARM64 on macOS.
  runtime/Makefile
  runtime/runtime.m
  runtime/trampolines-arm64-asm.s
  runtime/trampolines-arm64-objc_msgSend.inc.s
  runtime/trampolines-arm64-objc_msgSend.s
  runtime/trampolines-arm64-objc_msgSendSuper.s
  src/ObjCRuntime/DynamicRegistrar.cs
  src/ObjCRuntime/Registrar.cs
  tests/bindings-test/macOS/bindings-test.csproj
  tests/monotouch-test/CoreFoundation/BundleTest.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/ObjCRuntime/TrampolineTest.cs
  tests/test-libraries/testgenerator.cs
  tests/xammac_tests/xammac_tests.csproj
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/TestData.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tools/common/StaticRegistrar.cs
  tools/common/Target.cs
Labels: not-notes-worthy

#11499 [tests] Make ImageCaptioningTest.SetCaption restore the original value at the end.
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
Labels: not-notes-worthy

#11516 [xharness] Add ARM64 variations for macOS/.NET using both MonoVM and CoreCLR.
  tests/xharness/Jenkins/TestData.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#11515 [runtime] Implement mono_array_new and mono_array_length for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/trampolines-invoke.m
  runtime/trampolines.m
  runtime/xamarin/trampolines.h
  src/ObjCRuntime/Runtime.CoreCLR.cs
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#11514 [runtime] Implement mono_get_string_class for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/trampolines.m
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11509 [Translations] Remove ) that does not close (.
  tools/mtouch/Errors.resx
  tools/mtouch/xlf/Errors.cs.xlf
  tools/mtouch/xlf/Errors.de.xlf
  tools/mtouch/xlf/Errors.es.xlf
  tools/mtouch/xlf/Errors.fr.xlf
  tools/mtouch/xlf/Errors.it.xlf
  tools/mtouch/xlf/Errors.ja.xlf
  tools/mtouch/xlf/Errors.ko.xlf
  tools/mtouch/xlf/Errors.pl.xlf
  tools/mtouch/xlf/Errors.pt-BR.xlf
  tools/mtouch/xlf/Errors.ru.xlf
  tools/mtouch/xlf/Errors.tr.xlf
  tools/mtouch/xlf/Errors.zh-Hans.xlf
  tools/mtouch/xlf/Errors.zh-Hant.xlf
Labels: not-notes-worthy

#11508 [Tests] Allow to assert on device and not vm on macOS.
  tests/common/TestRuntime.cs
Labels: not-notes-worthy

#11503 [d16-10] [tests][xtro] Fix catalyst changes with xcode12.5 RC. Fixes #11308.
  tests/xtro-sharpie/MacCatalyst-Metal.todo
Labels: backported, not-notes-worthy, run-xtro-tests

#11374 Update to new linker custom steps API
  tests/linker/ios/link all/PreserveTest.cs
  tools/dotnet-linker/ApplyPreserveAttributeBase.cs
  tools/dotnet-linker/SetupStep.cs
  tools/dotnet-linker/Steps/ConfigurationAwareMarkHandler.cs
  tools/dotnet-linker/Steps/DotNetMarkAssemblyDispatcher.cs
  tools/dotnet-linker/Steps/ExceptionalMarkHandler.cs
  tools/dotnet-linker/Steps/PreserveBlockCodeHandler.cs
  tools/dotnet-linker/Steps/PreserveBlockCodeSubStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/linker/ApplyPreserveAttribute.cs
  tools/linker/CoreOptimizeGeneratedCode.cs
  tools/linker/MarkNSObjects.cs
  tools/linker/MonoTouch.Tuner/PreserveSmartEnumConversions.cs
  tools/linker/RegistrarRemovalTrackingStep.cs
  tools/mmp/mmp.csproj
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy, run-all-tests, skip-device-tests

#11513 [runtime] Implement mono_reflection_type_get_type for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/exports.t4
  runtime/runtime.m
  runtime/trampolines-invoke.m
Labels: not-notes-worthy

#11520 [CoreCLR] Stub out RegisterToggleRef for CoreCLR.
  src/Foundation/NSObject2.cs
  src/ObjCRuntime/Runtime.CoreCLR.cs
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy

#11518 [CI] Adding changes to make sure tests are not run in scheduled builds
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#11461 [CI] Use stage names and clean the triggers.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/publish-ci-html-results.yml
  tools/devops/automation/publish-pr-html-results.yml
  tools/devops/automation/templates/devices/stage.yml
  tools/devops/automation/templates/mac/stage.yml
Labels: not-notes-worthy

#11522 [dotnet][generator] Fix creating 3rd party bindings
  src/generator-attribute-manager.cs
Labels: not-notes-worthy

#11523 [dotnet][linker] Fix the elimitation of calls for `UIApplication::EnsureUIThread`
  tools/linker/CoreOptimizeGeneratedCode.cs
Labels: not-notes-worthy

#11519 [runtime] Implement functions for getting and setting array elements for CoreCLR.
  runtime/delegates.inc.t4
  runtime/delegates.t4
  runtime/mono-runtime.h.t4
  runtime/trampolines.m
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11521 [CoreCLR] Stub out mono_runtime_set_pending_exception for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/mono-runtime.h.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11524 [Tests] Ignore tests that fail on VMs
  tests/common/TestRuntime.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/monotouch-test/CoreAnimation/CAOpenGLLayer.cs
  tests/monotouch-test/ObjCRuntime/DelegateAndDataSourceTest.cs
Labels: not-notes-worthy

#11526 [CI] Remove noise added when debugging at the start of the CI move.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#11512 [Localization] Change LanguageSet and Dependencies
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.hu.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.nl.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-PT.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.sv.resx
  msbuild/Xamarin.Localization.MSBuild/Xamarin.Localization.MSBuild.csproj
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationIgnore/common-Translations.ignore
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/LocalizationStringTest.cs
  tests/mtouch/LocalizationTests.cs
  tools/devops/LocProject.json.in
  tools/dotnet-linker/dotnet-linker.csproj
  tools/mmp/mmp.csproj
  tools/mtouch/TranslatedAssemblies/Errors.hu.resx
  tools/mtouch/TranslatedAssemblies/Errors.nl.resx
  tools/mtouch/TranslatedAssemblies/Errors.pt-PT.resx
  tools/mtouch/TranslatedAssemblies/Errors.sv.resx
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy

#11529 Update the README with download links for d16-8 and d16-9 packages.
  README.md
Labels: not-notes-worthy

#11532 [runtime] Fix call to xamarin_print_all_exceptions.
  runtime/runtime.m
Labels: not-notes-worthy

#11533 [runtime] Implement mono_value_box for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
Labels: not-notes-worthy

#11531 [runtime] Implement mono_class_get_nullable_param for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/trampolines.m
  src/ObjCRuntime/Runtime.CoreCLR.cs
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#11530 [runtime] Refactor xamarin_get_nsnumber_converter to use string comparisons instead of mono_type_get_type.
  runtime/exports.t4
  runtime/trampolines.m
Labels: not-notes-worthy

#11541 [MediaToolbox] Don't use Action<T> in reverse P/Invokes.
  src/MediaToolbox/MTAudioProcessingTap.cs
Labels: not-notes-worthy

#11535 [tools] Make exception marshalling the default for CoreCLR (and make it an error to choose otherwise).
  runtime/runtime.m
  tools/common/Application.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
Labels: not-notes-worthy

#11528 [runtime] Implement mono_class_is_nullable for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11536 [runtime] Implement mono_method_full_name for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11542 [tests][intro] Add back `[Test]` on some methods
  tests/introspection/ApiPInvokeTest.cs
Labels: not-notes-worthy

#11527 [dotnet][tests] Fix monotouch-test RegistrarRemoval
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/dotnet/iOS/monotouch-test.csproj
  tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
  tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#11525 [CI] If the api & generator is not built do not fail the build.
  tools/devops/automation/scripts/bash/vsts-compare.sh
  tools/devops/automation/templates/build/api-diff.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
Labels: not-notes-worthy

#11549 [dotnet][tests][link sdk] Remove [Ignore] for https://github.com/dotnet/runtime/issues/49201
  tests/linker/ios/link sdk/PclTest.cs
Labels: not-notes-worthy

#11551 [dotnet][tests][link all] Ignore failures on devices
  tests/linker/ios/link all/DataContractTest.cs
  tests/linker/ios/link all/LinkAllTest.cs
Labels: not-notes-worthy

#11537 [msbuild] Add support for smelting metal for Mac Catalyst.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MetalTaskBase.cs
Labels: not-notes-worthy

#11538 [runtime] Add support for creating managed exceptions from native code for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  runtime/monovm-bridge.m
  runtime/runtime.m
  runtime/xamarin/main.h
  runtime/xamarin/runtime.h
  src/ObjCRuntime/Runtime.CoreCLR.cs
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#11550 [runtime] Make xamarin_bridge_free_mono_signature accept NULL signatures.
  runtime/coreclr-bridge.m
Labels: not-notes-worthy

#11552 [runtime] Implement xamarin_get_[nsnumber|nsvalue]_type for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/monovm-bridge.m
  runtime/trampolines.m
  runtime/xamarin/runtime.h
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11556 [Tests] Undo change that broke intro in BS.
  tests/introspection/Mac/MacApiProtocolTest.cs
Labels: not-notes-worthy

#11559 [d16-10] [apidiff] Bump definitions now that `xcode12.5` support is on stable
  Make.config
Labels: backported, not-notes-worthy

#11558 [apidiff] Bump definitions now that `xcode12.5` support is on stable
  Make.config
Labels: not-notes-worthy

#11557 [dotnet][tests][intro] Update ApiPInvokeTest
  tests/introspection/ApiPInvokeTest.cs
Labels: not-notes-worthy

#11553 [runtime] Implement mono_class_is_enum and mono_class_enum_basetype for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11554 [runtime] Implement mono_class_value_size for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/exports.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11564 [CI] Backport all changes in the CI from main to d16-10.
  tools/devops/LocProject.json.in
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/publish-pr-html-results.yml
  tools/devops/automation/scripts/bash/vsts-compare.sh
  tools/devops/automation/templates/build/api-diff.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-azure.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
  tools/devops/automation/templates/devices/stage.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/mac/stage.yml
  tools/devops/automation/templates/publish-html-result.yml
Labels: not-notes-worthy

#11565 [release-preview 4][CI] Backport all changes in the CI from main to release preview 4.
  tools/devops/LocProject.json.in
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/publish-pr-html-results.yml
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/scripts/bash/compare.sh
  tools/devops/automation/scripts/bash/local-compare.sh
  tools/devops/automation/scripts/bash/vsts-compare.sh
  tools/devops/automation/templates/build/api-diff.yml
  tools/devops/automation/templates/build/build-nugets.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-azure.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/devices/stage.yml
  tools/devops/automation/templates/governance-checks.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/mac/stage.yml
  tools/devops/automation/templates/publish-html-result.yml
Labels: not-notes-worthy

#11560 [CoreGraphics] Adjust CGPDFOperatorTable to not use a generic Action delegate.
  src/CoreGraphics/CGPDFOperatorTable.cs
  tests/monotouch-test/CoreGraphics/PDFScannerTest.cs
Labels: not-notes-worthy

#11571 [CI] Do run 32b tests.
  tests/Makefile
Labels: not-notes-worthy

#11567 [src] Fix some breaking changes detected when bumping APIDIFF
  src/AudioUnit/AUEnums.cs
  src/UIKit/UIEnums.cs
  src/authenticationservices.cs
Labels: not-notes-worthy

#11578 [d16-10] [CI] Do run 32b tests.
  tests/Makefile
Labels: backported, not-notes-worthy

#11582 [ObjCRuntime] Fix pointer logic with regards to MonoObject*s.
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11586 [d16-10] [src] Fix some breaking changes detected when bumping APIDIFF
  src/AudioUnit/AUEnums.cs
  src/UIKit/UIEnums.cs
  src/authenticationservices.cs
Labels: backported, not-notes-worthy

#11585 [msbuild] Fix error message MSBStrings.W0073 -> W0074
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ValidateAppBundleTaskBase.cs
Labels: bug

#11583 [xharness] Add a variation that uses the static registrar for monotouch-test/.NET/CoreCLR.
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#11584 [registrar] Define CORECLR_RUNTIME when in the generated registrar code for CoreCLR
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#11594 [Runtime/CoreCLR] Only read/write a single byte for booleans when marshalling parameters in dynamic method calls for CoreCLR.
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11592 [dotnet] Don't use an Output property to retrieve the list of native object files to link.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#11577 [dotnet][linker] Eliminate code that is only required for CoreCLR on iOS and tvOS
  runtime/Delegates.cs.t4
  src/ILLink.Substitutions.ios.xml
  src/ILLink.Substitutions.tvos.xml
  src/Makefile
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy

#11588 [Runtime] Don't skip dynamic user type checking as long as dynamic registration is supported.
  src/ObjCRuntime/Runtime.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
  tests/test-libraries/Makefile
  tests/test-libraries/custom-type-assembly/Makefile
  tests/test-libraries/custom-type-assembly/custom-type-assembly.cs
  tests/xammac_tests/xammac_tests.csproj
Labels: not-notes-worthy

#11580 [CI] Do run 32b tests. (#11571)
  tests/Makefile
Labels: backported, not-notes-worthy

#11591 [d16-10] [msbuild] Fix error message MSBStrings.W0073 -> W0074
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/ValidateAppBundleTaskBase.cs
Labels: backported, bug

#11595 [CoreCLR] Disable debug spew by default.
  runtime/xamarin/coreclr-bridge.h
Labels: not-notes-worthy

#11539 [tests] Add a .NET/MacCatalyst variation of monotouch-test.
  src/Makefile
  tests/EmbeddedResources/ResourcesTest.cs
  tests/monotouch-test/Foundation/LocaleTest.cs
  tests/monotouch-test/UIKit/SearchDisplayControllerTest.cs
  tests/monotouch-test/dotnet/MacCatalyst/Info.plist
  tests/monotouch-test/dotnet/MacCatalyst/monotouch-test.csproj
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tests/xharness/MacFlavorsExtensions.cs
  tests/xharness/MacTestProject.cs
Labels: not-notes-worthy

#11599 [runtime] Throw a runtime exception instead of execution engine exception.
  runtime/exports.t4
  runtime/runtime.m
  runtime/trampolines-invoke.m
  tools/mtouch/Errors.resx
Labels: not-notes-worthy

#11601 [runtime] Be a bit defensive after handling Objective-C exceptions and return a consistent value.
  runtime/trampolines-arm64-objc_msgSend.inc.s
Labels: not-notes-worthy

#11597 [src] Add the method's name when computing a method's full name for display purposes.
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11600 [d16-10] [Runtime] Don't skip dynamic user type checking as long as dynamic registration is supported.
  src/ObjCRuntime/Runtime.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
  tests/test-libraries/Makefile
  tests/test-libraries/custom-type-assembly/Makefile
  tests/test-libraries/custom-type-assembly/custom-type-assembly.cs
  tests/xammac_tests/xammac_tests.csproj
Labels: backported

#11587 [CI] Update the config and parse it in the cascade pipeline.
  tools/devops/automation/templates/build/configure.yml
  tools/devops/automation/templates/publish-html-result.yml
Labels: not-notes-worthy

#11607 [Runtime] Make Runtime.IsUserType optimizable.
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy, run-mmp-tests

#11609 [CI] Fix API diff uploads since they broke when we wanted to continue on failure.
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
Labels: not-notes-worthy

#11602 [d16-10] [CI] If api & generator fail also ignore in publish html.
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
Labels: backported, not-notes-worthy

#11603 [Localization] Sync Localization branch with Main
  tools/devops/automation/templates/build/configure.yml
Labels: not-notes-worthy

#11608 [runtime] Implement mono_get_exception_out_of_memory for CoreCLR.
  runtime/coreclr-bridge.m
  runtime/exports.t4
  runtime/xamarin/main.h
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11610 [runtime] Postpone implementing mono_domain_set_config for CoreCLR.
  runtime/exports.t4
  runtime/monotouch-main.m
Labels: not-notes-worthy

#11613 [monotouch-test] Ignore the SslSupportedCiphers test on .NET due to #11498.
  tests/monotouch-test/Security/SecureTransportTest.cs
Labels: not-notes-worthy

#11614 [runtime] Fix declaration of xamarin_bridge_get_method_declaring_type.
  runtime/delegates.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#11615 [monotouch-test] Ignore tests that require exception marshalling on CoreCLR for now, they fail.
  tests/api-shared/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: not-notes-worthy

#11616 [runtime] Refactor the toggle ref code to separate MonoVM-specific code and generic logic.
  runtime/coreclr-bridge.m
  runtime/exports.t4
  runtime/monovm-bridge.m
  runtime/runtime.m
  runtime/xamarin/runtime.h
Labels: not-notes-worthy

#11617 [runtime] Remove the declarations for mono_jit_parse_options and mono_gc_max_generation.
  runtime/exports.t4
Labels: not-notes-worthy

#11618 [mmp] Don't define CORECLR_RUNTIME when compiling the partial static registrar code
  tools/mmp/Makefile
Labels: not-notes-worthy

#11625 [catalyst][adsupport] Update xtro - framework is not available
  src/AdSupport/ASCompat.cs
  src/adsupport.cs
  src/frameworks.sources
  tests/xtro-sharpie/MacCatalyst-AdSupport.ignore
  tests/xtro-sharpie/MacCatalyst-AdSupport.todo
Labels: not-notes-worthy

#11624 [catalyst][accounts] Update xtro - framework is not available
  tests/xtro-sharpie/MacCatalyst-Accounts.ignore
Labels: not-notes-worthy
