Repository dotnet/macios, pull requests merged in 2022-12, with the labels that each got.

#16806 [release/7.0.1xx] [tests] Ignore PassLibraryTest.PassLibraryTest on bots if PKPassLibrary.GetPasses returns null. Fixes #xamarin/maccore@2598.
  tests/monotouch-test/PassKit/PassLibraryTest.cs
Labels: backported

#16807 [release/6.0.4xx-xcode14.1] [tests] Ignore PassLibraryTest.PassLibraryTest on bots if PKPassLibrary.GetPasses returns null. Fixes #xamarin/maccore@2598.
  tests/monotouch-test/PassKit/PassLibraryTest.cs
Labels: backported

#16940 [actions] Fix parsing problem in the changelog action.
  .github/workflows/maestro-changelog.yml
Labels: skip-all-tests, skip-api-comparison

#16943 [release/6.0.4xx-xcode14.1] [Foundation] Fix random memory access / memory corruption in NSFastEnumerator. Fixes #xamarin/maccore@1347.
  src/Foundation/NSFastEnumerationState.cs
  src/Foundation/NSFastEnumerator.cs
Labels: backported

#16941 [xcode14.1] [Foundation] Fix random memory access / memory corruption in NSFastEnumerator. Fixes #xamarin/maccore@1347.
  src/Foundation/NSFastEnumerationState.cs
  src/Foundation/NSFastEnumerator.cs
Labels: backported

#16929 [perf] Update Delete Task to use DeleteFilesAsync.
  msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Delete.cs
Labels: performance

#16970 [dotnet-linker] Handle null fields in BackingFieldDelayHandler as unmarked fields. Fixes #16957.
  tests/linker/CommonLinkAnyTest.cs
  tools/dotnet-linker/BackingFieldDelayHandler.cs
Labels: bug

#16996 [release/7.0.1xx] [dotnet-linker] Handle null fields in BackingFieldDelayHandler as unmarked fields. Fixes #16957.
  tests/linker/CommonLinkAnyTest.cs
  tools/dotnet-linker/BackingFieldDelayHandler.cs
Labels: bug, backported

#17012 [xcode14.1] [Foundation] Handle re-entrancy in NSObject_Disposer.Drain. Fixes #16587.
  src/Foundation/NSObject2.cs
Labels: bug

#16992 [CoreMidi] Fixed MidiPacket.Bytes IndexOutOfRangeException. Fixes #16979.
  src/CoreMidi/MidiServices.cs
Labels: bug, community

#17022 [release/7.0.1xx] [CoreMidi] Fixed MidiPacket.Bytes IndexOutOfRangeException. Fixes #16979.
  src/CoreMidi/MidiServices.cs
Labels: bug, community, backported

#17021 [xcode14.1] [CoreMidi] Fixed MidiPacket.Bytes IndexOutOfRangeException. Fixes #16979.
  src/CoreMidi/MidiServices.cs
Labels: bug, community, backported

#17016 [dotnet] handle arrays to make blittable
  src/CoreGraphics/CGColor.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGContext.cs
  src/CoreGraphics/CGFunction.cs
  src/CoreGraphics/CGGradient.cs
  src/CoreGraphics/CGImage.cs
  src/CoreGraphics/CGPath.cs
  src/CoreText/CTFont.cs
Labels: enhancement

#16710 Bump API references to the Xcode 14.1 release.
  Make.config
  tools/apidiff/Makefile
Labels: skip-all-tests

#17031 [release/6.0.4xx-xcode14.2] Bump bindings to Xcode 14.2
  Make.config
  Make.versions
  Versions-ios.plist.in
  Versions-mac.plist.in
  src/BusinessChat/Enums.cs
  src/businesschat.cs
  src/gamekit.cs
  src/intents.cs
  src/screencapturekit.cs
  src/sharedwithyou.cs
  src/uikit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Matter.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Matter.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-SensorKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Matter.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-Matter.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-Matter.todo
  tests/xtro-sharpie/iOS-BusinessChat.ignore
  tests/xtro-sharpie/iOS-Matter.ignore
  tests/xtro-sharpie/iOS-Matter.todo
  tests/xtro-sharpie/iOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/iOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/iOS-SensorKit.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/macOS-Matter.ignore
  tests/xtro-sharpie/macOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/tvOS-Matter.ignore
  tests/xtro-sharpie/tvOS-Matter.todo
  tests/xtro-sharpie/watchOS-Matter.ignore
  tests/xtro-sharpie/watchOS-Matter.todo
Labels: backported

#17030 [xcode14.2] Bump bindings to Xcode 14.2
  Make.config
  Make.versions
  Versions-ios.plist.in
  Versions-mac.plist.in
  src/BusinessChat/Enums.cs
  src/businesschat.cs
  src/gamekit.cs
  src/intents.cs
  src/screencapturekit.cs
  src/sharedwithyou.cs
  src/uikit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Matter.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Matter.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-SensorKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Matter.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-Matter.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-Matter.todo
  tests/xtro-sharpie/iOS-BusinessChat.ignore
  tests/xtro-sharpie/iOS-Matter.ignore
  tests/xtro-sharpie/iOS-Matter.todo
  tests/xtro-sharpie/iOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/iOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/iOS-SensorKit.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/macOS-Matter.ignore
  tests/xtro-sharpie/macOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/tvOS-Matter.ignore
  tests/xtro-sharpie/tvOS-Matter.todo
  tests/xtro-sharpie/watchOS-Matter.ignore
  tests/xtro-sharpie/watchOS-Matter.todo
Labels: backported

#17004 Fix WatchKit stub copy error when using native watchOS app
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Common.targets
Labels: community

#17040 [release/7.0.1xx] Bump API references to the Xcode 14.1 release.
  Make.config
  tools/apidiff/Makefile
Labels: skip-all-tests, backported

#17052 [release/6.0.4xx-xcode14.2] Bump API references to the Xcode 14.1 release.
  Make.config
Labels: skip-all-tests

#17053 [release/6.0.4xx] Bump API references to the Xcode 14.1 release.
  Make.config
Labels: skip-all-tests

#17041 [xcode14.1] Bump API references to the Xcode 14.1 release.
  Make.config
  tools/apidiff/Makefile
  tools/compare-commits.sh
Labels: skip-all-tests, backported

#17050 [xcode14.2] Bump API references to the Xcode 14.1 release.
  Make.config
  tools/apidiff/Makefile
  tools/compare-commits.sh
Labels: skip-all-tests, backported

#17048 [main] Fix WatchKit stub copy error when using native watchOS app
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Common.targets
Labels: community, backported

#17047 [xcode14.2] Fix WatchKit stub copy error when using native watchOS app
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Common.targets
Labels: community, backported

#17051 [release/7.0.1xx-xcode14.2] Bump API references to the Xcode 14.1 release.
  Make.config
  tools/apidiff/Makefile
Labels: skip-all-tests, backported

#17025 [net8.0] Bump .NET 6 versions.
  Make.versions
Labels: not-notes-worthy

#17055 [tests] Assert that we don't have any private IntPtr constructors in cecil-tests.
  tests/cecil-tests/ConstructorTest.cs
Labels: do-not-merge

#17054 [dotnet] security string pinvokes
  src/ObjCRuntime/TransientString.cs
  src/Security/SecProtocolMetadata.cs
  src/frameworks.sources
Labels: dotnet

#17063 [xcode14.2] [tests] Ignore the MonoTests.System.TimeZoneInfoTest+IsDaylightSavingTimeTests.Bug_16395 test. Fixes #xamarin/maccore@2629.
  tests/bcl-test/common-monotouch_corlib_test.dll.ignore
  tests/bcl-test/macOS-xammac_net_4_5_corlib_test.dll.ignore
Labels: backported

#17065 [release/7.0.1xx-xcode14.2] [tests] Ignore the MonoTests.System.TimeZoneInfoTest+IsDaylightSavingTimeTests.Bug_16395 test. Fixes #xamarin/maccore@2629.
  tests/bcl-test/common-monotouch_corlib_test.dll.ignore
  tests/bcl-test/macOS-xammac_net_4_5_corlib_test.dll.ignore
Labels: backported

#16706 Fix libs reidentification deployed in a subdirectory
  builds/create-csproj-for-all-packagereferences.sh
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/AppDelegate.cs
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/MacCatalyst/AppWithNativeDynamicLibrariesInPackageReference.csproj
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/Makefile
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/macOS/AppWithNativeDynamicLibrariesInPackageReference.csproj
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/shared.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/DynamicLibrariesInRuntimesNativeDirectory.csproj
  tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/Makefile
  tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/Xamarin.Tests.DynamicLibrariesInRuntimesNativeDirectory.targets
  tests/test-libraries/nugets/Makefile
Labels: community

#17064 [release/6.0.4xx-xcode14.2] [tests] Ignore the MonoTests.System.TimeZoneInfoTest+IsDaylightSavingTimeTests.Bug_16395 test. Fixes #xamarin/maccore@2629.
  tests/bcl-test/common-monotouch_corlib_test.dll.ignore
  tests/bcl-test/macOS-xammac_net_4_5_corlib_test.dll.ignore
Labels: backported

#16513 [dotnet] Add [SupportedOSPlatformGuard] attributes to UIDevice.CheckSystemVersion. Fixes #16250.
  src/UIKit/UIDevice.cs
Labels: bug

#16871 [msbuild] Validate OutputType property
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/AppWithWinExeOutputType/AppDelegate.cs
  tests/dotnet/AppWithWinExeOutputType/Makefile
  tests/dotnet/AppWithWinExeOutputType/macOS/AppWithWinExeOutputType.csproj
  tests/dotnet/AppWithWinExeOutputType/shared.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: community

#17105 [AppKit] Try to make NSWindow.ReleasedWhenClosed work. Fixes #8606.
  src/AppKit/NSWindow.cs
  src/appkit.cs
Labels: bug
