Repository dotnet/macios, pull requests merged in 2022-02, with the labels that each got.

#13941 [ModelIO] Adopt XAMCORE_4_0 changes in .NET.
  dotnet/BreakingChanges.md
  src/ModelIO/MDLAsset.cs
  src/ModelIO/MDLTransform.cs
  src/ModelIO/MDLTransformComponent.cs
  src/modelio.cs
  tests/monotouch-test/ModelIO/MDLCameraTest.cs
  tests/monotouch-test/ModelIO/MDLMaterialProperty.cs
  tests/monotouch-test/ModelIO/MDLObject.cs
  tests/monotouch-test/ModelIO/MDLStereoscopicCameraTest.cs
  tests/monotouch-test/ModelIO/MDLTransform.cs
  tests/monotouch-test/ModelIO/MDLTransformComponentTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13984 [MediaAccessibility] Adopt XAMCORE_4_0 changes in .NET.
  src/MediaAccessibility/MediaAccessibility.cs
  src/mediaaccessibility.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-MediaAccessibility.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14001 [dotnet] Fix templates to use NativeHandle instead of IntPtr. Fixes #13979.
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/ApiDefinition.cs
  dotnet/Templates/Microsoft.iOS.Templates/iosbinding/ApiDefinition.cs
  dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.cs
  dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.cs
  tests/dotnet/UnitTests/TemplateTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests

#13889 [NET 6 Attribute Conversion] CoreVideo
  src/CoreVideo/CVBuffer.cs
  src/CoreVideo/CVDisplayLink.cs
  src/CoreVideo/CVImageBuffer.cs
  src/CoreVideo/CVMetalTexture.cs
  src/CoreVideo/CVMetalTextureCache.cs
  src/CoreVideo/CVOpenGLESTexture.cs
  src/CoreVideo/CVOpenGLESTextureCache.cs
  src/CoreVideo/CVPixelBuffer.cs
  src/CoreVideo/CVPixelBufferAttributes.cs
  src/CoreVideo/CVPixelBufferIOSurface.cs
  src/CoreVideo/CVPixelBufferPool.cs
  src/CoreVideo/CVPixelFormatDescription.cs
  src/CoreVideo/CVPixelFormatType.cs
Labels: not-notes-worthy, run-dotnet-tests

#13905 [NET 6 Attribute Conversion] Foundation
  src/Foundation/NSAttributedString.iOS.cs
  src/Foundation/NSCalendar.cs
  src/Foundation/NSCoder.cs
  src/Foundation/NSExpression.cs
  src/Foundation/NSIndexPath.cs
  src/Foundation/NSItemProvider.cs
  src/Foundation/NSLayoutConstraint.cs
  src/Foundation/NSMetadataItem.cs
  src/Foundation/NSUrlSessionConfiguration.cs
  src/Foundation/NSUserDefaults.cs
Labels: not-notes-worthy, run-dotnet-tests

#13994 [Accounts] Adopt XAMCORE_4_0 changes in .NET.
  src/accounts.cs
Labels: not-notes-worthy, run-dotnet-tests

#13987 [AppKit] Adopt XAMCORE_4_0 changes in .NET.
  src/AppKit/Enums.cs
  src/AppKit/NSApplication.cs
  src/AppKit/NSBezierPath.cs
  src/AppKit/NSCollectionView.cs
  src/AppKit/NSCollectionViewDelegate.cs
  src/AppKit/NSDraggingInfo.cs
  src/AppKit/NSDraggingItem.cs
  src/AppKit/NSDraggingSession.cs
  src/AppKit/NSLayoutManager.cs
  src/AppKit/NSMutableFontCollection.cs
  src/AppKit/NSPasteboard.cs
  src/AppKit/NSSharingServiceDelegate.cs
  src/AppKit/NSTextTableBlock.cs
  src/AppKit/NSTouch.cs
  src/AppKit/NSWorkspace.cs
  src/appkit.cs
  src/foundation.cs
  src/webkit.cs
  tests/introspection/Mac/MacApiTypoTest.cs
  tests/monotouch-test/AppKit/NSDraggingItem.cs
  tests/monotouch-test/AppKit/NSPasteboard.cs
  tests/monotouch-test/AppKit/NSSlider.cs
  tests/monotouch-test/AppKit/NSTabViewController.cs
  tests/monotouch-test/AppKit/NSWorkspace.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14004 [ObjCRuntime] Improve code to render an exception to avoid a NullReferenceException in case of invalid input.
  src/ObjCRuntime/Runtime.cs
Labels: dotnet, run-dotnet-tests

#13988 [Network] Adopt XAMCORE_4_0 changes in .NET.
  src/Network/NWBrowser.cs
  src/Network/NWProtocolDefinition.cs
  src/Network/NWProtocolMetadata.cs
  src/Network/NWProtocolStack.cs
  src/Network/NWTxtRecord.cs
  tests/monotouch-test/Network/NWBrowserTest.cs
  tests/monotouch-test/Network/NWProtocolDefinitionTest.cs
  tests/monotouch-test/Network/NWProtocolMetadataTest.cs
  tests/monotouch-test/Network/NWTxtRecordTest.cs
  tests/monotouch-test/Security/SecProtocolMetadataTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14005 [release/6.0.2xx-preview13] [dotnet] Fix templates to use NativeHandle instead of IntPtr. Fixes #13979.
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/ApiDefinition.cs
  dotnet/Templates/Microsoft.iOS.Templates/iosbinding/ApiDefinition.cs
  dotnet/Templates/Microsoft.macOS.Templates/macos/ViewController.cs
  dotnet/Templates/Microsoft.tvOS.Templates/tvos/ViewController.cs
  tests/dotnet/UnitTests/TemplateTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests, backported

#14008 [dotnet] Downgrade the linker reference.
  eng/Version.Details.xml
  eng/Versions.props
Labels: not-notes-worthy, run-dotnet-tests

#14014 [coreimage] Modernize CIFilter
  src/CoreImage/CIFilter.cs
  src/coreimage.cs
Labels: community

#14012 [FileProvider] Adopt XAMCORE_4_0 changes in .NET.
  src/fileprovider.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-FileProvider.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14009 [ExternalAccessory] Adopt XAMCORE_4_0 changes in .NET.
  src/externalaccessory.cs
Labels: not-notes-worthy, run-dotnet-tests

#14011 [dotnet] Ask the linker to not mark copied assemblies if we're in a 'don't link' scenario.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#14003 [runtime] Don't try to log an exception for GCHandle that has been freed.
  runtime/runtime.m
  runtime/xamarin/runtime.h
Labels: dotnet, run-dotnet-tests

#13997 [NET 6 Attribute Conversion] NaturalLanguage
  src/NaturalLanguage/NLModel.cs
Labels: not-notes-worthy, run-dotnet-tests

#13973 [tests] Add ILStrip with satellite assemblies lib
  tests/dotnet/MySatelliteAssembliesLibrary/MacCatalyst/MyClass.cs
  tests/dotnet/MySatelliteAssembliesLibrary/MacCatalyst/MySatelliteAssembliesLibrary.csproj
  tests/dotnet/MySatelliteAssembliesLibrary/MacCatalyst/Welcome.de.resx
  tests/dotnet/MySatelliteAssembliesLibrary/MacCatalyst/Welcome.en-AU.resx
  tests/dotnet/MySatelliteAssembliesLibrary/MacCatalyst/Welcome.es.resx
  tests/dotnet/MySatelliteAssembliesLibrary/MacCatalyst/Welcome.resx
  tests/dotnet/MySatelliteAssembliesLibrary/iOS/MyClass.cs
  tests/dotnet/MySatelliteAssembliesLibrary/iOS/MySatelliteAssembliesLibrary.csproj
  tests/dotnet/MySatelliteAssembliesLibrary/iOS/Welcome.de.resx
  tests/dotnet/MySatelliteAssembliesLibrary/iOS/Welcome.en-AU.resx
  tests/dotnet/MySatelliteAssembliesLibrary/iOS/Welcome.es.resx
  tests/dotnet/MySatelliteAssembliesLibrary/iOS/Welcome.resx
  tests/dotnet/MySatelliteAssembliesLibrary/macOS/MyClass.cs
  tests/dotnet/MySatelliteAssembliesLibrary/macOS/MySatelliteAssembliesLibrary.csproj
  tests/dotnet/MySatelliteAssembliesLibrary/macOS/Welcome.de.resx
  tests/dotnet/MySatelliteAssembliesLibrary/macOS/Welcome.en-AU.resx
  tests/dotnet/MySatelliteAssembliesLibrary/macOS/Welcome.es.resx
  tests/dotnet/MySatelliteAssembliesLibrary/macOS/Welcome.resx
  tests/dotnet/MySatelliteAssembliesLibrary/tvOS/MyClass.cs
  tests/dotnet/MySatelliteAssembliesLibrary/tvOS/MySatelliteAssembliesLibrary.csproj
  tests/dotnet/MySatelliteAssembliesLibrary/tvOS/Welcome.de.resx
  tests/dotnet/MySatelliteAssembliesLibrary/tvOS/Welcome.en-AU.resx
  tests/dotnet/MySatelliteAssembliesLibrary/tvOS/Welcome.es.resx
  tests/dotnet/MySatelliteAssembliesLibrary/tvOS/Welcome.resx
  tests/dotnet/MySimpleAppWithSatelliteReference/AppDelegate.cs
  tests/dotnet/MySimpleAppWithSatelliteReference/MacCatalyst/Makefile
  tests/dotnet/MySimpleAppWithSatelliteReference/MacCatalyst/MySimpleAppWithSatelliteReference.csproj
  tests/dotnet/MySimpleAppWithSatelliteReference/Makefile
  tests/dotnet/MySimpleAppWithSatelliteReference/iOS/Makefile
  tests/dotnet/MySimpleAppWithSatelliteReference/iOS/MySimpleAppWithSatelliteReference.csproj
  tests/dotnet/MySimpleAppWithSatelliteReference/macOS/Makefile
  tests/dotnet/MySimpleAppWithSatelliteReference/macOS/MySimpleAppWithSatelliteReference.csproj
  tests/dotnet/MySimpleAppWithSatelliteReference/shared.csproj
  tests/dotnet/MySimpleAppWithSatelliteReference/shared.mk
  tests/dotnet/MySimpleAppWithSatelliteReference/tvOS/Makefile
  tests/dotnet/MySimpleAppWithSatelliteReference/tvOS/MySimpleAppWithSatelliteReference.csproj
  tests/dotnet/UnitTests/PostBuildTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13983 [CoreImage] Adopt XAMCORE_4_0 changes in .NET.
  src/CoreImage/CIFilter.cs
  src/coreimage.cs
  tests/introspection/ApiCoreImageFiltersTest.cs
  tests/monotouch-test/CoreImage/CIFilter.cs
  tests/monotouch-test/CoreImage/FilterTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13975 [NET 6 Attribute Conversion] MediaPlayer
  src/MediaPlayer/MPMediaItem.cs
  src/MediaPlayer/MPMoviePlayerController.cs
  src/MediaPlayer/MPNowPlayingInfoCenter.cs
  src/MediaPlayer/MPPlayableContentDelegate.cs
  src/MediaPlayer/MPVolumeSettings.cs
  src/MediaPlayer/MediaPlayer.cs
Labels: not-notes-worthy, run-dotnet-tests

#14002 [runtime] Use the full managed description (including inner exceptions) as the reason when creating an NSException from a managed exception.
  runtime/runtime.m
  tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14017 [Foundation] Adopt more XAMCORE_4_0 changes in .NET.
  src/foundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13948 [NET 6 Attribute Conversion] Intents
  src/Intents/INIntentResolutionResult.cs
  src/Intents/INPerson.cs
  src/Intents/INSetClimateSettingsInCarIntent.cs
  src/Intents/INSetDefrosterSettingsInCarIntent.cs
  src/Intents/INSetProfileInCarIntent.cs
  src/Intents/INSetSeatSettingsInCarIntent.cs
Labels: not-notes-worthy, run-dotnet-tests

#13998 [NET 6 Attribute Conversion] NetworkExtension
  src/NetworkExtension/NEHotspotConfiguration.cs
  src/NetworkExtension/NEVpnManager.cs
Labels: not-notes-worthy, run-dotnet-tests

#14006 [NET 6 Attribute Conversion] ObjCRuntime
  src/ObjCRuntime/PlatformAvailability.cs
  src/ObjCRuntime/SystemVersion.cs
Labels: not-notes-worthy, run-dotnet-tests

#14007 [NET 6 Attribute Conversion] OpenGL
  src/OpenGL/CGLContext.cs
  src/OpenGL/CGLEnums.cs
  src/OpenGL/CGLPixelFormat.cs
Labels: not-notes-worthy, run-dotnet-tests

#14010 [NET 6 Attribute Conversion] OpenGLES
  src/OpenGLES/EAGLConsts.cs
  src/OpenGLES/EAGLContext.cs
Labels: not-notes-worthy, run-dotnet-tests

#14030 [SceneKit] Remove file that's not part of the build.
  src/SceneKit/SCNEnums.cs
Labels: not-notes-worthy

#14028 [AppKit] Rename NSWorkspace.OpenURL[s] to OpenUrl[s] in .NET.
  src/appkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#14027 [XKit] Adopt XAMCORE_4_0 changes in .NET.
  src/XKit/XKitCompat.cs
Labels: not-notes-worthy, run-dotnet-tests

#14024 [CoreText] Adopt XAMCORE_4_0 changes in .NET.
  src/CoreText/CTFont.cs
Labels: not-notes-worthy, run-dotnet-tests

#14023 [generator] .NET is XAMCORE v4.
  src/generator.cs
Labels: not-notes-worthy, run-dotnet-tests

#14020 [generator] Rework how we implement [Abstract] classes in .NET. Fixes #4969.
  src/generator.cs
  tests/generator/BGenTests.cs
  tests/generator/tests/abstract-type.cs
Labels: not-notes-worthy, run-dotnet-tests

#14019 [ImageKit] Adopt XAMCORE_4_0 changes in .NET.
  src/imagekit.cs
Labels: not-notes-worthy, run-dotnet-tests

#14034 Link against the Compression framework.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#14032 [NET Conversion] SensorKit
  src/SensorKit/SRAbsoluteTime.cs
  src/SensorKit/SRAmbientLightChromaticity.cs
Labels: not-notes-worthy, run-dotnet-tests

#14035 [dotnet] Update docs about default inclusion in binding projects.
  dotnet/DefaultCompilationIncludes.md
Labels: not-notes-worthy, run-dotnet-tests

#14021 [NET 6 Attribute Conversion] PdfKit
  src/PdfKit/PdfAnnotation.cs
Labels: not-notes-worthy, run-dotnet-tests

#13996 [NET 6 Attribute Conversion] Network
  src/Network/NWAdvertiseDescriptor.cs
  src/Network/NWBrowseResult.cs
  src/Network/NWBrowser.cs
  src/Network/NWBrowserDescriptor.cs
  src/Network/NWConnection.cs
  src/Network/NWConnectionGroup.cs
  src/Network/NWContentContext.cs
  src/Network/NWDataTransferReport.cs
  src/Network/NWEndpoint.cs
  src/Network/NWError.cs
  src/Network/NWEstablishmentReport.cs
  src/Network/NWEthernetChannel.cs
  src/Network/NWFramer.cs
  src/Network/NWFramerMessage.cs
  src/Network/NWIPMetadata.cs
  src/Network/NWInterface.cs
  src/Network/NWListener.cs
  src/Network/NWMulticastGroup.cs
  src/Network/NWMultiplexGroup.cs
  src/Network/NWParameters.cs
  src/Network/NWPath.cs
  src/Network/NWPathMonitor.cs
  src/Network/NWPrivacyContext.cs
  src/Network/NWProtocolDefinition.cs
  src/Network/NWProtocolIPOptions.cs
  src/Network/NWProtocolMetadata.cs
  src/Network/NWProtocolOptions.cs
  src/Network/NWProtocolQuicOptions.cs
  src/Network/NWProtocolStack.cs
  src/Network/NWProtocolTcpOptions.cs
  src/Network/NWProtocolTlsOptions.cs
  src/Network/NWProtocolUdpOptions.cs
  src/Network/NWQuicMetadata.cs
  src/Network/NWResolutionReport.cs
  src/Network/NWResolverConfig.cs
  src/Network/NWTcpMetadata.cs
  src/Network/NWTlsMetadata.cs
  src/Network/NWTxtRecord.cs
  src/Network/NWUdpMetadata.cs
  src/Network/NWWebSocketMetadata.cs
  src/Network/NWWebSocketOptions.cs
  src/Network/NWWebSocketRequest.cs
  src/Network/NWWebSocketResponse.cs
Labels: not-notes-worthy, run-dotnet-tests

#14022 [NET 6 Attribute Conversion] PassKit
  src/PassKit/PKPaymentRequest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14031 [NET 6 Attribute Conversion] SpriteKit
  src/SpriteKit/SKNode.cs
  src/SpriteKit/SKShapeNode.cs
Labels: not-notes-worthy, run-dotnet-tests

#14042 [Foundation] Move NSUndoManager.SetActionName to the API definition for .NET.
  src/Foundation/NSUndoManager.cs
  src/foundation.cs
Labels: not-notes-worthy, run-dotnet-tests

#14041 [AppKit] Use the correct interface for inlining protocols in our api definitions in .NET.
  src/appkit.cs
  src/generator.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14049 [NET 6 Attribute Conversion] TVServices
  src/TVServices/TVContentItemImageShape.cs
Labels: not-notes-worthy, run-dotnet-tests

#14055 [NET 6 Attribute Conversion] VideoSubscriberAccount
  src/VideoSubscriberAccount/VSAccountMetadataRequest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14059 [UIKit] Rename UISegmentedControl.DividerImageForLeftSegmentStaterightSegmentStatebarMetrics to UISegmentedControl.GetDividerImage in .NET. Fixes #6357.
  src/uikit.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14058 [AppKit] Remove NSImage.DrawInRect in .NET, because it's already implemented as NSImage.Draw.
  src/appkit.cs
Labels: dotnet, run-dotnet-tests

#14056 [CFNetwork] Remove the MessageHandler type from .NET.
  dotnet/BreakingChanges.md
  src/CFNetwork/Content.cs
  src/CFNetwork/MessageHandler.cs
  src/CFNetwork/WebRequestStream.cs
  src/CFNetwork/WebResponseStream.cs
  src/CFNetwork/WorkerThread.cs
Labels: not-notes-worthy, run-dotnet-tests

#14054 [WebKit] Unseal a few members in XAMCORE_3_0+ that don't need to be sealed anymore.
  src/webkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#14053 [AppKit] Unify two partial NSLayoutManager declarations.
  src/appkit.cs
  src/xkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#14052 [HealthKit] Remove the HKAnchoredObjectResultHandler2 delegate in .NET.
  src/healthkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#14045 [AppKit] Implement the NSUserActivityRestoring protocol.
  src/appkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-AppKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/common-AppKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14043 [AppKit] Remove a few obsolete members in .NET
  src/appkit.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/monotouch-test/AppKit/NSPasteboard.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14038 [src] Remove CategoryAttribute.AllowStaticMembers and fix resulting issues in .NET.
  src/generator-attributes.cs
  src/generator.cs
  src/notificationcenter.cs
  tests/generator/ErrorTests.cs
Labels: not-notes-worthy, run-dotnet-tests

#14036 [AppKit] Implement the NSUserInterfaceValidation protocol for a few types in .NET.
  src/appkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14044 [dotnet] Update breaking changes docs.
  dotnet/BreakingChanges.md
Labels: not-notes-worthy

#14060 [NET 6 Attribute Conversion] VideoToolbox
  src/VideoToolbox/VTCompressionProperties.cs
  src/VideoToolbox/VTCompressionSession.cs
  src/VideoToolbox/VTDecompressionSession.cs
  src/VideoToolbox/VTFrameSilo.cs
  src/VideoToolbox/VTMultiPassStorage.cs
  src/VideoToolbox/VTPixelTransferProperties.cs
  src/VideoToolbox/VTSession.cs
  src/VideoToolbox/VTUtilities.cs
  src/VideoToolbox/VTVideoEncoder.cs
Labels: not-notes-worthy, run-dotnet-tests

#14068 [AppKit] Obsolete (and remove in .NET) a few notifications which have already been bound elsewhere.
  src/appkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#14057 [NET 6 Attribute Conversion] UIKit
  src/UIKit/NSLayoutManager.cs
  src/UIKit/UIAccessibility.cs
  src/UIKit/UIContentSizeCategory.cs
  src/UIKit/UIControl.cs
  src/UIKit/UIEventButtonMaskExtensions.cs
  src/UIKit/UIFont.cs
  src/UIKit/UIFontDescriptor.cs
  src/UIKit/UIGuidedAccessRestriction.cs
  src/UIKit/UIImagePickerController.cs
  src/UIKit/UIStringAttributes.cs
  src/UIKit/UIStringDrawing.cs
  src/UIKit/UITypes.cs
  src/UIKit/UIVibrancyEffect.cs
  src/UIKit/UIViewController.cs
Labels: not-notes-worthy, run-dotnet-tests

#14062 [NET 6 Attribute Conversion] WKWebKit
  src/WKWebKit/WKPreferences.cs
Labels: not-notes-worthy, run-dotnet-tests

#14063 [NET 6 Attribute Conversion] Vision
  src/Vision/VNUtils.cs
Labels: not-notes-worthy, run-dotnet-tests

#14082 [NetworkExtension] Remove fields from macOS that aren't in macOS for .NET.
  src/networkextension.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-NetworkExtension.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14078 [xtro] Remove dead comment in ignore file.
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreLocation.ignore
Labels: not-notes-worthy

#14076 [runtime] Make Runtime.Arch a readonly field in .NET. Fixes #5518.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/runtime.m
  runtime/xamarin/runtime.h
  src/ILLink.Substitutions.ios.xml
  src/ILLink.Substitutions.tvos.xml
  src/ObjCRuntime/Runtime.iOS.cs
  tools/common/Application.cs
Labels: not-notes-worthy, run-dotnet-tests

#14071 [AppKit] Make NSTextView implement the NSColorChanging protocol in .NET.
  src/appkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14051 [tools/runtime] Enable exception marshalling by default for all platforms in .NET.
  runtime/runtime.m
  tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
  tools/common/Application.cs
Labels: not-notes-worthy, note-highlight, run-dotnet-tests

#13777 [AppKit] Fix the protocols for NSTextView according to the current headers.
  src/appkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13977 [NET 6 Attribute Conversion] GameKit
  src/GameKit/GameKit.cs
Labels: not-notes-worthy, run-dotnet-tests

#14072 [NET 6 Attribute Conversion] XKit
  src/XKit/Types.cs
Labels: not-notes-worthy, run-dotnet-tests

#14074 [NET 6 Conversion] MetalKit
  src/MetalKit/MTKTextureLoaderOptions.cs
Labels: not-notes-worthy, run-dotnet-tests

#14048 [NET 6 Attribute Conversion] StoreKit
  src/StoreKit/NativeMethods.cs
Labels: not-notes-worthy, run-dotnet-tests

#14064 [NET 6 Attribute Conversion] WebKit
  src/WebKit/Enums.cs
Labels: not-notes-worthy, run-dotnet-tests

#14087 [MetalPerformanceShaders] Make MPSCnnConvolutionDataSource.Load a method in .NET. Fixes #6530.
  src/metalperformanceshaders.cs
Labels: not-notes-worthy, run-dotnet-tests

#14075 [NET 6 Attribute Conversion] MobileCoreServices
  src/MobileCoreServices/UTType.cs
Labels: not-notes-worthy, run-dotnet-tests

#14081 [NET 6 Attribute Conversion] ModelIO
  src/ModelIO/MDLMesh.cs
  src/ModelIO/MDLNoiseTexture.cs
  src/ModelIO/MDLStructs.cs
  src/ModelIO/MDLVertexDescriptor.cs
Labels: not-notes-worthy, run-dotnet-tests

#14079 [CI] Move to the new sdk-insertions workload.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: not-notes-worthy

#13949 [NET 6 Attribute Conversion] Homekit
  src/HomeKit/HMActionSet.cs
  src/HomeKit/HMCharacteristic.cs
  src/HomeKit/HMCharacteristicMetadata.cs
  src/HomeKit/HMCharacteristicProperties.cs
  src/HomeKit/HMEventTrigger.cs
  src/HomeKit/HMHome.cs
  src/HomeKit/HMService.cs
Labels: do-not-merge, not-notes-worthy, run-dotnet-tests

#14018 [dotnet] Include all files in the Resources subdirectory as bundle resources. Fixes #13808.
  dotnet/DefaultCompilationIncludes.md
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
  tests/common/TestProjects/My Spaced App/My Spaced App.dotnet.csproj
  tests/common/TestProjects/MySingleView/MySingleView.dotnet.csproj
  tests/common/TestProjects/MySpriteKitGame/MySpriteKitGame.dotnet.csproj
  tests/common/TestProjects/MyTabbedApplication/MyTabbedApplication.dotnet.csproj
  tests/common/TestProjects/MyXamarinFormsApp/Resources/Default-568h@2x.png
  tests/common/TestProjects/MyXamarinFormsApp/Resources/Default-Portrait.png
  tests/common/TestProjects/MyXamarinFormsApp/Resources/Default-Portrait@2x.png
  tests/common/TestProjects/MyXamarinFormsApp/Resources/Default.png
  tests/common/TestProjects/MyXamarinFormsApp/Resources/Default@2x.png
  tests/dotnet/BundleStructure/MacCatalyst/Resources/AutoIncluded.txt
  tests/dotnet/BundleStructure/MacCatalyst/Resources/SubDirectory/AutoIncluded2.txt
  tests/dotnet/BundleStructure/iOS/Resources/AutoIncluded.txt
  tests/dotnet/BundleStructure/iOS/Resources/SubDirectory/AutoIncluded2.txt
  tests/dotnet/BundleStructure/macOS/Resources/AutoIncluded.txt
  tests/dotnet/BundleStructure/macOS/Resources/SubDirectory/AutoIncluded2.txt
  tests/dotnet/BundleStructure/tvOS/Resources/AutoIncluded.txt
  tests/dotnet/BundleStructure/tvOS/Resources/SubDirectory/AutoIncluded2.txt
  tests/dotnet/UnitTests/BundleStructureTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14099 [tests] Adopt XAMCORE_4_0 changes in monotouch-test .NET.
  tests/monotouch-test/AVFoundation/CaptureDeviceTest.cs
  tests/monotouch-test/Metal/MTLArgumentEncoderTest.cs
  tests/monotouch-test/Metal/MTLComputeCommandEncoderTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14097 [src] Fix makefile to create directories before copying files into them.
  src/Makefile
Labels: not-notes-worthy, run-dotnet-tests

#14095 [UIKit] Implement the UIResponderStandardEditActions protocol.
  src/uikit.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore
  tests/xtro-sharpie/common-UIKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14091 [tools] Remove XAMCORE_4_0 condition in linker source.
  tools/common/Driver.cs
  tools/linker/CoreOptimizeGeneratedCode.cs
  tools/linker/MobileExtensions.cs
Labels: not-notes-worthy, run-dotnet-tests

#14090 [JavaScriptCore] Bind JSValue.ToArray as NSArray in .NET. Fixes #12549.
  src/javascriptcore.cs
  tests/monotouch-test/JavascriptCore/ValueTest.cs
Labels: dotnet, run-dotnet-tests

#14040 [Foundation] Add strongly typed version of NSUndoManager.RunLoopModes for .NET.
  src/Foundation/NSRunLoop.cs
  src/Foundation/NSUndoManager.cs
  src/foundation.cs
  tests/common/TestProjects/MyTVMetalGame/GameViewController.cs
Labels: not-notes-worthy, run-dotnet-tests

#13956 [msbuild] Rework code signing to sign everything at the end of the build.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy, run-dotnet-tests

#14096 [generator] Make sure to not have dead code. Fixes a few compiler warnings.
  src/generator.cs
Labels: not-notes-worthy

#14089 [Foundation] Remove a WebKit workaround for NSProxy on tvOS in .NET.
  src/Foundation/NSProxy.cs
  tests/introspection/ApiFrameworkTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14070 Fix GC issue on CoreCLR where finalized objects are returned by Runtime.GetNSObject
  src/Foundation/NSObject2.cs
  tests/monotouch-test/Foundation/NSObjectGCTest.cs
Labels: bug, community, run-dotnet-tests

#14077 [NET 6 Attribute Conversion] MetalPerformanceShaders
  src/MetalPerformanceShaders/MPSCnnConvolutionDescriptor.cs
  src/MetalPerformanceShaders/MPSCnnNeuron.cs
  src/MetalPerformanceShaders/MPSDefs.cs
  src/MetalPerformanceShaders/MPSImageBatch.cs
  src/MetalPerformanceShaders/MPSKernel.cs
  src/MetalPerformanceShaders/MPSNNGraph.cs
  src/MetalPerformanceShaders/MPSStateBatch.cs
Labels: not-notes-worthy, run-dotnet-tests

#14029 [NET 6 Attribute Conversion] SceneKit
  src/SceneKit/SCNJavaScript.cs
  src/SceneKit/SCNPhysicsShape.cs
  src/SceneKit/SCNRenderingOptions.cs
  src/SceneKit/SCNSkinner.cs
Labels: not-notes-worthy, run-dotnet-tests

#14088 [Foundation] Make NSSecureCoding a static class in .NET.
  src/Foundation/NSSecureCoding.cs
Labels: not-notes-worthy, run-dotnet-tests

#14098 [tests] Adopt XAMCORE_4_0 changes for introspection in .NET.
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/introspection/Mac/MacApiFieldTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/introspection/Mac/MacApiSignatureTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSignatureTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14094 [xtro] Update legacy annotations to talk about .NET instead of XAMCORE_4_0.
  tests/xtro-sharpie/common-AVFoundation.ignore
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/common-GameplayKit.ignore
  tests/xtro-sharpie/common-Metal.ignore
  tests/xtro-sharpie/common-ModelIO.ignore
  tests/xtro-sharpie/common-SceneKit.ignore
  tests/xtro-sharpie/common-Security.ignore
  tests/xtro-sharpie/common-UIKit.ignore
  tests/xtro-sharpie/iOS-CoreNFC.ignore
  tests/xtro-sharpie/iOS-IntentsUI.ignore
  tests/xtro-sharpie/iOS-MessageUI.ignore
  tests/xtro-sharpie/iOS-QuickLook.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/macOS-AVKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
  tests/xtro-sharpie/macOS-CoreLocation.ignore
  tests/xtro-sharpie/macOS-Foundation.ignore
  tests/xtro-sharpie/macOS-GameKit.ignore
  tests/xtro-sharpie/macOS-Intents.ignore
  tests/xtro-sharpie/macOS-NetworkExtension.ignore
  tests/xtro-sharpie/macOS-QuickLookUI.ignore
  tests/xtro-sharpie/macOS-Social.ignore
  tests/xtro-sharpie/tvOS-CoreLocation.ignore
  tests/xtro-sharpie/tvOS-GameKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/watchOS-CoreLocation.ignore
  tests/xtro-sharpie/watchOS-MediaPlayer.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14103 [dotnet] Fix non-bundling of debug files for release builds. Fixes #14085.
  dotnet/BundleContents.md
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeBundleLocationTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ParseBundlerArgumentsTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/dotnet/BundleStructure/shared.csproj
  tests/dotnet/UnitTests/BundleStructureTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy, run-dotnet-tests

#14112 [bgen] Make sure to render nint/nuint in delegates as nint/nuint for .NET. Fixes #14107.
  src/generator-typemanager.cs
  src/generator.cs
  tests/generator/BGenTests.cs
  tests/generator/tests/nint-delegates.cs
Labels: not-notes-worthy, run-dotnet-tests

#14109 [msbuild] Make sure to set 'ResolveAssemblyConflicts=true' before importing Microsoft.CSharp.targets. Fixes #11691.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.AppExtension.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.CSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.FSharp.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.ObjCBinding.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.AppExtension.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.TVOS.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.App.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.Common.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.AppExtension.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.WatchOS.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.AppExtension.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.CSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.FSharp.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.WatchApp.CSharp.targets
  tests/common/TestProjects/SystemMemoryFromNetStandard2_0/Info.plist
  tests/common/TestProjects/SystemMemoryFromNetStandard2_0/Program.cs
  tests/common/TestProjects/SystemMemoryFromNetStandard2_0/SystemMemoryFromNetStandard2_0.csproj
  tests/common/TestProjects/SystemMemoryLibrary/SystemMemoryConsumer.cs
  tests/common/TestProjects/SystemMemoryLibrary/SystemMemoryLibrary.csproj
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/ProjectTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/SystemMemoryReference.cs
Labels: not-notes-worthy, run-dotnet-tests

#13656 Generate Software Bill of Materials (SBOM) manifest
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-azure.yml
Labels: not-notes-worthy

#14117 [release/6.0.2xx-preview13] Fix GC issue on CoreCLR where finalized objects are returned by Runtime.GetNSObject
  src/Foundation/NSObject2.cs
  tests/monotouch-test/Foundation/NSObjectGCTest.cs
Labels: bug, community, run-dotnet-tests, backported

#14110 [src] Fix dependencies in makefile to not contain a trailing slash.
  src/Makefile
Labels: not-notes-worthy

#13862 Improvements on Xamarin.iOS.Tasks.Windows
  msbuild/Xamarin.iOS.Tasks.Windows/Properties/AssemblyInfo.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Properties/Resources.Designer.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Properties/Resources.resx
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/Codesign.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/LocalUnzip.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/UnpackHotRestartFrameworks.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/Unzip.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
  msbuild/Xamarin.iOS.Tasks.Windows/Zip.cs
Labels: not-notes-worthy

#14121 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#14120 [src] Use different variables for source files for .NET and legacy.
  src/Makefile
  src/frameworks.sources
Labels: not-notes-worthy, run-dotnet-tests

#14118 [release/6.0.2xx-preview13] [bgen] Make sure to render nint/nuint in delegates as nint/nuint for .NET. Fixes #14107.
  src/generator-typemanager.cs
  src/generator.cs
  tests/generator/BGenTests.cs
  tests/generator/tests/nint-delegates.cs
Labels: not-notes-worthy, run-dotnet-tests, backported

#14106 [tests] Add disabled NET6 availability attribute test
  tests/cecil-tests/AttributeTest.cs
  tests/cecil-tests/Helper.cs
Labels: not-notes-worthy

#14127 [msbuild] Provide a stamp file when codesign on-demand resources. Fixes #14126.
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-dotnet-tests

#14136 [runtime] Remove `NSLog (string format, params object?[] args)` overload
  src/Foundation/NSObject2.cs
  src/ObjCRuntime/Registrar.cs
  src/ObjCRuntime/Runtime.cs
  src/UIKit/UIButton.cs
Labels: community

#14133 [src/introspection] Adjust tests and availability attributes to work run on iOS/tvOS 12.4. Fixes #13957.
  src/Network/NWProtocolDefinition.cs
  src/appkit.cs
  src/avfoundation.cs
  src/externalaccessory.cs
  src/gamekit.cs
  src/metal.cs
  src/spritekit.cs
  src/uikit.cs
  tests/introspection/ApiAvailabilityTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
Labels: run-old-simulator-tests, not-notes-worthy, run-dotnet-tests

#14132 [CoreText] Move numerous CoreText fields to generated code for .NET.
  src/CoreText/CTBaselineClass.cs
  src/CoreText/CTFontCollection.cs
  src/CoreText/CTFontDescriptor.cs
  src/CoreText/CTFontNameKey.cs
  src/CoreText/CTFontTrait.cs
  src/CoreText/CTFrame.cs
  src/CoreText/CTStringAttributes.cs
  src/CoreText/CTTextTab.cs
  src/coretext.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-CoreText.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14115 [dotnet/runtime] Fix a few issues with regards to extensions in .NET. Fixes #13742.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/exports.t4
  runtime/monotouch-main.m
  tools/common/Application.cs
  tools/dotnet-linker/LinkerConfiguration.cs
Labels: not-notes-worthy, run-dotnet-tests

#14111 [dotnet] Sign the 'createdump' executable. Fixes #13417.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy, run-dotnet-tests

#14130 Default VerifyDependencyInjectionOpenGenericServiceTrimmability
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: run-dotnet-tests

#14138 [objcruntime] Simplified earlier split of internal `Lookup` method
  src/ObjCRuntime/Class.cs
Labels: community

#13882 [NET 6 Attribute Conversion] CoreMedia
  src/CoreMedia/CMBufferQueue.cs
  src/CoreMedia/CMFormatDescription.cs
  src/CoreMedia/CMSampleBuffer.cs
  src/CoreMedia/CMSync.cs
  src/CoreMedia/CMTime.cs
  src/CoreMedia/CoreMedia.cs
Labels: do-not-merge, not-notes-worthy, run-dotnet-tests

#14140 [net][objcruntime] Remove `Class (IntPtr)` for .net profile
  src/ObjCRuntime/Class.cs
Labels: community, run-dotnet-tests

#14137 [mono] Bump mono to the HEAD of 2020-02
  Make.config
  mk/mono.mk
Labels: notes-mention

#14142 [UIKit] Fix signature of UIFont._MonospacedSystemFontOfSize.
  src/uikit.cs
Labels: not-notes-worthy, run-dotnet-tests

#14145 [ObjCRuntime] Keep accepting IntPtr constructors in .NET as an alternative to NativeHandle constructors. Fixes #14046.
  src/ObjCRuntime/Runtime.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
  tools/common/StaticRegistrar.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
Labels: not-notes-worthy, run-dotnet-tests

#14153 [objcruntime] Use `AllocGCHandle` helper everywhere
  src/ObjCRuntime/Runtime.CoreCLR.cs
  src/ObjCRuntime/Runtime.cs
Labels: community

#14152 [generator] Make the `Messaging` a static class
  src/generator.cs
Labels: community

#14150 [objcruntime] Inline the use of the `Class.LookupFullName` method
  src/ObjCRuntime/Class.cs
  src/ObjCRuntime/Runtime.cs
  tests/linker/ios/link all/PreserveTest.cs
Labels: community

#14144 [test] Add help makefile targets to run .NET tests on remote machines.
  Make.config
  tests/common/shared-dotnet-test.mk
  tests/common/shared-dotnet.mk
  tests/introspection/dotnet/Makefile
Labels: not-notes-worthy

#14160 [corefoundation] Skip intermediate call inside `CFArray.DefaultConvert`
  src/CoreFoundation/CFArray.cs
Labels: community

#14149 [SceneKit] Remove dead code from SCNMatrix4.cs.
  src/SceneKit/SCNMatrix4.cs
Labels: not-notes-worthy, run-dotnet-tests

#12694 [msbuild/dotnet] Set NoBindingEmbedding to 'true' by default in .NET. Fixes #12530.
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/MacCatalystBinding1.csproj
  dotnet/Templates/Microsoft.iOS.Templates/iosbinding/iOSBinding1.csproj
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  tests/bindings-xcframework-test/dotnet/shared.csproj
  tests/dotnet/BindingOldStyle/shared.csproj
  tests/dotnet/BindingWithDefaultCompileInclude/shared.csproj
Labels: not-notes-worthy, run-dotnet-tests

#14148 [release/6.0.2xx-preview13] [dotnet/msbuild] Run install_name_tool to fix the id for dylibs. Fixes #13999.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/InstallNameToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/InstallNameTool.cs
  src/ObjCRuntime/ErrorHelper.cs
  tests/dotnet/BundleStructure/shared.csproj
  tests/dotnet/UnitTests/BundleStructureTest.cs
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/test-libraries/libraries/Makefile
  tools/common/MachO.cs
Labels: not-notes-worthy, run-dotnet-tests, backported

#14163 [msbuild] Generate Versions.*.g.cs before running msbuild to build the solution.
  msbuild/Makefile
Labels: not-notes-worthy

#14164 [nfloat] Obsolete nfloat.CopyArray in legacy Xamarin and stop using it.
  src/AppKit/NSColor.cs
  src/NativeTypes/Primitives.tt
  tests/monotouch-test/AppKit/NSColor.cs
Labels: not-notes-worthy, run-dotnet-tests

#14165 [runtime] Be a bit more explicit about format warnings related to security.
  Make.config
Labels: not-notes-worthy

#14143 [tests] Use the correct OS version for Mac Catalyst.
  tests/common/PlatformInfo.cs
Labels: not-notes-worthy, run-dotnet-tests

#14162 [dotnet] Add support for the PublishFolderType metadata on Content and BundleResource items.
  dotnet/BundleContents.md
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CollectBundleResourcesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeBundleLocationTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/dotnet/BundleStructure/BundleResourceD.txt
  tests/dotnet/BundleStructure/BundleResourceE.txt
  tests/dotnet/BundleStructure/BundleResourceF.txt
  tests/dotnet/BundleStructure/BundleResourceG.txt
  tests/dotnet/BundleStructure/BundleResourceH.txt
  tests/dotnet/BundleStructure/ContentD.txt
  tests/dotnet/BundleStructure/ContentE.txt
  tests/dotnet/BundleStructure/ContentF.txt
  tests/dotnet/BundleStructure/ContentG.txt
  tests/dotnet/BundleStructure/ContentH.txt
  tests/dotnet/BundleStructure/EmbeddedResourceD.txt
  tests/dotnet/BundleStructure/EmbeddedResourceE.txt
  tests/dotnet/BundleStructure/EmbeddedResourceF.txt
  tests/dotnet/BundleStructure/EmbeddedResourceG.txt
  tests/dotnet/BundleStructure/EmbeddedResourceH.txt
  tests/dotnet/BundleStructure/shared.csproj
  tests/dotnet/UnitTests/BundleStructureTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14147 [dotnet/msbuild] Run install_name_tool to fix the id for dylibs. Fixes #13999.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/InstallNameToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/InstallNameTool.cs
  src/ObjCRuntime/ErrorHelper.cs
  tests/dotnet/BundleStructure/shared.csproj
  tests/dotnet/UnitTests/BundleStructureTest.cs
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/test-libraries/libraries/Makefile
  tools/common/MachO.cs
Labels: not-notes-worthy, run-dotnet-tests

#14173 [release/6.0.2xx-preview13] [CI] Allow several builds to upload binlogs and do not fail.
  tools/devops/automation/templates/build/build-nugets.yml
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy, backported

#14135 [accelerate] Add nullability to (generated and manual) bindings
  src/Accelerate/vImageTypes.cs
Labels: not-notes-worthy

#14183 [foundation] Fix some `IntPtr` -> `NativeHandle` inside `NSObject`
  src/Foundation/NSObject2.cs
Labels: community

#14185 [objcruntime] Small simplification of `ErrorHelper.CollectExceptions`
  src/ObjCRuntime/ErrorHelper.cs
Labels: community

#14186 [objcruntime] Use more direct calls in `Runtime`
  src/ObjCRuntime/Runtime.cs
Labels: community

#14189 [net] Fix the product/assemblies names in error messages
  src/ObjCRuntime/Runtime.iOS.cs
  src/ObjCRuntime/Runtime.mac.cs
Labels: community

#14161 [net][objcruntime] Remove `DisposableObject.ClearHandle`
  src/ObjCRuntime/DisposableObject.cs
  src/SearchKit/SearchKit.cs
Labels: community

#14175 [monotouch-test] The RuntimeTest.ResurrectedObjectsDisposedTest test seems to be passing now.
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14180 [msbuild] Move debug-related targets to shared code.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateDebugConfigurationTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateDebugSettingsTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectDebugNetworkConfigurationTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CreateDebugConfiguration.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CreateDebugSettings.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/DetectDebugNetworkConfiguration.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-dotnet-tests

#14179 [msbuild] Don't report 'unable to open object file:' from dsymutil as warnings.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
Labels: not-notes-worthy

#13875 [CI] If we disabled the api diff do not event spawn a job.
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#14200 [CoreGraphics] Remove CGColorConversionInfo and CGColorConversionInfoTriple from .NET.
  src/CoreGraphics/CGColorConverter.cs
Labels: not-notes-worthy, run-dotnet-tests

#14195 [tests/msbuild] Use full path to binlogs and executables.
  msbuild/Xamarin.HotRestart.PreBuilt/Makefile
  tests/common/shared-dotnet.mk
Labels: not-notes-worthy

#14196 [msbuild/dotnet] Make codesigning createdump work in universal apps. Fixes #14155.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy, run-dotnet-tests

#14187 [ApiDiffs] More renaming to enable ApiDiffs
  Make.config
  tools/apidiff/Makefile
  tools/devops/automation/templates/build/publish-html.yml
Labels: not-notes-worthy

#14198 [AVFoundation] AVAudioUnitManufacturerNameApple and AVAudioUnitType aren't deprecated neither in headers nor documentation.
  src/avfoundation.cs
Labels: not-notes-worthy

#14199 [AVFoundation] Simplify code behind + api definition for AVCaptureConnection.
  src/AVFoundation/AVCaptureConnection.cs
  src/avfoundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AVFoundation.ignore
  tests/xtro-sharpie/macOS-AVFoundation.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14191 Reduce string duplication in the platform assemblies (part 1)
  src/Foundation/NSObject2.cs
  src/ObjCRuntime/Blocks.cs
  src/ObjCRuntime/Class.cs
  src/ObjCRuntime/ErrorConstants.cs
  src/ObjCRuntime/Runtime.cs
  src/frameworks.sources
Labels: community, run-dotnet-tests

#14216 [runtime] Ask curl to fail (--fail) if fetching the URL fails for coreclrhost.h.
  runtime/Makefile
Labels: not-notes-worthy
