Repository dotnet/macios, pull requests merged in 2022-08, with the labels that each got.

#15579 [foundation] Xcode 13 & Xcode 14 beta 1-3 bindings
  src/Foundation/Enum.cs
  src/Foundation/Enums.cs
  src/Foundation/NSArray.cs
  src/Foundation/NSArray_1.cs
  src/Foundation/NSMutableArray_1.cs
  src/Foundation/NSMutableOrderedSet_1.cs
  src/Foundation/NSOrderedCollectionChange.cs
  src/Foundation/NSOrderedCollectionChange_1.cs
  src/Foundation/NSOrderedCollectionDifference.cs
  src/Foundation/NSOrderedCollectionDifference_1.cs
  src/Foundation/NSOrderedSet.cs
  src/Foundation/NSOrderedSet_1.cs
  src/MetalPerformanceShadersGraph/MPSGraphTensorData.cs
  src/foundation.cs
  src/frameworks.sources
  tests/cecil-tests/AttributeTest.cs
  tests/introspection/ApiProtocolTest.cs
  tests/monotouch-test/Foundation/NSArray1Test.cs
  tests/monotouch-test/Foundation/NSOrderedCollectionChange1Test.cs
  tests/monotouch-test/Foundation/NSOrderedCollectionChangeTest.cs
  tests/monotouch-test/Foundation/NSOrderedCollectionDifference1Test.cs
  tests/monotouch-test/Foundation/NSOrderedCollectionDifferenceTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-Foundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-Foundation.todo
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Foundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Foundation.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Foundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Foundation.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-Foundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-Foundation.todo
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/iOS-Foundation.ignore
  tests/xtro-sharpie/iOS-Foundation.todo
  tests/xtro-sharpie/macOS-Foundation.ignore
  tests/xtro-sharpie/macOS-Foundation.todo
  tests/xtro-sharpie/tvOS-Foundation.ignore
  tests/xtro-sharpie/tvOS-Foundation.todo
  tests/xtro-sharpie/watchOS-Foundation.ignore
  tests/xtro-sharpie/watchOS-Foundation.todo
Labels: notes-mention

#15592 [nnyeah] update documentation
  tools/nnyeah/README.md
Labels: enhancement, skip-all-tests, not-notes-worthy

#15539 [ShazamKit] Update bindings for Xcode 14.0 beta 1&2&3&4
  src/shazamkit.cs
  src/uniformtypeidentifiers.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-ShazamKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-ShazamKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-ShazamKit.todo
  tests/xtro-sharpie/iOS-ShazamKit.todo
  tests/xtro-sharpie/macOS-ShazamKit.todo
  tests/xtro-sharpie/tvOS-ShazamKit.todo
  tests/xtro-sharpie/watchOS-ShazamKit.todo
Labels: notes-mention

#15450 [nnyeah] Return a non-zero exit code if something goes wrong.
  tools/nnyeah/nnyeah/AssemblyConverter.cs
  tools/nnyeah/nnyeah/Program.cs
Labels: not-notes-worthy

#15611 [CI] List the installed frameworks in the test bot.
  tools/devops/automation/templates/common/setup.yml
  tools/devops/automation/templates/tests/build.yml
  tools/devops/automation/templates/tests/run-tests.yml
Labels: not-notes-worthy

#15609 [StoreKit] Update bindings for Xcode 14 beta 1, 2, 3 & 4
  src/storekit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-StoreKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-StoreKit.todo
  tests/xtro-sharpie/iOS-StoreKit.todo
  tests/xtro-sharpie/tvOS-StoreKit.todo
  tests/xtro-sharpie/watchOS-StoreKit.todo
Labels: notes-mention

#15606 [CoreText] Update binding for xcode 14 beta 4.
  src/CoreText/CTFont.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreText.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreText.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreText.todo
  tests/xtro-sharpie/iOS-CoreText.todo
  tests/xtro-sharpie/macOS-CoreText.todo
  tests/xtro-sharpie/tvOS-CoreText.todo
  tests/xtro-sharpie/watchOS-CoreText.todo
Labels: notes-mention

#15618 [submodules] Fix indentation in config file.
  .gitmodules
Labels: not-notes-worthy

#15616 [Xcode14] Merge main into xcode14
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/Codesign.cs
  msbuild/Xamarin.iOS.Tasks/Model/DataItem.cs
  msbuild/Xamarin.iOS.Tasks/Model/DataSet.cs
  src/usernotifications.cs
  tests/monotouch-test/UserNotifications/NotificationInterruptionLevel.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj
  tools/devops/automation/templates/common/setup.yml
  tools/devops/automation/templates/tests/build.yml
  tools/devops/automation/templates/tests/run-tests.yml
  tools/nnyeah/README.md
  tools/nnyeah/nnyeah/AssemblyConverter.cs
  tools/nnyeah/nnyeah/Program.cs
Labels: not-notes-worthy

#15607 [GameKit] Update binding for xcode 14 beta 4.
  src/gamekit.cs
  tests/xtro-sharpie/iOS-GameKit.todo
  tests/xtro-sharpie/macOS-GameKit.todo
  tests/xtro-sharpie/tvOS-GameKit.todo
  tests/xtro-sharpie/watchOS-GameKit.todo
Labels: notes-mention

#15605 [CoreSpotlight] Add support for Xcode 14 beta 4.
  src/corespotlight.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreSpotlight.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreSpotlight.todo
  tests/xtro-sharpie/iOS-CoreSpotlight.todo
  tests/xtro-sharpie/macOS-CoreSpotlight.todo
Labels: notes-mention

#15619 [CI] Make sure we do not have pkgs from other builds.
  tools/devops/automation/templates/build/build-pkgs.yml
  tools/devops/automation/templates/common/teardown.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy

#15624 [xcode14] [CI] Make sure we do not have pkgs from other builds.
  tools/devops/automation/templates/build/build-pkgs.yml
  tools/devops/automation/templates/common/teardown.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#15378 [nnyeah] Better error message for ctors that we can't get to anymore.
  tools/nnyeah/nnyeah/AssemblyConverter.cs
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
Labels: enhancement, skip-all-tests, not-notes-worthy

#15610 [ShazamKit] Remove availability from an error enum.
  src/shazamkit.cs
Labels: not-notes-worthy

#15626 [SpriteKit] Add support for Xcode 14 beta 1, 2, 3, 4
  src/SpriteKit/Enums.cs
  src/spritekit.cs
  tests/xtro-sharpie/watchOS-SpriteKit.todo
Labels: notes-mention

#15627 [Speech] Add support Xcode14 beta 1, 2, 3 and 4
  src/speech.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Speech.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Speech.todo
  tests/xtro-sharpie/iOS-Speech.todo
  tests/xtro-sharpie/macOS-Speech.todo
Labels: notes-mention

#15631 [nnyeah] Added code to look up the legacy platform dll instead of requiring it.
  tools/nnyeah/nnyeah/AssemblyConverter.cs
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/Program.cs
  tools/nnyeah/tests/integration/IntegrationExamples.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15638 [PHASE] Add support for xcode14 beta 4.
  src/phase.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PHASE.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-PHASE.todo
  tests/xtro-sharpie/iOS-PHASE.todo
  tests/xtro-sharpie/macOS-PHASE.todo
Labels: notes-mention

#15639 [DeviceCheck] Add support for Xcode 14 beta 4.
  src/devicecheck.cs
  src/frameworks.sources
  tests/introspection/ApiTypeTest.cs
  tests/xtro-sharpie/watchOS-DeviceCheck.todo
  tools/common/Frameworks.cs
Labels: notes-mention

#15640 [HealthKitUI] Add support for xcode14 beta4.
  src/healthkitui.cs
Labels: notes-mention

#15646 [nnyeah] documentation update
  tools/nnyeah/README.md
Labels: enhancement, skip-all-tests, not-notes-worthy

#15368 Set TrimMode to partial if not set
  dotnet/targets/Xamarin.Shared.Sdk.props
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: do-not-merge, not-notes-worthy

#15601 [UIKit] Remove the preprocessor directives for watchOS.
  src/UIKit/UIEnums.cs
  src/uikit.cs
Labels: not-notes-worthy

#15625 [Xtro] Update xtro after GameKit.
  tests/xtro-sharpie/api-annotations-dotnet/iOS-GameKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-GameKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-GameKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-GameKit.todo
  tests/xtro-sharpie/common-GameKit.ignore
  tests/xtro-sharpie/macOS-GameKit.ignore
Labels: not-notes-worthy

#15641 [ExecutionPolicy] Add support for xcode14 beta 4.
  src/executionpolicy.cs
  src/frameworks.sources
  tools/common/Frameworks.cs
Labels: notes-mention

#15650 [HomeKit] Update for Xcode 14 beta 4.
  tests/xtro-sharpie/api-annotations-dotnet/common-HomeKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-HomeKit.todo
  tests/xtro-sharpie/common-HomeKit.ignore
  tests/xtro-sharpie/iOS-HomeKit.todo
Labels: notes-mention

#15645 [PushToTalk] Add new framework for Xcode 14 bet4.
  src/frameworks.sources
  src/pushtotalk.cs
  tests/introspection/iOS/iOSApiClassPtrTest.cs
  tests/introspection/iOS/iOSApiCtorInitTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/mtouch/RegistrarTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PushToTalk.todo
  tests/xtro-sharpie/iOS-PushToTalk.todo
  tools/common/Frameworks.cs
Labels: notes-mention

#15644 [RoomPlan] Update xtro.
  tests/xtro-sharpie/api-annotations-dotnet/iOS-RoomPlan.ignore
  tests/xtro-sharpie/common-RoomPlan.ignore
Labels: not-notes-worthy

#15635 [SafariServices] Add support for Xcode14 upt to beta 4.
  src/safariservices.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-SafariServices.todo
  tests/xtro-sharpie/iOS-SafariServices.todo
Labels: notes-mention

#15647 [ScreeCaptureKit] Add support for Xcode 14 beta 4.
  src/screencapturekit.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-ScreenCaptureKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-ScreenCaptureKit.todo
  tests/xtro-sharpie/macOS-ScreenCaptureKit.ignore
  tests/xtro-sharpie/macOS-ScreenCaptureKit.todo
Labels: notes-mention

#15649 [BackgroundAssets] Add new framework from Xcode1 4 beta 4.
  src/backgroundassets.cs
  src/frameworks.sources
  tests/mtouch/RegistrarTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-BackgroundAssets.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-BackgroundAssets.todo
  tests/xtro-sharpie/iOS-BackgroundAssets.todo
  tests/xtro-sharpie/macOS-BackgroundAssets.todo
  tools/common/Frameworks.cs
  tools/mtouch/Makefile
Labels: notes-mention

#15655 [xcode14] [UIKit] Remove the preprocessor directives for watchOS.
  src/UIKit/UIEnums.cs
  src/uikit.cs
Labels: not-notes-worthy, backported

#15648 [generator] Do not zero-extend implied catalyst attributes
  src/generator.cs
Labels: not-notes-worthy

#15652 [MessageUI] Added support for Xcode 14 beta 1 & 2
  src/messageui.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MessageUI.todo
  tests/xtro-sharpie/iOS-MessageUI.todo
Labels: notes-mention

#15637 [PushKit] Added support for Xcode 14
  src/pushkit.cs
  tests/xtro-sharpie/watchOS-PushKit.todo
Labels: notes-mention

#15542 [EventKit] Add support for Xcode 14 beta 1
  src/eventkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-EventKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-EventKit.todo
  tests/xtro-sharpie/iOS-EventKit.todo
  tests/xtro-sharpie/macOS-EventKit.todo
  tests/xtro-sharpie/watchOS-EventKit.todo
Labels: notes-mention

#15659 [xcode14] [generator] Do not zero-extend implied catalyst attributes
  src/generator.cs
Labels: not-notes-worthy, backported

#15634 [SharedWithYouCore] Add new framework for xcode14.
  src/frameworks.sources
  src/sharedwithyoucore.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/mtouch/RegistrarTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-SharedWithYouCore.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-SharedWithYouCore.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-SharedWithYouCore.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-SharedWithYouCore.todo
  tests/xtro-sharpie/common-SharedWithYouCore.ignore
  tests/xtro-sharpie/iOS-SharedWithYouCore.todo
  tests/xtro-sharpie/macOS-SharedWithYouCore.todo
  tests/xtro-sharpie/tvOS-SharedWithYouCore.todo
  tools/common/Frameworks.cs
  tools/mtouch/Makefile
Labels: notes-mention

#15660 [nnyeah] better help, change priority of processing help request.
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/Program.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15661 [coreimage] Xcode 14 Beta 1-4
  src/coreimage.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreImage.todo
  tests/xtro-sharpie/api-annotations-dotnet/common-CoreImage.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreImage.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreImage.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreImage.todo
  tests/xtro-sharpie/common-CoreImage.ignore
  tests/xtro-sharpie/iOS-CoreImage.todo
  tests/xtro-sharpie/macOS-CoreImage.todo
  tests/xtro-sharpie/tvOS-CoreImage.todo
Labels: notes-mention

#15667 [net7.0] Updates the path to illink when building from Windows
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: notes-mention

#15613 [PassKit] Update bindings for Xcode 14 beta 1-5
  src/PassKit/PKEnums.cs
  src/PassKit/PKShareablePassMetadata.cs
  src/frameworks.sources
  src/passkit.cs
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PassKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PassKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-PassKit.todo
  tests/xtro-sharpie/iOS-PassKit.ignore
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/macOS-PassKit.todo
  tests/xtro-sharpie/watchOS-PassKit.todo
Labels: notes-mention

#15686 [xcode14] Merge release/6.0.400 into xcode14
  Make.config
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: not-notes-worthy

#15665 Remove duplicated SceneKitAsset declarations
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
Labels: community

#15500 [msbuild] Unify the CreateEmbeddedResources task between iOS and Mac.
  msbuild/Xamarin.Mac.Tasks/Tasks/CreateEmbeddedResources.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CreateEmbeddedResources.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#15483 [dotnet] Make it possible to specify the registrar using a 'Registrar' property in MSBuild.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BundlerToolTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/ComputeRegistrarConstant.targets
  tests/common/shared-dotnet.csproj
  tests/monotouch-test/dotnet/MacCatalyst/monotouch-test.csproj
  tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
  tests/monotouch-test/dotnet/shared.csproj
  tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj
  tests/monotouch-test/monotouch-test.csproj
  tests/xammac_tests/xammac_tests.csproj
  tests/xharness/Jenkins/TestData.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#15688 [tests] Improve output when writing log events in test logs.
  tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/LogEvent.cs
Labels: not-notes-worthy

#15356 Nullability annotations on NSUrl
  src/Foundation/NSUrl.cs
  src/Foundation/NSUrlSessionHandler.cs
  src/foundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: enhancement, not-notes-worthy

#15701 [CoreSpotlight] Updates for Xcode14 beta 5
  src/corespotlight.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreSpotlight.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreSpotlight.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreSpotlight.todo
  tests/xtro-sharpie/iOS-CoreSpotlight.todo
  tests/xtro-sharpie/macOS-CoreSpotlight.todo
  tests/xtro-sharpie/tvOS-CoreSpotlight.todo
Labels: notes-mention

#15705 [iTunesLibrary] Updates for Xcode14 Beta 5
  src/ituneslibrary.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-iTunesLibrary.todo
  tests/xtro-sharpie/macOS-iTunesLibrary.todo
Labels: notes-mention

#15714 Updated Xamarin.Messaging to 1.7.9
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#15713 Updated Xamarin.Messaging to 1.7.9
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#15521 [src] Use constants instead of string literals in numerous DllImports.
  src/Foundation/NSInputStream.cs
  src/Foundation/NSObject2.cs
  src/Foundation/NSOutputStream.cs
  src/ObjCRuntime/Class.cs
  src/ObjCRuntime/Messaging.cs
  src/ObjCRuntime/Protocol.cs
  src/ObjCRuntime/Selector.cs
  src/ObjCRuntime/TrampolineBlockBase.cs
  src/frameworks.sources
  src/generator.cs
Labels: not-notes-worthy

#15642 Fix #9996 and #15622
  src/ObjCRuntime/ObsoleteConstants.cs
  src/carplay.cs
Labels: community

#15715 [ModelIO] Updates for Xcode 14 beta1
  src/modelio.cs
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-ModelIO.todo
Labels: notes-mention

#15710 [tools] Fix issue when doing api comparison for PRs with multiple commits
  tools/compare-commits.sh
Labels: skip-all-tests, not-notes-worthy

#15712 [runtime] Allow `IntPtr` for native objects in the dynamic registrar. Fixes #15708
  runtime/trampolines.m
Labels: community

#15726 Fixed remote archiving with iOS app extensions
  msbuild/Xamarin.MacDev.Tasks/Tasks/Archive.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Zip.cs
Labels: not-notes-worthy

#15731 [net7.0] Merge main into net7.0.
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Directory.Build.props
  msbuild/Xamarin.Mac.Tasks/Tasks/CreateEmbeddedResources.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BundlerToolTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CreateEmbeddedResources.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  src/Foundation/NSInputStream.cs
  src/Foundation/NSObject2.cs
  src/Foundation/NSOutputStream.cs
  src/Foundation/NSUrl.cs
  src/Foundation/NSUrlSessionHandler.cs
  src/ObjCRuntime/Class.cs
  src/ObjCRuntime/Messaging.cs
  src/ObjCRuntime/ObsoleteConstants.cs
  src/ObjCRuntime/Protocol.cs
  src/ObjCRuntime/Selector.cs
  src/ObjCRuntime/TrampolineBlockBase.cs
  src/UIKit/UIEnums.cs
  src/carplay.cs
  src/foundation.cs
  src/frameworks.sources
  src/generator.cs
  src/uikit.cs
  tests/ComputeRegistrarConstant.targets
  tests/common/shared-dotnet.csproj
  tests/monotouch-test/dotnet/MacCatalyst/monotouch-test.csproj
  tests/monotouch-test/dotnet/macOS/monotouch-test.csproj
  tests/monotouch-test/dotnet/shared.csproj
  tests/monotouch-test/dotnet/tvOS/monotouch-test.csproj
  tests/monotouch-test/monotouch-test.csproj
  tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/LogEvent.cs
  tests/xammac_tests/xammac_tests.csproj
  tests/xharness/Jenkins/TestData.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/common-Foundation.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
  tools/compare-commits.sh
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/Program.cs
Labels: not-notes-worthy

#15700 [WebKit] Add support for Xcode 14 beta 5.
  src/wkwebkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-WebKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-WebKit.todo
  tests/xtro-sharpie/iOS-WebKit.todo
  tests/xtro-sharpie/macOS-WebKit.todo
Labels: notes-mention

#15706 [IOSurface] Add support for Xcode 14 beta 5.
  src/iosurface.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-IOSurface.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-IOSurface.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-IOSurface.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-IOSurface.todo
  tests/xtro-sharpie/common-IOSurface.ignore
  tests/xtro-sharpie/iOS-IOSurface.todo
  tests/xtro-sharpie/macOS-IOSurface.todo
  tests/xtro-sharpie/tvOS-IOSurface.todo
Labels: notes-mention

#15736 [apidiff] Fix apidiff for .NET 7.
  tools/apidiff/Makefile
Labels: skip-all-tests, not-notes-worthy

#15698 [msbuild] Unify the DetectSigningIdentity task between iOS and Mac.
  msbuild/Xamarin.Mac.Tasks/Tasks/DetectSigningIdentity.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentity.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#15738 Bump xharness.
  tests/xharness/xharness.csproj
Labels: not-notes-worthy

#15742 [AutomaticAssessmentConfiguration] Updates for Xcode14 Beta5
  src/automaticassessmentconfiguration.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-AutomaticAssessmentConfiguration.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AutomaticAssessmentConfiguration.todo
  tests/xtro-sharpie/iOS-AutomaticAssessmentConfiguration.todo
  tests/xtro-sharpie/macOS-AutomaticAssessmentConfiguration.todo
Labels: notes-mention

#15743 [xcode14] Bump to Xcode 14 Beta 6
  Make.config
Labels: not-notes-worthy

#15755 [msbuild] Build for iOS if any platform except macOS is enabled.
  msbuild/Makefile
Labels: not-notes-worthy

#15748 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#15739 Bump api references to latest 6.0.4xx / d17-3 builds.
  DOWNLOADS.md
  Make.config
Labels: not-notes-worthy

#15756 [configure] Treat each platform separately.
  configure
Labels: not-notes-worthy

#15735 [devops] Make the binlog artifact name unique.
  tools/devops/automation/templates/build/build-pkgs.yml
  tools/devops/automation/templates/tests/run-tests.yml
Labels: not-notes-worthy

#15697 [dotnet] Honor existing values for BuildIpa and CreatePackage. Fixes #15696.
  dotnet/targets/Xamarin.Shared.Sdk.Publish.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
Labels: bug

#15752 [nnyeah] Don't build nnyeah unless the iOS build is enabled.
  tools/nnyeah/Makefile
Labels: not-notes-worthy

#15699 [VideoSubscriberAccount] Update API to support Xcode 14 beta 5.
  src/videosubscriberaccount.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/iOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/macOS-VideoSubscriberAccount.todo
  tests/xtro-sharpie/tvOS-VideoSubscriberAccount.todo
Labels: notes-mention

#15751 [src] Don't build iOS libs unless iOS is enabled.
  src/Makefile
Labels: not-notes-worthy

#15514 Improve console output by telling dotnet to not complain about any workload updates.
  Make.config
Labels: not-notes-worthy

#15750 [tests] Adjust MonoTouchFixtures.SceneKit.Invert to cope with tiny expected differences.
  tests/monotouch-test/SceneKit/SCNMatrixTest.cs
Labels: not-notes-worthy

#15763 [tests] Ignore any NuGet failures in PackageReferenceTests.SatellitesFromNuget. Fixes #xamarin/maccore@2612.
  tests/common/mac/ProjectTestHelpers.cs
  tests/mmptest/src/PackageReferenceTests.cs
Labels: not-notes-worthy

#15702 [PencilKit] Added support for Xcode 14 beta 5.
  src/pencilkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PencilKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-PencilKit.todo
  tests/xtro-sharpie/iOS-PencilKit.todo
  tests/xtro-sharpie/macOS-PencilKit.todo
Labels: notes-mention

#15760 [release/7.0.1xx-rc1] [msbuild] Fix the FindAotCompiler task for .NET 7.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
Labels: not-notes-worthy, backported

#15765 [release/7.0.1xx-rc1] Revert "[tests] Update expected error message texts."
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#15704 [IntentsUI] Add support for Xcode 14 beta 5.
  src/intents.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-IntentsUI.todo
  tests/xtro-sharpie/macOS-IntentsUI.todo
Labels: notes-mention

#15707 [FSEvents] Add support for Xcode 14 beta 5.
  src/CoreServices/FSEvents.cs
Labels: notes-mention

#15718 [NaturalLanguage] Updates for Xcode14 Beta 2
  src/NaturalLanguage/Enums.cs
  tests/monotouch-test/NaturalLanguage/EmbeddingTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-NaturalLanguage.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-NaturalLanguage.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-NaturalLanguage.todo
  tests/xtro-sharpie/iOS-NaturalLanguage.todo
  tests/xtro-sharpie/macOS-NaturalLanguage.todo
  tests/xtro-sharpie/tvOS-NaturalLanguage.todo
  tests/xtro-sharpie/watchOS-NaturalLanguage.todo
Labels: notes-mention

#15740 [IdentityLookup] Updates for Xcode14 beta1
  src/identitylookup.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-IdentityLookup.todo
  tests/xtro-sharpie/iOS-IdentityLookup.todo
Labels: notes-mention

#15717 [WebKit] Apple fixed issue #15593
  src/wkwebkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-WebKit.ignore
  tests/xtro-sharpie/common-WebKit.ignore
Labels: notes-mention

#15729 [msbuild] Automatically detect any Entitlements.plist files in the root project in .NET.
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  tests/dotnet/AutoDetectEntitlements/AppDelegate.cs
  tests/dotnet/AutoDetectEntitlements/MacCatalyst/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/MacCatalyst/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/MacCatalyst/Makefile
  tests/dotnet/AutoDetectEntitlements/Makefile
  tests/dotnet/AutoDetectEntitlements/iOS/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/iOS/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/iOS/Makefile
  tests/dotnet/AutoDetectEntitlements/macOS/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/macOS/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/macOS/Makefile
  tests/dotnet/AutoDetectEntitlements/shared.csproj
  tests/dotnet/AutoDetectEntitlements/shared.mk
  tests/dotnet/AutoDetectEntitlements/tvOS/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/tvOS/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/tvOS/Makefile
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/DotnetTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/ProjectTest.cs
Labels: not-notes-worthy

#15759 [msbuild] Fix the FindAotCompiler task for .NET 7.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
Labels: not-notes-worthy

#15767 [runtime] Add some debugging aid to xamarin_release_managed_ref.
  runtime/runtime.m
Labels: not-notes-worthy

#15720 [dotnet] macOS/MacCatalyst Archive and publishing support
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#15754 [runtime] Only build macOS libraries if we're building for macOS.
  runtime/Makefile
Labels: not-notes-worthy

#15770 [tests] Add global imports to the .NET unit tests to simplify code.
  tests/dotnet/UnitTests/AssetsTest.cs
  tests/dotnet/UnitTests/BundleStructureTest.cs
  tests/dotnet/UnitTests/GlobalImports.cs
  tests/dotnet/UnitTests/IncrementalBuildTest.cs
  tests/dotnet/UnitTests/PackTest.cs
  tests/dotnet/UnitTests/PartialAppManifestTest.cs
  tests/dotnet/UnitTests/PostBuildTest.cs
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/dotnet/UnitTests/PublishTrimmedTest.cs
  tests/dotnet/UnitTests/TemplateProjectTest.cs
  tests/dotnet/UnitTests/TemplateTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
Labels: not-notes-worthy

#15746 [UIKit] Wrap the call to UIApplicationMain in a @try/@catch handler.
  runtime/bindings.h
  runtime/bindings.m
  src/UIKit/UIApplication.cs
Labels: not-notes-worthy

#15779 [ImageIO] Updates for Xcode14 Beta 3
  src/imageio.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-ImageIO.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-ImageIO.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-ImageIO.todo
  tests/xtro-sharpie/iOS-ImageIO.todo
  tests/xtro-sharpie/macOS-ImageIO.todo
  tests/xtro-sharpie/tvOS-ImageIO.todo
  tests/xtro-sharpie/watchOS-ImageIO.todo
Labels: notes-mention

#15773 [tools] Don't build legacy stuff unless legacy is enabled.
  tools/Makefile
Labels: not-notes-worthy

#15654 [Mediaplayer] Add support for xcode14 beta 4.
  src/avfoundation.cs
  src/mediaplayer.cs
  tests/cecil-tests/AttributeTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MediaPlayer.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-MediaPlayer.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-MediaPlayer.todo
  tests/xtro-sharpie/iOS-MediaPlayer.todo
  tests/xtro-sharpie/macOS-MediaPlayer.todo
  tests/xtro-sharpie/tvOS-MediaPlayer.todo
  tests/xtro-sharpie/watchOS-MediaPlayer.todo
Labels: notes-mention

#15703 [Intents] Add support for Xcode 14 beta 5.
  src/intents.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-Intents.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Intents.todo
  tests/xtro-sharpie/common-Intents.ignore
  tests/xtro-sharpie/iOS-Intents.todo
  tests/xtro-sharpie/watchOS-Intents.todo
Labels: notes-mention

#15780 [dotnet] Disable warning about using a preview version of .NET.
  Make.config
Labels: not-notes-worthy

#15781 Merge main into net7.0.
  DOWNLOADS.md
  Make.config
  NuGet.config
  configure
  dotnet/targets/Xamarin.Shared.Sdk.Publish.targets
  mk/xamarin.mk
  msbuild/Makefile
  msbuild/Xamarin.Mac.Tasks/Tasks/DetectSigningIdentity.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/Archive.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentity.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Windows/Zip.cs
  runtime/Makefile
  runtime/runtime.m
  src/Makefile
  tests/common/mac/ProjectTestHelpers.cs
  tests/dotnet/AutoDetectEntitlements/AppDelegate.cs
  tests/dotnet/AutoDetectEntitlements/MacCatalyst/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/MacCatalyst/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/MacCatalyst/Makefile
  tests/dotnet/AutoDetectEntitlements/Makefile
  tests/dotnet/AutoDetectEntitlements/iOS/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/iOS/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/iOS/Makefile
  tests/dotnet/AutoDetectEntitlements/macOS/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/macOS/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/macOS/Makefile
  tests/dotnet/AutoDetectEntitlements/shared.csproj
  tests/dotnet/AutoDetectEntitlements/shared.mk
  tests/dotnet/AutoDetectEntitlements/tvOS/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/tvOS/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/tvOS/Makefile
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/mmptest/src/PackageReferenceTests.cs
  tests/monotouch-test/SceneKit/SCNMatrixTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/DotnetTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/ProjectTest.cs
  tests/xharness/xharness.csproj
  tools/devops/automation/templates/build/build-pkgs.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/tests/run-tests.yml
  tools/nnyeah/Makefile
Labels: not-notes-worthy

#15782 Merge main into xcode14.
  DOWNLOADS.md
  Make.config
  NuGet.config
  configure
  dotnet/targets/Xamarin.Shared.Sdk.Publish.targets
  eng/Version.Details.xml
  eng/Versions.props
  msbuild/Makefile
  msbuild/Xamarin.Mac.Tasks/Tasks/DetectSigningIdentity.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ArchiveTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/Archive.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentity.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.props
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.props
  msbuild/Xamarin.iOS.Tasks.Windows/Zip.cs
  runtime/Makefile
  runtime/runtime.m
  src/Makefile
  tests/common/DotNet.cs
  tests/common/mac/ProjectTestHelpers.cs
  tests/dotnet/AutoDetectEntitlements/AppDelegate.cs
  tests/dotnet/AutoDetectEntitlements/MacCatalyst/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/MacCatalyst/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/MacCatalyst/Makefile
  tests/dotnet/AutoDetectEntitlements/Makefile
  tests/dotnet/AutoDetectEntitlements/iOS/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/iOS/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/iOS/Makefile
  tests/dotnet/AutoDetectEntitlements/macOS/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/macOS/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/macOS/Makefile
  tests/dotnet/AutoDetectEntitlements/shared.csproj
  tests/dotnet/AutoDetectEntitlements/shared.mk
  tests/dotnet/AutoDetectEntitlements/tvOS/AutoDetectEntitlements.csproj
  tests/dotnet/AutoDetectEntitlements/tvOS/Entitlements.plist
  tests/dotnet/AutoDetectEntitlements/tvOS/Makefile
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/mmptest/src/PackageReferenceTests.cs
  tests/monotouch-test/SceneKit/SCNMatrixTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/DotnetTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/ProjectsTests/ProjectTest.cs
  tests/xharness/xharness.csproj
  tools/devops/automation/templates/build/build-pkgs.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/tests/run-tests.yml
  tools/nnyeah/Makefile
Labels: not-notes-worthy

#15774 [.NET/CoreMidi] Use [UnmanagedCallersOnly] instead of [MonoPInvokeCallback] Partial Fix for #10470
  src/CoreMidi/MidiServices.cs
Labels: run-all-tests, skip-device-tests, not-notes-worthy, run-dotnet-tests

#15629 [MetricKit] Added support for Xcode 14 beta 1 & 3
  src/MetricKit/MXEnums.cs
  src/frameworks.sources
  src/metrickit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetricKit.todo
  tests/xtro-sharpie/iOS-MetricKit.todo
Labels: notes-mention

#15694 [UIKit] Add support for Xcode 14 up to beta 5.
  src/AppKit/Enums.cs
  src/UIKit/UIBarButtonItem.cs
  src/UIKit/UIEnums.cs
  src/UIKit/UIFont.cs
  src/appkit.cs
  src/generator.cs
  src/uikit.cs
  src/xkit.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/monotouch-test/UIKit/FontTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.todo
  tests/xtro-sharpie/common-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/macOS-AppKit.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-UIKit.todo
Labels: notes-mention

#15788 [tools] Don't call mono_marshal_ilgen_init in .NET.
  tools/common/Target.cs
Labels: not-notes-worthy

#15747 [tests] Improve handling timed out macOS tests.
  tests/run-with-timeout.sh
  tools/devops/automation/scripts/bash/collect-and-upload-crash-reports.sh
  tools/devops/automation/templates/mac/build.yml
Labels: skip-all-tests, not-notes-worthy

#15786 [main] [ci] Add support to main for multi-targeting in VS
  dotnet/Workloads/Microsoft.NET.Sdk.MacCatalyst/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.macOS/WorkloadManifest.targets
  dotnet/Workloads/Microsoft.NET.Sdk.tvOS/WorkloadManifest.targets
  dotnet/Workloads/vs-workload.template.props
  dotnet/targets/WorkloadManifest.MacCatalyst.template.json
  dotnet/targets/WorkloadManifest.iOS.template.json
  dotnet/targets/WorkloadManifest.macOS.template.json
  dotnet/targets/WorkloadManifest.tvOS.template.json
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: backported

#15516 [tests] Improve detection of bad CI networks.
  tests/EmbeddedResources/EmbeddedResources.csproj
  tests/common/TestRuntime.cs
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/CryptoTest.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy

#15753 [tools] Only build mtouch if iOS, tvOS or watchOS is enabled.
  tools/Makefile
Labels: not-notes-worthy

#15793 [tests] Allow setting CONFIG to specify the Configuration to build.
  tests/common/shared-dotnet.mk
Labels: not-notes-worthy

#15791 [devops] Remove unused file.
  tools/devops/automation/templates/common/upload-vsdrops.yml
Labels: not-notes-worthy

#15797 Add 'None' build action to ObjC binding items
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
Labels: not-notes-worthy

#15814 [net7.0] [CI] Bump microbuild.
  tools/devops/automation/templates/sign-and-notarized/setup.yml
Labels: not-notes-worthy, backported

#15815 [xcode14] [CI] Bump microbuild.
  tools/devops/automation/templates/sign-and-notarized/setup.yml
Labels: not-notes-worthy, backported

#15816 [CI] Bump microbuild.
  tools/devops/automation/templates/build/sign-and-notarized.yml
Labels: not-notes-worthy

#15817 [CI] Bump microbuild.
  tools/devops/automation/templates/sign-and-notarized/setup.yml
Labels: not-notes-worthy

#15794 Bump to dotnet/runtime/release/7.0-rc1@06aceb70.
  Make.config
  NuGet.config
  builds/Makefile
  builds/package-download/download-packages.proj
  dotnet/targets/Xamarin.Shared.Sdk.targets
  eng/Version.Details.xml
  eng/Versions.props
  tools/common/Target.cs
Labels: not-notes-worthy

#15802 [devops] Make sure no errors are ignored during signing.
  tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
Labels: not-notes-worthy

#15809 [system-dependencies] Log what we do when downloading extra platforms.
  system-dependencies.sh
Labels: not-notes-worthy

#15769 [dotnet] Make relase builds for desktop universal by default. Fixes #15620.
  dotnet/targets/Xamarin.Shared.Sdk.props
  tests/common/shared-dotnet.csproj
  tests/linker/ios/link all/dotnet/shared.csproj
Labels: not-notes-worthy

#15792 [msbuild] Fix a few duplicate compile items warnings.
  msbuild/Xamarin.Localization.MSBuild/Xamarin.Localization.MSBuild.csproj
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
Labels: not-notes-worthy

#15805 [msbuild] Ignore NU1603 for XVS package references.
  msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
Labels: not-notes-worthy

#15692 [GameController] Update bindings for Xcode 14 beta 1-5
  src/GameController/Enums.cs
  src/gamecontroller.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-GameController.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-GameController.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-GameController.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-GameController.todo
  tests/xtro-sharpie/common-GameController.ignore
  tests/xtro-sharpie/iOS-GameController.todo
  tests/xtro-sharpie/macOS-GameController.todo
  tests/xtro-sharpie/tvOS-GameController.todo
Labels: notes-mention

#15790 [FileProvider] Update for Xcode14 binding
  src/fileprovider.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-FileProvider.ignore
  tests/xtro-sharpie/common-FileProvider.ignore
Labels: not-notes-worthy

#15800 [UIKit] Add Preferred Content Size Wrapper
  src/uikit.cs
  tests/monotouch-test/UIKit/UIContentSizeCategoryTest.cs
Labels: notes-mention

#15778 [AppKit] Xcode 14 Beta 1-5
  src/AppKit/Enums.cs
  src/AppKit/NSFont.cs
  src/UIKit/UIFont.cs
  src/appkit.cs
  src/uikit.cs
  src/xkit.cs
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.todo
  tests/xtro-sharpie/macOS-AppKit.ignore
  tests/xtro-sharpie/macOS-AppKit.todo
Labels: notes-mention

#15799 [CoreFoundation] Add deprecation and ignores for Xcode 14 Beta 1-5
  src/CoreFoundation/CFStream.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-CoreFoundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreFoundation.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreFoundation.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreFoundation.todo
  tests/xtro-sharpie/common-CoreFoundation.ignore
  tests/xtro-sharpie/iOS-CoreFoundation.todo
  tests/xtro-sharpie/macOS-CoreFoundation.todo
  tests/xtro-sharpie/tvOS-CoreFoundation.todo
  tests/xtro-sharpie/watchOS-CoreFoundation.todo
Labels: notes-mention

#15818 [WebKit] Added missing properties related to UIKit
  src/wkwebkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-WebKit.ignore
  tests/xtro-sharpie/common-WebKit.ignore
Labels: notes-mention

#15828 [devops] Stop doing things that don't work.
  tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
Labels: not-notes-worthy
