Repository dotnet/macios, pull requests merged in 2022-06, with the labels that each got.

#15149 [perf] Cache `Runtime.IsUserType` results
  src/ObjCRuntime/Runtime.cs
Labels: community, notes-mention

#15175 [CI] Using templates does not allow to run the pipeline without access to ESRP.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/main-stage.yml
  tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml
  tools/devops/automation/templates/sign-and-notarized/setup.yml
  tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
Labels: enhancement, not-notes-worthy

#15164 [modelio] Add nullability to (generated and manual) bindings
  src/ModelIO/MDLAnimatedQuaternion.cs
  src/ModelIO/MDLAnimatedValueTypes.cs
Labels: not-notes-worthy

#15163 [metalperformanceshaders] Add nullability to (generated and manual) bindings
  src/MetalPerformanceShaders/MPSCnnConvolutionDescriptor.cs
  src/MetalPerformanceShaders/MPSCnnKernel.cs
  src/MetalPerformanceShaders/MPSCnnNeuron.cs
  src/MetalPerformanceShaders/MPSDefs.cs
  src/MetalPerformanceShaders/MPSImageBatch.cs
  src/MetalPerformanceShaders/MPSImageScale.cs
  src/MetalPerformanceShaders/MPSKernel.cs
  src/MetalPerformanceShaders/MPSNDArray.cs
  src/MetalPerformanceShaders/MPSNNGraph.cs
  src/MetalPerformanceShaders/MPSStateBatch.cs
  src/MetalPerformanceShaders/MPSStateResourceList.cs
  src/metalperformanceshaders.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-MetalPerformanceShaders.todo
  tests/xtro-sharpie/api-annotations-dotnet/common-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/common-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/iOS-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/macOS-MetalPerformanceShaders.ignore
  tests/xtro-sharpie/tvOS-MetalPerformanceShaders.ignore
Labels: not-notes-worthy

#15191 [nnyeah] Report on work done on ctors
  tools/nnyeah/nnyeah/ConstructorTransforms.cs
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/unit/ConstructorTransformTests.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15194 [CI] Allow to build PRs agains net* branches.
  tools/devops/automation/build-pull-request.yml
Labels: not-notes-worthy

#15195 [net7.0] [CI] Allow to build PRs agains net* branches.
  tools/devops/automation/build-pull-request.yml
Labels: not-notes-worthy, backported

#15197 [release/6.0.4xx] [dotnet] Condition default inclusion on the target framework version.
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
Labels: not-notes-worthy, backported

#15183 [dotnet] Change condition when to include the System.Runtime.InteropServices.NFloat.Internal package reference.
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#15182 [tests] Remove ignore because corresponding bug has been fixed.
  tests/linker/ios/dont link/CalendarTest.cs
Labels: not-notes-worthy

#15181 [tests] We're not implementing Mac Catalyst for legacy Xamarin.iOS.
  tests/introspection/ApiPInvokeTest.cs
Labels: not-notes-worthy

#15180 [dotnet] Remove some dead build logic.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#15139 [runtime] Improve error reporting when calling mono_assembly_open.
  runtime/coreclr-bridge.m
  runtime/runtime.m
Labels: not-notes-worthy

#15179 [CarPlay] Propagate constructors to derived classes. Fixes #15169.
  src/carplay.cs
Labels: bug, not-notes-worthy

#15192 [build] Version .NET VS manifest file
  dotnet/Makefile
  dotnet/Workloads/vs-workload.template.props
Labels: not-notes-worthy

#15184 [release/6.0.4xx] [dotnet] Change condition when to include the System.Runtime.InteropServices.NFloat.Internal package reference.
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
Labels: run-all-tests, skip-device-tests, not-notes-worthy, backported

#15193 [nnyeah] Test now passes. Fixes #15120
  tools/nnyeah/tests/unit/CompileALibrary.cs
Labels: bug, skip-all-tests, not-notes-worthy

#15171 Allow overriding HOME variable in dotnet remote builds
  msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
Labels: not-notes-worthy

#15090 [corefoundation] Add nullability to (generated and manual) bindings
  src/CoreFoundation/Architecture.cs
  src/CoreFoundation/CFBundle.cs
  src/CoreFoundation/CFDataBuffer.cs
  src/CoreFoundation/CFDictionary.cs
  src/CoreFoundation/CFException.cs
  src/CoreFoundation/CFMessagePort.cs
  src/CoreFoundation/CFMutableString.cs
  src/CoreFoundation/CFNetwork.cs
  src/CoreFoundation/CFNotificationCenter.cs
  src/CoreFoundation/CFPreferences.cs
  src/CoreFoundation/CFPropertyList.cs
  src/CoreFoundation/CFProxySupport.cs
  src/CoreFoundation/CFReadStream.cs
  src/CoreFoundation/CFRunLoop.cs
  src/CoreFoundation/CFSocket.cs
  src/CoreFoundation/CFStream.cs
  src/CoreFoundation/CFString.cs
  src/CoreFoundation/CFType.cs
  src/CoreFoundation/CFUrl.cs
  src/CoreFoundation/CFWriteStream.cs
  src/CoreFoundation/Dispatch.cs
  src/CoreFoundation/DispatchBlock.cs
  src/CoreFoundation/DispatchData.cs
  src/CoreFoundation/DispatchIO.cs
  src/CoreFoundation/DispatchQueueSynchronizationContext.cs
  src/CoreFoundation/DispatchSource.cs
  src/CoreFoundation/OSLog.cs
  src/ObjCRuntime/ThrowHelper.cs
Labels: not-notes-worthy

#15098 [coremidi] Add nullability to (generated and manual) bindings
  src/CoreMidi/MidiCIDeviceIdentification.cs
  src/CoreMidi/MidiServices.cs
  src/CoreMidi/MidiThruConnection.cs
  src/CoreMidi/MidiThruConnectionParams.cs
Labels: not-notes-worthy

#15111 [homekit] Add nullability to (generated and manual) bindings
  src/HomeKit/HMActionSet.cs
  src/HomeKit/HMCharacteristic.cs
  src/HomeKit/HMCharacteristicMetadata.cs
  src/HomeKit/HMCharacteristicProperties.cs
  src/HomeKit/HMCompat.cs
  src/HomeKit/HMEventTrigger.cs
  src/HomeKit/HMHome.cs
  src/HomeKit/HMService.cs
  src/homekit.cs
  tests/monotouch-test/HomeKit/HMCharacteristicTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-HomeKit.ignore
  tests/xtro-sharpie/common-HomeKit.ignore
Labels: not-notes-worthy

#15127 [imagecapturecore] Add nullability to (generated and manual) bindings
  src/imagecapturecore.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-ImageCaptureCore.ignore
  tests/xtro-sharpie/macOS-ImageCaptureCore.ignore
Labels: not-notes-worthy

#15066 [coremedia] Add nullability to (generated and manual) bindings
  src/CoreMedia/CMAttachmentBearer.cs
  src/CoreMedia/CMCustomBlockAllocator.cs
  src/CoreMedia/CMTextMarkupAttributes.cs
  src/CoreMedia/CMTime.cs
  src/CoreMedia/CoreMedia.cs
  src/CoreMedia/ICMAttachmentBearer.cs
  src/Foundation/DictionaryContainer.cs
Labels: not-notes-worthy

#15206 [CI] Ensure that with the new ci/pr pipelines we can sign in the older branch.
  tools/devops/automation/templates/build/sign-and-notarized.yml
Labels: not-notes-worthy

#15196 [dotnet] Condition default inclusion on the target framework version.
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
Labels: not-notes-worthy

#15185 [msbuild] Simplify code to remove metadata.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileSceneKitAssetsTaskBase.cs
Labels: not-notes-worthy

#15176 [msbuild] Unify the CompileSceneKitAsset task logic between iOS and Mac and improve it.
  msbuild/Xamarin.Mac.Tasks/Tasks/CompileSceneKitAssets.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileSceneKitAssetsTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileSceneKitAssets.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileSceneKitAssetsTaskBase.cs
Labels: not-notes-worthy

#15207 [nneah] tests now pass
  tools/nnyeah/tests/integration/IntegrationExamples.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15219 [net7.0] [CI] Fix credscan false positive.
  src/CoreFoundation/CFProxySupport.cs
Labels: not-notes-worthy, backported

#15221 [CI] Correctly sign and notarise only on the CI pipeline.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/build/build-pkgs.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
Labels: not-notes-worthy

#15211 [build] Remove more unused variables after the VS dependency was removed.
  Make.config
Labels: not-notes-worthy

#15200 [UIKit] Correct nullability attributes for parts of UIKit
  src/uikit.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
Labels: community

#15224 [CI] Ignore test on macOS because the class is not present. Fixes test failures.
  tests/monotouch-test/HomeKit/HMCharacteristicTest.cs
Labels: not-notes-worthy

#15214 [tools] Make sure to finish the P/Invoke generator output before running the static registrar. Fixes #15190.
  src/Simd/MatrixFloat3x3RM.cs
  tests/dotnet/UnitTests/ProjectTest.cs
  tools/common/StaticRegistrar.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
  tools/mmp/driver.cs
  tools/mtouch/Target.mtouch.cs
Labels: not-notes-worthy

#15213 [tests] Fix nullability warning in the .NET tests.
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#15226 [CI] Remove the usage of python2 and move to python 3.
  tools/devops/automation/templates/common/setup.yml
  tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
Labels: not-notes-worthy

#15227 [build] Fix invalid cache management by 'dotnet tool restore'.
  Make.config
  builds/Makefile
Labels: skip-all-tests, not-notes-worthy

#15225 [nnyeah] add code to handle get_ClassHandle calls. Fixes #15218
  tools/nnyeah/nnyeah/AssemblyConverter.cs
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/unit/ClassHandleUnitTests.cs
Labels: bug, skip-all-tests, not-notes-worthy

#15240 [Tests] Ensure we do check the catalyst version on catalyst.
  tests/monotouch-test/HomeKit/HMCharacteristicTest.cs
Labels: not-notes-worthy

#15235 [apidiff] Bump the .NET reference files to the final stable version we released.
  Make.config
Labels: skip-all-tests, not-notes-worthy

#15241 [devops] Fix computation of the vsdrops uri prefix.
  tools/devops/automation/templates/tests/run-tests.yml
Labels: not-notes-worthy, skip-dotnet-tests

#15245 [CI] The cron jobs do not need to use ESRP signing.
  tools/devops/automation/build-cronjob.yml
Labels: not-notes-worthy

#15249 [Siminstaller] Print valid arguments when a unvalid one is provided.
  tools/siminstaller/Program.cs
Labels: enhancement, not-notes-worthy

#15248 [CI] Ensure we do upload the agent logs in case of failure.
  tools/devops/automation/templates/common/mac-agent-logs.yml
  tools/devops/automation/templates/common/teardown.yml
Labels: not-notes-worthy

#15259 [CI] Conditions have no meanign in templates.
  tools/devops/automation/templates/common/teardown.yml
Labels: not-notes-worthy

#15205 [CI] Remove the need of a variable to state if we are building a PR.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-pkgs.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/main-stage.yml
  tools/devops/automation/templates/release/vs-insertion-prep.yml
  tools/devops/automation/templates/sign-and-notarized/dotnet-signing.yml
  tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml
  tools/devops/automation/templates/sign-and-notarized/setup.yml
  tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
  tools/devops/automation/templates/variables.yml
Labels: not-notes-worthy

#15257 [runtime] Fix 'skip_nested_brace' to not read past the string. Fixes #15253.
  runtime/trampolines.m
  tests/monotouch-test/ObjCRuntime/Messaging.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: bug

#15246 [nnyeah] ensure that outside invocations of IntPtr constructors will work correctly
  tools/nnyeah/nnyeah/ConstructorTransforms.cs
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/unit/ClassHandleUnitTests.cs
  tools/nnyeah/tests/unit/ConstructorTransformTests.cs
  tools/nnyeah/tests/unit/utils/ReworkerHelper.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15260 [Siminstaller] Use latest version of the lang and enable nullability.
  tools/siminstaller/Program.cs
  tools/siminstaller/siminstaller.csproj
Labels: not-notes-worthy

#15268 [CI] Do not provision simulators on builds.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#15272 [CI] Remove the sim provisioning when building on EO machines.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#15264 [release/6.0.4xx] Backport build fixes
  Make.config
  builds/Makefile
  tools/devops/automation/templates/build/sign-and-notarized.yml
  tools/devops/automation/templates/common/setup.yml
Labels: not-notes-worthy

#15265 [introspection] Fix protocol checks on iOS and tvOS 12.4.
  tests/introspection/iOS/iOSApiProtocolTest.cs
Labels: run-old-simulator-tests, not-notes-worthy

#15255 [tools] Fix nunit3-console shell scripts.
  tools/nunit3-console-3.10.0
  tools/nunit3-console-3.11.1
  tools/nunit3-console-3.9.0
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#15254 [msbuild] Only pass -z to dsymutil when using Xcode 13.2 or earlier.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DSymUtilTaskBase.cs
Labels: not-notes-worthy

#15234 [tests] Ignore the CS1416 warning by default in .NET test projects.
  tests/common/shared-dotnet.csproj
Labels: not-notes-worthy

#15262 [passkit] Add nullability to (generated and manual) bindings
  src/PassKit/PKPaymentRequest.cs
  src/passkit.cs
  tests/monotouch-test/PassKit/PKPassTest.cs
  tests/monotouch-test/PassKit/PKPaymentRequestTest.cs
  tests/monotouch-test/PassKit/PKPaymentSummaryItemTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-PassKit.ignore
  tests/xtro-sharpie/common-PassKit.ignore
Labels: not-notes-worthy

#15270 [nnyeah] Added correct mapping for NSObject.Handle fixing #15261
  tools/nnyeah/nnyeah/AssemblyComparator/TypeReworker.cs
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/unit/ClassHandleUnitTests.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15275 [release/6.0.3xx] Merge 'release/6.0.4xx' into release/6.0.3xx
  .config/dotnet-tools.json
  Make.config
  Make.versions
  builds/Makefile
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  dotnet/targets/Xamarin.Shared.Sdk.targets
  mk/quiet.mk
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.Messaging.Apple.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
  src/Makefile
  system-dependencies.sh
  tests/common/Configuration.cs
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/CryptoTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/linker/mac/LinkAnyTest.cs
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
  tools/devops/automation/VSMacVersion.ps1
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/build/build-pkgs.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
Labels: not-notes-worthy

#15287 [release/6.0.4xx] [tests] Backport a few introspection fixes.
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
Labels: not-notes-worthy

#15291 [release/6.0.3xx] Fix release branch naming.
  Make.config
Labels: not-notes-worthy

#15282 [CI] Use isPR parameter instead of the build reason on the loc translations.
  tools/devops/automation/templates/loc-translations.yml
Labels: not-notes-worthy

#15293 [CI] Add missing paramenter.
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#15292 [nnyeah] test for private classes fixing #15223
  tools/nnyeah/integration/API/IntegrationAPI.cs
  tools/nnyeah/integration/Consumer/Consumer.cs
Labels: bug, skip-all-tests, not-notes-worthy

#15256 [msbuild] Unify the DetectSdkLocations task logic between iOS and Mac.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/DetectSdkLocations.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSdkLocations.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/DetectSdkLocationsTaskTests.cs
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#15288 [release/6.0.3xx] [tests] Backport a few introspection fixes.
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
Labels: not-notes-worthy

#15160 [SceneKit] Fix SCNMatrix4 in .NET. Fixes #15094.
  src/SceneKit/SCNMatrix4_dotnet.cs
  src/SceneKit/SCNVector3.cs
  src/SceneKit/SCNVector4.cs
  tests/bindings-test/StructsAndEnums.cs
  tests/monotouch-test/Asserts.cs
  tests/monotouch-test/SceneKit/SCNMatrixTest.cs
  tests/monotouch-test/SceneKit/SCNVector3Test.cs
  tests/monotouch-test/SceneKit/SCNVector4Test.cs
  tests/monotouch-test/monotouch-test.csproj
  tests/test-libraries/libtest.h
  tests/test-libraries/libtest.m
  tests/test-libraries/rename.h
  tests/xammac_tests/xammac_tests.csproj
  tools/devops/automation/templates/tests/run-tests.yml
Labels: bug, breaking-change, note-highlight, dotnet, only-dotnet

#15283 [CI] Use isPR parameter instead of the build reason on publishing nugets.
  tools/devops/automation/templates/sign-and-notarized/dotnet-signing.yml
  tools/devops/automation/templates/sign-and-notarized/publish-nugets.yml
Labels: not-notes-worthy

#15284 [CI] Use isPR parameter instead of the build reason on the checkout template.
  tools/devops/automation/templates/build/api-diff-process-results.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/common/checkout.yml
  tools/devops/automation/templates/common/clean.yml
  tools/devops/automation/templates/common/configure.yml
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/common/upload-vsdrops.yml
  tools/devops/automation/templates/common/upload-vsts-tests.yml
  tools/devops/automation/templates/governance-checks.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/mac/stage.yml
  tools/devops/automation/templates/main-stage.yml
  tools/devops/automation/templates/publish-html-result.yml
  tools/devops/automation/templates/sign-and-notarized/artifact-github-comment.yml
  tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml
  tools/devops/automation/templates/tests/build.yml
  tools/devops/automation/templates/tests/stage.yml
  tools/devops/automation/templates/windows/build.yml
  tools/devops/automation/templates/windows/stage.yml
Labels: not-notes-worthy

#15281 [CI] Use isPR parameter instead of the build reason.
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#15266 [build] Set DEVELOPER_DIR and MD_APPLE_SDK_ROOT to the Xcode we're using.
  Make.config
  system-dependencies.sh
  tests/Makefile
  tests/common/mac/project_building.mk
  tests/dotnet/size-comparison/common.mk
  tests/mac-binding-project/Makefile
  tests/mmp-regression/Makefile
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ToolTasksBinPathTest.cs
  tests/packaged-macos-tests.mk
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#15297 [release/6.0.3xx] [SceneKit] Fix SCNMatrix4 in .NET. Fixes #15094.
  src/SceneKit/SCNMatrix4_dotnet.cs
  src/SceneKit/SCNVector3.cs
  src/SceneKit/SCNVector4.cs
  tests/bindings-test/StructsAndEnums.cs
  tests/monotouch-test/Asserts.cs
  tests/monotouch-test/SceneKit/SCNMatrixTest.cs
  tests/monotouch-test/SceneKit/SCNVector3Test.cs
  tests/monotouch-test/SceneKit/SCNVector4Test.cs
  tests/monotouch-test/monotouch-test.csproj
  tests/test-libraries/libtest.h
  tests/test-libraries/libtest.m
  tests/test-libraries/rename.h
  tests/xammac_tests/xammac_tests.csproj
  tools/devops/automation/templates/tests/run-tests.yml
Labels: bug, breaking-change, note-highlight, dotnet, backported, only-dotnet

#15303 Use unix-style line endings in project files.
  builds/fix-maccatalyst-assembly/fix-maccatalyst-assembly.csproj
  docs/website/xamarin-analysis-doc-tool/xamarin-analysis-doc.csproj
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/iOSTabbedApp1.csproj
  dotnet/Templates/Microsoft.macOS.Templates/macos/macOSApp1.csproj
  msbuild/Xamarin.Localization.MSBuild/Xamarin.Localization.MSBuild.csproj
  tests/bgen/bgen-tests.csproj
  tests/bindings-test/macOS/bindings-test.csproj
  tests/common/TestProjects/AppWithExtraArgumentThatOverrides/AppWithExtraArgumentThatOverrides.csproj
  tests/common/TestProjects/AssemblyRegistration/AssemblyRegistration.csproj
  tests/common/TestProjects/ImmutableCollection_Test/ImmutableCollection_Test/ImmutableCollection_Test.csproj
  tests/common/TestProjects/MyCocoaSceneKitApp/MyCocoaSceneKitApp.csproj
  tests/common/TestProjects/MySatelliteAssembliesBug/FooAssembly/FooAssembly.csproj
  tests/common/TestProjects/MySatelliteAssembliesBug/iOSBinding/iOSBinding.csproj
  tests/common/TestProjects/MySceneKitApp/MySceneKitApp.csproj
  tests/common/TestProjects/MySceneKitLibrary/MySceneKitLibrary.csproj
  tests/common/TestProjects/MyTVMetalGame/MyTVMetalGame.csproj
  tests/common/TestProjects/MyTVServicesExtension/MyTVServicesExtension.csproj
  tests/common/TestProjects/RoslynTestApp/Full/RoslynTestApp.csproj
  tests/common/TestProjects/RoslynTestApp/Lib/Full/ReadOnlyTestMacLib/ReadOnlyTestMacLib.csproj
  tests/common/TestProjects/RoslynTestApp/Lib/Modern/ReadOnlyTestMacLib/ReadOnlyTestMacLib.csproj
  tests/common/TestProjects/RoslynTestApp/Modern/RoslynTestApp.csproj
  tests/common/mac/ConsoleXMApp.csproj
  tests/common/mac/Finder/FinderExtensionTest.csproj
  tests/common/mac/NetStandard/NetStandardLib.csproj
  tests/common/mac/Share/ShareExtensionTest.csproj
  tests/common/mac/Today/TodayExtensionTest.csproj
  tests/dotnet/AppWithGenericLibraryReference/Library/macOS/Library.csproj
  tests/dotnet/AppWithResources/macOS/AppWithResources.csproj
  tests/dotnet/AppWithXCAssets/macOS/AppWithXCAssets.csproj
  tests/dotnet/BundleStructure/macOS/BundleStructure.csproj
  tests/dotnet/ExtensionConsumer/macOS/MySimpleApp.csproj
  tests/dotnet/ExtensionProject/macOS/ExtensionProject.csproj
  tests/dotnet/MyCocoaApp/MyCocoaApp.csproj
  tests/dotnet/MySimpleApp/macOS/MySimpleApp.csproj
  tests/dotnet/MySimpleAppWithSatelliteReference/macOS/MySimpleAppWithSatelliteReference.csproj
  tests/dotnet/SimpleAppWithOldReferences/macOS/SimpleAppWithOldReferences.csproj
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/generator/generator-tests.csproj
  tests/linker/mac/link all/link all-mac.csproj
  tests/linker/mac/link sdk/link sdk-mac.csproj
  tests/mmptest/mmptest.csproj
  tests/sampletester/sampletester.csproj
  tests/test-libraries/testgenerator.csproj
  tests/xharness/Xharness.Tests/Xharness.Tests.csproj
  tests/xharness/xharness.csproj
  tests/xtro-sharpie/u2ignore/u2ignore.csproj
  tools/governance/governance.csproj
  tools/install-source/InstallSourcesTests/InstallSourcesTests.csproj
  tools/nnyeah/integration/API/iOSIntegration.csproj
  tools/nnyeah/integration/API/macOSIntegration.csproj
  tools/nnyeah/integration/Consumer/macOS/macOS.csproj
  tools/nnyeah/nnyeah/nnyeah.csproj
  tools/nnyeah/tests/nnyeah-tests.csproj
  tools/siminstaller/siminstaller.csproj
  tools/xibuild/xibuild.csproj
Labels: not-notes-worthy

#15309 [d17-2] Backport build fixes
  Make.config
  builds/Makefile
  tools/devops/automation/templates/build/sign-and-notarized.yml
  tools/devops/automation/templates/common/setup.yml
Labels: not-notes-worthy, backported

#15294 [foundation] Cache parts of `NSObject.ConformsToProtocol`
  src/Foundation/NSObject2.cs
  src/ObjCRuntime/Runtime.cs
Labels: performance, community

#15317 [CI] Do not provision simulators in EO machines.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#15300 chore: Set permissions for GitHub actions
  .github/workflows/label-checker.yml
  .github/workflows/localization-update.yml
  .github/workflows/pwsh-ci.yml
Labels: do-not-merge, community

#15313 [Tests] Add missing nuget.
  tests/generator/generator-tests.csproj
  tests/mmptest/mmptest.csproj
  tests/mtouch/mtouchtests.csproj
  tools/nunit3-console-3.12.0
Labels: not-notes-worthy

#15215 [devops] Collect diagnostic logs from the simulator.
  tests/xharness/AppRunner.cs
  tools/devops/automation/templates/tests/run-tests.yml
Labels: not-notes-worthy

#15311 A .NET 'servicing' release is also a stable release.
  Make.config
Labels: not-notes-worthy

#15329 [Tests] Bump Newtonsoft.Json version
  tests/common/TestProjects/BasicPCLTest/MyLibrary/MyLibrary.csproj
  tests/common/TestProjects/MyAppWithPackageReference/MyAppWithPackageReference.csproj
  tests/common/TestProjects/MyAppWithPackageReference/MyAppWithPackageReference.dotnet.csproj
  tests/common/TestProjects/MyExtensionWithPackageReference/MyExtensionWithPackageReference.csproj
  tests/common/TestProjects/MyExtensionWithPackageReference/MyExtensionWithPackageReference.dotnet.csproj
  tests/mmptest/src/PackageReferenceTests.cs
Labels: enhancement, not-notes-worthy

#15324 [nnyeah] Fix more ctor/handle mapping
  tools/nnyeah/nnyeah/AssemblyComparator/ComparingVisitor.cs
  tools/nnyeah/nnyeah/AssemblyComparator/TypeReworker.cs
  tools/nnyeah/nnyeah/ConstructorTransforms.cs
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/unit/ConstructorTransformTests.cs
Labels: bug, skip-all-tests, not-notes-worthy

#15337 [CI] Fix api diff comment
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/api-diff-process-results.yml
Labels: not-notes-worthy

#15345 [CI] Bump the build timeout.
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#15307 [d17-2] [msbuild] Use the full path to the symbols list file. Fixes #15046.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: bug, backported

#15362 [CI] Ignore branches that start with dev/*
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#15355 [nnyeah] Manage DisposableObject
  tools/nnyeah/nnyeah/ConstructorTransforms.cs
  tools/nnyeah/nnyeah/Reworker.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15341 [CI] Just collect sim logs on debug.
  tools/devops/automation/templates/tests/run-tests.yml
Labels: enhancement, not-notes-worthy

#15364 [CI] Stop running pipelines on debug mode.
  tools/devops/automation/templates/variables.yml
Labels: not-notes-worthy

#15367 Fix introspection selection when old simulators are present.
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: not-notes-worthy

#15334 [CI] Allow to skip all tests in the parallel implementation.
  tools/devops/automation/templates/common/configure.yml
  tools/devops/automation/templates/tests/stage.yml
Labels: skip-all-tests

#15376 [CI] Provide a script to help when doing bot reports.
  tools/devops/automation/scripts/VSTS.psm1
  tools/devops/automation/scripts/bots-info.ps1
Labels: not-notes-worthy

#15380 [Build] Allow to skip the build of Hotrestart.
  Make.config
  dotnet/Makefile
Labels: not-notes-worthy

#15377 [CI] Allow to pass the xcode channel.
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/main-stage.yml
  tools/devops/automation/templates/tests/stage.yml
Labels: not-notes-worthy
