Repository dotnet/macios, pull requests merged in 2022-07, with the labels that each got.

#15405 [xcode14] [CI] Fix the skip of tests.
  tools/devops/automation/templates/tests/stage.yml
Labels: not-notes-worthy, backported

#15406 [CI] Use the Stable Xcode channel in main related branches.
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
Labels: not-notes-worthy

#15409 [Xcode 14] Bump sharpie to a version that supports maccatalyst.
  Make.config
Labels: not-notes-worthy

#15415 [xcode14] [CI] Change logic to take into account that CI has no labels.
  tools/devops/automation/templates/tests/stage.yml
Labels: not-notes-worthy, backported

#15403 [CarPlay] Add support for Xcode 14 beta 1&2.
  src/carplay.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CarPlay.todo
  tests/xtro-sharpie/iOS-CarPlay.todo
Labels: notes-mention

#15401 [build] Commit global.json to get maestro updates.
  Makefile
  global.json
Labels: not-notes-worthy

#15374 [devops] Make sure BUILD_REVISION is set to something during the build.
  tools/devops/automation/templates/build/build-stage.yml
Labels: not-notes-worthy

#15321 [msbuild/tools] Fix path issues in the FilterStaticFrameworks task and ExtractBindingLibraries step. Fixes #15289.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FilterStaticFrameworksTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/FilterStaticFrameworks.cs
  tools/dotnet-linker/Steps/ExtractBindingLibrariesStep.cs
Labels: bug

#15423 Bump xharness.
  tests/xharness/Jenkins/TestSelector.cs
  tests/xharness/Jenkins/TestTasks/RunSimulator.cs
  tests/xharness/Xharness.Tests/packages.config
  tests/xharness/xharness.csproj
Labels: not-notes-worthy

#15392 [generator] Don't use culture-aware API.
  .editorconfig
  src/generator.cs
  tests/monotouch-test/AppKit/NSView.cs
Labels: not-notes-worthy

#15391 [ObjCRuntime] Add missing cases for UIntPtr for determining if a type is a built-in type.
  src/ObjCRuntime/Stret.cs
Labels: not-notes-worthy

#15366 [devops] Enable verbose build.
  tools/devops/automation/templates/build/build.yml
Labels: skip-all-tests, not-notes-worthy

#15358 [CoreCLR] Avoid having any internal calls in managed code for CoreCLR. Fixes #15343.
  src/Foundation/NSObject2.cs
Labels: bug

#15328 [msbuild] Copy partial app manifests to build server if they exists on Windows. Fixes #15267.
  msbuild/Xamarin.iOS.Tasks/Tasks/CompileAppManifest.cs
Labels: bug

#15459 [nnyeah] removed constructor size limit
  tools/nnyeah/nnyeah/ConstructorTransforms.cs
  tools/nnyeah/tests/unit/ConstructorTransformTests.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15449 [siminstaller] Adjust according to recent Xcode changes.
  tools/siminstaller/Program.cs
Labels: not-notes-worthy

#15456 [actions] Add action to re-generate global.json for a dotnet/installer bump.
  .github/workflows/bump-global-json.yml
  Makefile
Labels: skip-all-tests, not-notes-worthy

#15385 [dotnet] Generate Microsoft.<platform>.Sdk.ImplicitNamespaceImports.props.
  dotnet/.gitignore
  dotnet/Makefile
  dotnet/targets/Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.Sdk.ImplicitNamespaceImports.template.props
  dotnet/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
Labels: not-notes-worthy

#15357 [dotnet] Accept invalid runtime identifiers for Restore.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/DotNet.cs
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy

#15429 [tools] Use MONO_AOT_MODE_INTERP_ONLY instead of MONO_AOT_MODE_INTERP for x86_64.
  runtime/mono-runtime.h.t4
  tools/common/Target.cs
Labels: bug

#15387 [dotnet] Generate the AutoImport.props file for each platform.
  dotnet/.gitignore
  dotnet/Makefile
  dotnet/Microsoft.MacCatalyst.Sdk/Sdk/AutoImport.props
  dotnet/Microsoft.iOS.Sdk/Sdk/AutoImport.props
  dotnet/Microsoft.macOS.Sdk/Sdk/AutoImport.props
  dotnet/Microsoft.tvOS.Sdk/Sdk/AutoImport.props
  dotnet/targets/AutoImport.template.props
Labels: not-notes-worthy

#15386 [dotnet] Stop hardcoding the TargetFrameworkVersion in the default items template.
  dotnet/Makefile
  dotnet/targets/Microsoft.Sdk.DefaultItems.template.props
Labels: not-notes-worthy

#15454 [release/6.0.4xx] [CI] Add support to choose the xcodeChannel to be used.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/tests/stage.yml
Labels: not-notes-worthy, backported

#15395 [system-dependencies] Compute the exact path of the path to the additional simulator runtimes.
  system-dependencies.sh
Labels: not-notes-worthy

#15383 Revert workarounds for broken dlopen in Xcode 14 beta 1. Fixes #15231.
  runtime/runtime.m
  src/ObjCRuntime/Constants.cs
  src/generator.cs
  tests/monotouch-test/ObjCRuntime/DlfcnTest.cs
  tests/mtouch/MTouch.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-CoreFoundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/common-ObjCRuntime.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreFoundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-ObjCRuntime.ignore
  tests/xtro-sharpie/common-CoreFoundation.ignore
  tests/xtro-sharpie/common-ObjCRuntime.ignore
  tests/xtro-sharpie/macOS-CoreFoundation.ignore
  tests/xtro-sharpie/macOS-ObjCRuntime.ignore
Labels: not-notes-worthy

#15412 [release/6.0.3xx] [devops] Fix the post-build pipeline after dependent pipeline rename.
  tools/devops/automation/post-build-pipeline.yml
Labels: not-notes-worthy, backported

#15413 [release/6.0.4xx] [devops] Fix the post-build pipeline after dependent pipeline rename.
  tools/devops/automation/post-build-pipeline.yml
Labels: not-notes-worthy, backported

#15433 [release/6.0.3xx] [devops] Make sure BUILD_REVISION is set to something during the build.
  tools/devops/automation/templates/build/build-stage.yml
Labels: not-notes-worthy, backported

#15434 [release/6.0.4xx] [devops] Make sure BUILD_REVISION is set to something during the build.
  tools/devops/automation/templates/build/build-stage.yml
Labels: not-notes-worthy, backported

#15476 [monotouch-test] Improve MonoTouchFixtures.ObjCRuntime.ToggleRefRetainDeadlockTest to get a native stack trace upon failure.
  tests/monotouch-test/ObjCRuntime/ToggleRefRetainDeadlockTest.cs
Labels: not-notes-worthy

#15470 [devops] Simplify validation for cleanup script.
  tools/devops/automation/scripts/bash/clean-bot.sh
Labels: not-notes-worthy

#15441 [runtime] Simplify code to use existing local variable
  src/ObjCRuntime/Class.cs
Labels: not-notes-worthy

#15439 [runtime] Adjust nullability a bit
  src/ObjCRuntime/Class.cs
Labels: not-notes-worthy

#15438 [Dlfcn] Add an enum to specify the mode to dlopen
  src/ObjCRuntime/Dlfcn.cs
Labels: not-notes-worthy

#15435 [runtime] The InitializationFlagsDynamicRegistrar flag is never used, so remove it
  runtime/runtime.m
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy

#15431 [tests] Be explicit about parameters when looking for the Class.FindType method.
  tests/api-shared/ObjCRuntime/Registrar.cs
Labels: not-notes-worthy

#15298 [mlaunch] Download mlaunch from NuGet instead of building from maccore.
  mk/xamarin.mk
  tools/devops/automation/scripts/bash/build-mlaunch-nuget.sh
  tools/devops/automation/templates/build/build-nugets.yml
  tools/mlaunch/.gitignore
  tools/mlaunch/Makefile
  tools/mlaunch/download-mlaunch.csproj
  tools/mlaunch/nupkg/Microsoft.DotNet.Mlaunch.csproj
  tools/mlaunch/nupkg/README.md
  tools/mlaunch/nupkg/build/Microsoft.DotNet.Mlaunch.props
  tools/mlaunch/nupkg/build/Microsoft.DotNet.Mlaunch.targets
Labels: not-notes-worthy

#15481 [devops] Fix publishing in the presence of our global.json
  tools/devops/automation/post-build-pipeline.yml
Labels: not-notes-worthy

#15466 [xharness] Collect and upload any crash reports that occurred during the entire test run.
  tests/xharness/Jenkins/Jenkins.cs
Labels: not-notes-worthy

#15479 [runtime] Remove dead code.
  runtime/monotouch-debug.m
Labels: not-notes-worthy

#15487 [devops] Fix publishing in the presence of our global.json (second part)
  tools/devops/automation/post-build-pipeline.yml
Labels: not-notes-worthy

#15488 [CallKit] Fix missing attr in Callkit classes that appeared in older versions.
  src/callkit.cs
Labels: not-notes-worthy

#15480 [registrar] Improve naming of generated P/Invoke wrappers.
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy

#15474 [msbuild] Unify the CompileAppManifest task logic between iOS and Mac.
  msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/CompileAppManifest.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifest.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
Labels: not-notes-worthy

#15473 [msbuild] Unify the PrepareNativeReferences task between iOS and Mac.
  msbuild/Xamarin.Mac.Tasks/Tasks/PrepareNativeReferences.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/PrepareNativeReferences.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#15477 [nnyeah] limit to one reference to Microsoft.iOS
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/unit/ConstructorTransformTests.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15349 [release/6.0.4xx] A .NET 'servicing' release is also a stable release.
  Make.config
Labels: not-notes-worthy, backported

#15462 [release/6.0.3xx] [runtime] Fix 'skip_nested_brace' to not read past the string. Fixes #15253.
  runtime/trampolines.m
  tests/monotouch-test/ObjCRuntime/Messaging.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: bug, backported

#15467 [release/6.0.4xx] [msbuild] Copy partial app manifests to build server if they exists on Windows. Fixes #15267.
  msbuild/Xamarin.iOS.Tasks/Tasks/CompileAppManifest.cs
Labels: bug, backported

#15460 [release/6.0.3xx] [msbuild] Copy partial app manifests to build server if they exists on Windows. Fixes #15267.
  msbuild/Xamarin.iOS.Tasks/Tasks/CompileAppManifest.cs
Labels: bug, backported

#15463 [release/6.0.3xx] [dotnet] Generate Microsoft.<platform>.Sdk.ImplicitNamespaceImports.props.
  dotnet/.gitignore
  dotnet/Makefile
  dotnet/targets/Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.Sdk.ImplicitNamespaceImports.template.props
  dotnet/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
Labels: not-notes-worthy, backported

#15464 [release/6.0.4xx] [dotnet] Generate Microsoft.<platform>.Sdk.ImplicitNamespaceImports.props.
  dotnet/.gitignore
  dotnet/Makefile
  dotnet/targets/Microsoft.MacCatalyst.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.Sdk.ImplicitNamespaceImports.template.props
  dotnet/targets/Microsoft.iOS.Sdk.ImplicitNamespaceImports.props
  dotnet/targets/Microsoft.macOS.Sdk.ImplicitNamespaceImports.props
Labels: not-notes-worthy, backported

#15491 [release/6.0.4xx] [dotnet] Accept invalid runtime identifiers for Restore.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/DotNet.cs
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, backported

#15490 [release/6.0.3xx] [dotnet] Accept invalid runtime identifiers for Restore.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/DotNet.cs
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: not-notes-worthy, backported

#15458 [release/6.0.4xx] [CoreCLR] Avoid having any internal calls in managed code for CoreCLR. Fixes #15343.
  src/Foundation/NSObject2.cs
Labels: bug, backported

#15419 [CoreBluetooth] Add support for Xcode 14 beta 1 & 2.
  src/CoreBluetooth/Enums.cs
  src/corebluetooth.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreBluetooth.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreBluetooth.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreBluetooth.todo
  tests/xtro-sharpie/iOS-CoreBluetooth.todo
  tests/xtro-sharpie/macOS-CoreBluetooth.todo
  tests/xtro-sharpie/tvOS-CoreBluetooth.todo
  tests/xtro-sharpie/watchOS-CoreBluetooth.todo
Labels: notes-mention

#15498 [dotnet] Add support for 'make dotnet-install-system'.
  Makefile
  dotnet/Makefile
  mk/quiet.mk
Labels: not-notes-worthy

#15502 [xcode14] Merge main into xcode14.
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  mk/xamarin.mk
  runtime/monotouch-debug.m
  runtime/runtime.m
  src/ObjCRuntime/Class.cs
  src/ObjCRuntime/Dlfcn.cs
  src/ObjCRuntime/Runtime.cs
  tests/api-shared/ObjCRuntime/Registrar.cs
  tests/monotouch-test/ObjCRuntime/ToggleRefRetainDeadlockTest.cs
  tests/xharness/Jenkins/Jenkins.cs
  tools/devops/automation/post-build-pipeline.yml
  tools/devops/automation/scripts/bash/build-mlaunch-nuget.sh
  tools/devops/automation/scripts/bash/clean-bot.sh
  tools/devops/automation/templates/build/build-nugets.yml
  tools/mlaunch/.gitignore
  tools/mlaunch/Makefile
  tools/mlaunch/download-mlaunch.csproj
  tools/mlaunch/nupkg/Microsoft.DotNet.Mlaunch.csproj
  tools/mlaunch/nupkg/README.md
  tools/mlaunch/nupkg/build/Microsoft.DotNet.Mlaunch.props
  tools/mlaunch/nupkg/build/Microsoft.DotNet.Mlaunch.targets
Labels: not-notes-worthy

#15340 [dotnet][macos] The only runtime is CoreCLR (not a feature)
  src/ILLink.Substitutions.macOS.xml
Labels: community

#15499 [dotnet] Use the correct manifest version band.
  dotnet/Makefile
Labels: not-notes-worthy

#15501 [tests] Only include enabled platforms in the FrameworksInRuntimeNativeDirectory nupkg.
  tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj
  tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/Makefile
Labels: not-notes-worthy

#15451 [debugger] Work around a debugger issue when using the interpreter
  runtime/monovm-bridge.m
Labels: bug

#15505 [CI] Add support to choose the xcodeChannel to be used.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/tests/stage.yml
Labels: not-notes-worthy

#15417 [ClockKit] Add support for Xcode 14 beta 1 & 2.
  src/ClockKit/CLKEnums.cs
  src/clockkit.cs
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/iOS/iOSApiCtorInitTest.cs
  tests/xtro-sharpie/watchOS-ClockKit.ignore
  tests/xtro-sharpie/watchOS-ClockKit.todo
Labels: notes-mention

#15418 [CoreAudioKit] Add support for Xcode 14 beta 1 & 2
  src/coreaudiokit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreAudioKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreAudioKit.todo
  tests/xtro-sharpie/iOS-CoreAudioKit.todo
  tests/xtro-sharpie/macOS-CoreAudioKit.todo
Labels: notes-mention

#15497 [src] Adjust AssemblyVersion for .NET with Xcode 13.3.
  src/AssemblyInfo.cs.in
  src/Makefile
Labels: not-notes-worthy

#15527 [CoreML] Add support for xcode 14 beta 1, 2 & 3
  src/coreml.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreML.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreML.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreML.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreML.todo
  tests/xtro-sharpie/iOS-CoreML.todo
  tests/xtro-sharpie/macOS-CoreML.todo
  tests/xtro-sharpie/tvOS-CoreML.todo
  tests/xtro-sharpie/watchOS-CoreML.todo
Labels: notes-mention

#15524 [CoreMedia] Add support for xcode 14 beta 1,2 & 3
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreMedia.todo
  tests/xtro-sharpie/api-annotations-dotnet/common-CoreMedia.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreMedia.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreMedia.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreMedia.todo
  tests/xtro-sharpie/common-CoreMedia.ignore
  tests/xtro-sharpie/iOS-CoreMedia.todo
  tests/xtro-sharpie/macOS-CoreMedia.todo
  tests/xtro-sharpie/tvOS-CoreMedia.todo
  tests/xtro-sharpie/watchOS-CoreMedia.todo
Labels: notes-mention

#15531 [CoreMedia] Fix xtro for xcode 14.
  src/CoreMedia/CMSync.cs
Labels: not-notes-worthy

#15471 [devops] Try parallelize less during the API diff build.
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/build/build.yml
Labels: skip-all-tests, not-notes-worthy

#15509 [release/6.0.3xx] [debugger] Work around a debugger issue when using the interpreter.
  runtime/monovm-bridge.m
Labels: bug

#15507 Bump mono to get debugging fix when using the interpreter.
  mk/mono.mk
Labels: bug

#15533 [CoreTelephony] Add support for Xcode 14 beta 1,2 & 3
  src/coretelephony.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreTelephony.todo
  tests/xtro-sharpie/iOS-CoreTelephony.todo
Labels: notes-mention

#15532 [CoreSpotlight] Add support for Xcode 14 beta 1,2 & 3
  src/corespotlight.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreSpotlight.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreSpotlight.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreSpotlight.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreSpotlight.todo
  tests/xtro-sharpie/iOS-CoreSpotlight.todo
  tests/xtro-sharpie/macOS-CoreSpotlight.todo
  tests/xtro-sharpie/tvOS-CoreSpotlight.ignore
  tests/xtro-sharpie/tvOS-CoreSpotlight.todo
Labels: notes-mention

#15534 [CoreText] Add support for Xcode 14 beta 1,2 & 3
  src/CoreText/CTFont.cs
  src/CoreText/CTParagraphStyle.cs
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreText.ignore
  tests/xtro-sharpie/api-annotations-dotnet/watchOS-CoreText.ignore
  tests/xtro-sharpie/tvOS-CoreText.ignore
  tests/xtro-sharpie/watchOS-CoreText.ignore
Labels: notes-mention

#15538 [Vision] Add support for Xcode 14 beta 1,2 & 3
  src/vision.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Vision.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Vision.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-Vision.todo
  tests/xtro-sharpie/iOS-Vision.todo
  tests/xtro-sharpie/macOS-Vision.todo
  tests/xtro-sharpie/tvOS-Vision.todo
Labels: notes-mention

#15536 [xcode14] [devops] Try parallelize less during the API diff build.
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/build/build.yml
Labels: skip-all-tests, not-notes-worthy, backported

#15554 [Xtro] Clean file that was missed due to xtro bug.
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreText.ignore
Labels: not-notes-worthy

#15381 [UIKit] Fix typo in UIGraphics EndPDFContent => EndPDFContext
  src/UIKit/UIGraphics.cs
Labels: notes-mention

#15550 [UniformTypeIdentifiers] Add support for Xcode 14 beta 1, 2 & 3
  src/foundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UniformTypeIdentifiers.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-UniformTypeIdentifiers.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UniformTypeIdentifiers.todo
  tests/xtro-sharpie/iOS-UniformTypeIdentifiers.todo
  tests/xtro-sharpie/macOS-UniformTypeIdentifiers.todo
  tests/xtro-sharpie/tvOS-UniformTypeIdentifiers.todo
  tests/xtro-sharpie/watchOS-UniformTypeIdentifiers.todo
Labels: notes-mention

#15551 [Xtro] Ensure that when we do auto sanitize we do not return a fail.
  tests/xtro-sharpie/xtro-sanity/Sanitizer.cs
Labels: not-notes-worthy

#15555 [ThreadNetwork] Add support for Xcode 14 beta 1, 2 & 3
  src/threadnetwork.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-ThreadNetwork.todo
  tests/xtro-sharpie/iOS-ThreadNetwork.todo
Labels: notes-mention

#15549 [nnyeah] fix incorrect attribute
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/unit/DependencyRemovedTests.cs
Labels: skip-all-tests, not-notes-worthy

#15547 [xcode14] [CI] Remove older pkgs in the system to make sure we are not running the tests with an older version.
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#15560 [release/6.0.4xx] Ensure the Hot Restart bundle does not have any entitlements set
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs
Labels: not-notes-worthy, backported

#15559 [release/6.0.3xx] Ensure the Hot Restart bundle does not have any entitlements set
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs
Labels: not-notes-worthy, backported

#15558 Ensure the Hot Restart bundle does not have any entitlements set
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs
Labels: not-notes-worthy

#15561 [nnyeah] Fix for branch targets and AVMediaTypes
  tools/nnyeah/nnyeah/InstructionExtensions.cs
  tools/nnyeah/nnyeah/MethodTransformations.cs
  tools/nnyeah/nnyeah/Transformation.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15567 [d17-3] [mlaunch] Fix permisisons after extracting from nuget
  tools/mlaunch/Makefile
Labels: not-notes-worthy, backported

#15566 [mlaunch] Fix permisisons after extracting from nuget
  tools/mlaunch/Makefile
Labels: not-notes-worthy

#15569 [d17-3] Set custom home env var from XMA Build Agent
  msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
Labels: not-notes-worthy

#15571 Set custom home env var from XMA Build Agent
  msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
Labels: not-notes-worthy

#15570 [appkit] Add missing NullAllowed on NSSavePanel.AllowedFileTypes
  src/appkit.cs
Labels: notes-mention

#15572 [tests] Fix MonoNativeFunctionWrapper/MonoPInvokeCallback to report specific errors
  tests/introspection/iOS/iOSApiPInvokeTest.cs
Labels: not-notes-worthy

#15563 [UniformTypeIdentifiers] Fix for support for Xcode 14 beta 1, 2 & 3
  src/foundation.cs
Labels: notes-mention

#15546 [CloudKit] Update bindings for Xcode 14 beta 1and2
  src/CloudKit/Enums.cs
  src/cloudkit.cs
  src/foundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CloudKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CloudKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CloudKit.todo
  tests/xtro-sharpie/iOS-CloudKit.todo
  tests/xtro-sharpie/macOS-CloudKit.todo
  tests/xtro-sharpie/tvOS-CloudKit.todo
Labels: notes-mention

#15557 [GameKit] Update bindings for Xcode 14.0 beta 1&2
  src/gamekit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-GameKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-GameKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreText.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-GameKit.todo
  tests/xtro-sharpie/iOS-GameKit.ignore
Labels: notes-mention

#15540 [Fix] Reorder the enum to the correct order
  src/usernotifications.cs
  tests/monotouch-test/UserNotifications/NotificationInterruptionLevel.cs
Labels: bug

#15553 [TVServices] Add support for Xcode 14 beta 1, 2 & 3
  src/tvservices.cs
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-TVServices.todo
  tests/xtro-sharpie/tvOS-TVServices.todo
Labels: notes-mention

#15520 [msbuild] Ignore CS0169 in a few places.
  msbuild/Xamarin.iOS.Tasks/Model/DataItem.cs
  msbuild/Xamarin.iOS.Tasks/Model/DataSet.cs
Labels: not-notes-worthy

#15518 [tests] Don't include ErrorHelper.cs nor error.cs in Xamarin.MacDev.Tasks.Tests.
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/Xamarin.MacDev.Tasks.Tests.csproj
Labels: not-notes-worthy

#15576 [Xcode14] Bring main to xcode14.
  Makefile
  NuGet.config
  dotnet/Makefile
  eng/Version.Details.xml
  mk/mono.mk
  mk/quiet.mk
  msbuild/Directory.Build.props
  msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
  msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/CompileAppManifest.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/PrepareNativeReferences.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindAotCompilerTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifest.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/PrepareNativeReferences.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs
  runtime/monovm-bridge.m
  src/AssemblyInfo.cs.in
  src/ILLink.Substitutions.macOS.xml
  src/Makefile
  src/Security/Items.cs
  src/UIKit/UIGraphics.cs
  src/appkit.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_Core.cs
  tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/FrameworksInRuntimesNativeDirectory.csproj
  tests/test-libraries/nugets/FrameworksInRuntimesNativeDirectory/Makefile
  tools/common/StaticRegistrar.cs
  tools/mlaunch/Makefile
  tools/nnyeah/nnyeah/AssemblyConverter.cs
  tools/nnyeah/nnyeah/InstructionExtensions.cs
  tools/nnyeah/nnyeah/MethodReferenceExtensions.cs
  tools/nnyeah/nnyeah/MethodTransformations.cs
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/nnyeah/Transformation.cs
  tools/nnyeah/tests/unit/ConstructorTransformTests.cs
  tools/nnyeah/tests/unit/DependencyRemovedTests.cs
Labels: not-notes-worthy

#15578 [Xcode14] Add missing availability on dotnet. fixes #2607
  src/CoreText/CTFont.cs
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreText.ignore
Labels: not-notes-worthy

#15590 [release/7.0.1xx-preview7] Ensure the Hot Restart bundle does not have any entitlements set
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/PrepareAppBundle.cs
Labels: not-notes-worthy, backported
