Repository dotnet/macios, pull requests merged in 2022-04, with the labels that each got.

#14599 [tests] Ignore the BindingLibraryDSymCreated test until we've fixed the underlying issue.
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy

#14587 [cecil-tests] Enable previously disabled tests.
  tests/cecil-tests/ConstructorTest.cs
  tests/cecil-tests/ObsoleteTest.cs
  tests/cecil-tests/OpenTKTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14524 [dotnet] Rename hardcoded 'net6.0' to use a 'DOTNET_TFM' variable instead.
  tests/Makefile
  tests/common/Configuration.cs
  tests/common/shared-dotnet.mk
  tests/dotnet/Makefile
  tests/dotnet/UnitTests/ApplePlatformExtensions.cs
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/dotnet/UnitTests/TestBaseClass.cs
  tests/monotouch-test/dotnet/macOS/Makefile
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/MergeAppBundleTaskTest.cs
  tests/msbuild/Xamarin.MacDev.Tests/TargetTests/CollectAppManifestsTests.cs
  tests/msbuild/Xamarin.MacDev.Tests/TargetTests/DetectSigningIdentityTests.cs
  tests/msbuild/Xamarin.MacDev.Tests/TestHelpers/TestBase.cs
  tests/packaged-macos-tests.mk
  tests/perftest/Makefile
  tests/xharness/Targets/MacTarget.cs
  tests/xharness/Targets/TVOSTarget.cs
  tests/xharness/Targets/Target.cs
  tests/xharness/Targets/UnifiedTarget.cs
  tests/xharness/Targets/WatchOSTarget.cs
Labels: run-all-tests, skip-simulator-tests, not-notes-worthy

#14374 [EventKitUI] Add this framework to Mac Catalyst.
  src/frameworks.sources
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-EventKitUI.todo
  tests/xtro-sharpie/api-annotations-dotnet/common-EventKitUI.ignore
  tools/common/Frameworks.cs
Labels: not-notes-worthy, run-dotnet-tests

#14597 [Foundation] Enable nullability in NSUrlSessionHandler.
  src/Foundation/NSUrlSessionHandler.cs
  src/foundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
  tests/xtro-sharpie/common-Foundation.ignore
Labels: not-notes-worthy, run-dotnet-tests

#14536 Remove unnecessary conditional defines from networkextension.cs
  src/networkextension.cs
Labels: not-notes-worthy

#14512 Remove unnecessary conditional defines from metrickit.cs
  src/metrickit.cs
Labels: not-notes-worthy

#14469 Remove unnecessary conditional defines from corespotlight.cs
  src/corespotlight.cs
Labels: not-notes-worthy

#14467 Remove unnecessary conditional defines from corelocation.cs
  src/corelocation.cs
Labels: not-notes-worthy

#14446 Remove unnecessary conditional defines from avfoundation.cs
  src/avfoundation.cs
Labels: not-notes-worthy

#14449 Remove unnecessary conditional defines from appkit.cs
  src/appkit.cs
Labels: not-notes-worthy

#14581 [dotnet] Update macos template to visible at launch
  dotnet/Templates/Microsoft.macOS.Templates/macos/Main.storyboard
Labels: not-notes-worthy

#14582 [scenekit] Remove [Protocolize] from SCNSceneRendererDelegate param
  src/scenekit.cs
Labels: notes-mention

#14602 [fileprovider] Add nullability to (generated and manual) bindings
  src/FileProvider/Structs.cs
Labels: not-notes-worthy

#14448 Remove unnecessary conditional defines from accounts.cs
  src/accounts.cs
Labels: not-notes-worthy

#14482 Remove unnecessary conditional defines from spritekit.cs
  src/spritekit.cs
Labels: not-notes-worthy

#14466 Remove unnecessary conditional defines from coregraphics.cs
  src/coregraphics.cs
Labels: not-notes-worthy

#14603 [Foundation] Allow null parameters when creating a NSUrl from a string.
  src/foundation.cs
  tests/monotouch-test/Foundation/UrlTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
  tests/xtro-sharpie/common-Foundation.ignore
Labels: enhancement

#14614 [system-dependencies.sh] Fix check that would always insist on instal…
  system-dependencies.sh
Labels: not-notes-worthy

#14613 [mapkit] Fix API removal made in https://github.com/xamarin/xamarin-m…
  src/mapkit.cs
Labels: not-notes-worthy

#14620 [Foundation] Fix a small nullability change in the NSUrlSessionHandler.
  src/Foundation/NSUrlSessionHandler.cs
Labels: not-notes-worthy

#14606 [tests] Fix dependencies to build the mtouch tests.
  tests/mtouch/Makefile
Labels: run-mtouch-tests, skip-all-tests, not-notes-worthy

#14605 [tests] Adjust the Xamarin.Tests.Misc.PublicSymbols test to accept Brotli-related symbols.
  tests/mtouch/MiscTests.cs
Labels: run-mtouch-tests, skip-all-tests, not-notes-worthy

#14592 [dotnet] Port the iOS tabbed app template to .NET.
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.cs.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.de.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.es.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.fr.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.it.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.ja.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.ko.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.pl.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.pt-BR.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.ru.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.tr.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.zh-Hans.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.zh-Hant.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/template.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/AppDelegate.cs
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Contents.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon1024.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon120.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon152.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon167.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon180.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon20.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon29.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon40.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon58.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon60.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon76.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon80.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/AppIcon.appiconset/Icon87.png
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/First.imageset/Contents.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/First.imageset/First.pdf
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/Second.imageset/Contents.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Assets.xcassets/Second.imageset/Second.pdf
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Entitlements.plist
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/FirstViewController.cs
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/FirstViewController.designer.cs
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Info.plist
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Main.cs
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Main.storyboard
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/Resources/LaunchScreen.xib
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/SceneDelegate.cs
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/SecondViewController.cs
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/SecondViewController.designer.cs
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/iOSTabbedApp1.csproj
  tests/dotnet/UnitTests/TemplateTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14484 [Foundation] Implement the properties inherited from HttpClientHandler in NSUrlSessionHandler. Fixes #13579.
  src/Foundation/NSUrlSessionHandler.cs
Labels: not-notes-worthy, run-dotnet-tests

#14588 [CI] Start using manifest to simplify the pwsh import.
  tools/devops/automation/scripts/CreateManifest.ps1
  tools/devops/automation/scripts/MaciosCI.psd1
  tools/devops/automation/scripts/README.md
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/upload-azure.yml
  tools/devops/automation/templates/common/configure.yml
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
  tools/devops/automation/templates/tests/run-tests.yml
Labels: not-notes-worthy

#14363 [coreimage] Add nullability to (generated and manual) bindings
  src/CoreImage/CIContext.cs
  src/CoreImage/CIDetector.cs
  src/CoreImage/CIDetectorOptions.cs
  src/CoreImage/CIFilter.cs
  src/CoreImage/CIImage.cs
  src/CoreImage/CIImageInitializationOptions.cs
  src/CoreImage/CIKernel.cs
  src/CoreImage/CISampler.cs
  src/CoreImage/CIVector.cs
Labels: not-notes-worthy

#14617 [iosurface] Add nullability to (generated and manual) bindings
  src/IOSurface/IODefs.cs
  src/IOSurface/IOSurface.cs
  src/IOSurface/IOSurfacePropertyKey.cs
Labels: not-notes-worthy

#14626 [devops] Rework and fix issue with making local symlinks point to global installs.
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy

#14465 Remove unnecessary conditional defines from coreimage.cs
  src/coreimage.cs
Labels: not-notes-worthy

#14557 [metalperformanceshaders] Add one troublesome missing method
  src/metalperformanceshaders.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-MetalPerformanceShaders.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/iOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/macOS-MetalPerformanceShaders.todo
  tests/xtro-sharpie/tvOS-MetalPerformanceShaders.todo
Labels: notes-mention

#14593 [tests] Execute tests on older macOS bots with a timeout.
  tests/dotnet/Makefile
  tests/package-mac-tests.sh
  tests/packaged-macos-tests.mk
  tests/run-with-timeout.sh
  tools/devops/automation/templates/mac/build.yml
Labels: skip-all-tests, not-notes-worthy

#14627 [mtouch] Ignore linker warning due to a bug in the AOT compiler we already know about.
  tools/mtouch/Application.mtouch.cs
Labels: not-notes-worthy

#14628 [tests] Request labels after each test from NUnit.
  tests/generator/Makefile
  tests/mmptest/Makefile
  tests/mtouch/Makefile
  tests/sampletester/Makefile
  tests/xharness/Jenkins/TestTasks/NUnitExecuteTask.cs
Labels: not-notes-worthy

#14630 [nnyeah] Array copy
  tools/nnyeah/nnyeah/MethodTransformations.cs
Labels: enhancement, not-notes-worthy

#14623 Use the tip of the 6.0.3xx-rc1 branch as the baseline for .NET API diffs.
  Make.config
Labels: not-notes-worthy

#14610 [msbuild] Make codesigned output files relative, and don't list directories.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
Labels: do-not-merge, not-notes-worthy, run-dotnet-tests

#14641 Fix multiple API mistakes made in define removal
  src/foundation.cs
  src/mapkit.cs
  src/quicklook.cs
  src/quicklookUI.cs
Labels: not-notes-worthy

#14645 Updated Xamarin.Messaging version to 1.5.27
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#14611 [gamekit] Add nullability to (generated and manual) bindings
  src/GameKit/GKScore.cs
  src/GameKit/GameKit2.cs
Labels: not-notes-worthy

#14637 [imagekit] Add nullability to (generated and manual) bindings
  src/ImageKit/Enums.cs
Labels: not-notes-worthy

#14638 [inputmethodkit] Add nullability to (generated and manual) bindings
  src/InputMethodKit/Enums.cs
Labels: not-notes-worthy

#14639 [mlcompute] Add nullability to (generated and manual) bindings
  src/MLCompute/MLHelpers.cs
Labels: not-notes-worthy

#14655 [builds] Don't use DOTNET6_VERSION anymore, it's DOTNET_VERSION.
  builds/Makefile
Labels: skip-all-tests, not-notes-worthy

#14642 [CI] Improve API diff.
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
Labels: skip-all-tests, not-notes-worthy

#14644 [ScreenCaptureKit] Add ScreenCaptureKit bindings up to Xcode 13.3
  src/ScreenCaptureKit/SCContentFilter.cs
  src/coregraphics.cs
  src/frameworks.sources
  src/screencapturekit.cs
  tests/introspection/ApiSelectorTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreGraphics.ignore
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-ScreenCaptureKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreGraphics.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-ReplayKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-ScreenCaptureKit.todo
  tests/xtro-sharpie/macOS-CoreGraphics.ignore
  tests/xtro-sharpie/macOS-ReplayKit.ignore
  tests/xtro-sharpie/macOS-ScreenCaptureKit.todo
  tools/common/Frameworks.cs
Labels: notes-mention

#14662 [msbuild] Don't create output files for ditto'ed directories on Windows.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DittoTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/Ditto.cs
Labels: not-notes-worthy, run-dotnet-tests

#14661 [msbuild] Move logic to validate the UIDeviceFamily to shared code in the CompileAppManifest task.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
Labels: not-notes-worthy

#14652 [tests] A few test fixes to make testing system installs better.
  Make.config
  tests/test-libraries/custom-type-assembly/Makefile
  tests/test-libraries/custom-type-assembly/custom-type-assembly.csproj
  tests/xammac_tests/xammac_tests.csproj
Labels: not-notes-worthy, run-dotnet-tests

#14629 [msbuild] Improve product name in .NET.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinToolTask.cs
Labels: not-notes-worthy

#14643 [dotnet] Adds platform specific RID options
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: not-notes-worthy

#14657 [CI] Move API diff to its own stage to make things much simpler.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-stage.yml
Labels: skip-all-tests, not-notes-worthy

#14653 Add nullability on one UndoManager API
  src/uikit.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
Labels: notes-mention

#14665 [dotnet] Don't list OS versions we don't support.
  dotnet/generate-target-platforms.csharp
Labels: not-notes-worthy, run-dotnet-tests

#14668 [tests] Stop hardcoding system assembly version number in linker tests.
  tests/linker/CommonLinkAllTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14640 [mapkit] Add nullability to (generated and manual) bindings
  src/MapKit/MKGeodesicPolyline.cs
  src/MapKit/MKLocalSearch.cs
  src/MapKit/MKMapItem.cs
  src/MapKit/MKPolygon.cs
  src/MapKit/MKPolyline.cs
Labels: not-notes-worthy

#14656 [mediaaccessibility] Add nullability to (generated and manual) bindings
  src/MediaAccessibility/MAImageCaptioning.cs
  src/MediaAccessibility/MediaAccessibility.cs
Labels: not-notes-worthy

#14664 [mediatoolbox] Add nullability to (generated and manual) bindings
  src/MediaToolbox/MTAudioProcessingTap.cs
  src/MediaToolbox/MTFormatNames.cs
  src/MediaToolbox/MTProfessionalVideoWorkflow.cs
Labels: not-notes-worthy

#14658 [javascriptcore] Add nullability to (generated and manual) bindings
  src/JavaScriptCore/Extensions.cs
Labels: not-notes-worthy

#14633 [imageio] Add nullability to (generated and manual) bindings
  src/ImageIO/CGImageAnimation.cs
  src/ImageIO/CGImageDestination.cs
  src/ImageIO/CGImageMetadata.cs
  src/ImageIO/CGImageMetadataTag.cs
  src/ImageIO/CGImageSource.cs
  src/ImageIO/CGMutableImageMetadata.cs
Labels: not-notes-worthy

#14358 [CI] Split the logic that writes artifacts and test it.
  .github/workflows/pwsh-ci.yml
  tools/devops/automation/scripts/APIDiff.Tests.ps1
  tools/devops/automation/scripts/Artifacts.Tests.ps1
  tools/devops/automation/scripts/Artifacts.psm1
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/scripts/MaciosCI.psd1
  tools/devops/automation/scripts/StaticPages.Tests.ps1
  tools/devops/automation/scripts/test_data/artifacts.json
Labels: not-notes-worthy

#14683 [xcode13.3] Updated Hot Restart client version
  msbuild/Directory.Build.props
Labels: not-notes-worthy, backported

#14669 [tools] Make the TargetFramework.DotNet* variables version-agnostic.
  src/Makefile
  src/btouch.cs
  tests/cecil-tests/AttributeTest.cs
  tests/generator/BGenTool.cs
  tests/generator/GeneratorTests.cs
  tools/common/TargetFramework.cs
  tools/mmp/Makefile
  tools/mtouch/Makefile
Labels: not-notes-worthy, run-dotnet-tests

#14670 [msbuild] Enable nullability for the CompileAppManifest task.
  msbuild/Xamarin.Mac.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  msbuild/Xamarin.Mac.Tasks.Core/Xamarin.Mac.Tasks.Core.csproj
  msbuild/Xamarin.Mac.Tasks/Tasks/CompileAppManifest.cs
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Tasks.csproj
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DittoTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Xamarin.MacDev.Tasks.Core.csproj
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/CompileAppManifestTaskCore.cs
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Tasks.Core.csproj
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/CompileAppManifest.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
  msbuild/Xamarin.iOS.Tasks/Tasks/CompileAppManifest.cs
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Tasks.csproj
Labels: not-notes-worthy

#14679 [dotnet] Use only the first three parts of our product version as the assembly version.
  src/AssemblyInfo.cs.in
Labels: not-notes-worthy, run-dotnet-tests

#14403 [msbuild] Ask ditto to thin native libraries according to the architectures we're targetting. Fixes #13081.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/Makefile
  tests/common/Configuration.cs
  tests/dotnet/UnitTests/BundleStructureTest.cs
  tests/package-mac-tests.sh
Labels: not-notes-worthy, run-dotnet-tests

#14689 [msbuild] Fix the build due to nullability changes from multiple PRs conspiring.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CompileAppManifestTaskBase.cs
Labels: skip-all-tests, not-notes-worthy

#14675 [nnyeah] Nfloat type substitution
  tools/nnyeah/nnyeah/Reworker.cs
Labels: enhancement, not-notes-worthy

#14688 [tests] Make MonoTests.System.Net.Http.MessageHandlerTest handle some 504's.
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy

#14687 [runtime] Fix typo in comment.
  runtime/trampolines.m
Labels: skip-all-tests, not-notes-worthy

#14654 [ESRP] Move signing to the new xcode version.
  tools/devops/automation/templates/build/sign-and-notarized.yml
Labels: not-notes-worthy

#14696 [nnyeah] Nfloat fields
  tools/nnyeah/nnyeah/FieldTransformations.cs
Labels: enhancement, not-notes-worthy

#14680 [multipeerconnectivity] Add nullability to (generated and manual) bindings
  src/MultipeerConnectivity/Compat.cs
  src/MultipeerConnectivity/MCSession.cs
Labels: not-notes-worthy

#14694 [nativetypes] Add nullability to (generated and manual) bindings
  src/NativeTypes/NMath.cs
  src/NativeTypes/test.cs
Labels: not-notes-worthy

#14695 [metalkit] Add nullability to (generated and manual) bindings
  src/MetalKit/MTKMesh.cs
  src/MetalKit/MTKMeshBufferAllocator.cs
  src/MetalKit/MTKTextureLoaderOptions.cs
Labels: not-notes-worthy

#14676 [messageui] Add nullability to (generated and manual) bindings
  src/MessageUI/MessageUI2.cs
Labels: not-notes-worthy

#14677 [mobilecoreservices] Add nullability to (generated and manual) bindings
  src/MobileCoreServices/UTType.cs
Labels: not-notes-worthy

#14678 [metrickit] Add nullability to (generated and manual) bindings
  src/MetricKit/MXMetaData.cs
  src/MetricKit/MXMetric.cs
  src/MetricKit/MXMetricManager.cs
  src/MetricKit/MXMetricPayload.cs
Labels: not-notes-worthy

#14706 [CI] Fix the import path to be relative.
  tools/devops/automation/templates/tests/run-tests.yml
Labels: not-notes-worthy

#14710 [nnyeah] Namespace change
  tools/nnyeah/nnyeah/BaseTransformEventArgs.cs
  tools/nnyeah/nnyeah/Enums.cs
  tools/nnyeah/nnyeah/FieldTransformations.cs
  tools/nnyeah/nnyeah/MethodTransformations.cs
  tools/nnyeah/nnyeah/Program.cs
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/nnyeah/TransformEventArgs.cs
  tools/nnyeah/nnyeah/Transformation.cs
  tools/nnyeah/nnyeah/WarningEventArgs.cs
  tools/nnyeah/nnyeah/nnyeah.csproj
Labels: enhancement, not-notes-worthy

#14707 Updated Xamarin.Messaging to 1.6.1
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#14705 [CI] Re-enable the api diff comments.
  tools/devops/automation/scripts/APIDiff.psm1
  tools/devops/automation/templates/build/api-diff-github-comment.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
Labels: skip-all-tests, not-notes-worthy

#14712 [CI] Add a prefix to the comment headers.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#14714 [CI] Fix variables to show the correct bot in the comments.
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#14713 [CI] Add the hash that was used to build in the commit.
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/api-diff-github-comment.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/artifact-github-comment.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/build/build.yml
Labels: not-notes-worthy

#14723 [CI] Improve the action used to run tests on the pwsh.
  .github/workflows/pwsh-ci.yml
  tools/devops/automation/scripts/APIDiff.Tests.ps1
  tools/devops/automation/scripts/Artifacts.Tests.ps1
  tools/devops/automation/scripts/GitHub.Tests.ps1
  tools/devops/automation/scripts/MLaunch.Tests.ps1
  tools/devops/automation/scripts/StaticPages.Tests.ps1
  tools/devops/automation/scripts/System.Tests.ps1
  tools/devops/automation/scripts/VSTS.Tests.ps1
Labels: not-notes-worthy

#14697 [tests] Improve NWProtocolStackTest to not crash the process if the state change handler throws an exception.
  tests/monotouch-test/Network/NWProtocolStackTest.cs
Labels: not-notes-worthy

#14719 Update Messaging to 1.6.2 (revert changes)
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#14726 Revert Messaging to 1.5.25: Threading issues
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#14703 [Localization] Add the resx file for localization and move errors and warnings
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/MethodTransformations.cs
  tools/nnyeah/nnyeah/Program.cs
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/nnyeah/TransformEventArgs.cs
  tools/nnyeah/nnyeah/WarningEventArgs.cs
  tools/nnyeah/nnyeah/nnyeah.csproj
Labels: not-notes-worthy

#14727 [CI] Fix typo that made comments fail on CI but not PRs.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#14717 [CI] Provide the bot name on mac test result comments.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#14731 [CI] Fix issue when adding the api diff on CI.
  tools/devops/automation/scripts/GitHub.psm1
Labels: bug, not-notes-worthy

#14729 [Foundation] Ensure that post requests are not cached by the native code.
  src/Foundation/NSUrlSessionHandler.cs
Labels: bug, enhancement

#14728 [CI] Migrate all code to use the new api to set the status on github.
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/upload-azure.yml
  tools/devops/automation/templates/common/status.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
  tools/devops/automation/templates/tests/run-tests.yml
Labels: enhancement, not-notes-worthy

#14739 [d17-2] [Foundation] Ensure that post requests are not cached by the native code.
  src/Foundation/NSUrlSessionHandler.cs
Labels: bug, enhancement, backported

#14734 [CI] Set all comments as oudated after every build.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/common/clean.yml
Labels: enhancement, not-notes-worthy

#14736 [CI] Move mac tests to use the new comments API.
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/mac/stage.yml
Labels: enhancement, not-notes-worthy

#14743 Bump Microsoft.DotNet.XHarness.iOS.Shared to `1.0.0-prerelease.22211.4`
  tests/xharness/AppRunner.cs
  tests/xharness/Program.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy

#14745 [CI] Add a status for the PR API diff.
  tools/devops/automation/scripts/bash/compare.sh
  tools/devops/automation/templates/build/api-diff.yml
Labels: enhancement, not-notes-worthy

#14747 [CI] Add a status for the API diff from stable.
  tools/devops/automation/templates/build/api-diff.yml
Labels: enhancement, not-notes-worthy

#14746 [CI] Remove dependency on build in the governance tests.
  tools/devops/automation/build-pipeline.yml
Labels: enhancement, not-notes-worthy

#14748 [CI] Fix the links for the API diff in dotnet.
  tools/devops/automation/templates/build/api-diff-github-comment.yml
Labels: not-notes-worthy

#14744 [CI] Clean the statuses mess.
  tools/devops/automation/scripts/GitHub.Tests.ps1
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/scripts/MaciosCI.psd1
  tools/devops/automation/scripts/TestResults.psm1
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/tests/run-tests.yml
Labels: enhancement, not-notes-worthy

#14750 [CI] Fix the API diff statuses on CI
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/api-diff.yml
Labels: enhancement, not-notes-worthy

#14699 [devops] Add more validation to the compare.sh script.
  tools/devops/automation/scripts/bash/compare.sh
Labels: not-notes-worthy

#14765 [CI] Perform the same checkout operations in all the jobs.
  tools/devops/automation/templates/build/api-diff-github-comment.yml
  tools/devops/automation/templates/build/artifact-github-comment.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/upload-azure.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
  tools/devops/automation/templates/common/checkout.yml
  tools/devops/automation/templates/common/clean.yml
  tools/devops/automation/templates/common/configure.yml
  tools/devops/automation/templates/common/download-artifacts.yml
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/common/upload-vsdrops.yml
  tools/devops/automation/templates/common/upload-vsts-tests.yml
  tools/devops/automation/templates/governance-checks.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/publish-html-result.yml
  tools/devops/automation/templates/tests/build.yml
  tools/devops/automation/templates/windows/build.yml
Labels: enhancement, not-notes-worthy

#14767 [CI] Do not crash when we cannot remove an empty dir.
  tools/devops/automation/templates/publish-html-result.yml
Labels: enhancement, not-notes-worthy

#14768 [CI] Only upload the config files once.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/common/configure.yml
  tools/devops/automation/templates/mac/stage.yml
  tools/devops/automation/templates/tests/stage.yml
Labels: enhancement, not-notes-worthy

#14776 [CI] Fix the dir in the loc command.
  tools/devops/automation/templates/loc-translations.yml
Labels: enhancement, not-notes-worthy

#14777 [CI] Fix the push to the localization branch.
  tools/devops/automation/templates/loc-translations.yml
Labels: enhancement, not-notes-worthy

#14778 [CI] Do not use relative paths in the updated json.
  tools/devops/automation/scripts/update-locproject.ps1
Labels: enhancement, not-notes-worthy

#14771 Updated Xamarin.Messaging to 1.6.3
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#14769 [tests] Add some code to try to diagnose why certain test failures aren't ignored in CI.
  tests/common/TestRuntime.cs
Labels: not-notes-worthy

#14766 [Dotnet] Fix the template on iOS and Catalyst to use the system background color.
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/AppDelegate.cs
  dotnet/Templates/Microsoft.iOS.Templates/ios/.template.config/template.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/AppDelegate.cs
Labels: bug

#14764 [CI] Use template extension to simplify the separation between api diff and building the pkgs.
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-api-diff.yml
  tools/devops/automation/templates/build/build-pkgs.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/build/build.yml
Labels: enhancement, not-notes-worthy

#14690 [runtime] Don't call 'retain' and 'autorelease' selectors on returned NativeObjects.
  runtime/delegates.t4
  runtime/trampolines.m
  src/CoreFoundation/Dispatch.cs
  src/CoreFoundation/DispatchBlock.cs
  src/CoreFoundation/NativeObject.cs
  src/CoreFoundation/OSLog.cs
  src/CoreGraphics/CGColor.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGContext.cs
  src/CoreGraphics/CGDataConsumer.cs
  src/CoreGraphics/CGDataProvider.cs
  src/CoreGraphics/CGFont.cs
  src/CoreGraphics/CGFunction.cs
  src/CoreGraphics/CGGradient.cs
  src/CoreGraphics/CGImage.cs
  src/CoreGraphics/CGLayer.cs
  src/CoreGraphics/CGPDFContentStream.cs
  src/CoreGraphics/CGPDFDocument.cs
  src/CoreGraphics/CGPDFOperatorTable.cs
  src/CoreGraphics/CGPDFPage.cs
  src/CoreGraphics/CGPDFScanner.cs
  src/CoreGraphics/CGPath.cs
  src/CoreGraphics/CGPattern.cs
  src/CoreGraphics/CGShading.cs
  src/CoreServices/FSEvents.cs
  src/CoreVideo/CVBuffer.cs
  src/CoreVideo/CVDisplayLink.cs
  src/CoreVideo/CVPixelBufferPool.cs
  src/Network/NWContentContext.cs
  src/ObjCRuntime/BaseWrapper.cs
  src/ObjCRuntime/Runtime.cs
  src/OpenGL/CGLContext.cs
  src/OpenGL/CGLPixelFormat.cs
  src/PrintCore/PrintCore.cs
  src/SearchKit/SearchKit.cs
  tools/common/StaticRegistrar.cs
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#14783 [ObjCRuntime] Augment Runtime.GetNSObject to optionally create a new instance even if an existing instance was found.
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy, run-dotnet-tests

#14784 [ObjCRuntime] Fix GCHandle leak in our NSObject map.
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy, run-dotnet-tests

#14785 [CoreCLR] Rework how we track the lifetime of managed NSObjects.
  runtime/coreclr-bridge.m
  src/Foundation/NSObject2.cs
  src/ObjCRuntime/Runtime.CoreCLR.cs
  src/ObjCRuntime/Runtime.cs
Labels: not-notes-worthy, run-dotnet-tests

#14735 [nearbyinteraction] Add nullability to (generated and manual) bindings
  src/NearbyInteraction/NINearbyObject.cs
Labels: not-notes-worthy

#14738 [network] Add nullability to (generated and manual) bindings
  src/Network/NWAdvertiseDescriptor.cs
  src/Network/NWBrowseResult.cs
  src/Network/NWBrowser.cs
  src/Network/NWBrowserDescriptor.cs
  src/Network/NWConnection.cs
  src/Network/NWConnectionGroup.cs
  src/Network/NWContentContext.cs
  src/Network/NWDataTransferReport.cs
  src/Network/NWEndpoint.cs
  src/Network/NWEstablishmentReport.cs
  src/Network/NWEthernetChannel.cs
  src/Network/NWFramer.cs
  src/Network/NWFramerMessage.cs
  src/Network/NWListener.cs
  src/Network/NWMulticastGroup.cs
  src/Network/NWParameters.cs
  src/Network/NWPath.cs
  src/Network/NWPathMonitor.cs
  src/Network/NWProtocolDefinition.cs
  src/Network/NWProtocolStack.cs
  src/Network/NWResolverConfig.cs
  src/Network/NWTxtRecord.cs
  src/Network/NWWebSocketMetadata.cs
  src/Network/NWWebSocketOptions.cs
  src/Network/NWWebSocketRequest.cs
  src/Network/NWWebSocketResponse.cs
Labels: not-notes-worthy

#14788 [networkextension] Add nullability to (generated and manual) bindings
  src/NetworkExtension/NECompat.cs
  src/NetworkExtension/NEFilterFlow.cs
  src/NetworkExtension/NEFilterProvider.cs
  src/NetworkExtension/NEHotspotConfiguration.cs
  src/NetworkExtension/NEHotspotEapSettings.cs
  src/NetworkExtension/NEHotspotHelperOptions.cs
  src/NetworkExtension/NEPacketTunnelFlow.cs
  src/NetworkExtension/NEVpnConnectionStartOptions.cs
  src/NetworkExtension/NEVpnManager.cs
Labels: not-notes-worthy

#14798 [tests] Set the test name for the MySimpleApp test project.
  tests/dotnet/MySimpleApp/shared.mk
Labels: skip-all-tests, not-notes-worthy

#14801 Add fabricbot readme.
  .github/fabricbot_readme.md
Labels: skip-all-tests, not-notes-worthy

#14800 [msbuild] Just use the 'AppBundleDir' variable to find the app bundle in the CreateInstallerPackage task. Fixes #14751.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateInstallerPackageTaskBase.cs
Labels: not-notes-worthy, run-dotnet-tests

#14792 [runtime] Don't try process managed exceptions in xamarin_initialize.
  runtime/runtime.m
Labels: not-notes-worthy

#14772 Bump mono to get fix for #mono/mono@21450.
  mk/mono.mk
Labels: not-notes-worthy

#14799 [release/6.0.2xx-preview14] Backport fixes for #13531.
  runtime/coreclr-bridge.m
  runtime/delegates.t4
  runtime/trampolines.m
  src/CoreFoundation/Dispatch.cs
  src/CoreFoundation/DispatchBlock.cs
  src/CoreFoundation/NativeObject.cs
  src/CoreFoundation/OSLog.cs
  src/CoreGraphics/CGColor.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGContext.cs
  src/CoreGraphics/CGDataConsumer.cs
  src/CoreGraphics/CGDataProvider.cs
  src/CoreGraphics/CGFont.cs
  src/CoreGraphics/CGFunction.cs
  src/CoreGraphics/CGGradient.cs
  src/CoreGraphics/CGImage.cs
  src/CoreGraphics/CGLayer.cs
  src/CoreGraphics/CGPDFContentStream.cs
  src/CoreGraphics/CGPDFDocument.cs
  src/CoreGraphics/CGPDFOperatorTable.cs
  src/CoreGraphics/CGPDFPage.cs
  src/CoreGraphics/CGPDFScanner.cs
  src/CoreGraphics/CGPath.cs
  src/CoreGraphics/CGPattern.cs
  src/CoreGraphics/CGShading.cs
  src/CoreServices/FSEvents.cs
  src/CoreVideo/CVBuffer.cs
  src/CoreVideo/CVDisplayLink.cs
  src/CoreVideo/CVPixelBufferPool.cs
  src/Foundation/NSObject2.cs
  src/Network/NWContentContext.cs
  src/ObjCRuntime/BaseWrapper.cs
  src/ObjCRuntime/Runtime.CoreCLR.cs
  src/ObjCRuntime/Runtime.cs
  src/OpenGL/CGLContext.cs
  src/OpenGL/CGLPixelFormat.cs
  src/PrintCore/PrintCore.cs
  src/SearchKit/SearchKit.cs
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy, run-dotnet-tests, backported

#14704 [msbuild/dotnet] Fix building binding projects on Windows in .NET
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindCscCompilerTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/BTouch.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeRemoteGeneratorProperties.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Tasks/GetPropertyValueTaskBase.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.ObjCBinding.Common.After.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.ObjCBinding.Common.After.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.ObjCBinding.Common.Before.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/GetPropertyValue.cs
Labels: do-not-merge, not-notes-worthy, run-dotnet-tests

#14346 [avfoundation] Add nullability to (generated and manual) bindings - Fixed Branch
  src/AVFoundation/AVAssetDownloadStorageManagementPolicy.cs
  src/AVFoundation/AVAssetDownloadTask.cs
  src/AVFoundation/AVAssetDownloadUrlSession.cs
  src/AVFoundation/AVAssetImageGenerator.cs
  src/AVFoundation/AVAssetReaderVideoCompositionOutput.cs
  src/AVFoundation/AVAssetResourceLoadingDataRequest.cs
  src/AVFoundation/AVAudioBuffer.cs
  src/AVFoundation/AVAudioChannelLayout.cs
  src/AVFoundation/AVAudioConverterPrimeInfo.cs
  src/AVFoundation/AVAudioFormat.cs
  src/AVFoundation/AVAudioPlayer.cs
  src/AVFoundation/AVAudioRecorder.cs
  src/AVFoundation/AVAudioSession.cs
  src/AVFoundation/AVAudioSessionDataSourceDescription.cs
  src/AVFoundation/AVAudioSessionPortDescription.cs
  src/AVFoundation/AVAudioSettings.cs
  src/AVFoundation/AVBeatRange.cs
  src/AVFoundation/AVCaptureConnection.cs
  src/AVFoundation/AVCaptureDeviceDiscoverySession.cs
  src/AVFoundation/AVCaptureDeviceInput.cs
  src/AVFoundation/AVCaptureFileOutput.cs
  src/AVFoundation/AVCaptureMetadataOutput.cs
  src/AVFoundation/AVCaptureSynchronizedDataCollection.cs
  src/AVFoundation/AVCaptureSynchronizedDepthData.cs
  src/AVFoundation/AVCaptureVideoPreviewLayer.cs
  src/AVFoundation/AVCompat.cs
  src/AVFoundation/AVContentKeyResponse.cs
  src/AVFoundation/AVDepthData.cs
  src/AVFoundation/AVEdgeWidths.cs
  src/AVFoundation/AVFragmentedAsset.cs
  src/AVFoundation/AVFragmentedAssetTrack.cs
  src/AVFoundation/AVLayerVideoGravity.cs
  src/AVFoundation/AVMetadataItemFilter.cs
  src/AVFoundation/AVMetadataMachineReadableCodeObject.cs
  src/AVFoundation/AVMetadataObject.cs
  src/AVFoundation/AVOutputSettingsAssistant.cs
  src/AVFoundation/AVPixelAspectRatio.cs
  src/AVFoundation/AVPlayer.cs
  src/AVFoundation/AVPlayerItem.cs
  src/AVFoundation/AVPlayerItemVideoOutput.cs
  src/AVFoundation/AVPlayerLayer.cs
  src/AVFoundation/AVPlayerLooper.cs
  src/AVFoundation/AVSampleBufferExtensions.cs
  src/AVFoundation/AVTextStyleRule.cs
  src/AVFoundation/AVTypes.cs
  src/AVFoundation/AVUrlAssetOptions.cs
  src/AVFoundation/AVVideoSettings.cs
  src/AVFoundation/AudioRendererWasFlushedAutomaticallyEventArgs.cs
  src/AVFoundation/Events.cs
Labels: not-notes-worthy

#14612 [gamecontroller] Add nullability to (generated and manual) bindings
  src/GameController/GCController.cs
  src/GameController/GCExtendedGamepadSnapshot.cs
  src/GameController/GCGamepadSnapshot.cs
  src/GameController/GCMicroGamepadSnapshot.cs
  src/GameController/GCMotion.cs
Labels: not-notes-worthy

#14789 [pdfkit] Add nullability to (generated and manual) bindings
  src/PdfKit/PdfAnnotation.cs
  src/PdfKit/PdfKit.cs
Labels: not-notes-worthy

#14803 Workaround FirstChanceExceptionEventArgs being trimmed
  src/ILLink.Descriptors.xml
  src/Makefile
Labels: not-notes-worthy

#14808 [msbuild] Fix typo in warning message.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ComputeCodesignItemsTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ComputeCodesignItemsTaskTests.cs
Labels: not-notes-worthy

#14685 Build fixes (-dotnet) for app extensions
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/Makefile
  tests/dotnet/WidgetConsumer/AppDelegate.cs
  tests/dotnet/WidgetConsumer/Makefile
  tests/dotnet/WidgetConsumer/README.md
  tests/dotnet/WidgetConsumer/iOS/Makefile
  tests/dotnet/WidgetConsumer/iOS/WidgetConsumer.csproj
  tests/dotnet/WidgetConsumer/macOS/Makefile
  tests/dotnet/WidgetConsumer/macOS/WidgetConsumer.csproj
  tests/dotnet/WidgetConsumer/shared.csproj
  tests/dotnet/WidgetConsumer/shared.mk
  tests/dotnet/WidgetExtension/Info.plist
  tests/dotnet/WidgetExtension/Makefile
  tests/dotnet/WidgetExtension/README.md
  tests/dotnet/WidgetExtension/iOS/Entitlements.plist
  tests/dotnet/WidgetExtension/iOS/MainInterface.storyboard
  tests/dotnet/WidgetExtension/iOS/Makefile
  tests/dotnet/WidgetExtension/iOS/TodayViewController.cs
  tests/dotnet/WidgetExtension/iOS/TodayViewController.designer.cs
  tests/dotnet/WidgetExtension/iOS/WidgetExtension.csproj
  tests/dotnet/WidgetExtension/macOS/Entitlements.plist
  tests/dotnet/WidgetExtension/macOS/Makefile
  tests/dotnet/WidgetExtension/macOS/ShareViewController.cs
  tests/dotnet/WidgetExtension/macOS/ShareViewController.designer.cs
  tests/dotnet/WidgetExtension/macOS/ShareViewController.xib
  tests/dotnet/WidgetExtension/macOS/TodayViewController.cs
  tests/dotnet/WidgetExtension/macOS/TodayViewController.designer.cs
  tests/dotnet/WidgetExtension/macOS/WidgetExtension.csproj
  tests/dotnet/WidgetExtension/shared.csproj
  tests/dotnet/WidgetExtension/shared.mk
  tools/dotnet-linker/LinkerConfiguration.cs
  tools/dotnet-linker/Steps/GenerateMainStep.cs
Labels: community

#14807 [tests] Fix registrar tests to not return unretained INativeObjects to Objective-C. Fixes #xamarin/maccore@2572.
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14817 [devops] Set the BUILD_REVISION variable when running the tests.
  tools/devops/automation/templates/tests/run-tests.yml
Labels: not-notes-worthy

#14820 [static registrar] Fix lookup of block proxy attributes.
  src/ObjCRuntime/Registrar.cs
  tests/bindings-test/RegistrarBindingTest.cs
  tests/mtouch/RegistrarTest.cs
  tools/common/StaticRegistrar.cs
Labels: not-notes-worthy, run-dotnet-tests

#14811 [Localization] Update the Lcl paths
  tools/devops/LocProject.json.in
  tools/devops/automation/scripts/update-locproject.ps1
  tools/devops/automation/templates/loc-translations.yml
Labels: not-notes-worthy

#14749 [fabricbot] Update FabricBot with more useful commands
  .github/fabricbot.json
Labels: not-notes-worthy

#14822 Stop branding main as a release branch for .NET.
  Make.config
  Make.versions
Labels: not-notes-worthy, run-dotnet-tests

#14829 [FabricBot] Fix 'Write' & 'Admin' permission issue
  .github/fabricbot.json
Labels: not-notes-worthy

#14821 [CI] Do not use variable interpolation.
  tools/devops/automation/scripts/bash/compare.sh
  tools/devops/automation/scripts/bash/vsts-compare.sh
  tools/devops/automation/templates/build/api-diff.yml
Labels: enhancement, not-notes-worthy

#14702 [msbuild] Copy binding resource files back to Windows. Fixes #13393.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateBindingResourcePackageBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackage.cs
Labels: not-notes-worthy, run-dotnet-tests

#14828 [release/6.0.3xx-rc3] [msbuild] Copy binding resource files back to Windows. Fixes #13393.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateBindingResourcePackageBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CreateBindingResourcePackage.cs
Labels: not-notes-worthy

#14823 [Foundation] Use ObjCRuntime.ThrowHelper in NSUrlSessionHandler.
  src/Foundation/NSUrlSessionHandler.cs
  src/ObjCRuntime/ThrowHelper.cs
Labels: not-notes-worthy

#14831 [CI] Provide a stage that can be used to pair a Mac from a Windows machine
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/scripts/VSTS.psm1
  tools/devops/automation/templates/windows/build.yml
  tools/devops/automation/templates/windows/reserve-mac.yml
  tools/devops/automation/templates/windows/stage.yml
Labels: not-notes-worthy

#14615 [gameplaykit] Add nullability to (generated and manual) bindings
  src/GameplayKit/GKBehavior.cs
  src/GameplayKit/GKCompat.cs
  src/GameplayKit/GKComponentSystem.cs
  src/GameplayKit/GKCompositeBehavior.cs
  src/GameplayKit/GKEntity.cs
  src/GameplayKit/GKGameModel.cs
  src/GameplayKit/GKGridGraph.cs
  src/GameplayKit/GKObstacleGraph.cs
  src/GameplayKit/GKPath.cs
  src/GameplayKit/GKPolygonObstacle.cs
  src/GameplayKit/GKPrimitives.cs
  src/GameplayKit/GKState.cs
  src/GameplayKit/GKStateMachine.cs
  src/GameplayKit/NSArray_GameplayKit.cs
  tests/monotouch-test/GameplayKit/GKBehaviorTests.cs
Labels: not-notes-worthy

#14730 [healthkit] Add nullability to (generated and manual) bindings
  src/HealthKit/EnumsCompat.cs
  src/HealthKit/HKAnchoredObjectQuery.cs
  src/HealthKit/HKAppleWalkingSteadiness.cs
  src/HealthKit/HKObjectType.cs
  src/HealthKit/HKObsolete.cs
  src/HealthKit/HKSampleQuery.cs
  src/HealthKit/HKUnit.cs
  src/healthkit.cs
  tests/monotouch-test/HealthKit/HKHealthStoreTest.cs
  tests/monotouch-test/HealthKit/HKWorkoutBuilderTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-HealthKit.ignore
  tests/xtro-sharpie/common-HealthKit.ignore
  tests/xtro-sharpie/iOS-HealthKit.ignore
  tests/xtro-sharpie/watchOS-HealthKit.ignore
Labels: not-notes-worthy
