Repository dotnet/macios, pull requests merged in 2022-05, with the labels that each got.

#14836 [nnyeah] Assembly comparator
  tools/nnyeah/nnyeah/AssemblyComparator/ComparingVisitor.cs
  tools/nnyeah/nnyeah/AssemblyComparator/ItemFoundEventArgs.cs
  tools/nnyeah/nnyeah/AssemblyComparator/ModuleElements.cs
  tools/nnyeah/nnyeah/AssemblyComparator/ModuleVisitor.cs
  tools/nnyeah/nnyeah/AssemblyComparator/TypeAndMemberMap.cs
  tools/nnyeah/nnyeah/AssemblyComparator/TypeElements.cs
  tools/nnyeah/nnyeah/AssemblyComparator/TypeReworker.cs
  tools/nnyeah/nnyeah/AssemblyComparator/TypeVisitedEventArgs.cs
  tools/nnyeah/nnyeah/AssemblyComparator/UniquingStringDictionary.cs
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/Program.cs
Labels: enhancement, not-notes-worthy

#14854 [CI] Move the sing and notarize steps to a VM.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/prepare-pkg-stage.yml
Labels: enhancement, not-notes-worthy

#14853 [CI] Move templates to their own dir.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/sign-and-notarized/artifact-github-comment.yml
  tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml
  tools/devops/automation/templates/sign-and-notarized/publish-nugets.yml
  tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: not-notes-worthy

#14851 [dotnet] Update generated files after template changes.
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-controller/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/iosbinding/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/ioslib/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.macOS.Templates/macos/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.tvOS.Templates/tvos/.template.config/localize/templatestrings.en.json
Labels: not-notes-worthy

#14846 [dotnet] Use only the first two parts of our product version as the assembly version.
  Make.versions
  src/AssemblyInfo.cs.in
Labels: not-notes-worthy, run-dotnet-tests

#14847 Branch for .NET 6 and adjust versioning.
  Make.config
Labels: not-notes-worthy, run-dotnet-tests

#14852 [mtouch] Preserve the xamarin_dyn_* functions when we're handling Objective-C exceptions by unwinding managed code. Fixes #14193.
  tools/common/CompilerFlags.cs
  tools/common/Target.cs
  tools/mtouch/Target.mtouch.cs
Labels: bug

#14850 [tests] Add two test projects to compare app size between MAUI and Xamarin.Forms.
  tests/dotnet/Makefile
  tests/dotnet/size-comparison/MauiForms/Makefile
  tests/dotnet/size-comparison/MauiForms/MauiForms.map
  tests/dotnet/size-comparison/MauiForms/dotnet/App.xaml
  tests/dotnet/size-comparison/MauiForms/dotnet/App.xaml.cs
  tests/dotnet/size-comparison/MauiForms/dotnet/MainPage.xaml
  tests/dotnet/size-comparison/MauiForms/dotnet/MainPage.xaml.cs
  tests/dotnet/size-comparison/MauiForms/dotnet/MauiForms.csproj
  tests/dotnet/size-comparison/MauiForms/dotnet/MauiForms.sln
  tests/dotnet/size-comparison/MauiForms/dotnet/MauiProgram.cs
  tests/dotnet/size-comparison/MauiForms/dotnet/Platforms/iOS/AppDelegate.cs
  tests/dotnet/size-comparison/MauiForms/dotnet/Platforms/iOS/Info.plist
  tests/dotnet/size-comparison/MauiForms/dotnet/Platforms/iOS/Program.cs
  tests/dotnet/size-comparison/MauiForms/dotnet/Properties/launchSettings.json
  tests/dotnet/size-comparison/MauiForms/dotnet/Resources/Fonts/OpenSans-Regular.ttf
  tests/dotnet/size-comparison/MauiForms/dotnet/Resources/Images/dotnet_bot.svg
  tests/dotnet/size-comparison/MauiForms/dotnet/Resources/Raw/AboutAssets.txt
  tests/dotnet/size-comparison/MauiForms/dotnet/Resources/appicon.svg
  tests/dotnet/size-comparison/MauiForms/dotnet/Resources/appiconfg.svg
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/AppDelegate.cs
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon1024.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon120.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon152.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon167.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon180.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon20.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon29.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon40.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon58.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon60.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon76.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon80.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Assets.xcassets/AppIcon.appiconset/Icon87.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Entitlements.plist
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Info.plist
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Main.cs
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/MauiForms.iOS.csproj
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Properties/AssemblyInfo.cs
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Resources/Default-568h@2x.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Resources/Default-Portrait.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Resources/Default-Portrait@2x.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Resources/Default.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Resources/Default@2x.png
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.iOS/Resources/LaunchScreen.storyboard
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms.sln
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms/App.xaml
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms/App.xaml.cs
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms/AssemblyInfo.cs
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms/MainPage.xaml
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms/MainPage.xaml.cs
  tests/dotnet/size-comparison/MauiForms/oldnet/MauiForms/MauiForms.Shared.csproj
  tests/dotnet/size-comparison/MySingleView/Makefile
  tests/dotnet/size-comparison/MySingleView/MySingleView.map
  tests/dotnet/size-comparison/common.mk
Labels: not-notes-worthy

#14848 [release/6.0.3xx] [dotnet/Templates] Remove preview language
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/.template.config/template.json
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalystbinding/.template.config/template.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-controller/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-controller/.template.config/template.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/.template.config/template.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/.template.config/template.json
  dotnet/Templates/Microsoft.iOS.Templates/iosbinding/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/iosbinding/.template.config/template.json
  dotnet/Templates/Microsoft.iOS.Templates/ioslib/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.iOS.Templates/ioslib/.template.config/template.json
  dotnet/Templates/Microsoft.macOS.Templates/macos/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.macOS.Templates/macos/.template.config/template.json
  dotnet/Templates/Microsoft.tvOS.Templates/tvos/.template.config/localize/templatestrings.en.json
  dotnet/Templates/Microsoft.tvOS.Templates/tvos/.template.config/template.json
Labels: backported

#14868 [nnyeah] Move to generating map on the fly
  tools/nnyeah/nnyeah/AssemblyComparator/ComparingVisitor.cs
  tools/nnyeah/nnyeah/AssemblyComparator/ItemFoundEventArgs.cs
  tools/nnyeah/nnyeah/AssemblyComparator/TypeAndMemberMap.cs
  tools/nnyeah/nnyeah/AssemblyComparator/UniquingStringDictionary.cs
  tools/nnyeah/nnyeah/Program.cs
Labels: enhancement, not-notes-worthy

#14856 [printcore] Add nullability to (generated and manual) bindings
  src/PrintCore/Defs.cs
  src/PrintCore/PrintCore.cs
Labels: not-notes-worthy

#14861 [photos] Add nullability to (generated and manual) bindings
  src/Photos/PHAssetChangeRequest.cs
  src/Photos/PHAssetCreationRequest.cs
  src/Photos/PHChangeRequest.cs
  src/Photos/PHCompat.cs
  src/Photos/PHFetchResult.cs
  src/Photos/PHLivePhoto.cs
  src/Photos/PHPhotoLibrary.cs
Labels: not-notes-worthy

#14862 [quicklookui] Add nullability to (generated and manual) bindings
  src/QuickLookUI/QLPreviewPanel.cs
Labels: not-notes-worthy

#14863 [replaykit] Add nullability to (generated and manual) bindings
  src/ReplayKit/RPBroadcastConfiguration.cs
Labels: not-notes-worthy

#14844 [Xharness] Add a label per test project to later be able to filter them.
  tests/xharness/BCLTestImportTargetFactory.cs
  tests/xharness/Harness.cs
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
  tests/xharness/MacTestProject.cs
  tests/xharness/Program.cs
  tests/xharness/TestProject.cs
  tests/xharness/TestProjectExtensions.cs
  tests/xharness/iOSTestProject.cs
Labels: not-notes-worthy

#14866 [Xharness]Enable nullability and update C# to new code patterns.
  tests/xharness/Jenkins/TestTasks/AggregatedRunSimulatorTask.cs
Labels: enhancement, not-notes-worthy

#14881 [sensorkit] Add nullability to (generated and manual) bindings
  src/SensorKit/SRSensor.cs
Labels: not-notes-worthy

#14883 [spritekit] Add nullability to (generated and manual) bindings
  src/SpriteKit/SKNode.cs
  src/SpriteKit/SKShapeNode.cs
  src/SpriteKit/SKWarpGeometryGrid.cs
Labels: not-notes-worthy

#14886 [systemcomponentmodel] Add nullability to (generated and manual) bindings
  src/System.ComponentModel/CancelEventArgs.cs
Labels: not-notes-worthy

#14888 Bump API reference for .NET to the 6.0.3xx branch.
  Make.config
Labels: not-notes-worthy

#14885 [nnyeah] Add usage of module mapping
  tools/nnyeah/nnyeah/AssemblyComparator/TypeAndMemberMap.cs
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/MemberNotFoundException.cs
  tools/nnyeah/nnyeah/Program.cs
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/nnyeah/TypeNotFoundException.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#14875 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#14865 [quicklook] Add nullability to (generated and manual) bindings
  src/QuickLook/Thumbnail.cs
Labels: not-notes-worthy

#14878 [searchkit] Add nullability to (generated and manual) bindings
  src/SearchKit/SearchKit.cs
Labels: not-notes-worthy

#14900 [nnyeah] Fix race on error message output
  tools/nnyeah/nnyeah/Program.cs
Labels: not-notes-worthy

#14909 [apidiff] Use DOTNET_TFM instead of hardcoding 'net6.0'.
  tools/apidiff/Makefile
Labels: skip-all-tests, not-notes-worthy

#14911 [introspection] Fix failures on older iOS/tvOS
  tests/introspection/ApiSelectorTest.cs
Labels: not-notes-worthy

#14860 Fix crash with NSUrl implicit conversion and null
  src/Foundation/NSUrl.cs
  tests/monotouch-test/Network/NSUrlTest.cs
Labels: notes-mention

#14898 [nnyeah] Beginnings of an integration test framework
  tools/nnyeah/Makefile
  tools/nnyeah/integration/Makefile
  tools/nnyeah/integration/MyClass.cs
  tools/nnyeah/integration/ios/iOSIntegration.csproj
  tools/nnyeah/integration/macOS/macOSIntegration.csproj
  tools/nnyeah/integration/tvOS/tvOSIntegration.csproj
Labels: not-notes-worthy

#14901 [nnyeah] Bump to NET6
  tools/nnyeah/nnyeah/nnyeah.csproj
Labels: not-notes-worthy

#14914 [nnyeah] Add dotnet tool support
  tools/nnyeah/.gitignore
  tools/nnyeah/Makefile
  tools/nnyeah/nnyeah/nnyeah.csproj
Labels: not-notes-worthy

#14867 [XHarness] Enable nullable and fix some code issues (wrong inheritance)
  tests/xharness/Jenkins/TestTasks/AppleTestTask.cs
Labels: enhancement, not-notes-worthy

#14910 [Nnyeah] Ensure that we have all the needed xamarin-macios dlls when using make.
  tools/nnyeah/Makefile
Labels: not-notes-worthy

#14908 [CI] Make signing faster by using two diff jobs one for classic and one for dotnet.
  tools/devops/automation/templates/sign-and-notarized/dotnet-signing.yml
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml
  tools/devops/automation/templates/sign-and-notarized/setup.yml
  tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
Labels: enhancement, not-notes-worthy

#14917 [apidiff] Pass full paths to mono-api-info and mono-api-html.
  tools/apidiff/Makefile
Labels: skip-all-tests, not-notes-worthy

#14924 [msbuild] Enable nullability in the AOTCompileTask class.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/AOTCompileTaskBase.cs
Labels: not-notes-worthy

#14927 [release/6.0.3xx-rc3] Bumps Xamarin.HotRestart.Application to 1.1.5
  msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj
Labels: backported

#14913 [nnyeah] Start testing
  src/generate-frameworks-constants/generate-frameworks-constants.csproj
  tests/mtouch/Cache.cs
  tools/common/Execution.cs
  tools/common/StringUtils.cs
  tools/nnyeah/nnyeah.sln
  tools/nnyeah/tests/CompileALibrary.cs
  tools/nnyeah/tests/nnyeah-tests.csproj
  tools/nnyeah/tests/utils/Compiler.cs
  tools/nnyeah/tests/utils/TestRunning.cs
  tools/xibuild/xibuild.csproj
Labels: enhancement, skip-all-tests, not-notes-worthy

#14945 [nnyeah] IConvertible ancient history
  tools/nnyeah/nnyeah/MethodTransformations.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#14942 [Foundation] Make NSUserDefaults.VolatileDomainNames a property in XAMCORE_5_0.
  src/foundation.cs
Labels: skip-all-tests, not-notes-worthy

#14926 [release/6.0.3xx] Bumps Xamarin.HotRestart.Application to 1.1.5
  Make.versions
  msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj
Labels: backported

#14935 [apidiff] Use variables to reduce code duplication.
  tools/apidiff/Makefile
Labels: skip-all-tests, not-notes-worthy

#14918 Add a [NativeName] attribute we can use to declare the native name for a type (enum/struct).
  src/AppKit/Enums.cs
  src/AudioToolbox/AudioType.cs
  src/CoreMidi/MidiCIDeviceIdentification.cs
  src/EventKit/EKEnums.cs
  src/ExternalAccessory/EAEnums.cs
  src/Foundation/Enum.cs
  src/GameKit/GameKit.cs
  src/HomeKit/HMEnums.cs
  src/LocalAuthentication/LAEnums.cs
  src/MediaPlayer/MediaPlayer.cs
  src/MultipeerConnectivity/Enums.cs
  src/NetworkExtension/NEEnums.cs
  src/ObjCRuntime/NativeNameAttribute.cs
  src/Photos/Enums.cs
  src/ReplayKit/RPEnums.cs
  src/SafariServices/SSEnums.cs
  src/Security/Enums.cs
  src/Security/SecureTransport.cs
  src/StoreKit/Enums.cs
  src/UIKit/UIEnums.cs
  src/WatchKit/WKDefs.cs
  src/bgen/bgen.csproj
  src/coreimage.cs
  src/coremidi.cs
  src/corenfc.cs
  src/fileprovider.cs
  src/frameworks.sources
  src/generator-attribute-manager.cs
  src/generator-enums.cs
  src/generator.csproj
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/MapNamesCheck.cs
  tests/xtro-sharpie/Runner.cs
  tests/xtro-sharpie/xtro-sharpie.csproj
  tools/common/StaticRegistrar.cs
  tools/dotnet-linker/Steps/RemoveAttributesStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/mmp/mmp.csproj
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
  tools/mtouch/mtouch.csproj
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#14960 [apidiff] Ignore inherited interfaces.
  tools/apidiff/Makefile
Labels: not-notes-worthy

#14959 [release/6.0.3xx] Bump maccore to get fix for #14834.
  Make.versions
  mk/xamarin.mk
Labels: not-notes-worthy

#14950 [xcode13.3] Bump maccore to get fix for #14834.
  mk/xamarin.mk
Labels: bug

#14946 Bump maccore to get fix for #14834.
  mk/xamarin.mk
Labels: bug, not-notes-worthy

#14922 [runtime] Fix build when logging is enabled.
  runtime/coreclr-bridge.m
Labels: not-notes-worthy

#14923 Adjust versioning scheme for .NET to make the third field the commit distance.
  Make.config
  Make.versions
  dotnet/VERSIONS.md
  system-dependencies.sh
Labels: not-notes-worthy, run-dotnet-tests

#14937 [tests] Unignore test that's now fixed in .NET.
  tests/linker/ios/link sdk/CryptoTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#14303 Add MetalPerformanceShadersGraph Bindings
  CODEOWNERS
  src/Foundation/NSObject.mac.cs
  src/MetalPerformanceShaders/MPSNDArray.cs
  src/MetalPerformanceShadersGraph/MPSGraphEnums.cs
  src/MetalPerformanceShadersGraph/MPSGraphExtensions.cs
  src/MetalPerformanceShadersGraph/MPSGraphTensorData.cs
  src/frameworks.sources
  src/generator.cs
  src/metalperformanceshadersgraph.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/iOS/iOSApiCtorInitTest.cs
  tests/introspection/iOS/iOSApiFieldTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/monotouch-test/MetalPerformanceShaders/MnistTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/iOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/macOS-MetalPerformanceShadersGraph.todo
  tests/xtro-sharpie/tvOS-MetalPerformanceShadersGraph.todo
  tools/common/Frameworks.cs
  tools/linker/ObjCExtensions.cs
  tools/mtouch/Makefile
Labels: community

#14932 [CI] Perform the classic sign-notarize of each pkg in parallel.
  tools/devops/automation/templates/sign-and-notarized/dotnet-signing.yml
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/sign-and-notarized/prepare-pkg-stage.yml
  tools/devops/automation/templates/sign-and-notarized/sign-and-notarized.yml
Labels: enhancement, not-notes-worthy

#14964 [apidiff] Fix comparison of assemblies with different names.
  tools/apidiff/Makefile
Labels: skip-all-tests, not-notes-worthy

#14954 [Tools] Enable nullability on Execution.cs
  tools/common/Execution.cs
  tools/nnyeah/tests/utils/Compiler.cs
Labels: enhancement, not-notes-worthy

#14956 [nnyeah] Module information extensions
  tools/nnyeah/nnyeah/Enums.cs
  tools/nnyeah/nnyeah/ModuleExtensions.cs
  tools/nnyeah/tests/XamarinDependencyTests.cs
  tools/nnyeah/tests/nnyeah-tests.csproj
Labels: enhancement, skip-all-tests, not-notes-worthy

#14957 [nnyeah] Refactor reworker to a 1-pass initialization
  tools/nnyeah/integration/Makefile
  tools/nnyeah/nnyeah/Program.cs
  tools/nnyeah/nnyeah/Reworker.cs
Labels: skip-all-tests, not-notes-worthy

#14949 [Nnyeah] Improve error messages for missing required arguments
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/Program.cs
Labels: skip-all-tests, not-notes-worthy

#14962 [nnyeah] Fix method hashing of generic matching non-generic due to Cecil limitation.
  tools/nnyeah/integration/Makefile
  tools/nnyeah/nnyeah/AssemblyComparator/ModuleElements.cs
  tools/nnyeah/nnyeah/PatchName.cs
Labels: skip-all-tests, not-notes-worthy

#14944 [Tools] Enable nullability on StringUtils.
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/AOTCompileTaskBase.cs
  tools/common/Execution.cs
  tools/common/StringUtils.cs
Labels: enhancement, not-notes-worthy

#14947 [Tools] Enable nullability on Cache.cs.
  tests/mtouch/Cache.cs
Labels: enhancement, not-notes-worthy

#14897 [Xharness] Enable nullable in the BuildProject class and clean code a little.
  tests/xharness/Jenkins/TestTasks/BuildProject.cs
Labels: enhancement, not-notes-worthy

#14984 [actions] Add GitHub action to compute the changelog for maestro bumps.
  .github/workflows/maestro-changelog.yml
Labels: not-notes-worthy

#14988 [CI] Ensure we do not leave processes once we are done.
  tools/devops/automation/templates/common/setup.yml
  tools/devops/automation/templates/mac/build.yml
Labels: enhancement, not-notes-worthy

#14995 [make] Add better error message when the required Xcode isn't installed.
  Make.config
Labels: skip-all-tests, not-notes-worthy

#14992 [devops] A PR API diff with changes isn't an error.
  tools/devops/automation/scripts/bash/compare.sh
Labels: skip-all-tests, not-notes-worthy

#14991 [xharness] Fix logic to include the .NET xtro tests.
  tests/xharness/Jenkins/Jenkins.cs
Labels: skip-all-tests, not-notes-worthy

#14998 [xharness/devops] Enable .NET tests by default.
  tests/xharness/Jenkins/Jenkins.cs
  tools/devops/automation/templates/common/configure.yml
Labels: skip-all-tests, not-notes-worthy

#15003 [actions] Fix changelog logic when there's no existing changelog comment.
  .github/workflows/maestro-changelog.yml
Labels: not-notes-worthy

#14920 [ObjCRuntime] Improve the debug logging in the Runtime.CoreCLR.cs file.
  src/ObjCRuntime/Runtime.CoreCLR.cs
Labels: not-notes-worthy

#14884 [security] Add nullability to (generated and manual) bindings
  src/Security/Authorization.cs
  src/Security/Certificate.cs
  src/Security/CssmKeyUse.cs
  src/Security/CssmTPAppleCertStatus.cs
  src/Security/ImportExport.cs
  src/Security/Items.cs
  src/Security/SecCertificate2.cs
  src/Security/SecExternalFormat.cs
  src/Security/SecIdentity2.cs
  src/Security/SecItemAttr.cs
  src/Security/SecItemClass.cs
  src/Security/SecItemExportFlags.cs
  src/Security/SecKeyAttribute.cs
  src/Security/SecPolicy.cs
  src/Security/SecProtocolMetadata.cs
  src/Security/SecProtocolOptions.cs
  src/Security/SecSharedCredential.cs
  src/Security/SecStatusCodeExtensions.cs
  src/Security/SecTrust.cs
  src/Security/SecTrust2.cs
  src/Security/SslConnection.cs
  src/Security/SslContext.cs
  src/Security/Trust.cs
Labels: not-notes-worthy

#14941 [usernotification] Add nullability to (generated and manual) bindings
  src/UserNotifications/UNNotificationAttachment.cs
Labels: not-notes-worthy

#14929 [twitter] Add nullability to (generated and manual) bindings
  src/Twitter/Enums.cs
  src/Twitter/TWCompat.cs
Labels: not-notes-worthy

#14970 [CI] Sign the contents of the bundle.zip to be used in xma.
  tools/devops/automation/templates/sign-and-notarized/dotnet-signing.yml
Labels: enhancement, not-notes-worthy

#14948 [videosubscriberaccount] Add nullability to (generated and manual) bindings
  src/VideoSubscriberAccount/VSAccountManager.cs
  src/VideoSubscriberAccount/VSAccountMetadataRequest.cs
  src/VideoSubscriberAccount/VSAccountProviderAuthenticationScheme.cs
Labels: not-notes-worthy

#14987 [nnyeah] Check dependencies in output
  tools/nnyeah/nnyeah/Program.cs
  tools/nnyeah/tests/CompileALibrary.cs
  tools/nnyeah/tests/DependencyRemovedTests.cs
  tools/nnyeah/tests/nnyeah-tests.csproj
  tools/nnyeah/tests/utils/Compiler.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15013 [devops] Don't ignore api-diff failures, but show then as non-fatal warnings instead.
  tools/devops/automation/scripts/bash/compare.sh
  tools/devops/automation/templates/build/api-diff.yml
Labels: skip-all-tests, not-notes-worthy

#15011 [compare-commits] We don't use XmlDocSync anymore, so remove workaround for NuGet.config.
  tools/compare-commits.sh
Labels: skip-all-tests, not-notes-worthy

#15010 Bump api references to the latest stable (d17-2).
  Make.config
Labels: skip-all-tests, not-notes-worthy

#15012 [devops] Remove the logic for SkipPublicJenkins, it's never set anymore.
  tools/devops/automation/templates/build/api-diff.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/common/configure.yml
Labels: not-notes-worthy

#15009 [devops] Authenticate requests to GitHub.
  tools/devops/automation/scripts/GitHub.psm1
Labels: skip-all-tests, not-notes-worthy

#15004 Update the issue template.
  ISSUE_TEMPLATE.md
Labels: not-notes-worthy

#14993 [msbuild] Improve error reporting when an external tool fails to print some of stderr.
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.Designer.cs
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/XamarinTask.cs
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#15016 [nnyeah] Get nint types
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/DependencyRemovedTests.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#14997 [CI] Reset the submodules for the API diff.
  tools/devops/automation/templates/common/checkout.yml
Labels: not-notes-worthy

#15007 [apidiff] Remove detection of empty diffs for cases we know that will never happen.
  tools/apidiff/Makefile
Labels: skip-all-tests, not-notes-worthy

#15006 [apidiff] Simplify code a bit to use templates and iterate over the selected platforms.
  tools/apidiff/Makefile
Labels: skip-all-tests, not-notes-worthy

#14994 [cecil-tests] Improve these tests a bit.
  tests/cecil-tests/AttributeTest.cs
  tests/cecil-tests/ConstructorTest.cs
  tests/cecil-tests/Helper.cs
  tests/cecil-tests/Makefile
  tests/cecil-tests/MarshalAsTest.cs
  tests/cecil-tests/ObsoleteTest.cs
  tests/cecil-tests/OpenTKTest.cs
  tests/cecil-tests/Test.cs
  tests/cecil-tests/cecil-tests.csproj
  tests/common/Configuration.cs
  tests/common/ExecutionHelper.cs
  tools/common/TargetFramework.cs
Labels: not-notes-worthy

#15018 [tests] Adjust a few linker tests to cope with unreliable networks.
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/CryptoTest.cs
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#15026 Avoid executing _VerifyXcodeVersion when there's no connection to a Mac
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.Messaging.Apple.targets
Labels: not-notes-worthy

#15017 [Nnyeah] nuget execution
  tools/nnyeah/integration/.gitignore
  tools/nnyeah/integration/API/Makefile
Labels: skip-all-tests, not-notes-worthy

#14928 [tvservices] Add nullability to (generated and manual) bindings
  src/TVServices/TVContentItemImageShape.cs
Labels: not-notes-worthy

#14969 [xkit] Add nullability to (generated and manual) bindings
  src/XKit/Types.cs
  src/XKit/XKitCompat.cs
Labels: not-notes-worthy

#14973 [vision] Add nullability to (generated and manual) bindings
  src/Vision/VNBarcodeSymbologyExtensions.cs
  src/Vision/VNCircle.cs
  src/Vision/VNCompat.cs
  src/Vision/VNDetectBarcodesRequest.cs
  src/Vision/VNFaceLandmarkRegion2D.cs
  src/Vision/VNFeaturePrintObservation.cs
  src/Vision/VNRecognizedPointsObservation.cs
  src/Vision/VNRequest.cs
  src/Vision/VNRequestRevision.cs
  src/Vision/VNUtils.cs
  src/Vision/VNVector.cs
Labels: not-notes-worthy

#15029 [runtime] Handle fatal managed exceptions a bit better in the runtime.
  runtime/monotouch-main.m
  runtime/runtime.m
  runtime/xamarin/runtime.h
Labels: not-notes-worthy

#15019 [devops] Reword api diff GitHub text a bit and add index entry.
  tools/devops/automation/scripts/APIDiff.psm1
Labels: skip-all-tests, not-notes-worthy

#15042 [mono] Bump mono to the latest version of 2020-02
  Make.config
  mk/mono.mk
Labels: notes-mention

#15045 [devops] Fix tests according to recent changes.
  tools/devops/automation/scripts/APIDiff.Tests.ps1
Labels: skip-all-tests, not-notes-worthy

#14955 [wkwebkit] Add nullability to (generated and manual) bindings
  src/WKWebKit/WKWindowFeatures.cs
Labels: not-notes-worthy

#15023 [corespotlight] Add nullability to (generated and manual) bindings
  src/CoreSpotlight/CSSearchableIndex.cs
  src/CoreSpotlight/CSSearchableItemAttributeSet.cs
Labels: not-notes-worthy

#14896 [storekit] Add nullability to (generated and manual) bindings
  src/StoreKit/NativeMethods.cs
  src/StoreKit/SKAdNetworkCompat.cs
  src/StoreKit/SKCloudServiceSetupOptions.cs
  src/StoreKit/SKOverlayAppClipConfiguration.cs
  src/StoreKit/SKOverlayAppConfiguration.cs
  src/StoreKit/SKPayment.cs
  src/StoreKit/SKPaymentTransactionObserver.cs
  src/StoreKit/SKReceiptProperty.cs
  src/StoreKit/StoreProductParameters.cs
Labels: not-notes-worthy

#14971 [videotoolbox] Add nullability to (generated and manual) bindings
  src/VideoToolbox/VTCompressionProperties.cs
  src/VideoToolbox/VTCompressionSession.cs
  src/VideoToolbox/VTDataRateLimit.cs
  src/VideoToolbox/VTDecompressionProperties.cs
  src/VideoToolbox/VTDecompressionSession.cs
  src/VideoToolbox/VTFrameSilo.cs
  src/VideoToolbox/VTPixelTransferProperties.cs
  src/VideoToolbox/VTPropertyOptions.cs
  src/VideoToolbox/VTSession.cs
  src/VideoToolbox/VTUtilities.cs
  src/VideoToolbox/VTVideoEncoder.cs
Labels: not-notes-worthy

#15048 [nnyeah] Refactor module usage
  tools/nnyeah/nnyeah/AssemblyComparator/TypeAndMemberMap.cs
  tools/nnyeah/nnyeah/MethodTransformations.cs
  tools/nnyeah/nnyeah/ModuleContainer.cs
  tools/nnyeah/nnyeah/Program.cs
  tools/nnyeah/nnyeah/Reworker.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15049 [nnyeah] Optionally run integration test nnyeah in-process
  tools/nnyeah/tests/integration/IntegrationExamples.cs
Labels: skip-all-tests, not-notes-worthy

#15043 [Runtime] Provide better diagnostics if we fail to invoke a method in CoreCLR.
  src/ObjCRuntime/Runtime.CoreCLR.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#15025 [dotnet-linker] Bump default trampoline count when using the interpreter on x64 in .NET. Fixes #14887.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/common/Application.cs
  tools/dotnet-linker/LinkerConfiguration.cs
Labels: bug

#15050 [d17-2] [mono] Bump mono to the latest version of 2020-02
  Make.config
  mk/mono.mk
Labels: notes-mention, backported

#15005 [devops] Compute DOTNET_TFM instead of hardcoding 'net6.0.'
  tools/devops/automation/templates/build/api-diff-github-comment.yml
Labels: skip-all-tests, not-notes-worthy

#15051 [nnyeah] Integration tests run against dotnet tool from nupkg
  tools/nnyeah/Makefile
  tools/nnyeah/tests/integration/IntegrationExamples.cs
Labels: skip-all-tests, not-notes-worthy

#15032 [Xharness] Move to use a flag to decide what tests to use
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/MacTestTasksEnumerable.cs
  tests/xharness/Jenkins/MakeTestTaskEnumerable.cs
  tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
  tests/xharness/Jenkins/RunDeviceTasksFactory.cs
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
  tests/xharness/Jenkins/TestSelector.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tests/xharness/TestLabel.cs
  tests/xharness/xharness.csproj
Labels: enhancement, not-notes-worthy

#15052 [nnyeah] Import Type and Member references
  tools/nnyeah/nnyeah/Reworker.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15054 [Localization] Use force-with-lease
  .github/workflows/localization_branch_sync.yml
  tools/devops/automation/templates/loc-translations.yml
Labels: not-notes-worthy

#15063 [XHarness] Provide the correct value to the tvOS label.
  tests/xharness/TestLabel.cs
Labels: bug, not-notes-worthy

#15065 [nnyeah] Add unit test showing most common nuget failure
  tools/nnyeah/tests/unit/CompileALibrary.cs
  tools/nnyeah/tests/unit/utils/Compiler.cs
Labels: skip-all-tests, not-notes-worthy

#15058 [nnyeah] Add rest of top nuget examples to integration suite
  tools/nnyeah/tests/integration/IntegrationExamples.cs
Labels: skip-all-tests, not-notes-worthy

#15074 [release/6.0.4xx] Automatically bump commit distance.
  Make.config
  Make.versions
  system-dependencies.sh
Labels: skip-all-tests, not-notes-worthy

#15072 [coremotion] Add nullability to (generated and manual) bindings
  src/CoreMotion/CMCompat.cs
  src/CoreMotion/CMDeviceMotion.cs
  src/CoreMotion/CMMagnetometer.cs
  src/CoreMotion/CMSensorDataList.cs
  src/CoreMotion/Defs.cs
  src/CoreMotion/Extras.cs
Labels: not-notes-worthy

#15082 [nnyeah] fix issues compiling against nnyeah touched libraries
  tests/common/DotNet.cs
  tools/nnyeah/integration/API/IntegrationAPI.cs
  tools/nnyeah/integration/Consumer/Consumer.cs
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/integration/IntegrationExamples.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15091 [devops] Publish builds from the net7.0 branch.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/post-build-pipeline.yml
Labels: skip-all-tests, not-notes-worthy

#15076 [dotnet] Make sure to not run the linker when we're on a disconnected Windows build.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: bug

#15077 [release/6.0.4xx] Adjust a few tests to cope with broken networks.
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/CryptoTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/linker/mac/LinkAnyTest.cs
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
Labels: not-notes-worthy

#15064 [nnyeah] Centralize error handling
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/MemberNotFoundException.cs
  tools/nnyeah/nnyeah/Program.cs
  tools/nnyeah/nnyeah/TypeNotFoundException.cs
Labels: skip-all-tests, not-notes-worthy

#15079 Provisionator's XcodeSelect now configures Xamarin Settings.plist
  tools/devops/build-provisioning.csx.in
  tools/devops/device-tests-provisioning.csx.in
  tools/devops/provision-shared.csx
  tools/devops/provision-xcode.csx.in
Labels: not-notes-worthy

#15087 [AppKit] Add constructors for NSMenuToolbarItem classes
  src/appkit.cs
Labels: notes-mention

#15097 [nnyeah] Arithmetic tests
  tools/nnyeah/integration/API/IntegrationAPI.cs
  tools/nnyeah/integration/Consumer/Consumer.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15101 [Harness] Revert label changes
  tests/xharness/Jenkins/Jenkins.cs
  tests/xharness/Jenkins/MacTestTasksEnumerable.cs
  tests/xharness/Jenkins/MakeTestTaskEnumerable.cs
  tests/xharness/Jenkins/NUnitTestTasksEnumerable.cs
  tests/xharness/Jenkins/RunDeviceTasksFactory.cs
  tests/xharness/Jenkins/RunSimulatorTasksFactory.cs
  tests/xharness/Jenkins/TestSelector.cs
  tests/xharness/Jenkins/TestVariationsFactory.cs
  tests/xharness/TestLabel.cs
  tests/xharness/xharness.csproj
Labels: not-notes-worthy

#15095 [release/6.0.4xx] [introspection] Fix failures on older iOS/tvOS
  tests/introspection/ApiSelectorTest.cs
Labels: not-notes-worthy, backported

#15096 [release/6.0.4xx] [dotnet] Make sure to not run the linker when we're on a disconnected Windows build.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: bug, backported

#15102 Remove the Visual Studio dependency.
  .config/dotnet-tools.json
  Make.config
  builds/Makefile
  mk/quiet.mk
  src/Makefile
  system-dependencies.sh
  tests/common/Configuration.cs
  tools/devops/automation/VSMacVersion.ps1
Labels: not-notes-worthy

#15085 [runtime] Skip passing ICU_DAT_FILE_PATH to the runtime if we don't have an ICU data file.
  runtime/coreclr-bridge.m
  runtime/runtime.m
Labels: not-notes-worthy, run-dotnet-tests

#15114 Updated Messaging and Hot Restart versions
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#15109 [nnyeah] added tests for boolean operators
  tools/nnyeah/integration/API/IntegrationAPI.cs
  tools/nnyeah/integration/Consumer/Consumer.cs
  tools/nnyeah/tests/unit/CompileALibrary.cs
Labels: enhancement, not-notes-worthy

#15115 [release/6.0.4xx] Remove the Visual Studio dependency.
  .config/dotnet-tools.json
  Make.config
  builds/Makefile
  mk/quiet.mk
  src/Makefile
  system-dependencies.sh
  tests/common/Configuration.cs
  tools/devops/automation/VSMacVersion.ps1
Labels: not-notes-worthy, backported

#15116 [d17-2] Remove the Visual Studio dependency.
  .config/dotnet-tools.json
  Make.config
  builds/Makefile
  mk/quiet.mk
  src/Makefile
  system-dependencies.sh
  tests/common/Configuration.cs
  tools/devops/automation/VSMacVersion.ps1
Labels: not-notes-worthy, backported

#15078 [d17-2] Adjust a few tests to cope with broken networks.
  tests/linker/ios/link all/LinkAllTest.cs
  tests/linker/ios/link sdk/CryptoTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/linker/mac/LinkAnyTest.cs
  tests/monotouch-test/System.Net.Http/NetworkResources.cs
Labels: not-notes-worthy, backported

#15128 [nnyeah] implicit operator tests
  tools/nnyeah/integration/API/IntegrationAPI.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#14979 Bump maccore.
  mk/xamarin.mk
Labels: run-all-tests, skip-device-tests, not-notes-worthy

#15135 Fix bundle.zip structure in 'Sign bundle.zip' step
  tools/devops/automation/templates/sign-and-notarized/dotnet-signing.yml
Labels: not-notes-worthy

#15132 [nnyeah] added missing test invocations
  tools/nnyeah/integration/Consumer/Consumer.cs
Labels: enhancement, skip-all-tests, not-notes-worthy

#15140 [xharness] Redirect stdout/stderr for watch apps.
  tests/xharness/AppRunner.cs
Labels: not-notes-worthy

#15141 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#15080 [msbuild] Improve logic to clean up app bundle for unwanted files.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: bug

#15146 [corefoundation] Cache `kCFNull` to avoid native calls
  src/CoreFoundation/CFArray.cs
  src/corefoundation.cs
  tests/perftest/NativeArrayPerf.cs
Labels: community, notes-mention

#15134 [nnyeah] Map NSObject ctors with IntPtr to NativeHandle
  tools/nnyeah/integration/API/IntegrationAPI.cs
  tools/nnyeah/integration/Consumer/Consumer.cs
  tools/nnyeah/nnyeah/AssemblyComparator/ComparingVisitor.cs
  tools/nnyeah/nnyeah/AssemblyComparator/ModuleElements.cs
  tools/nnyeah/nnyeah/AssemblyConverter.cs
  tools/nnyeah/nnyeah/AssemblyResolver.cs
  tools/nnyeah/nnyeah/ConstructorTransforms.cs
  tools/nnyeah/nnyeah/Errors.Designer.cs
  tools/nnyeah/nnyeah/Errors.resx
  tools/nnyeah/nnyeah/Program.cs
  tools/nnyeah/nnyeah/Reworker.cs
  tools/nnyeah/tests/integration/IntegrationExamples.cs
  tools/nnyeah/tests/unit/CompileALibrary.cs
  tools/nnyeah/tests/unit/ConstructorTransformTests.cs
  tools/nnyeah/tests/unit/DependencyRemovedTests.cs
  tools/nnyeah/tests/unit/XamarinDependencyTests.cs
  tools/nnyeah/tests/unit/utils/TestRunning.cs
Labels: skip-all-tests, not-notes-worthy

#15158 Bump maccore.
  mk/xamarin.mk
Labels: not-notes-worthy

#15152 Add newlines to issue template to fix markdown formatting problems.
  ISSUE_TEMPLATE.md
Labels: not-notes-worthy
