Repository dotnet/macios, pull requests merged in 2022-11, with the labels that each got.

#16521 [release/6.0.4xx] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16517 [xcode14.1] Update all provisionator call sites to use AUTH_TOKEN_GITHUB_COM
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16534 [xcode14.1] Bump to stable release of Xcode 14.1
  Make.config
Labels: notes-mention

#16535 [net7.0-xcode14.1] [tests] Handle managed exceptions in a networking callback.
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy, backported

#16536 [xcode14.1] [tests] Handle managed exceptions in a networking callback.
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy, backported

#16551 Merge xcode14.1 into net7.0-xcode14.1.
  Make.config
  msbuild/Xamarin.iOS.Tasks/Xamarin.WatchOS.App.Common.targets
  src/ObjCRuntime/Runtime.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: not-notes-worthy

#16548 [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.
  Make.config
  tools/apidiff/Makefile
  tools/apidiff/README.md
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/main-stage.yml
Labels: skip-all-tests, not-notes-worthy

#16549 Merge xcode14.1 into 6.0.4xx-xcode14.1.
  Make.config
  msbuild/Xamarin.iOS.Tasks/Xamarin.WatchOS.App.Common.targets
  src/ObjCRuntime/Runtime.cs
  tests/monotouch-test/ObjCRuntime/RegistrarTest.cs
  tests/monotouch-test/ObjCRuntime/RuntimeTest.cs
Labels: not-notes-worthy

#16533 [Foundation] Fix capitalization mistake in type NSBundle
  src/foundation.cs
Labels: notes-mention

#7404 Fix DateTime -> NSDate conversion
  src/Foundation/NSDate.cs
  tests/monotouch-test/Foundation/DateTest.cs
Labels: enhancement

#16559 [release/6.0.4xx-xcode14.1] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.
  Make.config
  builds/Makefile
  tools/apidiff/Makefile
  tools/apidiff/README.md
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#16558 [release/6.0.4xx-xcode14] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.
  Make.config
  builds/Makefile
  tools/apidiff/Makefile
  tools/apidiff/README.md
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#16556 [devops] Make publishing binlogs nonfatal.
  tools/devops/automation/post-build-pipeline.yml
Labels: not-notes-worthy

#16554 [release/7.0.1xx-xcode13.3] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.
  Make.config
  builds/Makefile
  tools/apidiff/Makefile
  tools/apidiff/README.md
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/main-stage.yml
Labels: skip-all-tests, not-notes-worthy, backported

#16550 [release/6.0.4xx-xcode14.1] [tests] Handle managed exceptions in a networking callback.
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: not-notes-worthy, backported

#16553 [release/7.0.1xx-xcode14] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.
  Make.config
  builds/Makefile
  tools/apidiff/Makefile
  tools/apidiff/README.md
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/main-stage.yml
Labels: skip-all-tests, not-notes-worthy, backported

#16560 [net7.0-xcode14.1] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.
  Make.config
  builds/Makefile
  tools/apidiff/Makefile
  tools/apidiff/README.md
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#16545 [Photos] Fix capitalization mistake in PHFetchResult type
  src/photos.cs
Labels: notes-mention

#16552 [devops] Move logic to store and load the build configuration to disk into shareable PowerShell functions.
  tools/devops/automation/scripts/VSTS.Tests.ps1
  tools/devops/automation/scripts/VSTS.psm1
  tools/devops/automation/scripts/load-configuration.ps1
  tools/devops/automation/templates/common/configure.yml
  tools/devops/automation/templates/publish-html-result.yml
Labels: not-notes-worthy

#16557 [xcode14.1] [apidiff] Change to use dl.internalx.com with a GitHub PAT for API reference downloads.
  Make.config
  builds/Makefile
  tools/apidiff/Makefile
  tools/apidiff/README.md
  tools/devops/automation/templates/build/api-diff-build-and-detect.yml
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#16576 [WebKit] Fix capitalization mistakes in type DomDocument
  src/webkit.cs
Labels: notes-mention

#16578 [UIKit] Fix xHeight -> XHeight
  src/uikit.cs
Labels: notes-mention

#16575 [ImageKit] Fix capitalization mistakes autoPlayDelay -> AutoPlayDelay, filterArray -> FilterArray
  src/imagekit.cs
Labels: notes-mention

#16490 [autoformat] Add the Contacts, CoreAnimation, CoreBluetooth and CoreData frameworks.
  src/Contacts/CNContact.cs
  src/Contacts/CNContactStore.cs
  src/Contacts/CNEnums.cs
  src/Contacts/CNSocialProfile.cs
  src/CoreAnimation/CABasicAnimation.cs
  src/CoreAnimation/CACompat.cs
  src/CoreAnimation/CADefs.cs
  src/CoreAnimation/CAEnums.cs
  src/CoreAnimation/CAFrameRateRange.cs
  src/CoreAnimation/CAKeyFrameAnimation.cs
  src/CoreAnimation/CALayer.cs
  src/CoreAnimation/CALayerDelegate.cs
  src/CoreAnimation/CAMediaTimingFunction.cs
  src/CoreAnimation/CATextLayer.cs
  src/CoreAnimation/CATransform3D.cs
  src/CoreBluetooth/AdvertisementDataOptions.cs
  src/CoreBluetooth/CBUUID.cs
  src/CoreBluetooth/CoreBluetooth.cs
  src/CoreBluetooth/Enums.cs
  src/CoreBluetooth/GuidWrapper.cs
  src/CoreBluetooth/PeripheralConnectionOptions.cs
  src/CoreBluetooth/PeripheralScanningOptions.cs
  src/CoreData/Enums.cs
  src/CoreData/NSEntityDescription.cs
  tools/autoformat.sh
Labels: not-notes-worthy

#16594 [DevOps] Update the version of the provisionator template to deal with the new storage.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy

#16596 [xcode14.1] [DevOps] Update the version of the provisionator template to deal with the new storage.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16597 [release/6.0.4xx-xcode14.1] [DevOps] Update the version of the provisionator template to deal with the new storage.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16598 [release/7.0.1xx] [DevOps] Update the version of the provisionator template to deal with the new storage.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16592 [xcode14.1] [tests] Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop.
  tests/common/TestRuntime.cs
  tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
Labels: not-notes-worthy, backported

#16591 [release/6.0.4xx-xcode14.1] [tests] Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop.
  tests/common/TestRuntime.cs
  tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
Labels: not-notes-worthy, backported

#16590 [release/7.0.1xx] [tests] Ignore ExceptionsTest.ManagedExceptionPassthrough on ARM64 desktop.
  tests/common/TestRuntime.cs
  tests/monotouch-test/ObjCRuntime/ExceptionsTest.cs
Labels: not-notes-worthy, backported

#16602 [DevOps] Allow to set the azure storage to be used via variables.
  tools/devops/automation/templates/main-stage.yml
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
  tools/devops/automation/templates/variables.yml
Labels: not-notes-worthy

#16593 [autoformat] Add introspection.
  tests/common/MonoNativeConfig.cs
  tests/common/PlatformInfo.cs
  tests/common/TestRuntime.cs
  tests/common/mac/MacMain.cs
  tests/introspection/ApiAvailabilityTest.cs
  tests/introspection/ApiBaseTest.cs
  tests/introspection/ApiCMAttachmentTest.cs
  tests/introspection/ApiClassPtrTest.cs
  tests/introspection/ApiCoreImageFiltersTest.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/introspection/ApiFieldTest.cs
  tests/introspection/ApiFrameworkTest.cs
  tests/introspection/ApiPInvokeTest.cs
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/ApiSignatureTest.cs
  tests/introspection/ApiStructTest.cs
  tests/introspection/ApiTypeTest.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/CoreSelectorTest.cs
  tests/introspection/Mac/MacApiCtorInitTest.cs
  tests/introspection/Mac/MacApiFieldTest.cs
  tests/introspection/Mac/MacApiPInvokeTest.cs
  tests/introspection/Mac/MacApiProtocolTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/introspection/Mac/MacApiSignatureTest.cs
  tests/introspection/Mac/MacApiTypoTest.cs
  tests/introspection/Mac/MacApiWeakPropertyTest.cs
  tests/introspection/Mac/MacCoreImageFiltersTest.cs
  tests/introspection/iOS/AppDelegate.cs
  tests/introspection/iOS/iOSApiCtorInitTest.cs
  tests/introspection/iOS/iOSApiFieldTest.cs
  tests/introspection/iOS/iOSApiPInvokeTest.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/introspection/iOS/iOSApiSignatureTest.cs
  tests/introspection/iOS/iOSCoreImageFiltersTest.cs
  tools/autoformat.sh
Labels: not-notes-worthy

#16613 [tests] Remove a few duplicated package references.
  tests/bindings-test/dotnet/shared.csproj
  tests/bindings-test2/dotnet/shared.csproj
  tests/fsharplibrary/dotnet/shared.fsproj
Labels: not-notes-worthy

#16606 Unset the prerelease identifier.
  Make.config
Labels: not-notes-worthy

#16614 [release/7.0.1xx] Change to stable branding.
  Make.config
Labels: not-notes-worthy

#16601 [release/7.0.1xx] [DevOps] Update statuses urls for the new storage.
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: not-notes-worthy, backported

#16600 [release/6.0.4xx-xcode14.1] [DevOps] Update statuses urls for the new storage.
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: not-notes-worthy, backported

#16599 [xcode14.1] [DevOps] Update statuses urls for the new storage.
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: not-notes-worthy, backported

#16610 [dotnet] Show a better error when trying to launch an app using 'dotnet run' on Windows.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: not-notes-worthy

#16617 Switch maccore to track main and bump.
  mk/versions.mk
  mk/xamarin.mk
Labels: not-notes-worthy

#16619 [autoformat] Add the CoreFoundation framework.
  src/CoreFoundation/Architecture.cs
  src/CoreFoundation/CFAllocator.cs
  src/CoreFoundation/CFArray.cs
  src/CoreFoundation/CFBoolean.cs
  src/CoreFoundation/CFBundle.cs
  src/CoreFoundation/CFData.cs
  src/CoreFoundation/CFDataBuffer.cs
  src/CoreFoundation/CFDictionary.cs
  src/CoreFoundation/CFException.cs
  src/CoreFoundation/CFMachPort.cs
  src/CoreFoundation/CFMessagePort.cs
  src/CoreFoundation/CFMutableString.cs
  src/CoreFoundation/CFNetwork.cs
  src/CoreFoundation/CFNotificationCenter.cs
  src/CoreFoundation/CFPreferences.cs
  src/CoreFoundation/CFPropertyList.cs
  src/CoreFoundation/CFProxySupport.cs
  src/CoreFoundation/CFReadStream.cs
  src/CoreFoundation/CFRunLoop.cs
  src/CoreFoundation/CFSocket.cs
  src/CoreFoundation/CFStream.cs
  src/CoreFoundation/CFString.cs
  src/CoreFoundation/CFType.cs
  src/CoreFoundation/CFUrl.cs
  src/CoreFoundation/CFWriteStream.cs
  src/CoreFoundation/CGAffineTransformComponents.cs
  src/CoreFoundation/Dispatch.cs
  src/CoreFoundation/DispatchBlock.cs
  src/CoreFoundation/DispatchData.cs
  src/CoreFoundation/DispatchQueueSynchronizationContext.cs
  src/CoreFoundation/DispatchSource.cs
  src/CoreFoundation/OSLog.cs
  tools/autoformat.sh
Labels: not-notes-worthy

#16636 [release/7.0.1xx] [dotnet] Always use a four part VS component version
  dotnet/Makefile
Labels: backported

#16623 [dotnet/tools] Don't disable compact unwind info. Fixes #16546.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/common/CompilerFlags.cs
Labels: bug

#16635 [release/6.0.4xx-xcode14.1] [dotnet] Always use a four part VS component version
  dotnet/Makefile
Labels: backported

#16618 [DevOps] Rename the yaml-templates resources to match the MAUI repo.
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/publish-pr-html-results.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/common/checkout.yml
  tools/devops/automation/templates/common/setup.yml
  tools/devops/automation/templates/common/teardown.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/release/vs-insertion-prep.yml
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/sign-and-notarized/setup.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
  tools/devops/automation/vs-insertion.yml
Labels: not-notes-worthy

#16641 [release/7.0.1xx-xcode13.3] [DevOps] Update the version of the provisionator template to deal with the new storage.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16595 [DevOps] Update statuses urls for the new storage.
  tools/devops/automation/templates/main-stage.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: not-notes-worthy

#16622 [autoformat] Add xtro.
  tests/xtro-sharpie/AttributeHelpers.cs
  tests/xtro-sharpie/DeprecatedCheck.cs
  tests/xtro-sharpie/DesignatedInitializerCheck.cs
  tests/xtro-sharpie/DllImportCheck.cs
  tests/xtro-sharpie/EnumCheck.cs
  tests/xtro-sharpie/FieldCheck.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/Log.cs
  tests/xtro-sharpie/NullabilityCheck.cs
  tests/xtro-sharpie/ObjCInterfaceCheck.cs
  tests/xtro-sharpie/ObjCProtocolCheck.cs
  tests/xtro-sharpie/Program.cs
  tests/xtro-sharpie/ReleaseAttributeCheck.cs
  tests/xtro-sharpie/RequiresSuperCheck.cs
  tests/xtro-sharpie/Runner.cs
  tests/xtro-sharpie/SelectorCheck.cs
  tests/xtro-sharpie/SimdCheck.cs
  tests/xtro-sharpie/UIAppearanceCheck.cs
  tests/xtro-sharpie/VersionHelpers.cs
  tools/autoformat.sh
Labels: not-notes-worthy

#16642 [release/7.0.1xx-xcode14] [DevOps] Update the version of the provisionator template to deal with the new storage.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16626 [DevOps] Use the checkout template for the unified pipeline to work.
  tools/devops/automation/templates/common/checkout.yml
  tools/devops/automation/templates/loc-translations.yml
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/sign-and-notarized/setup.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
  tools/devops/automation/templates/windows/reserve-mac.yml
Labels: not-notes-worthy

#16643 [release/6.0.4xx] [DevOps] Update the version of the provisionator template to deal with the new storage.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16658 [DevOps] Fix value of yamlResourceName to use the new resource name.
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: not-notes-worthy

#16646 [7.0.1xx] Bump .NET 6 versions.
  Make.versions
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
Labels: not-notes-worthy

#16664 [release/6.0.4xx-xcode14.1] [CI] Go back to the stable bots
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
Labels: not-notes-worthy, backported

#16661 [CI] Go back to the stable bots
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
Labels: not-notes-worthy

#16612 [msbuild] Show an error when trying to build a binding project from Windows without a Mac connection.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: not-notes-worthy

#16663 [xcode14.1] [CI] Go back to the stable bots
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
Labels: not-notes-worthy, backported

#16644 [autoformat] Add the CoreGraphics framework.
  src/CoreGraphics/CGAffineTransform.cs
  src/CoreGraphics/CGBitmapContext.cs
  src/CoreGraphics/CGColor.cs
  src/CoreGraphics/CGColorConversionInfo.cs
  src/CoreGraphics/CGColorConverter.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGContext.cs
  src/CoreGraphics/CGContextPDF.cs
  src/CoreGraphics/CGDataConsumer.cs
  src/CoreGraphics/CGDataProvider.cs
  src/CoreGraphics/CGEnums.cs
  src/CoreGraphics/CGFont.cs
  src/CoreGraphics/CGFunction.cs
  src/CoreGraphics/CGGradient.cs
  src/CoreGraphics/CGImage.cs
  src/CoreGraphics/CGImageProperties.cs
  src/CoreGraphics/CGLayer.cs
  src/CoreGraphics/CGPDFArray.cs
  src/CoreGraphics/CGPDFContentStream.cs
  src/CoreGraphics/CGPDFDictionary.cs
  src/CoreGraphics/CGPDFDocument.cs
  src/CoreGraphics/CGPDFOperatorTable.cs
  src/CoreGraphics/CGPDFPage-2.cs
  src/CoreGraphics/CGPDFScanner.cs
  src/CoreGraphics/CGPDFStream.cs
  src/CoreGraphics/CGPDFString.cs
  src/CoreGraphics/CGPath.cs
  src/CoreGraphics/CGPattern.cs
  src/CoreGraphics/CGPdfTagType.cs
  src/CoreGraphics/CGShading.cs
  src/CoreGraphics/CGVector.cs
  tools/autoformat.sh
Labels: not-notes-worthy

#16634 [DevOps] Fix missed variables format.
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#16653 [DevOps] Do not use the output var from the azure step for the urls.
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: not-notes-worthy

#16676 [DevOps] Pass the yaml resource name since the default is not longer valid.
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: not-notes-worthy

#16691 [DevOps] Update the way we pass the token to the provisionator task.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy

#16649 [registrar] Deduplicate the code to compute the initialization method name for the generated static registrar code.
  tools/common/Application.cs
  tools/common/StaticRegistrar.cs
  tools/common/Target.cs
  tools/dotnet-linker/Steps/RegistrarStep.cs
  tools/mmp/driver.cs
  tools/mtouch/BuildTasks.mtouch.cs
  tools/mtouch/Target.mtouch.cs
Labels: not-notes-worthy

#16692 [release/6.0.4xx-xcode14.1] [DevOps] Update the way we pass the token to the provisionator task.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16688 Merge main into net8.0.
  src/CoreGraphics/CGAffineTransform.cs
  src/CoreGraphics/CGBitmapContext.cs
  src/CoreGraphics/CGColor.cs
  src/CoreGraphics/CGColorConversionInfo.cs
  src/CoreGraphics/CGColorConverter.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGContext.cs
  src/CoreGraphics/CGContextPDF.cs
  src/CoreGraphics/CGDataConsumer.cs
  src/CoreGraphics/CGDataProvider.cs
  src/CoreGraphics/CGEnums.cs
  src/CoreGraphics/CGFont.cs
  src/CoreGraphics/CGFunction.cs
  src/CoreGraphics/CGGradient.cs
  src/CoreGraphics/CGImage.cs
  src/CoreGraphics/CGImageProperties.cs
  src/CoreGraphics/CGLayer.cs
  src/CoreGraphics/CGPDFArray.cs
  src/CoreGraphics/CGPDFContentStream.cs
  src/CoreGraphics/CGPDFDictionary.cs
  src/CoreGraphics/CGPDFDocument.cs
  src/CoreGraphics/CGPDFOperatorTable.cs
  src/CoreGraphics/CGPDFPage-2.cs
  src/CoreGraphics/CGPDFScanner.cs
  src/CoreGraphics/CGPDFStream.cs
  src/CoreGraphics/CGPDFString.cs
  src/CoreGraphics/CGPath.cs
  src/CoreGraphics/CGPattern.cs
  src/CoreGraphics/CGPdfTagType.cs
  src/CoreGraphics/CGShading.cs
  src/CoreGraphics/CGVector.cs
  src/avfoundation.cs
  tools/autoformat.sh
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/main-stage.yml
  tools/devops/automation/templates/release/vs-insertion-prep.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy

#16694 [release/7.0.1xx] [DevOps] Update the way we pass the token to the provisionator task.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16693 [xcode14.1] [DevOps] Update the way we pass the token to the provisionator task.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/tests/build.yml
Labels: not-notes-worthy, backported

#16680 [DevOps] Use the project URI to calculate the project.
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/build/api-diff-process-results.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/common/clean.yml
  tools/devops/automation/templates/common/status.yml
  tools/devops/automation/templates/mac/build.yml
  tools/devops/automation/templates/sign-and-notarized/artifact-github-comment.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
  tools/devops/automation/templates/tests/build.yml
  tools/devops/automation/templates/tests/publish-html.yml
  tools/devops/automation/templates/tests/run-tests.yml
  tools/devops/automation/templates/tests/stage.yml
Labels: not-notes-worthy

#16686 [DevOps] Allow to pass a prefix to be used in the display names.
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#16696 [release/7.0.1xx] [devops] Continue if there are any errors gathering agent logs.
  tools/devops/automation/templates/common/mac-agent-logs.yml
Labels: not-notes-worthy, backported

#7561 [perf] Add unmanaged constraint to some APIs to allow pinning, and not manual GCHandle code
  src/AudioToolbox/AudioConverter.cs
  src/AudioToolbox/AudioFormatAvailability.cs
  tests/monotouch-test/AudioUnit/AudioUnitTest.cs
Labels: do-not-merge, not-notes-worthy

#16715 [DevOps] Checkout the yaml repos to fix an issue with the working dir.
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: not-notes-worthy

#16681 [apidiff] Fix comparison vs previous commit for .NET.
  tools/apidiff/Makefile
  tools/compare-commits.sh
Labels: skip-all-tests

#16737 [DevOps] Forward forgotten parameters.
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/windows/stage.yml
Labels: not-notes-worthy

#16736 [DevOps] Allow to pass extra dependencies for the build stage.
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#16624 [xcode14.1] [dotnet/tools] Don't disable compact unwind info. Fixes #16546.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/common/CompilerFlags.cs
Labels: bug, backported

#16765 [DevOps] Do not use ta vm for the pkgs upload due to its hdd size.
  tests/monotouch-test/CoreFoundation/SocketTest.cs
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
Labels: not-notes-worthy

#16690 Fix native watchOS app bundling when using newer Xcode 14 watchOS project. Fixes #16142.
  msbuild/Xamarin.iOS.Tasks/Tasks/ValidateAppBundleTaskBase.cs
Labels: community

#16773 [main] Fix native watchOS app bundling when using newer Xcode 14 watchOS project. Fixes #16142.
  msbuild/Xamarin.iOS.Tasks/Tasks/ValidateAppBundleTaskBase.cs
Labels: community, backported

#16782 [Foundation] Unify a few NSAttributedString functions.
  src/foundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/watchOS-UIKit.ignore
Labels: not-notes-worthy

#16788 [Actions] Add the action to perform a bump in the unified pipeline.
  .github/workflows/sdk-insertion-bump.yml
Labels: not-notes-worthy

#16416 [msbuild] Don't process assemblies over and over again in the UnpackLibraryResources target. Fixes #16377.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: enhancement

#16803 [Actions] Do not use the full commit. Just the head.
  .github/workflows/sdk-insertion-bump.yml
Labels: not-notes-worthy

#16702 [perf] [runtime] Optimize startup by using function pointers instead of delegates for our native->managed bridge.
  runtime/Delegates.cs.t4
  runtime/delegates.t4
  src/ObjCRuntime/Runtime.CoreCLR.cs
  src/ObjCRuntime/Runtime.cs
Labels: performance

#16835 [Localization] Change the Cron Job to trigger weekend scheduled build
  tools/devops/automation/build-cronjob.yml
Labels: not-notes-worthy

#16769 [release/7.0.1xx] [dotnet/tools] Don't disable compact unwind info. Fixes #16546.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/common/CompilerFlags.cs
Labels: bug, backported

#16770 [release/6.0.4xx-xcode14.1] [dotnet/tools] Don't disable compact unwind info. Fixes #16546.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tools/common/CompilerFlags.cs
Labels: bug, backported

#16846 Merge main into net8.0.
  src/CoreLocation/CLEnums.cs
  src/PassKit/PKEnums.cs
  src/PassKit/PKPaymentRequest.cs
  src/PassKit/PKShareablePassMetadata.cs
  src/PdfKit/PdfAnnotation.cs
  src/PdfKit/PdfCompat.cs
  src/Photos/Enums.cs
  src/Photos/PHCompat.cs
  src/Photos/PHFetchResult.cs
  src/Photos/PHPhotoLibrary.cs
  src/PhotosUI/PHEnums.cs
  src/PrintCore/Defs.cs
  src/PrintCore/PrintCore.cs
  src/QTKit/QTCompat.cs
  src/QuickLookUI/QLPreviewPanel.cs
  src/ReplayKit/RPBroadcastConfiguration.cs
  src/ReplayKit/RPEnums.cs
  src/SafariServices/SSEnums.cs
  src/ScreenCaptureKit/SCContentFilter.cs
  src/ScriptingBridge/Enums.cs
  src/ScriptingBridge/SBApplication.cs
  src/SearchKit/SearchKit.cs
  src/avfoundation.cs
  src/coregraphics.cs
  src/generator-enums.cs
  src/generator.cs
  src/watchkit.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_watchOS.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_watchOS_WatchKitApp.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/GeneratePlistTaskTests/GeneratePlistTaskTests_watchOS_WatchKitExtension.cs
  tools/autoformat.sh
  tools/devops/automation/build-cronjob.yml
Labels: not-notes-worthy

#16852 [xcode14.1] [mono] Bump mono to match android
  mk/mono.mk
Labels: notes-mention, backported

#16851 [mono] Bump mono to match android
  mk/mono.mk
Labels: notes-mention

#16832 [release/6.0.4xx-xcode14.1] [msbuild] Partial revert of ad8cdb3
  msbuild/Makefile
Labels: not-notes-worthy, backported

#16879 [dotnet-linker] Only enable ForceLoad for native binding libraries if that's actually requested in the binding library. Fixes #16861.
  tools/dotnet-linker/Steps/ExtractBindingLibrariesStep.cs
Labels: bug

#16862 [msbuild] Fix parsing -gcc_flags when the value is the next argument. Fixes #16861.
  msbuild/Xamarin.MacDev.Tasks/Tasks/ParseBundlerArgumentsTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ParseBundlerArgumentsTests.cs
Labels: bug

#16900 [xcode14.1] Updated Xamarin.Messaging to 1.8.49
  msbuild/Directory.Build.props
Labels: backported

#16901 [release/7.0.1xx] Updated Xamarin.Messaging to 1.8.49
  msbuild/Directory.Build.props
Labels: backported

#16902 [release/6.0.4xx-xcode14.1] Updated Xamarin.Messaging to 1.8.49
  msbuild/Directory.Build.props
Labels: backported

#16909 [Localization] Set OneLocBuild Task to not delete Lego Branch
  tools/devops/automation/templates/loc-translations.yml
Labels: not-notes-worthy
