Repository dotnet/macios, pull requests merged in 2022-01, with the labels that each got.

#13629 [hotrestart] Fixed MSBuild outputs when using $(AppBundleManifest)
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: not-notes-worthy

#13644 [Metal] Exposing Selectors in iOS. Fixes #12648
  src/Metal/MTLRenderCommandEncoder.cs
Labels: enhancement

#13650 Ensure we remotely copy all project pdbs and not only the main app one
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy

#13651 [release/6.0.2xx-preview12] Ensure we remotely copy all project pdbs and not only the main app one
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets
Labels: not-notes-worthy, backported

#13653 [CI] Fix mac tests yaml error
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#13658 Prepare for NET6 attribute conversion with hand fixes
  src/AVKit/Enums.cs
  src/Foundation/Enum.cs
  src/avkit.cs
  src/foundation.cs
Labels: not-notes-worthy

#13631 [VideoToolbox] Add a VTCompressionSession.EncodeFrame overload that takes a CVImageBuffer instead of a handle to one.
  src/VideoToolbox/VTCompressionSession.cs
  tests/monotouch-test/VideoToolbox/VTCompressionSessionTests.cs
Labels: not-notes-worthy, run-dotnet-tests

#13663 Localized file check-in by OneLocBuild Task: Build definition ID 14411: Build ID 5607500
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
Labels: not-notes-worthy

#13660 [CI] Use the correct dependency variable.
  tools/devops/automation/templates/mac/stage.yml
Labels: not-notes-worthy

#13657 [CI] Fix device tests
  tests/xharness/MacFlavorsExtensions.cs
  tools/devops/automation/templates/common/publish-html.yml
  tools/devops/automation/templates/devices/build.yml
  tools/devops/automation/templates/devices/run-tests.yml
  tools/devops/automation/templates/devices/stage.yml
Labels: not-notes-worthy

#13662 [CI] Allow to retrieve the logs of the agent.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/common/mac-agent-logs.yml
Labels: not-notes-worthy

#13666 [ObjCRuntime] Fix the DisposableObject.Owns property to return the correct value. Fixes #13646.
  src/ObjCRuntime/DisposableObject.cs
  tests/monotouch-test/AudioToolbox/AudioConverterTest.cs
  tests/monotouch-test/ObjCRuntime/DisposableObjectTest.cs
Labels: bug

#13661 [NET 6 Attribute Conversion] ARKit
  src/ARKit/ARSkeleton.cs
Labels: not-notes-worthy

#13667 [CI] Upload the agent logs as an artifact.
  tools/devops/automation/templates/common/mac-agent-logs.yml
Labels: not-notes-worthy

#13670 [CI] Add missing env.
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#13671 [CI] Fix comment aligment and add a warning sign.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#13675 [dotnet] Update breaking changes documentation to talk about nint/nuint.
  dotnet/BreakingChanges.md
Labels: not-notes-worthy

#13682 [d17-1] [AudioUnit] Create a GCHandle when AudioUnit.SetInputCallback is called. Fixes #13637.
  src/AudioUnit/AudioUnit.cs
  tests/monotouch-test/AudioToolbox/AudioUnitTest.cs
Labels: bug, backported

#13687 [d17-1] [CI] Upload the agent logs as an artifact.
  tools/devops/automation/templates/common/mac-agent-logs.yml
Labels: not-notes-worthy, backported

#13590 Add cecil test for verifying obsoleted apis
  tests/cecil-tests/Helper.cs
  tests/cecil-tests/ObsoleteTest.cs
  tests/common/Configuration.cs
Labels: not-notes-worthy, run-cecil-tests

#13689 [release/6.0.2xx-preview12] Include Broker satellite assemblies to the sign list
  dotnet/Workloads/SignList.xml
Labels: not-notes-worthy, backported

#13690 [release/6.0.2xx-preview12] [ObjCRuntime] Fix the DisposableObject.Owns property to return the correct value. Fixes #13646.
  src/ObjCRuntime/DisposableObject.cs
  tests/monotouch-test/AudioToolbox/AudioConverterTest.cs
  tests/monotouch-test/ObjCRuntime/DisposableObjectTest.cs
Labels: bug, backported

#13691 [release/6.0.2xx-preview12] [AudioUnit] Create a GCHandle when AudioUnit.SetInputCallback is called. Fixes #13637.
  src/AudioUnit/AudioUnit.cs
  tests/monotouch-test/AudioToolbox/AudioUnitTest.cs
Labels: bug, backported

#13674 [CI] Clean the WriteDiff function to follow the pwsh style.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#13685 [xharness] Bump timeout for the .NET tests to 3 hours. Fixes #xamarin/maccore@2538.
  tests/xharness/Jenkins/Jenkins.cs
Labels: not-notes-worthy

#13676 [msbuild] Add helpful comment about unused property
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CodesignTaskBase.cs
Labels: not-notes-worthy

#13679 [NSSecureCoding] Enable nullability and a few other code improvements.
  src/Foundation/NSSecureCoding.cs
Labels: not-notes-worthy

#13673 [AudioUnit] Create a GCHandle when AudioUnit.SetInputCallback is called. Fixes #13637.
  src/AudioUnit/AudioUnit.cs
  tests/monotouch-test/AudioToolbox/AudioUnitTest.cs
Labels: bug

#13681 [Foundation] Remove the NSObject.[MonoTouchAssembly|MonoMacAssembly] fields in .NET.
  src/Foundation/NSObject.iOS.cs
  src/Foundation/NSObject.mac.cs
Labels: not-notes-worthy, run-dotnet-tests

#13684 [CoreAnimation] Rename CATransform3D's fields to follow standard naming conventions for .NET.
  src/CoreAnimation/CATransform3D.cs
  src/SceneKit/SCNMatrix4.cs
  tests/monotouch-test/ObjCRuntime/TrampolineTest.cs
  tests/test-libraries/testgenerator.cs
Labels: not-notes-worthy, run-dotnet-tests, breaking-changes

#13672 [CI] Refactor code out to a function.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#13668 [coregraphics] Fix some names for the NET profile
  src/CoreGraphics/CGColorConversionInfo.cs
  src/CoreGraphics/CGColorConverter.cs
  src/CoreGraphics/CGColorSpace.cs
  src/CoreGraphics/CGEvent.cs
  src/CoreGraphics/CGGeometry.cs
  src/CoreGraphics/CGPDFArray.cs
  tests/introspection/ApiCMAttachmentTest.cs
  tests/monotouch-test/CoreGraphics/ColorConversionInfoTest.cs
  tests/monotouch-test/CoreGraphics/ColorSpaceTest.cs
Labels: enhancement, community

#13694 [AudioToolbox] Use unsafe code to marshal in/out arrays. Fixes #xamarin/maccore@2537.
  src/AudioToolbox/AudioFile.cs
Labels: not-notes-worthy, run-dotnet-tests

#13698 [CI] Invert if to workaround a bad variable expansion.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/mac/build.yml
Labels: not-notes-worthy

#13705 [Foundation] Make all NSMetadataItem properties nullable for .NET.
  src/Foundation/NSMetadataItem.cs
Labels: not-notes-worthy, run-dotnet-tests

#13696 [AppKit] Update NSWindowStyle deprecations according to headers.
  src/AppKit/Enums.cs
  tests/xtro-sharpie/Helpers.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-AppKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/common-AppKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13688 Include Broker satellite assemblies to the sign list
  dotnet/Workloads/SignList.xml
Labels: not-notes-worthy

#13706 [Foundation] Rename the NSLinguisticTagUnit enum to NSLinguisticTag in .NET.
  src/Foundation/Enums.cs
  src/foundation.cs
  tests/monotouch-test/Foundation/NSLinguisticAnalysisTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13711 [CI] Refactor the artifacts parsing.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#13714 Bump mono.
  mk/mono.mk
Labels: bug

#13713 [Foundation] Remove the NSDateComponentsWrappingBehavior in .NET.
  src/Foundation/Enum.cs
  src/foundation.cs
  tests/monotouch-test/Foundation/CalendarTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13695 [SceneKit] Make SCNMatrix4 column-major in .NET. Fixes #4652.
  dotnet/BreakingChanges.md
  src/SceneKit/SCNMatrix4.cs
  src/SceneKit/SCNMatrix4_dotnet.cs
  src/frameworks.sources
  tests/monotouch-test/SceneKit/SCNMatrixTest.cs
Labels: breaking-change, not-notes-worthy, run-dotnet-tests

#13707 [AppKit/Foundation] Use NSUnderlineStyle from the Foundation namespace everywhere.
  src/AppKit/Enums.cs
  src/Foundation/Enum.cs
Labels: not-notes-worthy, run-dotnet-tests

#13717 [maccore] Bump maccore to ease submission tests
  mk/xamarin.mk
Labels: not-notes-worthy

#13718 [CoreData] Move CoreData into the .NET age.
  src/CoreData/Obsolete.cs
  src/coredata.cs
  src/foundation.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/monotouch-test/CoreData/FetchedResultsControllerTest.cs
  tests/monotouch-test/CoreData/ManagedObjectModelTest.cs
Labels: breaking-change, not-notes-worthy, run-dotnet-tests

#13716 [NET 6 Attribute Conversion] AddressBookUI
  src/AddressBookUI/ABAddressFormatting.cs
  src/AddressBookUI/ABNewPersonViewController.cs
  src/AddressBookUI/ABPeoplePickerNavigationController.cs
  src/AddressBookUI/ABPersonViewController.cs
  src/AddressBookUI/ABUnknownPersonViewController.cs
  src/AddressBookUI/DisplayedPropertiesCollection.cs
Labels: not-notes-worthy, run-dotnet-tests

#13710 [NET 6 Attribute Conversion] AVKit
  src/AVKit/Enums.cs
Labels: run-docs-tests, not-notes-worthy

#13726 [d17-1] Bump mono.
  mk/mono.mk
Labels: bug, backported

#13741 [Foundation] Abstractify protocol members in .NET.
  src/foundation.cs
  tests/monotouch-test/UIKit/UIDragDropSessionExtensionsTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13740 [Foundation] Always use the good version of NSTextLayoutEnumerateLineFragments/NSTextLayoutEnumerateEnclosingRects in .NET.
  src/xkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13738 [Intents] Fix optional/abstract for protocols in .NET.
  src/intents.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Intents.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13737 [CGAffineTransform] Rename public fields in .NET to follow Apple and managed naming conventions. Fixes #13494.
  src/CoreGraphics/CGAffineTransform.cs
  src/CoreImage/CISampler.cs
  tests/monotouch-test/CoreGraphics/AffineTransformTest.cs
Labels: run-dotnet-tests

#13736 [AppKit] Make NSScrollView.DocumentView be an NSView in .NET. Fixes #8198.
  src/appkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13735 [Foundation] Remove conditional code that wasn't conditional for NSValueTransformer.
  src/foundation.cs
Labels: not-notes-worthy, run-dotnet-tests

#13733 [Foundation] Rename NSURLAuthenticationChallengeSender in .NET to follow our naming guidelines.
  src/foundation.cs
Labels: not-notes-worthy, run-dotnet-tests

#13732 [Foundation] Replace broken version of NSRegularExpression.GetMatches with a working version for .NET.
  src/foundation.cs
  tests/monotouch-test/Foundation/RegularExpressionTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13731 [Intents] Rename several Confirm* methods to Confirm in .NET.
  src/intents.cs
Labels: not-notes-worthy, run-dotnet-tests

#13729 [Intents] Make use of 'BindAs' to improve a few bindings for .NET.
  src/intents.cs
Labels: not-notes-worthy, run-dotnet-tests

#13728 [Foundation] Remove a few broken NSExpression overloads in .NET.
  src/foundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-Foundation.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-Foundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Foundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-Foundation.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13727 [Intents] Remove Intents types from macOS in .NET that were added by mistake.
  src/Intents/INGetCarPowerLevelStatusIntentResponse.cs
  src/Intents/INMessageAttributeOptionsResolutionResult.cs
  src/Intents/INMessageAttributeResolutionResult.cs
  src/Intents/INSearchCallHistoryIntent.cs
  src/Intents/INStartWorkoutIntent.cs
  src/intents.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Intents.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13724 [Intents] Remove obsolete manual Intents bindings from .NET.
  src/Intents/INCarAirCirculationModeResolutionResult.watchOS.cs
  src/Intents/INCarAudioSourceResolutionResult.watchOS.cs
  src/Intents/INCarDefrosterResolutionResult.watchOS.cs
  src/Intents/INCarSeatResolutionResult.watchOS.cs
  src/Intents/INCompat.cs
  src/Intents/INRadioTypeResolutionResult.watchOS.cs
  src/Intents/INRelativeReferenceResolutionResult.watchOS.cs
  src/Intents/INRelativeSettingResolutionResult.watchOS.cs
Labels: not-notes-worthy, run-dotnet-tests

#13723 [AppKit] Rename NSTableView.DragImageForRowsWithIndexestableColumnseventoffset to NSTableView.DragImageForRows in .NET.
  src/appkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13719 [Foundation] Remove some obsolete NSObject API in .NET
  src/foundation.cs
  tests/monotouch-test/Foundation/FileCoordinatorTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13730 [AudioUnit] Improve a few AudioUnit methods to return the error code.
  src/AudioUnit/AudioUnit.cs
  tests/monotouch-test/AudioToolbox/AudioUnitTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13749 [Intents] Misc API updates for .NET.
  src/intents.cs
Labels: not-notes-worthy, run-dotnet-tests

#13751 [Intents] The INPersonRelationship enum was added to macOS 12.1 according to the documentation.
  src/intents.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Intents.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13750 [Foundation] Fix signature for NSLayoutConstraint.[First|Second]Anchor in .NET.
  src/Foundation/NSLayoutConstraint.cs
  src/xkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13752 [Intents] Remove INSetMessageAttributeIntentResponseCode from macOS in .NET.
  src/intents.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-Intents.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13763 [Foundation] Fix a few method names to follow naming guidelines for .NET.
  src/foundation.cs
  tests/monotouch-test/Foundation/NSKeyedUnarchiverTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13753 [Foundation] Fix the NSMetadataItem.UbiquitousItemDownloadingStatus property name for .NET.
  src/Foundation/NSMetadataItem.cs
  tests/monotouch-test/Foundation/NSMetadataItem.cs
Labels: not-notes-worthy, run-dotnet-tests

#13758 [Foundation] Fix NSMutableCharacterSet.[Add|Remove]Characters signature for .NET.
  src/foundation.cs
Labels: not-notes-worthy, run-dotnet-tests

#13756 [Foundation] Use a better version of NSItemProviderCompletionHandler for .NET.
  src/foundation.cs
Labels: not-notes-worthy, run-dotnet-tests

#13757 [tests] Simplify mmptest a bit by using existing mechanisms to create frameworks.
  tests/common/mac/ProjectTestHelpers.cs
  tests/mmptest/src/BindingProjectNoEmbeddingTests.cs
  tests/mmptest/src/CodeStrippingTests.cs
  tests/test-libraries/frameworks/Makefile
Labels: not-notes-worthy

#13762 [introspection] Add exception according to recent changes in .NET API.
  tests/introspection/ApiSelectorTest.cs
Labels: run-old-simulator-tests, not-notes-worthy, run-dotnet-tests

#13760 [Foundation] Remove the default constructor for NSMetadataItem in .NET (it's broken)
  src/foundation.cs
Labels: not-notes-worthy, run-dotnet-tests

#13759 [Foundation] Remove compat overloads of methods taking a NSUrlSessionPendingTasks delegate in .NET.
  src/foundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13765 [Intents] Adjust initial introduction to INPersonRelationship in macOS.
  src/intents.cs
Labels: not-notes-worthy

#13745 [tests] Disable attribute duplication check
  tests/introspection/ApiAvailabilityTest.cs
Labels: not-notes-worthy

#13744 [CI] Add missing warning and list element.
  tools/devops/automation/scripts/GitHub.psm1
Labels: not-notes-worthy

#13743 [CI] Do not add not needed data in the device test comments.
  tools/devops/automation/scripts/GitHub.psm1
  tools/devops/automation/templates/common/publish-html.yml
Labels: not-notes-worthy

#13769 [AppKit] Fix atrocious API naming in NSTextFinderClient in .NET.
  src/appkit.cs
  tests/monotouch-test/AppKit/NSTextFinder.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13782 [UIKit] Add missing nullability fixes #13683
  src/uikit.cs
Labels: enhancement

#13761 [CFNetwork] Move the CFHost and CFHTTP* types to the CFNetwork namespace in .NET.
  dotnet/BreakingChanges.md
  src/CFNetwork/CFHTTPAuthentication.cs
  src/CFNetwork/CFHTTPMessage.cs
  src/CFNetwork/CFHTTPStream.cs
  src/CFNetwork/CFHost.cs
  src/CoreFoundation/CFProxySupport.cs
  src/CoreFoundation/CFStream.cs
  src/Foundation/NSStream.cs
  src/System.Net.Http/CFContentStream.cs
  src/System.Net.Http/CFNetworkHandler.cs
  src/cfnetwork.cs
  tests/introspection/ApiCMAttachmentTest.cs
  tests/introspection/ApiFrameworkTest.cs
  tests/linker/ios/link sdk/LinkSdkRegressionTest.cs
  tests/monotouch-test/CoreFoundation/ProxyTest.cs
  tests/monotouch-test/CoreServices/HttpMessageTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-CFNetwork.ignore
  tests/xtro-sharpie/api-annotations-dotnet/common-CoreServices.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13780 [TVMLKit] Adopt XAMCORE_4_0 changes in .NET.
  src/tvmlkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13766 [Foundation] Rename parameter to NSItemProviderCompletionHandler to be more descriptive.
  src/foundation.cs
Labels: not-notes-worthy

#13770 [AppKit] Update NSSpellingState to be a native enum in .NET, according to current AppKit headers.
  src/AppKit/XEnums.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13773 [WebKit] Adopt XAMCORE_4_0 changes in .NET.
  src/WebKit/DomNode.cs
  src/WebKit/Enums.cs
  src/webkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13774 [CoreMidi] Fix availability for MidiNetworkConnectionPolicy.
  src/CoreMidi/MidiServices.cs
  src/coremidi.cs
Labels: not-notes-worthy, run-dotnet-tests

#13775 [Vision] Adopt XAMCORE_4_0 changes in .NET.
  src/Vision/VNCompat.cs
  src/vision.cs
Labels: not-notes-worthy, run-dotnet-tests

#13779 [AppKit] Fix NSRulerView.MeasurementUnits to be a BindAs property for NSRulerViewUnits in .NET
  src/appkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13781 [AppKit] Don't add NSTextInput.DoCommandBySelector in .NET.
  src/appkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13764 [src] Fix optional/required protocol members in .NET.
  src/AVFoundation/AVAssetDownloadUrlSession.cs
  src/appkit.cs
  src/avfoundation.cs
  src/carplay.cs
  src/coreimage.cs
  src/corenfc.cs
  src/fileprovider.cs
  src/gamekit.cs
  src/gameplaykit.cs
  src/intentsui.cs
  src/metrickit.cs
  src/modelio.cs
  src/passkit.cs
  src/pushkit.cs
  src/quicklookUI.cs
  src/scenekit.cs
  src/uikit.cs
  src/watchconnectivity.cs
  src/webkit.cs
  tests/monotouch-test/AppKit/NSAppearance.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-GameKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-MetricKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-PassKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/common-AVFoundation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/common-CoreImage.ignore
  tests/xtro-sharpie/api-annotations-dotnet/common-GameKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/common-GameplayKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/common-ModelIO.ignore
  tests/xtro-sharpie/api-annotations-dotnet/common-PassKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/common-SceneKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/common-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CarPlay.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreNFC.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreNFC.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-FileProvider.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-GameKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-IntentsUI.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetricKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PushKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-WatchConnectivity.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-GameKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-QuickLookUI.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-SceneKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-WebKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13785 [CI] Allow to run macOS without devices.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#13709 [NET 6 Attribute Conversion] AVFoundation
  src/AVFoundation/AVAudioConverterPrimeInfo.cs
  src/AVFoundation/AVAudioRecorder.cs
  src/AVFoundation/AVAudioSettings.cs
  src/AVFoundation/AVBeatRange.cs
  src/AVFoundation/AVCaptureConnection.cs
  src/AVFoundation/AVCaptureVideoPreviewLayer.cs
  src/AVFoundation/AVPlayerItem.cs
  src/AVFoundation/AVPlayerLayer.cs
  src/AVFoundation/AVPlayerViewController.cs
  src/AVFoundation/AVTypes.cs
  src/AVFoundation/AVVideoSettings.cs
  src/AVFoundation/AudioRendererWasFlushedAutomaticallyEventArgs.cs
  src/AVFoundation/Enums.cs
  src/AVFoundation/Events.cs
Labels: do-not-merge, not-notes-worthy, run-dotnet-tests

#13786 [SpriteKit] Adopt XAMCORE_4_0 changes in .NET.
  src/SpriteKit/SKAction.cs
  src/SpriteKit/SKUniform.cs
  src/spritekit.cs
  tests/monotouch-test/SpriteKit/UniformTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-SpriteKit.todo
Labels: not-notes-worthy, run-dotnet-tests

#13783 [StoreKit] Adopt XAMCORE_4_0 changes in .NET.
  src/StoreKit/Enums.cs
  src/storekit.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-StoreKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-StoreKit.ignore
  tests/xtro-sharpie/iOS-StoreKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13778 [VideoSubscriberAccount] Adopt XAMCORE_4_0 changes in .NET.
  src/videosubscriberaccount.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-VideoSubscriberAccount.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13725 [msbuild] Unify some of the codesign dependency properties.
  msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
  tests/dotnet/UnitTests/BundleStructureTest.cs
Labels: not-notes-worthy

#13787 [ScriptingBridge] Improve API and add nullability.
  src/ScriptingBridge/SBApplication.cs
  src/scriptingbridge.cs
  tests/monotouch-test/ScriptingBridge/SBApplicationTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-ScriptingBridge.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13703 Add NullAllowed to NSRunningApplication
  src/appkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: enhancement, backported

#13790 [coregraphics] Remove _really_ outdated status file
  src/CoreGraphics/status
Labels: not-notes-worthy

#13789 [CoreText] Adopt XAMCORE_4_0 changes in .NET.
  src/CoreText/CTParagraphStyle.cs
  src/CoreText/CTRunDelegate.cs
  src/CoreText/CTTypesetterOptionKeyCompat.cs
  src/coretext.cs
  tests/monotouch-test/CoreText/RunTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13798 [HomeKit] Add missing availability attributes for a few HomeKit types for Mac Catalyst.
  src/homekit.cs
Labels: not-notes-worthy

#13799 [MessageUI] Fix enum sizes in .NET.
  src/MessageUI/MessageUI.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MessageUI.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13776 [Foundation] Adopt a better name/signature for numerous Foundation API in .NET.
  src/xkit.cs
  tests/introspection/ApiSelectorTest.cs
  tests/introspection/Mac/MacApiSelectorTest.cs
  tests/monotouch-test/AppKit/NSLayoutManagerTests.cs
  tests/monotouch-test/UIKit/NSTextStorageTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13801 [SafariServices] Adopt XAMCORE_4_0 changes in .NET.
  src/SafariServices/SSEnums.cs
  src/safariservices.cs
  tests/monotouch-test/SafariServices/ReadingListTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-SafariServices.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13797 [CI] Bootstrap dotnet.
  tools/devops/automation/templates/devices/run-tests.yml
Labels: not-notes-worthy

#13809 [CI] Allow to optionally skip API diff.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#13810 [CI] Call agent cleanser on device bots.
  tools/devops/automation/templates/devices/build.yml
Labels: not-notes-worthy

#13806 [SceneKit] Adopt XAMCORE_4_0 changes in .NET.
  src/SceneKit/SCNCompat.cs
  src/SceneKit/SCNNode.cs
  src/SceneKit/SCNPhysicsShape.cs
  src/scenekit.cs
  tests/monotouch-test/SceneKit/ActionTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13805 [msbuild] Copy all the files in a framework to the Mac for the FilterStaticFrameworks task. Fixes #13804.
  msbuild/Xamarin.MacDev.Tasks/Tasks/FilterStaticFrameworks.cs
Labels: not-notes-worthy

#13815 [ReplayKit] Adopt XAMCORE_4_0 change in .NET.
  src/replaykit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13819 [CI] Parallel api diff
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#13784 [NET 6 Attribute Conversion] Appkit
  src/AppKit/NSAccessibility.cs
  src/AppKit/NSBezierPath.cs
  src/AppKit/NSButton.cs
  src/AppKit/NSCollectionLayoutAnchor.cs
  src/AppKit/NSCollectionView.cs
  src/AppKit/NSCollectionViewDelegate.cs
  src/AppKit/NSFont.cs
  src/AppKit/NSGraphics.cs
  src/AppKit/NSLayoutManager.cs
  src/AppKit/NSSegmentedControl.cs
  src/AppKit/NSSlider.cs
  src/AppKit/NSTextContainer.cs
  src/AppKit/NSWorkspace.cs
Labels: not-notes-worthy, run-dotnet-tests

#13820 [UIKit] Adopt XAMCORE_4_0 changes in .NET.
  src/UIKit/Compat.cs
  src/UIKit/NSLayoutManager.cs
  src/UIKit/UIAccessibility.cs
  src/UIKit/UIActionSheet.cs
  src/UIKit/UIEnums.cs
  src/UIKit/UIImagePickerController.cs
  src/UIKit/UITraitCollection.cs
  src/UIKit/UIViewController.cs
  src/UIKit/UIWindow.cs
  src/uikit.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-UIKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13822 [QuickLookThumbnailing] Adopt XAMCORE_4_0 changes in .NET.
  src/quicklookthumbnailing.cs
Labels: not-notes-worthy, run-dotnet-tests

#13818 [NET 6 Attribute Conversion] CoreImage
  src/CoreImage/CIContext.cs
  src/CoreImage/CIDetectorOptions.cs
  src/CoreImage/CIFilter.cs
  src/CoreImage/CIImage.cs
Labels: not-notes-worthy, run-dotnet-tests

#13813 [NET 6 Attribute Conversion] CoreData
  src/CoreData/NSEntityDescription.cs
Labels: run-dotnet-tests

#13792 [NET 6 Attribute Conversion] AuthenticationServices
  src/AuthenticationServices/PublicPrivateKeyAuthentication.cs
Labels: not-notes-worthy, run-dotnet-tests

#13794 [NET 6 Attribute Conversion] CFNetwork
  src/CFNetwork/CFHTTPMessage.cs
  src/CFNetwork/CFHTTPStream.cs
  src/CFNetwork/CFHost.cs
Labels: do-not-merge, not-notes-worthy, run-dotnet-tests

#13791 [NET 6 Attribute Conversion] Autotoolbox
  src/AudioToolbox/AudioFile.cs
  src/AudioToolbox/AudioFormat.cs
  src/AudioToolbox/AudioQueue.cs
  src/AudioToolbox/AudioSession.cs
  src/AudioToolbox/AudioSessions.cs
  src/AudioToolbox/AudioToolbox.cs
  src/AudioToolbox/AudioType.cs
  src/AudioToolbox/Enums.cs
  src/AudioToolbox/SystemSound.cs
Labels: not-notes-worthy, run-dotnet-tests

#13821 [AppKit/UIKit] Remove several obsolete API (due to bad naming) in .NET.
  src/AppKit/NSLayoutManager.cs
  src/xkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13796 [NET 6 Attribute Conversion] Compression
  src/Compression/Compression.cs
  src/Compression/CompressionStreamStruct.cs
Labels: not-notes-worthy, run-dotnet-tests

#13812 [NET 6 Attribute Conversion] CoreAnimation
  src/CoreAnimation/CADefs.cs
  src/CoreAnimation/CAFrameRateRange.cs
  src/CoreAnimation/CALayer.cs
  src/CoreAnimation/CATransform3D.cs
Labels: not-notes-worthy, run-dotnet-tests

#13823 [QuickLookUI] Adopt XAMCORE_4_0 change in .NET.
  src/quicklookUI.cs
Labels: not-notes-worthy, run-dotnet-tests

#13807 [msbuild] Share the logic to sign app extensions between iOS and Mac.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-dotnet-tests

#13827 [AudioComponentDescription] Strong-type the ComponentSubType field in .NET.
  src/AudioUnit/AudioComponentDescription.cs
  tests/monotouch-test/AudioUnit/AUAudioUnitFactoryTest.cs
  tests/monotouch-test/AudioUnit/AUGraphTestMac.cs
  tests/monotouch-test/AudioUnit/AudioUnit.cs
  tests/monotouch-test/AudioUnit/AudioUnitTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13841 [CI] Increase timeouts when reporting a device result.
  tools/devops/automation/templates/common/publish-html.yml
Labels: not-notes-worthy

#13835 [CI] Unify all the setup steps in a template.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/common/setup.yml
  tools/devops/automation/templates/devices/build.yml
Labels: not-notes-worthy

#13419 [CI] Use old signing when running on a PR.
  tools/devops/automation/templates/build/sign-and-notarized.yml
Labels: not-notes-worthy

#13846 ResolveNativeReferences task pass the Xcframework NativeReference metadata to the _FrameworkNativeReference
  msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveNativeReferencesBase.cs
Labels: bug

#13858 [CI] Use correct pwd for the device bots.
  tools/devops/automation/build-pipeline.yml
Labels: not-notes-worthy

#13859 [CI] Unify the cleaning of the bots.
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/common/teardown.yml
  tools/devops/automation/templates/devices/build.yml
Labels: not-notes-worthy

#13831 [mobilecoreservices] Modernize UTType
  src/MobileCoreServices/UTType.cs
  tests/monotouch-test/MobileCoreServices/UTTypeTest.cs
Labels: community, not-notes-worthy

#13826 [QuickLook] Adopt XAMCORE_4_0 changes in .NET.
  src/quicklook.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-QuickLook.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-QuickLook.ignore
Labels: not-notes-worthy, run-dotnet-tests

#13852 [MetalPerformanceShaders] Adopt XAMCORE_4_0 changes in .NET.
  src/MetalPerformanceShaders/MPSCompat.cs
  src/MetalPerformanceShaders/MPSEnums.cs
  src/MetalPerformanceShaders/MPSImageHistogram.cs
  src/MetalPerformanceShaders/MPSMatrixDescriptor.cs
  src/metalperformanceshaders.cs
Labels: not-notes-worthy, run-dotnet-tests

#13844 [msbuild] Share the logic to CalculateCodesignAppBundleInputs between iOS and Mac.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets
Labels: not-notes-worthy, run-dotnet-tests

#13842 [NetworkExtension] Adopt XAMCORE_4_0 changes in .NET.
  src/NetworkExtension/NECompat.cs
  src/networkextension.cs
  tests/monotouch-test/NetworkExtension/VpnManagerTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13833 [PassKit] Adopt XAMCORE_4_0 changes in .NET.
  src/PassKit/PKCompat.cs
  src/passkit.cs
  tests/monotouch-test/PassKit/PassTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13832 [NotificationCenter] Adopt XAMCORE_4_0 changes in .NET.
  src/notificationcenter.cs
Labels: not-notes-worthy, run-dotnet-tests

#13830 [Photos] Adopt XAMCORE_4_0 changes in .NET.
  src/Photos/Enums.cs
  src/Photos/PHCompat.cs
  src/photos.cs
  tests/monotouch-test/Photos/LivePhotoEditingContextTest.cs
Labels: not-notes-worthy, run-dotnet-tests

#13828 [PdfKit] Adopt XAMCORE_4_0 changes in .NET.
  src/PdfKit/Enums.cs
  src/PdfKit/PdfAnnotation.cs
  src/PdfKit/PdfCompat.cs
  src/pdfkit.cs
Labels: not-notes-worthy, run-dotnet-tests

#13825 [PhotosUI] Adopt XAMCORE_4_0 change in .NET.
  src/photosui.cs
Labels: not-notes-worthy, run-dotnet-tests

#13860 [CI] Improve the upload script to help with SBOM
  tools/devops/automation/templates/build/upload-azure.yml
Labels: not-notes-worthy

#13868 [CI] Allow to skip ESRP to help speed up the CI testing.
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/templates/build/build.yml
  tools/devops/automation/templates/build/sign-and-notarized.yml
  tools/devops/automation/templates/build/stage.yml
Labels: not-notes-worthy

#13869 [CI] Fix a broken CI when we skip the api diff.
  tools/devops/automation/templates/build/download-artifacts.yml
  tools/devops/automation/templates/build/publish-html.yml
  tools/devops/automation/templates/build/stage.yml
  tools/devops/automation/templates/build/upload-vsdrops.yml
Labels: not-notes-worthy

#13572 Fix bgen CLI command for macos net6 TFM
  src/btouch.cs
Labels: notes-mention

#13865 [NET 6 Attribute Conversion] CoreServices
  src/CoreServices/FSEvents.cs
  src/CoreServices/LaunchServices.cs
Labels: not-notes-worthy, run-dotnet-tests

#13863 [NET 6 Attribute Conversion] CoreMidi
  src/CoreMidi/MidiCIDeviceIdentification.cs
  src/CoreMidi/MidiServices.cs
Labels: not-notes-worthy, run-dotnet-tests

#13814 [NET 6 Attribute Conversion] CoreBluetooth
  src/CoreBluetooth/CBManager.cs
  src/CoreBluetooth/CBUUID.cs
Labels: not-notes-worthy, run-dotnet-tests
