Repository dotnet/macios, pull requests merged in 2023-05, with the labels that each got.

#18175 [dotnet] Use the type_map_path arg
  tools/common/Application.cs
  tools/common/Driver.cs
  tools/common/StaticRegistrar.cs
  tools/dotnet-linker/Steps/RegistrarStep.cs
  tools/mmp/driver.cs
  tools/mtouch/BuildTasks.mtouch.cs
Labels: not-notes-worthy, dotnet

#18180 [release/8.0.1xx-preview4] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.
  tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
Labels: backported

#18181 [release/8.0.1xx-preview4] [tests] Find a workaround for #xamarin/maccore@2668.
  tests/common/AppDelegate.cs
Labels: backported

#18177 [release/7.0.2xx] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.
  runtime/runtime.m
Labels: backported

#18221 [release/7.0.2xx-xcode14.3] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: bug, backported

#18216 [Localization] Revert change to non-breaking space
  dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst-view/.template.config/localize/templatestrings.es.json
Labels: not-notes-worthy

#18246 [Foundation] Fix nullability issues in NSUserDefaults. Fixes #18243.
  src/Foundation/NSUserDefaults.cs
  src/foundation.cs
  tests/xtro-sharpie/api-annotations-dotnet/common-Foundation.ignore
  tests/xtro-sharpie/common-Foundation.ignore
Labels: bug

#18241 [Localization] Bring More Translations Manually
  Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Labels: not-notes-worthy

#18247 Fix nullability of WebView.EditingDelegate
  src/webkit.cs
Labels: community

#18254 [autoformat] Fix running sed on Linux.
  msbuild/Xamarin.iOS.Tasks/Tasks/MTouchTaskBase.cs
  tools/autoformat.sh
Labels: skip-all-tests

#18244 [dotnet] Turn class-redirector into a Task
  msbuild/Xamarin.MacDev.Tasks/Tasks/ClassRedirectorTask.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/Rewriter.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/SimpleAssemblyResolver.cs
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  tools/class-redirector/class-redirector/Program.cs
  tools/class-redirector/class-redirector/class-redirector.csproj
Labels: not-notes-worthy, dotnet

#18299 [release/7.0.2xx-xcode14.3] [msbuild] Fix calling the GetFileSystemEntries task on Windows when not connected to a Mac.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: backported

#18303 [release/7.0.2xx-xcode14.3] [runtime] Add support for keeping the same block alive multiple times. Fixes #18161.
  src/ObjCRuntime/Blocks.cs
  src/ObjCRuntime/Runtime.cs
Labels: backported

#18342 [release/7.0.2xx-xcode14.3] [msbuild] Make the GetFileSystemEntries task capable of copying files to the Mac.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks/Tasks/GetFileSystemEntries.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/GetFileSystemEntriesTaskBase.cs
Labels: backported

#18317 [main] Hot Restart fixes
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: not-notes-worthy

#18345 [Localization] Change PAT for automated PRs
  tools/devops/automation/build-lego.yml
Labels: not-notes-worthy

#18125 [docs]Created a doc for preparing an app for TestFlight
  docs/preparing-your-app-for-testflight.md
Labels: documentation

#18370 [release/7.0.2xx-xcode14.3] [dotnet] Add support for asking more of 'open' when launching desktop apps.
  dotnet/Microsoft.MacCatalyst.Sdk/targets/Microsoft.MacCatalyst.Sdk.targets
  dotnet/Microsoft.macOS.Sdk/targets/Microsoft.macOS.Sdk.targets
Labels: backported
