Repository dotnet/macios, pull requests merged in 2023-10, with the labels that each got.

#19129 [xcode14.3] Updating Xamarin.iOS.HotRestart.Client to 1.0.125
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#19130 [release/7.0.3xx] Updating Xamarin.iOS.HotRestart.Client to 1.0.125
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#19128 [net8.0] Updating Xamarin.iOS.HotRestart.Client to 1.0.125
  msbuild/Directory.Build.props
Labels: backported

#19134 [release/7.0.3xx] [dotnet] Link Mono and Xamarin statically in Mac Catalyst by default. Fixes #14686.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/introspection/ApiPInvokeTest.cs
  tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs
Labels: backported

#19153 [release/8.0.1xx] [CI] Ensure we use python 3 before we install the ESRP plugin.
  tools/devops/automation/templates/sign-and-notarized/setup.yml
Labels: backported

#19154 [xcode14.3] [CI] Ensure we use python 3 before we install the ESRP plugin.
  tools/devops/automation/templates/sign-and-notarized/setup.yml
Labels: backported

#19160 [release/8.0.1xx-rc2] [CI] Ensure we use python 3 before we install the ESRP plugin.
  tools/devops/automation/templates/sign-and-notarized/setup.yml
Labels: backported

#19155 [release/7.0.3xx] [CI] Ensure we use python 3 before we install the ESRP plugin.
  tools/devops/automation/templates/sign-and-notarized/setup.yml
Labels: backported

#19166 [release/8.0.1xx] Bump mlaunch to get device support for iOS 17.
  mk/xamarin.mk
Labels: backported

#19168 [release/8.0.1xx-rc2] Bump mlaunch to get device support for iOS 17.
  mk/xamarin.mk
Labels: backported

#19171 [release/8.0.1xx] Revert "[MacCatalyst] Added Default Entitlements for MacCatalyst projects"
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: backported

#19172 [release/8.0.1xx-rc2.1] Revert "[MacCatalyst] Added Default Entitlements for MacCatalyst projects"
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: backported

#19167 [release/8.0.1xx-rc2.1] Bump mlaunch to get device support for iOS 17.
  mk/xamarin.mk
Labels: backported

#19202 [release/8.0.1xx-rc2] [sign] Update SignList to match mlaunch list
  dotnet/Workloads/SignList.xml
Labels: backported

#19203 [release/8.0.1xx] [sign] Update SignList to match mlaunch list
  dotnet/Workloads/SignList.xml
Labels: backported

#19207 [release/8.0.1xx-rc2.1] [sign] Update SignList to match mlaunch list
  dotnet/Workloads/SignList.xml
Labels: backported

#19214 [release/8.0.1xx] [dotnet] Complete support for universal builds when using NativeAOT.
  dotnet/targets/Xamarin.Shared.Sdk.props
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: backported

#19205 Bring changes from Localization branch #20231013.4
  Localize/loc/cs/tools/mtouch/Errors.resx.lcl
  Localize/loc/pl/tools/mtouch/Errors.resx.lcl
  Localize/loc/ru/tools/mtouch/Errors.resx.lcl
  Localize/loc/tr/tools/mtouch/Errors.resx.lcl
Labels: not-notes-worthy

#19218 [release/8.0.1xx-rc2.1] [tests] Implement a workaround for an unreliable url to download a command-line installer for .NET.
  tests/dotnet/Windows/InstallDotNet.csproj
Labels: backported

#19219 [release/7.0.3xx] [tests] Implement a workaround for an unreliable url to download a command-line installer for .NET.
  tests/dotnet/Windows/InstallDotNet.csproj
Labels: backported

#19226 [release/8.0.1xx] [dotnet/msbuild] Create directory in the ILStrip task instead of using MSBuild logic.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/ILStripBase.cs
Labels: backported

#19225 [release/8.0.1xx-rc2.1] [dotnet/msbuild] Create directory in the ILStrip task instead of using MSBuild logic.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/ILStripBase.cs
Labels: backported

#18543 [dotnet] Test integration
  dotnet/targets/Xamarin.Shared.Sdk.targets
  runtime/xamarin/runtime.h
  src/ObjCRuntime/Registrar.cs
  src/ObjCRuntime/Runtime.cs
  tests/dotnet/MyClassRedirectApp/AppDelegate.cs
  tests/dotnet/MyClassRedirectApp/MacCatalyst/Makefile
  tests/dotnet/MyClassRedirectApp/MacCatalyst/MyClassRedirectApp.csproj
  tests/dotnet/MyClassRedirectApp/Makefile
  tests/dotnet/MyClassRedirectApp/iOS/Makefile
  tests/dotnet/MyClassRedirectApp/iOS/MyClassRedirectApp.csproj
  tests/dotnet/MyClassRedirectApp/macOS/Makefile
  tests/dotnet/MyClassRedirectApp/macOS/MyClassRedirectApp.csproj
  tests/dotnet/MyClassRedirectApp/shared.csproj
  tests/dotnet/MyClassRedirectApp/shared.mk
  tests/dotnet/MyClassRedirectApp/tvOS/Makefile
  tests/dotnet/MyClassRedirectApp/tvOS/MyClassRedirectApp.csproj
  tests/dotnet/UnitTests/RegistrarTest.cs
  tools/common/Rewriter.cs
  tools/common/StaticRegistrar.cs
  tools/dotnet-linker/Steps/ClassHandleRewriterStep.cs
Labels: not-notes-worthy, dotnet

#19235 [release/8.0.1xx-rc2.1] [msbuild] Copy the entire frameworks to the Mac when building remotely in the ResolveNativeReferences task. Fixes #19173.
  msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs
Labels: backported

#19234 [release/8.0.1xx] [msbuild] Copy the entire frameworks to the Mac when building remotely in the ResolveNativeReferences task. Fixes #19173.
  msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs
Labels: backported

#19247 Bring changes from Localization branch #20231018.2
  Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Labels: not-notes-worthy

#19252 [release/8.0.1xx-rc2.1] Bump mlaunch to get fix for older devices.
  mk/xamarin.mk
Labels: backported

#19251 [release/8.0.1xx] Bump mlaunch to get fix for older devices.
  mk/xamarin.mk
Labels: backported

#19253 [xcode14.3] Bump mlaunch to get fix for older devices.
  mk/xamarin.mk
Labels: backported

#19250 [release/7.0.3xx] Bump mlaunch to get fix for older devices.
  mk/xamarin.mk
Labels: backported

#19294 [release/7.0.3xx] Bump mlaunch to get resource fix.
  mk/xamarin.mk
Labels: backported

#19292 [release/8.0.1xx] Bump mlaunch to get resource fix.
  mk/xamarin.mk
Labels: backported

#19293 [release/8.0.1xx-rc2.1] Bump mlaunch to get resource fix.
  mk/xamarin.mk
Labels: backported

#19261 Bring changes from Localization branch #20231018.4
  Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Labels: not-notes-worthy

#19267 Bring changes from Localization branch #20231019.4
  Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Labels: not-notes-worthy

#19139 [PassKit] Add support Xcode15 Beta 7
  src/PassKit/PKEnums.cs
  src/PassKit/PKPayLaterView.cs
  src/frameworks.sources
  src/passkit.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/monotouch-test/PassKit/PKPayLaterViewTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-PassKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-PassKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PassKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PassKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-PassKit.todo
  tests/xtro-sharpie/iOS-PassKit.ignore
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/macOS-PassKit.todo
  tests/xtro-sharpie/watchOS-PassKit.todo
Labels: note-highlight

#19295 [xcode14.3] Bump mlaunch to get resource fix.
  mk/xamarin.mk
Labels: backported

#19315 [release/8.0.1xx] [NerabyInteraction] Add support for xcode 15.
  src/NearbyInteraction/Enums.cs
  src/nearbyinteraction.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-NearbyInteraction.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-NearbyInteraction.todo
  tests/xtro-sharpie/iOS-NearbyInteraction.ignore
  tests/xtro-sharpie/iOS-NearbyInteraction.todo
  tests/xtro-sharpie/watchOS-NearbyInteraction.ignore
  tests/xtro-sharpie/watchOS-NearbyInteraction.todo
Labels: backported

#19314 [release/8.0.1xx] [MetalKit] Add support for Xcode 15.
  src/metalkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-MetalKit.todo
  tests/xtro-sharpie/iOS-MetalKit.todo
  tests/xtro-sharpie/macOS-MetalKit.todo
  tests/xtro-sharpie/tvOS-MetalKit.todo
Labels: backported

#19306 [release/8.0.1xx] [PassKit] Add support Xcode15 Beta 7
  src/PassKit/PKEnums.cs
  src/PassKit/PKPayLaterView.cs
  src/frameworks.sources
  src/passkit.cs
  tests/introspection/ApiCtorInitTest.cs
  tests/monotouch-test/PassKit/PKPayLaterViewTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-PassKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-PassKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PassKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-PassKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-PassKit.todo
  tests/xtro-sharpie/iOS-PassKit.ignore
  tests/xtro-sharpie/iOS-PassKit.todo
  tests/xtro-sharpie/macOS-PassKit.todo
  tests/xtro-sharpie/watchOS-PassKit.todo
Labels: note-highlight, backported

#19321 [release/8.0.1xx] [Storekit] Add support for xcode 15.
  src/storekit.cs
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-StoreKit.todo
  tests/xtro-sharpie/tvOS-StoreKit.todo
Labels: backported

#19301 [release/8.0.1xx] [MetalFX] Add the framework (which was added in Xcode 14) and add xcode 15 support.
  src/build/generator-frameworks.g.cs
  src/frameworks.sources
  src/metalfx.cs
  src/rsp/dotnet/ios-defines-dotnet.rsp
  src/rsp/dotnet/macos-defines-dotnet.rsp
  src/rsp/ios-defines.rsp
  src/rsp/macos-defines.rsp
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/ApiTypoTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/mtouch/RegistrarTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalFX.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-MetalFX.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalFX.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-MetalFX.todo
  tests/xtro-sharpie/iOS-MetalFX.ignore
  tests/xtro-sharpie/iOS-MetalFX.todo
  tests/xtro-sharpie/macOS-MetalFX.ignore
  tests/xtro-sharpie/macOS-MetalFX.todo
  tools/common/Frameworks.cs
  tools/linker/ObjCExtensions.cs
Labels: backported

#19313 [release/8.0.1xx] [MacCatalyst] Fix intro failures in catalyst on sonoma.
  src/safariservices.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
Labels: backported

#19325 [msbuild] Look for and copy binding resource packages to the remote Mac in the ResolveNativeReferences task. Fixes #19229.
  msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs
Labels: bug

#19336 [release/8.0.1xx] [msbuild] Don't add frameworks with static libraries to Hot Restart apps.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks/Tasks/FilterStaticFrameworksTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: backported

#19334 [release/8.0.1xx] [msbuild] Look for and copy binding resource packages to the remote Mac in the ResolveNativeReferences task. Fixes #19229.
  msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs
Labels: bug, backported

#19348 [release/8.0.1xx] [maestro] Fix a few issues with the maestro subscriptions.
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  tools/dotnet-linker/dotnet-linker.csproj
Labels: backported

#19346 [release/8.0.1xx] [main] Updated Hot Restart client version
  msbuild/Directory.Build.props
Labels: backported

#19335 [release/8.0.1xx] [msbuild] Copy files to be signed into the correct directory for Hot Restart. Fixes #19278.
  msbuild/Xamarin.iOS.Tasks.Windows/Tasks/ComputeHotRestartBundleContents.cs
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: backported

#19344 [release/8.0.1xx] [UIKit] Add support for Xcode 15.
  src/UIKit/UIEnums.cs
  src/UIKit/UIGraphics.cs
  src/UIKit/UIImage.cs
  src/uikit.cs
  src/xkit.cs
  tests/introspection/iOS/iOSApiProtocolTest.cs
  tests/introspection/iOS/iOSApiSelectorTest.cs
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/iOS-UIKit.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.ignore
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-UIKit.todo
  tests/xtro-sharpie/iOS-UIKit.ignore
  tests/xtro-sharpie/iOS-UIKit.todo
  tests/xtro-sharpie/tvOS-UIKit.ignore
  tests/xtro-sharpie/tvOS-UIKit.todo
  tests/xtro-sharpie/watchOS-UIKit.todo
Labels: backported

#19359 [release/8.0.1xx] [UIKit] Add missing attrs for catalyst.
  src/uikit.cs
Labels: backported

#19340 Bring changes from Localization branch #20231025.9
  Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Labels: not-notes-worthy
