Repository dotnet/macios, pull requests merged in 2023-01, with the labels that each got.

#17071 [dotnet] blitable network pinvokes
  src/Network/NWAdvertiseDescriptor.cs
  src/Network/NWBrowserDescriptor.cs
  src/Network/NWConnection.cs
  src/Network/NWContentContext.cs
  src/Network/NWEndpoint.cs
  src/Network/NWFramerMessage.cs
  src/Network/NWListener.cs
  src/Network/NWPrivacyContext.cs
  src/Network/NWProtocolDefinition.cs
  src/Network/NWProtocolFramerOptions.cs
  src/Network/NWProtocolQuicOptions.cs
  src/Network/NWQuicMetadata.cs
  src/Network/NWTxtRecord.cs
  src/Network/NWWebSocketOptions.cs
  src/Network/NWWebSocketResponse.cs
  src/ObjCRuntime/TransientString.cs
Labels: dotnet

#17135 [dotnet] CoreGraphics convert strings in pinvokes
  src/CoreGraphics/CGContext.cs
  src/CoreGraphics/CGDataProvider.cs
  src/CoreGraphics/CGPDFContentStream.cs
  src/CoreGraphics/CGPDFDictionary.cs
  src/CoreGraphics/CGPDFDocument.cs
  src/CoreGraphics/CGPDFOperatorTable.cs
Labels: dotnet

#17155 [Localization] Change the line endings to use LF instead of CRLF
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.cs.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.de.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.es.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.fr.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.it.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.ja.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.ko.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.pl.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.pt-BR.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.ru.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.tr.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.zh-Hans.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/csharp/.template.config/localize/templatestrings.zh-Hant.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.cs.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.de.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.es.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.fr.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.it.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.ja.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.ko.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.pl.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.pt-BR.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.ru.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.tr.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.zh-Hans.json
  dotnet/Templates/Microsoft.iOS.Templates/ios/fsharp/.template.config/localize/templatestrings.zh-Hant.json
Labels: not-notes-worthy

#17151 [dotnet] replace strings in pinvokes
  src/Security/SecProtocolOptions.cs
Labels: dotnet

#17123 [XKit] Fix creating NSTextLists with custom formats in .NET. Fixes #15766.
  src/xkit.cs
  tests/monotouch-test/Foundation/NSTextListTest.cs
Labels: bug

#17163 Updated MessagingVersion to 1.9.0
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#17143 [dotnet] sanitized pinvokes that use string
  src/CoreFoundation/CFMutableString.cs
  src/CoreFoundation/CFString.cs
  src/CoreFoundation/Dispatch.cs
  src/CoreFoundation/DispatchSource.cs
  src/CoreFoundation/OSLog.cs
Labels: dotnet

#17167 [xcode14.2] Updated MessagingVersion to 1.9.0
  msbuild/Directory.Build.props
Labels: not-notes-worthy, backported

#17164 [xcode14.1] Updated MessagingVersion to 1.9.0
  msbuild/Directory.Build.props
Labels: not-notes-worthy, backported

#17207 Merge main into net8.0.
  NuGet.config
  msbuild/Xamarin.Mac.Tasks/Tasks/Mmp.cs
  msbuild/Xamarin.Mac.Tasks/Tasks/MmpTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/DSymUtilTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  src/AudioToolbox/AudioSessions.cs
  src/AudioToolbox/Enums.cs
  src/AudioUnit/AUEnums.cs
  src/CoreFoundation/CFMutableString.cs
  src/CoreFoundation/CFString.cs
  src/CoreFoundation/Dispatch.cs
  src/CoreFoundation/DispatchSource.cs
  src/CoreFoundation/OSLog.cs
  tests/monotouch-test/Network/NWPathMonitorTest.cs
  tests/xtro-sharpie/Makefile
  tests/xtro-sharpie/Program.cs
  tests/xtro-sharpie/Runner.cs
  tests/xtro-sharpie/xtro-sharpie.csproj
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: not-notes-worthy

#17117 [src/runtime] Fix lookup of RID-specific satellite resources. Fixes #16847.
  runtime/runtime.m
  src/Makefile
  src/ObjCRuntime/Runtime.CoreCLR.cs
  src/ObjCRuntime/TransientString.cs
  tests/monotouch-test/ObjCRuntime/ResourcesTest.cs
  tests/monotouch-test/Resources/Welcome.de.resx
  tests/monotouch-test/Resources/Welcome.en-AU.resx
  tests/monotouch-test/Resources/Welcome.es.resx
  tests/monotouch-test/Resources/Welcome.resx
  tests/monotouch-test/dotnet/shared.csproj
  tests/monotouch-test/monotouch-test.csproj
  tests/xammac_tests/xammac_tests.csproj
  tests/xharness/Jenkins/TestVariationsFactory.cs
Labels: bug

#17230 [release/7.0.2xx] Bump to MSBuild.StructuredLogger v2.1.758.
  tests/bgen/bgen-tests.csproj
  tests/dotnet/UnitTests/DotNetUnitTests.csproj
  tests/generator/generator-tests.csproj
  tests/mmptest/mmptest.csproj
  tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj
  tests/mtouch/mtouchtests.csproj
Labels: backported

#17234 [release/7.0.2xx] [msbuild] Don't process assemblies over and over again in the UnpackLibraryResources target. Fixes #16377.
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: enhancement, backported

#17255 [release/7.0.2xx] [dotnet] Ensure any trimmer components are restored properly.
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: backported

#17254 [release/7.0.1xx-xcode14.2] [dotnet] Ensure any trimmer components are restored properly.
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: backported

#17253 [release/6.0.4xx-xcode14.2] [dotnet] Ensure any trimmer components are restored properly.
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: backported

#17250 [release/6.0.4xx] [dotnet] Ensure any trimmer components are restored properly.
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: backported

#17251 [release/7.0.1xx] [dotnet] Ensure any trimmer components are restored properly.
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: backported

#17252 [release/6.0.4xx-xcode14.1] [dotnet] Ensure any trimmer components are restored properly.
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: backported

#17221 [release/7.0.2xx] Fix libs reidentification deployed in a subdirectory
  builds/create-csproj-for-all-packagereferences.sh
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/AppDelegate.cs
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/MacCatalyst/AppWithNativeDynamicLibrariesInPackageReference.csproj
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/Makefile
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/macOS/AppWithNativeDynamicLibrariesInPackageReference.csproj
  tests/dotnet/AppWithNativeDynamicLibrariesInPackageReference/shared.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/DynamicLibrariesInRuntimesNativeDirectory.csproj
  tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/Makefile
  tests/test-libraries/nugets/DynamicLibrariesInRuntimesNativeDirectory/Xamarin.Tests.DynamicLibrariesInRuntimesNativeDirectory.targets
  tests/test-libraries/nugets/Makefile
Labels: community, backported

#17273 [PushToTalk] Add missing Model attribute to the PTChannelManagerDelegate and PTChannelRestorationDelegate declarations. Fixes #16792.
  src/PushToTalk/Compat.cs
  src/frameworks.sources
  src/generator.cs
  src/pushtotalk.cs
Labels: bug

#17257 [release/7.0.1xx-xcode14.2] [msbuild] Build the solution using .NET instead of msbuild.
  msbuild/Makefile
  msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
Labels: backported

#17258 [release/7.0.2xx] [msbuild] Build the solution using .NET instead of msbuild.
  msbuild/Makefile
  msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
Labels: backported

#17259 [release/6.0.4xx-xcode14.2] [msbuild] Build the solution using .NET instead of msbuild.
  msbuild/Makefile
  msbuild/Messaging/Xamarin.Messaging.Build/Xamarin.Messaging.Build.csproj
Labels: backported

#17335 [release/7.0.1xx-xcode14.2] [system-dependencies] Add diagnostics for duplicate sim download error.
  system-dependencies.sh
Labels: backported

#17336 [release/7.0.2xx] [system-dependencies] Add diagnostics for duplicate sim download error.
  system-dependencies.sh
Labels: backported

#17334 [release/6.0.4xx-xcode14.1] [system-dependencies] Add diagnostics for duplicate sim download error.
  system-dependencies.sh
Labels: backported

#17333 [release/6.0.4xx-xcode14.2] [system-dependencies] Add diagnostics for duplicate sim download error.
  system-dependencies.sh
Labels: backported

#17338 [dotnet] CoreFont delegates
  src/CoreText/CTFontCollection.cs
  src/CoreText/CTFontDescriptor.cs
  src/CoreText/CTRunDelegate.cs
Labels: not-notes-worthy, dotnet

#17345 [CoreAnimation] Add missing CAMetalLayer properties. Fixes #17340.
  src/coreanimation.cs
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreAnimation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/MacCatalyst-CoreAnimation.todo
  tests/xtro-sharpie/api-annotations-dotnet/iOS-CoreAnimation.todo
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreAnimation.ignore
  tests/xtro-sharpie/api-annotations-dotnet/macOS-CoreAnimation.todo
  tests/xtro-sharpie/api-annotations-dotnet/tvOS-CoreAnimation.todo
  tests/xtro-sharpie/iOS-CoreAnimation.todo
  tests/xtro-sharpie/macOS-CoreAnimation.ignore
  tests/xtro-sharpie/macOS-CoreAnimation.todo
  tests/xtro-sharpie/tvOS-CoreAnimation.todo
Labels: bug

#17360 [dotnet] Change the order of the linker steps. Fixes #17347.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: bug

#17198 [release/7.0.1xx] Updated MessagingVersion to 1.9.0
  msbuild/Directory.Build.props
Labels: not-notes-worthy, backported

#17200 [release/6.0.4xx-xcode14.1] Updated MessagingVersion to 1.9.0
  msbuild/Directory.Build.props
Labels: not-notes-worthy, backported

#17363 Updated Xamarin.Messaging to 1.9.5
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#17369 [release/6.0.4xx-xcode14.2] Updated Xamarin.Messaging to 1.9.5
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#17368 [release/7.0.1xx-xcode14.2] Updated Xamarin.Messaging to 1.9.5
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#17364 [xcode14.2] Updated Xamarin.Messaging to 1.9.5
  msbuild/Directory.Build.props
Labels: not-notes-worthy, backported

#17372 [release/7.0.2xx] Updated Xamarin.Messaging to 1.9.5
  msbuild/Directory.Build.props
Labels: not-notes-worthy, backported

#17373 [release/7.0.1xx] Updated Xamarin.Messaging to 1.9.5
  msbuild/Directory.Build.props
Labels: not-notes-worthy, backported

#17388 [dotnet] audiotoolbox blittable pinvokes with delegates
  src/AudioToolbox/AudioConverter.cs
  src/AudioToolbox/AudioFile.cs
  src/AudioToolbox/AudioFileStream.cs
  src/AudioToolbox/AudioQueue.cs
  src/AudioToolbox/MusicSequence.cs
  tests/cecil-tests/BlittablePInvokes.cs
Labels: not-notes-worthy, dotnet
