Repository dotnet/macios, pull requests merged in 2023-08, with the labels that each got.

#18621 [tools] Always link weakly with NewsstandKit. Fixes #18606.
  tools/common/Frameworks.cs
Labels: bug

#18624 [release/7.0.3xx] [tools] Always link weakly with NewsstandKit. Fixes #18606.
  tools/common/Frameworks.cs
Labels: bug, backported

#18625 [xcode14.3] [tools] Always link weakly with NewsstandKit. Fixes #18606.
  tools/common/Frameworks.cs
Labels: bug, backported

#18632 [xcode14.3] [tools] Don't link with NewsstandKit if we're using Xcode 15+.
  tools/common/Frameworks.cs
Labels: backported

#18631 [release/7.0.3xx] [tools] Don't link with NewsstandKit if we're using Xcode 15+.
  tools/common/Frameworks.cs
Labels: backported

#18652 [release/7.0.3xx] [mlaunch] Bump to a version that works with Xcode 15.
  mk/xamarin.mk
Labels: backported

#18653 [xcode14.3] [mlaunch] Bump to a version that works with Xcode 15.
  mk/xamarin.mk
Labels: backported

#18718 [remote] Explicitly import .mobile.props file
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: not-notes-worthy

#18724 [tools] Store list of trampolines even if it's empty. Fixes #18570.
  tools/dotnet-linker/Steps/ManagedRegistrarStep.cs
Labels: bug

#18749 [dotnet] Fix assembly stripping of resource assemblies. Fixes #17262.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: bug

#18831 [xcode14.3] [registrar] Skip registering types removed in Xcode 15.
  tools/common/StaticRegistrar.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
Labels: backported

#18822 [release/8.0.1xx-rc1] [registrar] Skip registering types removed in Xcode 15.
  tools/common/StaticRegistrar.cs
  tools/mtouch/Errors.designer.cs
  tools/mtouch/Errors.resx
Labels: backported

#18669 [MacCatalyst] Added Default Entitlements for MacCatalyst projects
  dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: msbuild, Mac Catalyst

#18842 [xcode14.3] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.
  tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
Labels: backported

#18523 [docs] Document how we plan to do multi targeting.
  docs/multi-target-framework.md
Labels: request-for-comments

#18875 [Localization] Manually bring over lcl files
  Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Labels: not-notes-worthy
