Repository dotnet/macios, pull requests merged in 2023-07, with the labels that each got.

#18560 Fix _DefaultLinkMode for NativeAOT.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: community

#18576 [release/8.0.1xx-preview7] [net8.0] Update dependencies from xamarin/xamarin-macios
  eng/Version.Details.xml
  eng/Versions.props
Labels: backported

#18567 [dotnet][xma] Ensure we don't use DOTNET_ROOT and DOTNET_HOST_PATH in…
  msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
  msbuild/Xamarin.MacDev.Tasks/Extensions/TaskExtensions.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinBuildTask.cs
Labels: not-notes-worthy

#18591 [release/8.0.1xx-preview7] [dotnet][xma] Ensure we don't use DOTNET_ROOT and DOTNET_HOST_PATH in.
  msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
  msbuild/Xamarin.MacDev.Tasks/Extensions/TaskExtensions.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinBuildTask.cs
Labels: not-notes-worthy, backported

#18590 [net8.0] [dotnet][xma] Ensure we don't use DOTNET_ROOT and DOTNET_HOST_PATH in.
  msbuild/Messaging/Xamarin.Messaging.Build/TaskRunner.cs
  msbuild/Xamarin.MacDev.Tasks/Extensions/TaskExtensions.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/BTouchTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeRemoteGeneratorPropertiesTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinBuildTask.cs
Labels: not-notes-worthy, backported
