Repository dotnet/macios, pull requests merged in 2023-04, with the labels that each got.

#17951 [dotnet] preliminary cut for class-redirector
  src/ObjCRuntime/Runtime.cs
  tools/class-redirector/class-redirector-tests/Usings.cs
  tools/class-redirector/class-redirector-tests/XmlTests.cs
  tools/class-redirector/class-redirector-tests/class-redirector-tests.csproj
  tools/class-redirector/class-redirector.sln
  tools/class-redirector/class-redirector/Program.cs
  tools/class-redirector/class-redirector/Rewriter.cs
  tools/class-redirector/class-redirector/SimpleAssemblyResolver.cs
  tools/class-redirector/class-redirector/class-redirector.csproj
  tools/common/CSToObjCMap.cs
  tools/common/ObjCNameIndex.cs
  tools/common/StaticRegistrarFile.cs
Labels: not-notes-worthy

#17963 [Localization] Resolve Merge Conflicts
  Localize/loc/ru/tools/mtouch/Errors.resx.lcl
  Localize/loc/tr/tools/mtouch/Errors.resx.lcl
Labels: not-notes-worthy

#17965 [release/7.0.2xx] Fixed remote and local build issues
  msbuild/Directory.Build.props
Labels: not-notes-worthy, backported

#17968 [release/6.0.4xx-xcode14.3] Fixed remote and local build issues
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: not-notes-worthy, backported

#17967 [release/7.0.2xx-xcode14.3] Fixed remote and local build issues
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: not-notes-worthy, backported

#17964 Fixed remote and local build issues
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: not-notes-worthy

#17966 [xcode14.3] Fixed remote and local build issues
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: not-notes-worthy, backported

#17971 [release/6.0.4xx-xcode14.2] Fixed remote and local build issues
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: not-notes-worthy, backported

#17969 [release/8.0.1xx-preview3] Fixed remote and local build issues
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: not-notes-worthy, backported

#17970 [xcode14.2] Fixed remote and local build issues
  msbuild/Directory.Build.props
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
Labels: not-notes-worthy, backported

#17972 [Localization] Two more merge conflicts to remove
  Localize/loc/ru/tools/mtouch/Errors.resx.lcl
  Localize/loc/tr/tools/mtouch/Errors.resx.lcl
Labels: not-notes-worthy

#17975 [main] Bump .NET 6 versions old-fashioned 🥃
  Make.versions
Labels: backported

#17976 [Localization] Run the OneLoc Task more efficiently
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/templates/loc-translations.yml
Labels: not-notes-worthy

#17989 [xcode14.3] [msbuild] Get RecursiveDir directory name only if it isn't empty
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: backported

#17990 [release/7.0.2xx-xcode14.3] [msbuild] Get RecursiveDir directory name only if it isn't empty
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: backported

#17982 [Localization] Remove Schedule Variables and use displayName
  tools/devops/automation/build-cronjob.yml
  tools/devops/automation/templates/loc-translations.yml
Labels: not-notes-worthy

#18002 [release/6.0.4xx-xcode14.3] Update Messaging and Hot Restart versions
  msbuild/Directory.Build.props
Labels: backported

#18000 [xcode14.3] Update Messaging and Hot Restart versions
  msbuild/Directory.Build.props
Labels: backported

#18001 [release/7.0.2xx-xcode14.3] Update Messaging and Hot Restart versions
  msbuild/Directory.Build.props
Labels: backported

#17999 [Localization] Use backticks and include label and milestone
  tools/devops/automation/build-lego.yml
Labels: not-notes-worthy

#18011 [Foundation] Preserve all members of WrappedNSInputStream. Fixes #15860.
  src/Foundation/NSUrlSessionHandler.cs
Labels: bug

#18020 [release/7.0.2xx-xcode14.3] [Foundation] Preserve all members of WrappedNSInputStream. Fixes #15860.
  src/Foundation/NSUrlSessionHandler.cs
Labels: bug, backported

#18019 [xcode14.3] [Foundation] Preserve all members of WrappedNSInputStream. Fixes #15860.
  src/Foundation/NSUrlSessionHandler.cs
Labels: bug, backported

#18032 [release/7.0.2xx-xcode14.3] [maestro] Make 'Microsoft.NETCore.App.Ref' depend on 'Microsoft.Dotnet.Sdk.Internal'.
  Make.config
  NuGet.config
  builds/Makefile
  builds/package-download/download-packages.csproj
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: backported

#18042 [Localization] Remove BOM
  tools/devops/automation/scripts/localizationBomRemoval.ps1
  tools/devops/automation/templates/loc-translations.yml
Labels: not-notes-worthy

#18046 [bgen] Check for null (no) namespace when matching namespace to framework. Fixes #18025.
  src/bgen/Generator.cs
  tests/generator/BGenTests.cs
  tests/generator/bug18025.cs
Labels: bug

#18056 [release/7.0.2xx-xcode14.3] [runtime] Add support for passing on a connect timeout to sdb.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks/Tasks/CreateDebugConfigurationTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  runtime/monotouch-debug.m
Labels: backported

#17979 [dotnet] Added tests, fixed bugs
  tools/class-redirector/class-redirector-tests/CodeTests.cs
  tools/class-redirector/class-redirector-tests/CompileResult.cs
  tools/class-redirector/class-redirector-tests/Compiler.cs
  tools/class-redirector/class-redirector-tests/XmlTests.cs
  tools/class-redirector/class-redirector-tests/class-redirector-tests.csproj
  tools/class-redirector/class-redirector/Rewriter.cs
Labels: not-notes-worthy, dotnet

#18073 [dotnet] Added one more test to ensure that multiple types in a file work.
  tools/class-redirector/class-redirector-tests/CodeTests.cs
Labels: not-notes-worthy, dotnet

#18066 [release/7.0.2xx-xcode14.3] [tests] Ignore DNS lookup failures in CI.
  tests/common/TestRuntime.cs
Labels: backported

#18069 [xcode14.2] [tests] Ignore DNS lookup failures in CI.
  tests/common/TestRuntime.cs
Labels: backported

#18076 [xcode14.3] [maestro] Make 'Microsoft.NETCore.App.Ref' depend on 'Microsoft.Dotnet.Sdk.Internal'.
  Make.config
  NuGet.config
  builds/Makefile
  builds/package-download/download-packages.csproj
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: backported

#18067 [release/6.0.4xx-xcode14.2] [tests] Ignore DNS lookup failures in CI.
  tests/common/TestRuntime.cs
Labels: backported

#18070 [xcode14.3] [tests] Ignore DNS lookup failures in CI.
  tests/common/TestRuntime.cs
Labels: backported

#18085 [CI] Move the xtro script out of the yaml to make it as small as possible.
  tools/devops/automation/scripts/set_xtro_workloads.ps1
  tools/devops/automation/templates/tests/run-tests.yml
Labels: not-notes-worthy

#18045 [release/6.0.4xx-xcode14.3] [maestro] Make 'Microsoft.NETCore.App.Ref' depend on 'Microsoft.Dotnet.Sdk.Internal'.
  Make.config
  NuGet.config
  builds/Makefile
  builds/package-download/download-packages.csproj
  eng/Version.Details.xml
  eng/Versions.props
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: backported

#17785 [AVFoundation] Fix callback signature for the AVAudioSinkNode constructor. Fixes #17575.
  src/AVFoundation/AVAudioSinkNode.cs
  src/avfoundation.cs
  src/frameworks.sources
  tests/monotouch-test/AVFoundation/AVAudioSinkNodeTest.cs
Labels: bug

#18105 [Localization] Bring over more translations
  Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Labels: not-notes-worthy

#18112 [release/6.0.4xx-xcode14.3] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.
  tests/introspection/ApiTypeTest.cs
Labels: backported

#18108 [release/7.0.2xx] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.
  tests/introspection/ApiTypeTest.cs
Labels: backported

#18107 [release/7.0.2xx-xcode14.3] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.
  tests/introspection/ApiTypeTest.cs
Labels: backported

#18111 [release/7.0.3xx] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.
  tests/introspection/ApiTypeTest.cs
Labels: backported

#18109 [xcode14.3] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.
  tests/introspection/ApiTypeTest.cs
Labels: backported

#18110 [xcode14.2] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.
  tests/introspection/ApiTypeTest.cs
Labels: backported

#18113 [release/6.0.4xx-xcode14.2] [introspection] Ignore the AddressBook namespace for Mac Catalyst when checking static cctors.
  tests/introspection/ApiTypeTest.cs
Labels: backported

#18117 [release/6.0.4xx-xcode14.2] [release/7.0.2xx] [tests] Update introspection to run on latest Ventura version.
  tests/introspection/ApiProtocolTest.cs
  tests/introspection/ApiSelectorTest.cs
Labels: backported

#18118 [AppKit] Add a few missing NullAllowed attributes. Fixes #18115.
  src/appkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/macOS-AppKit.ignore
Labels: bug

#18126 [release/7.0.2xx-xcode14.3] [devops] Ignore any errors when printing the system's .NET version on Windows.
  tools/devops/automation/templates/windows/build.yml
Labels: backported

#18128 [xcode14.3] [devops] Ignore any errors when printing the system's .NET version on Windows.
  tools/devops/automation/templates/windows/build.yml
Labels: backported

#18145 [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: bug

#18123 [Localization] Remove Duplicate Translations
  Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
Labels: not-notes-worthy

#18114 [Localization] Use new custom powershell script for removing BOM - Part 2
  tools/devops/automation/scripts/localizationBomRemoval.ps1
  tools/devops/automation/templates/loc-translations.yml
Labels: not-notes-worthy

#18131 [release/7.0.2xx-xcode14.3] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.
  runtime/runtime.m
Labels: backported

#18132 [release/7.0.3xx] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.
  runtime/runtime.m
Labels: backported

#18133 [release/6.0.4xx-xcode14.3] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.
  runtime/runtime.m
Labels: backported

#18134 [release/6.0.4xx-xcode14.2] [runtime] Always look for dynamic libraries relative to the root directory first. Fixes #xamarin/maccore@2668.
  runtime/runtime.m
Labels: backported

#18151 [release/6.0.4xx-xcode14.3] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: bug, backported

#18149 [release/7.0.2xx] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: bug, backported

#18152 [release/7.0.3xx] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: bug, backported

#18168 [release/6.0.4xx-xcode14.3] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.
  tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
Labels: backported

#18169 [release/6.0.4xx-xcode14.2] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.
  tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
Labels: backported

#18165 [release/7.0.2xx-xcode14.3] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.
  tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
Labels: backported

#18167 [release/7.0.2xx-xcode14.3] [tests] Find a workaround for #xamarin/maccore@2668.
  tests/common/AppDelegate.cs
Labels: backported

#18170 [release/7.0.3xx] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.
  tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
Labels: backported

#18166 [release/7.0.3xx] [tests] Find a workaround for #xamarin/maccore@2668.
  tests/common/AppDelegate.cs
Labels: backported

#18173 [release/7.0.2xx] [tests] Allow a little bit of leeway when testing floating point numbers in SKTransformNodeTest.
  tests/monotouch-test/SpriteKit/SKTransformNodeTest.cs
Labels: backported

#18150 [release/6.0.4xx-xcode14.2] [dotnet] Add a missing IsMacEnabled check before executing a task in the _ComputeLinkerArguments target.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: bug, backported
