Repository dotnet/macios, pull requests merged in 2023-06, with the labels that each got.

#18387 [dotnet] Add to optimizations
  tests/mmptest/src/MMPTest.cs
  tests/mtouch/MTouch.cs
Labels: not-notes-worthy, dotnet

#18412 [dotnet] Set _RequiresILLinkPack=true so that we always restore the ILLink package.
  dotnet/targets/Xamarin.Shared.Sdk.props
Labels: backported

#18431 [release/8.0.1xx-preview5] Update Messaging and System.Diagnostics.Tracer versions
  msbuild/Directory.Build.props
  msbuild/Makefile
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
Labels: backported

#18450 [release/7.0.2xx-xcode14.3] [dotnet] Add a property to opt-out of the _CopyLocalBindingResources logic easily.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: backported

#18454 [release/7.0.2xx-xcode14.3] [msbuild] Copy the zip file back to Windows from the Zip task for remote builds. Fixes #18402.
  msbuild/Xamarin.MacDev.Tasks/Tasks/Zip.cs
Labels: backported

#18451 [release/7.0.2xx-xcode14.3] [dotnet] Add targets to compute mlaunch arguments for installing and launching mobile apps. Fixes #18359.
  dotnet/Microsoft.iOS.Windows.Sdk/targets/Microsoft.iOS.Windows.Sdk.props
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/common/BinLog.cs
  tests/dotnet/UnitTests/MlaunchTest.cs
Labels: backported

#18459 NSUrlSessionHandler should propagate network exceptions
  src/Foundation/NSUrlSessionHandler.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: community

#18456 [dotnet] Integrate class handle rewriting into static registrar process.
  msbuild/Xamarin.MacDev.Tasks/Tasks/ClassRedirectorTask.cs
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
  src/ObjCRuntime/Runtime.cs
  tools/common/Application.cs
  tools/common/CSToObjCMap.cs
  tools/common/Driver.cs
  tools/common/ObjCNameIndex.cs
  tools/common/Rewriter.cs
  tools/common/StaticRegistrar.cs
  tools/dotnet-linker/Steps/RegistrarStep.cs
  tools/dotnet-linker/dotnet-linker.csproj
  tools/mmp/driver.cs
  tools/mmp/mmp.csproj
  tools/mtouch/BuildTasks.mtouch.cs
  tools/mtouch/mtouch.csproj
Labels: not-notes-worthy, dotnet

#18514 Revert "[dotnet] Remove libSystem.Net.Security.Native from tvOS build…
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: community
