Repository dotnet/macios, pull requests merged in 2023-11, with the labels that each got.

#19331 [Generator] Refactor Format Type methods into TypeManager class
  src/bgen/BindingTouch.cs
  src/bgen/Generator.cs
  src/bgen/StringExtensions.cs
  src/bgen/TypeManager.cs
  tests/generator/StringExtensionTests.cs
Labels: generator

#19380 [Generator] Move Type-related methods into Type Manager
  src/bgen/BindingTouch.cs
  src/bgen/Generator.cs
  src/bgen/TypeManager.cs
Labels: generator

#19398 [Generator] Implement TypeCache.
  src/ObjCRuntime/Stret.cs
  src/bgen/AsyncMethodInfo.cs
  src/bgen/AttributeManager.cs
  src/bgen/BindingTouch.cs
  src/bgen/ExtensionMethods.cs
  src/bgen/GeneratedType.cs
  src/bgen/Generator.cs
  src/bgen/MarshalInfo.cs
  src/bgen/MarshalTypeList.cs
  src/bgen/MemberInformation.cs
  src/bgen/TypeCache.cs
  src/bgen/TypeManager.cs
  src/generator.csproj
Labels: generator

#19422 [CI] Readd the statuses for bundle.zip and msbuild.zip
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: pr-change-not-shipping

#19425 [release/8.0.1xx] [CI] Pin the python version to 3.11 until ESRP fixes their deps.
  tools/devops/automation/templates/sign-and-notarized/setup.yml
Labels: backported

#19407 [tools] Don't detect/resolve binding resource packages in mtouch/mmp/dotnet-linker. Fixes #19378.
  tests/mtouch/MTouch.cs
  tools/common/Assembly.cs
Labels: regression

#19428 [Generator] Refactor ReferenceFixer and SearchPathsAssemblyResolver
  src/bgen/BindingTouch.cs
  src/bgen/ReferenceFixer.cs
  src/bgen/SearchPathsAssemblyResolver.cs
  src/generator.csproj
Labels: generator

#19426 [Generator] Do not couple BindingTouch to the TypeCache.
  src/bgen/BindingTouch.cs
  src/bgen/TypeCache.cs
Labels: generator

#19427 [Generator] Remove the BT reference from the NSManager.
  src/bgen/BindingTouch.cs
  src/bgen/NamespaceManager.cs
Labels: generator

#19435 [release/8.0.1xx] Bump api references for .NET 8 and legacy Xamarin.
  Make.config
  tools/apidiff/Makefile
Labels: backported

#19436 [xcode14.3] Bump api references for .NET 8 and legacy Xamarin.
  Make.config
  tools/apidiff/Makefile
Labels: pr-change-not-shipping

#19470 [Generator] TryLoadApi method
  src/bgen/BindingTouch.cs
Labels: generator

#19485 [Generator] Add BindingTouchConfig to BindingTouch
  src/bgen/BindingTouch.cs
  src/bgen/Models/BindingTouchConfig.cs
  src/generator.csproj
Labels: generator

#19476 [release/8.0.1xx] [devops] Set System.Debug to false by default.
  tools/devops/automation/templates/variables.yml
Labels: pr-change-not-shipping, backported

#19463 [release/8.0.1xx] [tools] Don't detect/resolve binding resource packages in mtouch/mmp/dotnet-linker. Fixes #19378.
  tests/mtouch/MTouch.cs
  tools/common/Assembly.cs
Labels: regression, backported

#19486 [release/8.0.1xx] [mmp] Don't run pkg-config when generating partial static registrar code.
  tools/mmp/driver.cs
  tools/mmp/resolver.cs
Labels: pr-change-not-shipping, backported

#19469 [release/8.0.1xx] [UIKit] Store the delegate in a local variable in the UIContextMenuInteraction.
  src/uikit.cs
Labels: backported

#19501 [release/7.0.3xx] [CI] Pin the python version to 3.11 until ESRP fixes their deps.
  tools/devops/automation/templates/sign-and-notarized/setup.yml
Labels: backported
