Repository dotnet/macios, pull requests merged in 2023-03, with the labels that each got.

#17646 [main] Updated Xamarin.Messaging to 1.9.59
  dotnet/Workloads/SignList.xml
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#17647 [xcode14.2] Updated Xamarin.Messaging to 1.9.59
  dotnet/Workloads/SignList.xml
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#17634 [dotnet] mac CoreGraphics pinvokes
  src/CoreGraphics/CGEvent.cs
Labels: not-notes-worthy, dotnet

#17643 [dotnet] security pinvoke and nullable string arrays
  src/ObjCRuntime/TransientString.cs
  src/Security/Authorization.cs
Labels: not-notes-worthy, dotnet

#17639 [AppKit] Make sure NSButtons are treated as toggled objects after setting a field. Fixes #17635.
  src/AppKit/NSButton.cs
  src/appkit.cs
Labels: bug

#17652 [xcode14.2] [Sim] Bump min simulator versions for ventura.
  Make.config
Labels: backported

#17655 [release/7.0.1xx-xcode14.2] [Sim] Bump min simulator versions for ventura.
  Make.config
Labels: backported

#17653 [release/6.0.4xx-xcode14.2] [Sim] Bump min simulator versions for ventura.
  Make.config
Labels: backported

#17661 [release/6.0.4xx-xcode14.2] [CI] The DropsPAT was removed, change it to a new one.
  tools/devops/automation/templates/variables.yml
  tools/devops/automation/templates/windows/build.yml
  tools/devops/automation/templates/windows/reserve-mac.yml
Labels: backported

#17684 [xcode14.2] Added Merq and Merq.Core to ILMerge since they're now required and loaded by Messaging
  msbuild/ILMerge.targets
Labels: not-notes-worthy

#17677 [release/7.0.2xx] [tests] Allow for timeouts in CI in a few tests.
  tests/common/TestRuntime.cs
  tests/linker/mac/LinkAnyTest.cs
  tests/monotouch-test/Foundation/UrlSessionTest.cs
Labels: backported

#17667 [release/7.0.2xx] [tests] Adjust ImageCaptioningTest to skip network-related failures in CI.
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
Labels: backported

#17675 [release/7.0.1xx-xcode14.2] [tests] Allow for timeouts in CI in a few tests.
  tests/common/TestRuntime.cs
  tests/linker/mac/LinkAnyTest.cs
  tests/monotouch-test/Foundation/UrlSessionTest.cs
Labels: backported

#17666 [release/7.0.1xx-xcode14.2] [tests] Adjust ImageCaptioningTest to skip network-related failures in CI.
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
Labels: backported

#17673 [release/6.0.4xx-xcode14.2] [tests] Adjust ImageCaptioningTest to skip network-related failures in CI.
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
Labels: backported

#17676 [xcode14.2] [tests] Allow for timeouts in CI in a few tests.
  tests/common/TestRuntime.cs
  tests/linker/mac/LinkAnyTest.cs
  tests/monotouch-test/Foundation/UrlSessionTest.cs
Labels: backported

#17626 [release/7.0.2xx] Fix WatchKit stub copy error when using native watchOS app
  msbuild/Xamarin.iOS.Tasks/Tasks/ValidateAppBundleTaskBase.cs
  msbuild/Xamarin.iOS.Tasks/Xamarin.iOS.Common.targets
Labels: community, backported

#17674 [release/6.0.4xx-xcode14.2] [tests] Allow for timeouts in CI in a few tests.
  tests/common/TestRuntime.cs
  tests/linker/mac/LinkAnyTest.cs
  tests/monotouch-test/Foundation/UrlSessionTest.cs
Labels: backported

#17662 [xcode14.2] [CI] The DropsPAT was removed, change it to a new one.
  tools/devops/automation/templates/variables.yml
  tools/devops/automation/templates/windows/build.yml
  tools/devops/automation/templates/windows/reserve-mac.yml
Labels: backported

#17651 [release/7.0.2xx] [Sim] Bump min simulator versions for ventura.
  Make.config
Labels: backported

#17689 [xcode14.2] [system-dependencies] Add diagnostics for duplicate sim download error.
  system-dependencies.sh
Labels: backported

#17683 [main] Added Merq and Merq.Core to ILMerge since they're now required and loaded by Messaging
  msbuild/ILMerge.targets
Labels: not-notes-worthy

#17690 [release/8.0.1xx-preview2] [net8.0] Updated Xamarin.Messaging and added Merq to ILMerge
  dotnet/Workloads/SignList.xml
  msbuild/Directory.Build.props
  msbuild/ILMerge.targets
Labels: not-notes-worthy, backported

#17691 [release/6.0.4xx-xcode14.2] Updated Xamarin.Messaging and added Merq to ILMerge
  dotnet/Workloads/SignList.xml
  msbuild/Directory.Build.props
  msbuild/ILMerge.targets
Labels: backported

#17644 [dotnet] AppKit pinvokes
  src/AppKit/NSAccessibility.cs
  src/AppKit/NSApplication.cs
  src/AppKit/NSGraphics.cs
Labels: not-notes-worthy, dotnet

#17704 [net8.0] [CI] Ensure that the condition also include the dependency of the stage.
  tools/devops/automation/templates/release/vs-insertion-prep.yml
Labels: backported

#17706 [release/8.0.1xx-preview2] [Localization] Revert "[CI] Remove the translations from the main stage. (#17453)"
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy, backported

#17694 [xcode14.2] [tests] Adjust ImageCaptioningTest to skip network-related failures in CI.
  tests/monotouch-test/MediaAccessibility/ImageCaptioningTest.cs
Labels: backported

#17698 [dotnet] Darwin p/invokes
  src/Darwin/SystemLog.cs
  tests/cecil-tests/BlittablePInvokes.cs
Labels: not-notes-worthy, dotnet

#17699 [dotnet] Missed a string in the Security pinvoke
  src/Security/Authorization.cs
Labels: not-notes-worthy, dotnet

#17710 [release/7.0.2xx] [xharness] Bump the timeout for the .NET tests.
  tests/xharness/Jenkins/Jenkins.cs
Labels: backported

#17725 [release/8.0.1xx-preview2] [net8.0] [tests] Add a .NET 7 test app.
  dotnet/generate-workloadmanifest-json.csharp
  tests/dotnet/Net7_0SimpleApp/AppDelegate.cs
  tests/dotnet/Net7_0SimpleApp/MacCatalyst/Makefile
  tests/dotnet/Net7_0SimpleApp/MacCatalyst/Net7_0SimpleApp.csproj
  tests/dotnet/Net7_0SimpleApp/Makefile
  tests/dotnet/Net7_0SimpleApp/iOS/Makefile
  tests/dotnet/Net7_0SimpleApp/iOS/Net7_0SimpleApp.csproj
  tests/dotnet/Net7_0SimpleApp/macOS/Makefile
  tests/dotnet/Net7_0SimpleApp/macOS/Net7_0SimpleApp.csproj
  tests/dotnet/Net7_0SimpleApp/shared.csproj
  tests/dotnet/Net7_0SimpleApp/shared.mk
  tests/dotnet/Net7_0SimpleApp/tvOS/Makefile
  tests/dotnet/Net7_0SimpleApp/tvOS/Net7_0SimpleApp.csproj
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: backported

#17723 [dotnet] final blittable pinvoke
  src/Darwin/SystemLog.cs
  tests/cecil-tests/BlittablePInvokes.cs
Labels: not-notes-worthy, dotnet

#17736 [release/7.0.2xx] [dotnet] Add support for passing environment variables and custom arguments when launching apps with mlaunch.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Labels: backported

#17737 [release/7.0.1xx-xcode14.2] [dotnet] Add support for passing environment variables and custom arguments when launching apps with mlaunch.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Labels: backported

#17735 [release/8.0.1xx-preview2] [dotnet] Add support for passing environment variables and custom arguments when launching apps with mlaunch.
  NuGet.config
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Labels: backported

#17739 [dotnet] future proof the test
  tests/cecil-tests/BlittablePInvokes.cs
Labels: not-notes-worthy, dotnet

#17727 [devops] Report the result of the Windows tests as a GitHub comment.
  tools/devops/automation/templates/windows/build.yml
Labels: skip-all-tests, run-windows-tests

#17760 [CI] [siminstaller] Bump bots to use the Ventura and make siminstaller more resilient
  tests/xammac_tests/xammac_tests.csproj
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/main-stage.yml
  tools/devops/automation/templates/tests/stage.yml
  tools/siminstaller/Program.cs
Labels: do-not-merge

#17751 [release/8.0.1xx-preview2] [CI] Allow to debug the env in the upload jobs.
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
Labels: backported

#17779 [AppKit] Add a weakly typed version of NSRulerView.WeakMeasurementUnits. Fixes #17742.
  src/appkit.cs
  tests/introspection/ApiWeakPropertyTest.cs
Labels: bug

#17854 add EditorBrowsable to obsolete member
  src/CoreGraphics/CGEvent.cs
  tests/cecil-tests/ObsoleteTest.cs
Labels: bug, not-notes-worthy

#17835 [msbuild] Verify Mac Catalyst apps like we verify macOS apps. Fixes #17829.
  msbuild/Xamarin.MacDev.Tasks/Tasks/CodesignVerify.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CodesignVerifyTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: bug

#17806 [dotnet/msbuild] Copy binding resource packages to output directories together with CopyLocal assemblies. Fixes #13910.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.MacDev.Tasks/Tasks/GetFileSystemEntriesTaskBase.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/ApiDefinition.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/MacCatalyst/ApiDefinition.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/MacCatalyst/BindingWithUncompressedResourceBundle.csproj
  tests/dotnet/BindingWithUncompressedResourceBundle/MacCatalyst/Makefile
  tests/dotnet/BindingWithUncompressedResourceBundle/MacCatalyst/MyClass.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/MacCatalyst/StructsAndEnums.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/MyClass.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/StructsAndEnums.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/iOS/ApiDefinition.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/iOS/BindingWithUncompressedResourceBundle.csproj
  tests/dotnet/BindingWithUncompressedResourceBundle/iOS/Makefile
  tests/dotnet/BindingWithUncompressedResourceBundle/iOS/MyClass.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/iOS/StructsAndEnums.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/macOS/ApiDefinition.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/macOS/BindingWithUncompressedResourceBundle.csproj
  tests/dotnet/BindingWithUncompressedResourceBundle/macOS/Makefile
  tests/dotnet/BindingWithUncompressedResourceBundle/macOS/MyClass.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/macOS/StructsAndEnums.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/shared.csproj
  tests/dotnet/BindingWithUncompressedResourceBundle/shared.mk
  tests/dotnet/BindingWithUncompressedResourceBundle/tvOS/ApiDefinition.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/tvOS/BindingWithUncompressedResourceBundle.csproj
  tests/dotnet/BindingWithUncompressedResourceBundle/tvOS/Makefile
  tests/dotnet/BindingWithUncompressedResourceBundle/tvOS/MyClass.cs
  tests/dotnet/BindingWithUncompressedResourceBundle/tvOS/StructsAndEnums.cs
  tests/dotnet/LibraryReferencingBindingLibrary/Library.cs
  tests/dotnet/LibraryReferencingBindingLibrary/MacCatalyst/LibraryReferencingBindingLibrary.csproj
  tests/dotnet/LibraryReferencingBindingLibrary/MacCatalyst/Makefile
  tests/dotnet/LibraryReferencingBindingLibrary/Makefile
  tests/dotnet/LibraryReferencingBindingLibrary/iOS/LibraryReferencingBindingLibrary.csproj
  tests/dotnet/LibraryReferencingBindingLibrary/iOS/Makefile
  tests/dotnet/LibraryReferencingBindingLibrary/macOS/LibraryReferencingBindingLibrary.csproj
  tests/dotnet/LibraryReferencingBindingLibrary/macOS/Makefile
  tests/dotnet/LibraryReferencingBindingLibrary/shared.csproj
  tests/dotnet/LibraryReferencingBindingLibrary/shared.mk
  tests/dotnet/LibraryReferencingBindingLibrary/tvOS/LibraryReferencingBindingLibrary.csproj
  tests/dotnet/LibraryReferencingBindingLibrary/tvOS/Makefile
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: bug

#17867 [release/7.0.2xx] [msbuild] Verify Mac Catalyst apps like we verify macOS apps. Fixes #17829.
  msbuild/Xamarin.MacDev.Tasks/Tasks/CodesignVerify.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CodesignVerifyTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: bug, backported

#17869 [release/7.0.1xx-xcode14.2] [msbuild] Verify Mac Catalyst apps like we verify macOS apps. Fixes #17829.
  msbuild/Xamarin.MacDev.Tasks/Tasks/CodesignVerify.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CodesignVerifyTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: bug, backported

#17881 [release/8.0.1xx-preview3] [dotnet] Add support for setting an MSBuild property to pass additional mlaunch arguments.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: backported

#17886 [release/8.0.1xx-preview3] [msbuild] Always pass --wait-for-exit:<value> to mlaunch.
  msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Labels: backported

#17853 [Localization] New Pipeline to replace github action - not from fork
  tools/devops/automation/build-lego.yml
Labels: not-notes-worthy

#17891 [Localization] Remove the loc parameter from main-stage.yml
  tools/devops/automation/templates/main-stage.yml
Labels: not-notes-worthy

#17905 [release/8.0.1xx-preview3] [CI] Fix GitHub ssh host key
  tools/devops/automation/templates/common/setup.yml
Labels: backported

#17906 [release/7.0.1xx-xcode14.2] [CI] Fix GitHub ssh host key
  tools/devops/automation/templates/common/setup.yml
Labels: backported

#17904 [release/6.0.4xx-xcode14.2] [CI] Fix GitHub ssh host key
  tools/devops/automation/templates/common/setup.yml
Labels: backported

#17903 [xcode14.2] [CI] Fix GitHub ssh host key
  tools/devops/automation/templates/common/setup.yml
Labels: backported

#17907 [release/7.0.2xx] [CI] Fix GitHub ssh host key
  tools/devops/automation/templates/common/setup.yml
Labels: backported

#17911 [release/8.0.1xx-preview3] Bump maccore.
  mk/xamarin.mk
Labels: backported

#17910 [release/7.0.2xx] Bump maccore.
  mk/xamarin.mk
Labels: backported

#17921 [release/8.0.1xx-preview3] [vs-workload] Update VS Component versions
  dotnet/Makefile
Labels: backported

#17935 [release/6.0.4xx-xcode14.2] Updated Xamarin.Messaging to 1.9.94
  msbuild/Directory.Build.props
  msbuild/ILMerge.targets
Labels: not-notes-worthy, backported

#17936 [release/7.0.2xx] Updated Xamarin.Messaging to 1.9.94
  msbuild/Directory.Build.props
  msbuild/ILMerge.targets
Labels: not-notes-worthy, backported

#17937 [release/8.0.1xx-preview3] Updated Xamarin.Messaging to 1.9.94
  msbuild/Directory.Build.props
  msbuild/ILMerge.targets
Labels: not-notes-worthy, backported

#17925 Updated Xamarin.Messaging to 1.9.94
  msbuild/Directory.Build.props
  msbuild/ILMerge.targets
Labels: not-notes-worthy

#17938 [xcode14.2] Updated Xamarin.Messaging to 1.9.94
  msbuild/Directory.Build.props
  msbuild/ILMerge.targets
Labels: not-notes-worthy, backported

#17950 [release/7.0.2xx] [msbuild] Always pass --wait-for-exit:<value> to mlaunch.
  msbuild/Xamarin.iOS.Tasks/Tasks/GetMlaunchArgumentsTaskBase.cs
Labels: backported

#17957 [main] Bump .NET 6 versions old-fashioned 🥃
  Make.versions
Labels: backported

#17956 [release/6.0.4xx-xcode14.3] Bump to stable Xcode 14.3
  Make.config
Labels: backported

#17955 [release/7.0.2xx-xcode14.3] Bump to stable Xcode 14.3
  Make.config
Labels: backported

#17954 [xcode14.3] Bump to stable Xcode 14.3
  Make.config
Labels: backported
