Repository dotnet/macios, pull requests merged in 2024-01, with the labels that each got.

#18981 Fix sending MidiPacket when MidiPacket has been created using a point…
  src/CoreMidi/MidiServices.cs
  tests/monotouch-test/CoreMidi/MidiClientTest.cs
Labels: community

#19714 [release/8.0.1xx] [dotnet] Call the _CreateAssetPackManifest target during the build. Fixes #19669.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: backported

#19731 [release/8.0.1xx-xcode15.1] [AppKit] Fix binding for NSFontDescriptor.Create. Fixes #19659.
  src/appkit.cs
Labels: backported

#19732 [release/8.0.1xx-xcode15.1] [AppKit] Implement the NSUserInterfaceItemSearching protocol. Fixes #19649.
  src/appkit.cs
  tests/xtro-sharpie/api-annotations-dotnet/macOS-AppKit.ignore
  tests/xtro-sharpie/common-AppKit.ignore
Labels: backported

#19716 [release/8.0.1xx] Fix sending MidiPacket when MidiPacket has been created using a point.
  src/CoreMidi/MidiServices.cs
  tests/monotouch-test/CoreMidi/MidiClientTest.cs
Labels: community, backported

#19635 More methods extracted in BindingTouch [Generator]
  src/bgen/BindingTouch.cs
  src/bgen/Models/BindingTouchConfig.cs
Labels: generator

#19863 [release/8.0.1xx-xcode15.1] [CI] Ensure that we use the upload prefix for the config file.
  tools/devops/automation/templates/windows/build.yml
Labels: backported

#19851 [xma] Updated Xamarin.Messaging
  msbuild/Directory.Build.props
  msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Copy.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileSceneKitAssetsTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/DittoTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/SmartCopy.cs
  msbuild/Xamarin.iOS.Tasks/Tasks/FindWatchOS2AppBundleTaskBase.cs
Labels: not-notes-worthy

#19867 [release/8.0.1xx-xcode15.1] [CI] Make the timeout to be closer to reality.
  tools/devops/automation/templates/build/build.yml
Labels: backported

#19871 Avoid passing null to TaskRunner.FixReferencedItems
  msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Copy.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileSceneKitAssetsTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/SmartCopyTaskBase.cs
Labels: not-notes-worthy

#19898 [release/8.0.1xx-xcode15.1] [CI] Use the prefix in the artifact name, not the file.
  tools/devops/automation/templates/windows/build.yml
Labels: backported

#19892 [release/8.0.1xx-xcode15.1] Add config stage for CI
  configure
  tools/devops/automation/templates/build/api-diff-stage.yml
  tools/devops/automation/templates/build/build-mac-tests-stage.yml
  tools/devops/automation/templates/build/build-stage.yml
  tools/devops/automation/templates/main-stage.yml
Labels: backported

#19930 [release/8.0.1xx-xcode15.1] [msbuild] Take the CustomEntitlements item group into account in DetectSigningIdentity.
  msbuild/Xamarin.MacDev.Tasks/Tasks/DetectSigningIdentityTaskBase.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/DetectSigningIdentityTaskTests.cs
Labels: backported

#19929 [release/8.0.1xx-xcode15.1] [tests] Disable the BCL tests by default.
  tests/Makefile
  tools/devops/automation/templates/main-stage.yml
Labels: pr-change-not-shipping

#19943 [release/8.0.1xx-xcode15.1] [msbuild] Correctly add custom entitlements to the archived entitlements.
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlementsTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs
Labels: backported

#19955 [release/8.0.1xx-xcode15.1] [msbuild] Process custom entitlements as if they came from an Entitlements.plist file.
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileEntitlementsTaskBase.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/CompileEntitlementsTaskTests.cs
Labels: backported

#19970 [release/8.0.1xx] GITHUB_TOKEN read-only change: Include permissions block
  .github/workflows/backport-trigger.yml
Labels: pr-change-not-shipping, backported

#19971 [release/8.0.1xx-xcode15.1] GITHUB_TOKEN read-only change: Include permissions block
  .github/workflows/backport-trigger.yml
Labels: backported
