Repository dotnet/macios, pull requests merged in 2024-12, with the labels that each got.

#21778 [runtime] Call mono_debugger_agent_unhandled_exception when an exception is marshalled.
  runtime/exports.t4
  runtime/runtime.m
Labels: notes-mention

#21767 [xma] Updated Xamarin.Messaging to 3.0.13
  dotnet/Workloads/SignList.xml
  msbuild/Directory.Build.props
  msbuild/ILMerge.targets
  msbuild/Messaging/Xamarin.Messaging.Build/App.config
  msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Exec.cs
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
Labels: not-notes-worthy

#21819 [src] Fix duplicate availability attributes.
  src/ObjCRuntime/PlatformAvailability.cs
  src/ObjCRuntime/PlatformAvailability2.cs
  src/ObjCRuntime/PlatformAvailabilityShadow.cs
  src/bgen/Attributes.cs
  src/browserenginekit.cs
  src/corelocation.cs
  src/coremotion.cs
  src/mapkit.cs
  src/metal.cs
  src/networkextension.cs
  src/pdfkit.cs
  src/social.cs
  src/uikit.cs
Labels: notes-mention

#21839 [release/9.0.1xx] [xma] Updated Xamarin.Messaging to 3.0.13
  dotnet/Workloads/SignList.xml
  msbuild/Directory.Build.props
  msbuild/ILMerge.targets
  msbuild/Messaging/Xamarin.Messaging.Build/App.config
  msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Exec.cs
  msbuild/Xamarin.MacDev.Tasks/Xamarin.MacDev.Tasks.csproj
Labels: not-notes-worthy, backported

#21661 [dotnet] Disable dedup optimization if we're interpreting every assembly.
  dotnet/targets/Xamarin.Shared.Sdk.targets
Labels: notes-mention
