Repository dotnet/macios, pull requests merged in 2024-10, with the labels that each got.

#21359 [release/8.0.1xx-xcode16.0] [dotnet] Don't link with BrowserEngineKit. Fixes #21324.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  tests/dotnet/UnitTests/ProjectTest.cs
  tests/introspection/dotnet/iOS/introspection.csproj
  tests/introspection/dotnet/macOS/introspection.csproj
  tests/introspection/dotnet/tvOS/introspection.csproj
Labels: backported

#21403 [tests] Ignore a few tests that fail on iOS Simulator/arm64.
  tests/monotouch-test/ObjCRuntime/RegistrarTestGenerated.cs
Labels: test-only-issue

#21340 [net9.0] Bump maccore.
  mk/xamarin.mk
Labels: backported

#21420 [net9.0] [dotnet] Fix building universal apps using NativeAOT when the default RuntimeIdentifiers value is set. Fixes #19391.
  dotnet/targets/Xamarin.Shared.Sdk.props
  tests/dotnet/UnitTests/ProjectTest.cs
Labels: backported

#21438 [main] [nuget-msi-convert] Support improved VS component IDs
  dotnet/generate-vs-workload.csharp
Labels: backported

#21477 [net9.0] [nuget-msi-convert] Do not use new VS component IDs
  dotnet/generate-vs-workload.csharp
Labels: backported

#21461 [net10.0] Trim by default (SdkOnly) when building for arm64. Fixes #21444.
  dotnet/targets/Xamarin.Shared.Sdk.Trimming.props
  tests/dotnet/AppWithXCFrameworkWithStaticLibraryInPackageReference/shared.csproj
  tests/dotnet/UnitTests/BundleStructureTest.cs
Labels: notes-mention

#21507 [release/8.0.1xx-xcode16.0] [msbuild] Fix: `Assembly.GetManifestResourceNames()` may return an empty string
  msbuild/Xamarin.MacDev.Tasks/Tasks/UnpackLibraryResources.cs
Labels: community, backported

#21521 Update Xamarin.Messaging to 2.2.10
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#21551 [release/9.0.1xx] Bump mlaunch.
  mk/xamarin.mk
Labels: backported
