Repository dotnet/macios, pull requests merged in 2024-02, with the labels that each got.

#20000 [release/9.0.1xx-preview1] [devops] Don't validate legacy package links if legacy is disabled.
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: backported

#20002 [release/8.0.1xx-xcode15.1] [devops] Don't validate legacy package links if legacy is disabled.
  tools/devops/automation/templates/sign-and-notarized/funnel.yml
  tools/devops/automation/templates/sign-and-notarized/upload-azure.yml
Labels: backported

#20023 [release/7.0.3xx] Avoid passing null to TaskRunner.FixReferencedItems
  msbuild/Xamarin.MacDev.Tasks/MsBuildTasks/Copy.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/CompileSceneKitAssetsTaskBase.cs
  msbuild/Xamarin.MacDev.Tasks/Tasks/SmartCopyTaskBase.cs
Labels: backported

#19990 [dotnet] Don't build library projects multiple times for universal apps.
  dotnet/targets/Xamarin.Shared.Sdk.targets
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
Labels: performance

#19855 [CI] Update bots to use macOS 14 Sonoma
  tools/devops/automation/build-pipeline.yml
  tools/devops/automation/build-pull-request.yml
Labels: do-not-merge

#20091 [release/8.0.1xx-xcode15.1] [devops] Remove the Whitesource task.
  tools/devops/automation/templates/governance-checks.yml
Labels: backported

#20087 [release/7.0.3xx] [actions] Fix permissions for the global.json action after default credential change.
  .github/workflows/bump-global-json.yml
Labels: backported

#20086 [release/8.0.1xx-xcode15.1] [actions] Fix permissions for the global.json action after default credential change.
  .github/workflows/bump-global-json.yml
Labels: backported

#20085 [release/8.0.1xx-xcode15.1] [actions] Fix permissions for the changelog action after default permissions change.
  .github/workflows/maestro-changelog.yml
Labels: backported

#20096 [release/9.0.1xx-preview1] [devops] Remove the Whitesource task.
  tools/devops/automation/templates/governance-checks.yml
Labels: backported

#20103 Update AOTCompile task to handle cycles in up-to-date check
  Localize/loc/cs/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/de/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/es/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/fr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/it/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ja/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ko/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pl/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/pt-BR/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/ru/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/tr/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hans/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  Localize/loc/zh-Hant/msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx.lcl
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.cs.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.de.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.es.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.fr.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.it.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ja.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ko.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pl.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.pt-BR.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.ru.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.tr.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hans.resx
  msbuild/Xamarin.Localization.MSBuild/TranslatedAssemblies/MSBStrings.zh-Hant.resx
  msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompile.cs
Labels: community

#16341 NSUrlSessionHandler: Rewind request content to the start before sending
  src/Foundation/NSUrlSessionHandler.cs
  tests/monotouch-test/System.Net.Http/MessageHandlers.cs
Labels: bug, community
