Repository dotnet/macios, pull requests merged in 2025-01, with the labels that each got.

#21891 [release/9.0.1xx] [ObjCRuntime] Ensure all assemblies' module constructors have executed before failing registrar lookup.
  src/ObjCRuntime/RegistrarHelper.cs
Labels: backported

#21877 [msbuild] Show an error if an app tries to link with a static library when building for Hot Restart.
  docs/building-apps/build-properties.md
  msbuild/Xamarin.Localization.MSBuild/MSBStrings.resx
  msbuild/Xamarin.MacDev.Tasks/Tasks/ValidateNoStaticLibraries.cs
  msbuild/Xamarin.Shared/Xamarin.Shared.targets
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
  tests/dotnet/BundleStructure/shared.csproj
  tests/dotnet/UnitTests/WindowsTest.cs
  tests/msbuild/Xamarin.MacDev.Tasks.Tests/TaskTests/ValidateNoStaticLibraresTests.cs
  tools/common/MachO.cs
Labels: notes-mention

#21965 [release/8.0.1xx-xcode16.0] [tests] Update the default simulator name for iOS.
  tests/dotnet/UnitTests/MlaunchTest.cs
Labels: pr-change-not-shipping

#21964 [release/8.0.1xx-xcode16.0] [tests] Ignore a few tests that fail on desktop/arm64.
  tests/monotouch-test/ObjCRuntime/RegistrarTestGenerated.cs
Labels: pr-change-not-shipping

#21980 [Rgen] Add a binding syntax factory that will generate C# expressions.
  src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs
  src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Runtime.cs
  src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs
  tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/BindingSyntaxFactoryTests.cs
Labels: actions-disable-autoformat

#21937 Update HotRestart.Client to 17.14.51-gd03e25086a
  msbuild/Directory.Build.props
Labels: not-notes-worthy

#22029 [Rgen] Add the needed code to make the objc_msgSend signatures.
  src/rgen/Microsoft.Macios.Generator/Attributes/MarshalDirective.cs
  src/rgen/Microsoft.Macios.Generator/DataModel/Property.cs
  src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.Generator.cs
  src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfo.cs
  src/rgen/Microsoft.Macios.Generator/DataModel/TypeInfoComparer.cs
  src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.Dlfcn.cs
  src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.ObjCRuntime.cs
  src/rgen/Microsoft.Macios.Generator/Emitters/BindingSyntaxFactory.cs
  src/rgen/Microsoft.Macios.Generator/Extensions/EnumExtensions.cs
  src/rgen/Microsoft.Macios.Generator/Extensions/SpecialTypeExtensions.cs
  src/rgen/Microsoft.Macios.Generator/Formatters/ParameterFormatter.cs
  src/rgen/Microsoft.Macios.Generator/Formatters/TypeInfoFormatter.cs
  src/rgen/Microsoft.Macios.Transformer/Microsoft.Macios.Transformer.csproj
  tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoComparerTests.cs
  tests/rgen/Microsoft.Macios.Generator.Tests/DataModel/TypeInfoToMarshallTypeTests.cs
  tests/rgen/Microsoft.Macios.Generator.Tests/Emitters/GetObjCMessageSendMethodNameTests.cs
  tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/EnumExtensionTests.cs
  tests/rgen/Microsoft.Macios.Generator.Tests/TestDataFactory.cs
Labels: actions-disable-autoformat

#22037 [RGen] Add a roslyn based implementation of the GetValueTypeSize.
  src/ObjCRuntime/Stret.cs
  src/rgen/Microsoft.Macios.Generator/Extensions/TypeSymbolExtensions.Core.cs
  tests/rgen/Microsoft.Macios.Generator.Tests/Extensions/TypeSymbolExtensionsSizeTests.cs
Labels: actions-disable-autoformat

#22034 [release/9.0.1xx] Update Hot Restart Client to 17.14.83-g77e8f56103
  msbuild/Directory.Build.props
  msbuild/Makefile
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
Labels: not-notes-worthy

#22033 Update Hot Restart Client to 17.14.83-g77e8f56103
  msbuild/Directory.Build.props
  msbuild/Makefile
  msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj
Labels: not-notes-worthy
